### ISSUE TITLE
Duplicated line when saving

### ISSUE THREAD

**Issue by vpenando** [golang/vscode-go#1003]
**Configuration**
* Go version: `go1.15.5 windows/amd64`
* Gopls version: `golang.org/x/tools/gopls v0.5.4`
* VSCode version: `1.51.1 e5a624b788d92b8d34d1392e4c4d9789406efe8f x64`
* Windows version: Windows 7 Professional

**Describe the bug**
When saving, the current line is duplicated. It gets duplicated two times if I save again, then three, then four...

**Steps to reproduce the behavior:**
Edit then save a file that belongs to a `replace`d module in `go.mod`. (`replace github.com/path/to/module => ./module`)
However, it looks fine if I disable the extension or set `go.useLanguageServer` to `false`  in `settings.json`.

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.5, and that bug should be fixed in that version. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by vpenando** [comment]
Thank you for your reply. I've updated `gopls` to `v0.5.5` and it looks OK now.

Thanks!
