### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by wgbbiao** [golang/vscode-go#1004]
gopls version: v0.5.5
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: no snapshot assigned for files [file:///Users/guangbiaowu/go/pkg/mod/github.com/kataras/iris/v12@v12.2.0-alpha.0.20201204104853-3e86301b7a75/iris.go]

goroutine 87 [running]:
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles(0xc00013c2a0, 0x1b5c100, 0xc000374090, 0xc00019afa0, 0x1, 0x1, 0x0, 0x0, 0x0)
	  text_synchronization.go:234  0xd97
golang.org/x/tools/internal/lsp.(*Server).didOpen(0xc00013c2a0, 0x1b5c100, 0xc000374090, 0xc00036d040, 0x0, 0xc000196420)
	  text_synchronization.go:92  0x201
golang.org/x/tools/internal/lsp.(*Server).DidOpen(0xc00013c2a0, 0x1b5c100, 0xc000374090, 0xc00036d040, 0xc00036d040, 0x0)
	  server_gen.go:56  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1b5c100, 0xc000374090, 0x1b7c380, 0xc00013c2a0, 0xc00128d170, 0x2799248, 0xc000374030, 0x0, 0x0, 0x0)
	  tsserver.go:112  0x15c7
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1b5c100, 0xc000374090, 0xc00128d170, 0x2799248, 0xc000374030, 0x0, 0xbfeb886cb4eedf70)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1b5c100, 0xc000374090, 0xc00128d170, 0x2799248, 0xc000374030, 0x0, 0x0)
	  lsprpc.go:559  0x44c
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1b5c100, 0xc000374090, 0xc0003782a0, 0x2799248, 0xc000374030, 0x10baf00010ba9, 0x10c4800010c00)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0001c4180, 0xc0003759b0, 0xc0003541c0, 0x1b5c100, 0xc000374090, 0xc0003782a0, 0x2799248, 0xc000374030)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 12:06:21 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@wgbbiao: Would you be able to share the workspace setup that led to this error message? A full `gopls` log would also be very helpful: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.
