### ISSUE TITLE
debugger causes SIGSEGV in my running process

### ISSUE THREAD

**Issue by rayjlinden** [golang/vscode-go#1012]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:
 
- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Go Language Server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.15.6
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- golang.org/x/tools/gopls v0.5.4
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1
- Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rayj/.cache/go-build"
GOENV="/home/rayj/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/var/tmp/rayj/gocode/pkg/mod"
GONOPROXY="github.com/lindenlab/*"
GONOSUMDB="github.com/lindenlab/*"
GOOS="linux"
GOPATH="/var/tmp/rayj/gocode"
GOPRIVATE="github.com/lindenlab/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/rayj/.gvm/gos/go1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/rayj/.gvm/gos/go1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/var/tmp/rayj/gocode/src/github.com/lindenlab/extraction-wallets/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build067185222=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug

I am running a kind of complex set up.  ssh connection from Mac to AWS box.
From there a rather complex docker-compose set up with > 50 containers.
When debugging the container in question I launch like this:
```
    dlv --check-go-version=false --listen=0.0.0.0:54341 --accept-multiclient=true --headless=true --api-version=2  exec --continue /extraction-wallets-api-debug
```

The build happens in a different step - but it is build with proper debug flags (no inlining, etc.)

I had this working on a different container.  One difference is I updated to go1.15.6 and upgraded delve.  But a very similar set up worked for a different container.

In this one however, I am getting a fault when connecting to the container:
```
2020-12-08T00:39:49Z error layer=rpc writing response:write tcp 127.0.0.1:54341->127.0.0.1:35980: use of closed network connection
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x456fae]
```

Port 54341 is mapped from the container to my aws machine.  It is expected as was both passed into the dlv command line and in the launch.json file.  I do not know what port 35980 is for?

In any case, I would not expect it to see the seg fault and I wants to be debugging my code not this...  :)

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
@rayjlinden Can you try to connect to the remote debug server  using the `dlv` cli tool ?  
 `dlv connect 127.0.0.1:54341`.

If it doesn't work, it could be an issue with the dlv or the setup.

If it works with `dlv cli`, the culprit is likely on the extension's debug adapter. If so, can you capture the logs of the headless server & the extension?

For the headless delve server pass, `--log --log-output=rpc` flags and capture the stderr.
For the extension side, add `"trace": "verbose"` in your launch.json and the trace will be on the OUTPUT tab.

**Comment by rayjlinden** [comment]
This problem is weird.  It appears that once every three or so times the debugger connects.  (Though I'm wondering if the longer I wait before connecting if that helps.)

However, when it does connect something is still a miss.  I try to set a break point on a file (that happens to be in a module used by the service not the service itself.)

I get this error in in the debug console:
```
Skipping stop event for breakpoint. The current Go routines is [object Object].
Error on CreateBreakpoint: could not find file /var/tmp/rayj/gocode/pkg/mod/github.com/lindenlab/extraction-utils-go@v1.8.57/controllers/common.go
```

However, that file is reachable both on my AWS machine and in the container.  (The container volume mounts the GOPATH.)

This may not relate to my seg fault problem - but may be a clue as to if I have something not set up right?

**Comment by rayjlinden** [comment]
[dump.txt](https://github.com/golang/vscode-go/files/5663859/dump.txt)
Here is a dump of the longs from the container.  The segfault looks like it happens shortly after break points are attempted to be set.  (Maybe why it does not crash some times if no break points need to be set.)

I should mention that the code I'm wanting to debug is in an included module - not the main code.

**Comment by rayjlinden** [comment]
By setting remotePath: "" and "cwd": "/"  - I got it to stop getting errors about not a valid break point from happening.
However, the segfault still happens as soon as it tries to continue the application.

**Comment by rayjlinden** [comment]
OMG - I think I found the issue.  In the container I had dlv version 1.5.  However, on my AWS linux box it was the older dlv version 1.2.  I upgraded and the segfault is no longer occurring.

(Though that still seems like a bug maybe?)

**Comment by hyangah** [comment]
@rayjlinden glad to hear that you figured out and fixed the problem.
For new Go runtimes, new `dlv` is needed because there could be runtime data structure and logic changes. If `dlv` didn't provide sufficient warnings when you started the headless server, please file an issue in https://github.com/go-delve/delve to see if `dlv` can detect such runtime version issues and warn about it to the users, and ideally from its RPC as well so remote client like our extension can help surfacing the problem in user-friendly way.

Is there anything else this extension can help?

**Comment by hyangah** [comment]
I will close this issue now. @rayjlinden If you still encounter an issue, please file a new issue. Thanks!
