### ISSUE TITLE
tools: replace `go-outline` with `gopls`

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1020]
`go-outline` is no longer used for outline view when language server is enabled.
However, it's still being used by `GoDocumentSymbolProvider` that is used for 
  - generate tests: goGenerateTests.ts
  - references codelens: goReferencesCodelens.ts
  - run test/benchmark codelenses: goRuntestCodelens.ts

They can be replaced with gopls's implementation `LanguageClient.getFeatures("textDocument/documentSymbol")` or with a direct invocation of `vscode.commands.executeCommand('vscode.executeDocumentSymbolProvider', ...)`. 

One difference between the gopls's document symbol provider and `GoDocumentSymbolProvider` is `gopls` version doesn't provide the file's package name info, so we need a different way to find the package name if the info is necessary. See https://github.com/golang/go/issues/40514.

**Comment by qdm12** [comment]
Any update on this one? Can we drop go-outline already if we use `gopls` today? Or is it still needed? Thanks!

**Comment by mihaitodor** [comment]
Would be great to see this one fixed. go-outline doesn't seem to be actively maintained and VS Code has a hard time installing it in some cases: https://github.com/ramya-rao-a/go-outline/issues/15

**Comment by hyangah** [comment]
Gopls issue https://github.com/golang/go/issues/40514 was closed but instead of implementing a variation of `documentSymbol`, gopls implements  [`gopls.list_imports` command](https://go-review.googlesource.com/c/tools/+/383354/3/gopls/doc/commands.md#146) that provides the list of imported packages from the specified file and the package the file belongs to. So, the plan is to combine the usual symbol provider output and the gopls.list_imports output from the extension side.

cc @suzmue @heschi

**Comment by hyangah** [comment]
@suzmue Are we ready to close this?

**Comment by suzmue** [comment]
@hyangah I think we can close this. There is more work we can do to clean up the code when we remove the go-outline code path, but I think for now this is done.

**Comment by suzmue** [comment]
In the next release we will attempt to use gopls if available, but will still recommend installing go-outline as a fallback.
