### ISSUE TITLE
package handling error

### ISSUE THREAD

**Issue by ranon-rat** [golang/vscode-go#1026]
the extension have 2 problems :

1-.sometimes when importing a package it gives an error but when I compile it it runs without problems
2-.sometimes when a library imports a loop happens and I end up importing a package more than 100 times and more 

(sorry if my english is so bad but im not a native speaker)

**Comment by stamblerre** [comment]
Thanks for the report. Can you please provide the following details?

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- <Paste go version here>
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- <Paste gopls version here>
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- <Paste VS Code version here>
- Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
	- <Paste the output here>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
