### ISSUE TITLE
All Go commands fail with `flag provided but not defined: -p`

### ISSUE THREAD

**Issue by tonimelisma** [golang/vscode-go#1029]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go 1.15.6
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- v0.6.0-pre1 and v0.5.5
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.53.0-insider
Commit: 76436a4d43566cd313629799e2ec51b4d00caa64
Date: 2020-12-11T17:46:02.603Z
Electron: 11.0.3
Chrome: 87.0.4280.67
Node.js: 12.18.3
V8: 8.7.220.25-electron.0
OS: Darwin x64 20.1.0
- Check your installed extensions to get the version of the VS Code Go extension
	- v0.19.1 as well as go-nightly v2020.12.814
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/toni/.cache/go-build"
GOENV="/home/toni/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/toni/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/toni/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/toni/sdk/go1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/toni/sdk/go1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/toni/go/src/github.com/davidbyttow/govips/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build840047076=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

"go.formatTool": "goimports",
"go.useLanguageServer": true,
"go.coverageDecorator": {
"type": "gutter"
},
"go.coverOnSingleTest": true,
"go.coverOnSingleTestFile": true,
"go.coverageOptions": "showUncoveredCodeOnly",
### Describe the bug

Since the last few days, after running any Go commands from VS code via Cmnd-P such as Test package or Run debugging, it works for the first 1-2 times that I've started VS code but then I just get:

```
Running tool: /home/toni/sdk/go1.15.6/bin/go test -timeout 180s -coverprofile=/tmp/vscode-goFFx0fV/go-code-cover github.com/davidbyttow/govips/v2/vips

# internal/cpu
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -V	print version and exit
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -gensymabis
    	write symbol ABI information to output file, don't assemble
  -newobj
    	use new object file format
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
# runtime/internal/atomic
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -V	print version and exit
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -gensymabis
    	write symbol ABI information to output file, don't assemble
  -newobj
    	use new object file format
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
# sync/atomic
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -V	print version and exit
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -gensymabis
    	write symbol ABI information to output file, don't assemble
  -newobj
    	use new object file format
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
# runtime/internal/sys
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# internal/race
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# math/bits
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# unicode
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# unicode/utf8
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# encoding
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# container/list
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# crypto/internal/subtle
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# crypto/subtle
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# unicode/utf16
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# internal/nettrace
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# image/color
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# golang.org/x/net/html/atom
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# golang.org/x/text/encoding/internal/identifier
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# golang.org/x/text/internal/utf8internal
compile: version "go1.14.7" does not match go tool version "go1.15.6"
# runtime/cgo
flag provided but not defined: -p
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -V	print version and exit
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -gensymabis
    	write symbol ABI information to output file, don't assemble
  -newobj
    	use new object file format
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
FAIL	github.com/davidbyttow/govips/v2/vips [build failed]
FAIL
```

Running the exact same command `/home/toni/sdk/go1.15.6/bin/go test -timeout 180s -coverprofile=/tmp/vscode-goFFx0fV/go-code-cover github.com/davidbyttow/govips/v2/vips` on the command line works as you'd expect.

**Comment by tonimelisma** [comment]
I tried deleting my whole go1.15.6 installation and reinstalling via VS code, didn't work. Running locate Go tools gives:

`Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/toni/go
GOROOT: /home/toni/sdk/go1.15.6
PATH: /home/toni/sdk/go1.15.6/bin:/home/toni/.vscode-server-insiders/bin/76436a4d43566cd313629799e2ec51b4d00caa64/bin:/home/toni/.local/bin:/home/toni/.vscode-server-insiders/bin/76436a4d43566cd313629799e2ec51b4d00caa64/bin:/home/toni/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/toni/go/bin

   gocode: /home/toni/go/bin/gocode installed
   gopkgs: /home/toni/go/bin/gopkgs installed
   go-outline: /home/toni/go/bin/go-outline installed
   go-symbols: go-symbols not installed
   guru: guru not installed
   gorename: /home/toni/go/bin/gorename installed
   gotests: /home/toni/go/bin/gotests installed
   gomodifytags: gomodifytags not installed
   impl: impl not installed
   fillstruct: fillstruct not installed
   goplay: goplay not installed
   godoctor: godoctor not installed
   dlv: /home/toni/go/bin/dlv installed
   gocode-gomod: /home/toni/go/bin/gocode-gomod installed
   godef: /home/toni/go/bin/godef installed
   goimports: /home/toni/go/bin/goimports installed
   golint: /home/toni/go/bin/golint installed
   gopls: /home/toni/go/bin/gopls installed

go env
Workspace Folder (govips): /home/toni/go/src/github.com/davidbyttow/govips
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/toni/.cache/go-build"
	GOENV="/home/toni/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/toni/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/toni/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/lib/go-1.14"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/toni/go/src/github.com/davidbyttow/govips/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build131589385=/tmp/go-build -gno-record-gcc-switches"`

**Comment by hyangah** [comment]
@tonimelisma thanks - here I see 
```
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
```

I don't know how it ended up there. Can you verify all settings (user level, and workspace level), and contents of `"/home/toni/.config/go/env"`?

**Comment by hyangah** [comment]
And run`Developer: Toggle Developer Tools`, from the 'console', run `process.env['GOROOT']`.

**Comment by hyangah** [comment]
Good that at least there is no `go env -w` setup.

The workspace settings.json is in /home/toni/go/src/github.com/davidbyttow/govips/.vscode/settings.json if exists.

If not, I don't know where else the extension could pick up `/usr/lib/go-1.14` as GOROOT.
BTW disable other extensions during debugging this issue.
 
Sorry for the trouble, but I am really running out of ideas.

Meanwhile, you can try to update your system go version, or try `"go.toolsEnvVars": { "GOROOT": " /home/toni/sdk/go1.15.6" }` as a workaround. The `"go.toolsEnvVars"` setting overrides GOROOT env var when invoking the go tools.

**Comment by tonimelisma** [comment]
I'm doing this remotely to a linux server from my mac - apologies for not mentioning this. So I can't do the workaround as I get loads of errors, because that's an invalid goroot on my mac.

No workspace settings.

Can we classify this as a bug?

**Comment by tonimelisma** [comment]
<img width="451" alt="Screenshot 2020-12-12 at 22 59 10" src="https://user-images.githubusercontent.com/59022391/101994776-ab031400-3ccd-11eb-9784-d618383fc8ef.png">
Here's what I get with the workaround

**Comment by hyangah** [comment]
@tonimelisma That explains why `process.env['GOROOT']` was `undefined`. 

The gopls error message (popup) is confusing. Doesn't `/home/toni/sdk/go1.15.6` exist on the remote host? 
AFAIK the extension and gopls should run on the remote host. 

I want to ask you a couple of things:
1) Run `echo $GOROOT` from the integrated terminal to confirm GOROOT isn't set on the remote host.

2) Enable gopls trace by setting `"go.languageServerFlags: ["-rpc.trace"]` which will show what version of `go` the gopls is picking and what GOROOT it's seeing.

3) Restart the remote vscode server.  From command palette, `Remote-SSH: Kill VS Code Server On Host` command and then reconnect. The remote vscode server is sticky and its environment variable isn't changed. Then, verify whether you are seeing the matched go version from the integrated terminal (the remote host). `go version`

Let me know how it goes. 

Sorry for the trouble but remote setup is a bit less explored path. The ideal setup is still to update the default system go version on the remote machine.



An

**Comment by tonimelisma** [comment]
Thanks @hyangah. Yes, indeed, /home/toni/sdk/go1.15.6 does exist in the remote host. 
1. GOROOT is not set
2. Done
3. Done

I'm confused by the objective being to update the default system go version. I think it would be optimal if the VS code extension used whichever Go version I have chosen.

Restarting the server seems to have solved the issue for now. I'll reopen if it comes back up. Thanks a lot for the help!

**Comment by tonimelisma** [comment]
It's happening again. Just killed the remote VS code server, restarted it, restarted VS code, latest Go, Go nightly extension, goals 0.6.1 etc. Attached is the goals trace.

[gopls_trace.txt](https://github.com/golang/vscode-go/files/5731919/gopls_trace.txt)

**Comment by tonimelisma** [comment]
@hyangah

**Comment by tonimelisma** [comment]
Hey @hyangah I haven't seen engagement on the issue in a week now. Was the provided log enough for information? This breaks most Go functionality in VS code for me.

**Comment by hyangah** [comment]
@tonimelisma Sorry for the slow response - this is the holiday season and most of people are on vacation.

gopls trace shows that the go 1.15.6 (installed in /home/toni/sdk/)  was located correctly and runs as expected. 

I don't know why the go extension picks up go 1.14 directory as GOROOT and GOTOOLDIR only when it runs in `/home/toni/go/src/github.com/davidbyttow/govips` folder.  I couldn't repro with the clean checkout of govips with remote vscode server.  Is there any  `.vscode/settings.json` file? Or do you use any directory-based environment setup (e.g. direnv)?

**Comment by tonimelisma** [comment]
Hey @hyangah the file is empty, no other directory-based environment setup. Apologies for the holidays - didn't come to think of it. Have a great holiday and hope everything is good :)

**Comment by tonimelisma** [comment]
Still seeing the same issue...

**Comment by defihyung** [comment]
I seem to experience the same issue. Have you resolved this @tobiaszheller?

## Setups

- VSC version: 1.54.3
- go version go1.16.2 darwin/amd64
- echo $GOROOT -> is not set
- which go -> /usr/local/go/bin/go

## Steps to reproduce

There is this integration test for a blockchain project called [Cosmos SDK](https://github.com/cosmos/cosmos-sdk), and I am trying to run [this test method](https://github.com/cosmos/cosmos-sdk/blob/v0.42.3/x/staking/client/cli/cli_test.go#L78) in `Visual Studio Code`. It is strange that the test runs well when using `GoLand`.

```
Run test:

Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestIntegrationTestSuite$ -testify.m ^(TestNewCreateValidatorCmd)$ github.com/cosmos/cosmos-sdk/x/staking/client/cli -v
```

## Result

```
flag provided but not defined: -testify.m
Usage of /var/folders/wn/zwc2mf1n61z7sghz9g_1wl8h0000gn/T/go-build3734965414/b001/cli.test:
  -test.bench regexp
    	run only benchmarks matching regexp
  -test.benchmem
    	print memory allocations for benchmarks
  -test.benchtime d
    	run each benchmark for duration d (default 1s)
  -test.blockprofile file
    	write a goroutine blocking profile to file
  -test.blockprofilerate rate
    	set blocking profile rate (see runtime.SetBlockProfileRate) (default 1)
  -test.count n
    	run tests and benchmarks n times (default 1)
  -test.coverprofile file
    	write a coverage profile to file
  -test.cpu list
    	comma-separated list of cpu counts to run each test with
  -test.cpuprofile file
    	write a cpu profile to file
  -test.failfast
    	do not start new tests after the first test failure
  -test.list regexp
    	list tests, examples, and benchmarks matching regexp then exit
  -test.memprofile file
    	write an allocation profile to file
  -test.memprofilerate rate
    	set memory allocation profiling rate (see runtime.MemProfileRate)
  -test.mutexprofile string
    	write a mutex contention profile to the named file after execution
  -test.mutexprofilefraction int
    	if >= 0, calls runtime.SetMutexProfileFraction() (default 1)
  -test.outputdir dir
    	write profiles to dir
  -test.paniconexit0
    	panic on call to os.Exit(0)
  -test.parallel n
    	run at most n tests in parallel (default 16)
  -test.run regexp
    	run only tests and examples matching regexp
  -test.short
    	run smaller test suite to save time
  -test.testlogfile file
    	write test action log to file (for use only by cmd/go)
  -test.timeout d
    	panic test binary after duration d (default 0, timeout disabled)
  -test.trace file
    	write an execution trace to file
  -test.v
    	verbose: print additional output
exit status 2
FAIL	github.com/cosmos/cosmos-sdk/x/staking/client/cli	0.602s
```

## Settings in VSC

```
{
  "editor.snippetSuggestions": "top",
    "go.useLanguageServer": true,
    "[go]": {
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      }
    },
    "[go.mod]": {
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      }
    },
    "gopls": {
      // Add parameter placeholders when completing a function.
      "usePlaceholders": true,
      // If true, enable additional analyses with staticcheck.
      // Warning: This will significantly increase memory usage.
      "staticcheck": false,
      "completeUnimported": true, // autocomplete unimported packages
      "deepCompletion": true // enable deep completion
    },
    "go.testFlags": ["-v"],
    "go.formatTool": "goimports",
    "diffEditor.ignoreTrimWhitespace": true,
    "files.associations": {
      "*.html": "html",
      "*.go": "go"
    },
    "editor.defaultFormatter": "golang.go",
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.quickSuggestions": true,
    "workbench.colorTheme": "Dark-Dracula",
    "go.toolsManagement.autoUpdate": true,
    "go.languageServerFlags": ["-rpc.trace"],
  }
```

**Comment by hyangah** [comment]
@defihyung That looks like a different issue - yours is for `go test` command, and  this issue is more about `go build` even though it was surfaced while running `go test`.  I created #1382. Let's follow up from there.
