### ISSUE TITLE
vscode for go need  refactor feature

### ISSUE THREAD

**Issue by xcrossed** [golang/vscode-go#103]
Hello, first of all, let me say that GoCode is a really cool package and I especially appreciate the support for Delve that it gives me. What would be really nice would be some form of refactoring. Maybe just "Extract Method" to start with as this is probably the most likely refactoring feature to be needed. Alternatively, do you or anyone else know of any Golang refactoring extensions for VS Code?

**Comment by stamblerre** [comment]
Thanks for the kind words!

All feature requests like this will likely be handled through `gopls`, the Go language server (https://golang.org/s/gopls). [This list](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AFeatureRequest+label%3Agopls) contains all of the `gopls` feature requests, and https://github.com/golang/go/issues/38028 and https://github.com/golang/go/issues/37170 seem relevant to your request.
