### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by tonimelisma** [golang/vscode-go#1030]
gopls version: v0.6.0-pre.1
gopls flags: 
extension version: 2020.12.814
environment: Visual Studio Code - Insiders

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Saved my go file, during which gopls crashed

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 11:51:32 PM] 2020/12/12 23:51:32 go env for /home/toni/go/src/github.com/tonimelisma/fastgallery
(root /home/toni/go/src/github.com/tonimelisma/fastgallery)
(go version go version go1.15.6 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOMOD=/home/toni/go/src/github.com/tonimelisma/fastgallery/go.mod
GONOSUMDB=
GOPATH=/home/toni/go
GOPRIVATE=
GO111MODULE=
GOCACHE=/home/toni/.cache/go-build
GONOPROXY=
GOINSECURE=
GOFLAGS=
GOROOT=/home/toni/sdk/go1.15.6
GOSUMDB=sum.golang.org
GOPROXY=https://proxy.golang.org,direct
GOMODCACHE=/home/toni/go/pkg/mod

[Info  - 11:52:45 PM] 2020/12/12 23:52:45 go/packages.Load
	snapshot=0
	directory=/home/toni/go/src/github.com/tonimelisma/fastgallery
	query=[builtin github.com/tonimelisma/fastgallery/...]
	packages=4

[Info  - 11:52:47 PM] 2020/12/12 23:52:47 go env for /home/toni/go/src/github.com/tonimelisma/fastgallery
(root /home/toni/go/src/github.com/tonimelisma/fastgallery)
(go version go version go1.15.6 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOMOD=/home/toni/go/src/github.com/tonimelisma/fastgallery/go.mod
GOPROXY=https://proxy.golang.org,direct
GOSUMDB=sum.golang.org
GOROOT=/home/toni/sdk/go1.15.6
GOMODCACHE=/home/toni/go/pkg/mod
GO111MODULE=
GOCACHE=/home/toni/.cache/go-build
GOPRIVATE=
GONOSUMDB=
GOFLAGS=
GOINSECURE=
GONOPROXY=
GOPATH=/home/toni/go

[Info  - 11:52:47 PM] 2020/12/12 23:52:47 go/packages.Load
	snapshot=0
	directory=/home/toni/go/src/github.com/tonimelisma/fastgallery
	query=[builtin github.com/tonimelisma/fastgallery/...]
	packages=4

[Info  - 12:04:28 AM] 2020/12/13 00:04:28 go env for /home/toni/go/src/github.com/tonimelisma/fastgallery
(root /home/toni/go/src/github.com/tonimelisma/fastgallery)
(go version go version go1.15.6 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOCACHE=/home/toni/.cache/go-build
GOMODCACHE=/home/toni/go/pkg/mod
GOPRIVATE=
GOROOT=/home/toni/sdk/go1.15.6
GONOSUMDB=
GO111MODULE=
GONOPROXY=
GOPROXY=https://proxy.golang.org,direct
GOSUMDB=sum.golang.org
GOFLAGS=
GOINSECURE=
GOMOD=/home/toni/go/src/github.com/tonimelisma/fastgallery/go.mod
GOPATH=/home/toni/go

[Info  - 12:04:28 AM] 2020/12/13 00:04:28 go/packages.Load
	snapshot=0
	directory=/home/toni/go/src/github.com/tonimelisma/fastgallery
	query=[builtin github.com/tonimelisma/fastgallery/...]
	packages=4

[Error - 12:30:21 AM] Starting client failed
Error: Connection got disposed.
	at Object.dispose (/home/toni/.vscode-server-insiders/extensions/golang.go-nightly-2020.12.814/dist/goMain.js:94435:27)
	at Object.dispose (/home/toni/.vscode-server-insiders/extensions/golang.go-nightly-2020.12.814/dist/goMain.js:10515:35)
	at /home/toni/.vscode-server-insiders/extensions/golang.go-nightly-2020.12.814/dist/goMain.js:12693:28
[Info  - 12:30:22 AM] 2020/12/13 00:30:22 go env for /home/toni/go/src/github.com/tonimelisma/fastgallery
(root /home/toni/go/src/github.com/tonimelisma/fastgallery)
(go version go version go1.15.6 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOPATH=/home/toni/go
GOROOT=/home/toni/sdk/go1.15.6
GOMOD=/home/toni/go/src/github.com/tonimelisma/fastgallery/go.mod
GONOPROXY=
GO111MODULE=
GOINSECURE=
GOPROXY=https://proxy.golang.org,direct
GOCACHE=/home/toni/.cache/go-build
GOFLAGS=
GOMODCACHE=/home/toni/go/pkg/mod
GONOSUMDB=
GOPRIVATE=
GOSUMDB=sum.golang.org

[Info  - 12:30:23 AM] 2020/12/13 00:30:23 go/packages.Load
	snapshot=0
	directory=/home/toni/go/src/github.com/tonimelisma/fastgallery
	query=[builtin github.com/tonimelisma/fastgallery/...]
	packages=4

Failed to auto-collect gopls trace: unrecognized crash pattern.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@tonimelisma Thanks for reporting the issue and sharing the trace. 

From the trace, looks like the client's stop was requested while start is in progress. Any settings.json file was saved?
The closest thing I can think of is the bug https://go-review.googlesource.com/c/vscode-go/+/276973 is trying to fix.
golang.go-nightly 2020.12.814 doesn't include the fix yet. 

@tonimelisma if you keep getting the issue after today's nightly version release, can you please enable verbose tracing - by setting `"go.languageServerFlags": ["-rpc.trace"]`? That will show us a bit more details on what happened during the language server restart. Thanks again!

**Comment by tonimelisma** [comment]
Ok. I turned on tracing and will reopen if it repeats.
