### ISSUE TITLE
GOPATH set to GOROOT has no effect

### ISSUE THREAD

**Issue by zhb1207** [golang/vscode-go#1032]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:
 
- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Go Language Server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- <go version go1.13.7 darwin/amd64>
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- <Paste gopls version here>
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- <Paste VS Code version here>
- Check your installed extensions to get the version of the VS Code Go extension
	- <0.19.1>
- Run `go env` to get the go development environment details
	- <GO111MODULE="off"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/xxx/Library/Caches/go-build"
GOENV="/Users/xxx/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/xxx/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.google.cn"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qc/bc2r3xpj7_lcyhjt9h65kkxc0000gn/T/go-build533526213=/tmp/go-build -gno-record-gcc-switches -fno-common">

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
    "go.gopath": "/Users/xxx/go",
    "go.goroot": "/usr/local/go",
    "go.autocompleteUnimportedPackages": true,
    "go.gotoSymbol.includeImports": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.inferGopath": true,
    "go.formatTool": "goimports",
### Describe the bug
Open the go src file(/usr/local/go/src) in vscode, the output shows:
failed to run "/usr/local/go/bin/go version": stdout: go version go1.13.7 darwin/amd64
, stderr: warning: GOPATH set to GOROOT (/usr/local/go) has no effect
and the OUTLINE in the left shows that: No symbols found in document 'xxx'
This issue doesn't happen if I open other repos in golang or open the same repo in other IDE.

### Steps to reproduce the behavior:
1.Open the go src file(/usr/local/go/src) in vscode

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="993" alt="screenshot" src="https://user-images.githubusercontent.com/15380695/102227680-cf0c6280-3f24-11eb-85cb-95b439f21c44.png">

**Comment by hyangah** [comment]
@zhb1207 Please turn off `"go.inferGopath"`. What the setting does is to tell the VS Code Go to treat any directory that contains `/src` directory as `GOPATH`. That's not what you want.
