### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by GeorgeXc** [golang/vscode-go#1035]
gopls version: v0.5.5
gopls flags: server -rpc.trace --debug=localhost:6060

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

always show setting up workspace

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 11:53:06 PM] 2020/12/16 23:53:06 go env for /data/.gvm/pkgsets/go1.13.8/global/src/lc
(root /data/.gvm/pkgsets/go1.13.8/global/src/lc)
(go version go version go1.13.8 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOPATH=/data/.gvm/pkgsets/go1.13.8/global
GOFLAGS=
GOINSECURE=
GOMOD=/data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod
GOPRIVATE=
GO111MODULE=
GOMODCACHE=
GONOSUMDB=
GOSUMDB=sum.golang.org
GOPROXY=https://mirrors.cloud.tencent.com/go/,direct
GOCACHE=/root/.cache/go-build
GOROOT=/data/.gvm/gos/go1.13.8
GONOPROXY=

[Error - 12:07:30 AM] 2020/12/17 00:07:30 initial workspace load failed: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

[Error - 12:07:30 AM] 2020/12/17 00:07:30 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=0
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[builtin lc/...]
	packages=0

[Error - 12:07:30 AM] 2020/12/17 00:07:30 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=0

[Error - 12:07:30 AM] 2020/12/17 00:07:30 starting work for Error loading workspace: Request window/workDoneProgress/create failed with message: Language client is not ready yet

[Error - 12:07:30 AM] 2020/12/17 00:07:30 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=0
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:07:35 AM] 2020/12/17 00:07:35 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=1
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:07:35 AM] 2020/12/17 00:07:35 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:07:35 AM] 2020/12/17 00:07:35 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=1

[Error - 12:07:35 AM] 2020/12/17 00:07:35 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=1
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:08:34 AM] Request textDocument/definition failed.
  Message: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: unrecognized import path "go.etcd.io/etcd/v3" (https fetch: Get https://go.etcd.io/etcd/v3?go-get=1: dial tcp 172.217.24.19:443: i/o timeout)

  Code: 0 
[Error - 12:08:34 AM] 2020/12/17 00:08:34 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: unrecognized import path "go.etcd.io/etcd/v3" (https fetch: Get https://go.etcd.io/etcd/v3?go-get=1: dial tcp 172.217.24.19:443: i/o timeout)

	snapshot=1
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:08:44 AM] 2020/12/17 00:08:44 go/packages.Load: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=2
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:08:44 AM] 2020/12/17 00:08:44 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:08:44 AM] 2020/12/17 00:08:44 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=2

[Error - 12:08:44 AM] 2020/12/17 00:08:44 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=2
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:08:58 AM] 2020/12/17 00:08:58 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=3
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:08:58 AM] 2020/12/17 00:08:58 failed to compute document links: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	URI=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go

[Error - 12:09:19 AM] 2020/12/17 00:09:19 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: unrecognized import path "go.etcd.io/etcd/v3" (https fetch: Get https://go.etcd.io/etcd/v3?go-get=1: dial tcp 172.217.24.19:443: i/o timeout)

	snapshot=3
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:09:19 AM] 2020/12/17 00:09:19 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: unrecognized import path "go.etcd.io/etcd/v3" (https fetch: Get https://go.etcd.io/etcd/v3?go-get=1: dial tcp 172.217.24.19:443: i/o timeout)

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:09:19 AM] 2020/12/17 00:09:19 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=3

[Error - 12:09:19 AM] 2020/12/17 00:09:19 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=3
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:09:33 AM] 2020/12/17 00:09:33 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=3
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:09:33 AM] 2020/12/17 00:09:33 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:09:35 AM] 2020/12/17 00:09:35 go/packages.Load: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=4
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:09:35 AM] 2020/12/17 00:09:35 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:09:35 AM] 2020/12/17 00:09:35 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=4

[Error - 12:09:35 AM] 2020/12/17 00:09:35 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=4
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:09:40 AM] 2020/12/17 00:09:40 go/packages.Load: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=4
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:09:40 AM] 2020/12/17 00:09:40 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:09:49 AM] 2020/12/17 00:09:49 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=5
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:09:49 AM] 2020/12/17 00:09:49 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:09:49 AM] 2020/12/17 00:09:49 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=5

[Error - 12:09:49 AM] 2020/12/17 00:09:49 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=5
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:10:14 AM] 2020/12/17 00:10:14 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=5
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:10:14 AM] 2020/12/17 00:10:14 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:10:20 AM] 2020/12/17 00:10:20 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=6
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:10:20 AM] 2020/12/17 00:10:20 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:10:20 AM] 2020/12/17 00:10:20 warning: diagnose go.mod: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	snapshot=6

[Error - 12:10:20 AM] 2020/12/17 00:10:20 errors diagnosing workspace: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin lc/...]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=6
	directory=file:///data/.gvm/pkgsets/go1.13.8/global/src/lc

[Error - 12:11:18 AM] 2020/12/17 00:11:18 go/packages.Load: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=6
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:11:18 AM] 2020/12/17 00:11:18 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: go [-m -json all]: exit status 1: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

[Error - 12:11:21 AM] 2020/12/17 00:11:21 go/packages.Load: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	snapshot=7
	directory=/data/.gvm/pkgsets/go1.13.8/global/src/lc
	query=[file=/data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]
	packages=0

[Error - 12:11:21 AM] 2020/12/17 00:11:21 reloadOrphanedFiles: failed to load: source error list:
	file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/go.mod:43:1-43:26: err: exit status 1: stderr: go: go.etcd.io/etcd/v3@v3.4.7: go.mod has non-.../v3 module path "go.etcd.io/etcd" (and .../v3/go.mod does not exist) at revision v3.4.7

	query=[file:///data/.gvm/pkgsets/go1.13.8/global/src/lc/lib/resolver/client.go]

gopls: Unknown command server
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

gopls is a Go language server. It is typically used with an editor to provide
language features. When no command is specified, gopls will default to the 'serve'
command. The language features can also be accessed via the gopls command-line interface.

Available commands are:

main:
  serve : run a server for Go code using the Language Server Protocol
  version : print the gopls version information
  bug : report a bug in gopls
  api-json : print json describing gopls API

features:
  call_hierarchy : display selected identifier's call hierarchy
  check : show diagnostic results for the specified file
  definition : show declaration of selected identifier
  folding_ranges : display selected file's folding ranges
  format : format the code according to the go standard
  highlight : display selected identifier's highlights
  implementation : display selected identifier's implementation
  imports : updates import statements
  inspect : inspect server state (daemon mode only)
  links : list links in a file
  prepare_rename : test validity of a rename operation at location
  references : display selected identifier's references
  rename : rename selected identifier
  semtok : show semantic tokens for the specified file
  signature : display selected identifier's signature
  fix : apply suggested fixes
  symbols : display selected file's symbols
  workspace : manage the gopls workspace (experimental: under development)
  workspace_symbol : search symbols in workspace

gopls flags are:
[Info  - 12:11:21 AM] Connection to server got closed. Server will restart.
gopls: Unknown command server
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

gopls is a Go language server. It is typically used with an editor to provide
language features. When no command is specified, gopls will default to the 'serve'
command. The language features can also be accessed via the gopls command-line interface.

Available commands are:

main:
  serve : run a server for Go code using the Language Server Protocol
  version : print the gopls version information
  bug : report a bug in gopls
  api-json : print json describing gopls API

features:
  call_hierarchy : display selected identifier's call hierarchy
  check : show diagnostic results for the specified file
  definition : show declaration of selected identifier
  folding_ranges : display selected file's folding ranges
  format : format the code according to the go standard
  highlight : display selected identifier's highlights
  implementation : display selected identifier's implementation
  imports : updates import statements
  inspect : inspect server state (daemon mode only)
  links : list links in a file
  prepare_rename : test validity of a rename operation at location
  references : display selected identifier's references
  rename : rename selected identifier
  semtok : show semantic tokens for the specified file
  signature : display selected identifier's signature
  fix : apply suggested fixes
  symbols : display selected file's symbols
  workspace : manage the gopls workspace (experimental: under development)
  workspace_symbol : search symbols in workspace

gopls flags are:
[Info  - 12:11:21 AM] Connection to server got closed. Server will restart.
gopls: Unknown command server
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

gopls is a Go language server. It is typically used with an editor to provide
language features. When no command is specified, gopls will default to the 'serve'
command. The language features can also be accessed via the gopls command-line interface.

Available commands are:

main:
  serve : run a server for Go code using the Language Server Protocol
  version : print the gopls version information
  bug : report a bug in gopls
  api-json : print json describing gopls API

features:
  call_hierarchy : display selected identifier's call hierarchy
  check : show diagnostic results for the specified file
  definition : show declaration of selected identifier
  folding_ranges : display selected file's folding ranges
  format : format the code according to the go standard
  highlight : display selected identifier's highlights
  implementation : display selected identifier's implementation
  imports : updates import statements
  inspect : inspect server state (daemon mode only)
  links : list links in a file
  prepare_rename : test validity of a rename operation at location
  references : display selected identifier's references
  rename : rename selected identifier
  semtok : show semantic tokens for the specified file
  signature : display selected identifier's signature
  fix : apply suggested fixes
  symbols : display selected file's symbols
  workspace : manage the gopls workspace (experimental: under development)
  workspace_symbol : search symbols in workspace

gopls flags are:
[Info  - 12:11:21 AM] Connection to server got closed. Server will restart.
gopls: Unknown command server
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

gopls is a Go language server. It is typically used with an editor to provide
language features. When no command is specified, gopls will default to the 'serve'
command. The language features can also be accessed via the gopls command-line interface.

Available commands are:

main:
  serve : run a server for Go code using the Language Server Protocol
  version : print the gopls version information
  bug : report a bug in gopls
  api-json : print json describing gopls API

features:
  call_hierarchy : display selected identifier's call hierarchy
  check : show diagnostic results for the specified file
  definition : show declaration of selected identifier
  folding_ranges : display selected file's folding ranges
  format : format the code according to the go standard
  highlight : display selected identifier's highlights
  implementation : display selected identifier's implementation
  imports : updates import statements
  inspect : inspect server state (daemon mode only)
  links : list links in a file
  prepare_rename : test validity of a rename operation at location
  references : display selected identifier's references
  rename : rename selected identifier
  semtok : show semantic tokens for the specified file
  signature : display selected identifier's signature
  fix : apply suggested fixes
  symbols : display selected file's symbols
  workspace : manage the gopls workspace (experimental: under development)
  workspace_symbol : search symbols in workspace

gopls flags are:
[Info  - 12:11:21 AM] Connection to server got closed. Server will restart.
gopls: Unknown command server
The Go Language source tools.

Usage: gopls [flags] <command> [command-flags] [command-args]

gopls is a Go language server. It is typically used with an editor to provide
language features. When no command is specified, gopls will default to the 'serve'
command. The language features can also be accessed via the gopls command-line interface.

Available commands are:

main:
  serve : run a server for Go code using the Language Server Protocol
  version : print the gopls version information
  bug : report a bug in gopls
  api-json : print json describing gopls API

features:
  call_hierarchy : display selected identifier's call hierarchy
  check : show diagnostic results for the specified file
  definition : show declaration of selected identifier
  folding_ranges : display selected file's folding ranges
  format : format the code according to the go standard
  highlight : display selected identifier's highlights
  implementation : display selected identifier's implementation
  imports : updates import statements
  inspect : inspect server state (daemon mode only)
  links : list links in a file
  prepare_rename : test validity of a rename operation at location
  references : display selected identifier's references
  rename : rename selected identifier
  semtok : show semantic tokens for the specified file
  signature : display selected identifier's signature
  fix : apply suggested fixes
  symbols : display selected file's symbols
  workspace : manage the gopls workspace (experimental: under development)
  workspace_symbol : search symbols in workspace

gopls flags are:
[Error - 12:11:21 AM] Connection to server got closed. Server will not be restarted.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@GeorgeXc  `"go.languageServerFlags"` setting should be `["serve", "-rpc.trace", "--debug=localhost:6060"]` (note `serve` not `server`)
