### ISSUE TITLE
📣 Enable `gopls` by default

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1037]
We plan to enable the language server, [`gopls`](https://github.com/golang/vscode-go/blob/master/docs/gopls.md), by default early next year.

We recommend switching to the language server now (`"go.useLanguageServer": true` in your `settings.json`) to confirm that it works well for you. If you notice bugs or missing features, please [file a new issue](https://github.com/golang/vscode-go/issues/new/choose) and explain the problem.

You can see our progress in this [project dashboard](https://github.com/orgs/golang/projects/3).

**Comment by leafac** [comment]
I arrived here because of the message in the README saying that “the official Go language server is now enabled in VS Code by default.”

Does the official Go language server subsume the **Go for VS Code** extension? Does it still make sense to install the **Go for VS Code** extension?

**Comment by stamblerre** [comment]
Thank you for pointing this out--it should say "in VS Code Go by default". The Go language server is made available through the Go extension, so yes, you do need to install it.

**Comment by leafac** [comment]
Got it. Thanks for helping out a newcomer. 😀
