### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by tonimelisma** [golang/vscode-go#1047]
gopls version: v0.6.1
gopls flags: -rpc.trace
extension version: 2020.12.1703
[gopls_crash.txt](https://github.com/golang/vscode-go/files/5721597/gopls_crash.txt)

environment: Visual Studio Code - Insiders

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Saved the file. goals crashed.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

See attached file.

[gopls_crash.txt](https://github.com/golang/vscode-go/files/5721598/gopls_crash.txt)

**Comment by stamblerre** [comment]
Thank you for sharing this report. It looks like the VS Code Go extension was trying to restart `gopls` and that failed because I don't see a `gopls` stack trace but I do see this:

```
[Error - 12:22:27 AM] Starting client failed
Error: Connection got disposed.
    at Object.dispose (/Users/tonimelisma/.vscode-insiders/extensions/golang.go-nightly-2020.12.1703/dist/goMain.js:94582:27)
    at Object.dispose (/Users/tonimelisma/.vscode-insiders/extensions/golang.go-nightly-2020.12.1703/dist/goMain.js:10537:35)
    at /Users/tonimelisma/.vscode-insiders/extensions/golang.go-nightly-2020.12.1703/dist/goMain.js:12715:28
```

@hyangah: Do you have any advice on how to investigate this?
