### ISSUE TITLE
test: run extension tests in GOPATH and module modes

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#106]
Currently, the test fixtures have `go.mod` files but they are not used by the extension tests.

**Comment by Piyushhbhutoria** [comment]
Can you provide some more insights here?

**Comment by stamblerre** [comment]
The majority of the extension's [tests](https://github.com/golang/vscode-go/tree/master/test/integration) run only in GOPATH mode, which means that a lot of the code is untested for modules users. This issue is a reminder for us to make sure that we have tests running in both modes. It is possible that the eventual migration to gopls will make this unnecessary, so I don't think this issue should be a top priority.

**Comment by hyangah** [comment]
https://go-review.googlesource.com/c/vscode-go/+/291313 added testing for modules mode.
