### ISSUE TITLE
goimports does not work with autosave

### ISSUE THREAD

**Issue by danielhelfand** [golang/vscode-go#1060]
**Is your feature request related to a problem? Please describe.**

When using Auto Save (` "files.autoSave": "afterDelay"`), I notice that `goimports` is not run on each save action, which causes imports to not be ordered correctly or imports to be cleaned up automatically.

**Describe the solution you'd like**

If a go format tool is set, I would like that formatter to be applied on each save action when using Auto Save.

**Describe alternatives you've considered**

I can use auto save and then run goimports manually as I see necessary, but this seems like something that can be done by vscode for a user. 

If the feature I am describing above is available in some way, documentation on this would be something to consider adding as well.

**Comment by stamblerre** [comment]
This feature is available and described here: https://github.com/golang/vscode-go/blob/master/docs/features.md#format-and-organize-imports.

Can you please share your VS Code settings, which can found by opening the Command Palette (Ctrl+Shift+P) and selecting Preferences: Open Settings (JSON)? Also, what version of the extension are you using?

**Comment by stamblerre** [comment]
Sorry about the earlier comment, I misread the feature request.

Can you please share your VS Code settings, which can found by opening the Command Palette (Ctrl+Shift+P) and selecting Preferences: Open Settings (JSON)? Also, what version of the extension are you using?

**Comment by danielhelfand** [comment]
Thanks for the response. My settings are very simple:

```
{
    "go.formatTool": "goimports",
    "files.autoSave": "afterDelay",
    "go.alternateTools": {},
    "window.zoomLevel": 0
}
```

I am using latest version of the extension (`v0.20.0`).

**Comment by stamblerre** [comment]
It looks like this is a limitation of the `"afterDelay"` setting, see https://github.com/microsoft/vscode/issues/45997.

**Comment by danielhelfand** [comment]
Thanks for pointing out the duplicate issue. 

I am not seeing the rationale for why the original issue was labeled out of scope. The UX of alternative options like `onFocusChange` or `onWindowChange` aren't what most were looking for out of the original issue.

**Comment by stamblerre** [comment]
I would recommend opening a new issue in the VS Code repository (https://github.com/microsoft/vscode) or commenting on the existing issue. There's not much that the Go extension can do about a VS Code limitation. Going to close this issue since its a VS Code limitation.
