### ISSUE TITLE
Error loading workspace

### ISSUE THREAD

**Issue by Kurt-Shiwz** [golang/vscode-go#1064]
os: macos 11.1 (20C69)
vscode:1.52.1
go: go version go1.15.6 darwin/amd64

when i pull the lastest version(go.mod change), the error loading always running until i run "rm -rf vendor && go mod vendor".
i know it is't a real bug, because i use vendor(i like to see the pkg files in left explore, go mod can just see the single file),
i want to know if where is a setting can disable try to load when the error happened.  as i see it running until i fix it.

```
Error loading workspace: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin
```

**Comment by stamblerre** [comment]
@Kurt-Shiwz: Can you please share the full text of the error? Based on what you're saying about vendoring, it sounds like you may have an issue with inconsistent vendoring. In that case, you should also see a diagnostic with a suggested fix--do you see a diagnostic on the `go.mod` file?

**Comment by Kurt-Shiwz** [comment]
> @Kurt-Shiwz: Can you please share the full text of the error? Based on what you're saying about vendoring, it sounds like you may have an issue with inconsistent vendoring. In that case, you should also see a diagnostic with a suggested fix--do you see a diagnostic on the `go.mod` file?

it seem like pkg version in go.mod new than vendor/ **, so i "rm -rf vendor" and run "go mod vendor" use the newest pkg, after that it ok

**Comment by stamblerre** [comment]
That sounds like inconsistent vendoring, and you should see the diagnostic with the quick fix. You can just click the suggested fix to resolve the problem. Unfortunately, inconsistent vendoring is a critical problem for the go command, so until https://github.com/golang/go/issues/39164 is resolved, there's nothing else that can be done.
