### ISSUE TITLE
vscode whenever the import package under a GOROOT, have suggested that "can not find package xxx", but reopened vscode, package xxx successfully imported

### ISSUE THREAD

**Issue by DomBro96** [golang/vscode-go#1069]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:
 
- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Go Language Server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	go1.15.6
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	v0.6.0
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	1.52.1
- Check your installed extensions to get the version of the VS Code Go extension
	v0.20.1
- Run `go env` to get the go development environment details
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/usr/local/Cellar/go/1.15.6/libexec/bin"
GOCACHE="/Users/dongbo7/Library/Caches/go-build"
GOENV="/Users/dongbo7/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/dongbo7/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/dongbo7/go"
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/Cellar/go/1.15.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.6/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kq/r9fnjt9932qb176sg_v2z6dh0000gn/T/go-build852516590=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

{
    "go.languageServerExperimentalFeatures": {
    
        "diagnostics": true,
        "documentLink": true
    },
    "go.languageServerFlags": [
    
    
    ],
    "go.docsTool": "guru",
    "go.formatTool": "gofmt",
    "editor.fontSize": 18,
    "go.useLanguageServer": true,
    "window.zoomLevel": 0,
    "go.gotoSymbol.includeGoroot": true,
    "go.gopath": ""
}

### Describe the bug

vscode whenever the import package under a GOROOT, have suggested that "can not find package xxx", but reopened vscode, package xxx successfully imported

### Steps to reproduce the behavior:
1. import a package under GOROOT, 

![image1](https://user-images.githubusercontent.com/30015473/103332019-718b2080-4aa3-11eb-920a-c40f11099ca7.png)

2. reopen vscode

![mage2](https://user-images.githubusercontent.com/30015473/103332100-c29b1480-4aa3-11eb-8746-3c0c74d0b868.png)

3. See error

but I cannot reopen vscode every time I import the package : )

**Comment by stamblerre** [comment]
Can you please share your language server logs, which can be captured following the steps [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code)?

**Comment by DomBro96** [comment]
ok ,here is:

Trace Information
$/cancelRequest last: 94.23µs, longest: 94.23µs
$/progress last: 104.303µs, longest: 194.239µs
Server.diagnose last: 2.256916ms, longest: 56.862783ms
Server.diagnoseChangedFiles last: 1.619609ms, longest: 371.039869ms
Server.diagnosePkg last: 222.679µs, longest: 1.359117ms
Server.diagnoseSnapshot last: 254.389579ms, longest: 625.350613ms
Server.publishDiagnostics last: 77.004µs, longest: 217.344µs
cache.importer.typeCheck last: 518.679µs, longest: 87.185419ms
cache.parseGo last: 158.658µs, longest: 48.324958ms
cache.readFile last: 40.825µs, longest: 759.111µs
cache.view.load last: 317.246711ms, longest: 317.246711ms
client/registerCapability last: 1.255049ms, longest: 5.166631ms
completion.Completion last: 317.414125ms, longest: 317.414125ms
initialize last: 1.024828ms, longest: 1.024828ms
initialized last: 152.052139ms, longest: 152.052139ms
lsp.Server.documentSymbol last: 271.021µs, longest: 325.943µs
mod.Diagnostics last: 25.809µs, longest: 43.52µs
queued last: 54.171µs, longest: 372.027517ms
source.AllImportsFixes last: 595.21µs, longest: 749.011µs
source.DocumentSymbols last: 126.02µs, longest: 193.062µs
source.Highlight last: 120.837µs, longest: 120.837µs
source.Hover last: 23.46µs, longest: 67.671µs
source.Identifier last: 254.397µs, longest: 684.859µs
source.diagnostics last: 91.494µs, longest: 91.494µs
textDocument/codeAction last: 1.211721ms, longest: 372.168839ms
textDocument/codeLens last: 614.478µs, longest: 160.854273ms
textDocument/completion last: 324.780581ms, longest: 324.780581ms
textDocument/didChange last: 2.986846ms, longest: 7.502904ms
textDocument/didOpen last: 1.627785ms, longest: 1.627785ms
textDocument/documentHighlight last: 615.936µs, longest: 615.936µs
textDocument/documentLink last: 1.631757ms, longest: 372.096178ms
textDocument/documentSymbol last: 954.395µs, longest: 372.44073ms
textDocument/foldingRange last: 704.431µs, longest: 168.929338ms
textDocument/hover last: 774.923µs, longest: 1.616945ms
textDocument/publishDiagnostics last: 137.434µs, longest: 137.434µs
window/logMessage last: 169.12µs, longest: 623.489µs
window/workDoneProgress/create last: 4.734528ms, longest: 4.734528ms
workspace/configuration last: 2.005835ms, longest: 2.005835ms

**Comment by DomBro96** [comment]
thank you, I solved this problem when I execute the "go mod init command...
", hope this is useful information
