### ISSUE TITLE
coverage: show code coverage for multiple packages

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#108]
Currently, the code coverage is applied only to the files that fall under the package corresponding to the current file that is open. The feature request is to support showing code coverage for multiple packages.

While using the flag `-coverpkg=all`, the `go test` command does create a cover profile for all packages, the extension fails to apply it correctly. The problem lies in converting the relative paths in the cover profile to absolute paths that the editor can understand.

For more, please see https://github.com/microsoft/vscode-go/issues/816,

**Comment by hyangah** [comment]
This is available since 0.16 (https://go-review.googlesource.com/c/vscode-go/+/238697).
Users can set the flag using `go.testFlags` or manually run from the terminal and feed to the `Go: Apply Coverage Profile` command.

Thanks @pjweinbgo and @suzmue for fixing and verifying!
