### ISSUE TITLE
Error loading workspace: go - hairy problem with new module system depending upon an incompatible module but also vendored modules

### ISSUE THREAD

**Issue by KevinBuchs** [golang/vscode-go#1081]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.15.6 and 1.12.7
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- 0.6.0
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.52.1
- Check your installed extensions to get the version of the VS Code Go extension
	- v0.20.1
- Run `go env` to get the go development environment details
	$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kbuchs/.cache/go-build"
GOENV="/home/kbuchs/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kbuchs/go/pkg/mod"
GONOPROXY="gitlab.com/redacted1/*"
GONOSUMDB="gitlab.com/redacted1/*"
GOOS="linux"
GOPATH="/home/kbuchs/go"
GOPRIVATE="gitlab.com/redacted1/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go/go1.15.5"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/go1.15.5/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/redacted2/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build415755634=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

   "go.useLanguageServer": false

### Describe the bug

So, I have been hitting this problem recently with VSCode where it complains:

```text
Error loading workspace: go [-e -json -compiled=true -test=true -export=false 
-deps=true -find=false -- builtin opa-decision-logger/...]: exit status 1: go: 
gitlab.com/redacted1/utility/go-logger.git@v4.0.0+incompatible: module 
lookup disabled by GOPROXY=off go: error loading module requirements
```

This is a repo/folder which has a go.mod which contains
```text
require (
   	gitlab.com/redacted1/utility/go-logger.git v4.0.0+incompatible
```

We have dependencies vendored in ./vendor, including the go-logger one. I've read that the Gopls (Go Language Server for vscode) insists upon the new module system so I have disabled its use by the Go extension, but had the same problem with it enabled. This go build command 

```shell
CGO_ENABLED=0 GOOS=linux go build -mod=vendor
```
works just fine in my shell and with our Dockerfile Docker build. I tried adding a build flag to the go extension settings: *-mod=vendor* and the extension complains

```text
Error loading workspace: err: exit status 1: stderr: build flag -mod=vendor only valid when
using modules
```

I really can't find useful info about GOPROXY, but when I try to explicitly install the module (e.g. with the Quick Fix action for the error flagged in the go.mod file) I get this error:

```text
Add dependency failed: err: exit status 1: stderr: go: finding gitlab.com/redacted1/utility/
go-logger.git v4.0.0+incompatible go: gitlab.com/redacted1/utility/go-logger.git@v4.0.0
+incompatible: unknown revision v4.0.0 go: error loading module requirements
```
Also when I try to install via shell I see the same:
```shell
go install gitlab.com/redacted1/utility/go-logger.git@v4.0.0
go: gitlab.com/redacted1/utility/go-logger.git@v4.0.0+incompatible: reading gitlab.com/
redacted1/utility/go-logger.git/go.mod at revision v4.0.0: unknown revision v4.0.0
```
That version certainly exists in the repo, but it is a private repo, and I think the error message that it doesn't exist is a red herring and the true error is it cannot read the repo. I tried with GOPRIVATE environment variable in the shell and that did not work either.

**Comment by hyangah** [comment]
@KevinBuchs Thanks for the report - Can you please reenable the language server again  (`"go.useLanguageServer": true`), reload the window, and see if the gopls got the GOPRIVATE environment variable correctly? The OUTPUT channel of `gopls (server)` will show the `go env` output run by `gopls`.
![Screen Shot 2021-01-05 at 12 34 03 PM](https://user-images.githubusercontent.com/4999471/103679150-7d1e9180-4f52-11eb-9815-368fa9abeb5a.png)

**Comment by KevinBuchs** [comment]
@hyangah thanks for the reply. I have made the configuration changes you suggested. I started vscode from a shell in which GOPRIVATE was set and I have confirmed that the `go env` output for gopls (server) shows that that environment variable was set. Still the "Error loading workspace" error persists.

**Comment by stamblerre** [comment]
Can you please share your `gopls` log when this happens? Information on how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs). Redacted logs are totally fine.

**Comment by KevinBuchs** [comment]
Well, hanging my head, my workgroup was working on this issue and someone created a new version of the go-logger code that made it compatible with go.mod new modules (added a go.mod, etc.). Well, with that change, but not a dependency change for go-logger in my redacted1 project, the problem is resolved. I do not understand this, but I cannot put things back as they were and reproduce the failure I saw, so I cannot capture the gopls log with the error. Sorry. 

Ironically, I cannot upgrade the dependency in the redacted1 project either. With the dependency updated to the new version, without the +incompatible version decorator, the reports the semantic dependency versioning problem 
```text
/home/kbuchs/git/DMP/docker-google-storage-proxy/go.mod:13:2: require gitlab.com/sbra-dmp/utility/go-logger.git: version "v4.1.1" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v4
```
That is not your problem, of course.

**Comment by hyangah** [comment]
@KevinBuchs Thanks for the update. Unfortunately, without concrete examples to repro the issue or the gopls traces to inspect, it's hard for us to go any further. So I propose to close this issue. For general modules-related question, you can ask the `#modules` channel in the gophers slack. Looks like the `go.mod` files seems invalid - for `v4`, the module name should end with `/v4`.
 
From the original report, I guess there are multiple issues mixed.

- The vendoring behavior has changed over time, so go1.12 and go1.15 behavior may slightly differ. So, please stick with go1.15 for the discussion.
- gopls not understanding `-mod=vendor` is a bug which should be fixed in the master but not released. You can try the unstable version (https://github.com/golang/tools/blob/master/gopls/doc/user.md#unstable-versions) and see if it still complains.
- Installation issue: It looks like the original module needs to be fixed. Use `go get` for dependency install/update in module mode. The `-x -v` flags will help inspecting what's going on underneath.
