### ISSUE TITLE
in typescript project ,shows errors

### ISSUE THREAD

**Issue by ycllz** [golang/vscode-go#1082]
Error loading workspace: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module, but found .git/config in D:\project\client\trunk\king 	to create a module there, run: 	go mod init : packages.Load error

**Comment by hyangah** [comment]
@ycllz Can you tell us more about your project? Does it have any go file - not sure why Go extension is activated in typescript project.
And what is the gopls version?

**Comment by ycllz** [comment]
I'm a typescript project, have no any go file. And I use Go Nightly version. Buy I change to 0.20.2 version ,the same problem happen.

**Comment by ycllz** [comment]
i use vs code in windows 10 pro 1909, not preview version, and I code with a TypeScript Project.
but, it's ok now,  when i update twice to insider perview verison of build 21301. it fix the problem. 
I'm sorry, I didn't reappear the problem. It may be the win10 env cause the problem.It should be possible to close the issue.
 @hyangah thanks your kind help.
