### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by blessedmadukoma** [golang/vscode-go#1088]
gopls version: v0.6.2
gopls flags: 
extension version: 0.20.1
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.
Coudn't start client gopls

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@blessedmadukoma: Can you please share the content found by navigating to View -> Output -> Tasks -> gopls (server))?

**Comment by blessedmadukoma** [comment]
It has been solved thank you, I needed to run the installer again.
I have a new issue, anytime I use my Linux mint 20 for golang and I shut
down, the next time I use it, golang is not found in path, I have tried
using the docs to permanently fix it but nothing seems to work. is there a
permanent way of setting go path, root and the rest? thank you

**Comment by stamblerre** [comment]
https://golang.org/doc/install#install should have more information--are the instructions (under Linux) here helpful?
You should be able to permanently set your `$GOPATH` and `$PATH` variables in your `$HOME/.profile` file.

**Comment by blessedmadukoma** [comment]
It worked. Thank you

**Comment by stamblerre** [comment]
Glad to hear it--closing this issue since it has been resolved.
