### ISSUE TITLE
Allow setting custom go binary

### ISSUE THREAD

**Issue by rafaelsierra** [golang/vscode-go#1099]
**Is your feature request related to a problem? Please describe.**
When you have multiple go versions it is annoying to switch which version is going to be used by vscode

**Describe the solution you'd like**
Provide a command/config to set which go cli to use

**Additional context**
Multiple go versions are available as `go$VERSION` and changing the default `go` version before opening vscode is not ideal.

I know about the alternatives, like having a `$HOME` based `bin` path and use `ln` to switch which version is the default `go` command, or using `alias go=go1.13.13` before opening vscode, but those solutions are not ideal.

**Comment by hyangah** [comment]
Have you tried the "go.alternateTools" setting?

```
"go.alternateTools": {
  "go": "/path/to/your/choice/of/gowrapper"
}
```

**Comment by rafaelsierra** [comment]
@hyangah yes, combined with per-workspace settings this works perfectly :+1:
