### ISSUE TITLE
debug: support delve's rewind command

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#110]
This is a request to add integration to the rewind command in delve. Please see https://github.com/microsoft/vscode-go/issues/1529 for details where there are discussions on the implementation as well as links to past PRs that attempted to add this feature

Corresponding PR in this repo: #89

**Comment by polinasok** [comment]
The rewind option is available in two cases:
1. Replay regenerated rr trace:
```
"request": "launch",
"mode": "replay",
"traceDirPath":"path/to/rr/trace",
```
Tracked under #1243.
2. Build/take binary, generate rr trace and replay:
```
```

**Comment by polinasok** [comment]
I am able to launch with "rr" backend. The trace is generated and the Step Back button shows up. Unfortunately, there appears to be some kind of compatibility issue with rr and my workstation not related to dlv dap - the recording exits before anything runs, so I don't hit any breakpoints and can't test the button itself. 

@lggomez Could you confirm please that this works for you?
```
"request": "launch",
"mode": "debug", // or "exec" or "test"
"backend":"rr",
```

**Comment by lggomez** [comment]
@polinasok Is this on main branch? I'm using launch config `"mode": "replay"`  which works as intended using the latest version of the extension

My setup is the following

```
golang.go v0.27.2

.rr version 5.3.0

Delve Debugger
Version: 1.7.1
Build: $Id: 3bde2354aafb5a4043fd59838842c4cd4a8b6f0b $

Version: 1.60.0
Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
Date: 2021-09-01T10:43:02.136Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-34-generic snap

uname: 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by polinasok** [comment]
> @polinasok Is this on main branch? I'm using launch config `"mode": "replay"` which works as intended using the latest version of the extension

@lggomez No I don't mean "replay" mode. That one takes a pre-generated file.  If you add "rr" backend to any other mode it should, run and record for you and then replay that recording.

**Comment by polinasok** [comment]
FYI @rogchap @t-bast who were on the original issue microsoft/vscode-go#1529

**Comment by polinasok** [comment]
@hyangah Could you please verify that rewind buttons works as expected when hitting a breakpoint with the following configuration on Linux?
```
"request": "launch",
"mode": "debug", // or "exec" or "test"
"backend":"rr",
```

**Comment by hyangah** [comment]
https://twitter.com/belbaoverhill/status/1466911997174464513 :-) 

Thanks @lggomez @polinasok @aarzilli @derekparker
