### ISSUE TITLE
Don't expose user env on automated crashes

### ISSUE THREAD

**Issue by ranisalt** [golang/vscode-go#1101]
[REDACTED]

**Comment by hyangah** [comment]
@ranisalt Can you please be more specific about what user environment info is included in the automated crash report?

The automated crash report includes only the panic messages (and gopls installation directory path is also redacted) in case of crash, and the initialization error string (from gopls), and shouldn't include sensitive info. 
If not, that's a bug in the extensions automated crash report, but without the details on what info is included to fix the bug.

**Comment by ranisalt** [comment]
gopls was crashing, I will wait for it to crash again to submit a new report
