### ISSUE TITLE
v0.20.0 works, v0.21.0 causes "Cannot get property 'get' of undefined"

### ISSUE THREAD

**Issue by PatrickDuncan** [golang/vscode-go#1104]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.3 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- Version: 1.52.1
- Check your installed extensions to get the version of the VS Code Go extension
	- 0.21.0
- Run `go env` to get the go development environment details
	- (Work machine)

### Share the Go related settings you have added/edited

Default

### Describe the bug
When I saw I get the `Cannot get property 'get' of undefined`, but it seems like the extension was partially doing its job still. v0.20.0 does not have the error at all.

### Steps to reproduce the behavior:
1. Use v0.21.0 and save a `.go` file on macOS

**Comment by hyangah** [comment]
@PatrickDuncan Thanks for the report - do you mind sharing the full exception log? I guess the error message is either in the  
`View: Toggle Output` -> Log(Extension Host) or
`Developer: View Developer Tools` -> Console tab

**Comment by hyangah** [comment]
Oh, nevermind. I reproduced the issue. :-(

**Comment by kjbass** [comment]
I'm encountering the same issue myself -- I might be a little dense towards the end of the day, but could you clarify if there is a workaround for this currently?

**Comment by hyangah** [comment]
Thanks @kjbass for sharing the workaround. That's what I'd recommend - we plan to enable the language server by default next week so this is a good time to test 😅

If enabling the language server isn't an option, please try the older version (0.20.0)
Go to the extension view (Ctrl+Shift+X or Cmd+Shift+X) -> select Go -> select the gear icon -> select "Install another version" -> choose the old version

I will try to publish the patch as soon as it is reviewed. Sorry for the inconvenience.

**Comment by shotgunwilly** [comment]
I had the same issue running on Windows 10. Went back to version v0.20.2 and is working again.

**Comment by kelleyau** [comment]
I have this problem on OSX 11.1
Go version: 
go version go1.15.7 darwin/amd64

Vscode version:
1.52.1

Go extension version:
v0.21.0

I also tried adding the languageserver to my settings via the sugggested workaround and that does not work for me unfortunately:
`
{
    "workbench.colorTheme": "Solarized Dark",
    "workbench.colorCustomizations": {
        "editor.foreground": "#FFFFE0",
        "editorCursor.foreground": "#ffff00",
        "terminalCursor.foreground": "#ffff00"
    },
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "keyword.operator",
                    "entity.name.function",
                    "string",
                ],
                "settings": {
                    "foreground": "#FFFFFF",
                },
            },
        ],
    },
    "editor.fontSize": 20,
    "editor.fontWeight": "bold",
    "window.zoomLevel": 4,
    "files.autoSave": "afterDelay",
    "terminal.integrated.copyOnSelection": true,
    "editor.accessibilitySupport": "off",
    "go.useLanguageServer": true
}
`

**Comment by BatmanAoD** [comment]
I had the same issue, I think. I also had other weird errors, such as:

```
Cannot activate the 'Go Coverage Viewer' extension because it depends on an unknown 'ms-vscode.go' extension .
```

After some fruitless searching (and following the troubleshooting guide), I eventually discovered that my `gopls` was at version `0.5.5`. VSCode was unable to update the tool for me (unfortunately I can't remember the error message), but manually updating to the latest (`0.6.4`) seems to have fixed things.

**Comment by hyangah** [comment]
v0.21.1 Release Candidate is available in https://github.com/golang/vscode-go/releases/tag/v0.21.1-rc.1 
Can any of you try if it actually addresses all issues?
