### ISSUE TITLE
check: allow use of custom vet when using the language server

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1109]
From https://github.com/golang/vscode-go/issues/50 - 
some users had to turn off gopls diagnostics because they need custom vet analyzers.
Find a way for users to turn on the vet.

**Comment by tamayika** [comment]
I gave up to run go vet with vscode-go and made [vscode-any-lint](https://github.com/tamayika/vscode-any-lint) to support multiple lint tools for any files.
Thanks to this extension, I got both gopls's diagnostics and custom analyzer's diagnostics.
So, if there is nobody who wants custom vet with gopls, please close this issue and deprecate custom vet with gopls feature.

**Comment by hyangah** [comment]
Let's close this - users who want to use a custom vet should consider

- utilize meta linter like golangci-lint and wire it up using the linter setting
- 3rd party extension like @tamayika's vscode-any-lint
- ultimately, gopls should look into a way to make it extensible (see https://github.com/golang/go/issues/49018)
