### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by mahyuddin** [golang/vscode-go#1112]
gopls version: v0.6.4
gopls flags: 
extension version: 0.20.2
environment: Visual Studio Code

[Error - 9:36:55 am] Starting client failed
Error: Connection got disposed.
	at Object.dispose (c:\Users\mahyuddin\.vscode\extensions\golang.go-0.20.2\dist\goMain.js:94607:27)
	at Object.dispose (c:\Users\mahyuddin\.vscode\extensions\golang.go-0.20.2\dist\goMain.js:10537:35)
	at c:\Users\mahyuddin\.vscode\extensions\golang.go-0.20.2\dist\goMain.js:12715:28
[Info  - 9:37:18 am] 2021/01/22 09:37:18 go env for C:\Users\mahyuddin\Workspace
(root C:\Users\mahyuddin\Workspace)
(go version go version go1.15.6 windows/amd64)
(valid build configuration = false)
(build flags: [])
GOPRIVATE=
GONOSUMDB=
GOINSECURE=
GONOPROXY=
GOPROXY=https://proxy.golang.org,direct
GOROOT=c:\go
GOSUMDB=sum.golang.org
GO111MODULE=
GOCACHE=C:\Users\mahyuddin\AppData\Local\go-build
GOFLAGS=
GOPATH=C:\Users\mahyuddin\go
GOMOD=
GOMODCACHE=C:\Users\mahyuddin\go\pkg\mod

[Info  - 9:37:18 am] 2021/01/22 09:37:18 go/packages.Load
	snapshot=0
	directory=C:\Users\mahyuddin\Workspace
	query=[./ builtin]
	packages=2

[Info  - 9:37:19 am] 2021/01/22 09:37:19 go/packages.Load
	snapshot=0
	directory=C:\Users\mahyuddin\Workspace
	query=[./]
	packages=1

[Info  - 9:37:20 am] 2021/01/22 09:37:20 go/packages.Load
	snapshot=0
	directory=C:\Users\mahyuddin\Workspace
	query=[./]
	packages=1

[Info  - 9:37:20 am] 2021/01/22 09:37:20 go/packages.Load
	snapshot=0
	directory=C:\Users\mahyuddin\Workspace
	query=[./]
	packages=1

[Info  - 9:37:21 am] 2021/01/22 09:37:21 go/packages.Load
	snapshot=1
	directory=C:\Users\mahyuddin\Workspace
	query=[file=C:\Users\mahyuddin\Workspace\golang\books\Mastering-Concurrency-in-Go\ch01\ch1_1_patientgoroutine.go]
	packages=1

[Info  - 9:37:21 am] 2021/01/22 09:37:21 go/packages.Load
	snapshot=1
	package="command-line-arguments"
	files=[C:\Users\mahyuddin\Workspace\golang\books\Mastering-Concurrency-in-Go\ch01\ch1_1_patientgoroutine.go]

[Info  - 9:37:21 am] 2021/01/22 09:37:21 go/packages.Load
	snapshot=1
	package="command-line-arguments"
	files=[C:\Users\mahyuddin\Workspace\golang\books\Mastering-Concurrency-in-Go\ch01\ch1_1_patientgoroutine.go]

[Info  - 9:37:21 am] 2021/01/22 09:37:21 go/packages.Load
	snapshot=1
	directory=C:\Users\mahyuddin\Workspace
	query=[file=C:\Users\mahyuddin\Workspace\golang\books\Mastering-Concurrency-in-Go\ch01\ch1_1_patientgoroutine.go]
	packages=1

**Comment by hyangah** [comment]
Thanks for the report including the crash log, @mahyuddin.
It looks like it was a transient failure. Can you please tell us a bit more about when you observed this crash?
(e.g. I just opened the workspace, I was editing settings.json, ...)
