### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by vo9312** [golang/vscode-go#1114]
gopls version: v0.6.4
gopls flags: -trace
extension version: 0.21.1
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x12f08c9]

goroutine 1 [running]:
text/template.(*Template).Parse(0xc00031c240, 0x1a3ff7d, 0x21b, 0x1, 0x1, 0x1)
	  template.go:203  0x199
html/template.(*Template).Parse(0xc00019bad0, 0x1a3ff7d, 0x21b, 0x0, 0x0, 0x0)
	  template.go:189  0xfd
net/http/pprof.init()
	  pprof.go:307  0x37b
[Error - 11:58:03 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@vo9312: Can you please change the `-trace` flag in your `"go.languageServerFlags"` setting to `-rpc.trace`? (See https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by hyangah** [comment]
@vo9312 thanks for the report. I don't fully understand how crash in pprof occurred. Maybe it's another issue. Please correct the `go.languageServerFlags` setting and if you encounter the same crash, please open a new issue.
We will need your go version, too. Thanks!
