### ISSUE TITLE
cannot find package - But it's not a mistake

### ISSUE THREAD

**Issue by edubudubolo** [golang/vscode-go#1121]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.15.7 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.6.4
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.52.1
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.22.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs (/Users/eduardoortizmejia/go/bin/gopkgs) SUCCEEDED
Installing github.com/ramya-rao-a/go-outline (/Users/eduardoortizmejia/go/bin/go-outline) SUCCEEDED
Installing github.com/cweill/gotests/... (/Users/eduardoortizmejia/go/bin/gotests) SUCCEEDED
Installing github.com/fatih/gomodifytags (/Users/eduardoortizmejia/go/bin/gomodifytags) SUCCEEDED
Installing github.com/josharian/impl (/Users/eduardoortizmejia/go/bin/impl) SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay (/Users/eduardoortizmejia/go/bin/goplay) SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv (/Users/eduardoortizmejia/go/bin/dlv) SUCCEEDED
Installing golang.org/x/lint/golint (/Users/eduardoortizmejia/go/bin/golint) SUCCEEDED
Installing golang.org/x/tools/gopls (/Users/eduardoortizmejia/go/bin/gopls) SUCCEEDED

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

"editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }

### Describe the bug
I have worked for several months in the development of an API-Rest without problems. Today in visual studio the extension update message appeared and I clicked update, after that in several files it has started to give problems with the imports of the packages. The problem is with local packages, are not looking for them in the local directory but in the root directory. For example: import "./repository" the package exists in the project but I get the following message:

could not import ./repository (cannot find package "./repository" in any of 
	/usr/local/go/src/repository (from $GOROOT)
	/Users/eduardoortizmejia/go/src/repository (from $GOPATH))compiler

In some files it recognizes the import and in others it does not. When executing the command:

->go run main.go

The api runs fine and I have no problem consuming the endPoints. 

When I close the visual studio and open it again, there are other files that the imports do not recognize, that is, when I open visual studio the problem is not in the same files. But when running the application I don't have any errors. This problem did not happen in all the time I have worked on the API, which is several months, it appeared today when updating the extension. 

### Steps to reproduce the behavior:
1. Open visual studio

**Comment by stamblerre** [comment]
Thank you for reporting this issue. The latest version of this extension enabled the language server, `gopls`, which is likely why you ran into this issue today. Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by edubudubolo** [comment]
[Logs.pdf](https://github.com/golang/vscode-go/files/5889363/Logs.pdf)

Thank you very much for your help. I have attached a file where the logs are seen, this information is when loading the project in visual studio, I highlighted in red the imports that were not found. As I was saying it is not an error, because the api works correctly. But in VSCode it appears as error.

**Comment by hyangah** [comment]
@edubudubolo Thank you for the log. It looks like you've been working in GOPATH mode, but the project workspace (`/Users/computer/Documents/goProjects/APIDev`) is outside of GOPATH (`/Users/computer/go`). That layout is not supported by gopls. See gopls's [supported workspace doc](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md).

For the background: as go is moving towards module mode (fyi it's the default in the upcoming 1.16), the relative import feature is not going to be supported any more. See https://github.com/golang/go/issues/26645#issuecomment-408572701 for the discussion. The easiest path to migrate is to define a module name from your workspace (e.g. `go mod init m`) and replace the imports to be rooted from the module name (e.g. `./repository` -> `m/repository`).

**Comment by edubudubolo** [comment]
I have tried not to place the point, instead I put the project name, but it does not recognize. How can the relative reference be used? instead of placing the point I place the name of the project it does not recognize the reference, it does not even compile.

Or your suggestion to move my project to the path /Users/computer/go so that it doesn't get this error?

**Comment by hyangah** [comment]
@stamblerre Carefully looking at the trace @edubudubolo shared in https://github.com/golang/vscode-go/issues/1121#issuecomment-769294877,  I found there was no warning from gopls about unsupported workspace configuration. Surprisingly, I found gopls works ok for my trivial project in a directory outside GOPATH (in GOPATH mode). Does the latest version of gopls start to support this scenario? If so, should update the workspace doc?

@edubudubolo Please wait for @stamblerre's response.

I still recommend migrating to go modules (https://blog.golang.org/using-go-modules) before go1.16.  Relative path is not supported in module mode. The import path should be starting with  <module_path> and `go mod init` command is how to define the module path. Do you have the `go.mod` file now? Can you share the content of the file?

**Comment by edubudubolo** [comment]
Greetings, I have been reviewing the information that you indicated to me to change the way to make the references of the packages. I created the .mod file and in this file in the "require" section I put the external references, then instead of having this reference ./repository I put in this way m/repository. Fixed all issues with previously featured references. Surprisingly now I have a problem with Gorm, it gives me problems in the SQL Querys syntax, something that did not happen before, now I am checking this problem. In short, the local import problems have been solved with the mod file

**Comment by stamblerre** [comment]
> @stamblerre Carefully looking at the trace @edubudubolo shared in [#1121 (comment)](https://github.com/golang/vscode-go/issues/1121#issuecomment-769294877), I found there was no warning from gopls about unsupported workspace configuration. Surprisingly, I found gopls works ok for my trivial project in a directory outside GOPATH (in GOPATH mode). Does the latest version of gopls start to support this scenario? If so, should update the workspace doc?

`gopls` supports ad-hoc packages as long as it can find all of the needed dependencies. I'd rather that we didn't explicitly indicate support for this since it's not well tested, but we try to keep the warnings to a minimum since many users seem to have ad-hoc packages.

@edubudubolo: Can this issue be closed now that it's resolved?

**Comment by edubudubolo** [comment]
Yes, mod file implementation has fixed the problem. Thank you very much
