### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by sheazp** [golang/vscode-go#1123]
gopls version: (devel)
gopls flags: 
extension version: 0.22.0
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report @sheazp 
It looks like the `gopls` binary was built in dev mode long ago and needs update.
Please update it either by running Ctrl+Shift+P (or Cmd+Shift+P) > "Go: Install/Update Tools" > Select 'gopls', or
manually following the instruction [here](https://github.com/golang/tools/tree/master/gopls#installation).
