### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by gusandrioli** [golang/vscode-go#1149]
gopls version: v0.6.4
gopls flags: 
extension version: 0.22.0
environment: Visual Studio Code

Failed to auto-collect gopls trace: unrecognized crash pattern.

**Comment by hyangah** [comment]
Thanks @gusandrioli. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was editing settings.json, I just opened up the window, etc.)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
