### ISSUE TITLE
promptForTags should also prompt for transform

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#115]
_From @bhenderson in https://github.com/microsoft/vscode-go/issues/2546_

Hi, I was hoping for a way for Go: Add Tags to prompt for the transform parameter. I often want to switch between camelCase and snake_case even within the same project.

I was thinking that if go.addTags.promptForTags is true, it would also prompt for the transform parameter.

**Comment by ramya-rao-a** [comment]
Related PR: https://github.com/golang/vscode-go/pull/78

**Comment by hyangah** [comment]
https://go-review.googlesource.com/c/vscode-go/+/234659 was merged a while ago into the Nightly.
