### ISSUE TITLE
Error loading workspace

### ISSUE THREAD

**Issue by inigosola** [golang/vscode-go#1151]
- `go version` go version go1.15.7 darwin/amd64
- `gopls -v version` golang.org/x/tools/gopls v0.6.4
- `code -v` 1.52.1
- `VS Code Go extension` 0.22.0
- `Go: Locate Configured Go Tools`:
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/a/go
GOROOT: /usr/local/Cellar/go/1.15.7/libexec
PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

   gopkgs: /Users/a/go/bin/gopkgs installed
   go-outline: /Users/a/go/bin/go-outline installed
   gotests: /Users/a/go/bin/gotests installed
   gomodifytags: /Users/a/go/bin/gomodifytags installed
   impl: /Users/a/go/bin/impl installed
   goplay: /Users/a/go/bin/goplay installed
   dlv: /Users/a/go/bin/dlv installed
   golint: /Users/a/go/bin/golint installed
   gopls: /Users/a/go/bin/gopls installed

go env
Workspace Folder (hello-world-example): /Volumes/a/b/c/hello-world-example
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/a/Library/Caches/go-build"
	GOENV="/Users/a/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/a/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/a/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.15.7/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.15.7/libexec/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p3/wm6w_xgx4qn9x4_rfgzbtqb80000gn/T/go-build481392918=/tmp/go-build -gno-record-gcc-switches -fno-common"
	

- `Preferences: Open Settings (JSON)`  "go.formatTool": "goimports",

### Describe the bug
_Error loading workspace: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- builtin hello-world/...]: exit status 1: go: updates to go.sum needed, disabled by -mod=readonly : packages.Load error_

### Steps to reproduce the behavior:
1. Open go file in VS Code
2. See error (in bottom bar)

**Comment by hyangah** [comment]
@inigosola Thanks for the report. 

As the error message hinted, `go.sum` needs updates. Please open the `go.mod` file in the editor or see the "PROBLEMS" pane. There should be a quick fix suggest (light bulb) near the problematic location. Choose `Run go mod tidy`. Or manually run `go mod tidy` in the `hello-world` directory from the integrated terminal.

@stamblerre Is it possible to rewrite the error notification message so it's more user-friendly?
     - skip the go command or place it later, so the details like `updates to go.sum needed, disabled by -mod=readonly` is more visible.
     - make it clear what action users need to take to address this issue. I wonder if it's possible to add a button or a link that opens the problematic go.mod file or presents quick fix options.

**Comment by inigosola** [comment]
@hyangah thanks you.
I get `go: cannot find main module;` when I run `go mod tidy`.

This is the `go.mod` file content:

```
require github.com/aws/aws-lambda-go v1.13.3

module hello-world

```

**Comment by inigosola** [comment]
Sorry, now it is working with `go mod tidy` (I was in parent directory when I tried the first time).

So, `go mod tidy` fix the problem as @hyangah wrote before
