### ISSUE TITLE
add multiple tags to "add tags to struct"

### ISSUE THREAD

**Issue by OneOfOne** [golang/vscode-go#1158]
Sometimes you need different tags for the same field, for example `json:"x,omitempty" bigquery:"x"`, it'd be nice if the "add tags to struct" option was a menu that allowed multiple options.

I could to work on an implementation if the idea sounds acceptable.

**Comment by hyangah** [comment]
@OneOfOne Thanks for volunteering! Is it a duplicate of https://github.com/golang/vscode-go/issues/905?

**Comment by OneOfOne** [comment]
@hyangah I didn't see that before but yeah I guess it could work that way.

**Comment by hyangah** [comment]
Thanks! I will close this issue in favor of the old issue. AFAIK, nobody is currently working on this. 😉
