### ISSUE TITLE
gopls: cannot handle ssh:// or tcp:// URIs

### ISSUE THREAD

**Issue by Philippe12** [golang/vscode-go#1160]
gopls version: v0.6.4
gopls flags: 
extension version: 0.22.0
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: unsupported URI schemes: [{ssh://neptune-rdi/ SSH FS - neptune-rdi}] (gopls only supports file URIs)
  Code: 0 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
gopls cannot handle ssh:// uri. Not sure what to do in this case but disabling gopls.
Setup like [dev container](https://code.visualstudio.com/docs/remote/troubleshooting#_using-an-ssh-tunnel-to-connect-to-a-remote-docker-host) will not work.

For remote development, is it not possible to use [VSCode Remote - SSH or Remote -WSL](https://code.visualstudio.com/docs/remote/ssh)?

**Comment by hyangah** [comment]
Dup of #1171
