### ISSUE TITLE
Debug not work

### ISSUE THREAD

**Issue by zhiqiangxu** [golang/vscode-go#1163]
I'm following the steps here: https://github.com/golang/vscode-go/blob/master/docs/debugging.md . (it still requires `gopath` even though I'm using go1.15 which has go module, weird!)

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.15 darwin/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.6.4
    golang.org/x/tools/gopls@v0.6.4 h1:PO8rURGmi+QEKZ3pk+ZXJh51EFTVTSXqxzoRzrGSTJM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.0 h1:8pl+sMODzuvGJkmj2W4kZihvVb5mKm8pB/X44PIQHv8=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
    golang.org/x/tools@v0.1.1-0.20210119222907-0a1a9685734a h1:ttr/sghFptib3jlHwNS65KwGoqjr03TFzso3kpHyia8=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- command not found
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.22.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/xxx/.gvm/pkgsets/go1.15/global
GOROOT: /Users/xxx/.gvm/gos/go1.15
PATH: /Users/xxx/.gvm/gos/go1.15/bin:/Users/xxx/.pyenv/shims:/Users/xxx/.pyenv/bin:/Users/xxx/.wasmtime/bin:/Users/xxx/.cargo/bin:/usr/local/opt/mysql-client/bin:/Users/xxx/.gvm/pkgsets/go1.10/global/src/github.com/xxx/client2/third_party/cocos2d-x/templates:/Users/xxx/.gvm/pkgsets/go1.10/global/src/github.com/xxx/client2/third_party:/Users/xxx/.gvm/pkgsets/go1.10/global/src/github.com/xxx/client2/third_party/cocos2d-x/tools/cocos2d-console/bin:/Users/xxx/.cargo/bin:/Users/xxx/.gvm/pkgsets/go1.15/global/bin:/Users/xxx/.gvm/pkgsets/go1.15/global/overlay/bin:/Users/xxx/.gvm/bin:/Users/xxx/.gvm/bin:/Users/xxx/.cargo/bin:/Users/xxx/.rvm/gems/ruby-2.3.0/bin:/Users/xxx/.rvm/gems/ruby-2.3.0@global/bin:/Users/xxx/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xxx/.rvm/bin:/Users/xxx/.rvm/bin:/Users/xxx/.rvm/bin:/Users/xxx/Downloads/flutter/bin:/Users/xxx/Desktop/workspace/vagrant/java/build/apache-maven-3.5.0/bin/:/Users/xxx/bin/:/usr/local/Cellar/protobuf/3.3.0/bin:/Users/xxx/bin/dex2jar-2.1-SNAPSHOT:/Users/xxx/Library/Android/sdk/platform-tools:/Users/xxx/.luarocks/bin/:/Users/xxx/Downloads/flutter/bin/cache/dart-sdk/bin:/Users/xxx/.local/bin:/Users/xxx/Library/Python/3.8/bin

   gopkgs: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/gopkgs installed
   go-outline: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/go-outline installed
   gotests: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/gotests installed
   gomodifytags: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/gomodifytags installed
   impl: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/impl installed
   goplay: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/goplay installed
   dlv: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/dlv installed
   golint: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/golint installed
   gopls: /Users/xxx/.gvm/pkgsets/go1.15/global/bin/gopls installed

go env
Workspace Folder (evm-lab): /Users/xxx/Desktop/workspace/opensource/go_projects/evm-lab
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/xxx/Library/Caches/go-build"
	GOENV="/Users/xxx/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/xxx/.gvm/pkgsets/go1.15/global/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/xxx/.gvm/pkgsets/go1.15/global"
	GOPRIVATE=""
	GOPROXY="https://goproxy.cn,direct"
	GOROOT="/Users/xxx/.gvm/gos/go1.15"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/Users/xxx/.gvm/gos/go1.15/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/xxx/Desktop/workspace/opensource/go_projects/evm-lab/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ym/c42xcdhn78g0s97z3ycj2yw00000gn/T/go-build122889842=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
{
    "go.gopath": "/Users/xxx/.gvm/pkgsets/go1.15/global",
    "go.goroot": "/Users/xxx/.gvm/gos/go1.15",
    "go.toolsEnvVars": {
        "GOROOT": "/Users/xxx/.gvm/gos/go1.15",
        "PATH": "/Users/xxx/.gvm/gos/go1.15/bin/"
    }
}
```

These are copied somewhere long ago, the meanings are vague now...

### Describe the bug
When click the "Run and Debug", got this error:

```
# runtime/cgo
exec: "clang": executable file not found in $PATH
exit status 2
Process exiting with code: 1

```

**Comment by hyangah** [comment]
exec: "clang": executable file not found in $PATH
 
@zhiqiangxu Can you please check xcode is set up and you have `clang` in your $PATH?

**Comment by zhiqiangxu** [comment]
in the integrated console:

```
$ which clang
/usr/bin/clang
```

I think xcode developer tools are set up.

**Comment by suzmue** [comment]
@zhiqiangxu can you try setting PATH to include both your original PATH value and the directory you want to add like:

```
{
    "go.toolsEnvVars": {
        "PATH": "${env:PATH}:/Users/xxx/.gvm/gos/go1.15/bin/"
    }
}

```

[Here is the link](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) for reading more about accessing environment variables values in vscode.

**Comment by zhiqiangxu** [comment]
Still the same after adding `${env:PATH}` to PATH.

**Comment by hyangah** [comment]
@zhiqiangxu Unfortunately, [variable substitution like `${env:PATH}`](https://code.visualstudio.com/docs/editor/variables-reference) does not work for go.toolsEnvVars configuration. `/Users/xxx/.gvm/gos/go1.15` is already set as `go.goroot`, so I don't think it's necessary to set `"go.toolsEnvVars"` `PATH`. Can you try to remove the "PATH" property?

**Comment by zhiqiangxu** [comment]
After remove PATH from `"go.toolsEnvVars"`, it works!

Why adding PATH screws up the debugger?

**Comment by hyangah** [comment]
> Why adding PATH screws up the debugger?
Actually, the error was from the build stage. The extension calls either `dlv debug` or `dlv test` depending on the target type. Dlv then, builds the target with necessary debug info, in the given environments. Since the `PATH` doesn't include all the tools necessary to build the target, the build failed.

> How to make the debug button automatically appear above `main` function entry?
That is https://github.com/golang/vscode-go/issues/159. For running `main`, you can just press F5 (Run Debug) or Ctrl+F5 (Run without Debug).

I hope all questions were answered. Feel free to reach out in the gophers slack or https://github.com/golang/vscode-go/discussions/categories/q-a, and reports bugs in this issue tracker. Happy coding!

**Comment by zhiqiangxu** [comment]
Thanks！
