### ISSUE TITLE
Invalid code colorization due to back slash at the end of the single quoted string   

### ISSUE THREAD

**Issue by regorov** [golang/vscode-go#1164]
### Versions

vscode-go: v0.22.0

### Steps to reproduce the behavior:
Enter following line
```
	fmt.Println(`hello world C:\`)
        
        // all following text will be colored as text
```

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/2199318/106501808-da5f2180-64c3-11eb-87c0-7fa7543d3d9b.png)

**Comment by hyangah** [comment]
The default syntax highlighting is done by VS Code, not this extension.
What is the version of your VS Code?
With 1.52.1, I couldn't reproduce this issue.

**Comment by regorov** [comment]
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.11-arch1-1

**Comment by hyangah** [comment]
That's really strange.
Please file an issue in github.com/microsoft/vscode issue tracker - with necessary info such as the vscode version and your vscode settings. Thanks!
