### ISSUE TITLE
In a multi-module setup, enabling languageserver=true does not resolve modules 

### ISSUE THREAD

**Issue by rajkrishnamurthy** [golang/vscode-go#1166]
### Describe the bug
I have the following setup:
/workspace
     /src
          /commonlib
              /constants
                  constants.go
                  ...other files/folders
              /types
                  types.go
                  ...other files/folders           
              go.mod
              go.sum
          /module1
              module.go
              go.mod
              go.sum
          /module2
              module.go
              go.mod
              go.sum
.....
I "import commonlib/constants" and have module1/go.mod replace cowcommonlibs => ../cowcommonlibs. 
I'm connecting to this workspace using remote-ssh extension. When I enable (or default) Language Server, I cannot resolve any references specified in go.mod. However, when I disable Language Server, the problem goes away. 

 

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.15.6 linux/amd64 (remote 
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.6.4
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.52.1 
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.22.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/rajkrishnamurthy/go
GOROOT: /usr/local/go
PATH: /home/rajkrishnamurthy/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/bin:/home/rajkrishnamurthy/.local/bin:/home/rajkrishnamurthy/go/bin:/home/rajkrishnamurthy/.local/bin:/home/rajkrishnamurthy/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/bin:/home/rajkrishnamurthy/.local/bin:/home/rajkrishnamurthy/go/bin:/home/rajkrishnamurthy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin

   gopkgs: /home/rajkrishnamurthy/go/bin/gopkgs installed
   go-outline: /home/rajkrishnamurthy/go/bin/go-outline installed
   gotests: gotests not installed
   gomodifytags: /home/rajkrishnamurthy/go/bin/gomodifytags installed
   impl: /home/rajkrishnamurthy/go/bin/impl installed
   goplay: /home/rajkrishnamurthy/go/bin/goplay installed
   dlv: /home/rajkrishnamurthy/go/bin/dlv installed
   golint: /home/rajkrishnamurthy/go/bin/golint installed
   gopls: /home/rajkrishnamurthy/go/bin/gopls installed

go env
Workspace Folder (ComplianceCow): /home/rajkrishnamurthy/coding/continube/ComplianceCow
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/rajkrishnamurthy/.cache/go-build"
	GOENV="/home/rajkrishnamurthy/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/rajkrishnamurthy/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/rajkrishnamurthy/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build389662700=/tmp/go-build -gno-record-gcc-switches"
	

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
    "go.useLanguageServer": true,
    "go.languageServerFlags": [
        "-rpc.trace"
    ],
    "[go]": {
        

        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },

**Comment by stamblerre** [comment]
Please take a look at https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules to see if you can address this issue by using workspace folders.
