### ISSUE TITLE
debug: gcflags set by user should be ignored when debugging

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#117]
As described in https://github.com/microsoft/vscode-go/issues/2415, gcflags set by the user interferes with debugging. This issue is to have the extension ignore this setting when debugging.

While https://github.com/microsoft/vscode-go/issues/2415 is about debugging tests, this may apply to normal debugging as well

**Comment by stamblerre** [comment]
@hyangah: How do you feel about this? I am nervous the ignore any user-set flags, and would maybe prefer to surface an error message.

**Comment by ramya-rao-a** [comment]
This would be similar to the other issue where we have user set GOOS and GOARCH. Basically user settings that would mess with delve

**Comment by hyangah** [comment]
Removing gcflags, GOOS, GOARCH when launching through debugger makes sense. We will do it.
To avoid user confusion, we need to notify users of this modification when those conflicting settings are detected.

/cc @suzmue @polinasok 

@suzmue also questioned whether we should apply similar changes on GOOS/GOARCH when running tests.

**Comment by szmcdull** [comment]
Hi, I need -gcflags='-G=3' to enable generics. But seems vscode cannot do this. Neither gopls nor dlv-dap is using the gcflags.

**Comment by polinasok** [comment]
@szmcdull If you want dlv to build things for you, then it will supply its own `gcflags`. If you prefer to customize those, then you can build the binary directly and let dlv/vscode execute it with `exec` mode.
