### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by Nizom98** [golang/vscode-go#1171]
gopls version: v0.6.4
gopls flags: 
extension version: 0.22.0
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: unsupported URI schemes: [{ssh://izba/ SSH FS - izba}] (gopls only supports file URIs)
  Code: 0 
</pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
The language server cannot handle SSH URIs (see https://github.com/golang/vscode-go/issues/1160). 
@hyangah has suggested a few alternatives, like [dev containers](https://code.visualstudio.com/docs/remote/troubleshooting#_using-an-ssh-tunnel-to-connect-to-a-remote-docker-host) or [VSCode Remote - SSH or Remote -WSL](https://code.visualstudio.com/docs/remote/ssh). If those alternatives don't work, the best workaround would be to disable the language server with the setting `"go.useLanguageServer": false`.
