### ISSUE TITLE
debug: implement set variable (dlv-dap)

### ISSUE THREAD

**Issue by rspruyt-google** [golang/vscode-go#1173]
Duplicate of #890

Bug report as requested by @hakim from internal Google discussion trying to set VS Code values. Here we attempt to change a string value from "Google" to "Randy".

When trying to set a variable value in VS Code, the value fails to set. An integer value does set correctly however, so this may be specific to strings.

StackTrace
```
Failed to set variable - could not find symbol value for Randy
locations [{"pc":93919450674442,"file":"<<redacted>>/debugging/demo/main.go","line":33,"function":{"name":"main.main","value":93919450674080,"type":0,"goType":0,"optimized":false},"Locals":[{"name":"args","addr":824635629360,"onlyAddr":false,"type":"[]string","realType":"[]string","flags":0,"kind":23,"value":"","len":0,"cap":0,"children":[],"base":824633795024,"unreadable":"","LocationExpr":"[block] DW_OP_fbreg -0x58 ","DeclLine":18},{"name":"str1","addr":824635629296,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"Hello","len":5,"cap":0,"children":[],"base":93919450679567,"unreadable":"","LocationExpr":"[block] DW_OP_fbreg -0x98 ","DeclLine":21},{"name":"str2","addr":824635629280,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"Google","len":6,"cap":0,"children":[],"base":93919450680644,"unreadable":"","LocationExpr":"[block] DW_OP_fbreg -0xa8 ","DeclLine":22},{"name":"combined","addr":824635629312,"onlyAddr":false,"type":"string","realType":"string","flags":0,"kind":24,"value":"Hello Google!","len":13,"cap":0,"children":[],"base":824633813472,"unreadable":"","LocationExpr":"[block] DW_OP_fbreg -0x88 ","DeclLine":29}],"Arguments":[],"FrameOffset":-120,"FramePointerOffset":-136,"Defers":[],"Err":""},{"pc":93919447800137,"file":"third_party/go/gc/src/runtime/proc.go","line":204,"function":{"name":"runtime.main","value":93919447799616,"type":0,"goType":0,"optimized":true},"Locals":[{"name":"g","addr":824635[...]
Last known immediate stacktrace (goroutine id 1):
	<<redacted>>/debugging/demo/main.go:33
		main.main
	<<redacted>>/src/runtime/proc.go:204
		runtime.main
	<<redacted>>/src/runtime/asm_amd64.s:1374
		runtime.goexit
```

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.

go version go1.15.6 linux/amd64

* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.

Build info
----------
golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200708181441-6004c8539734 h1:Vc0Vx98oU/O3+qPQ36fnTT5UduS55KLh2uSGbL7mqEo=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.15.6 linux/amd64

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.

(on MacOS):

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

* Check your installed extensions to get the version of the VS Code Go extension

0.22.0

* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.

Redacted. Ping me, rspruyt@ internally if you'd like this info

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

Default (no settings.json for this project)

### Describe the bug

I am unable to change the value of a string value while debugging.

### Steps to reproduce the behavior:

Run the go debugging codelab (or ask me directly internally rspruyt@)

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by polinasok** [comment]
Please include the request/response logs before the error. That would give us more info as to what was happening.

I just tried doing this myself with "Set Value" via VARIABLES pane. 
Code
```
	mystr := "abc"
```
From log
```
{
  "name": "mystr",
  "value": "\"abc\"",
  "evaluateName": "mystr",
  "variablesReference": 0
 },
```

I got the following behavior trying to:
* Setting to `"foo"` (with quotes) results in the following error
```
[20:34:30.737 UTC] From client: setVariable({"variablesReference":1000,"name":"mystr","value":"\"foo\""})
[20:34:30.738 UTC] SetVariableRequest
2021-02-02T12:34:30-08:00 debug layer=rpc <- RPCServer.Set(rpc2.SetIn{"Scope":{"GoroutineID":1,"Frame":0,"DeferredCall":0},"Symbol":"mystr","Value":"\"foo\""})
2021-02-02T12:34:30-08:00 debug layer=rpc -> *rpc2.SetOut{} error: "literal string can not be allocated because function calls are not allowed without using 'call'"
[20:34:30.743 UTC] [Error] Failed to set variable - literal string can not be allocated because function calls are not allowed without using 'call'
[20:34:30.744 UTC] To client: {"seq":0,"type":"response","request_seq":11,"command":"setVariable","success":false,"message":"Failed to set variable: literal string can not be allocated because function calls are not allowed without using 'call'","body":{"error":{"id":2010,"format":"Failed to set variable: literal string can not be allocated because function calls are not allowed without using 'call'","showUser":true}}}
```
* Setting to `foo` (without quotes) results in the following error
```
20:39:05.913 UTC] From client: setVariable({"variablesReference":1000,"name":"mystr","value":"foo"})
[20:39:05.913 UTC] SetVariableRequest
2021-02-02T12:39:05-08:00 debug layer=rpc <- RPCServer.Set(rpc2.SetIn{"Scope":{"GoroutineID":1,"Frame":0,"DeferredCall":0},"Symbol":"mystr","Value":"foo"})
2021-02-02T12:39:05-08:00 debug layer=rpc -> *rpc2.SetOut{} error: "could not find symbol value for foo"
[20:39:05.920 UTC] [Error] Failed to set variable - could not find symbol value for foo
[20:39:05.920 UTC] To client: {"seq":0,"type":"response","request_seq":12,"command":"setVariable","success":false,"message":"Failed to set variable: could not find symbol value for foo","body":{"error":{"id":2010,"format":"Failed to set variable: could not find symbol value for foo","showUser":true}}}
```
The second one makes sense as it is treated as an expression with a variable name. I need to dig a bit more to understand what's wrong with the first one.

**Comment by polinasok** [comment]
Tried this with just dlv:

```
(dlv) set mystr = "foo"
Command failed: literal string can not be allocated because function calls are not allowed without using 'call'
(dlv) call mystr = "foo"
...
(dlv) p mystr
"foo"
```

Looks like we need to special case string values/variables and send a call request to dlv.

**Comment by polinasok** [comment]
In the meantime, the workaround would be to use that expression "call <somevar> = "..."" in the Debug Console.

**Comment by polinasok** [comment]
As there is a workaround, I propose that we do not fix this in the original adapter, but address this in the new dlv-dap adapter we are working on.
