### ISSUE TITLE
debug: changing to a different goroutine and executing Step Over goes back to the previous goroutine

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#118]
_From https://github.com/microsoft/vscode-go/issues/2560 by @aarzilli:_

1. Debug https://github.com/aarzilli/delve_client_testing/blob/master/08gswitch/main.go
2. Click on one of the paused goroutines executing `main.coroutine` in the left column
3. Click Step Over

### Expected:

Cursor moves to the next line on the goroutine I'm currently watching.

### What actually happend

Debuggers switches back to the goroutine it was originally stopped at and moves to the next line.

**Comment by polinasok** [comment]
There is a TODO for this in dlv-dap as well:
https://github.com/go-delve/delve/blob/84328ed8703eb493072899d418ab04a4b37759e5/service/dap/server.go#L646

**Comment by polinasok** [comment]
Was about to close this, but you beat me to it! Thank you for making the change @suzmue! Just tried it for myself - works great!
