### ISSUE TITLE
Go autocomplete stops working if project contains errors

### ISSUE THREAD

**Issue by distinctdan** [golang/vscode-go#1181]
While I'm writing code in a Go file, the autocomplete and Go To Definition functionality sometimes stops working if the project contains an error. The autocomplete doesn't start working again until I've fixed most of the errors in the project. This is annoying and makes vscode-go basically useless to do any large scale refactoring. From my experience, this doesn't happen for other languages like TypeScript, where the autocomplete continues working even if your project contains errors.

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.15.2 darwin/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- `zsh: command not found: gopls`
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `zsh: command not found: code`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.22.0`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
<details>
<summary>Command output: </summary>
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/my.name/go
GOROOT: /usr/local/go
PATH: /Users/my.name/.pyenv/shims:/Users/my.name/.nvm/versions/node/v12.18.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin

   gopkgs: /Users/my.name/go/bin/gopkgs installed
   go-outline: /Users/my.name/go/bin/go-outline installed
   gotests: /Users/my.name/go/bin/gotests installed
   gomodifytags: /Users/my.name/go/bin/gomodifytags installed
   impl: /Users/my.name/go/bin/impl installed
   goplay: /Users/my.name/go/bin/goplay installed
   dlv: /Users/my.name/go/bin/dlv installed
   golint: /Users/my.name/go/bin/golint installed
   gopls: /Users/my.name/go/bin/gopls installed

go env
Workspace Folder (my-repo): /Users/my.name/git/my-repo
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/my.name/Library/Caches/go-build"
	GOENV="/Users/my.name/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/my.name/go/pkg/mod"
	GONOPROXY="github.com/myorg,git.myorg.com/myorg-developers"
	GONOSUMDB="github.com/myorg,git.myorg.com/myorg-developers"
	GOOS="darwin"
	GOPATH="/Users/my.name/go"
	GOPRIVATE="github.com/myorg,git.myorg.com/myorg-developers"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/my.name/git/my-repo/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/jzrn96rn02765bbr_chytlh80000gn/T/go-build125489229=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
Workspace Folder (my-repo-2): /Users/my.name/git/my-repo-2
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/my.name/Library/Caches/go-build"
	GOENV="/Users/my.name/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/my.name/go/pkg/mod"
	GONOPROXY="github.com/myorg,git.myorg.com/myorg-developers"
	GONOSUMDB="github.com/myorg,git.myorg.com/myorg-developers"
	GOOS="darwin"
	GOPATH="/Users/my.name/go"
	GOPRIVATE="github.com/myorg,git.myorg.com/myorg-developers"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/my.name/git/my-repo-2/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/jzrn96rn02765bbr_chytlh80000gn/T/go-build925074542=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
Workspace Folder (my-repo-3): /Users/my.name/git/my-repo-3
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/my.name/Library/Caches/go-build"
	GOENV="/Users/my.name/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/my.name/go/pkg/mod"
	GONOPROXY="github.com/myorg,git.myorg.com/myorg-developers"
	GONOSUMDB="github.com/myorg,git.myorg.com/myorg-developers"
	GOOS="darwin"
	GOPATH="/Users/my.name/go"
	GOPRIVATE="github.com/myorg,git.myorg.com/myorg-developers"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/my.name/git/my-repo-3/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/jzrn96rn02765bbr_chytlh80000gn/T/go-build374100039=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
Workspace Folder (tests): /Users/my.name/git/my-repo-3/tests
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/my.name/Library/Caches/go-build"
	GOENV="/Users/my.name/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/my.name/go/pkg/mod"
	GONOPROXY="github.com/myorg,git.myorg.com/myorg-developers"
	GONOSUMDB="github.com/myorg,git.myorg.com/myorg-developers"
	GOOS="darwin"
	GOPATH="/Users/my.name/go"
	GOPRIVATE="github.com/myorg,git.myorg.com/myorg-developers"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/my.name/git/my-repo-3/tests/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/jzrn96rn02765bbr_chytlh80000gn/T/go-build174786136=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
Workspace Folder (my-repo-4): /Users/my.name/git/my-repo-4
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/my.name/Library/Caches/go-build"
	GOENV="/Users/my.name/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/my.name/go/pkg/mod"
	GONOPROXY="github.com/myorg,git.myorg.com/myorg-developers"
	GONOSUMDB="github.com/myorg,git.myorg.com/myorg-developers"
	GOOS="darwin"
	GOPATH="/Users/my.name/go"
	GOPRIVATE="github.com/myorg,git.myorg.com/myorg-developers"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/my.name/git/my-repo-4/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/jzrn96rn02765bbr_chytlh80000gn/T/go-build878402745=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
Workspace Folder (my-repo-5): /Users/my.name/git/my-repo-5
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/my.name/Library/Caches/go-build"
	GOENV="/Users/my.name/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/my.name/go/pkg/mod"
	GONOPROXY="github.com/myorg,git.myorg.com/myorg-developers"
	GONOSUMDB="github.com/myorg,git.myorg.com/myorg-developers"
	GOOS="darwin"
	GOPATH="/Users/my.name/go"
	GOPRIVATE="github.com/myorg,git.myorg.com/myorg-developers"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/my.name/git/my-repo-5/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/jzrn96rn02765bbr_chytlh80000gn/T/go-build671688906=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited
Go specific settings:
```
    "go.formatTool": "goimports",
    "go.enableCodeLens": {
        "references": false,
        "runtest": false
    },
```

**Comment by hyangah** [comment]
Thanks for the report @distinctdan 
Can you please share what types of errors you had to fix to make the autocomplete/navigation feature work again?
Example to reproduce the issue will be super-helpful.

cc @stamblerre

**Comment by distinctdan** [comment]
Thanks @hyangah, I'm not sure exactly, but here are some examples of things I was doing:
 - Renamed a method that was used in a lot of places
 - Renamed/moved a package. I expect this will break autocomplete for things using this package, but I still expect autocomplete to work within the package
 - Doing a large refactor. If I've changed enough things in the project, autocomplete and error checking totally dies until enough errors are fixed, even if the package I'm working on doesn't import any of the packages with errors. I generally do refactors "bottom-up", so I'll start at the lower level packages that don't depend on anything, then work my way up to the higher level ones. However, when autocomplete breaks, it makes this painful to do.

Generally, vscode seems to have a very low number of errors that it will display at a time. It starts displaying them at an arbitrary file, and if you're working on a different file, it just doesn't show any until you go fix that other file first.

**Comment by stamblerre** [comment]
The next time you see this issue, can you please share your `gopls` logs with us? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information). There is not much that we can investigate without a repro case or a log.

**Comment by distinctdan** [comment]
K, here's one. This happens pretty frequently. So I moved a block of code, and was trying to CMD-click an interface to get its definition, but vscode's autocomplete totally died for the file. I checked the gopls logs and found this:
```
[Error - 1:12:37 PM] 2021/02/04 13:12:37 imports fixes: AllImportsFixes: /Users/my.name/git/my-repo/my-project/goauth.go:99:2: expected operand, found '}' (and 263 more errors)
	file="/Users/my.name/git/my-repo/my-project/goauth.go"

[Error - 1:12:46 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Error - 1:12:47 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Error - 1:12:47 PM] 2021/02/04 13:12:47 imports fixes: AllImportsFixes: /Users/my.name/git/my-repo/my-project/goauth.go:99:2: expected operand, found '}' (and 263 more errors)
	file="/Users/my.name/git/my-repo/my-project/goauth.go"
```
So it looks like when I moved the block, I missed a closing `}`. In other languages I've worked in, the editor is smart enough to limit the scope of errors, so if you have a typo, it doesn't kill all autocomplete features for the whole file, it just limits the scope to that block of code.

**Comment by stamblerre** [comment]
For an issue like this, we would really need a repro case to isolate and fix it.

**Comment by stamblerre** [comment]
Closing, as this has been in a WaitingForInfo state for a few months.
