### ISSUE TITLE
WINDOWS INSTALATION NOT GOOD

### ISSUE THREAD

**Issue by DBJDBJ** [golang/vscode-go#1189]
2021 FEB 04  WIN10 PRO  i5 CPU 8GB 

Installed GO and GO extension twice ... still, something is wrong, 

This is the situation when I open the GO project

![image](https://user-images.githubusercontent.com/145155/106913788-a757a080-6704-11eb-835f-049326c4695b.png)

> Notice the "Go Update Available" ... that is also a problem as I have installed the latest GO twice today.

And this is the gopls(server) output

![image](https://user-images.githubusercontent.com/145155/106914375-3fee2080-6705-11eb-8d58-2697fac416e1.png)

GO  is installed in `C:\go` and I can use go to compile etc ... 

Code is exactly the same as on the introductory video. I can debug, still, I have the GOPATH/GOROOT warning

![image](https://user-images.githubusercontent.com/145155/106914994-d6badd00-6705-11eb-92e1-bcd0485ac3f5.png)

Please advise ...

**Comment by hyangah** [comment]
Can you please share your go extension settings?
As the warning and error messages indicate the GOPATH shouldn't be set to `c:\go`.

**Comment by DBJDBJ** [comment]
I do want to be "module compliant go citizen", I assume you want to see my  userspace settings JSON, here it is:

![image](https://user-images.githubusercontent.com/145155/106916573-a07e5d00-6707-11eb-8b96-0115647f9d13.png)

**Comment by DBJDBJ** [comment]
I think I am getting myself out of the rabbit hole ...  I understand now how to move to module based source, etc ...


thanks for your immediate response ... I will post here if I hit the brick wall again ..

**Comment by DBJDBJ** [comment]
it seems to `GOPATH` has to be completely eradicated from the local machine before the very latest (4FEB) VSCode GO extension is installed. It seems  `gopls`  server gets utterly confused if it is not...? That, in turn, is the cause of this odd behavior.
