### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by prabinv** [golang/vscode-go#1194]
gopls version: v0.6.5
gopls flags: 
extension version: 0.22.0
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

I got the error when running the _Go: Install/Update Tools_ command in VS Code and selecting gopls (along with others).

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

```
[Error - 11:05:31 AM] Starting client failed
Error: Connection got disposed.
    at Object.dispose (/Users/prabin_varma/.vscode/extensions/golang.go-0.22.0/dist/goMain.js:77783:27)
    at Object.dispose (/Users/prabin_varma/.vscode/extensions/golang.go-0.22.0/dist/goMain.js:10726:35)
    at /Users/prabin_varma/.vscode/extensions/golang.go-0.22.0/dist/goMain.js:12904:28
[Info  - 11:05:36 AM] 2021/02/05 11:05:36 go env for /Users/prabin_varma/Documents/Github/v1-checkout-new
(root /Users/prabin_varma/Documents/Github/v1-checkout-new)
(go version go version go1.15.8 darwin/amd64)
(valid build configuration = false)
(build flags: [])
GOPROXY=https://proxy.golang.org,direct
GOSUMDB=sum.golang.org
GONOSUMDB=
GOPATH=/Users/prabin_varma/Documents/Github/go-projects
GO111MODULE=
GOCACHE=/Users/prabin_varma/Library/Caches/go-build
GOFLAGS=
GOPRIVATE=
GOINSECURE=
GOMODCACHE=/Users/prabin_varma/Documents/Github/go-projects/pkg/mod
GONOPROXY=
GOMOD=
GOROOT=/usr/local/go


[Info  - 11:05:36 AM] 2021/02/05 11:05:36 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./ builtin]
	packages=2

[Info  - 11:05:36 AM] 2021/02/05 11:05:36 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:05:36 AM] 2021/02/05 11:05:36 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:05:36 AM] 2021/02/05 11:05:36 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:07:53 AM] 2021/02/05 11:07:53 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:07:53 AM] 2021/02/05 11:07:53 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:07:53 AM] 2021/02/05 11:07:53 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:40:48 AM] 2021/02/05 11:40:48 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1

[Info  - 11:40:48 AM] 2021/02/05 11:40:48 go/packages.Load
	snapshot=0
	directory=/Users/prabin_varma/Documents/Github/v1-checkout-new
	query=[./]
	packages=1
```

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Thanks for the report @prabinv. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was editing settings.json, I just installed/updated gopls, I just opened up the window, etc.)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by prabinv** [comment]
> Thanks for the report @prabinv. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was editing settings.json, I just installed/updated gopls, I just opened up the window, etc.)?
> ![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

@stamblerre Sorry about not adding that info. I have updated the issue to add details and the stack trace. Hope it is helpful.

**Comment by stamblerre** [comment]
Thank you for sharing that! Has the issue been resolved / is the language server working for you now?

**Comment by prabinv** [comment]
I reopened VS Code, ran the install again, and it went through.

**Comment by stamblerre** [comment]
Glad to hear it's working again--thank you for following up! Going to close this issue.
