### ISSUE TITLE
Não carrega a ajuda dinâmica para um programa especifico

### ISSUE THREAD

**Issue by fernandoxl** [golang/vscode-go#1200]
Issue Type: <b>Feature Request</b>

Em programa específico que estou usando para estudo, ao passar o mouse por sobre as funções, o visual studio apresenta apenas a mensagem "Carregando..." e logo apaga, não trazendo o popup com os detalhes da função

Extension version: 0.22.0
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19041

**Comment by hyangah** [comment]
Thanks for filing an issue - I don't speak in Portugese so I used google translate. 

> Does not load dynamic help for a specific program 
>
> when hovering over the functions, visual studio displays only the message "Loading ..." and then deletes, without bringing up the popup with the function details 

Please follow the troubleshooting guide (https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#make-sure-your-project-compiles). In particular, check if there is any error status message in the bottom of the vscode window, or the PROBLEMS pane.

If you are still having an issue, please share your settings and the gopls log ([instruction](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)). Screenshot or video recordings are also helpful.
