### ISSUE TITLE
Feature request: support Go project template

### ISSUE THREAD

**Issue by Prajwal-Koirala** [golang/vscode-go#1205]
Hello,
So i have been using golang for a while and one of the major things i saw was missing was a structure for golang apps like flutter apps, so i created `gocreate`

https://github.com/complexorganizations/gocreate

Feel free to fork or copy or modify or whatever you want with it, and i was wondering if the devs would add this as one of the suggested installed.

**Comment by hyangah** [comment]
Thanks for the feature request and writing a tool for it. My concern is that there is no official standard or widely agreed standard for go project structure other than having `go.mod` in the project root directory. The golang-standard project the `gocreate` tool is based on also clearly states the fact.

**Comment by Prajwal-Koirala** [comment]
> Thanks for the feature request and writing a tool for it. My concern is that there is no official standard or widely agreed standard for go project structure other than having `go.mod` in the project root directory. The golang-standard project the `gocreate` tool is based on also clearly states the fact.

https://github.com/complexorganizations/gocreate#credits

Its there.
