### ISSUE TITLE
settings: restructure build/vet/lint to make sure all errors are surfaced

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#121]
As described in https://github.com/microsoft/vscode-go/issues/2985, when both build and vet on save features are disabled, and there is critical error when running the linter, there is no diagnostic shown to the user. When build or vet on save feature is enabled, it takes care of surfacing such errors.

**Comment by stamblerre** [comment]
It seems strange to me that someone might enable lint or vet, but not build errors. My proposal would be to modify the `buildOnSave`, `vetOnSave`, and `lintOnSave` settings and instead make them hierarchical - something like "go.showErrors", which can be either "build", "vet", or "lint".

/cc @hyangah

**Comment by ramya-rao-a** [comment]
Given that `gopls` would handle most of the diagnostics moving forward, I would caution against modifying existing settings of build/vet/lint on save.

We can on the other hand tweak the `runTool()` utility function. It currently takes a flag `useStdErr` which is true for build and vet, false for linters.  When this false, and the running of the tool fails, we can return a generic error that the tool failed to run with the error message and map it to the start of the file.

**Comment by pztrn** [comment]
@stamblerre for example: I do not want to build or vet separately, I want to get golangci-lint output in problems view. If vet or build is disabled I got nothing in problems view at all, but when I run golangci-lint manually I'll get compilation errors in console. This can only be solved by enabling vetOnSave which might be considered as "overkill" - golangci-lint already doing it.

The whole reason of this report was "hey, if golangci-lint is supported, then why go plugin for vscode cannot process anything else than something that starts with filename:lineno and report it to me?".

If plugin will move to use `gopls` by default and/or will get rid of ability to run linters manually - it can be closed.

(microsoft#2985 is reported by me)

**Comment by hyangah** [comment]
@stamblerre @pztrn @ramya-rao-a @suzmue We enabled gopls by default recently and the build/vet errors are provided by gopls. The linters are not replaced by gopls and the plugin still runs linter. We are presenting the union of diagnostics from gopls and linter now.

There may be a small number of users who currently chose to disable gopls diagnostics ( `go.languageServerExperimentalFeatures.diagnostics`) and they may still experience this issue, but I hope they know what they are doing.  :-) Can we close this?

**Comment by stamblerre** [comment]
Closing sounds good to me.
