### ISSUE TITLE
gopls: json: cannot unmarshal object into Go struct field

### ISSUE THREAD

**Issue by ditkyama** [golang/vscode-go#1216]
gopls version: (devel)
gopls flags: 
extension version: 0.22.1
environment: Visual Studio Code darwin
initialization error: Error: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@ditkyama Looks like you are using an old, dev version of gopls. Please update `gopls`, by running either
`Cmd+Shift+P` -> "Go: Install/Update Tools" -> select 'gopls', or by running a command from the terminal
`cd; GO111MODULE=on go get golang.org/x/tools/gopls`.
