### ISSUE TITLE
while saving, go extension changes formats to unexecutable manner

### ISSUE THREAD

**Issue by faizal1712** [golang/vscode-go#1222]
Issue Type: <b>Bug</b>

on saving it produces error in code due to wrong formatting

Extension version: 0.22.1
VS Code version: Code 1.53.1 (5d424b828ada08e1eb9f95d6cb41120234ef57c7, 2021-02-08T23:29:42.785Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.36GB free)|
|Process Argv|--crash-reporter-id 436e86ed-f68f-48f3-aa81-86e53c4a82cd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by hyangah** [comment]
@faizal1712 I saw some Windows users experience similar issues when using CRLF. Can you try to switch to LF (the bottom of the window)? 
![Screen Shot 2021-02-11 at 8 43 11 AM](https://user-images.githubusercontent.com/4999471/107644538-8bdd2000-6c45-11eb-90fa-1cfc9bad5186.png)

If you still see the issue, can you please share the language server trace?
Here is the [instruction](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information) for how to capture gopls trace.
