### ISSUE TITLE
debug: support Logpoints

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#123]
_From https://github.com/microsoft/vscode-go/issues/1751 by @lggomez:_

Logpoints are a special kind of breakpoint provided by VS Code that just logs messages unpon being hit, instead of stopping and showing the current stack trace/frame information

The difference between a regular breakpoint and a logpoint seems to be in this property: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1413-L1414

We could support this although I'm still not sure on how to bypass the SetBreakPointsRequest delve apicalls  and still be able to track the logpoints

This belongs to the [SourceBreakpoint](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1404) interface so I guess it is related to #1676

**Comment by ramya-rao-a** [comment]
This feature request has quite a few upvotes in https://github.com/microsoft/vscode-go/issues/1751, please follow the discussion there for more context

**Comment by ig0rsky** [comment]
@ramya-rao-a so what happened? any news?

**Comment by blacktop** [comment]
Please add 🙏

**Comment by suzmue** [comment]
Log points are now available at tip with dlv dap, and will be in the next delve release.
