### ISSUE TITLE
Error while running golangci-lint: can't combine options --disable-all and --disable errcheck

### ISSUE THREAD

**Issue by leguminosa** [golang/vscode-go#1230]
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?

<details><summary><code>❯ go version</code></summary><br><pre>
go version go1.13.9 linux/amd64
</pre></details>

<details><summary><code>❯ gopls -v version</code></summary><br><pre>
Build info
----------
golang.org/x/tools/gopls v0.6.5
    golang.org/x/tools/gopls@v0.6.5 h1:kLt9rD/dWtVdvc8LmdcxagDFih6zxYXREpKSYYZu5KE=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.0 h1:8pl+sMODzuvGJkmj2W4kZihvVb5mKm8pB/X44PIQHv8=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
    golang.org/x/tools@v0.1.1-0.20210201201750-4d4ee958a9b7 h1:/wdPW261t381NDQd8TBo63/FyvACfLICwtH8wMRoHJQ=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
</pre></details>

<details><summary><code>❯ code -v</code></summary><br><pre>
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
</pre></details>

<details><summary>VS Code Go extension version</summary><br><pre>
v0.22.1
</pre></details>

![image](https://user-images.githubusercontent.com/38403278/108020583-3e9aed00-704f-11eb-92b4-cf305c624ac0.png)

<details><summary><code>❯ Go: Locate Configured Go Tools</code></summary><br><pre>
go env
Workspace Folder (rechargeapp): /home/leguminosa/workspace/tokopedia/rechargeapp
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/leguminosa/.cache/go-build"
	GOENV="/home/leguminosa/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GONOPROXY="github.com/tokopedia/*"
	GONOSUMDB="github.com/tokopedia/*"
	GOOS="linux"
	GOPATH="/home/leguminosa/.gvm/pkgsets/go1.13.9/global"
	GOPRIVATE="github.com/tokopedia/*"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/home/leguminosa/.gvm/gos/go1.13.9"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/home/leguminosa/.gvm/gos/go1.13.9/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/leguminosa/workspace/tokopedia/rechargeapp/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build950403742=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

<details><summary><code>❯ Preferences: Open Settings (JSON)</code></summary><br><pre>
{
    "go.formatTool": "goimports"
}
</pre></details>

<details><summary><code>❯ Preferences: Open Workspace Settings (JSON)</code></summary><br><pre>
{
    // "go.gopath": "/home/leguminosa/.gvm/pkgsets/go1.13.9/global",
    // "go.goroot": "/home/leguminosa/.gvm/gos/go1.13.9",
    "go.coverOnSave": true,
    "go.coverOnSingleTest": true,
    "go.coverOnSingleTestFile": true,
    // "go.coverShowCounts": true,
    "go.coverageDecorator": {
        // "type": "gutter",
        "type": "highlight",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "blockred"
    },
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        // "--disable=govet",
        "--disable=errcheck",
        "--enable=gocyclo",
        "--enable=gocognit"
    ],
    "go.useLanguageServer": true,
    "go.languageServerFlags": [
        "--rpc.trace"
    ]
}
</pre></details>

### Describe the bug
On save, it will run golangci-lint, and it always gives error below.
```
Starting linting the current package at /home/leguminosa/workspace/tokopedia/rechargeapp/src/recharge/mkm
Error while running tool: /home/leguminosa/.gvm/pkgsets/go1.13.9/global/bin/golangci-lint run --disable=errcheck --enable=gocyclo --enable=gocognit --print-issued-lines=false --out-format=colored-line-number --issues-exit-code=0
level=error msg="Running error: can't combine options --disable-all and --disable errcheck"
```

### Steps to reproduce the behavior:
1. Save the project anywhere
2. Golangci-lint will run
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/38403278/108022035-59229580-7052-11eb-876b-9adf0bf1bb08.png)

**Comment by hyangah** [comment]
Please check if there is golangci-lint configuration file in the repository (https://golangci-lint.run/usage/configuration/#config-file) and `disable-all` setting is present there.

**Comment by leguminosa** [comment]
thank you i'll look into it now

**Comment by leguminosa** [comment]
@hyangah ah I understand what's going on now,

I used to feed the golangci-lint flags from my workspace settings (file on the right) since I was one of few engineers that has been using golangci-lint on our repo, and latter, when golangci-lint became almost "de facto", my friend added the config file (`.golangci.yaml` on the left)
![image](https://user-images.githubusercontent.com/38403278/108091064-e5ae7180-70ad-11eb-9df6-36c1d47457ff.png)

i deleted `go.lintFlags` and it works again like usual...

so, since we are already using config file, so i don't need to use `go.lintFlags` anymore?

**Comment by hyangah** [comment]
@leguminosa Yes, you don't need `go.lintFlags` since you already have the configuration and all the necessary settings are there.

**Comment by leguminosa** [comment]
@hyangah thank you, so that wrapped things up right? then you may now close this issue as this problem has been resolved.

Thank you for your assistance, and rest well.
