### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by GitHubFatherIsMe** [golang/vscode-go#1233]
gopls version: v0.6.5
gopls flags: go.languageServerFlags
extension version: 0.22.1
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incorrect gopls command usage.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@GitHubFatherIsMe: It looks like you may have incorrectly configured the `"go.languageServerFlags"` setting. I suggest that you delete that setting and try reloading your editor.
