### ISSUE TITLE
debug: add replay mode to launch.json

### ISSUE THREAD

**Issue by icholy** [golang/vscode-go#1243]
**Is your feature request related to a problem? Please describe.**

There is no simple way to replay an rr execution trace. 

* https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_replay.md
* https://github.com/rr-debugger/rr

**Describe the solution you'd like**
I'd like to specify the path to the trace file in `launch.json`.
``` json
{
    "name": "Replay Trace",
    "type": "go",
    "request": "launch",
    "mode": "replay",
    "traceFile": "/home/icholy/.local/share/rr/my.test-121",
    "program": "${workspaceFolder}"
}
```

**Describe alternatives you've considered**
I have tried starting `dlv replay`  in headless mode and connecting remotely with vscode, but it doesn't register the breakpoints.

**Comment by hyangah** [comment]
There is a WIP PR https://github.com/golang/vscode-go/pull/89 by @lggomez that adds the replay/coredump features to the old debug adapter.  @lggomez @polinasok @suzmue is it possible to port the pr in `delve dap`?

**Comment by lggomez** [comment]
@hyangah I've been completely out of the loop since the handover of the extension and the development of the new adapter so I'd be grateful if I could get a quick rundown of the new dap; I can check if the old WIP is still applicable

**Comment by polinasok** [comment]
Discussion now happening at https://github.com/go-delve/delve/pull/2367

**Comment by polinasok** [comment]
This feature is now available using the following in your `launch.json`
```
"request": "launch",
"mode": "replay",
"traceDirPath":"path/to/trace",
```
Thank you @lggomez for your contribution!

@icholy Please let us know if it is not working for you. Thank you.
