### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by vidhlakh** [golang/vscode-go#1249]
gopls version: v0.5.3
gopls flags: 
extension version: 0.21.1
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c6d88]

goroutine 6015 [running]:
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/internal/lsp/source.pathLinkAndSymbolName(0xc003913440, 0xc00007caa0, 0xc008f22320, 0xc0027b1040, 0x1b, 0xc00007ca01, 0xef99e0)
	  hover.go:186  0x2a8
golang.org/x/tools/internal/lsp/source.HoverIdentifier(0xf08d80, 0xc001c1cae0, 0xc003913440, 0x0, 0x0, 0x0)
	  hover.go:118  0x1b6
golang.org/x/tools/internal/lsp/source.Hover(0xf08cc0, 0xc0003ca800, 0xf1a860, 0xc0007fbc70, 0xf08f80, 0xc0003c3b00, 0x4057c00000000000, 0x4045800000000000, 0xf10d80, 0xc0003c3b00, ...)
	  hover.go:59  0xdb
golang.org/x/tools/internal/lsp.(*Server).hover(0xc0003629c0, 0xf08cc0, 0xc0003ca800, 0xc0035861b0, 0x0, 0x0, 0x0)
	  hover.go:25  0x2ce
golang.org/x/tools/internal/lsp.(*Server).Hover(0xc0003629c0, 0xf08cc0, 0xc0003ca800, 0xc0035861b0, 0xc0035861b0, 0x0, 0x0)
	  server_gen.go:96  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xf08cc0, 0xc0003ca800, 0xf1ce00, 0xc0003629c0, 0xc0035860c0, 0xf08f00, 0xc0003ca400, 0x0, 0xef6060, 0xc0019d4000)
	  tsserver.go:299  0x1afb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xf08cc0, 0xc0003ca800, 0xc0035860c0, 0xf08f00, 0xc0003ca400, 0x42719a5a, 0x136b280)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xf08cc0, 0xc0003ca800, 0xc0035860c0, 0xf08f00, 0xc0003ca400, 0x0, 0x0)
	  lsprpc.go:559  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xf08cc0, 0xc0003ca800, 0xc008e8e3c0, 0xf08f00, 0xc0003ca400, 0xc001e4be00, 0x20)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00028c5a0, 0xc000f59f20, 0xc0007081f0, 0xf08cc0, 0xc0003ca800, 0xc008e8e3c0, 0xf08f00, 0xc0003ca400)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 2:36:17 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.6.6. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

It also looks like you are using an old version of the Go extension for VS Code, so please update that as well.
