### ISSUE TITLE
bug: "Go: Build Workspace" fails when editing _test files in $GOPATH/src

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#125]
When the GOPATH/src folder is opened in VS Code, the command `Go:Build Workspace` fails if run after editing a test file. See https://github.com/microsoft/vscode-go/issues/1789 for more details on the root cause for the bug

**Comment by hyangah** [comment]
Go Modules is the default build mode, and now build-related diagnostics is handled by gopls, and `Go:Build Workspace` is not a useful command any more. 
Closing since the feature is no longer relevant to the extension's functionality.
