### ISSUE TITLE
Constantly get Error loading workspace: err: exit status 1

### ISSUE THREAD

**Issue by wtask** [golang/vscode-go#1250]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.15.8 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210222172741-77e031214674 h1:XzEjy9Ks1MwmcJOarbxTnL/AqHtzsRfRzAwfDhII2lE=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64

* Check your installed extensions to get the version of the VS Code Go extension
	- 0.22.1

### Describe the bug
I have multi-module repo. Inner module represent an gRPC API which is generated using vendor folder. The vendor folder is created temporarily, only for generation with `go mod vendor` inside sub-module directory. After generation was successfully done I constantly get an error related to vendor folder cannot be found. YES! The vendor folder is removed already.
 
```
Error loading workspace: err: exit status 1: stderr: go: gitlab.XXX.com/XXX/backend/DEPENDENCY/api@v1.9999999.0-goplsworkspace: parsing D:\Users\webta\Development\COMPANY\REPO\backend\MODULE\api\vendor\gitlab.XXX.com\XXX\backend\MODULE\api\go.mod: open D:\Users\webta\Development\COMPANY\REPO\backend\MODULE\api\vendor\gitlab.XXX.com\XXX\backend\DEPENDENCY\api\go.mod: The system cannot find the path specified. : packages.Load error
```
I see this error with spining icon in the status bar and gopls is not responding anymore. Therefore, I have 2 options to choose from - restart VSCode or wait for unknown duration (several minutes) for gopls will start working again.

**Comment by hyangah** [comment]
Thanks for the report. 
Can you please share your vscode `go` and `gopls` setting, and capture the gopls trace following [the instruction](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).
 
Currently multi-module repo needs special handling. Please follow the [instruction here](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules) if you haven't done so already.
