### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dc-sherlock** [golang/vscode-go#1255]
gopls version: v0.6.6
gopls flags: true
extension version: 0.22.1
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incorrect gopls command usage.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>
[gopls-log.txt](https://github.com/golang/vscode-go/files/6050378/gopls-log.txt)

**Comment by hyangah** [comment]
It looks like you are passing a wrong flag to gopls. Please reset `"go.languageServerFlags"`.
