### ISSUE TITLE
golang indent issue 

### ISSUE THREAD

**Issue by chenyihui555** [golang/vscode-go#1259]
拥有项目风格原因,系统使用4空格缩进格式。在设置  "editor.formatOnSave": true 时。按ctrl+s自动保存时，goformat工具会将文件重新被格式化成tab缩进。 使用了插件editorconfig了。还是无法覆盖goformat对文件的影响。不知道光大网友有什么高见？ 指点小弟....这个问题困扰了很久。
 
editorconfig文件配置如下：
![image](https://user-images.githubusercontent.com/31525637/109422953-9a368480-7a18-11eb-8939-5aa56ba7ad77.png)

**Comment by hyangah** [comment]
Thanks for the report @chenyihui555 

I am guessing you were talking about an issue similar to https://github.com/microsoft/vscode-go/issues/2871. If not please correct me.

This extension follows `gofmt`-style formatting and uses tabs. The purpose of `gofmt` is to have a single style that all gophers use and that includes the choice of using tabs over spaces. Please see https://blog.golang.org/gofmt 

If you really need to use different indentation style, that may be possible once https://github.com/golang/vscode-go/issues/1238 is fixed. However, I still strongly recommend following `gofmt` style for go files.
