### ISSUE TITLE
debug: debug test with 'ldflags' cannot work

### ISSUE THREAD

**Issue by huyinghuan** [golang/vscode-go#1261]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.6.6
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.53.2
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.22.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.

```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/huyinghuan/go-work
GOROOT: /usr/local/go
PATH: /Users/huyinghuan/go-work/bin:/Users/huyinghuan/Bin:/usr/local/bin:/usr/bin:/Users/huyinghuan/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/huyinghuan/Bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands

   gopkgs: /Users/huyinghuan/go-work/bin/gopkgs installed
   go-outline: /Users/huyinghuan/go-work/bin/go-outline installed
   gotests: /Users/huyinghuan/go-work/bin/gotests installed
   gomodifytags: /Users/huyinghuan/go-work/bin/gomodifytags installed
   impl: /Users/huyinghuan/go-work/bin/impl installed
   goplay: /Users/huyinghuan/go-work/bin/goplay installed
   dlv: /Users/huyinghuan/go-work/bin/dlv installed
   golint: /Users/huyinghuan/go-work/bin/golint installed
   gopls: /Users/huyinghuan/go-work/bin/gopls installed

go env
Workspace Folder (gotest): /Users/huyinghuan/workspace/gotest
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/huyinghuan/Library/Caches/go-build"
	GOENV="/Users/huyinghuan/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/huyinghuan/go-work/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/huyinghuan/go-work"
	GOPRIVATE=""
	GOPROXY="https://goproxy.io,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.16"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/huyinghuan/workspace/gotest/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vs/2f_9lj890953pkxvdbqwckgh0000gn/T/go-build547467795=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### Share the Go related settings you have added/edited

```
{
    "go.testFlags": [
        "-v",
        "-count=1",
        "-ldflags",
        "-X 'my.test/suit.S=B'"
    ]
}
```
### Describe the bug

`suit/mytestsuit.go`:

```
package suit

import "log"

var S = "A"

func Run() {
	log.Println(S)
}

```

`suit/mytestsuit_test.go`:

```
package suit

import "testing"

func TestRun(t *testing.T) {
	Run()
}
```

when run

```
/usr/local/go/bin/go test -timeout 30s -run ^TestRun$ my.test/suit -v -count=1 -ldflags -X 'my.test/suit.S=B'
```

test is ok

when run 'debug test' show:

```
malformed import path "my.test/suit.S=B": invalid char '='
exit status 1
Process exiting with code: 1
```
![image](https://user-images.githubusercontent.com/3005433/109479293-31511a00-7ab5-11eb-99f2-6a4dc1b11dbf.png)

### Screenshots or recordings

project file tree

![image](https://user-images.githubusercontent.com/3005433/109478488-46797900-7ab4-11eb-9fe9-e23865bf5525.png)

![image](https://user-images.githubusercontent.com/3005433/109479125-0bc41080-7ab5-11eb-9c21-b1b2d2df277b.png)

![image](https://user-images.githubusercontent.com/3005433/109479145-0f579780-7ab5-11eb-8559-add619ffe994.png)

**Comment by hyangah** [comment]
The error is coming from dlv - dlv's buildFlags parsing logic is slightly different from go commands. 
  @huyinghuan Can you try the following?
  
  ```  
    "go.testFlags": ["-v", "-count=1", "-ldflags", "-X='my.test/suit.S'"]
  ```
  
fyi. currently `"go.testFlags"` isn't plumbed to the debug configuration by default so F5 (Run Debug) wouldn't use it, so you will need a separate launch.json configuration if you want F5. (cc @suzmue )

**Comment by huyinghuan** [comment]
@haryps  `launch.json` no field `go.testFlags`, but i add `buildFlags`

here is  `.vscode/launch.json` :
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${file}",
            "buildFlags": "-ldflags='-X my.test/suit.S=C'",
        }
    ]
}
```

To distinguish between the profiles used, I used different values  'C' and 'B',

 the error is show `malformed import path "my.test/suit.S=B": invalid char '='` so debug use  `setttings.json` ?
`

`.vscode/settings.json`:

```
{
    "go.testFlags": [
        "-v",
        "-count=1",
        "-ldflags",
        "-X 'my.test/suit.S=B'"
    ]
}
```

**Comment by huyinghuan** [comment]
@hyangah  thanks !!!  ` "-X='my.test/suit.S'"` need '='
