### ISSUE TITLE
gopls: unable to expand struct if object is array of struct

### ISSUE THREAD

**Issue by seanturner026** [golang/vscode-go#1269]
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210222172741-77e031214674 h1:XzEjy9Ks1MwmcJOarbxTnL/AqHtzsRfRzAwfDhII2lE=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.22.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- GOBIN: /Users/sean/go/bin
toolsGopath: 
gopath: /Users/sean/go
GOROOT: /usr/local/go
PATH: /Users/sean/.rbenv/shims:/Users/sean/Downloads/google-cloud-sdk/bin:/Users/sean/.pyenv/shims:/Users/sean/.pyenv/bin:/Users/sean/go/bin:/usr/local/sbin:/Users/sean/.serverless/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Users/sean/.cargo/bin

   gopkgs: /Users/sean/go/bin/gopkgs installed
   go-outline: /Users/sean/go/bin/go-outline installed
   gotests: gotests not installed
   gomodifytags: gomodifytags not installed
   impl: impl not installed
   goplay: goplay not installed
   dlv: /Users/sean/go/bin/dlv installed
   golint: /Users/sean/go/bin/golint installed
   gopls: /Users/sean/go/bin/gopls installed

go env
Workspace Folder (go-temp): /Users/sean/code/go-temp
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN="/Users/sean/go/bin"
	GOCACHE="/Users/sean/Library/Caches/go-build"
	GOENV="/Users/sean/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/sean/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/sean/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.16"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/sean/code/go-temp/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/9m/8w9cdsl57l15w01fn272zl_c0000gn/T/go-build2153109825=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
  "go.formatTool": "goimports",
  "go.useLanguageServer": true,
  "[go]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    // Optional: Disable snippets, as they conflict with completion ranking.
    "editor.snippetSuggestions": "none"
  },
  "[go.mod]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },
  "gopls": {
    // Add parameter placeholders when completing a function.
    "usePlaceholders": true,
    // If true, enable additional analyses with staticcheck.
    // Warning: This will significantly increase memory usage.
    "staticcheck": true
  },
```

### Describe the bug

Thanks you for this extension, first of all.

Otherwise, I am unable to expand structs if the object is an array of struct (`[]struct{}`)

Consider the following program https://play.golang.org/p/sV8a4HLlL9o

Within VSCode, I can put the cursor inside `{}` on line 15, and either click the lightbulb or hit `cmd` + `.` to bring up a menu which expands the struct.

<img width="314" alt="Screen Shot 2021-03-04 at 19 21 58" src="https://user-images.githubusercontent.com/30396892/109920353-09fd8580-7d1f-11eb-9d1d-198f8152c7b5.png">

This produces this result:
<img width="300" alt="Screen Shot 2021-03-04 at 19 22 32" src="https://user-images.githubusercontent.com/30396892/109920430-27325400-7d1f-11eb-8bdf-20d24f45c9a6.png">

However, I am unable to expand the `hobby` struct unless I remove the `[]` in front of hobby.
<img width="449" alt="Screen Shot 2021-03-04 at 19 25 03" src="https://user-images.githubusercontent.com/30396892/109920565-5779f280-7d1f-11eb-9834-31eb1d809621.png">

With the `[]` removed, I can expand the struct.
<img width="362" alt="Screen Shot 2021-03-04 at 19 25 37" src="https://user-images.githubusercontent.com/30396892/109920616-6c568600-7d1f-11eb-8396-53b0d32605ed.png">

I find this struct expansion very very useful. Is there something that can be done here?

Thanks again!

**Comment by hyangah** [comment]
@seancaffery thanks for the report. Personally I think the autocompletion is more appropriate in this case but maybe @stamblerre has a different thought to optimize the workflow.

Related: @stamblerre  I noticed that the first autocompletion candidate in this case is `hobby{}`. If I select this, it will insert `hobby{}`, which will trigger an `simplifycompositelit` warning. I think, in this case, just `{}` should be preferred. 

![Screen Shot 2021-03-04 at 1 59 01 PM](https://user-images.githubusercontent.com/4999471/110015633-161f1e00-7cf2-11eb-80d5-4c71309279f3.png)

**Comment by stamblerre** [comment]
Closing since this can be addressed with completion.

**Comment by seanturner026** [comment]
Could you explain a little further please? How do I trigger the auto-completion?

Isn't this still a bug regardless of it this can be addressed with completion?

**Comment by stamblerre** [comment]
You can trigger completion manually by pressing Ctrl + Space.
I don't think this is a bug because the actions are a bit different here--in the case of a struct, you may want to fill its fields, but in the case of a slice, it's not entirely obvious what the result of "Fill" would be. A single empty `hobby{}` struct? Or one with pre-filled fields? I think that using the completion makes things a bit more flexible for the user.
