### ISSUE TITLE
debug: connecting to dlv-dap results in connection error

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#1270]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16 darwin/amd64
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.53.2
* Check your installed extensions to get the version of the VS Code Go extension
	- Go Nightly

### Describe the bug
```
{
            "name": "Launch Program",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceFolder}",
            "debugAdapter": "dlv-dap"
 }
```

### Steps to reproduce the behavior:
1. Reinstall dlv
2. Click on 'Launch Program'
3. See error
<img width="269" alt="Screen Shot 2021-03-04 at 11 02 25 AM" src="https://user-images.githubusercontent.com/6634754/109992855-ac931580-7cd9-11eb-9872-e43d7410a37f.png">

This appears to be a timing related issue, since it does not happen often. This needs a better error message and/or a second attempt to connect.

**Comment by polinasok** [comment]
This happens when the server is not up and ready to listen. Do we have a sufficient delay in the factory? I think there used to be a start-up delay in the old adapter as well.

**Comment by polinasok** [comment]
The error message is coming from the editor. I don't know how to control it.

**Comment by suzmue** [comment]
There was a delay but it was not sufficient. Once @hyangah's change for redirecting stdout and stderr from dlv dap is in, I have a change that will wait for the "DAP serving listening at" message before returning the server info to vscode.
