### ISSUE TITLE
Long wait while saving the go code?

### ISSUE THREAD

**Issue by smartaquarius10** [golang/vscode-go#1271]
Team,

The moment I make changes in the lines at the top like renaming or referencing new package i.e.
1. `package name`
2. `import`

It takes at least 4 mins to save a file. On the right side I see this popup:- 

**Saving getting code actions from go**

Only in these 2 section I'm getting logs:
- Log(Extension Host)

```
[2021-03-05 01:53:00.845] [exthost] [error] [golang.go] provider FAILED
[2021-03-05 01:53:00.845] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (c:\Users\myname\.vscode\extensions\golang.go-0.22.1\dist\goMain.js:13227:24)
	at LanguageClient.handleFailedRequest (c:\Users\myname\.vscode\extensions\golang.go-0.22.1\dist\goMain.js:13217:28)
	at c:\Users\myname\.vscode\extensions\golang.go-0.22.1\dist\goMain.js:11753:39
```

- gopls (server)
There is a huge list of logs hence written it [here](https://raw.githubusercontent.com/smartaquarius10/AnsiblePlaybooks/master/logs)

I would be grateful if someone can help here. Currently I have latest version of gopls and vscode-go.

Thank you

**Comment by stamblerre** [comment]
Can you please add `-rpc.trace` to the `go.languageServerFlags` setting? (As described [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)). I think we need logs with higher verbosity here.

**Comment by smartaquarius10** [comment]
@stamblerre , Hey rebecca thanks for helping. Checked-in the logs in different file. [Click here](https://raw.githubusercontent.com/smartaquarius10/AnsiblePlaybooks/master/logs-rpc)

**Comment by stamblerre** [comment]
It looks like the `C:\Users\myname\Documents\Visual Studio Code\Projects\Golang\src\myproject\database\DBContext.go` file is not being mapped to a package. Does it use build tags / what is the package name in that file?

What is the output of `go list -e -json -compiled ./...` when you are in the `C:\Users\myname\Documents\Visual Studio Code\Projects\Golang\src\myproject\` directory?

**Comment by smartaquarius10** [comment]
the folder name and the package name of the file is database
Here are the [logs](https://raw.githubusercontent.com/smartaquarius10/AnsiblePlaybooks/master/list-logs)

**Comment by stamblerre** [comment]
Thanks for sharing that. It does seem like `gopls` should be recognizing your packages, but for some reason, it is treating each file as "orphaned". One more thing to try might be adding the following setting and collecting `gopls` logs once again:

```json5
"gopls": {
	"verboseOutput": true,
}
```

Also, is this project private or can you share it with us? If you are able to point us to a GitHub repository or share a .zip of the project, that would be very helpful.

**Comment by smartaquarius10** [comment]
@stamblerre, this project is private to the organisation. I will create a new hello world project and share that because in every case I’m facing this challenge. 

I was on leave today. Will share the project in few hours. Thanks. Take care.

**Comment by smartaquarius10** [comment]
I have tried like this but nothing is coming in gopls. Are these settings correct? Are you referring to gopls(server) logs.
```
{
    "editor.accessibilitySupport": "off",
    "python.dataScience.sendSelectionToInteractiveWindow": true,
    "files.autoSaveDelay": 60000,
    "gopls": {
      "verboseOutput": true,
    },
    "go.languageServerFlags": [
        //"serve",
       //"-rpc.trace",
      //"--debug=localhost:6060"
      ],
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      },
      "workbench.colorTheme": "Visual Studio Dark",
      "workbench.iconTheme": "vscode-icons",
      "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
      "go.delveConfig": {
      "dlvLoadConfig": {
        "followPointers": true,
        "maxVariableRecurse": 1,
        "maxStringLen": 300,
        "maxArrayValues": 64,
        "maxStructFields": -1
      }
      },
      "git.ignoreWindowsGit27Warning": true,
      "go.useLanguageServer": true,
      "window.zoomLevel": 1
}
```

**Comment by stamblerre** [comment]
Yes, I am referring to the `gopls (server)` logs, and to get them to show up, you need to uncomment the `-rpc.trace` in `go.useLanguageServerFlags`.

**Comment by smartaquarius10** [comment]
@stamblerre , Hello Rebecca, sorry for the delay. I've created a random go file and the same issue is coming. Here are the [logs](https://raw.githubusercontent.com/smartaquarius10/AnsiblePlaybooks/master/newlogs)

```
package main
import (
     "fmt"
     "bufio"
    "strconv"
    "strings"
    "os"
)

func main() {
    scanner := bufio.NewScanner(os.Stdin)
    var x int
    for scanner.Scan() {
        if x==0{
            x,_= strconv.Atoi(scanner.Text())  
            if x<1 || x>100{
                return
            }   
            continue
        }
        for x>0{
            var i int
            var v int16
            var c int16
            text:=strings.Split(scanner.Text()," ") // split string and window size
            y,_ := strconv.Atoi(text[1]) //read window size           
            if len(text[0])<1 || len(text[0])>10000{
                return
            }
            condition:=len(text[0])-y+1
            for t:=0; t<condition;t++{
                for i < y {
                    switch string(text[0][i]) {
                        case "a", "e", "i", "o", "u", "A", "E", "I", "O", "U":                 
                           v++     
                        default:
                            c++
                    }                    
                    i++                
                }                
                v=0
                c=0
                i--   
                y=y+i             
            }
            fmt.Println("")
            x--
            
        }
    }    
}
```

Hope it helps. Thank you :)

**Comment by stamblerre** [comment]
If you don't mind, can you please share a log where you have a Go module in your project (a `go.mod` file at the root of your workspace)? There are other problems associated with working outside of GOPATH and outside of a module, so it's difficult to tell what might be going wrong.

**Comment by smartaquarius10** [comment]
@stamblerre, Hey rebecca.. I have created a fresh project. I have not created the go.mod file yet. Do you want me to create it and share the logs again. My Gopath is  c:\Users\myname\go

I have created a sample folder like this `c:\Users\myname\go\src\Sample\main.go` and then tried with the same file which I have shared above still it is taking time to save.

**Comment by stamblerre** [comment]
Since you were using modules in your other project, let's stick with modules in general. Can you please create a `go.mod` file in your sample project and share the logs?

**Comment by smartaquarius10** [comment]
@stamblerre , Hello.. Here are the logs
[gopls-server](https://raw.githubusercontent.com/smartaquarius10/AnsiblePlaybooks/master/logsdir/gopls-server)
[list-logs](https://raw.githubusercontent.com/smartaquarius10/AnsiblePlaybooks/master/logsdir/list-logs)

This is my go.mod file
```
module hackerrank

go 1.14

```

**Comment by smartaquarius10** [comment]
@stamblerre , Hey Rebecca, 
Trust you’re doing well. Once u get any update regarding this issue please let me know. 

Thank you. Happy weekend.

**Comment by smartaquarius10** [comment]
@stamblerre , Hey. no issue. :)
So the moment I open golang code in vscode these processes starts and remain open 

![image](https://user-images.githubusercontent.com/7824529/113205820-54c1dd00-928c-11eb-9826-0acc62320088.png)

Now, the moment I do some update in the name of any of the imported packages and hit save, the fluctuations starts occurring between these processes. Once the save is complete all of them closes:

![image](https://user-images.githubusercontent.com/7824529/113206111-ad917580-928c-11eb-9ff2-50bd8b392caa.png)   

--------------------------------------------------------------

![image](https://user-images.githubusercontent.com/7824529/113206157-beda8200-928c-11eb-8997-90ef63a273b1.png)

As shown, the fluctuation is majorly between 2 two new processes, i.e. compiler.exe and asm.exe. They both keeps on swapping each other and close in the end.

**Comment by stamblerre** [comment]
That description seems to confirm that executables are taking a long time to run on your machine. Have you been able to check if you have a virus scanner that is interfering? Does `go list` or `go build` take a long time to complete on your machine? If so, then that is the underlying issue, and unfortunately we probably can't give further guidance in how to troubleshoot your computer.

**Comment by hyangah** [comment]
Closing. @smartaquarius10 Please reopen this issue or open a new one if you believe `go list` or `go build` is performant but `gopls` isn't. Thanks!
