### ISSUE TITLE
goroot settings gets overridden by updateGoVarsFromConfig function

### ISSUE THREAD

**Issue by rezigned** [golang/vscode-go#1273]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.16 darwin/amd64`
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.54.1`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.22.1`

### Share the Go related settings you have added/edited

```js
{
    "go.goroot": "${workspaceFolder}/example/bin",
}
```

### Describe the bug

I've found that `go.goroot` value always gets overridden by `updateGoVarsFromConfig` function. Possibly due to these lines.

https://github.com/golang/vscode-go/blob/808b02f972f0dcf4298d5fd52a8448c95522cca8/src/goInstallTools.ts#L459-L461

### Steps to reproduce the behavior:
1. Add any path to `goroot` in settings file.
2. Run `Go: Install/Update tools` and install any tool (e.g. `gopls`)
3. The logs will show `GOROOT` from global `go env GOROOT ...` instead of the one from `goroot` settings.

```
Installing github.com/ramya-rao-a/go-outline FAILED
{
 "errno": "ENOENT",
 "code": "ENOENT",
 "syscall": "spawn /usr/local/go/bin/go",  
 "path": "/usr/local/go/bin/go"
 }
```
The `/usr/local/go/bin` is from global `go env GOROOT`. Not from `goroot` settings (i.e. `${workspace}/example/bin`)

**Comment by hyangah** [comment]
@rezigned Is your `"go.goroot"` setting in the workspace settings? If so, that's deliberate. You need to toggle the trust bit by using "Go: Toggle Workspace Trust Flag".  

And the the specified go.goroot should have an expected GOROOT structure, otherwise will be ignored.

Out of curiosity there any reason that you need to set `go.goroot`?

**Comment by rezigned** [comment]
@hyangah Thanks for the help 👍 

> Is your "go.goroot" setting in the workspace settings?
Yes, it's in workspace settings.

> You need to toggle the trust bit by using "Go: Toggle Workspace Trust Flag".
I have toggled this flag already. But it seems to have no effects for `goroot` settings. Due to `updateGoVarsFromConfig` doesn't account for `goroot` value.

> Out of curiosity there any reason that you need to set go.goroot?
I'm working on some version manager tools that can be used per project/dir.

**Comment by hyangah** [comment]
The extension looks for the `go` binary from `go.goroot`/bin directory. If it fails to find it, the extension will believe the info from go.goroot is bogus and ignores it. 

If it finds a valid `go` binary from the `go.goroot`/bin directory, the extension will use the `go` binary from the directory. If you need to go with a different GOROOT, use `go.toolsEnvVars` setting instead now.

In most cases except a couple of edge cases, you shouldn't set GOROOT env var at all but let the `go` choose the right value for you.

**Comment by rezigned** [comment]
Right, for my case. At first I didn't add any settings to workspace `settings.json` at all. VScode can infer `go` binary from `$PATH` variable just fine. (Just an example, it uses the same path that I specified in settings.`PATH=${workspaceDir}/example/bin:$PATH}`).

For example if I installed tools manually from VS Code terminal (e.g. `gopls`). Everything works fine. VS Code did a great job to find correct `go` binary from `$PATH`.

The only time when extension failed is when I use `Go: Install/Update tools` command. Which seems to infer `go` bin different from other command.

**Comment by hyangah** [comment]
Thanks for the information. `Go: Install/Update tools` uses the same `go` binary picked by `gopls` or other commands run by the extension, but `go.toolsEnvVars` is not applied. Can you share your final vscode setting and, if you are using a version manager, what is that and how it picks up the go binary?

**Comment by rezigned** [comment]
@hyangah Thank you. I was reading the code on vscode-go to get more understanding. I'm not sure if this might be related. Here's my example `$PATH`.

```sh
PATH=${workspaceDir}/bin:$PATH
```

Most of go tools use `getBinPath('go')` to get `go` binary and for my case it returns correct value from `$PATH` above (e.g. `${workspaceDir}/bin/go`)

But when using `Go: Install/Update tools`. The following code use `getCurrentGoRoot()` which basically returns `go env GOROOT` i.e. `/usr/local/go` + `/bin/go`. Instead of `getBinPath('go')`.

Everything else works fine for me so far. Except just `Go: Install/Update tools` command. 

https://github.com/golang/vscode-go/blob/7dd7f7a0e374b7c5c9074f5959af9f73ae300d34/src/goInstallTools.ts#L228-L234

**Comment by hyangah** [comment]
Thanks. `getBinPath('go')` internally prefers the go from `getCurrentGoRoot` 

https://github.com/golang/vscode-go/blob/808b02f972f0dcf4298d5fd52a8448c95522cca8/src/utils/pathUtils.ts#L92-L104

As the comment in the `goInstallTools.ts` stated, it passes GOROOT/bin/go because, some version managers (such as direnv or I think it was asdf and gvm) use a wrapper that switches `go` depending on the directory where the command is invoked, and for tool installations the extension runs the go command in a temporary directory, not in the workspace. 

It's possible that this assumption does not work in your environment. But I don't know why it's not desirable to use `go env GOROOT)`/bin/go.

**Comment by rezigned** [comment]
@hyangah from your code snippets. For me, `pathFromGoRoot` returns `undefined` and it uses value from `pathFromPath` instead. 

Digging through the code and found that, `getBinPathFromEnvVar` relies on `getCurrentGoRoot` (which contains `/usr/local/go`). Since I don't have `go` installed in the default location (It's installed in workspace dir).  So, `getBinPathFromEnvVar(binname, preferredGoroot || getCurrentGoRoot()` returns `undefined`.

```
# there's no /usr/local/go
- proj1/
    `- bin/go
```
https://github.com/golang/vscode-go/blob/808b02f972f0dcf4298d5fd52a8448c95522cca8/src/utils/pathUtils.ts#L29-L31

Thus, it always returns value from `$PATH` variable for me. Which is the correct behavior.

```js
// PATH=${proj1}/bin:$PATH

// Finally search PATH parts 
const pathFromPath = getBinPathFromEnvVar(binname, envPath, false); 

console.log(pathFromPath) // returns `proj1/bin/go` 
```

For my case, since I have the above information and I know that `Go install/update tools` always uses `getCurrentGoRoot` to infer `go` bin (although if it uses `getBinPath('go')` it will return correct value from `$PATH` for me). So, I tried to use workspace settings to set `goroot` instead to make it works. But it seems like `getCurrentGoRoot` doesn't use value from `goroot` settings. Thus I opened this issue.

If this behavior can't be changed. Do you have a suggestion on how could I make `getCurrentGoRoot` reads from `go.goroot` settings instead. Or other solution would be appreciated.

https://github.com/golang/vscode-go/blob/7dd7f7a0e374b7c5c9074f5959af9f73ae300d34/src/goInstallTools.ts#L228-L234

**Comment by hyangah** [comment]
Thanks for digging into the code. @rezigned 
It's strange that `getBinPathFromEnvVar` returns `undefined`. 
`go.goroot` is one of the very first config the extension reads and sets during activation.

https://github.com/golang/vscode-go/blob/80f450fdbcdf0314a45cbaf851d1311e9afe6af7/src/goMain.ts#L150-L154.

[`updateGoVarsFromConfig`](https://github.com/golang/vscode-go/blob/master/src/goMain.ts#L180) is called after setting the currentGoRoot. So, `getCurrentGoRoot` should return the value from `go.goroot`.
(moreover, it looks like `getBinPath('go')` reads `go.goroot` once more and pass as the `preferredGoroot` param [here]( https://github.com/golang/vscode-go/blob/80f450fdbcdf0314a45cbaf851d1311e9afe6af7/src/util.ts#L520))

If the code works as intended, when you set `go.goroot` and that's a valid GOROOT that contains a go binary under its bin directory, `getBinPath('go')` should pick `go` from the `go.goroot`, NOT from your `$PATH`. But your observation doesn't match this, I am afraid the logic around `getBinPath('go')` is broken. Can you turn on a verbose logging (	`"go.logging.level": "verbose" ` in settings.json) and see what's printed in the console of `Developers: Toggle Developer Tools`? You should see outputs like this 
![Screen Shot 2021-03-06 at 1 06 28 PM](https://user-images.githubusercontent.com/4999471/110216372-d9336280-7e7c-11eb-8ffb-9ddd08c0e674.png)

As I described above, the value for `getCurrentGoRoot` is initialized with `go.goroot` setting. 
If you want to specify the go binary path, you can try 
`"go.alternateTools: { "go": "<path_to_your_go_bin>" }`
but the specified go binary should return the right GOROOT when running `go env`.

**Comment by rezigned** [comment]
Interesting, I did a clean install for go extension and with the following workspace settings.

```js
{
    "go.goroot": "${workspaceFolder}/exts", // `exts` contains `bin/go` i.e. exts/bin/go
    "go.logging.level": "verbose"
}
```
I got the following logs (replaced abs path with `${workspaceFolder}`).

```
[Extension Host] Go[V]: go.goroot = '${workspaceFolder}/exts'
[Extension Host] Go[V]: setCurrentGoRoot(${workspaceFolder}/exts) <-- 1.
[Extension Host] Go[V]: updateGoVarsFromConfig: found 'go' in ${workspaceFolder}/exts/bin/go 
[Extension Host] Go[V]: ${workspaceFolder}/exts/bin/go env ...:
/go
/usr/local/go  <-- GOROOT
https://proxy.golang.org,direct

[Extension Host] Go[V]: setCurrentGoRoot(/usr/local/go) <-- 2.
[Extension Host] Go[V]: addGoRuntimeBase(/usr/local/go/bin) when PATH=${workspaceFolder}/exts/bin:/usr/local/bin:/usr/bin:/bin
```

As you can see. `go.goroot` got overridden in step 2 from this

https://github.com/golang/vscode-go/blob/808b02f972f0dcf4298d5fd52a8448c95522cca8/src/goInstallTools.ts#L459-L461

If I change the above line to this. `Go install/update tools` works perfectly for me.

```
// check if there's no `go.goroot` settings.
 if (!getCurrentGoRoot() && envOutput[1] && envOutput[1].trim()) { 
 	setCurrentGoRoot(envOutput[1].trim()); 
 } 
```

**Comment by hyangah** [comment]
I see - so, the culprit is `${workspaceFolder}/exts/bin/go env ...` doesn't give the expected result - makes sense because it is not installed in the usual way so the `go` doesn't have the right GOROOT information embedded. In this case, the current workaround is to supply the GOROOT using `go.toolsEnvVars` as mentioned in https://github.com/golang/vscode-go/issues/1273#issuecomment-791491248. 
```
  "go.toolsEnvVars": { "GOROOT": "${workspaceFolder}/exts" }
```
`updateGoVarsFromConfig` runs the `go env` command with the `go.toolsEnvVars`, so `GOROOT=${workspaceFolder}/exts go env GOROOT` will return ${workspaceFolder}/exts. 

Setting GOROOT isn't recommended with the modern Go, but in your case, probably necessary. We will think about how to help this rare use case.

**Comment by rezigned** [comment]
Thanks a lot for your help and guidance @hyangah. Adding `go.toolsEnvVars` solved `GOROOT` problem for my case 🎉 .
