### ISSUE TITLE
"Running the contributed command: 'go.test.cursor' failed."

### ISSUE THREAD

**Issue by ThomasBurgess2000** [golang/vscode-go#1274]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210222172741-77e031214674 h1:XzEjy9Ks1MwmcJOarbxTnL/AqHtzsRfRzAwfDhII2lE=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.54.1
f30a9b73e8ffc278e71575118b6bf568f04587c8
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.23.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Command 'Go: Locate Configured Go Tools' resulted in an error (command 'go.locate.tools' not found)

### Share the Go related settings you have added/edited

None

### Describe the bug
Clicking "run test" in any of my test files results in "Running the contributed command: 'go.test.cursor' failed." However, running "go test" works.

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/14812407/110163938-4def9980-7db6-11eb-84ea-893c2bec282c.png)

**Comment by hyangah** [comment]
@ThomasBurgess2000 Have you tried to reload the window? (Developer: Reload Window) 
Looks like the extension wasn't activated (on the other hand, it's strange that you have 'run test' code lenses there. )

**Comment by ThomasBurgess2000** [comment]
> 
> 
> @ThomasBurgess2000 Have you tried to reload the window? (Developer: Reload Window)
> Looks like the extension wasn't activated (on the other hand, it's strange that you have 'run test' code lenses there. )

Yes, I tried that.

**Comment by hyangah** [comment]
@ThomasBurgess2000 I don't know what's going on - maybe the extension is corrupted? Try to reinstall the extension (you may need to delete the directory under $HOME/.vscode/extensions/golang.go-0.23.0 directory. 

Also check if there is any crash or error message in the log output channels https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-extension-logs and the developer console. (Command Palette -> Developers: Toggle Developer Tools).

**Comment by ThomasBurgess2000** [comment]
> 
> 
> @ThomasBurgess2000 I don't know what's going on - maybe the extension is corrupted? Try to reinstall the extension (you may need to delete the directory under $HOME/.vscode/extensions/golang.go-0.23.0 directory.
> 
> Also check if there is any crash or error message in the log output channels https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-extension-logs and the developer console. (Command Palette -> Developers: Toggle Developer Tools).

Tried reinstalling and it didn't work, but here's the log from "Log (Extension Host)". 

```
[2021-03-06 13:56:51.640] [exthost] [error] Error: command 'go.test.cursor' not found
    at C._tryExecuteCommand (file:///C:/Users/thoma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1654:3360)
    at file:///C:/Users/thoma/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1654:3241 go.test.cursor
```

**Comment by hyangah** [comment]
Thanks. 

Let me check if I understood correctly:  

- you saw log messages indicating `golang.go` extension was activated from the "Log (Extension Host)", e.g.
```
[2021-03-06 16:10:40.498] [exthost] [info] ExtensionService#_doActivateExtension golang.go {"startup":false,"extensionId":{"value":"golang.go","_lower":"golang.go"},"activationEvent":"onLanguage:go"}
[2021-03-06 16:10:40.498] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/hakim/.vscode/extensions/golang.go-0.23.0/dist/goMain.js
```

 - you saw the Go version status bar item appearing normal (see [pic](https://github.com/golang/vscode-go/blob/master/docs/ui.md#using-the-go-status-bar)), but 

- you didn't see any other error or crash log before the `Error: command 'go.test.cursor' not found` error log.

You can double check if the command is registered by increasing the log level.

- Run "Developer: Set Log Level" -> choose "Trace"
- Run "Developer: Reload Window" 
- Check the "Log (Extension Host)" again. 

If the commands are successfully registered, you should be able to see logs like this:

```
[2021-03-06 16:13:22.040] [exthost] [trace] ExtHostCommands#registerCommand go.test.cursor
```

If you saw the above message but no other error messages, I think we need to file an issue to vscode for help.

**Comment by stamblerre** [comment]
Closing, as this issue has been in a WaitingForInfo state for a while.
