### ISSUE TITLE
gopls: packages.Load error

### ISSUE THREAD

**Issue by vacheli** [golang/vscode-go#1283]
Error loading workspace: err: exit status 1: stderr: go: updates to go.sum needed, disabled by -mod=readonly : packages.Load error

Vscode-go is becoming more and more difficult to use.

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by stamblerre** [comment]
Closing, as this issue has been in a WaitingForInfo state for a month.

**Comment by Martin91** [comment]
> @vacheli What is the version of `gopls`? (`gopls -v version` output)
> 
> Were there any diagnostic messages in the `go.mod` file or code lens that suggests `go mod tidy` like the following?
> 
> ![Screen Shot 2021-03-09 at 9 57 49 AM](https://user-images.githubusercontent.com/4999471/110490101-fc008980-80bd-11eb-9b7d-f07e35d46f1a.png)
> 
> If not, do you mind sharing the gopls trace following [this instruction](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)?

This fixes my problem.
There was a message said that my go.sum is out of sync and mentioned that I could fix it by quick fix. The problem gone away after I clicked the "quick fix" action in the editor.

Thanks a lot!
