### ISSUE TITLE
go build tags in launch.json is invalid

### ISSUE THREAD

**Issue by zhb127** [golang/vscode-go#1286]
### Screenshots or recordings

![image](https://user-images.githubusercontent.com/5210208/110573152-b7482180-8195-11eb-89d4-235c8b7a74e1.png)

![image](https://user-images.githubusercontent.com/5210208/110573278-f24a5500-8195-11eb-8aa0-167140950d0a.png)

![image](https://user-images.githubusercontent.com/5210208/110573355-160d9b00-8196-11eb-9514-424f2e8e82f0.png)

![image](https://user-images.githubusercontent.com/5210208/110573406-2c1b5b80-8196-11eb-9617-827b7f01441b.png)

```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by hyangah** [comment]
@zhb127 Can you please turn on the verbose logging and see what command is used to invoke `dlv`?

launch.json
```
  ...
   {
      "name": "apiserver", 
        ...
      "trace": "verbose"
   }
```

Then, try to run the dlv command from the terminal to check if that works?

**Comment by zhb127** [comment]
> @zhb127 Can you please turn on the verbose logging and see what command is used to invoke `dlv`?
> 
> launch.json
> 
> ```
>   ...
>    {
>       "name": "apiserver", 
>         ...
>       "trace": "verbose"
>    }
> ```
> 
> Then, try to run the dlv command from the terminal to check if that works?

Thanks for the reply, this is my environment.

![image](https://user-images.githubusercontent.com/5210208/110583521-c4bad700-81a8-11eb-97cd-c726e59dd9d0.png)

![image](https://user-images.githubusercontent.com/5210208/110583975-7823cb80-81a9-11eb-9273-592bb5d726b5.png)

![image](https://user-images.githubusercontent.com/5210208/110584120-b0c3a500-81a9-11eb-913f-b501f3a07a0e.png)

![image](https://user-images.githubusercontent.com/5210208/110584168-c042ee00-81a9-11eb-8a34-a4b8d4cc88fe.png)

![image](https://user-images.githubusercontent.com/5210208/110584190-ca64ec80-81a9-11eb-99a4-9f6bb53d90c3.png)

![image](https://user-images.githubusercontent.com/5210208/110584221-d355be00-81a9-11eb-8d23-26c123fd07a8.png)

**Comment by hyangah** [comment]
For the `program` arg, can you try specify the directory since you need files other than main.go?

```
   "program": "${workspaceRoot}/cmd/apiserver"
```

**Comment by zhb127** [comment]
> For the `program` arg, can you try specify the directory since you need files other than main.go?
> 
> ```
>    "program": "${workspaceRoot}/cmd/apiserver"
> ```

Thank you so much,  that's the problem!

![image](https://user-images.githubusercontent.com/5210208/110646932-5e5aa680-81f2-11eb-88bc-f06ea050864f.png)
