### ISSUE TITLE
Remote SSH session does not detect the environment properly

### ISSUE THREAD

**Issue by maciejmatczak** [golang/vscode-go#1288]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.16 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210222172741-77e031214674 h1:XzEjy9Ks1MwmcJOarbxTnL/AqHtzsRfRzAwfDhII2lE=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.54.1
f30a9b73e8ffc278e71575118b6bf568f04587c8
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.23.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/u/maciejmatczak/.cache/go-build"
GOENV="/u/maciejmatczak/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/u/maciejmatczak/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/u/maciejmatczak/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/someDir/users/maciejmatczak/programs/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/someDir/users/maciejmatczak/programs/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="users/maciejmatczak/work/go_hello_world/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3429054638=/tmp/go-build"

### Describe the bug
I am using a SSH remote in VS Code. Dev machine Windows, target linux. As I have a quota limits in my home dir on a target, I used GOPATH to redirect all (or most) go related files. I set it with use of `.bashrc`.
- everything works as intended in my terminal on the host
- everything works as intended in VS Code's integrated terminal
- extension does not detect this settings at all, does not detect the gopls and when prompts to install, if agreed, it installs it in home dir

Thanks to a dumped  `Go: Locate Configured Go Tools` , I diffed it with what I get when I invoke the `go env` (removed `GOGCCFLAGS` with /tmp, etc):

```text
4c4
< GOCACHE="/u/maciejmatczak/.cache/go-build"
---
> GOCACHE="/someDir/users/maciejmatczak/cache/go-bin"
11c11
< GOMODCACHE="/u/maciejmatczak/go/pkg/mod"
---
> GOMODCACHE="/someDir/users/maciejmatczak/go/pkg/mod"
15c15
< GOPATH="/u/maciejmatczak/go"
---
> GOPATH="/someDir/users/maciejmatczak/go"
29c29
< GOMOD="users/maciejmatczak/work/go_hello_world/go.mod"
---
> GOMOD="/someDir/users/maciejmatczak/work/go_hello_world/go.mod"
36c36
```

From my understanding this part from readme is crucial:

> PATH environment variable (or Path on Windows) with which the VS Code process has started

I am guessing, that VS Code might be starting server in non-interactive session, hence by `.bashrc` setup is ignored, not sourced. Shouldn't be a call to `go env` used for making a setup?

On second thought, I viewed a `process.env` in Developer tools, console in VS Code. It's the same used by this extension, right?

It's populated with the client environment variables (Windows) even though I am connected to my remote (Linux). That initially sounds even worse...

Does this extension support the `Visual Studio Code Remote - SSH`?

Thanks!

**Comment by maciejmatczak** [comment]
Checking `process.env` on client shown client's `env`, that might have been bad idea. I am not sure how to show `process.env` on ssh target.

**Comment by maciejmatczak** [comment]
My apologies, it might have been a sticky behavior mentioned here: https://github.com/golang/vscode-go/issues/237#issuecomment-646067281

Reloading of VS Code is not enough to reevaluate the environment, so a explicit `Remote-SSH: Kill VS Code Server on Host` might be needed.

I am currently getting proper environment.

**Comment by hyangah** [comment]
@maciejmatczak thanks for digging into the history. I will create a section in the troubleshooting doc based on it.
(For the last few months, VSCode has been changing how they populate the environment variables for extension hosts and itself. It's good to know that some part is still true)
