### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ofili** [golang/vscode-go#13]
- Issue Type: `Performance`
- Extension Name: `go-nightly`
- Extension Version: `2020.3.144`
- OS Version: `Windows_NT x64 10.0.19582`
- VSCode version: `1.44.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ofili_lewis\golang.go-nightly-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by hyangah** [comment]
@ofili thanks for the report. Unfortunately I don't see cpu profile attachment.
