### ISSUE TITLE
📌  v0.23.1 requires gopls 0.6.6 or newer

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1300]
Please update `gopls` if you see errors like the following

<pre>
Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
 </pre>
 
 or 
 
 
![Screen Shot 2021-03-11 at 8 28 59 PM](https://user-images.githubusercontent.com/4999471/110878034-7a208400-82a8-11eb-9989-24cb56a6cdc1.png)

Choose to update it. 

If the above popup didn't appear (maybe because GOPROXY isn't reachable)
Run Ctrl+Shift+P -> "Go: Install/Update Tools" -> Select `gopls` -> OK

![Screen Shot 2021-03-11 at 8 30 18 PM](https://user-images.githubusercontent.com/4999471/110878190-b94ed500-82a8-11eb-9fd8-dcdba257014b.png)

Or, if you want to install it manually,

Go 1.16
```
  go install golang.org/x/tools/gopls@latest
```  
Go 1.15 or older
```
  GO111MODULE=on go get golang.org/x/tools/gopls@latest
```

**Comment by hyangah** [comment]
v0.23.2 that explicitly states the hard-coded minimum required gopls version (v0.6.6) is released.
Users with old gopls will be notified to update it.

Thank you for your patience.

**Comment by freezlite** [comment]
I am wondering how to deal with back compability which should be garanted in non major version changes. Go pls 0.6 is not working with go 1.13 and now go plugin not working with gopls 0.5.

**Comment by nitronick600** [comment]
Upgrading gopls itself didn't work for me with go version v1.15.  I needed to upgrade to go v1.16.2

1 - upgrade go v1.15 to v1.16.2
2 - `go install golang.org/x/tools/gopls@latest`
3 - restart the gopls server

**Comment by hyangah** [comment]
@nitronick600 if you want to install manually with go1.15 or older, you need to run `go get` command as described in the first comment.

`GO111MODULE=on go get golang.org/x/tools/gopls@latest`

Or do you see any other error?
The extension's `Go: Install/Update Tools` command chooses the right command (that works for go 1.12+) and restarts the gopls server behind the scene.

**Comment by piyushsingariya** [comment]
This is still happening to vscode. Can somebody guide I updated gopls still vscode-go says to update, I restarted the gopls server still not getting started.

**Comment by stamblerre** [comment]
@piyushsingariya: Please take a look at the [troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md) and open a new issue so we can help you investigate.
