### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by james-zhang-bing** [golang/vscode-go#1302]
gopls version: v0.6.4
gopls flags: 
extension version: 0.23.1
environment: Visual Studio Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

The language server is not able to serve any features. Initialization failed: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error. 

Failed to auto-collect gopls trace: no gopls log.

**Comment by hyangah** [comment]
Thanks for the report @james-zhang-bing Please update gopls to v0.6.6. See #1300 for the detailed instruction.

**Comment by james-zhang-bing** [comment]
> Thanks for the report @james-zhang-bing Please update gopls to v0.6.6. See #1300 for the detailed instruction.
Thank you! It's working
