### ISSUE TITLE
debug: simplify generated launch.json

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#131]
_From https://github.com/microsoft/vscode-go/issues/2120 by @isidorn_:

The `launch.json` that GO generates is attached at the end. This is cool and simple. However we can still do the following

- [x] Go needs to activate on `onDebugInitialConfigurations`
- [x] Consider to use `quickPick` in `DebugConfigurationProvider` to ask the user if he would like to launch file, launch package, connect to server, launch test package, launch test function and based on that create a launch configuration. 
-  [x] Remove default fields which are not necessery like `env`, `args`. Both from the configurationSnippets and from the intial configurations
- [x] What is the biggest pain point for go debugging setup, could we somehow help there with dynamicly providing debug configuratons or resolving them

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}
```

Related upstream issue in VS Code: Microsoft/vscode#62851

For prior discussion on this issue, please see https://github.com/microsoft/vscode-go/issues/2120

**Comment by suzmue** [comment]
>  Go needs to activate on onDebugInitialConfigurations

I have sent a change to activate the extension onDebugInitialConfigurations.

> Consider to use quickPick in DebugConfigurationProvider to ask the user if he would like to launch file, launch package, connect to server, launch test package, launch test function and based on that create a launch configuration

This seems like a good idea! Will leave this issue open to track this.

> Remove default fields which are not necessary like env, args. Both from the configurationSnippets and from the intial configurations

Ramya addressed this in the linked issue. These are there for discoverability purposes and we plan to keep them there at this time.

> What is the biggest pain point for go debugging setup, could we somehow help there with dynamically providing debug configurations or resolving them

@lggomez  mentioned in the linked issue that the "inconsistency between the debug test codelens and the debug viewlet launcher" was one of the main pain points. This issue is now covered by (golang/vscode-go#855)[https://github.com/golang/vscode-go/issues/855]

**Comment by hyangah** [comment]
@suzmue It looks like cl/271237 completes all the remaining tasks. Is it ok to close this?
