### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by darrensapalo** [golang/vscode-go#1316]
## Environment

gopls version: v0.6.4
gopls flags: 
extension version: 0.23.1
environment: Visual Studio Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 1
total start count: 2

## Describe what you observed

I opened my Visual Studio IDE on an existing golang project that I had (which previously had no problems), and then an error showed that the gopls language server did not start properly. 

There were no other actions that I did- I don't know if this error was caused by a silent update on the golang server.

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

## More information

```
[Error - 12:48:53 pm] Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
[Info  - 12:48:53 pm] 2021/03/12 12:48:53 server shutdown without initialization

[Error - 12:49:28 pm] Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
```

**Comment by hyangah** [comment]
Thanks for the report @darrensapalo
This is a duplicate of #1300 . Can you please update `gopls` following the instruction in the issue?
Sorry for the trouble.

**Comment by darrensapalo** [comment]
Fixed by followinghttps://github.com/golang/vscode-go/issues/1300

**Comment by darrensapalo** [comment]
Hey man, thanks :) I looked through the documentation and found it. Big help!
