### ISSUE TITLE
debug: Long strings in debugger get truncated

### ISSUE THREAD

**Issue by mattwelke** [golang/vscode-go#1318]
Duplicate issues: #645, #1451

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.16 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- `golang.org/x/tools/gopls v0.6.6`
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.54.1`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.23.2`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/matt/go
GOROOT: /usr/local/go
PATH: /home/matt/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/bin:/home/matt/.poetry/bin:/home/matt/google-cloud-sdk/bin:/home/matt/.poetry/bin:/home/matt/.pyenv/plugins/pyenv-virtualenv/shims:/home/matt/.pyenv/shims:/home/matt/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/AdoptOpenJDK/jdk-11.0.10.9-hotspot/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/mattw/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/mattw/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/AdoptOpenJDK/jdk-11.0.10.9-hotspot/bin:/mnt/c/Users/mattw/.dotnet/tools:/snap/bin:/usr/local/go/bin:/home/matt/go/bin:/home/matt/n/bin:/opt/protoc/bin

   gopkgs: /home/matt/go/bin/gopkgs installed
   go-outline: /home/matt/go/bin/go-outline installed
   gotests: /home/matt/go/bin/gotests installed
   gomodifytags: /home/matt/go/bin/gomodifytags installed
   impl: /home/matt/go/bin/impl installed
   goplay: /home/matt/go/bin/goplay installed
   dlv: /home/matt/go/bin/dlv installed
   staticcheck: staticcheck not installed
   gopls: /home/matt/go/bin/gopls installed

go env
Workspace Folder (beacons-router): /home/matt/code/github.com/groupby/beacons-router
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/matt/.cache/go-build"
	GOENV="/home/matt/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/matt/go/pkg/mod"
	GONOPROXY="github.com/groupby"
	GONOSUMDB="github.com/groupby"
	GOOS="linux"
	GOPATH="/home/matt/go"
	GOPRIVATE="github.com/groupby"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.16"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/matt/code/github.com/groupby/beacons-router/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1773576749=/tmp/go-build -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

(none)

### Describe the bug

This issue seems to have resurfaced. It was filed as an issue in the old repo managed by Microsoft and then closed as fixed: https://github.com/microsoft/vscode-go/issues/868

I'm experiencing truncated strings while debugging.

Here it happens when I move my mouse over an error. I'd like to read the entire error (error messages in Go can get quite deep when they're returned from a deep layer of code) but I can't see the root error:

![go_vscode_strings_in_debugger_too_short](https://user-images.githubusercontent.com/7719209/110898255-e57c4d00-82cc-11eb-98e1-ad81c1848aaa.png)

### Steps to reproduce the behavior:
1. Create a string variable and give it a value that is very long (not sure how long to be honest).
2. Run debugger.
3. Try to inspect value. Observe that you can't see all of it.

**Comment by hyangah** [comment]
Even though not very ideal, how about `maxStringLen` configuration?  That was added as the fix for https://github.com/microsoft/vscode-go/issues/868.

https://github.com/golang/vscode-go/blob/master/docs/debugging.md#configuration 

cc @suzmue @polinasok

**Comment by mattwelke** [comment]
@hyangah Oh I see. I have to admit I skimmed that issue and just noticed at the bottom that it was closed as fixed. I didn't realize that's how they fixed it. I tried setting it to 10000 characters, which should suit my needs, and it worked well. It still doesn't display the full string in the debugging part of the UI (it has `...` now instead of `+<num> more`) but now when I right click the variable in the debugging part of the UI and click `Copy Value`, I can paste the full value into a text editor etc instead of only being able to paste the truncated value before. This works well for my workflow. It's rare I need this, it's just that when I do, I need it a lot. xD

Speaking of skimming, I think the fact that I tend to skim through documentation these days is why I missed that instruction in the debugging section of the Go extension documentation. I have experience with multiple programming languages for a few years now, so I tend to assume certain things work the same way, like "this is how one declares a variable", "this is how one starts a debugging session", "this is how one observes the value of the variable while debugging", and with the Go extension, it seems that 3rd example is done differently compared to other languages I've used with VS Code. For example, with JavaScript debugging in VS Code, I don't recall ever encountering this problem.

I'm thinking that a better default setting would be to display a much longer version of the string. I understand that it may not be good for performance to display the *entire* string every time. But I feel like the current low limit is too low. If performance is a concern, we probably only need to protect the UI's performance from exceptionally long strings, like when someone has a loop and appends to a string making it very long.

If it isn't possible to change the default to be longer, I think something more discoverable would be nice. Maybe something in the UI people can click on to see the full string while they're debugging. I think JetBrains IDEs do it this way. I recall using GoLand and being able to see the full value of my big JSON strings representing data flowing through the program (usually up 10000 characters). I don't recall if they displayed that many characters automatically or if I had to click some sort of "see more".

**Comment by hyangah** [comment]
@mattwelke thanks for sharing the ideas.

I agree that the current state is not ideal.
It is possible that the new debug adapter (`dlv dap`) may take a completely different approach (either by implementing autoloading or by supporting a custom command to configure the max length dynamically, see https://github.com/go-delve/delve/pull/2144 for the discussion). Note however, UX/UI is mostly controlled by DAP & VS Code (debug adapter protocol) so there will be still limitations.

(Maybe at least we can apply longer limit for the Evaluate Request coming from Debug Console)

I don't know how the current default value was chosen though - some users found large limits affect the performance too much 
https://github.com/microsoft/vscode-go/issues/1555#issuecomment-399728409  I hope we can document better so it's more easily discoverable.

**Comment by mattwelke** [comment]
@hyangah I like the idea of the longer default limit for evaluate requests coming from the debug console. It's an explicit action from the user, so it's less likely to get in the way and cause performance problems.

There's another ticket we're communicating on related to Go debugging. It's clear to me now that if I want to get deeper into helping with Go debugging, I need to get more familiar with tools like Delve and DAP. I'll revisit this once I've had a chance to do so. :) ty

**Comment by polinasok** [comment]
The current default is the default in the dlv backend. You can change the limit, but you can't tell delve to load an entire string of arbitrary length at once.
```
$ dlv debug foo.go 
Type 'help' for list of commands.
(dlv) c
> main.main() ./foo.go:19 (PC: 0x10ce21f)
    14:                 for i := 0; i < 1000; i++ {
    15:                         longstr += "1"
    16:                 }
    17:
    18:                 runtime.Breakpoint()
=>  19:                 fmt.Println(longstr)
    20:         }
    21: }
    22:
    23: func foo() {
    24:         s := `\n123\n`
(dlv) p longstr
"1111111111111111111111111111111111111111111111111111111111111111...+936 more"
(dlv) p longstr[90:]
"1111111111111111111111111111111111111111111111111111111111111111...+846 more"
(dlv) config max-string-len 1000
(dlv) p longstr
"1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
```
Dlv has built-in loading limits for other types as well.

Dlv-dap can auto-load interfaces, but not other types yet. For strings, we could display the truncated string value by default, but offer an option to expand like we do with compound vars. The expansion would trigger another variables request, which will tell the adapter to load more of the string. At that point, we can either load the entire string chunk by chunk in a loop or change the str limit in dlv, load the whole string, then change the str limit back to the default value. That whole large string would need to be written into a single variables response. Maybe there can be an intermediate partial expansion for really really large values.

We can easily use different default limits for values plugged into the Debug Console. They will also affect WATCH and Copy Value options as those also map to EvaluateRequest.

Debug Adapter Protocol has some fields for "paging of variables", but I don't know if vscode editor actually supports that. But even so, it doesn't sound like this is what is desired here. Having to load thousands of characters in small chunks can get rather annoying.

**Comment by polinasok** [comment]
> We can easily use different default limits for values plugged into the Debug Console. They will also affect WATCH and Copy Value options as those also map to EvaluateRequest.

We get `evaluate` expressions in the following cases:
1. entered by user in Debug Console -- `"context":"repl"`
2. triggered when the user uses "Copy Value" -- `"context":"variables"`
3. automatically generated for expressions under WATCH at each stop -- `"context":"watch"`

It would make a lot of sense to use a larger string limit when doing (1) and (2), but not (3).

**Comment by JustinGrote** [comment]
This doesn't work for me with dlv-dap
```json
    "go.delveConfig": {
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 300,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": false,
        "debugAdapter": "dlv-dap"
    }
```
![image](https://user-images.githubusercontent.com/15258962/116160222-7bfea500-a6a6-11eb-903a-dd7245f1b7b0.png)

**Comment by polinasok** [comment]
Yes, These setting are not available in [dlv-dap](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md). Please see the discussion at go-delve/delve#2144. We will be looking into ways to load these on demand in dlv-dap.

**Comment by alambertt** [comment]
Go to this settings on VSCode `go.delveConfig` an set this parameters
![image](https://user-images.githubusercontent.com/6148597/129458149-71da3b7f-a094-4aeb-ac97-cc55ac0b0c1c.png)

**Comment by mattwelke** [comment]
I added those settings to my VS Code config and ran the debugger again, but it had no effect. However, I do see a popup in the bottom right warning me that it won't have an effect.

Before:

![image](https://user-images.githubusercontent.com/7719209/129460694-05620570-e5a4-4ab9-9068-09c3fd27106f.png)

After:

![image](https://user-images.githubusercontent.com/7719209/129460739-d5d42e9d-10a6-43b0-b716-d07afecccff0.png)

**Comment by mattwelke** [comment]
I was able to solve the popup in the bottom right using the instructions in the accepted answer at https://stackoverflow.com/questions/68732514/user-specified-dlvloadconfig-setting-will-be-ignored-by-debug-adapter-dlv-dap.

But then the string doesn't appear correctly under VARIABLES while debugging:

![image](https://user-images.githubusercontent.com/7719209/129460809-f3181fd8-987c-4c89-aa06-c58624bb8ae9.png)

The only whitespace is a new line before the characters:

![image](https://user-images.githubusercontent.com/7719209/129460821-c5f22119-32bb-4116-b359-0dadaa1cebfd.png)

I'm able to see the string contents if I make sure there's no white space before the non-whitespace characters of my string, but it does still get truncated in the hover preview:

![image](https://user-images.githubusercontent.com/7719209/129460849-3edd8421-636a-457a-b116-80449a08ce07.png)

**Comment by polinasok** [comment]
@mattwelke, please instead see the [stackoverflow answer](https://stackoverflow.com/questions/68732514/user-specified-dlvloadconfig-setting-will-be-ignored-by-debug-adapter-dlv-dap) on the bottom from Hana, who is one of the maintainers of vscode-go.

We are currently transitioning from the legacy adapter (`"debugAdapter": "legacy"`) to the new dlv-dap adapter (`"debugAdapter": "dlv-dap"`), which was recently enabled by default for local debugging. You do still have the option to switch back to the original debug adapter as the stackoverflow suggested, but we urge you to give the new adapter a full try and let us know of ways we can improve it instead of falling back to the legacy option that we hope to deprecate in a foreseeable future.

The dlv-dap adapter ignores `dlvLoadConfig` because we are investing in more dynamic and context-based ways of loading data than a single setting that is used for everything in the debug session. Our goal is to create a UI where the user will not miss this setting. Your options for viewing the string currently include:
* Variables pane value via hover - limit is 512 (we are also considering 1024, which is the editor's hover limit)
(Note: this limit is the most conservative one because it applies to all strings and can impact the tools' performance)
* Entering variable's fully qualified name (`Copy as Expression`) into Debug Console - limit is 4096
* `Copy Value` - load limit is 4096
* Hover over the variable in the source file - limit is 4096

If these automated limits are not sufficient for your case, please let us know.

As for the rendering of the newline, you have come across the difference in how this is handled in the legacy adapter vs the new dlv-dap adapter. This difference is not related to `dlvLoadConfig`. Please also see #1321.

**Comment by hyangah** [comment]
dlv-dap has been the default debug adapter for a while. @polinasok summarized the current status and limit in https://github.com/golang/vscode-go/issues/1318#issuecomment-904366663. (thanks!) 

If those limits are not sufficient, please open a new issue and what context you want to inspect long strings. 

Note though, as @polinasok explained, variables pane value via hover cannot display more than 1024 due to editor's limit even we increase the default or allow users to configure the limit. 

Closing.
