### ISSUE TITLE
gopls cannot initialized due to JSON RPC error

### ISSUE THREAD

**Issue by cdivita** [golang/vscode-go#1327]
gopls version: v0.6.5
gopls flags: 
extension version: 0.23.2
environment: Visual Studio Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 2
total start count: 3

The Go Language Server does not start. I'm using a remote container for Go development

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

**Comment by hyangah** [comment]
Thanks for the report. @cdivita This is a duplicate of #1300.
Wasn't there a popup to prompt users to update gopls to a compatible version (v0.6.6+)?
The extension 0.23.2 should show the notification, and I wonder why it's not working as expected for some users.

**Comment by cdivita** [comment]
The popup was not there, however upgrading to v0.6.6 solved my issue
