### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by abvaidya** [golang/vscode-go#1329]
gopls version: v0.6.4
gopls flags: 
extension version: 0.23.2
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Getting following error on vs code start up ( after latest vscode version upgrade )
The language server is not able to serve any features. Initialization failed: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error.

vscode Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:09.783Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report @abvaidya 
This is a duplicate of #1300
I expected the extension to show a message like this. Did you see this message?
I suspect the notification was hidden due to other sever error popups.

![Screen Shot 2021-03-12 at 2 01 23 PM](https://user-images.githubusercontent.com/4999471/110986332-886bb000-833b-11eb-9fc8-a22a5a6324b3.png)

**Comment by abvaidya** [comment]
I didnt get this message.

**Comment by abvaidya** [comment]
nm. Looked at the pinned issue, its working as expected after manually upgrading it.
