### ISSUE TITLE
golang tool installer succeed in installing but vscode say that the command is not available

### ISSUE THREAD

**Issue by gekigek99** [golang/vscode-go#1332]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.15.2 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- percorso sia incluso e corretto, quindi riprovare. In riga:1 car:1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.54.2
fd6f3bce6709b121a895d042d343d71f317d74e7
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.23.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.

```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: C:\Users\gekigek99\go
GOROOT: C:\Program Files\Go
PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Go\bin;C:\Users\gekigek99\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\gekigek99\AppData\Local\Programs\Python\Python39\;C:\Users\gekigek99\AppData\Local\Microsoft\WindowsApps;C:\Users\gekigek99\AppData\Local\GitHubDesktop\bin;C:\Users\gekigek99\AppData\Local\Programs\Git\cmd;C:\Users\gekigek99\go\bin

   gopkgs: gopkgs not installed
   go-outline: go-outline not installed
   gotests: gotests not installed
   gomodifytags: gomodifytags not installed
   impl: impl not installed
   goplay: goplay not installed
   dlv: dlv not installed
   staticcheck: staticcheck not installed
   gopls: gopls not installed

go env
Workspace Folder (config yaml load): c:\Users\gekigek99\Desktop\config yaml load
	set GO111MODULE=auto
	set GOARCH=386
	set GOBIN=
	set GOCACHE=C:\Users\gekigek99\AppData\Local\go-build
	set GOENV=C:\Users\gekigek99\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=C:\Users\gekigek99\go\pkg\mod
	set GONOPROXY=
	set GONOSUMDB=
	set GOOS=windows
	set GOPATH=C:\Users\gekigek99\go
	set GOPRIVATE=
	set GOPROXY=https://proxy.golang.org,direct
	set GOROOT=C:\Program Files\Go
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	set GCCGO=gccgo
	set GO386=sse2
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=0
	set GOMOD=
	set CGO_CFLAGS=-g -O2
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-g -O2
	set CGO_FFLAGS=-g -O2
	set CGO_LDFLAGS=-g -O2
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m32 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\gekigek99\AppData\Local\Temp\go-build699436230=/tmp/go-build -gno-record-gcc-switches
```
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
{
    "workbench.startupEditor": "newUntitledFile"
}
```

### Describe the bug
A clear and concise description of what the bug.
after a clean install of vscode and the go extension, I receive a message from vscode that tools are missing, so I install them (from the notification window) and after a restart of vscode I receive the same message again
I expected the tools to be installed (I think they are) and vscode to recognize them and use them

### Steps to reproduce the behavior:
1. clean install of vs code
2. clean install of golang and of the go extension
3. in vscode press the install missing tools button
4. they all succeed installing but vscode can find them

### Comments:
the tools apparently are installed in `%GOPATH%\bin\windows_386`
moving the .exe files (gopls.exe, go-outline.exe ecc...) in `%GOPATH%\bin` seems to have solved the problem

Still it's not really convenient since updating them or installing other packages might result in the same error that would need to be solved by manually moving executables...

**Comment by hyangah** [comment]
@gekigek99 Thanks for the report. It looks like the tools were cross-compiled which I don't understand how
given that we explicitly delete [GOARCH](https://github.com/golang/vscode-go/blob/3f78921d4c067dd4d88ca311a9a6e13619818cac/src/goEnv.ts#L47) from the environment variables when installing tools. Maybe this trick doesn't work on windows?

If you run the command equivalent to this unix command, do you see them correctly installed in `$GOPATH/bin`? 
```
GOARCH=amd64 GO111MODULE=on go get -x -v golang.org/x/tools/gopls
``

**Comment by gekigek99** [comment]
this is the command and the relative output:

```
C:\Users\gekigek99>set GOARCH=amd64 && set GO111MODULE=on && go get -x -v golang.org/x/tools/gopls
cmd/go: unsupported GOOS/GOARCH pair windows/amd64
```

I'll try to install golang `go1.15.2.windows-386.msi` and see if anything changes

**Comment by gekigek99** [comment]
I tried installing the `386` version of `golang 1.15.2` and it seems to have installed them in the correct directory (`$GOPATH/bin`)

still... golang 64bit version does not seem to work properly...

**Comment by gekigek99** [comment]
ok I installed golang version 1.15.10 64bit and after a clean install i get this:

```
C:\Users\gekigek99>go env
set GO111MODULE=auto
set GOARCH=386
set GOBIN=
set GOCACHE=C:\Users\gekigek99\AppData\Local\go-build
set GOENV=C:\Users\gekigek99\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
...
```

I really cannot understand why `GOARCH=386` and `GOHOSTARCH=amd64`... (are you aware of similar problems?)

anyway setting `GOARCH=amd64` and installing manually the tools works correctly

maybe instead of using GOARCH for tool compilation GOHOSTARCH can be used?  
(it's a problem of all the tools that are by default installed)

**Comment by hyangah** [comment]
@gekigek99 I recommend fixing the `GOARCH` issue - otherwise, all of your go build/test output will be compiled in 386 mode 
 which you don't want unless you intentionally want to work with 386 mode.
 
Please double check if you have any system environment settings (maybe https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.1 or browse through the system setting), and if your GOENV file ( C:\Users\gekigek99\AppData\Roaming\go\env) is empty. 
 
 I use windows/amd64, and didn't see issues in clean install yet. :-(

**Comment by wtask** [comment]
@gekigek99 Could you install required tools outside vscode directly in console? Have you access to installed tools from everywhere in your Windows from console? Also does your local environment contains `git` binary?

**Comment by gekigek99** [comment]
@hyangah tahnks for the link i'll check it out
> if your GOENV file ( C:\Users\gekigek99\AppData\Roaming\go\env) is empty.

I checked and it contains:
```
GO111MODULE=auto
GOARCH=386
GOOS=windows
```

@wtask 
> @gekigek99 Could you install required tools outside vscode directly in console? Have you access to installed tools from everywhere in your Windows from console? Also does your local environment contains git binary?

- yes (but only after setting GOARCH=amd64 on that particular terminal session)
- what do you mean? I can run the tools executables from any folder
- yes but the problem is present also when I open a folder in vscode which does not contain a .git folder

**Comment by gekigek99** [comment]
apparently I had the go env file (`C:\Users\gekigek99\AppData\Roaming\go\env`) set like this:

```
GOARCH=386
GO111MODULE=auto
GOOS=windows
```

so that GOARCH was always set to 386 even though golang architecture was amd64

running `go env -u GOARCH` fixed the problem for me (remove the GOARCH parameter from go env file)
(also removing the go env file works)

**Comment by stamblerre** [comment]
Glad to hear you were able to resolve the issue. Is this OK to close now?

**Comment by gekigek99** [comment]
oh yea sure
