### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by levidurfee** [golang/vscode-go#1335]
gopls version: v0.6.5
gopls flags: 
extension version: 0.23.2
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

* I upgraded Golang from 1.15.6 to 1.16.1 using Brew
* I opened VSCode to work on a new Go project
* I was prompted to update the tools, so I said yes

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.6.6. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by levidurfee** [comment]
Result of updating `gopls` version using the Command Palette.

```
Tools environment: GOPATH=/Users/levidurfee/go
Installing 0 tool at /Users/levidurfee/go/bin in module mode.


All tools successfully installed. You are ready to Go :).
```

```
~ » gopls version                                                                                                        levidurfee@Levis-MacBook-Pro
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@(devel)
```

I open up vscode.

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/10798199/111053370-415fe680-8431-11eb-9873-851079076e5c.png">


```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/levidurfee/go
GOROOT: /usr/local/Cellar/go/1.16.1/libexec
PATH: /Users/levidurfee/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin

   gopkgs: /Users/levidurfee/go/bin/gopkgs installed
   go-outline: /Users/levidurfee/go/bin/go-outline installed
   gotests: /Users/levidurfee/go/bin/gotests installed
   gomodifytags: /Users/levidurfee/go/bin/gomodifytags installed
   impl: /Users/levidurfee/go/bin/impl installed
   goplay: /Users/levidurfee/go/bin/goplay installed
   dlv: /Users/levidurfee/go/bin/dlv installed
   staticcheck: staticcheck not installed
   gopls: /Users/levidurfee/go/bin/gopls installed

go env
Workspace Folder (cache-handler): /Users/levidurfee/Projects/github.com/golevi/cache-handler
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/levidurfee/Library/Caches/go-build"
	GOENV="/Users/levidurfee/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/levidurfee/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/levidurfee/go"
	GOPRIVATE=""
	GOPROXY="https://goproxy.dev,direct"
	GOROOT="/usr/local/Cellar/go/1.16.1/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.16.1/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.16.1"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/levidurfee/Projects/github.com/golevi/cache-handler/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xm/kssjcwc91_3bxpn1zt0vydx00000gn/T/go-build124464410=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

I upgraded to Go v1.16.2 and still the same issue.

**Comment by hyangah** [comment]
@levidurfee Did you click the checkbox for `gopls`? It seems like no tools from `Go: Install/Update Tools` were selected before clicking "OK".

**Comment by levidurfee** [comment]
@hyangah I thought I did click the checkbox for `gopls`, but I went ahead and did it again. Attached is a screenshot. I tried it with all tools, then just with `gopls`.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/10798199/111069282-ad2e6780-84a2-11eb-8878-67b72d6052bc.png">

Below is the result from upgrading all of the tools.

```
Tools environment: GOPATH=/Users/levidurfee/go
Installing 9 tools at /Users/levidurfee/go/bin in module mode.
  gopkgs
  go-outline
  gotests
  gomodifytags
  impl
  goplay
  dlv
  staticcheck
  gopls

Installing github.com/uudashr/gopkgs/v2/cmd/gopkgs (/Users/levidurfee/go/bin/gopkgs) SUCCEEDED
Installing github.com/ramya-rao-a/go-outline (/Users/levidurfee/go/bin/go-outline) SUCCEEDED
Installing github.com/cweill/gotests/gotests (/Users/levidurfee/go/bin/gotests) SUCCEEDED
Installing github.com/fatih/gomodifytags (/Users/levidurfee/go/bin/gomodifytags) SUCCEEDED
Installing github.com/josharian/impl (/Users/levidurfee/go/bin/impl) SUCCEEDED
Installing github.com/haya14busa/goplay/cmd/goplay (/Users/levidurfee/go/bin/goplay) SUCCEEDED
Installing github.com/go-delve/delve/cmd/dlv (/Users/levidurfee/go/bin/dlv) SUCCEEDED
Installing honnef.co/go/tools/cmd/staticcheck (/Users/levidurfee/go/bin/staticcheck) SUCCEEDED
Installing golang.org/x/tools/gopls (/Users/levidurfee/go/bin/gopls) SUCCEEDED

All tools successfully installed. You are ready to Go :).
```

Everything looks good, then I get the following messages.

```
[Error - 8:52:14 AM] Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
[Error - 8:53:16 AM] Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 
```

Also, I noticed that there are two `gopls` output options as shown in the below screenshot.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/10798199/111069332-f2529980-84a2-11eb-9699-5850d78584ab.png">

**Comment by hyangah** [comment]
@levidurfee thanks. Can you please check the followings?

* `/Users/levidurfee/go/bin/gopls -v version` ===> Should be v0.6.6, and  golang.org/x/tools@v0.1.1-0.20210222172741-77e031214674. 
* `ps -ax | grep gopls` or see Mac Activity Monitor to check the full path to the gopls binary. That should be `/Users/levidurfee/go/bin/gopls`. 

If the vscode is using the gopls, and its version is v0.6.6, just run "Developer: Reload Window" or "Go: Restart Language Server".

If the vscode isn't using the gopls (in /Users/levidurfee/go/bin/gopls ), need more investigation on why it picked up a different gopls. That also implies a bug in `Go: Locate Configured Go Tools` command.

The two separate output channels (gopls vs gopls (server)) are working as intended. one is for the client-side tracing (when using the `go.server.trace` setting), and the other is for the server-side tracing.

**Comment by levidurfee** [comment]
Here are the results from those commands.

```
~ » /Users/levidurfee/go/bin/gopls -v version                                                                                                       
Build info
----------
golang.org/x/tools/gopls v0.6.5
    golang.org/x/tools/gopls@v0.6.5 h1:kLt9rD/dWtVdvc8LmdcxagDFih6zxYXREpKSYYZu5KE=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.0 h1:8pl+sMODzuvGJkmj2W4kZihvVb5mKm8pB/X44PIQHv8=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210119212857-b64e53b001e4 h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
    golang.org/x/tools@v0.1.1-0.20210201201750-4d4ee958a9b7 h1:/wdPW261t381NDQd8TBo63/FyvACfLICwtH8wMRoHJQ=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

```
~ » ps -ax | grep gopls
31985 ttys018    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox gopls
```

I also ran `which gopls`

```
~ » which gopls
/usr/local/bin/gopls
```

Then I ran `/usr/local/bin/gopls -v version`

```
Build info
----------
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210222172741-77e031214674 h1:XzEjy9Ks1MwmcJOarbxTnL/AqHtzsRfRzAwfDhII2lE=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.1 h1:EVDuO03OCZwpV2t/tLLxPmPiomagMoBOgfPt0FM+4IY=
    mvdan.cc/gofumpt@v0.1.0 h1:hsVv+Y9UsZ/mFZTxJZuHVI6shSQCtzZ11h1JEFPAZLw=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

**Comment by hyangah** [comment]
Thanks for the info @levidurfee 
The extension correctly used what it should use. The issue seems to be the GOPROXY you are using.
https://goproxy.dev/golang.org/x/tools/gopls/@v/list currently has no v0.6.6. (The latest I see isv0.6.6-pre3).

I don't know why you have `/usr/local/bin/gopls` that is built in dev mode, but the extension prefers tools in GOBIN or GOPATH/bin currently.

If you want to continue to use tools installed in $GOPATH/bin:

* if proxy.golang.org is accessible:
GOPROXY=https://proxy.golang.org,direct go install golang.org/x/tools/gopls

* if proxy.golang.org isn't accessible:
GOPROXY=direct go install golang.org/x/tools/gopls

If you want to use tools installed in /usr/local/bin/gopls, delete `gopls` from your `$GOPATH/bin/`, and don't use the extension's tool installation commands. (but still I recommend to fix /usr/local/bin/gopls to be stable, not devel)

**Comment by levidurfee** [comment]
Thank you @hyangah  !

I run that GOPROXY so I did the following

* Cleared the cache
* Ran `go install golang.org/x/tools/gopls@v0.6.6` (version is required when current directory is not in a module)
* Opened up VSCode
* It works!

My issue is resolved. Thank you all for the help.
