### ISSUE TITLE
gopls: add Go version to automated issue reports

### ISSUE THREAD

**Issue by findleyr** [golang/vscode-go#1338]
When I get CCed on gopls issues related to go/* libraries, my first question is always which version of Go is being used.

Can we include this information in our automated issue reports?

CC @hyangah @stamblerre

**Comment by hyangah** [comment]
Do you want both go versions
  1) one used in building the gopls
  2) another that ** may be ** used by the gopls?
  
2) can be still different from what gopls actually uses in rare cases (due to a bug in PATH mapping, or due to users' configuration).

**Comment by findleyr** [comment]
Thanks, I think we want both. Mailed https://golang.org/cl/301749 to add runtime.Version() to the `gopls version` command.

**Comment by stamblerre** [comment]
Closing because I believe this has been resolved.
