### ISSUE TITLE
Mac not ready for Go extension on reboot due to Saved Application State

### ISSUE THREAD

**Issue by benguild** [golang/vscode-go#1339]
Issue Type: <b>Bug</b>

Hey guys I noticed that if I restart my Mac with Visual Studio Code open, it screws up my Go environment due to the "Saved Application State." 

See attached screenshot... it expects me to reinstall all of the Go tools in my non-GOPATH. (it defaults to `~/go` but I have it somewhere else... so using these options here creates a duplicate Go path)

Restarting the app works around this, but I would imagine this could be fixed.

Extension version: 0.23.1
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:09.783Z)
OS version: Darwin x64 20.3.0

<img width="469" alt="Screen Shot 2021-03-11 at 13 34 50" src="https://user-images.githubusercontent.com/1185659/111085140-a6701680-84db-11eb-9a92-148b5b6c2001.png">

**Comment by hyangah** [comment]
@benguild Go extension picks up the environment variables VS Code set for the extension host. I can't find official document explaining exactly how VS Code populates the environment variables for the extension host. But my understanding is that VS Code probes the environment variables from the default, interactive login shell. Check how your shell initialization is configured.

For example, if /bin/bash is used, the environment variables setting scripts should be called from `~/.bash_profile`.
  <pre>
  $ man bash
  ...
  When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it  first  reads  and
  executes  commands  from  the  file  /etc/profile,  if that file exists.  After reading that file, it looks for `~/.bash_profile`,
  `~/.bash_login`, and `~/.profile`, in that order, and reads and executes commands from the first one that exists  and  is  readable.
  ...
  </pre>

**Comment by benguild** [comment]
I wonder if this is a quirk with macOS because it works if you reboot VSCode.

**Comment by stamblerre** [comment]
@benguild: Does that mean you were able to resolve the issue?

**Comment by benguild** [comment]
No it's just a description of the problem haha

**Comment by stamblerre** [comment]
What shell are you using? I would suggest investigating the last pop-up in the image you shared--the one that says "Unable to resolve your shell environment in a reasonable time." As @hyangah said, that's probably causing the problem for the Go extension, and that pop-up is coming from VS Code itself, not the Go extension.

**Comment by benguild** [comment]
-> https://github.com/microsoft/vscode/issues/120479
