### ISSUE TITLE
debug: [dap: ext+DA] decision, documentation and/or implementation of relative paths support

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1348]
This is an umbrella issue. Each item below can be considered independently.

Directory/file paths come up in the following contexts:
- launch+debug/test: package/.go file/etc path for the program to be built and debugged
- launch+exec: binary path for the binary to be debugged
- setBreakpoint: breakpoint location is specified by the extension based on user click
- setFunctionBreakpoint: free-form path can be typed in by the user
- substitute paths: specified via launch/attach args, applied to requests and responses)
- output: where to write built binary (this is a file, not a directory)
- cwd: working directory for running the program

**For each of the above items, we need to decide when we allow absolute vs relative paths**. 

As @aarzilli noted in https://github.com/go-delve/delve/issues/2391#issuecomment-799489337, the trickiest thing with relative paths is to determine what they are relative to. This is true both for the implementers and for the users. Whatever we decide, we should log during execution and document (in --help and doc pages) what the directory roots are in all cases, both on the extension and adapter side (since the adapter might, in theory, be used with any dap client).

Then we need to decide if should guard/expand on the extension side and send only absolute paths to delve. In that case what would `"."` (e.g. current default for `cwd` attribute passed to dlv's `--wd`) mean? Dlv's current directory? Workspace?
 
Even if the extension takes care of everything, dlv-dap must be compatible with any dap client and should not make assumptions about paths always being absolute. So we should have guards/resolution logic on the delve side as well. Some of that might be handled by the Debugger backend and some things we might need to be handle in the dap server handlers. Our dap unittests should "document" all cases.

Related: https://github.com/go-delve/delve/issues/2391, https://github.com/go-delve/delve/pull/2360, https://github.com/go-delve/delve/issues/2392

**Comment by polinasok** [comment]
cc @suzmue @hyangah

**Comment by aarzilli** [comment]
I'm not sure about the motivation behind this. If vscode doesn't send relative paths and there are no known clients that send relative paths (are there?), then why?

**Comment by polinasok** [comment]
> I'm not sure about the motivation behind this. If vscode doesn't send relative paths and there are no known clients that send relative paths (are there?), then why?

Breakpoint paths are controlled by vscode. Launch program paths are controlled by the user, so they can be anything. We have some conversations about these recently, and people were not sure either way, so my motivation by filing this issue was to just capture what we know, don't know, should know with some mental TODOs. The adapter is still work in progress, it is not actively being used yet, including by vscode, but we have had other potential clients reach out with interest, so it is not unlikely that more dap clients might give it a go in a foreseeable future.

**Comment by polinasok** [comment]
> Breakpoint paths are controlled by vscode.

With the addition of FunctionBreakpoints (https://github.com/go-delve/delve/pull/2450), users can now supply relative filepaths via the UI. @suzmue Do they get forwarded to delve as-is?

**Comment by suzmue** [comment]
Function Breakpoints uses `NormalLocationSpec.Find()` to resolve the location that is passed in.
It checks that the path is the suffix of a filename to find candidate files and relative paths are checked using:
```
func tryMatchRelativePathByProc(expr, debugname, file string) bool {
	return len(expr) > 0 && expr[0] == '.' && file == path.Join(path.Dir(debugname), expr)
}
```

And debugname is `s.debugger.processArgs[0]` which is the binary location, not the working directory nor delves working directory.

I think we have 2 options for relative paths in function breakpoints:
1. reject any names that start with `.`
2. resolve them relative to the working directory (for launch requests)

Since function breakpoints aren't intended to be used to set breakpoints for filename and line numbers, I think for now we do (1), unless there are valid function names that begin with `.`.

**Comment by hyangah** [comment]
I agree that the option 1 is good if it starts with `.` or `..`. 
As a delve user, I expected the function breakpoint follows the usual delve location spec rule (not the relative path, but whether the given name can be unambiguously a suffix of a file name). Resolving them to any directory behind the scene doesn't make sense.

**Comment by hyangah** [comment]
@polinasok Can you clarify the purpose of this issue? I think vscode tries to do the best to use the absolute path if possible. 
From the original issue report: 
> For each of the above items, we need to decide when we allow absolute vs relative paths.

I think this is completely up to delve dap (and provides a comprehensive error message if it cares), and I am not sure what to do from this extension side any further. Should we close this issue?

**Comment by polinasok** [comment]
Anticipating issues like #1680 is the reason why I suggested we do this audit.

* launch+debug/test: package/.go file/dir path for the program to be built and debugged
   * dlv-dap
      * relative paths -- accepted (passed as-is to gobuild)
      * relative to -- dlv's wd
      * [This PR](go-delve/delve#2653) adds tests, missing logging and --help note
   * vscode-go:
      *  relative paths -- accepted
      *  relative to -- workspace => absolute path is passed to dlv-dap
      * Documented in [package.json](https://github.com/golang/vscode-go/blob/b4226abc79a4cea022cd9834e3a083b34bcf4a59/package.json#L545) + logged as part of launch request
      * __TODO__: reconsider in light of #1680
* launch+exec: binary path for the binary to be debugged
   * Same as above
* output: where to write built binary (this is a file, not a directory)
    * dlv-dap
      * relative paths -- accepted
      * relative to -- dlv's wd
    * vscode-go:
       *  relative paths -- accepted
       *  relative to -- workspace => absolute path is passed to dlv-dap
* cwd: working directory for running the program
   * TBD
* setBreakpoint: breakpoint location is specified by the extension based on user click
   * TBD 
* setFunctionBreakpoint: free-form path can be typed in by the user
   * TBD 
* substitute paths: specified via launch/attach args, applied to requests and responses
    * TBD

**Comment by polinasok** [comment]
Related discussions: #go-delve/delve/issues/2507, go-delve/delve/pull/2660

**Comment by hyangah** [comment]
Let's close this as documentation work was mostly done on both vscode-go and delve sides.
