### ISSUE TITLE
test: add automated test for debug adapter

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#137]
_From https://github.com/microsoft/vscode-go/issues/2382 by @lggomez:_

This issue is to keep track and brainstorm about ideas on how to add unit test support to the debug adapter

As of today, the debug adapter is the only part of the extension without tests and the most prone to regressions, due to the fact that it relies on the debugger process to work, and we still lack a standarized set of fixtures to run smoke tests (and, additionally, an automated way to do so)

I think that we should be able to add coverage for any basic scenarios we want (forget about remote for now), but some changes may be required to achieve this. The obvious to me are these:

Decouple GoDebugSession.Delve into an interface so it can be mocked
Finding a way to 'record' real scenarios so we can use those as the test cases. This means being able to intercept the json-rpc2 client apicalls. I believe this would allow us to test the debug protocol request implementations to some extent; logging request I/O and using those would be enough for now
Extra (and harder): Make a runner that is able to create and communicate with a GoDebugSession instance, which is the main entry point and contains most of the debugger-related logic of the adapter. This implies simulating a basic debug adapter lifecycle for each desired scenario (run and exit, breakpoints, pause, etc)

As Go and Delve evolve this should be a priority in the medium to long term roadmap, as it makes the development process more resilient against big changes and refactors in this area

**Comment by polinasok** [comment]
A smokes test that will ensure that most basic operations (start-up, shutdown, restart, set breakpoint, continue, etc) are working should be our top priority. We do not want to break the basics while adding some advanced feature or fixing an obscure bug.

Once something basic is in place, we can look into a more expanded set of tests. There are some interesting test cases and a report of how vscode-go did in 2019 at https://github.com/go-delve/delve/blob/master/Documentation/api/ClientHowto.md#testing-the-client.

**Comment by suzmue** [comment]
Since we are making the move to use the delve dap implementation, the current testing plan is to avoid making major changes to the old debug adapter in order to test. 

I have added some tests of the DAP implementation using the test support provided by [microsoft/vscode-debugadapter](github.com/microsoft/vscode-debugadapter). These tests should continue to be able to test the new debug adapter as well.

**Comment by hyangah** [comment]
@suzmue Since now we have the test framework, can we close this issue? (Or maybe close this after your pending cl to run the same tests for delve dap?)
