### ISSUE TITLE
Failed to find the "go" binary in either GOROOT() or PATH

### ISSUE THREAD

**Issue by lucas-marx** [golang/vscode-go#1400]
I've installed Go following the documentation https://golang.org/doc/install and then installed the go extension but when I open the code studio i get this error: `"Failed to find the "go" binary in either GOROOT() or PATH(/app/bin:/usr/bin:/home/lucas/.var/app/com.visualstudio.code/data/node_modules/bin).Check PATH, or Install Go and reload the window. If PATH isn't what you expected, see https://github.com/golang/vscode-go/issues/971"`

I've tried looking for some answer but could not solve it... when I run go env on my terminal i get this:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/lucas/.cache/go-build"
GOENV="/home/lucas/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/lucas/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/lucas/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2734927735=/tmp/go-build -gno-record-gcc-switches"

```
what can I do to debug it and find what I did wrong?

**Comment by hyangah** [comment]
The extension gets `PATH` environment variable from VSCode. And according to the error message, the PATH VSCode sees doesn't include `/usr/local/go/bin`. (`/app/bin:/usr/bin:/home/lucas/.var/app/com.visualstudio.code/data/node_modules/bin`). 

How VS Code populates the environment variables had been changed recently, but in general, it gets them either by
1) inherit from the terminal environment if it's launched from a terminal, or
2) get it from your login shell (`~/.bash_profile`, `~/.bash_login`, or `~/.profile` if you are using `bash` for example. ), if it's launched using application launchers or shortcuts.

Frequently seen culprits are the PATH is configured in `~/.bashrc` but it's not used in a login shell automatically.

**Comment by lucas-marx** [comment]
Thanks for the response... I've included PATH=$PATH:/usr/local/go/bin on my ~/.profile but it's still not working.

**Comment by hyangah** [comment]
Did you restart vscode and relaunched it after fixing your ~/.profile?

**Comment by lucas-marx** [comment]
Yes.
After that I tried running my vs code with the `code .` via terminal but the command wasn't found, I uninstalled the vs code, installed again using the snap store, installed the go extension again and it's working fine now.
Thanks for the help!
