### ISSUE TITLE
debug: support logging to a file with dlv-dap

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1407]
With certain "trace" attribute settings, the legacy adapter prints:
```
Verbose logs are written to:
/var/folders/dn/8hszkj9x21n__1gr_p8qgjgr0007jz/T/vscode-go-debug.txt
```
That's very convenient.
Can we set up trace for dlv-dap to capture whatever we get from dlv-dap and not just write it to debug console, but also write to a file?

**Comment by hyangah** [comment]
Thanks for filing the issue. I hoped we could've used `--log-dest` flag of delve but unfortunately, that breaks the current dlv-dap integration. The plan I had is to pass a file descriptor to `--log-dest`, and process the stream while teeing the logging info to user-specified file (if any). That way, we can also avoid crowding the DEBUG OUTPUT with the logging messages.

**Comment by polinasok** [comment]
I somehow missed that this got closed. So is `logDest` in `launch.json` the final solution? This will only capture dlv logging, not the program output, right? And when it is set, then no logging will go to the Debug Console, won't it?

I actually quite liked the way the legacy logging worked. It was convenient to be able both log to the console and to the file at the same time. I liked that I did not need to choose a file myself and that there was some default and the location was printed to the debug console. And it was often convenient to have all the output, from the extension, from delve and from the target in one place. Do you have ideas/plans on how to provide similar functionality with the new adapter?

**Comment by hyangah** [comment]
Yes, use `logDest` will write whatever output by delve's logger.
I modeled the current behavior based on the dlv's logging behavior - when `--log-dest` is provided, log is written to the file, and doesn't pollute stderr/stdout. If you prefer having the logging also printed in the debug console, it's an easy change to make though.

I am reluctant to add more logic in this thin adapter. This is the part we all want to get rid of eventually once dlv dap is capable of handling stdout/stderr. If you think creating a log file by default and writing logs to both ends is an important feature gap, I think it should be implemented in the dlv. Most of all, the logging logic belonged to the old debug adapter, not the extension.
