### ISSUE TITLE
debug: fix and expand extension logging for dlv-dap and process teardown

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1410]
When the dlv-dap server is started by the extension, the extension manages its lifecycle. For troubleshooting sticky situations and identifying issues, it would be great if it logged when the server is being shutdown from the extension side. We do have shutdown logging in dlv-dap, but that assumes that dlv-dap is shutting down cleanly and that dlv-dap chatty logging is on. That won't help us with cases where dlv is unresponsive or has crashed (potentially with the child process still lingering), so the extension needs to be doing some force-cleanup. 

We already print at start-up
```
Running: /Users/polina/go/bin/dlv-dap dap ...etc...
```
And sometimes I see this, but  it seems very inconsistent:
```
Process exited normally: false
```
It would be great if there was a reliable message at the end, whether things exited normally or not, both on the process and the debugger side. We could print something short by default and have additional details if "trace" attribute is on.

**Comment by polinasok** [comment]
Playing with `Process exited normally: false` a bit more. Something is not right.
```
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${file}",
            "debugAdapter": "dlv-dap",
            "showLog": true,
```

```
package main

func main() {
	return
}
```

Debug session 1 outputs:
```
Running: /Users/polina/go/bin/dlv-dap dap --listen=127.0.0.1:63496 --log=trueDAP server listening at: 127.0.0.1:63496
2021-04-08T17:28:27-07:00 info layer=debugger launching process with args: [/Users/polina/go/src/__debug_bin]
2021-04-08T17:28:27-07:00 debug layer=debugger continuing
```
Debug session 2 outputs:
```
Running: /Users/polina/go/bin/dlv-dap dap --listen=127.0.0.1:63541 --log=trueDAP server listening at: 127.0.0.1:63541
2021-04-08T17:29:20-07:00 info layer=debugger launching process with args: [/Users/polina/go/src/__debug_bin]
2021-04-08T17:29:20-07:00 debug layer=debugger continuing
2021-04-08T17:29:20-07:00 debug layer=debugger halting
2021-04-08T17:29:20-07:00 debug layer=debugger detaching
2021-04-08T17:29:20-07:00 debug layer=debugger detaching
Process exited normally: false
```
```

**Comment by hyangah** [comment]
Please follow the [troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md#reporting-issues) and include the dlv-dap's version information.

**Comment by polinasok** [comment]
```
$ go version -m  /Users/polina/go/bin/dlv-dap
/Users/polina/go/bin/dlv-dap: go1.14.3
	path	github.com/go-delve/delve/cmd/dlv
	mod	github.com/go-delve/delve	v1.6.1-0.20210407080014-c4b9c8584309	h1:gaXLIMtjalnxdCfPK6Tyh5fTFMN4e8t5WQ+nZOgnw84=
	dep	github.com/cosiner/argv	v0.1.0	h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
	dep	github.com/cpuguy83/go-md2man	v1.0.10	h1:BSKMNlYxDvnunlTymqtgONjNnaRV1sTpcovwwjF22jk=
	dep	github.com/google/go-dap	v0.4.0	h1:bWSjcM9zp/jEFD4YbWERcHSed8vHbEdk0rmTvqgXDAs=
	dep	github.com/hashicorp/golang-lru	v0.5.4	h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
	dep	github.com/mattn/go-isatty	v0.0.3	h1:ns/ykhmWi7G9O+8a448SecJU3nSMBXJfqQkl0upE1jI=
	dep	github.com/peterh/liner	v0.0.0-20170317030525-88609521dc4b	h1:8uaXtUkxiy+T/zdLWuxa/PG4so0TPZDZfafFNNSaptE=
	dep	github.com/russross/blackfriday	v1.5.2	h1:HyvC0ARfnZBqnXwABFeSZHpKvJHJJfPz81GNueLj0oo=
	dep	github.com/sirupsen/logrus	v1.6.0	h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
	dep	github.com/spf13/cobra	v0.0.0-20170417170307-b6cb39589372	h1:eRfW1vRS4th8IX2iQeyqQ8cOUNOySvAYJ0IUvTXGoYA=
	dep	github.com/spf13/pflag	v0.0.0-20170417173400-9e4c21054fa1	h1:7bozMfSdo41n2NOc0GsVTTVUiA+Ncaj6pXNpm4UHKys=
	dep	go.starlark.net	v0.0.0-20200821142938-949cc6f4b097	h1:YiRMXXgG+Pg26t1fjq+iAjaauKWMC9cmGFrtOEuwDDg=
	dep	golang.org/x/arch	v0.0.0-20190927153633-4e8777c89be4	h1:QlVATYS7JBoZMVaf+cNjb90WD/beKVHnIxFKT4QaHVI=
	dep	golang.org/x/sys	v0.0.0-20200625212154-ddb9806d33ae	h1:Ih9Yo4hSPImZOpfGuA4bR/ORKTAbhZo2AbWNRCnevdo=
	dep	gopkg.in/yaml.v2	v2.2.1	h1:mUhvW9EsL+naU5Q3cakzfE91YhliOondGd6ZrsDBHQE=
```

**Comment by polinasok** [comment]
I am not worried about inconsistent logging from the delve side. The above log only included debugger logging. If you turn on dap logging as well, you will see that after continue, there are the following things happening:
```
2021-04-08T22:35:46-07:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"terminated","body":{}}
2021-04-08T22:35:46-07:00 debug layer=dap [<- from client]{"seq":5,"type":"request","command":"threads"}
2021-04-08T22:35:46-07:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":5,"success":true,"command":"threads","body":{"threads":null}}
2021-04-08T22:35:46-07:00 debug layer=dap [<- from client]{"seq":6,"type":"request","command":"disconnect","arguments":{}}
2021-04-08T22:35:46-07:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":6,"success":true,"command":"disconnect"}
```
And sometimes the log ends there. Other times you get
```
2021-04-08T22:49:11-07:00 debug layer=debugger halting
2021-04-08T22:49:11-07:00 debug layer=dap Process 50461 has exited with status 0
2021-04-08T22:49:11-07:00 debug layer=debugger detaching
2021-04-08T22:49:11-07:00 debug layer=debugger detaching
```
The disconnect handler right now uses fire-and-forget approach: the disconnect response is sent first and then the rest of the teardown happens. So if the client gets the disconnect response before all the halting and detaching, it will disconnect. Or maybe ​the last couple of logging messages don't get flushed in time. This reminds me though that I have been meaning to move the disconnect response to after we detached.

But in either case, we would not know any of this, unless dlv-dap logging was on. So we really do need the extension to tell us from its end if things have exited and with what status. This was also the reason why "process has exited with status" message was error-logged from delve, so we get it no matter what, but that was changed in https://github.com/go-delve/delve/pull/2412. Perhaps we should consider bringing it back.
