### ISSUE TITLE
debug: missing newline in dlv-dap logging

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1412]
At start-up I get:
```
Running: /Users/polina/go/bin/dlv-dap dap --listen=127.0.0.1:63541 --log=trueDAP server listening at: 127.0.0.1:63541
```
instead of
```
Running: /Users/polina/go/bin/dlv-dap dap --listen=127.0.0.1:63541 --log=true
DAP server listening at: 127.0.0.1:63541
```
I think it's coming from here https://github.com/golang/vscode-go/blob/505f363cadcc939d3b8572a50a243db8cb60a111/src/goDebugFactory.ts#L305, which has a newline, so I am not sure what's going on.

**Comment by hyangah** [comment]
That's fixed in https://go-review.googlesource.com/c/vscode-go/+/306789/ but didn't make it to 0.24.0. Will be included in the release next week.

**Comment by polinasok** [comment]
Ah, good to know. I guess I should stop playing with the released version and use something fresher :)
