### ISSUE TITLE
debug: dlv-dap mode doesn't handle launch failure when current opened file is launch.json

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1413]
```
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${file}",
            //"debugAdapter": "dlv-dap",
            "showLog": true,
            "logOutput": "rpc,debugger,dap",
```

The following often happens to me:
- Have .go file and a launch.json file open
- Select launch.json to check some option and/or make some change
- Forget to navigate back to the go file
- Start debugging
- Get a pop-up `Failed to continue: "The program attribute must be a directory or .go file in debug mode"` with the following logged in the Debug Console: `The program "/Users/polina/go/src/foo/.vscode/launch.json" must be a valid go file in debug mode`

Doing the same with `"debugAdapter": "dlv-dap"`, I get only this in the log (no launch failure logging)
```
Running: /Users/polina/go/bin/dlv-dap dap --listen=127.0.0.1:63983 --log=true --log-output=rpc,debugger,dap
```
and then nothing but the option to stop/restart with the little blue marker running and running in the UI:
![image](https://user-images.githubusercontent.com/51177946/114112799-fbf8d280-9891-11eb-8d6f-be8de5974eb1.png)
I then have to manually click Stop.

If I do the same thing using `"debugServer":54321` to connect to an external instance of dlv-dap running in another terminal at port 54321, I get a (less informative) pop-up
```
Failed to launch: Build error: exit status 1
```
and the following log
```
2021-04-08T17:53:10-07:00 debug layer=dap building binary at /Users/polina/delve/__debug_bin
can't load package: package /Users/polina/go/src/foo/.vscode/launch.json: cannot find package
```

**Comment by hyangah** [comment]
Thanks for the report. I see the following log from the dev console.

```
  ERR The program attribute must be a directory or .go file in debug and test mode: Error: The program attribute must be a directory or .go file in debug and test mode
    at parseProgramArgSync (/Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59719:15)
    at /Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59643:21
    at Generator.next (<anonymous>)
    at /Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59369:71
    at new Promise (<anonymous>)
    at __webpack_modules__.52390.__awaiter (/Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59365:12)
    at spawnDlvDapServerProcess (/Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59619:12)
    at /Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59612:36
    at Generator.next (<anonymous>)
    at fulfilled (/Users/hakim/.vscode/extensions/golang.go-0.24.0/dist/goMain.js:59366:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Looks like we are not catching the error thrown here https://github.com/golang/vscode-go/blob/505f363cadcc939d3b8572a50a243db8cb60a111/src/goDebugFactory.ts#L393 

We can try to catch the error and start teardown (& print the error message in the DEBUG CONSOLE or popup for better visibility). 
Alternatively, before starting the thin adapter from the factory, we can parse the args and fail early. 

cc @suzmue
