### ISSUE TITLE
Error loading workspace in VSCode

### ISSUE THREAD

**Issue by AnannyaShanmugam23** [golang/vscode-go#1415]
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <v1.15>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <v0.6.9>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <1.55.0>
* Check your installed extensions to get the version of the VS Code Go extension
	- <v0.24.0>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <GOBIN: undefined
toolsGopath: 
gopath: /home/xyz/go
GOROOT: /usr/local/go
PATH: /usr/local/go/bin:/home/xyz/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xyz/go/bin:/home/xyz/go/bin

   gopkgs: /home/xyz/go/bin/gopkgs installed
   go-outline: /home/xyz/go/bin/go-outline installed
   gotests: /home/xyz/go/bin/gotests installed
   gomodifytags: /home/xyz/go/bin/gomodifytags installed
   impl: /home/xyz/go/bin/impl installed
   goplay: /home/xyz/go/bin/goplay installed
   dlv: /home/xyz/go/bin/dlv installed
   dlv-dap: /home/xyz/go/bin/dlv-dap installed
   staticcheck: /home/xyz/go/bin/staticcheck installed
   gopls: /home/xyz/go/bin/gopls installed

go env
Workspace Folder (ddi.dns.config): /home/xyz/go/src/github.com/ABC/ddi.dns.config
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/xyz/.cache/go-build"
	GOENV="/home/xyz/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/xyz/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/xyz/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="0"
	GOMOD=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build432453671=/tmp/go-build -gno-record-gcc-switches">

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
Everytime i open a repo on my vscode, i get an error at the bottom saying Error loading worksapce: err: exit status 1: stderr: unexpected directory layout: 	import path:
Due to this error, vscode doesnt show errors in our code and i cant jump between methods and files in my repo 
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).
