### ISSUE TITLE
Code is crashing every 5 minutes

### ISSUE THREAD

**Issue by makispapapa** [golang/vscode-go#1418]
Issue Type: <b>Bug</b>

No idea whether i can do something so you manualy to reproduce it. 
It happens to me all the time

gopls seems that is occupying all 16GB memory after 2-=3 min

Extension version: 0.24.0
VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:01:24.315Z)
OS version: Linux x64 5.8.0-48-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz (8 x 2749)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.07GB (0.21GB free)|
|Process Argv|--no-sandbox --crash-reporter-id 96da83be-dcda-4e0f-a935-06756378413e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by heschi** [comment]
Please follow the instructions at https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#debug-memory-usage to upload a memory usage .zip.
