### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by diaohaha** [golang/vscode-go#1419]
gopls version: v0.5.3
gopls flags: 
update flags: proxy
extension version: 0.24.0
go version: 1.14.7
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by heschi** [comment]
Please update to the latest gopls version following the instructions at https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#update-tools.

**Comment by hyangah** [comment]
Closing. @diaohaha Please open a new issue if you experience the same issue even after updating gopls.
