### ISSUE TITLE
gopls: deduplicate diagnostics from gopls / linters

### ISSUE THREAD

**Issue by ramya-rao-a** [golang/vscode-go#142]
Below is an example where we have the same diagnostic being presented by both the language server and the linter

![image](https://user-images.githubusercontent.com/6326271/57776815-cd4e3d80-76f6-11e9-8623-d4b2bfabd484.png)

When LSP was not in the picture, such duplicates were removed in https://github.com/microsoft/vscode-go/blob/0.10.2/src/util.ts#L747 and https://github.com/microsoft/vscode-go/blob/0.10.2/src/util.ts#L756

We might have to do something similar to remove duplicates between LSP and the linting tool.

This issue is created from https://github.com/microsoft/vscode-go/issues/2517 by @lggomez

**Comment by stamblerre** [comment]
My preference here would be that we leave this behavior as-is. `golint` will likely be deprecated soon (https://github.com/golang/go/issues/38968) and staticcheck is already part of `gopls`, which leaves `golangci-lint` and `revive`.

The error shown in the image here is a build error, so I would hope that these linters don't return such errors. If there are duplicate errors, I'm not sure that it is worth deduping them.

**Comment by dominikh** [comment]
> The error shown in the image here is a build error, so I would hope that these linters don't return such errors. If there are duplicate errors, I'm not sure that it is worth deduping them.

Linters do return build errors if being run on code with build errors.

**Comment by stamblerre** [comment]
Hm ok, I didn't realize. Then maybe this issue is specific to golint, and if that's deprecated we can deprecate it as a lintOnSave option.

**Comment by ramya-rao-a** [comment]
You can try changing the `go.lintTool` to other tools and see what the behavior then is

**Comment by ramya-rao-a** [comment]
But it has happened that `go vet` and a linter would provide the same diagnostics. If `gopls` does vetting, then the case of duplication would still be valid and also the need for de-duplicaton

**Comment by stamblerre** [comment]
Sure. Adding a bit of deduplication will not be difficult, as long as the error range and message are exactly the same.

**Comment by hyangah** [comment]
The existing deduplication code for go vet/lint/build errors: https://github.com/golang/vscode-go/blob/master/src/util.ts#L835-L923

We can intercept the diagnostics from Language Server using `handleDiagnostics` middleware. (e.g. https://go-review.googlesource.com/c/vscode-go/+/222338/1/src/goLanguageServer.ts)

cc @suzmue
