### ISSUE TITLE
import of modules in submodules gives "could not import"

### ISSUE THREAD

**Issue by DasJott** [golang/vscode-go#1420]
Sorry for not using the (huge) template here. Problem is as follows:

**I want to import `github.com/revzim/gongrok` into my project.**  

There is one project (one mod) where I use it within one single package of that project.  
Everything works fine there. I made `go get` and it was entered into go.mod (and go.sum).  

There is another project full of folders that are submodules. There is no main go.mod, but every package is a single mod.  
In this project I get the import underlined red where the tooltip says, that this import could not be found in the default folders (GOROOT, GOPATH).  
I did the same there, `go get` and it even is entered in the according go.mod file (and go.sum).
While the extension (linter?) says that it can not import the package, the compiler sees no problem here. The single mod compiles jsut fine. What annoys me is that the extension provides no intellisense whatsoever because it claims that the gongrok package can not be imported (which is wrong).

So I'm assuming, that this extension has problems with submodules, because this is the only difference between the project that runs just fine and the one where the extension does strange things.

I made two test projects to spot the difference. Simply unpack to go/src.
[test.zip](https://github.com/golang/vscode-go/files/6309883/test.zip)

**Comment by DasJott** [comment]
Okay, I investigated a little further and got to a more clear point.  
It seems that something breaks if multiple modules are in parallel.  

Since go has modules, a `go get` does not load the package into `go/src` anymore, but instead into the `go/pkg/mod`.  
That means, that the packages are not necessarily existing in `go/src` anymore. Which is okay, because it finds the needed packages in that (new) destination.  

**But** if you have more than one module parallel in a project, something breaks that search mechanism.  
Suddenly the extension (or whatever is responsible for this behavior) searches in `go/src` again and doesn't find it there.

Please see [this new file](https://github.com/golang/vscode-go/files/6311539/test.zip) to see the described behavior.  
Note that if you delete the other package it finds the import. You might have to reload vscode window to see.

I am pretty unsure whether this is a bug in this extension or in go itself.

**Comment by heschi** [comment]
I haven't looked at your repro in detail, but from the description it sounds like it's working as intended at the moment. See the documentation at https://github.com/golang/tools/blob/master/gopls/doc/workspace.md. You might be interested in the experimental workspace module mode.

Can you look at that document and let us know if answers your questions?
