### ISSUE TITLE
debug: duplicate notifications about missing `dlv-dap` when debug test codelens is used

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1426]
Extension version: v0.24.1-rc.3
no dlv-dap installed

How to repro:

- make sure dlv-dap isn't installed in the system.
- enable dlv-dap from settings.json, 
```
"go.delveConfig": {
        "debugAdapter": "dlv-dap",
 }
 ```
 - click any 'debug test' codelens from a test go file.
 
 What I expected to see:
 Extension suggesting dlv-dap installation.
 
 What I saw instead:
 Extension triggered duplicate notification popups with no clear tool installation instruction.
![Screen Shot 2021-04-15 at 11 59 17 AM](https://user-images.githubusercontent.com/4999471/114901624-fac02c00-9de2-11eb-98f8-b3770a260c2c.png)

In DEBUG CONSOLE, I saw error message like "Couldn't find dlv-dap at the Go tools path, /Users/hakim/go, /Users/hakim/go or <my PATH>..." followed by the same "connect to server error:..." error messages.

**Comment by suzmue** [comment]
I think this is because we attempt to connect each time a message is sent to the server, which I think happens twice on startup. To fix this we can add some code to only attempt to connect once.
