### ISSUE TITLE
src/goCheck: lintOnSave setting is undefined after function signature change of goLint

### ISSUE THREAD

**Issue by ToothlessGear** [golang/vscode-go#1429]
In 0058bd16ba31394f98aa3396056998e4808998a7 a new parameter in the `goLint` function for `goplsConfig` has been added, which is not reflected in `src/goCheck.ts`.
https://github.com/golang/vscode-go/blob/a9b31d966d87ffe27af9ad601354634fc359e039/src/goCheck.ts#L113

This results in an `undefined` linting scope. No matter what configuration option in `settings.json` for `go.lintOnSave` has been selected, it therefore will always fall back to the `package` scope.

The regression occurs since version `0.24.0`.

**Comment by hyangah** [comment]
Fix was released as v0.24.2. Thanks for the report @ToothlessGear !
