### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by josharian** [golang/vscode-go#1433]
gopls version: v0.6.10
gopls flags: -rpc.trace serve --debug=localhost:6066
update flags: proxy
extension version: 0.24.0
go version: 1.16.3
environment: Visual Studio Code darwin
initialization error: undefined
manual restart count: 0
total start count: 1

Describe what you observed.

I was working. Then an alert popped up. I hit "Yes". :)

<pre>panic: unreachable

goroutine 30447 [running]:
go/types.(*Checker).handleBailout(0xc00a2f30e0, 0xc00a66b818)
	  check.go:245  0x9f
panic(0x18d4c80, 0x1b49ba0)
	  panic.go:965  0x1b9
go/types.unreachable(...)
	  errors.go:25
go/types.(*Checker).assignment(0xc00a2f30e0, 0xc00aaaed80, 0x1b5f5c0, 0xc0044897d0, 0x1a1cb25, 0xa)
	  assignments.go:29  0x9ef
go/types.(*Checker).initVar(0xc00a2f30e0, 0xc00aa91c70, 0xc00aaaed80, 0x1a1cb25, 0xa, 0x100f300, 0xc004efd678)
	  assignments.go:141  0x148
go/types.(*Checker).initVars(0xc00a2f30e0, 0xc004efd670, 0x1, 0x1, 0xc005d123c0, 0x1, 0x1, 0x0)
	  assignments.go:264  0x633
go/types.(*Checker).shortVarDecl(0xc00a2f30e0, 0x1b5c160, 0xc0091b9380, 0xc005d123b0, 0x1, 0x1, 0xc005d123c0, 0x1, 0x1)
	  assignments.go:339  0x27e
go/types.(*Checker).stmt(0xc00a2f30e0, 0x3, 0x1b6a9a0, 0xc00a67afc0)
	  stmt.go:408  0x3d05
go/types.(*Checker).stmtList(0xc00a2f30e0, 0x3, 0xc00623e100, 0xf, 0x10)
	  stmt.go:120  0xd1
go/types.(*Checker).stmt(0xc00a2f30e0, 0x3, 0x1b6aac0, 0xc004488450)
	  stmt.go:495  0x480a
go/types.(*Checker).stmt(0xc00a2f30e0, 0x0, 0x1b6b000, 0xc00a2bba40)
	  stmt.go:876  0x2a72
go/types.(*Checker).stmtList(0xc00a2f30e0, 0x0, 0xc00a67a840, 0x4, 0x4)
	  stmt.go:120  0xd1
go/types.(*Checker).funcBody(0xc00a2f30e0, 0xc0035e68a0, 0xc00635d033, 0x3, 0xc005bee4b0, 0xc004488480, 0x0, 0x0)
	  stmt.go:42  0x1f3
go/types.(*Checker).funcDecl.func1()
	  decl.go:749  0x67
go/types.(*Checker).processDelayed(0xc00a2f30e0, 0x0)
	  check.go:291  0x3e
go/types.(*Checker).checkFiles(0xc00a2f30e0, 0xc006088078, 0x3, 0x3, 0x0, 0x0)
	  check.go:267  0xd0
go/types.(*Checker).Files(...)
	  check.go:250
golang.org/x/tools/internal/lsp/cache.typeCheck(0x1b6c878, 0xc00a2b95c0, 0xc0091c2340, 0xc000224460, 0x2, 0xc002241440, 0x0, 0x0, 0x0)
	  check.go:451  0x1173
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1(0x1b6c878, 0xc00a2b95c0, 0x1b5b080, 0xc0091c2340, 0x18d3280, 0xc00095b7e0)
	  check.go:121  0x1bc
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc005291560, 0x1b6c878, 0xc00a2b95c0, 0xc0023e0ae0, 0x1b5b080, 0xc0091c2340, 0xc0016b3ec0)
	  memoize.go:322  0xab
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x185
[Error - 8:55:03 PM] </pre>

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report.  This is, unfortunately, a known panic in go/types. See also https://golang.org/issue/44397.  It is fixed at tip Go.

Given that it  *seems* to be very rare, and is probably infeasible to guard against in gopls, I'm closing this as unactionable. Please reopen if you encounter this frequently. Sorry.
