### ISSUE TITLE
go.mod module name hint err without change any setting but update vscode and extensions.

### ISSUE THREAD

**Issue by PseudoCowboy** [golang/vscode-go#1437]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.13.4 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Build info
----------
golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=
    github.com/google/go-cmp@v0.5.4 h1:L8R9j+yAqZuZjsqh/z+F1NCffTKKLShY6zXTItVIZ8M=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.1 h1:Kvvh58BN8Y9/lBi7hTekvtMpm07eUZ0ck5pRHpsMWrY=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/sys@v0.0.0-20210124154548-22da62e12c0c h1:VwygUrnw9jn88c4u8GD3rZQbqrP/tgas88tPUbBxQrk=
    golang.org/x/tools@v0.1.1-0.20210408155258-593413344da1 h1:B+9Jhwu5uM+kDMAkoQH6IUoIoS48VbRqwLyceNdpRK8=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.55.2
3c4e3df9e89829dce27b7b5c24508306b151f30d
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.24.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- GOBIN: /Users/***/go/bin
toolsGopath: /Users/***/go
gopath: /Users/***/go
GOROOT: /usr/local/Cellar/go/1.13.4/libexec
PATH: /opt/apache-maven-3.6.3/bin:/usr/local/opt/openjdk@8/bin:/usr/local/opt/node@12/bin:/usr/local/opt/node@10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/***/go/bin

   gopkgs: /Users/***/go/bin/gopkgs installed
   go-outline: /Users/***/go/bin/go-outline installed
   gotests: gotests not installed
   gomodifytags: gomodifytags not installed
   impl: impl not installed
   goplay: goplay not installed
   dlv: /Users/***/go/bin/dlv installed
   dlv-dap: dlv-dap not installed
   staticcheck: staticcheck not installed
   gopls: /Users/***/go/bin/gopls installed

go env
Workspace Folder (adrive-file-service): /Users/***/***
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN="/Users/***/go/bin"
	GOCACHE="/Users/***/Library/Caches/go-build"
	GOENV="/Users/***/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GONOPROXY="***/*"
	GONOSUMDB="***/*"
	GOOS="darwin"
	GOPATH="/Users/***/go"
	GOPRIVATE="***/*"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/***/ali/adrive-file-service/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3r/dyp1yprj4hlc0vzps806h77w0000gn/T/go-build139277190=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
"go.useLanguageServer": true,
    "go.toolsGopath": "/Users/jiangzejia/go",
    "go.alternateTools": {
      "go-langserver": "gopls"
    },
    "go.languageServerExperimentalFeatures": {
      "format": true,
      "autoComplete": true,
      "goToDefinition": true,
      "hover": true,
      "signatureHelp": true,
      "goToTypeDefinition": true
    },
    "gopls": {
      "usePlaceholders": true,
      "completeUnimported": true,
      "deepCompletion": true,
    },
    "go.buildOnSave": "off",
    "go.vetOnSave": "off",
    "[go]": {
      "editor.snippetSuggestions": "none",
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      },
    },

### Describe the bug
After some updates, my go.mod file , the module name line hint an error:

`err: exit status 1: stderr: go: updates to go.mod needed, disabled by -mod=readonly
: packages.Load errorgo list`

I have no idea about how it occured, I didn't change any setting except vscode auto update some extensions and itself

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/20549450/115179405-d6778e80-a105-11eb-9f74-75606dc88451.png)

**Comment by findleyr** [comment]
Hi, thanks for the report.

This error means your go.mod file is not tidy.  Gopls behavior was changed to not modify the `go.mod` file unless explicitly requested by the user (via a code lens, for example). In go 1.16, this is the default behavior of the Go command as well.

Can you ensure that your project builds, and that your go.mod file is tidy? See also 
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#make-sure-your-project-compiles

**Comment by PseudoCowboy** [comment]
I will check it out. Thanks.
