### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by zhangpanpan01** [golang/vscode-go#1438]
gopls version: v0.5.3
gopls flags: 
update flags: proxy
extension version: 0.24.1
go version: 1.15.11
environment: iCoding linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by zhangpanpan01** [comment]
An error is still reported after updating the version

**Comment by findleyr** [comment]
> An error is still reported after updating the version

The error you report is a known breakage for older versions of gopls: see also #1328.  Are you sure you have updated gopls? You can see where gopls is installed by running [Go: Locate Configured Go Tools](https://github.com/golang/vscode-go/blob/master/docs/commands.md#go-locate-configured-go-tools), and then running `gopls -v version`.

**Comment by hyangah** [comment]
Closing. @zhangpanpan01 Please open a new issue if you still experience the same issue even after updating gopls to the latest version 0.6.10.
