### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by inferne** [golang/vscode-go#1442]
gopls version: v0.5.3
gopls flags: 
update flags: proxy
extension version: 0.24.1
go version: 1.14.6
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 2

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, this is a known compatibility problem with older versions of gopls on recent versions of the extension (#1328). You can update your gopls tool as described in the [troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#update-tools).
