### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by fringe-wb** [golang/vscode-go#1443]
gopls version: v0.6.10
gopls flags: 
update flags: proxy
extension version: 0.24.1
go version: 1.15.6
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, this is a known issue with older versions of gopls (#1300). Are you sure you're using gopls v0.6.10?  You can see where gopls is installed by running [Go: Locate Configured Go Tools](https://github.com/golang/vscode-go/blob/master/docs/commands.md#go-locate-configured-go-tools), and then running gopls -v version.

**Comment by zcqzcg** [comment]
I am in the same satiation here;
By the way, it's `gopls version` to get version, which on my deepin is 
```sh
gopls version                                                                                                                                                                                   2 ↵
golang.org/x/tools/gopls v0.6.5
    golang.org/x/tools/gopls@v0.6.5 h1:kLt9rD/dWtVdvc8LmdcxagDFih6zxYXREpKSYYZu5KE=
```
VsCode is the latest version of linux, I am currently on Deepin 20.2

**Comment by findleyr** [comment]
@zcqzcg you need at least gopls v0.6.6 -- see also #1300.  Did you get a prompt to update?

Any any case, you can update gopls via [these instructions](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#update-tools), or manually with the `go` command.

**Comment by hyangah** [comment]
Closing. @fringe-wb and @zcqzcg Please update the gopls to the latest version. Thanks!
