### ISSUE TITLE
debug: Fails when Delve returns an empty file location

### ISSUE THREAD

**Issue by JadenSimon** [golang/vscode-go#1447]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.16.3 darwin/amd64
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.55.2
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.24.2 but this bug happens on the latest commit too

### Share the Go related settings you have added/edited
All settings are default

### Describe the bug
I'm running Delve in headless exec mode in a container. Binary + Delve are cross-compiled for linux/amd64 without optimization. Using the legacy adapter.

The debug client will send a `StackTraceRequest` to the Delve server. Delve responds correctly except for two functions:
`runtime.call64` and `runtime.call1024`. These appear to be entry points for the Go runtime itself. Delve is unable to properly extract information about these two functions, returning blank file locations (Delve returns a file name for Go1.14 but not Go1.15 or Go1.16). The Go extension does not handle this gracefully, and instead will throw an exception in `inferLocalPathFromRemotePath` (the actual error is caused by glob.sync). 

#### Suggestion:
If Delve returns an invalid path, treat the source as an unknown instead of failing. A message should also be logged so the Delve team can be notified.

I have a quick-fix for this bug by immediately returning in `inferLocalPathFromRemotePath` if the path is empty, but I'm sure there is a better solution.

### Steps to reproduce the behavior:
Difficult to reproduce since it's dependent on the binary used. My executable also requires a specific set of steps to hit the desired breakpoints.

### Logs
An example of the file location being blank (StackTraceRequest):
``{"pc":4627612,"file":"","line":0,"function":{"name":"runtime.call1024","value":4627520,"type":0,"goType":0,"optimized":true},"Locals":[],"Arguments":[],"FrameOffset":-2280,"FramePointerOffset":-2296,"Defers":[],"Err":""}``

This is when the binary compiled with Go1.14.15:
``{"pc":4589589,"file":"/usr/local/go/src/runtime/asm_amd64.s","line":1,"function":{"name":"runtime.call1024","value":4589504,"type":0,"goType":0,"optimized":true},"Locals":[],"Arguments":[],"FrameOffset":-2328,"FramePointerOffset":-2344,"Defers":[],"Err":""}``

The empty file location is caused by a bug with Delve (https://github.com/go-delve/delve/issues/2442) but it's likely they won't fix it.

**Comment by suzmue** [comment]
Thanks for filing this issue! If you would like to send a PR with your fix I would be happy to review it.
