### ISSUE TITLE
debug: cannot view variable's complete content

### ISSUE THREAD

**Issue by Zuckjet** [golang/vscode-go#1451]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16 darwin/amd64
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.55.0
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.24.2

### Describe the bug
When debug go program, I set a breakpoint in order to view the variable content,  when variable content is long , it will just show part of it, and I cannot view it's complete content.

I hope when I click **more**, it will show the complete content, or any other solution can do this.

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/17976139/115808628-6296f800-a41d-11eb-84d0-22bf1252be3a.png)

**Comment by hyangah** [comment]
@Zuckjet Try to set `maxStringLen` https://github.com/golang/vscode-go/blob/master/docs/debugging.md#configuration for now. This is a temporary solution, and we are looking into a better way to handle this with a [new debug adapter](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md) in the context of https://github.com/golang/vscode-go/issues/1318

**Comment by Zuckjet** [comment]
> @Zuckjet Try to set `maxStringLen` https://github.com/golang/vscode-go/blob/master/docs/debugging.md#configuration for now. This is a temporary solution, and we are looking into a better way to handle this with a [new debug adapter](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md) in the context of #1318

Thanks, it works now by setting `maxStringLen `. It up to you whether or not to close this issue.

**Comment by hyangah** [comment]
Thanks for updating the issue. Yes, let's keep track of this underlying issue in #1318.
