### ISSUE TITLE
enhance auto-importing error message for fmt

### ISSUE THREAD

**Issue by szheng67** [golang/vscode-go#1453]
when there's a typo in the method call such as in `fmt.Prinln("hello world")`, the editor shows error `undefined: fmt`. This error seems to imply that it's unable to find `fmt` package.  It would be better if it auto-imports the fmt package and indicate that fmt.Prinln is undefined instead.

**Comment by hyangah** [comment]
@szheng67 Did you enable the language server (gopls)? If so, can you please share the `gopls` and the `go` versions?

I see "undeclared name" error coming from the compiler when using gopls.

![Screen Shot 2021-04-27 at 6 12 17 PM](https://user-images.githubusercontent.com/4999471/116319239-2a2c4c80-a784-11eb-898d-465a59d8ff9c.png)

Given that `fmt` can refer to a variable or type or package name other than the standard 'fmt' package, I am not sure if auto-importing fmt with this incomplete info is the right thing to do.

**Comment by findleyr** [comment]
Hi, if the algorithm is "whenever we have an undeclared name in a selector that is a known package name, auto-import that package", then I think there are some UX issues:
 - I don't think there's any other place where gopls just sends text edits without some action from the user. Running a code action, executing a refactoring command, or selecting a completion are all user-initiated actions. I'd be concerned about the precedent of automatically editing the buffer.
 - If we were to introduce an automatic edit, there's the problem that not every package name is as obviously a missing import as "fmt". Consider "path", "token", "format", or "color", to name a few. I think there's a high likelihood that this automatic edit _does the wrong thing_ for some users. For an automatic edit, the false positive rate should be extremely low.

I also don't think the problem being solved is significant enough to warrant the complexity of the solution above.

**Comment by stamblerre** [comment]
Thanks for the detailed analysis, @findleyr! I agree with your conclusion that this really only works in scenarios like `"fmt"`, and we shouldn't add special handling for these cases. Let's close this as a result.
