### ISSUE TITLE
all: cleanup use of `go.goroot`

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#146]
`go.goroot` is currently used to ["specify the GOROOT to use when no environment variable is set."](https://github.com/golang/vscode-go/blob/master/package.json#L885-L892). If not set, the go extension picks the `go` from the one in $PATH. As long as the right `go` can be picked from `PATH`, this is unnecessary. But usability wise, this is probably better than configuring `PATH`, and easily accessible for users who come from other languages where the SDK path has to be set explicitly.

When `go.goroot` is set, this extension currently tries to
  1) set the `GOROOT` environment variable to the value (see [code](https://github.com/golang/vscode-go/blob/master/src/goInstallTools.ts#L339-L341)) , 
  2) pick the `go` binary from the `GOROOT/bin` path (see [code](https://github.com/golang/vscode-go/blob/master/src/goPath.ts#L61-L66))
  3) prepend the go runtime path to `PATH` (see [code](https://github.com/golang/vscode-go/blob/master/src/goInstallTools.ts#L365-L373)) so that any tools that invoke `go` and associated go tools (e.g. `gopls`, `dlv`, ... ) use the same set of go tools.

In modern Go, users are never supposed to set `GOROOT`. Once the right `go` command is chosen, the `go` command will pick the right `GOROOT`. Manually and silently setting `GOROOT` causes confusion and problems hard to debug.

We **should stop setting the `GOROOT` env var**. In this clean up project:

* Stop setting and using `GOROOT` env var in the extension.
* Force the right `go` is chosen by setting the `PATH` for underlying tool execution, and ensuring the underlying tools to pick up the change if `go.goroot` is changed. (Or restart)
* Make the chosen Go SDK visible through the UI.
* (stretch goal) apply the `PATH` change to the integrated terminal, so users use the same `go` command when manually launching the command or inspecting the env variables from the  integrated terminal. (https://github.com/microsoft/vscode-go/issues/3201)
* Document and use it to standardize the standard library and the go development setup   (https://github.com/golang/vscode-go/issues/26).

**Comment by stamblerre** [comment]
Just wanted to add a note that we should also consider how to operate smoothly with version managers (see https://github.com/microsoft/vscode-go/issues/3087), or at least add documentation for them.

**Comment by hyangah** [comment]
@mcjcloud implemented features necessary for MVP, and we are now polishing and bug fixing. So, I will close this issue.
Documentation improvement will be tracked in #26 separately.

**Comment by segevfiner** [comment]
Looks like the apply `PATH` changes to the terminal bit wasn't done? Should this one receive a new separate issue? (Newer VS Code has API for this: `ctx.environmentVariableCollection` I think, not sure if/what other extensions are using it ATM)

**Comment by hyangah** [comment]
@segevfiner thanks for the pointer. We've been sending the PATH modification command to the terminal for some known shells. `ctx.environmentVariableCollection` seems useful. Relayed it to https://github.com/golang/vscode-go/issues/378.
