### ISSUE TITLE
debug: allow to configure `substitutePath` for debug test codelens and symlinks

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1467]
Users who work in symlinked workspace need to use `substitutePath` (introduced as a fix for https://github.com/golang/vscode-go/issues/622) because VSCode may use the symlinked path 
while the Go command and Delve would use the original path.

This solution is not available for debug sessions started with the debug test codelens or
the debug session that started with a default configuration without launch.json (see https://github.com/golang/vscode-go/issues/855)

A couple of options:

* allow users to configure the default `substitutePath` settings (e.g. [go.delveConfig](https://github.com/golang/vscode-go/blob/master/docs/settings.md#godelveconfig) ) in `settings.json`
* try to detect this symlink case and auto-populate `substitutePath` automatically.
* when this case is detected, the extension pops up a message to ask the user to configure the setting (or even update the settings value on behalf of the users).

**Comment by hyangah** [comment]
Since v0.26.0, `substitutePath` can be set using `go.delveConfig`  in settings.json. 
@suzmue Do you want to keep looking into this problem (e.g. auto-generate `substitutePath` mapping, or provide a way for users to inspect the file path info embedded in the debugged binary and configure the mappings on the fly, ...)? I think it's ok to close this issue, and open separate issues to investigate alternative options to improve UX. What do you think?

**Comment by suzmue** [comment]
Closing this since this particular issue is resolved. We can open separate issues for follow up features.
