### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by damarbds** [golang/vscode-go#1486]
gopls version: v0.6.11
gopls flags: 
update flags: proxy
extension version: 0.24.2
go version: 1.14.7
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: illegal file offset

goroutine 49 [running]:
go/token.(*File).Pos(...)
	  position.go:267
golang.org/x/tools/internal/lsp/source/completion.packageCompletionSurrounding(0xc00012bcc0, 0xe3a140, 0xc005503260, 0xc002092240, 0x924aee, 0x19, 0x36, 0x18b)
	  package.go:85  0xf62
golang.org/x/tools/internal/lsp/source/completion.packageClauseCompletions(0xe36b40, 0xc0024e20f0, 0xe4af40, 0xc00126c540, 0xe3a140, 0xc005503260, 0x3500000018, 0x0, 0x0, 0x0, ...)
	  package.go:46  0x1f9
golang.org/x/tools/internal/lsp/source/completion.Completion(0xe36b40, 0xc0024e20f0, 0xe4af40, 0xc00126c540, 0xe3a140, 0xc005503260, 0x3500000018, 0x3ff0000000000000, 0x0, 0x0, ...)
	  completion.go:442  0x209
golang.org/x/tools/internal/lsp.(*Server).completion(0xc0000d2460, 0xe36a80, 0xc000154c00, 0xc005825d60, 0x0, 0x0, 0x0)
	  completion.go:31  0xdfe
golang.org/x/tools/internal/lsp.(*Server).Completion(0xc0000d2460, 0xe36a80, 0xc000154c00, 0xc005825d60, 0xc005825d60, 0x0, 0x0)
	  server_gen.go:32  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xe36a80, 0xc000154c00, 0xe51100, 0xc0000d2460, 0xc0037d7d70, 0xe36d40, 0xc000154b80, 0x0, 0x0, 0xe27860)
	  tsserver.go:358  0x2462
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xe36a80, 0xc000154c00, 0xc0037d7d70, 0xe36d40, 0xc000154b80, 0x0, 0x0)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xe36a80, 0xc000154c00, 0xc0037d7d70, 0xe36d40, 0xc000154b80, 0x0, 0x0)
	  lsprpc.go:660  0x43b
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xe36a80, 0xc000154c00, 0xc000404f40, 0xe36d40, 0xc000154b80, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0001427e0, 0xc00041f920, 0xc00006fe60, 0xe36a80, 0xc000154c00, 0xc000404f40, 0xe36d40, 0xc000154b80)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 11:45:19 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. I'm not yet sure how this could occur, but it is certainly a bug.

Do you recall exactly what you were typing when the crash occurred?  I assume you were typing `package ...` in a new file, but I'm not sure how that would lead to this crash.

In any case, I'll fix this particular crash.

**Comment by findleyr** [comment]
Closing, as I think the CL above should fix the bug. This fix should be included in the next release.
