### ISSUE TITLE
debug: "unable to display threads: detached from the process"

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#149]
Transferring this issue from https://github.com/microsoft/vscode-go/issues/3104 - see the repro case provided in https://github.com/microsoft/vscode-go/issues/3104#issuecomment-617515787. 

/cc @polinasok

**Comment by segevfiner** [comment]
I'm seeing this pretty consistently whenever I restart or stop debugging.

macOS 10.14.6
Go 1.14.5
Delve 1.4.1
VS Code 1.47.2
vscode-go 0.15.1

**Comment by polinasok** [comment]
I think this is caused by the same flaw in the logic that causes #172. We need to fix continue logic not to always assume that execution was stopped on a breakpoint.

**Comment by suzmue** [comment]
This bug does not appear in the dlv dap DA and we do not plan to fix this in the legacy adapter.
