### ISSUE TITLE
Attached debugging using Delve is not showing code at breakpoints in VSCode

### ISSUE THREAD

**Issue by SGarno** [golang/vscode-go#1490]
I am attempting to debug a go application that is compiled and bundled prior to running the debugger. This is done using the command line:

```guark build -rm && dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec dist\windows\Demo.exe```

Delve starts up just fine, VSCode connects to Delve and issues the proper API commands, but it doesn't display the code when the breakpoint is hit. I can see from the Delve logs, that it is transmitting the breakpoint to VSCode, and VSCode is displaying the stacktrace, but it does not display the source code.

Attached is a Delve [log](https://github.com/golang/vscode-go/files/6453314/vscode-go-debug.txt) and a [screenshot](https://user-images.githubusercontent.com/8698262/117687061-a2c3dd80-b174-11eb-8025-f686554285ab.png) of VSCode during a breakpoint

From the [log](https://github.com/golang/vscode-go/files/6453314/vscode-go-debug.txt) you can see:

At [14:01:24.729 UTC] the brekpoints were verified
At [14:01:50.444 UTC] the breakpoint was triggered
At [14:01:50.471 UTC] Delve replied with location of breakpoint
At [14:01:50.479 UTC] VSCode requested a stack trace

From the  [screenshot](https://user-images.githubusercontent.com/8698262/117687061-a2c3dd80-b174-11eb-8025-f686554285ab.png), you can see that the callstack is populated and showing where it is paused, however, the editor doesn't reflect the breakpoint in the code. It remains where it was initiated at (in this case launch.json).

**Comment by suzmue** [comment]
Thanks for the detailed report! From the log it looks like the stackTrace response was never sent to VSCode, which is why its not showing up. It appears to only be showing the result of the threadsResponse (to confirm this you can try expand any of the goroutines in the call stack panel).

Since the locations were logged, but no response was sent I suspect the issue to be from initializeRemotePackagesAndSources not resolving:
```
if (this.delve.isRemoteDebugging) {
	await this.initializeRemotePackagesAndSources();
}
```

**Comment by SGarno** [comment]
Thanks for the quick reply.    Oh!   I thought it did respond back with [14:01:50.498 UTC] locations [...].    I guess that was internal logging not what got sent back to VSCode.   

Please let me know if there is anything else I can do to help track this down.

**Comment by lpflpf** [comment]
I have the same problem，upgrade remote server dlv version (1.1.0 ->  1.6.0), and it's not appear again.

**Comment by SGarno** [comment]
> Could you give this a try with the new debug adapter, `dlv dap`?
> 
> ```
> {
>     "name": "Launch executable",
>     "type": "go",
>     "request": "launch",
>     "mode": "exec",
>     "program": "dist\windows\Demo.exe",
>     "debugAdapter": "dlv-dap"
> }
> ```
> 
> If you still want to start the `dlv` outside of vscode you can run:
> `$ dlv dap --listen=:2345`
> 
> ```
> {
>     "name": "Launch executable",
>     "type": "go",
>     "request": "launch",
>     "mode": "exec",
>     "program": "dist\windows\Demo.exe",
>     "debugAdapter": "dlv-dap",
>     "port": 2345
> }
> ```
> 
> `--accept-multiclient` is not yet supported with `dlv dap`. Is the multiclient support important to your workflow?

Suzy,   

Thanks for the suggestions.   I kind of have it working, but VSCode is giving me fits in that it doesn't seem to handle multiple tasks properly.     In order for me to debug this, I have to run a cli build step.   It generates the executable. 

If I start up delve dap in a separate command line window and then run the debugger with the build step in the tasks.json, it seems to work fine.

However, if I try to create a tasks.json with multiple steps, one to build the exe and the other to run delve dap, VSCode just hangs and won't start up the debugger.    Any thoughts on this?    I have tried both sequential and parallel, no luck.

Here are my launch and tasks.json files


### Launch.json 
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "exec",
            "port": 2345,
            "preLaunchTask": "Debug_Build",
            "program": "dist\\windows\\GuarkDemo.exe",
            "debugAdapter": "dlv-dap",
            "showLog": true,
            "apiVersion": 2,
            "trace": "verbose"
        }
    ]
}
```

### Tasks.json
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Debug_Build",
            "dependsOn": [
                "GuarkBuild",
                "DAPDebug"
            ]
        },
        {
            "label": "GuarkBuild",
            "type": "shell",
            "isBackground": false,
            "command": "guark build --rm",
            "problemMatcher": "$go"
        },
        {
            "label": "DAPDebug",
            "type": "shell",
            "isBackground": true,
            "command": "dlv dap --listen=:2345",
        }
    ]
}
```

**Comment by SGarno** [comment]
> I have the same problem，upgrade remote server dlv version (1.1.0 -> 1.6.0), and it's not appear again.

I am already using 1.6.0

**Comment by SGarno** [comment]
I have been playing around with the delve dap adapter and I am not sure that it is working 100% with this configuration.    I keep getting empty OP Stack issues on variables.   Also, breakpoints don't show up as being there in VSCode and the path in the breakpoint is listed as /.      

Is the dap adapter fully functional or is there something with the way this configuration is setup to cause misalignment issues?

![image](https://user-images.githubusercontent.com/8698262/118149901-3b559a00-b3cf-11eb-87c9-18f90562dfb5.png)

**Comment by hyangah** [comment]
@SGarno Thanks for the report and the screenshot. Was the binary built with `-gcflags="all=-N -l"`? And what is the go version?

**Comment by SGarno** [comment]
Yes, it was built with `gcflags: "all=-N -l"`.    I am using go version go1.16.3 windows/amd64

**Comment by hyangah** [comment]
@SGarno Sorry for this delayed response. @polinasok noticed that the info in BREAKPOINTS was a bug fixed long ago (https://github.com/golang/vscode-go/issues/1212), and it's likely that you need a newer version of `delve` to use DAP.  

Please update the delve with the following command that builds delve from the master.

```
$ go install github.com/go-delve/delve@master
```

And, delve built on master has a feature that shows warning about optimized binaries/functions. (see https://github.com/go-delve/delve/pull/2475) so you can check whether the function is compiled in a way that's suitable for debugging.
