### ISSUE TITLE
Optional gosec linting support, 

### ISSUE THREAD

**Issue by Merith-TK** [golang/vscode-go#1491]
**Describe the solution you'd like**

Gosec to be added to the toolset and enabled by a optional setting, which would allow linting highlights and allow making things easier

**Comment by Merith-TK** [comment]
No it doesnt please look into what `gosec` actually is.
https://github.com/securego/gosec

Go sec is a tool to help view the security of your code,

**Comment by findleyr** [comment]
I know what gosec is. The golangci-lint documentation indicates that it is available, and can be enabled with a flag:
https://golangci-lint.run/usage/linters#disabled-by-default-linters--e--enable

Here's an example of how to configure golangci-lint for vscode:
https://github.com/golang/vscode-go/blob/master/docs/tools.md#examples
