### ISSUE TITLE
Auto-import not work

### ISSUE THREAD

**Issue by avelinobego** [golang/vscode-go#1495]
Issue Type: <b>Bug</b>

Auto-import not work.
VSCode can't auto-import package from my project.
I am using go mod in my project.

Extension version: 0.24.2
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (22.17GB free)|
|Process Argv|--crash-reporter-id e1a9fdc5-ba11-4f07-8ffe-8d777452e576|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscorecescf:30290706
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30294352
bridgeflight:30299254

```

</details>

**Comment by findleyr** [comment]
Hi, when reporting issues please follow the guidance in the [issue template](https://github.com/golang/vscode-go/issues/new?assignees=&labels=&template=bug_report.md&title=), specifically:

* Please share your go version, gopls version, and other configured tools.
* Please provide a concise but specific description of the bug: what did you do, what did you expect to happen, what actually happened.

Thanks

**Comment by findleyr** [comment]
Closing as we don't have enough information to diagnose this. Please re-open if you're able to provide more information.
