### ISSUE TITLE
Path Separator choice for substitutePath

### ISSUE THREAD

**Issue by yalcinmelihyasin** [golang/vscode-go#1497]
Recently `substitutePath` added to support relative paths which is really helpful but I am having an issue with path separators.

For:

```
"substitutePath": [
  {
    "from": "foo/bar/",
    "to": "",
  },
]
```

`foo/bar/morefoo/morebar/foobar.go` converts to `morefoo\morebar\foobar.go` 

This does not work on MacOS and I suspect it would not work on Linux either. 

I have tried to put the `"substitutePath"` under `"osx"` parent but it did not change the behaviour. It would be great if the path separator that is used after substitution is the same with the path separator that user provided(and/or based on OS)

This was happening with `remotePath` and `cwd` setting before and I have mentioned here* in the old repository and has been solved later.

https://github.com/microsoft/vscode-go/issues/3011

**Comment by suzmue** [comment]
Thanks for filing this issue! I agree that it makes more sense to default to `/` instead of `\` if there is no path separator in the `"to"` field to choose from. delve is pretty tolerant of accepting both `\` and `/` on windows as well so this should not cause issues on windows either.

**Comment by yalcinmelihyasin** [comment]
Thanks for the very quick response and fix!
