### ISSUE TITLE
gopls: crash while parsing non-go files?

### ISSUE THREAD

**Issue by OneOfOne** [golang/vscode-go#1498]
gopls version: (devel)
gopls flags: 
update flags: off
extension version: 0.25.0-dev
go version: devel go1.17-9995c6b50a
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 1
total start count: 2

I opened an empty file (vscode auto sets the file type to whatever the previous file was), and it wasn't go so gopls crashed?

goroutine 4502 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	  uri.go:32
golang.org/x/tools/internal/lsp.(*Server).computeSemanticTokens(0xc0001fe2a0, {0xe479f8, 0xc006f92580}, {{0xc00ccf69a8, 0x79}}, 0xc00e81b150)
	  semantic.go:52  0xad6
golang.org/x/tools/internal/lsp.(*Server).semanticTokensRange(...)
	  semantic.go:39
golang.org/x/tools/internal/lsp.(*Server).SemanticTokensRange(0xc001acf080, {0xe479f8, 0xc006f92580}, 0xbc4bc0)
	  server_gen.go:220  0x31
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0xe479f8, 0xc006f92580}, {0xe730e0, 0xc0001fe2a0}, 0xc00e824540, {0xe47c60, 0xc006f92500})
	  tsserver.go:288  0x4c3d
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0xe479f8, 0xc006f92580}, 0xc00e824540, {0xe47c60, 0xc006f92500})
	  protocol.go:63  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0xe479f8, 0xc006f92580}, 0xc00e824540, {0xe47c60, 0xc006f92500})
	  lsprpc.go:660  0xa7d
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0xe479f8, 0xc006f92580}, 0xc009ae2198, {0xe47c60, 0xc006f92500})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20f
[Error - 2:01:00 PM] </pre>

**Comment by findleyr** [comment]
Indeed. Thank you for reporting.

**Comment by findleyr** [comment]
Do you happen to have the panic message as well?
