### ISSUE TITLE
"'${workspaceFolder}' can not be resolved in a multi folder workspace" although ${workspaceFolder} is not used

### ISSUE THREAD

**Issue by plaili** [golang/vscode-go#1499]
Used SW:
Version: 1.57.0-insider
Commit: 659175fa39b994fc39381b0af2874c85efeb2a01
Date: 2021-05-13T05:12:05.031Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.4.0

Go for VSCode v0.25 (works fine when going back to v0.24.2)

Launching this remote debug configuration always fails:

			{
				"name": "Connect to content",
				"type": "go",
				"request": "attach",
				"mode": "remote",
				"port": 59136,
				"host": "127.0.0.1"
			}

Message is:
<code>'${workspaceFolder}' can not be resolved in a multi folder workspace<code>

**Comment by suzmue** [comment]
Thanks for the report!  We set the `cwd` to `"${workspaceFolder}"` by default if it is not specified in the `attach` configuration.

In v0.25.0 we switched to not resolving the home directory ourselves, and letting vscode do this (golang/vscode-go#1448).

Would you mind setting `"cwd": "${fileWorkspaceFolder}`? If that works for you, I think that in a multi folder workspace we could use that as a default instead.

**Comment by plaili** [comment]
> Would you mind setting `"cwd": "${fileWorkspaceFolder}`? If that works for you, I think that in a multi folder workspace we could use that as a default instead.

Yes, it works.

**Comment by suzmue** [comment]
I will make the change to use `"${fileWorkspaceFolder}"` by default if there are multiple workspace folders.

Another way to specify the specific workspace folder you want to run the remote attach in is to set:
`"cwd": "${workspaceFolder:folderName}"`
 
This will run it in the workspace folder specified by folder name.
