### ISSUE TITLE
tools: warn users if go.goroot is configured - it mutates GOROOT env var

### ISSUE THREAD

**Issue by TheJonRobinson** [golang/vscode-go#1501]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.13.4 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- command not found: gopls
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.56.1 e713fe9b05fc24facbec8f34fb1017133858842b x64
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.25.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: undefined
GOROOT: /usr/local/go/bin/go
PATH: /Users/jonrobinson/google-cloud-sdk/bin://bin:/Users/jonrobinson/.nvm/versions/node/v12.16.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin

failed to run "/usr/local/go/bin/go version": Error: Command failed: /usr/local/go/bin/go version
go: cannot find GOROOT directory: /usr/local/go/bin/go
 cwd: /Volumes/Development/game-pizzarush
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
    "go.formatTool": "goimports",
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "go.useLanguageServer": true,
    "go.toolsManagement.autoUpdate": true,
```

### Describe the bug

> A clear and concise description of what the bug.

We have been happily using 0.24.2 on the extension, but after the update happened to 0.25.0, we get the following pop-up when opening the VS-Code project:
```
Failed to run '/usr/local/go/bin/go env. The config change may not be applied correctly.
Source: Go (Extension)
```
Also, in the OUTPUT window:
```
Failed to run '/usr/local/go/bin/go env' (cwd: /Volumes/Development/game-pizzarush): Error: Command failed: /usr/local/go/bin/go env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE
go: cannot find GOROOT directory: /usr/local/go/bin/go

go: cannot find GOROOT directory: /usr/local/go/bin/go
```

After this, gopls is not present/working and the go environment seems somewhat broken.

NB If we revert the extension back to the previous one, the problems go away.

> A clear and concise description of what you expected to happen.

We'd expect the behaviour to remain as before the 0.25.0 update.

### Steps to reproduce the behavior:
1. After the Go extension has updated to 0.25.0
2. Open the workspace in VS-Code
3. See error

**Comment by hyangah** [comment]
Thanks for the report @TheJonRobinson 
It's probably related to [the commit](https://github.com/golang/vscode-go/commit/4e3fc58f6828721d32cf816d1efe6a69566c54c9#diff-d8aee10392e1f68e1b6b8f758ed36644727a008fbebc7ca31178f71ef2ccad63R157) but I thought that should change behavior only if `go.goroot` setting is used. It doesn't seem like you are using it though. Is the workspace setting empty?
(`Preferences: Open Workspace Settings (JSON)`)

**Comment by bestbeforetoday** [comment]
I also started seeing this issue with the update to v0.25.0 of the Go extension. I checked my VS Code settings and there was a `go.goroot` entry there. This isn't something I recall ever setting, and isn't something that was causing an issue before. Removing the `go.goroot` entry in my VS Code settings seems to have resolved the startup error.

**Comment by TheJonRobinson** [comment]
Ah - so yes, our project does have a workspace, which does indeed set `go.goroot` - I missed that because I just used thePreferences: Open Settings (JSON)which doesn’t include those.

Removing the setting altogether resolves the problem though, as I just noticed @bestbeforetoday commented. Similarly, that setting has been there since I created the project, and I can’t remember whether it was automagically set or I did but it certainly was benign before 0.25.0

**Comment by hyangah** [comment]
Long story - For many years `go.goroot` was used to set the `GOROOT` environment variable. Setting `GOROOT` environment variable is no longer recommended and in fact, probably against the best practice. Modern versions of Go find the right `GOROOT` by themselves when `GOROOT` isn't set. So, we cleaned up its behavior as part of https://github.com/golang/vscode-go/issues/146 and made that not to set `GOROOT` environment variable any more.

Unfortunately, there are still some popular version management tools that were written long ago and somehow depends on setting `GOROOT` environment variable to operate correctly. And there were users who want to unset/override GOROOT environment variable set in their environment. We received multiple requests to bring back the old behavior (https://github.com/golang/vscode-go/issues/776 for example). We considered completely deprecating `go.goroot` and  recommending users to use `go.toolsEnvVars` when they need to modify with the go's environment variables. But there was usability & security implication. So, instead we brought back `go.goroot`'s old behavior.

Most users shouldn't set `go.goroot` setting at all.

We can add extra warnings when `go.goroot` setting is detected.

**Comment by joelft** [comment]
Just for the sake of thoroughness, make sure to also check WSL settings if using VS Code Remote to program in WSL. 

In my case, that's where the stale go.root setting was located.
