### ISSUE TITLE
debug: output the build errors in debug console (dlv-dap)

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1502]
When the target program fails to build, dlv-dap reports the build error messages using the error response currently.

https://github.com/go-delve/delve/blob/master/service/dap/server.go#L729-L734

Instead, report them as output events (stderr maybe) so the build error logs can be more easily accessible.

**Comment by polinasok** [comment]
+1 The error response details show up in a small pop-up, centered, which is not very readable for build errors.
![image](https://user-images.githubusercontent.com/51177946/118231553-2ebf5900-b444-11eb-8972-5a6afc40b39b.png)
The old adapter printed "Check the debug console for details" and logged to console instead.

**Comment by polinasok** [comment]
Btw, the original issue that resulted in adding these details to the pop-up is still open https://github.com/golang/vscode-go/issues/1425 - I guess we could have had this discussion there.

**Comment by hyangah** [comment]
Good finding. I will close this issue in favor of #1425.
