### ISSUE TITLE
debug: inspect contents of field using hover

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#1510]
From an issue filed in delve (go-delve/delve#2491)

> Please answer the following before submitting your issue:
> 
> What version of Delve are you using (dlv version)? 1.6.0
> What version of Go are you using? (go version)? 1.15.5
> What operating system and processor architecture are you using? MacOS Catalina, 64bit
> What did you do? Hover over a field of a struct. i.e. attempt to inspect the contents of field b when code is a.b
> What did you expect to see? The value of b
> What did you see instead? nothing
>
> This behavior has been something I've lived with for years and never found an answer online nor did colleagues know how to get it to work. I don't want to have to use the debug side panel or hover over a and expand the contents to then find the field's value. I expect to be able to hover over any field regardless of depth to see it's contents.
> 
> Apparently Goland offers this feature but I don't want to move away from VS Code
>

**Comment by hyangah** [comment]
@suzmue Should we close this? Or do. you want to keep this until we update dlv-dap min version to include the fix?

**Comment by hyangah** [comment]
The upstream bug is closed and this feature works with the latest dlv-dap built at master. Closing. Thanks @suzmue !
