### ISSUE TITLE
Support folding regions for block comment

### ISSUE THREAD

**Issue by jsoref** [golang/vscode-go#1511]
**Is your feature request related to a problem? Please describe.**

I want to be able to comment out large portions of tests and then collapse them.

I tried the obvious (select a region and cmd+/), but that doesn't work:
https://github.com/microsoft/vscode/issues/124104#issuecomment-843452790

**Describe the solution you'd like**
either cmd-/ + folding works, or toggle block comment + folding works

**Describe alternatives you've considered**
I filed https://github.com/microsoft/vscode/issues/124104

**Additional context**
![image](https://user-images.githubusercontent.com/2119212/118651096-2dc75800-b7b3-11eb-9fb6-5277a730c9b2.png)
![image](https://user-images.githubusercontent.com/2119212/118651129-361f9300-b7b3-11eb-9906-bc86aa7e3282.png)
![image](https://user-images.githubusercontent.com/2119212/118651176-4172be80-b7b3-11eb-99be-a66f2ed68dd3.png)

**Comment by stamblerre** [comment]
Thanks for reporting this issue. This would be implemented in `gopls` so I've filed https://github.com/golang/go/issues/46253. Please follow along with that issue, but I'll leave this one open for tracking purposes.

**Comment by stamblerre** [comment]
Upstream issue has been resolved (https://github.com/golang/go/issues/46253).

**Comment by suzmue** [comment]
@jsoref Following up on this, there is also a way to toggle block comments in VS Code. This will use `/*` ... `*/`  instead of individually commenting out each line. Hope this helps!

<img width="609" alt="Screen Shot 2021-06-04 at 6 40 02 PM" src="https://user-images.githubusercontent.com/6634754/120869357-47fb8700-c564-11eb-9b3a-2c2b961e7c02.png">

**Comment by suzmue** [comment]
Reopening to track updates for folding ranges for block comments.
