### ISSUE TITLE
wrong warning: undeclared name

### ISSUE THREAD

**Issue by istanggsh** [golang/vscode-go#1513]
I have two go file, both are in main package. One is `user.go`, it defines `type User struct`, and other is `server.go`, it defines `type Server struct`. 
When I user `User` in `server.go` or use `Server` in `user.go`, the plugin **SOMETIMES** will report warning--`undeclared name`, but when I `go build -o server main.go server.go user.go`, it succeeded. 
- the file `server.go` with the warning
![1](https://user-images.githubusercontent.com/65331757/118781306-81bf6300-b8bf-11eb-98ab-b197d2ea6bcc.png)
- the file `user.go`
![3](https://user-images.githubusercontent.com/65331757/118781355-8e43bb80-b8bf-11eb-95b0-b4d42b0a5855.png)

**Comment by stamblerre** [comment]
It sounds like you may not be using Go modules or you may not have opened your project at the module root (directory with the `go.mod` file)? Is this case? Also, can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by istanggsh** [comment]
Thanks, I lack the `go mod`. I open my project at `$GOPATH/src` directory, so I think I don't need a `go.mod`. And now I add the file `go.mod`, it solves the problem.

**Comment by stamblerre** [comment]
Ok great! I'll close this issue.
