### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ianarnold** [golang/vscode-go#1515]
gopls version: v0.6.11
gopls flags: 
update flags: proxy
extension version: 0.25.0
go version: 1.16.4
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
`gopls` should've prepopulated the crash logs in this issue, but it seems like they weren't there.

The next time this happens, can you please paste in the output of Ctrl+Shift+P -> "View: Output" -> "Tasks" (right hand corner) -> "gopls (server)"? You can also see how to collect `gopls` logs [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by hyangah** [comment]
Closing.
Thanks for the report, @ianarnold Please open a new issue if you encounter similar crashes or any issues with extension's language features.
