### ISSUE TITLE
debug: support hit count conditions

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#1516]
This is a feature request for Hit Count Condition support.

Similar to conditional breakpoints, users may want to set a breakpoint based on how many times that breakpoint has been hit.

Here is the VS Code UI for setting a hit condition:
![Screen Shot 2021-05-14 at 3 24 05 PM](https://user-images.githubusercontent.com/6634754/118319207-71c31000-b4c8-11eb-8d22-8cb03c763a81.png)

Possible HitConditions to support would be:
- `int` (implied `==`)
- `== int`
- `>= int`
- `<= int`
- `% int`

Related delve feature request: go-delve/delve#2481

**Comment by hyangah** [comment]
Extension v0.26.0 requires a dlv-dap version that includes the fix. 
So, closing. Thanks @suzmue
