### ISSUE TITLE
bug: leftover temporary directories (/tmp/go-build*, /tmp/vscode-go*)

### ISSUE THREAD

**Issue by bukshee** [golang/vscode-go#152]
### Version

ms-vscode.go v0.14.3

### Describe the bug
`/tmp` dir is littered with orphaned `go-build*` and `vscode*` dirs/files:

```sh
vscode@c8e059c8e6a0:/tmp$ ls -d vscode-* |wc -l
103
vscode@c8e059c8e6a0:/tmp$ ls -d go-build* |wc -l
819
```

It might be related to issue #2442, but I have `editor.formatOnPaste` off.

### My settings

```sh
vscode@c8e059c8e6a0:/tmp$ go version
go version go1.14.2 linux/amd64
vscode@c8e059c8e6a0:/tmp$ code -v
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64
vscode@c8e059c8e6a0:/tmp$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vscode/.cache/go-build"
GOENV="/home/vscode/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build965369343=/tmp/go-build -gno-record-gcc-switches
```

**Comment by hyangah** [comment]
`/tmp/go-build*` is from the go command. https://github.com/golang/go/issues/25808
VS Code Go extension itself invokes go commands for various purposes.

@jayconrod In order to repro: clean /tmp/go-build*, run `go test ./...`, cancel it, and see what's left in the directory. If lucky, I get only empty directories left. If not lucky, some directories contain contents. `golang.org/x/tools` is a good repo to test against because `go test ./...` takes a while. (I could successfully repro on linux, with go1.14.2)

I don't know yet who's creating `/tmp/vscode-go*` directory. Given the existence of `/tmp/vscode-typescript*`, I guess this is a temp directory prepared by vscode but will keep looking.

**Comment by stamblerre** [comment]
> I don't know yet who's creating `/tmp/vscode-go*` directory. Given the existence of `/tmp/vscode-typescript*`, I guess this is a temp directory prepared by vscode but will keep looking.

It's created here, but it should get removed: https://github.com/golang/vscode-go/blob/master/src/util.ts#L926

**Comment by bukshee** [comment]
A note, might help: all `go-build*` dirs empty, while `vscode-*` contain a js an a sock file:
```sh
/tmp/vscode-ipc-f5af8922-d5a7-4293-aa60-ef083f21aec7.sock
/tmp/vscode-remote-containers-029431c21035f6d93854397256154bbac4bd71f3.js
```

**Comment by hyangah** [comment]
Thanks @stamblerre and @bukshee.

For those files named `vscode-ipc*` or `vscode-remote-containers-*`, github.com/microsoft/vscode may be a better place for discussion. In my case, I see `/tmp/vscode-ipc-*` files and I suspect they are used for communication with extension hosts. But I don't know the details.

**Comment by jayconrod** [comment]
@hyangah So the issue here is that `go test` leaves temporary directories behind when a build is cancelled? Should we create an issue for that specifically?

How is it cancelled? With SIGINT?

**Comment by hyangah** [comment]
@jayconrod I did Ctrl+C in the above repro scenario. (`SIGINT`)
I just tried to `kill` (SIGTERM), and the same observation.

When the go extension cancels outstanding commands (including `go build`, `go test`, ...), it uses node.js's `process.kill` with the default (undefined) signal type. That is `SIGTERM`.

**Comment by bukshee** [comment]
No, `/tmp/vscode-go*` are js and sock files. They are also leftover, but much less in number than go-build ones. It is up to you whether you want to address this part or not.

Thanks!

**Comment by hyangah** [comment]
The names of sock files mentioned in https://github.com/golang/vscode-go/issues/152#issuecomment-637693952 (no `vscode-go*` btw) look very similar to the ipc handles used in github.com/microsoft/vscode. So, please file a bug in github.com/microsoft/vscode (they historically had a few issues related to leftover sock files in /tmp) if this becomes an issue. 

Closing.
