### ISSUE TITLE
gopls: randomly crashing while hovering / moving the mouse?

### ISSUE THREAD

**Issue by OneOfOne** [golang/vscode-go#1522]
gopls version: (devel)
gopls flags: 
update flags: off
extension version: 0.26.0-dev
go version: devel go1.17-6d2ef2ef2a
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 4
total start count: 5

In a pretty huge go repo, moving the mouse randomly crashes gopls with this:

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7be26a]

goroutine 19047 [running]:
golang.org/x/tools/internal/lsp/source.HoverIdentifier({0xe600d8, 0xc00883e0c0}, 0x0)
	  hover.go:99  0xaa
golang.org/x/tools/internal/lsp/source.Hover({0xe600d8, 0xc00883e0c0}, {0xe87e78, 0xc02dcec700}, {0xe6bc98, 0xc02f2de8a0}, {0xbd5cc0, 0x0})
	  hover.go:70  0x8b
golang.org/x/tools/internal/lsp.(*Server).hover(0xc030e46ad8, {0xe600d8, 0xc00883e0c0}, 0xc02c8ba060)
	  hover.go:26  0x267
golang.org/x/tools/internal/lsp.(*Server).Hover(0xc005d9c900, {0xe600d8, 0xc00883e0c0}, 0xbd5cc0)
	  server_gen.go:128  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0xe600d8, 0xc00883e0c0}, {0xe8c1e0, 0xc00015e2a0}, 0xc02c8ba000, {0xe60340, 0xc00883e000})
	  tsserver.go:372  0x12c5
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0xe600d8, 0xc00883e0c0}, 0xc02c8ba000, {0xe60340, 0xc00883e000})
	  protocol.go:154  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0xe600d8, 0xc00883e0c0}, 0xc02c8ba000, {0xe60340, 0xc00883e000})
	  lsprpc.go:684  0xa7d
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0xe600d8, 0xc00883e0c0}, 0xc01977e2d0, {0xe60340, 0xc00883e000})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20f
[Info  - 2:04:45 PM] </pre>

**Comment by stamblerre** [comment]
Can you please try reproducing with gopls/v0.6.11? Also, have you noticed which identifier you are hovering on to cause the crash?

**Comment by OneOfOne** [comment]
It doesn't happen with v0.6.11, only master, I'll try to narrow it down
more but it's hard because it's completely random.

**Comment by OneOfOne** [comment]
I got another crash with master in:
```go
func HoverIdentifier(ctx context.Context, i *IdentifierInfo) (*HoverInformation, error) {
	ctx, done := event.Start(ctx, "source.Hover")
	defer done()

	fset := i.Snapshot.FileSet() <<<< here
......
```

I added some prints and will wait for it to happen again.

**Comment by stamblerre** [comment]
Thank you for continuing to try to track this down! Looks like the identifier is nil, so I think we will need some print statements in the `Identifier` function to see how it can return a nil identifier with a nil error. Please let me know if you'd like me to put together a CL with additional logging.

**Comment by OneOfOne** [comment]
I swear garret hates me, anyway https://go-review.googlesource.com/c/tools/+/322293

I'll be watching it more.

**Comment by stamblerre** [comment]
Thank you for mailing that CL. Do you mind running with it (instead of us merging it) until you are able to get a repro? Thank you!

**Comment by OneOfOne** [comment]
Yeah that's what I'm doing right now, if I find the bug i'll change the CL to have the fix.

**Comment by OneOfOne** [comment]
@stamblerre found it! https://go-review.googlesource.com/c/tools/+/322651
