### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by TomasWeg** [golang/vscode-go#1523]
gopls version: v0.6.11
gopls flags: 
update flags: proxy
extension version: 0.25.0
go version: 1.16.4
environment: Visual Studio Code win32
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: unreachable

goroutine 24654 [running]:
go/types.(*Checker).handleBailout(0xc002c06360, 0xc001813818)
	  check.go:245  0xa5
panic(0x1229b20, 0x14a00d0)
	  panic.go:965  0x1c7
go/types.unreachable(...)
	  errors.go:25
go/types.(*Checker).assignment(0xc002c06360, 0xc00441c880, 0x14b5560, 0xc00224a750, 0x137080c, 0xa)
	  assignments.go:29  0x9fa
go/types.(*Checker).initVar(0xc002c06360, 0xc005dd0af0, 0xc00441c880, 0x137080c, 0xa, 0x94e700, 0xc001f54df0)
	  assignments.go:141  0x151
go/types.(*Checker).initVars(0xc002c06360, 0xc001f54de8, 0x1, 0x1, 0xc001d71640, 0x1, 0x1, 0x0)
	  assignments.go:264  0x633
go/types.(*Checker).shortVarDecl(0xc002c06360, 0x14b21e0, 0xc005d82d68, 0xc001d71630, 0x1, 0x1, 0xc001d71640, 0x1, 0x1)
	  assignments.go:339  0x29e
go/types.(*Checker).stmt(0xc002c06360, 0x0, 0x14c0a40, 0xc001ee4bc0)
	  stmt.go:408  0x3d25
go/types.(*Checker).stmtList(0xc002c06360, 0x0, 0xc001d71670, 0x1, 0x1)
	  stmt.go:120  0xe6
go/types.(*Checker).funcBody(0xc002c06360, 0xc0016986c0, 0xc003e60930, 0x6, 0xc001e183f0, 0xc00350adb0, 0x0, 0x0)
	  stmt.go:42  0x1f3
go/types.(*Checker).funcDecl.func1()
	  decl.go:749  0x6e
go/types.(*Checker).processDelayed(0xc002c06360, 0x0)
	  check.go:291  0x45
go/types.(*Checker).checkFiles(0xc002c06360, 0xc002e65938, 0x3, 0x3, 0x0, 0x0)
	  check.go:267  0xdc
go/types.(*Checker).Files(...)
	  check.go:250
golang.org/x/tools/internal/lsp/cache.typeCheck(0x14c2878, 0xc002aec0c0, 0xc0054a8000, 0xc0054a81c0, 0x2, 0xc001549b60, 0x0, 0x0, 0x0)
	  check.go:467  0x1173
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1(0x14c2878, 0xc002aec0c0, 0x14b12c0, 0xc0054a8000, 0xc002835170, 0x13d9da0)
	  check.go:121  0x1d8
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc0038b02c0, 0x14c2878, 0xc002aec0c0, 0xc002f38540, 0x14b12c0, 0xc0054a8000, 0xc004e12600)
	  memoize.go:322  0xb2
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x18d
[Error - 17:38:15] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Thank you for this report! It looks like this may already be resolved at master: https://github.com/golang/go/blob/04cd717a269d94d3b3459a3aaf43bc71e3112b7a/src/go/types/assignments.go#L29 (1.16.4) vs. https://github.com/golang/go/blob/cca23a73733ff166722c69359f0bb45e12ccaa2b/src/go/types/assignments.go#L29 (master).
