### ISSUE TITLE
debug: Ability to see the content of machine registers when debugging .s files

### ISSUE THREAD

**Issue by petr-sneller** [golang/vscode-go#1527]
There is currently no way to inspect the content of machine registers. For example if you have some code written in go assemler (.s) file - you can step into that file and even hit a breakpoint, but you cannot see the content of registers, which makes debugging of such files kind of useless.

It would be nice to be able to see the content of machine registers at least in .s files.

**Comment by hyangah** [comment]
That's a good idea. 
With https://github.com/go-delve/delve/pull/2446 (already released as v1.6.1), I am guessing the newest dlv already should provide some degree of support for register content inspection through DEBUG CONSOLE and the watch panel. 
https://github.com/go-delve/delve/blob/master/Documentation/cli/expr.md#cpu-registers

But ideally, I hope we can see the list of registers (maybe through the VARIABLES viewlet when we stop at .s?). `debugger.ScopeRegisters` and `debugger.ThreadRegisters` look relevant.  (https://github.com/go-delve/delve/blob/master/service/rpc2/server.go#L425 for reference)  

cc @polinasok @suzmue

**Comment by hyangah** [comment]
I chat with @suzmue and @polinasok.

Something to think about:
  * how to present the `value` by default?
    -  is it sufficient to show as numbers in the hex format, and additional strings for flags such as `Rflags` as done by `dlv` cli)?
    - or, should we come up with a creative solution to utilize the richer expression?
   * should we set `evaluateName`? If yes, what that should be? 
   * wouldn't the new assembly view of VSCode  (https://github.com/microsoft/vscode/issues/124163) be more appropriate for assembly code inspection?

**Comment by petr-sneller** [comment]
I'm on latest golang and delve, but I still cannot see the content of all registers.

I can type XMM0, R15, etc in debug console and it would print a content of a register. But it cannot print XMM16 and above, YMM, ZMM, and K registers.

In my settings, I have:

```
    "go.delveConfig":{
        "debugAdapter":"dlv-dap",
        "showRegisters": true
    },
```

But I still don't see any content of registers anywhere.

Is there a plan to fix this somehow?

**Comment by petr-sneller** [comment]
@suzmue That's a good tip, thanks :)

BTW I really enjoy the feature to run a specific test in a .go file, which doesn't really have a launch configuration at all. I wish this worked so I can just click on tests I want to debug like that :)

**Comment by hyangah** [comment]
The Go Nightly version includes Suzy's change. Would be nice if you can give it a try and verify it works.
Hopefully we release the next version with this fix soon.
