### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by ypshe** [golang/vscode-go#1529]
gopls version: v0.5.3
gopls flags: 
update flags: proxy
extension version: 0.25.1
go version: 1.15.1
environment: iCoding linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
This is a known compatibility problem with older versions of gopls on recent versions of the extension (#1328). You can update your gopls tool as described in the [troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#update-tools).

**Comment by hyangah** [comment]
Closing. @ypshe, please open a new issue if the problem persists even after updating the gopls. The latest gopls version as of Jun 21 is v0.7.0.
