### ISSUE TITLE
gopls: show warning even if build tag was added

### ISSUE THREAD

**Issue by tuananhlai** [golang/vscode-go#1533]
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.4 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.6.11
    golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210403161142-5e06dd20ab57 h1:F5Gozwx4I1xtr/sr/8CFbb57iKi3297KFs0QDbGN60A=
    golang.org/x/tools@v0.1.1-0.20210504170620-03ebc2c9fca8 h1:rTLms91GhM16y4sUcNGLdel0jJ8jXdQeXuN+7evgYiQ=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.1.3 h1:qTakTkI6ni6LFD5sBwwsdSO+AQqbSIxOauHTTQKZ/7o=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64
```
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.25.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: /home/anhlt/go/bin
toolsGopath: 
gopath: /home/anhlt/go
GOROOT: /usr/local/go
PATH: /home/anhlt/.yarn/bin:/home/anhlt/.yarn/bin:/home/anhlt/android_sdk/emulator/:/home/anhlt/android_sdk/platform-tools:/home/anhlt/android_sdk/cmdline-tools/latest/bin:/home/anhlt/flutter/bin:/home/anhlt/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/anhlt/go/bin:/usr/local/go/bin:/home/anhlt/go/bin:/home/anhlt/.nvm/versions/node/v14.15.1/bin:/home/anhlt/flutter/.pub-cache/bin:/home/anhlt/.nvm/versions/node/v14.15.1/bin:/home/anhlt/flutter/.pub-cache/bin

   gopkgs: /home/anhlt/go/bin/gopkgs installed
   go-outline: /home/anhlt/go/bin/go-outline installed
   gotests: /home/anhlt/go/bin/gotests installed
   gomodifytags: /home/anhlt/go/bin/gomodifytags installed
   impl: /home/anhlt/go/bin/impl installed
   goplay: /home/anhlt/go/bin/goplay installed
   dlv: /home/anhlt/go/bin/dlv installed
   dlv-dap: dlv-dap not installed
   staticcheck: /home/anhlt/go/bin/staticcheck installed
   gopls: /home/anhlt/go/bin/gopls installed

go env
Workspace Folder (teko-footprint): /home/anhlt/Coding/teko-footprint
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN="/home/anhlt/go/bin"
	GOCACHE="/home/anhlt/.cache/go-build"
	GOENV="/home/anhlt/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/anhlt/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/anhlt/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.16.4"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/anhlt/Coding/teko-footprint/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1256749560=/tmp/go-build -gno-record-gcc-switches"
	
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
  "go.toolsManagement.autoUpdate": true,
  "go.useLanguageServer": true,
  "gopls": {
    "formatting.gofumpt": true,
    "build.buildFlags": ["-tags=pro"]
  },
}
```

### Describe the bug

The extension shows warning when the build tag is at the top of the file, even though I have added it to "gopls.build.buildTags".

### Steps to reproduce the behavior:
1. Add a tag to vscode settings `gopls.build.buildTags' (in my case, 'pro')
2. Add `// +build !pro` to the top of the file
3. See error

Funny enough, if I manually move the package declaration to the top of the file, then back to its original position, the warning went away.

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/42168740/120093802-d926c400-c146-11eb-842d-2d44fe270f62.png)

**Comment by stamblerre** [comment]
It seems like this file is still excluded by the `pro` build tag that you specified -- `// +build !pro` means that you should exclude this file from the build when the tag is `pro`. So in this case, I believe the warning is working as intended.

**Comment by tuananhlai** [comment]
How should I hide this warning? I tried add '!pro' to the build tag but the result is still the same.

**Comment by tuananhlai** [comment]
> > How should I hide this warning? When I tried adding '!pro' to the build tag, the extension shows warning on the file with `// +build pro`.
> 
> That is expected. `gopls` will not work in files that are excluded by the build, so depending on the build tag in use, you can work on either `pro` files or `!pro` files.

Is that so? Thank you for your support <3
