### ISSUE TITLE
debug: Get "Failed to set variable: 1:4: expected type, found newline" attempting to change slice element

### ISSUE THREAD

**Issue by davidmichaelkarr** [golang/vscode-go#1535]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

I have the following in "hello.go":
```
package main

import (
	"fmt"
)

func main() {
	fmt.Println(addTo(3))
	fmt.Println(addTo(3, 2))
	fmt.Println(addTo(3, 2, 4, 6, 8))
	a := []int{4, 3}
	fmt.Println(addTo(3, a...))
	fmt.Println(addTo(3, []int{1, 2, 3, 4, 5}...))
}

func addTo(base int, vals ...int) []int {
	out := make([]int, 0, len(vals))
	for _, v := range vals {
		out = append(out, base+v)
	}
	return out
}
```
I set a breakpoint at the top of main.  I stepped until right after the assignment to "a".  In the Variables panel, I inspected the contents of "a". I selected the second element (a[1]).  I right-clicked and selected "Set Value".  It created a text field around the current value of "3".  I changed it to "4" and hit tab (also tried enter).  That results in the following errors:

    Failed to set variable: 1:4: expected type, found newline

I also did the same thing running "dlv" from the command line. I had no issue changing the slice cell.

Extension version: 0.25.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.4.0-70-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (2 x 1607)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|6.11GB (3.15GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id fdbb3b1f-f14d-4b54-9990-f155f9c3839a|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30291414
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
vscgsv2:30307504
vscorehov:30309549
bridgeflightcf:30302070
vscod805:30301674

```

</details>

**Comment by polinasok** [comment]
@davidmichaelkarr Thank you for your detailed report with a reusable test case. In the future, please also do share share your launch.json configuration with us.

Based on the described behavior, I believe you are using the legacy adapter. The set-variable feature is not working properly with it. Roughly, it only supports scalar (non-string) top-level variables (e.g. if you want to change an index value to get out of a loop quicker), but breaks if used to set anything more complex. The good news is that we are currently actively working on a new dlv-dap adapter, implemented inside of delve itself, and this feature should be working much better with it. Please give it a try following the instructions [here](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md).

**Comment by davidmichaelkarr** [comment]
Ok, confirmed. Once I followed the steps to use the dlv-dap adapter, and tested my example, I was able to change a cell.

**Comment by polinasok** [comment]
Thank you @davidmichaelkarr. 
Closing this issue as fixed as we are on our way to replace the old adapter with the new one where this feature works.
