### ISSUE TITLE
debug: dlv-dap: "Attach to Process" configuration fails without program attribute (which it doesn't need)

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#1538]
Looks like we erroneously check for the program argument even when using local attach mode. With the following configuration:
```
{
            "name": "Attach to Process",
            "type": "go",
            "request": "attach",
            "mode": "local",
            "processId": 23125,
            "debugAdapter": "dlv-dap",
},
```
fails with
```
Program arg: undefined
Error: The program attribute is missing in the debug configuration in launch.json
```

Once I added a dummy (but valid) program arguments, the rest of the configuration appears to be working as expected.

**Comment by hyangah** [comment]
@polinasok proposed to add a test to prevent regression in the future.

**Comment by hyangah** [comment]
Filed the followup issue. Closing.
