### ISSUE TITLE
debug: callstack doesn't match editor / file content when clicking on function entries

### ISSUE THREAD

**Issue by rosasco-wk** [golang/vscode-go#1541]
SUMMARY
When debugging my project and stopped at a breakpoint, the call stack appears with the correct function names that match my locally modified code.  When I click on these function names,  the result is an editor tab is brought up with a source file that is up on github that is out of date w.r.t. my locally modified copy.  In my case, the cursor is placed in the wrong function entirely (the correct function doesn't exist in the upstream file).

CONFIGURATION
vscode: 1.56.2
vscode-go: 0.25.1
OS: macOS
gopls: v0.6.11 (I've tried with go.useLanguageServer set to both true and false)

VSCODE SETTINGS
    "go.toolsManagement.autoUpdate": true,
    "go.alternateTools": {
      "go": "go",
      "go-outline": "go-outline",
      "gometalinter": "gometalinter",
      "gopkgs": "gopkgs",
      "gopls": "gopls",
      "guru": "guru",
      "goimports": "/usr/bin/goimports",
    },
    "go.autocompleteUnimportedPackages": true,
    "go.toolsGopath": "${HOME}/go",
    "go.docsTool": "godoc",
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.gotoSymbol.includeImports": true,
    "[go]": {
      "editor.insertSpaces": false,
      "editor.formatOnSave": true,
      "editor.codeActionsOnSave": {
        "source.organizeImports": true
      }
    },

**Comment by suzmue** [comment]
Could you please share your launch configuration that you are using?

**Comment by rosasco-wk** [comment]
{
    "configurations": [
        {
            "name": "Attach to Delve",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "apiVersion": 2,
            "remotePath": "",
            "cwd": "<HOME>/src/fuse_for_agi",
            "dlvLoadConfig": {
                "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 120,
                "maxArrayValues": 120,
                "maxStructFields": -1
            },
            "host": "127.0.0.1",
            "port": 1234,
            "showLog": true,
            "trace": "verbose",
        },
    ],
}

**Comment by suzmue** [comment]
Thanks for including the launch configuration! Could you include the trace from the debug console as well?

**Comment by polinasok** [comment]
+1 on sharing the trace with "trace":"verbose", "showLog":true, "logOutput":"rpc,debugger" in your `launch.json`

**Comment by hyangah** [comment]
This is a remote/attach case - where the debug target was built externally and the delve RPC server was launched externally.
Closing the issue since we cannot make a progress without additional info.

@rosasco-wk please check whether the debug target was built with the expected version of source code.  If it was built correctly but you still see this issue, please share the log @suzmue and @polinasok requested, and reopen this issue. Thanks!
