### ISSUE TITLE
Base 10 range for numeric types

### ISSUE THREAD

**Issue by rajat-008** [golang/vscode-go#1550]
**Is your feature request related to a problem? Please describe.**
Every time I want to select a numeric type appropriate fo my use case i have to google the data-type appropriate for my range. 

**Describe the solution you'd like**
I'd be great help if along with intellisense for datatypes(numeric ones), the base 10 ranges are also given, which could help developers select the data type right away without any googling or calculation.

**Comment by findleyr** [comment]
Sorry, I don't fully understand this feature request, could you explain further?  Are you asking to see ranges in hover information? Completions?

**Comment by rajat-008** [comment]
Yes, so as shown in the below image, along with the completions for uint, I'd like to also view the Base-10 ranges of each of the datatypes. For example, uint16 can hold values from 0 to 65535. If this "0-65535" can be shown along with the suggestions, it can help developers make immediate decision as per their use case.
Please let me know if I have to clarify further.
![go_code_gh_issue](https://user-images.githubusercontent.com/29430988/121237865-20ceed80-c8b5-11eb-9712-7b6ae054de5a.png)

**Comment by findleyr** [comment]
Thanks for the clarification, I understand now.

I'm not sure if this is obviously better than the current behavior.  A couple counter points:

> Every time I want to select a numeric type appropriate fo my use case i have to google the data-type appropriate for my range.

The majority of times I need to select a numeric data type either an int or float64 work appropriately (sometimes uint).  Other data types are only relevant if there is a specific sizing requirement. So for me at least, most of the time this would be noise.

It's also unclear what to do with user-defined types.  E.g. `type Mode uint`, where Mode is used as a bitfield. We probably _don't_ want to see the range there, but I can imagine other scenarios where we _would_ want to see the range for a defined type.

**Comment by findleyr** [comment]
We discussed this at our team meeting today, and decided to decline this feature for the reasons listed in https://github.com/golang/vscode-go/issues/1550#issuecomment-857014659.

**Comment by rajat-008** [comment]
Cool!
I understand that the feature would make sense in very few cases, and most of the times this would be noise.
Thanks!
