### ISSUE TITLE
sudo debug request

### ISSUE THREAD

**Issue by linlih** [golang/vscode-go#1553]
I have to change user's suders file，to make sure user doesn't have to input password when I running debug.
Can it input the password by myself when it needed?

**Comment by findleyr** [comment]
Hi, I think you may have filed this in the wrong place.  This is the vscode-go repo.

**Comment by findleyr** [comment]
I'm sorry, I misread this issue initially.  This looks like a dupe of #558, however.

**Comment by findleyr** [comment]
And FWIW, #558 is a high priority for the new debug adapter (dlv-dap).
