### ISSUE TITLE
Debugging a Golang app that needs to execute under a specific Venv

### ISSUE THREAD

**Issue by aronchick** [golang/vscode-go#1556]
Here's my launch.json
```
{
            "name": "Debug CLI",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "dlvLoadConfig": {
                "followPointers": true,
                "maxVariableRecurse": 1,
                "maxStringLen": 6400,
                "maxArrayValues": 64,
                "maxStructFields": -1
            },
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}",
            "env": {},
            "args": [
                "program",
                "run"
            ],
            "showLog": true,
            "internalConsoleOptions": "openOnSessionStart"
        }
```

VSCode is using the right virtual environment:
![image](https://user-images.githubusercontent.com/51317/121606245-a8764280-ca02-11eb-9d35-733b7e34dc43.png)

But I can't get the debugger to use the right .venv for Go only. Suggestions?

**Comment by findleyr** [comment]
Hi, disclaimer that I'm not that familiar with the debugger, but AFAIK venv is a Python concept. What does it mean in the context of Go?

**Comment by aronchick** [comment]
Nothing really in the context of go, but it basically means that the shell you're executing in is taking place with a certain set of python packages installed. That's what I need to replicate - the debugger executes in the same shell that the terminal exists in.

**Comment by findleyr** [comment]
Got it.

I wonder if this could be achieved with a wrapper script for delve. For example, perhaps you could set `go.alternateTools` for this, using the new 'dlv-dap' adapter:
https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md#testing
(there may also be a way to do this with the legacy debug adapter).

Then have that wrapper script activate your venv.  This might not work if we ever require that `delve` is actually a go program, for example if it is passed to `go version -m`.

I think one of the debug experts will need to chime in @polinasok @suzmue @hyangah

**Comment by hyangah** [comment]
AFAIK venv is a python concept, and the screenshot @aronchick shared indicates that the "Python extension" recognizes it and uses it for python operation, not the vscode or extension host (which runs go extension) itself.  The debugger executes with the environment variables inherited from the vscode&extension host, not the terminal's.

`go.alternateTools` is the extension settings, so you can use that for the legacy debug adapter too.

Additionally - it looks like over time, this extension accumulated many different ways to configure environment variables. Wonder if any of the followings can meet your need.

* For debugging only: `env` and `envFile` launch configuration https://github.com/golang/vscode-go/blob/master/docs/debugging.md#launch-configurations

* For testing only: [`go.testEnvFile`](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gotestenvfile) and [`go.testEnvVars`](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gotestenvvars)

* For all the tools used by the extension (including `go` and `dlv`): [`go.toolsEnvVars`](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gotoolsenvvars)

**Comment by findleyr** [comment]
@hyangah IIRC the subtlety here is that to get the correct env vars you're meant to run the venv activation script. I.e. not something that can be statically configured.

**Comment by findleyr** [comment]
Although reading the venv docs, perhaps this isn't necessary:
> You don’t specifically need to activate an environment; activation just prepends the virtual environment’s binary directory to your path, so that “python” invokes the virtual environment’s Python interpreter and you can run installed scripts without having to use their full path. However, all scripts installed in a virtual environment should be runnable without activating it, and run with the virtual environment’s Python automatically.

(from https://docs.python.org/3/library/venv.html)

**Comment by aronchick** [comment]
@hyangah has the point - mentally, you get the idea that the entire vscode is running under the correct venv because you set the python extension. As a result, you'd expect to see new shells spawn and auto-activate that venv (they do). HOWEVER, the delve debugger uses its own shell and does not.

That's a surprise - and no obvious at all how to work around (other than prepending the execution of the debugger under the venv).

**Comment by hyangah** [comment]
@aronchick Yes, it's not very obvious to users.

At this moment, `venv` is still python-specific so I don't know what to do about it.
Closing since it seems beyond the scope of our extension for now.

Keep us posted if anyone figures out how other languages extensions handle similar problems. We may want to come back to this issue when we implement the `console` mode so we can launch the debug target in integrated terminals, but it's still too early to say its feasibility.

**Comment by aronchick** [comment]
Well, I'd like to suggest that when you run delve, you run it under the same environment as the terminal window. I guess that's what you're referencing for "console"?
________________________________

**Comment by hyangah** [comment]
It depends on how python extension populates the environment for the terminal window, and whether other extensions are allowed to access the terminal python extension is maintaining. We are not familiar with python's venv support and need specific guidance from the python extension.

**Comment by aronchick** [comment]
Fair enough - i'm not sure how it does it, but when I create a new terminal in VSCode, if i have a venv already activated, it automatically activates for the new one.

That's why this was so strange to me. Understood you'll have to talk to them to understand how!
________________________________
