### ISSUE TITLE
reconsider the "Go Modules" status bar

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#156]
https://github.com/microsoft/vscode-go/issues/2954 requests a setting to disable this status bar. I wonder if it's time get rid of it altogether - I believe it was used to help people understand if they were using modules when modules were released. It may no longer be necessary, or we may be able to expose the value of VS Code Go's value of `GOMOD` through a less intrusive UI.

**Comment by hyangah** [comment]
This is now removed and the information is available from the unified Go status bar item. 
(Its `go.mod` entry is activated only if the open file is inside a module (so, modules mode is on).
