### ISSUE TITLE
debug: strange behavior when debugging, possibly related to CGo

### ISSUE THREAD

**Issue by firelizzard18** [golang/vscode-go#1564]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.4 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.56.2
054a9295330880ed74ceaedda236253b4f39a335
x64
```
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.25.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: REDACTED/go
GOROOT: /usr/lib/go
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/11/bin

   gopkgs: REDACTED/go/bin/gopkgs installed
   go-outline: REDACTED/go/bin/go-outline installed
   gotests: REDACTED/go/bin/gotests installed
   gomodifytags: REDACTED/go/bin/gomodifytags installed
   impl: REDACTED/go/bin/impl installed
   goplay: REDACTED/go/bin/goplay installed
   dlv: REDACTED/go/bin/dlv installed
   dlv-dap: REDACTED/go/bin/dlv-dap installed
   staticcheck: REDACTED/go/bin/staticcheck installed
   gopls: REDACTED/go/bin/gopls installed

go env
Workspace Folder (runway): REDACTED/src/runway
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="REDACTED/.cache/go-build"
	GOENV="REDACTED/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="REDACTED/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="REDACTED/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/lib/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.16.4"
	GCCGO="gccgo"
	AR="ar"
	CC="x86_64-pc-linux-gnu-gcc"
	CXX="x86_64-pc-linux-gnu-g++"
	CGO_ENABLED="1"
	GOMOD="REDACTED/src/runway/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build659227540=/tmp/go-build -gno-record-gcc-switches"
	
```

### Share the Go related settings you have added/edited

```jsonc
{
    "go.lintOnSave": "off",
    "go.useLanguageServer": true,
    "go.vetFlags": ["-composites=false"],
    "go.toolsManagement.autoUpdate": true,
    // "go.formatTool": "goimports",

    "gopls": {
        "analyses": {
            "staticcheck": true,
        }
    },

    "go.playground": {
        "openbrowser": false,
        "share": false,
        "run": true
    },
}
```

### Describe the bug
I am working on a project, [gitlab.com/eukano/runway](https://gitlab.com/eukano/runway), which uses Go bindings for C libraries, specifically [gotk3](https://github.com/gotk3/gotk3) and [go-gl](github.com/go-gl/gl).

- **To debug my project (`./cmd/runway-viewer`), I must start debugging, kill the session, and start it again.**
- The first session always hangs, and the second one always works (as far as I remember).
- If I run dlv directly and connect via `"request": "attach"`, it works every time (using the arguments logged by vscode).
  - `$HOME/go/bin/dlv debug --headless=true --listen=127.0.0.1:40067 --api-version=2 --wd=$HOME/src/runway`

### Steps to reproduce the behavior:
1. `git clone https://gitlab.com/eukano/runway -b vscode-go-1564`
2. `code runway`
3. Create a Go package launch configuration with `"program": "${workspaceFolder}/cmd/runway-viewer"`
4. Start the debug session - it hangs
5. Stop the hung debug session
6. Start the debug session, again, changing nothing - it works

Launch configuration:
```jsonc
{
    "name": "Viewer",
    "type": "go",
    "request": "launch",
    "mode": "auto",
    "program": "${workspaceFolder}/cmd/runway-viewer",
    "cwd": "${workspaceFolder}",
}
```

### Screenshots or recordings
As of time of writing, the most recent commit (on my project) was d11497659ccbe24a8e72cabdfd8ab4ab0f52a409.

- [Log from first session (hung)](https://github.com/golang/vscode-go/files/6645729/vscode-go-debug.s1.txt)
- [Log from second session (successful)](https://github.com/golang/vscode-go/files/6645730/vscode-go-debug.s2.txt)

**Comment by hyangah** [comment]
Thank you for sharing the trace and the steps to reproduce.
From the trace, I guess this is a bug in the (legacy) debug adapter.
According to the trace, the first hung session shows that it took ~1.6sec to compile the target and bring up the debug server. 

```
[04:41:26.095 UTC] Running: REDACTED/go/bin/dlv debug --headless=true --listen=127.0.0.1:41805 --api-version=2 --log=true --log-output=rpc --wd=REDACTED/src/runway -- REDACTED/src/runway/example/fan.runway
[04:41:27.747 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"API server listening at: 127.0.0.1:41805\n"}}
```

The second session on the other hand was up and running quickly (possibly thank to caching)

```
[04:43:00.546 UTC] Running: REDACTED/go/bin/dlv debug --headless=true --listen=127.0.0.1:9065 --api-version=2 --log=true --log-output=rpc --wd=REDACTED/src/runway -- REDACTED/src/runway/example/fan.runway
...
[04:43:00.629 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"API server listening at: 127.0.0.1:9065\n"}}
```

The legacy debug adapter has [a hard-coded delay (200ms)](https://github.com/golang/vscode-go/blob/b70f3c00e82407ee70a8c1eeac2d6ceb0ffd9d29/src/debugAdapter/goDebug.ts#L718) before attempting to connect to the debug server and I am afraid this doesn't retry when it fails to connect.

Can you give a try to [the new debug adapter Delve DAP](https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md#getting-started)?

**Comment by firelizzard18** [comment]
That works, thanks! Is Delve DAP going to become the default eventually?

FWIW, this appears to be related to gotk3. Debugging (with the legacy adapter) works normally with OpenGL (still CGo), but not with GTK.

**Comment by polinasok** [comment]
> That works, thanks! Is Delve DAP going to become the default eventually?

dlv-dap is already the default in Nightly version for local debugging. We are planning to make it the default in the stable version in the near future. In the meantime, you can configure it to be your default using settings.json
```
"go.delveConfig": {
        "debugAdapter": "dlv-dap",
    }
```
