### ISSUE TITLE
Getting code actions from ''Go''

### ISSUE THREAD

**Issue by kotyara85** [golang/vscode-go#1567]
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.15.5 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.7.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.57.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.25.1

### Describe the bug
Getting code actions from ''Go'' spins indefinitely, this has been a problem for a year or so, just decided to report it right now. Disabling gopls again

**Comment by hyangah** [comment]
We need more details about why `gopls` isn't working for you. 

@kotyara85 Can you please collect the gopls log following the instruction [Collect Gopls Information](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)? Empirically, it often is related to the workspace setup and gopls logs the information in the first few records. So, please include trace from the beginning if possible. Thanks!

**Comment by kotyara85** [comment]
@hyangah I tried to get the logs following the instruction you shared, but gopls there's no logs under gopls menu.
There's a lot under gopls (server)

It takes forever to build these
```
Library/Caches/go-build/a8/a83d5da44709c4320490230b256969b9adab55a68b1e614b61744863cfd8d530-d
```

**Comment by hyangah** [comment]
Yes, the instruction captures the server-side log and the log is in the `gopls (server)` channel. Can you please share the trace? 

We need at least the first few messages (starting from message id `0`, and the `go env` output), and the point where you noticed the slowness.
