### ISSUE TITLE
Enhancement: Allow F2 to rename symbols in files like the C# Visual Studio 2019 IDE

### ISSUE THREAD

**Issue by Omzig** [golang/vscode-go#1568]
**Is your feature request related to a problem?**
I am frustrated when I cannot use F2 to rename a symbol in my struct that is used in more than one .go file.
I receive this error: 
_renaming "ID" to "myNewId" would make it unexported breaking references from packages such as "github.com/pluralsight/webservice/controllers"_

**Describe the solution you'd like**
I expect F2 to rename all symbols from my struct where it is referenced in my project folder.

**Describe alternatives you've considered**
Currently trying to use: https://pkg.go.dev/golang.org/x/tools/cmd/gorename
This is not an easy tool to use.

Tried: _gorename -from '"models".User.ID' -to myID_ and Failed
gorename is not easy to use, and there isn't not many examples out there for how the cli works.

**Additional context**
This is the struct I am trying to rename in the models\user.go file:
```
type User struct {
	ID        int
	FirstName string
	LastName  string
}
```

**Comment by hyangah** [comment]
@Omzig Are you not using the language server (`gopls`)? The extension provides renaming features using `gopls` https://github.com/golang/vscode-go/blob/master/docs/features.md#rename-symbol

But from the error message you reported, I guess the rename couldn't be done because it results in API changes (i.e., the field is no longer accessible from outside) and breaks the callsite (github.com/pluralsight/webservice/controllers for example). If so, I think that's working as intended. Otherwise, can you tell us more one what kind of renaming you want and what you want to do with the reference from external packages?

**Comment by Omzig** [comment]
@hyangah I have this set in my settings.json:
```
    "go.useLanguageServer": true,
```
There seems to be a problem when the symbol is used in other files, it will not rename the symbol. If the symbol is a variable inside a method it will work correctly, but the stope has to be inside the same file.

C:> gopls version
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=

controllers\user.go
```
	if id != u.ID {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("ID of submitted user must match id in url"))
		return
	}

	u, err = models.UpdateUserByID(u)
```

models\user.go
```
type User struct {
	ID        int
	FirstName string
	LastName  string
}
```

When you try to rename ID to something by using F2 it should be able to rename it where ever the users specifies.

![image](https://user-images.githubusercontent.com/1987296/121957760-74fc2680-cd28-11eb-809f-0109640bd6d4.png)

Hitting Enter Causes this error:
![image](https://user-images.githubusercontent.com/1987296/121957872-9c52f380-cd28-11eb-8e6e-1c3da13ea26d.png)

Please advise, maybe I have something messed up? Maybe it just doesn't meet my expectations of a symbol rename function. Visual Studio 20xx with C# sure has spoiled me ;)

**Comment by hyangah** [comment]
@Omzig It's not the scope issue. By changing `ID` to `myNewID`, you are unexporting the field and the external package can't access the field any more. Try to change it to `MyNewID`.

**Comment by Omzig** [comment]
@Omzig Oh my goodness. Where is the emoji to crawl under a rock?
