### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by dblate** [golang/vscode-go#1573]
gopls version: v0.5.3
gopls flags: 
update flags: proxy
extension version: 2021.6.1500
go version: 1.14.3
environment: iCoding linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by dblate** [comment]
I have try to update my gopls version use "Go: Install/Update Tools", and my latest version is v0.5.3
go: golang.org/x/tools/gopls latest => v0.5.3

**Comment by hyangah** [comment]
@dblate What is your `GOPROXY`? The latest gopls is v0.7.0. https://pkg.go.dev/golang.org/x/tools/gopls?tab=versions

**Comment by dblate** [comment]
Thanks, I re-installed all the plugins and now is ok
