### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by bukekangli** [golang/vscode-go#1596]
gopls version: v0.7.0
gopls flags: 
update flags: proxy
extension version: 0.26.0
go version: 1.13
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

**Comment by bukekangli** [comment]
It's ok now。I restart vscode。Thanks！



At 2021-06-29 22:24:02, "Rebecca Stambler" ***@***.***> wrote:

Can you please share your gopls logs? Information on how to capture them can be found here.
