### ISSUE TITLE
code snippets package main with init, main function

### ISSUE THREAD

**Issue by Ja7ad** [golang/vscode-go#1599]
snippets for package main with init, main function

```json
"package main and init, main function": {
	"prefix": "pkgmi",
	"body": "package main\n\nfunc init() {\n\t$0\n}\nfunc main() {\n\t$1\n}",
	"description": "Snippet for main package & init, main function"
}
```

**Comment by stamblerre** [comment]
Thank you for this suggestion. We aren't currently adding new snippets to this extension (see https://github.com/golang/vscode-go/issues/160), but you can continue to use this snippet through VS Code's custom snippets support: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets. Sorry about the inconvenience!
