### ISSUE TITLE
DX experience breaks when using lib with invalid flag in pkg-config 

### ISSUE THREAD

**Issue by paulm17** [golang/vscode-go#1600]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.3 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@(devel)
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/paul/go
GOROOT: /usr/local/Cellar/go/1.16.3/libexec
PATH: /Users/paul/.nvm/versions/node/v14.15.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public

   gopkgs: /Users/paul/go/bin/gopkgs installed
   go-outline: /Users/paul/go/bin/go-outline installed
   gotests: /Users/paul/go/bin/gotests installed
   gomodifytags: /Users/paul/go/bin/gomodifytags installed
   impl: /Users/paul/go/bin/impl installed
   goplay: /Users/paul/go/bin/goplay installed
   dlv: /Users/paul/go/bin/dlv installed
   dlv-dap: /Users/paul/go/bin/dlv-dap installed
   staticcheck: /Users/paul/go/bin/staticcheck installed
   gopls: /Users/paul/go/bin/gopls installed

go env
Workspace Folder (dam): /Users/paul/Share/development/ponos_services/dam
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/paul/Library/Caches/go-build"
	GOENV="/Users/paul/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/paul/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/paul/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.16.3/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.16.3/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.16.3"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/paul/Share/development/ponos_services/dam/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8n/w0_1bmj579g4g75w1bq380xm0000gn/T/go-build733184706=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
```

### Describe the bug
If I use the package gopkg.in/gographics/imagick.v3/imagick: I get the following and the whole DX experience breaks.

```
go build gopkg.in/gographics/imagick.v3/imagick: invalid flag in pkg-config --cflags: -Xpreprocessor
: packages.Load errorgo list
```

I also found the following, but sadly no answer:

```
http://5.9.10.113/67286751/how-should-i-pass-cgo-cflags-allow-xpreprocessor-to-the-debugger-in-vscode-go 
```

How to resolve.  Thanks

**Comment by findleyr** [comment]
Hi, if I'm understanding correctly you can't build your project. This seems like a problem independent of vscode / gopls. How would you expect vscode to handle this differently?

For what it's worth, this problem seems to be discussed in the imagick README, with a solution described:
https://github.com/gographics/imagick/blob/020a86d5c9cbe13e63db46a925479a9a54cbff0e/README.md#common

**Comment by paulm17** [comment]
Yes, you are misunderstanding.  I can build and run the project fine.  

Here is what go.mod says:

![alt text](https://i.imgur.com/ZMBccAv.png)

**Comment by findleyr** [comment]
Ok, thanks for clarifying.

The error message is coming from the go command, which is complaining about the invalid flag. This seems to be a known issue with recent versions of imagick. Did you do any of the workarounds at https://github.com/gographics/imagick/blob/020a86d5c9cbe13e63db46a925479a9a54cbff0e/README.md#common to get `go build` working from the command line?

You may need to configure CGO_CFLAGS_ALLOW via [build.env](https://github.com/golang/vscode-go/blob/master/docs/settings.md#buildenv), or add no_pkgconfig to [go.buildTags](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gobuildtags), as described in the imagick README. Could you please try that to see if it resolves your issue?

**Comment by paulm17** [comment]
Thank you so much for your time!  

Adding the following to settings.json has resolved the issue.  

```
"gopls": {
    "build.env": {
      "CGO_CFLAGS_ALLOW": "-Xpreprocessor"
    }
  }
```
