### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by victormedranop** [golang/vscode-go#1601]
gopls version: v0.7.0
gopls flags: 
update flags: proxy
extension version: 0.26.0
go version: 1.16.4
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 2

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, are you sure that you are using gopls v0.7.0? The crash pattern here is known, for gopls versions older than 0.6.6. See #1300.

You can locate your gopls binary with `Go: Locate Configured Go Tools` in the command palette.

**Comment by hyangah** [comment]
Closing. Please open a new issue if the problem persists after updating the gopls.
