### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mariagabrielapps** [golang/vscode-go#1605]
- Issue Type: `Bug`
- Extension Name: `go`
- Extension Version: `0.26.0`
- OS Version: `Windows_NT ia32 10.0.19042`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by mariagabrielapps** [comment]
Issue Type: Bug
Extension Name: go
Extension Version: 0.26.0
OS Version: Windows_NT ia32 10.0.19042
VS Code version: 1.57.1

**Comment by findleyr** [comment]
Closing, as empty. Please reopen if you can describe your issue, thanks.
