### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ttbug** [golang/vscode-go#1607]
gopls version: v0.7.0
gopls flags: 
update flags: proxy
extension version: 0.26.0
go version: 1.16.5
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls exited due to fatal error: runtime: out of memory

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

runtime stack:
runtime.throw(0xe8668c, 0x16)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc0b0000000, 0x4000000, 0x147ced0)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x1463ee0, 0x2800000, 0x42dff7, 0x1463ee8)
	/usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x1463ee0, 0x1313, 0x0)
	/usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x1463ee0, 0x1313, 0x440000, 0xc006228480)
	/usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1246

goroutine 22192 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc000438b90 sp=0xc000438b88 pc=0x471560
runtime.(*mheap).alloc(0x1463ee0, 0x1313, 0x750100, 0xfb0ff0)
	/usr/local/go/src/runtime/mheap.go:904 +0x85 fp=0xc000438be0 sp=0xc000438b90 pc=0x429ca5
runtime.(*mcache).allocLarge(0x7f1de5252108, 0x2626000, 0xc052560001, 0x40000000)
	/usr/local/go/src/runtime/mcache.go:224 +0x97 fp=0xc000438c38 sp=0xc000438be0 pc=0x41a317
runtime.mallocgc(0x2626000, 0xdb44a0, 0xf4201, 0x751601)
	/usr/local/go/src/runtime/malloc.go:1078 +0x925 fp=0xc000438cc0 sp=0xc000438c38 pc=0x40fd65
runtime.growslice(0xdb44a0, 0xc0ac83e000, 0xf4240, 0xf4240, 0xf4241, 0xfae140, 0xc039252510, 0xd680c0)
	/usr/local/go/src/runtime/slice.go:230 +0x1e9 fp=0xc000438d28 sp=0xc000438cc0 pc=0x4524a9
golang.org/x/tools/go/ast/inspector.traverse.func1(0xfb1270, 0xc05255baa0, 0xfb0f01)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/go/ast/inspector/inspector.go:170 +0x28e fp=0xc000438db0 sp=0xc000438d28 pc=0x75178e
go/ast.inspector.Visit(0xc039252510, 0xfb1270, 0xc05255baa0, 0xfae140, 0xc039252510)
	/usr/local/go/src/go/ast/walk.go:373 +0x3a fp=0xc000438dd8 sp=0xc000438db0 pc=0x60f5fa
go/ast.Walk(0xfae140, 0xc039252510, 0xfb1270, 0xc05255baa0)
	/usr/local/go/src/go/ast/walk.go:52 +0x63 fp=0xc000438ec0 sp=0xc000438dd8 pc=0x60c543
go/ast.Walk(0xfae140, 0xc039252510, 0xfb10b8, 0xc0525629f0)
	/usr/local/go/src/go/ast/walk.go:114 +0x1345 fp=0xc000438fa8 sp=0xc000438ec0 pc=0x60d825
go/ast.walkExprList(0xfae140, 0xc039252510, 0xc0525645f0, 0x1, 0x1)
	/usr/local/go/src/go/ast/walk.go:26 +0x9e fp=0xc000438ff0 sp=0xc000438fa8 pc=0x60c2de
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0a50, 0xc052560c00)
	/usr/local/go/src/go/ast/walk.go:207 +0x1f97 fp=0xc0004390d8 sp=0xc000438ff0 pc=0x60e477
go/ast.walkStmtList(0xfae140, 0xc039252510, 0xc05252d100, 0xd, 0x10)
	/usr/local/go/src/go/ast/walk.go:32 +0x9e fp=0xc000439120 sp=0xc0004390d8 pc=0x60c3be
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0bb8, 0xc052562c00)
	/usr/local/go/src/go/ast/walk.go:224 +0x1968 fp=0xc000439208 sp=0xc000439120 pc=0x60de48
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0f00, 0xc052560dc0)
	/usr/local/go/src/go/ast/walk.go:275 +0x6aa fp=0xc0004392f0 sp=0xc000439208 pc=0x60cb8a
go/ast.walkStmtList(0xfae140, 0xc039252510, 0xc051f43c00, 0x36, 0x40)
	/usr/local/go/src/go/ast/walk.go:32 +0x9e fp=0xc000439338 sp=0xc0004392f0 pc=0x60c3be
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0c80, 0xc052643bc0)
	/usr/local/go/src/go/ast/walk.go:238 +0x1d58 fp=0xc000439420 sp=0xc000439338 pc=0x60e238
go/ast.walkStmtList(0xfae140, 0xc039252510, 0xc052648100, 0xb, 0x10)
	/usr/local/go/src/go/ast/walk.go:32 +0x9e fp=0xc000439468 sp=0xc000439420 pc=0x60c3be
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0bb8, 0xc052656f00)
	/usr/local/go/src/go/ast/walk.go:224 +0x1968 fp=0xc000439550 sp=0xc000439468 pc=0x60de48
go/ast.Walk(0xfae140, 0xc039252510, 0xfb1388, 0xc052656f30)
	/usr/local/go/src/go/ast/walk.go:247 +0x22b9 fp=0xc000439638 sp=0xc000439550 pc=0x60e799
go/ast.walkStmtList(0xfae140, 0xc039252510, 0xc0524e3700, 0x8, 0x8)
	/usr/local/go/src/go/ast/walk.go:32 +0x9e fp=0xc000439680 sp=0xc000439638 pc=0x60c3be
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0bb8, 0xc052656f60)
	/usr/local/go/src/go/ast/walk.go:224 +0x1968 fp=0xc000439768 sp=0xc000439680 pc=0x60de48
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0f28, 0xc052656f90)
	/usr/local/go/src/go/ast/walk.go:344 +0xce6 fp=0xc000439850 sp=0xc000439768 pc=0x60d1c6
go/ast.walkDeclList(0xfae140, 0xc039252510, 0xc052458000, 0x250, 0x400)
	/usr/local/go/src/go/ast/walk.go:38 +0x9e fp=0xc000439898 sp=0xc000439850 pc=0x60c49e
go/ast.Walk(0xfae140, 0xc039252510, 0xfb0ed8, 0xc05265a500)
	/usr/local/go/src/go/ast/walk.go:353 +0x2446 fp=0xc000439980 sp=0xc000439898 pc=0x60e926
go/ast.Inspect(...)
	/usr/local/go/src/go/ast/walk.go:385
golang.org/x/tools/go/ast/inspector.traverse(0xc0310e0000, 0x5d, 0x80, 0xc0044efa30, 0x40fef8, 0x10)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/go/ast/inspector/inspector.go:161 +0x165 fp=0xc0004399e8 sp=0xc000439980 pc=0x750925
golang.org/x/tools/go/ast/inspector.New(...)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/go/ast/inspector/inspector.go:49
golang.org/x/tools/go/analysis/passes/inspect.run(0xc0220ee8f0, 0xc0220ee8f0, 0xc082180000, 0xd, 0x10)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/go/analysis/passes/inspect/inspect.go:48 +0x45 fp=0xc000439a40 sp=0xc0004399e8 pc=0x751965
golang.org/x/tools/internal/lsp/cache.runAnalysis(0xfbf318, 0xc0420edd00, 0xc00022a380, 0x1435060, 0xc06acdf5c0, 0xc061920390, 0xc061920390)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:333 +0xa48 fp=0xc000439eb0 sp=0xc000439a40 pc=0xb6dda8
golang.org/x/tools/internal/lsp/cache.(*snapshot).actionHandle.func1(0xfbf318, 0xc0420edd00, 0xfad200, 0xc00022a380, 0xc0073f7768, 0x47f774)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:150 +0x159 fp=0xc000439f28 sp=0xc000439eb0 pc=0xbb7659
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc04236a240, 0xfbf318, 0xc0420edd00, 0xc061911f50, 0xfad200, 0xc00022a380, 0xc03df5b860)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:322 +0xab fp=0xc000439fa8 sp=0xc000439f28 pc=0xb6ba8b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000439fb0 sp=0xc000439fa8 pc=0x4733a1
created by golang.org/x/tools/internal/memoize.(*Handle).run
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:315 +0x185

goroutine 1 [chan receive]:
golang.org/x/tools/internal/lsp/lsprpc.(*StreamServer).ServeStream(0xc000254e00, 0xfbf3c0, 0xc000578240, 0xfc4f40, 0xc0001539a0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/lsprpc/lsprpc.go:106 +0x3a5
golang.org/x/tools/internal/lsp/cmd.(*Serve).Run(0xc0000ac8f0, 0xfbf3c0, 0xc000567b90, 0xc00012c010, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cmd/serve.go:108 +0x6ec
golang.org/x/tools/internal/tool.Run(0xfbf3c0, 0xc000567b90, 0xfc3298, 0xc0000ac8f0, 0xc00012c010, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/tool/tool.go:152 +0x316
golang.org/x/tools/internal/lsp/cmd.(*Application).Run(0xc0000ac8c0, 0xfbf350, 0xc000122000, 0xc00012c010, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cmd/cmd.go:147 +0x347
golang.org/x/tools/internal/tool.Run(0xfbf350, 0xc000122000, 0xfc3258, 0xc0000ac8c0, 0xc00012c010, 0x1, 0x1, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/tool/tool.go:152 +0x316
golang.org/x/tools/internal/tool.Main(0xfbf350, 0xc000122000, 0xfc3258, 0xc0000ac8c0, 0xc00012c010, 0x1, 0x1)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/tool/tool.go:91 +0x18e
main.main()
	/home/colin/gosrc/pkg/mod/golang.org/x/tools/gopls@v0.7.0/main.go:25 +0xdb

goroutine 130 [select]:
golang.org/x/tools/internal/fakenet.(*connFeeder).run(0xc000567c50)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/fakenet/conn.go:115 +0xad
created by golang.org/x/tools/internal/fakenet.NewConn
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/fakenet/conn.go:27 +0x315

goroutine 49 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc000414000, 0x1000, 0xc000308dc0, 0x800000, 0x7ffff800000)
	/usr/local/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0x0, 0xc000414000, 0x1000, 0x1000, 0x0, 0x2, 0x10100000000)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
syscall.Read(...)
	/usr/local/go/src/syscall/syscall_unix.go:187
internal/poll.ignoringEINTRIO(...)
	/usr/local/go/src/internal/poll/fd_unix.go:581
internal/poll.(*FD).Read(0xc00012a000, 0xc000414000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:162 +0x145
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc000128000, 0xc000414000, 0x1000, 0x1000, 0x2, 0x2, 0xc000308eb8)
	/usr/local/go/src/os/file.go:117 +0x77
golang.org/x/tools/internal/fakenet.(*connFeeder).run(0xc000567c20)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/fakenet/conn.go:121 +0xf7
created by golang.org/x/tools/internal/fakenet.NewConn
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/fakenet/conn.go:26 +0x2ef

goroutine 48 [chan receive]:
golang.org/x/tools/internal/lsp/debug.(*Instance).MonitorMemory.func1(0xc000153720, 0xc0003a4a48, 0xc0000c00c0, 0xfbf3c0, 0xc000567b90)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/debug/serve.go:532 +0x65
created by golang.org/x/tools/internal/lsp/debug.(*Instance).MonitorMemory
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/debug/serve.go:530 +0x99

goroutine 131 [select]:
golang.org/x/tools/internal/fakenet.(*connFeeder).do(0xc000567c20, 0xc000414000, 0x1000, 0x1000, 0x144c960, 0x0, 0xc00075da58)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/fakenet/conn.go:103 +0x1a5
golang.org/x/tools/internal/fakenet.(*fakeConn).Read(0xc00056ab80, 0xc000414000, 0x1000, 0x1000, 0x1, 0x0, 0xc00075dab8)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/fakenet/conn.go:67 +0x4d
bufio.(*Reader).fill(0xc000574060)
	/usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc000574060, 0xa, 0xceef40, 0xc0086d99b0, 0x203001, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:360 +0x3d
bufio.(*Reader).collectFragments(0xc000574060, 0xa, 0x4, 0x7f1dbc01e3a0, 0x30, 0x40, 0x7f1de5252a68, 0x40, 0xc007f76c40, 0xc00075dbd0, ...)
	/usr/local/go/src/bufio/bufio.go:435 +0x7a
bufio.(*Reader).ReadString(0xc000574060, 0xa, 0x0, 0x0, 0x40c2bf, 0xc008707bb8)
	/usr/local/go/src/bufio/bufio.go:483 +0x4c
golang.org/x/tools/internal/jsonrpc2.(*headerStream).Read(0xc0002987c8, 0xfbf3c0, 0xc000578240, 0xc0003ec788, 0x1, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/jsonrpc2/stream.go:110 +0x98
golang.org/x/tools/internal/jsonrpc2.(*conn).run(0xc0001539a0, 0xfbf3c0, 0xc000578240, 0xc000298840)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/jsonrpc2/conn.go:196 +0xa2
created by golang.org/x/tools/internal/jsonrpc2.(*conn).Go
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/jsonrpc2/conn.go:189 +0x5d

goroutine 94 [select]:
golang.org/x/tools/internal/memoize.(*Handle).wait(0xc03df5b8c0, 0xfbf3c0, 0xc0003ef830, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:361 +0xf2
golang.org/x/tools/internal/memoize.(*Handle).run(0xc03df5b8c0, 0xfbf3c0, 0xc0003ef830, 0xc0003548a0, 0xfad200, 0xc00022a380, 0xc03e1d2c58, 0x0, 0x7f1de5252108, 0xc0004351e0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:352 +0x1b0
golang.org/x/tools/internal/memoize.(*Handle).Get(0xc03df5b8c0, 0xfbf3c0, 0xc0003ef830, 0xc0003548a0, 0xfad200, 0xc00022a380, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:287 +0x20d
golang.org/x/tools/internal/lsp/cache.(*actionHandle).analyze(0xc0390dfb90, 0xfbf3c0, 0xc0003ef830, 0xc00022a380, 0x56, 0x1436100, 0xc0390dfc20, 0x0, 0x0, 0xc00055a580, ...)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:159 +0x71
golang.org/x/tools/internal/lsp/cache.(*snapshot).Analyze(0xc00022a380, 0xfbf3c0, 0xc0003ef830, 0xc00076b4a0, 0x56, 0xc01ae76620, 0x4, 0x4, 0x0, 0x0, ...)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:49 +0x37f
golang.org/x/tools/internal/lsp/cache.(*snapshot).DiagnosePackage(0xc00022a380, 0xfbf3c0, 0xc0003ef830, 0xfd1058, 0xc06acdf5c0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:408 +0x66f
golang.org/x/tools/internal/lsp/mod.DiagnosticsForMod(0xfbf3c0, 0xc0003ef830, 0xfd3138, 0xc00022a380, 0x7f1dbc434e98, 0xc000188010, 0xc000188010, 0x0, 0x0, 0xc0003ef920, ...)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/mod/diagnostics.go:95 +0xfbd
golang.org/x/tools/internal/lsp/mod.Diagnostics(0xfbf3c0, 0xc0003ef830, 0xfd3138, 0xc00022a380, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/mod/diagnostics.go:31 +0x651
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc00022a2a0, 0xfbf9a8, 0xc000484290, 0xfd3138, 0xc00022a380, 0xed0700)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/diagnostics.go:184 +0x31c
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc00022a2a0, 0xfd3138, 0xc00022a380)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/diagnostics.go:90 +0xb1
golang.org/x/tools/internal/lsp.(*Server).addFolders.func3(0xc00022a2a0, 0xfd3138, 0xc00022a380, 0xc000280bf0, 0xc0002fa5e0, 0xc00054a840)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/general.go:264 +0x3f
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/general.go:263 +0xb3c

goroutine 1131 [semacquire]:
sync.runtime_Semacquire(0xc0003548c8)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0003548c0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/tools/internal/memoize.(*Generation).Destroy(0xc0003548a0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:74 +0x56
created by golang.org/x/tools/internal/lsp/cache.(*View).invalidateContent
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/view.go:674 +0x1ed

goroutine 1132 [select]:
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc00022a2a0, 0xfbf3c0, 0xc008b94240, 0xfd3138, 0xc0077282a0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/diagnostics.go:174 +0x28a
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot.func1()
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/diagnostics.go:111 +0x70
golang.org/x/tools/internal/lsp.(*debouncer).debounce(0xc00049fd10, 0xc000442810, 0xd, 0x1, 0xee6b280, 0xc010821ef8)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/debounce.go:79 +0x32a
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc00022a2a0, 0xfd3138, 0xc0077282a0, 0xc0065a2870, 0x1, 0x1, 0xc000a3d800)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/diagnostics.go:110 +0x3fa
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles.func2(0xc0007dab80, 0xc00022a2a0, 0x0, 0xfd3138, 0xc0077282a0, 0xc0065a2870, 0x1, 0x1)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/text_synchronization.go:232 +0xa5
created by golang.org/x/tools/internal/lsp.(*Server).didModifyFiles
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/text_synchronization.go:230 +0x2af

goroutine 22190 [semacquire]:
sync.runtime_Semacquire(0xc061920340)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc061920338)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc061920330, 0xc061920360, 0xfbf318)
	/home/colin/gosrc/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x31
golang.org/x/tools/internal/lsp/cache.execAll(0xfbf318, 0xc0420edc80, 0xc00022a380, 0xc061a48d78, 0x1, 0x1, 0xc061911d70, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:205 +0x225
golang.org/x/tools/internal/lsp/cache.(*snapshot).actionHandle.func1(0xfbf318, 0xc0420edc80, 0xfad200, 0xc00022a380, 0xc00005af68, 0x47f774)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:144 +0x96
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc04236a1c0, 0xfbf318, 0xc0420edc80, 0xc061920000, 0xfad200, 0xc00022a380, 0xc03df5b8c0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:322 +0xab
created by golang.org/x/tools/internal/memoize.(*Handle).run
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:315 +0x185

goroutine 1133 [semacquire]:
sync.runtime_Semacquire(0xc0007dab88)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0007dab80)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles.func3(0xc0007dab80, 0xc008654000, 0x1, 0x1)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/text_synchronization.go:237 +0x2b
created by golang.org/x/tools/internal/lsp.(*Server).didModifyFiles
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/text_synchronization.go:236 +0x325

goroutine 22191 [select]:
golang.org/x/tools/internal/memoize.(*Handle).wait(0xc03df5b860, 0xfbf318, 0xc0420edcc0, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:361 +0xf2
golang.org/x/tools/internal/memoize.(*Handle).run(0xc03df5b860, 0xfbf318, 0xc0420edcc0, 0xc0003548a0, 0xfad200, 0xc00022a380, 0x90, 0x90, 0xdc3160, 0xc0002a4ea0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:352 +0x1b0
golang.org/x/tools/internal/memoize.(*Handle).Get(0xc03df5b860, 0xfbf318, 0xc0420edcc0, 0xc0003548a0, 0xfad200, 0xc00022a380, 0x0, 0x0, 0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/memoize/memoize.go:287 +0x20d
golang.org/x/tools/internal/lsp/cache.execAll.func1(0x0, 0x0)
	/home/colin/gosrc/pkg/mod/golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c/internal/lsp/cache/analysis.go:189 +0xa5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc061920330, 0xc061920360)
	/home/colin/gosrc/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/colin/gosrc/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
[Error - 2:18:42 AM] Connection to server got closed. Server will not be restarted.

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, thanks for filing an issue.

Could you give me a sense for the size of your workspace? Are you working in a large monorepo?

This may just fall into the category of "gopls uses a lot of memory", which would be tracked by golang/go#45363, but I'd like to check that there's not anything else going on here.

**Comment by ttbug** [comment]
workspace size is 1.4Gb, but when using go version: 1.16.4, and gopls is not crashed on the same workspace.

**Comment by findleyr** [comment]
@ttbug you mean gopls memory footprint is normally 1.4 Gb? How much ram do you have?

>  when using go version: 1.16.4, and gopls is not crashed on the same workspace

You mean this has only happened once, right? Or are you saying it occurs regularly on 1.16.5, and never on 1.16.4? (that would be very surprising).

**Comment by ttbug** [comment]
> @ttbug you mean gopls memory footprint is normally 1.4 Gb? How much ram do you have?
> 
> > when using go version: 1.16.4, and gopls is not crashed on the same workspace
> 
> You mean this has only happened once, right? Or are you saying it occurs regularly on 1.16.5, and never on 1.16.4? (that would be very surprising).

4G ram，it occurs regularly on 1.16.5, and never on 1.16.4

**Comment by findleyr** [comment]
> 4G ram，it occurs regularly on 1.16.5, and never on 1.16.4

That's _fascinating_.  Are you sure you are comparing the same gopls version at these go versions? There are only a handful of commits between those go versions that could even affect gopls.

Are you willing to do some experimentation to help investigate this? For starters, does the issue reproduce if you simply change the go command in your PATH, but do not recompile the gopls binary?

**Comment by ttbug** [comment]
> That's _fascinating_. Are you sure you are comparing the same gopls version at these go versions? There are only a handful of commits between those go versions that could even affect gopls.
> 
> Are you willing to do some experimentation to help investigate this? For starters, does the issue reproduce if you simply change the go command in your PATH, but do not recompile the gopls binary?

go version 1.16.5 with gopls compiled by go 1.16.4, not crash，
go version 1.16.5 with gopls comiled by go 1.16.5, not crash any more, 
It seems impossible to reproduce

**Comment by stamblerre** [comment]
If it no longer reproduces, let's close this issue. If you are able to reproduce it again, please reopen.
