### ISSUE TITLE
Go modules integration with modules auto-import

### ISSUE THREAD

**Issue by Airgunster** [golang/vscode-go#1609]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.16.5 darwin/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
$ ~/go/bin/gopls -v version
Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (2 wks ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```
* Check your installed extensions to get the version of the VS Code Go extension
	- `Version: 0.26.0`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
go env
Workspace Folder (16. Packages): /Users/airgunster/Documents/personal/repos/building-modern-web-applications-with-go/16. Packages
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/airgunster/Library/Caches/go-build"
	GOENV="/Users/airgunster/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/airgunster/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/airgunster/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.16.5/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.16.5/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.16.5"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/airgunster/Documents/personal/repos/building-modern-web-applications-with-go/16. Packages/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ll/6cyfw7w16hj7mxppws15ly540000gp/T/go-build3341884324=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
- None.

### Describe the bug
Current: Module auto-import doesn't work, no references are shown from previously created Go module.
Expected: Suggestions are given on previously created Go module and auto-import is happening as soon as you select any suggestion to the reference to previously created Go module.

### Steps to reproduce the behavior:
1. Created Go module via `go mod init github.com/airgunster/myniceprogram` command.
2. Create empty `main.go` file.
3. Create following  `helpers/helpers.go` file,

```
package helpers

type SomeType struct {
	TypeName   string
	TypeNumber int
}
```
4. Type `var myVar S` and observe that no suggestions are given on `SomeType` struct and so no module auto-import is happening.

### Screenshots or recordings
- N/A

**Comment by findleyr** [comment]
Hi, in step (4) you are typing in main.go, right? Do you have `package main` in that file (just checking, since per (2) it was empty)?

Could you clarify how this relates to 'module auto-import'? If I'm understanding correctly, everything is happening in a single module. Your issue appears to relate to the 'unimported completion' feature of gopls, with would automatically import the `helpers` _package_.

You should get unimported completion if you start typing `var myVar helpers.S`, since the imported type name would be qualified by the `helpers` package name.  This seems to me to be a reasonable compromise for unimported completion.  Completing everything without qualification would produce a lot of noise in larger workspaces.
