### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by herbertluo** [golang/vscode-go#1610]
gopls version: v0.7.0
gopls flags: -mod=readonly
update flags: proxy
extension version: 0.26.0
go version: 1.15.13
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incorrect gopls command usage.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
@herbertluo it looks like you have invalid values in the go.languageServerFlags setting. Please delete the contents of that setting. You can navigate to the settings page by opening the Command Palette (Ctrl+Shift+P) and selecting "Preferences: Open Settings (JSON)".
