### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by vincent-chen** [golang/vscode-go#1619]
gopls version: v0.7.0
gopls flags: -format-​style=goimports
update flags: proxy
extension version: 0.26.0
go version: 1.16.5
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 4

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@vincent-chen Can you please remove `-format-style=goimports` from the gopls flag (`"go.languageServerFlags"`)? 
That's an invalid flag and `gopls` already uses goimports-style formatting.
