### ISSUE TITLE
debug: display byte/uint8/rune slices as strings for readability

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#162]
See the original discussion on https://github.com/microsoft/vscode-go/issues/1385.

**Comment by fatalc** [comment]
any works on this issuse? it is very useful for bytes debug, otherwise i must do 

```go
s := string(r)
_ = s
```

where nedded and rerun debuger. 😖

**Comment by hyangah** [comment]
Our expression evaluation follows dlv's expression syntax. (https://github.com/go-delve/delve/blob/master/Documentation/cli/expr.md) which already supports type casts between string, []byte, and []rune. 

So,  users can enter `string(s)` in the Debug Console or register it 
![Screen Shot 2020-11-02 at 1 05 58 PM](https://user-images.githubusercontent.com/4999471/97902860-2d320d00-1d0c-11eb-9f39-da4760a6ca0f.png)
in the watch panel.

**Comment by hyangah** [comment]
Not all byte slices make sense as strings. So, I think letting users selectively select the slices of interest and explicitly perform type casting on those is reasonable. Closing.

**Comment by emil14** [comment]
But Goland handles this

**Comment by hyangah** [comment]
@emil14 Not all of us use goland. Screenshot and video that handles non-printable bytes may be helpful.

**Comment by emil14** [comment]
@hyangah

In goland you have this "View" button, after click on it you see a string  

<img width="715" alt="Screenshot 2021-04-29 at 11 01 14" src="https://user-images.githubusercontent.com/6453537/116513955-00357000-a8d3-11eb-8f6c-9ce34941f5c6.png">

<img width="852" alt="Screenshot 2021-04-29 at 11 01 24" src="https://user-images.githubusercontent.com/6453537/116513949-fe6bac80-a8d2-11eb-8c3f-435ad258479d.png">

**Comment by polinasok** [comment]
@emil14 This issue has been revisited at #1459 if you have additional input. Thank you.
