### ISSUE TITLE
vscode golang debug hangs 1 out of 2 times

### ISSUE THREAD

**Issue by leolikescoding** [golang/vscode-go#1620]
For asking questions, see:
- [GitHub Discussions (Q&A)](https://github.com/golang/vscode-go/discussions/categories/q-a)
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Before filing an issue, please review our troubleshooting guides
* [Troubleshooting problems with debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#troubleshooting)
* [Troubleshooting other problems](https://github.com/golang/vscode-go/tree/master/docs/troubleshooting.md)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
go version go1.16.5 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

VS Code Version: 1.58.0
OS Version:macOS Big Sur 11.4
Steps to Reproduce:

git clone https://github.com/ethereum/go-ethereum.git
setup a debug config file below :
{
"version": "0.2.0",
"configurations": [
{
"name": "debug geth",
"type": "go",
"request": "launch",
"program": "${workspaceFolder}/cmd/geth",
"args": [ ],
"env": {},
"showLog": true,
"mode": "debug",
"trace":"verbose"
}
]
}

set a breakpoint on line 257 which is main function of file 'cmd/geth/main.go'
start to debug

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by yazver** [comment]
After updating to VS 1.58.0, Debugging stoped working. Setting of breakpoints has no affect. Downgrading to 1.57 has helps me.

I have next configuration:
Версия кода VS: 1.58.0
Версия ОС: macOS Big Sur 11.4

**Comment by leolikescoding** [comment]
actually it works 1 out of 2 times for me .

**Comment by leolikescoding** [comment]
it becomes fine when i used the nightly built go-plugin

**Comment by hyangah** [comment]
@leolikescoding The nightly extension uses a new debug adapter by default, which I believe is more robust in handling the connection setup. If you want to use the new adapter with the stable version of go plugin, use this setting

```
    "go.delveConfig": {
        "debugAdapter": "dlv-dap",
    }
```

For more details about the features and also limitations, see https://github.com/golang/vscode-go/blob/master/docs/dlv-dap.md#getting-started
