### ISSUE TITLE
UI: support inlay hints  (parameter hints)

### ISSUE THREAD

**Issue by birraasmile** [golang/vscode-go#1631]
Hello vscode-go team,
Can you please try to make the  vscode-go extension support parameter name hints in the upcoming version ? :) 

Example of similar support at the moment is the extension https://marketplace.visualstudio.com/items?itemName=DominicVonk.parameter-hints which started supporting parameter name hints with TypeScript 4.4. 

It would be perfect to see have this feature available through vscode-go extension if the editor has API  for it. thanks

**Comment by stamblerre** [comment]
The language server protocol does not yet have support for this behavior -- see https://github.com/microsoft/language-server-protocol/issues/956.

**Comment by hyangah** [comment]
[The upstream issue (LSP support)](https://github.com/microsoft/language-server-protocol/issues/956) is waiting for the inlayHints VS Code API to be finalized (https://github.com/microsoft/vscode/issues/16221).

**Comment by pepsighan** [comment]
The VS Code API has been finalized: https://github.com/microsoft/vscode/issues/16221#issuecomment-1033827087.

**Comment by Frederick888** [comment]
Is there an issue already at https://github.com/golang/go/issues?

**Comment by hyangah** [comment]
As soon as LSP spec is finalized, we can start working on adding that to `gopls`. 

* LSP spec: https://github.com/microsoft/language-server-protocol/issues/956
* Implement the spec in `gopls`
* Update vscode-go to require VSCode engine 1.65+ to use the new API 
* VS Code Client support: https://github.com/microsoft/vscode-languageserver-node/pull/772
* Update vscode-go to pull in the new VS Code Client support lib

**Comment by li1234yun** [comment]
@hyangah Hi, VSCode 1.65 the inlay hints api was finalized :-)

[VSCode 1.65 Inlay Hints Release Note](https://code.visualstudio.com/updates/v1_65#_inlay-hints)

**Comment by Med-H** [comment]
any news on this feature?

**Comment by jamalc** [comment]
Here is the initial set of inlay hints we plan to support, with configuration to enable or disable them independently. Let us know if there are additional config options or hint types you would like us to consider.

### Parameter Names
Will include configuration for showing hints for only literals and suppressing hints when an argument matches the parameter name.
<img width="355" alt="Screen Shot 2022-06-10 at 1 30 04 PM" src="https://user-images.githubusercontent.com/18269441/173120213-a8961b69-76b5-4953-97b2-dc2f335e032c.png">

### Constant Values
Similar to Enum Member Values for TypeScript inlay hints. Enables hints for sequential values declared using the iota constant generator and implicit repetition.
<img width="331" alt="Screen Shot 2022-06-10 at 1 30 51 PM" src="https://user-images.githubusercontent.com/18269441/173120236-89860d46-2790-4ef3-8398-0f5b6e8bfedd.png">

### Variable Types
<img width="480" alt="Screen Shot 2022-06-10 at 1 30 21 PM" src="https://user-images.githubusercontent.com/18269441/173120251-4fa8e438-a6c1-4d21-a7a9-7b4fc21cfef5.png">

### Composite Literal Field Names
<img width="691" alt="Screen Shot 2022-06-10 at 1 42 57 PM" src="https://user-images.githubusercontent.com/18269441/173122075-1e8de357-7d4d-41eb-99aa-4b4729e5c67f.png">

### Composite Literal Types
<img width="511" alt="Screen Shot 2022-06-10 at 1 32 15 PM" src="https://user-images.githubusercontent.com/18269441/173120353-173df839-5dc6-4fa7-91c3-e8f46f98d42c.png">

**Comment by nengqi** [comment]
> Here is the initial set of inlay hints we plan to support, with configuration to enable or disable them independently. Let us know if there are additional config options or hint types you would like us to consider.
> 
> ### Parameter Names
> Will include configuration for showing hints for only literals and suppressing hints when an argument matches the parameter name. <img alt="Screen Shot 2022-06-10 at 1 30 04 PM" width="355" src="https://user-images.githubusercontent.com/18269441/173120213-a8961b69-76b5-4953-97b2-dc2f335e032c.png">
> 
> ### Constant Values
> Similar to Enum Member Values for TypeScript inlay hints. Enables hints for sequential values declared using the iota constant generator and implicit repetition. <img alt="Screen Shot 2022-06-10 at 1 30 51 PM" width="331" src="https://user-images.githubusercontent.com/18269441/173120236-89860d46-2790-4ef3-8398-0f5b6e8bfedd.png">
> 
> ### Variable Types
> <img alt="Screen Shot 2022-06-10 at 1 30 21 PM" width="480" src="https://user-images.githubusercontent.com/18269441/173120251-4fa8e438-a6c1-4d21-a7a9-7b4fc21cfef5.png">
> 
> ### Composite Literal Field Names
> <img alt="Screen Shot 2022-06-10 at 1 42 57 PM" width="691" src="https://user-images.githubusercontent.com/18269441/173122075-1e8de357-7d4d-41eb-99aa-4b4729e5c67f.png">
> 
> ### Composite Literal Types
> <img alt="Screen Shot 2022-06-10 at 1 32 15 PM" width="511" src="https://user-images.githubusercontent.com/18269441/173120353-173df839-5dc6-4fa7-91c3-e8f46f98d42c.png">

When can we use it in vscode Go extension or Go Nightly

**Comment by hyangah** [comment]
From @zombiezen:
>The Rust language server has a nice subtle touch where if the parameter name matches the argument variable given, it skips showing the inlay. 

It looks like Javascript/Typescript have similars, e.g. `javascript.inlayHints.parameterNames.suppressWhenArgumentMatchesName`

**Comment by n-r-w** [comment]
> I saw a release notes for support of inlay hints, but at least in my case that seems to not work

same issue

**Comment by jamalc** [comment]
The go.* params work in vscode-go nightly and configuration will be available in the UI.

**Comment by hyangah** [comment]
v0.35.0 released today has dedicated settings for inlay hints. Please use `go.inlayHints.*` settings or use the VSCode settings UI instead of `"gopls": { "hints": ... }`. 

https://twitter.com/golang/status/1549106172870987776
