### ISSUE TITLE
Add extension to Open VSIX Repo

### ISSUE THREAD

**Issue by clin1234** [golang/vscode-go#1635]
**Is your feature request related to a problem? Please describe.**
Extension not available for VSCodium, which uses Open VSIX Repo be default.

**Describe the solution you'd like**
Add the extension to Open VSIX.

**Describe alternatives you've considered**
I cannot use VS Code, because of the license of the installers, and I could not be bothered compiling VS Code from scratch.

**Comment by findleyr** [comment]
Hi, I'm not sure if we can do this but we'll discuss in our triage meeting.

To be clear, you mean open-vsx.org, right? (not to be confused with vsixgallery.com, which is the first google result for 'Open VSIX'?)

**Comment by clin1234** [comment]
Yes

**Comment by hyangah** [comment]
https://open-vsx.org/extension/golang/Go We are already there.

This is a duplicate of https://github.com/golang/vscode-go/issues/1177 and https://github.com/golang/vscode-go/issues/222
In our prior discussion, we decided not to publish it ourselves, but let open-vsx keep publishing the extension by scraping .vsix files included in our github release page.

cc @jankeromnes

**Comment by findleyr** [comment]
Closing, as this appears to already be done.

@clin1234, please re-open or create a new issue if there is a reason the current VSIX is not working for you.
