### ISSUE TITLE
MacOS VSCode wrong default gopath

### ISSUE THREAD

**Issue by tseyt** [golang/vscode-go#1639]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.6 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.58.2
c3f126316369cd610563c75b1b1725e0679adfb3
arm64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.26.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/tseyt/go
GOROOT: /usr/local/go
PATH: /Users/tseyt/.nvm/versions/node/v14.17.0/bin:/opt/homebrew/bin:/usr/local/bin:/Users/tseyt/desktop/projects/work/clsdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/tseyt/.cargo/bin

   gopkgs: gopkgs not installed
   go-outline: go-outline not installed
   gotests: gotests not installed
   gomodifytags: gomodifytags not installed
   impl: impl not installed
   goplay: goplay not installed
   dlv: dlv not installed
   dlv-dap: dlv-dap not installed
   staticcheck: staticcheck not installed
   gopls: /Users/tseyt/go/bin/gopls installed

go env
Workspace Folder (dfuse-eosio): /Users/tseyt/Desktop/Projects/dfuse-eosio
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/tseyt/Library/Caches/go-build"
	GOENV="/Users/tseyt/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/tseyt/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/tseyt/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.16.6"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/tseyt/Desktop/Projects/dfuse-eosio/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/90/0m35v3295x7_c7q2074zlfnr0000gn/T/go-build416257726=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

N/A

### Describe the bug
A clear and concise description of what the bug.

Installed vscode-go extension on MacOS VSCode. Default $GOPATH=`/Users/**username**/go` and $GOROOT=`/usr/local/go`.
It is strange because go is installed at `/usr/local/go` by default on Mac, so I'm not sure why it is installing anything to `/Users/**username**/go`.
This also interferes with installation of certain repos, the one I was trying to install was https://github.com/dfuse-io/dfuse-eosio, where files are being downloaded to `/Users/*username*/go` instead of `/usr/local/go`.
There is also an error thrown when changing GOPATH, where if GOPATH == GOROOT a stderr is thrown saying they cannot be equal.

### Steps to reproduce the behavior:
1. Install Golang extension on macos
2. gopls is installed to `/Users/*username*/go` instead of at `/usr/local/go` where it is installed by default.
3. Everything should just be in `/usr/local/go` folder, there should be no `/Users/**username**/go` folder.

**Comment by findleyr** [comment]
Hi, I'm not sure I understand. Why do you expect Go binaries to be downloaded to `/usr/local/go`, when GOPATH is is `/Users/**username**/go`? See the output of `go env` above. This is not really related to vscode-go: this is the behavior of the Go command (see `go help gopath`).

**Comment by firelizzard18** [comment]
@tseyt This is the default behavior of Go. It is not specific to the VSCode extension. `GOROOT` is where the Go stdlib and binaries are installed. `GOPATH` is the user-specific location where 3rd party packages and binaries are installed. Go requires these to be different.

> instead of at `/usr/local/go` where it is installed by default.

Under what circumstances is it installed there? I have never seen Go install anything within `/usr/local/go` other than the stdlib and main binaries.

> Everything should just be in `/usr/local/go` folder

That's not how Go works.

> there should be no `/Users/**username**/go` folder.

You can change that to something else (`go env -w GOPATH /something/else`), but it should be user-specific, or you'll probably get permissions issues if any other user uses the same GOPATH.
