### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by kamit28** [golang/vscode-go#1664]
gopls version: v0.1.7
gopls flags: 
update flags: proxy
extension version: 0.26.0
go version: 1.16.6
environment: Visual Studio Code darwin
initialization error: Error: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, your gopls version is very out of date (we just released v0.7.1), and may not support recent LSP additions, could you please update?
https://github.com/golang/tools/tree/master/gopls#installation

Thanks. Closing as this should be fixed by updating gopls.
