### ISSUE TITLE
Saving Go file hangs

### ISSUE THREAD

**Issue by NanYiGit** [golang/vscode-go#1675]
Issue Type: <b>Bug</b>

The problem is not necessarily present.
When I save main.go, the progress bar in the bottom right corner prompts me `Is saving "main.go": Get code actions from "'Go'" (configure). '

Extension version: 0.26.0
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (8.82GB free)|
|Process Argv|--crash-reporter-id d430f946-ac50-46d2-9742-fcd331d5aaab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473
bridge0723:30346310

```

</details>

**Comment by NanYiGit** [comment]
I am using `go mod` mode

**Comment by stamblerre** [comment]
Can you please check your other installed extensions and see if disabling them helps? Go Group Imports, Spell Right, and Go Test Explorer have both been identified as causing slow saves.

Also, can you please share your `gopls` logs? Information on how to capture them can be found [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).
