### ISSUE TITLE
debug: auto-resume execution after setting breakpoints

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#1676]
When debugging, users often want to modify / add breakpoints after starting the session which often means this happens while the program is already running.

The debugger should stop the program to set the breakpoints and resume execution after.

The legacy adapter attempts to implement this, but runs into issues if a next request is interrupted, skipping the step entirely.

Delve's native DAP implementation attempts to solve this problem by stopping the program to set the breakpoints, but does not automatically resume it.

It was previously considered to add auto resume in go-delve/delve#2472, but was determined to be too complicated at the time. Much of this extra complexity is required for log points as well, so this is something that seems more reasonable to add now. This behavior of stopping the program is also confusing behavior to the user, as it can be difficult to spot in the UI if you are not expecting it.

**Comment by polinasok** [comment]
Is this not a duplicate of https://github.com/golang/vscode-go/issues/1648 (which, I guess, could be renamed better)?

**Comment by suzmue** [comment]
This is available at tip in delve, and will be included in the next release.
