### ISSUE TITLE
debug: UI to examine core dumps

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#168]
From https://github.com/microsoft/vscode-go/issues/3169

@lggomez has pending PR(golang/vscode-go#89) to implement this feature.
With example configuration:
> ```
>{
>             "name": "core:Launch",
>             "debugServer": 4711,
>             "type": "go",
>             "request": "launch",
>             "mode": "core",
>             "program": "${workspaceRoot}/main/main.go",
>             "env": {},
>             "args": [],
>             "dlvLoadConfig": {
>                 "followPointers": true,
>                 "maxVariableRecurse": 1,
>                 "maxStringLen": 5,
>                 "maxArrayValues": 5,
>                 "maxStructFields": -1
>             },
>             "backend": "coredump",
>             "executable": "${workspaceRoot}/main/helloworldmodules",
>             "coreDumpDirectory": "pathtodump...",
>             "trace": "verbose"
>         },
>```

**Comment by marco-m-pix4d** [comment]
Hello @hyangah, I am an happy user of vscode-go. I would like to ask to reconsider the priority of this feature, I think it would be quite useful. Thanks for all the work of the vscode-go team :-)

**Comment by polinasok** [comment]
This feature is now available using the following in your `launch.json`
```
"request": "launch",
"mode": "core",
"program":"path/to/executable",
"coreFilePath":"path/to/coredump",
```

@marco-m-pix4d Please let us know if it is not working for you. Thank you.

**Comment by marco-m-pix4d** [comment]
Hello @polinasok, @lggomez,
I confirm that this works fine, thanks a lot! :-)
Tested on Arch Linux, Go 1.17, vscode 1.60.0, delve 1.7.1.
