### ISSUE TITLE
dlv-dap could not Stop Process nor delete __debug_bin file in "start without debugging" mode

### ISSUE THREAD

**Issue by crazytaxi824** [golang/vscode-go#1687]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.16.7
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.7.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.59.0
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.27.0

### Share the Go related settings you have added/edited
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Auto Main",
      "type": "go",
      "request": "launch",
      "mode": "auto",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/src",
      "internalConsoleOptions": "openOnSessionStart",
      "trace": "verbose",
      "logOutput": "rpc,debugger,dap",
      "showLog": true
    }
  ]
}
```

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
"go.useLanguageServer": true,

"gopls": {
  "usePlaceholders": true,
  "staticcheck": false
},

"go.languageServerFlags": [
    "-rpc.trace",
    "serve",
    "--debug=localhost:16060"
],
```

### Describe the bug

The program is a simple HTTP service. 

1. When I use "Start Debugging" - (F5 in vscode) it's all good. no problem at all.

2. When I use "Start Without Debugging" - (control+F5), the program will run. But After I click the Stop button (shift+F5), debugging control panel disappears, but the program is still running, and `__debug_bin` file is not deleted.

**Comment by polinasok** [comment]
I can reproduce this. It's a bug. We block the request loop waiting for the program to terminate in `onLaunchRequest`, which means we do not receive and process the disconnect request.

**Comment by polinasok** [comment]
The fix has been checked into delve's master. @hyangah, should we wait for the pinned version in VS Code to be updated to mark this issue fixed?

**Comment by hyangah** [comment]
v0.27.2 is released. `Go: Install/Update Tools` -> choose `dlv-dap` to pick up the fixed version of delve if you haven't updated it already. Thanks!
