### ISSUE TITLE
request: please keep the engine at 1.58

### ISSUE THREAD

**Issue by OneOfOne** [golang/vscode-go#1688]
This is related to https://github.com/microsoft/vscode/issues/130457

A lot of us are hardlocking vscode to v1.58.x until we find an alternative, so would it be possible to use the 1.58 engine in package.json until there's a strong reason to switch to 1.59?

**Comment by hyangah** [comment]
Thanks for the info @OneOfOne 
I thought VS Code users still could use v0.27.1 and marketplace would suggest only compatible versions of the extension. Is it not the case?

We wanted 1.59 to use the new test explorer API in the next release. @firelizzard18 Is it possible to have the extension still require 1.58, and enable the test explorer feature (and use of the new API) **only if** the api is available (i.e. user is using 1.59 or newer)?

**UPDATE**: I just tested with Go nightly, and it suggested 2021.8.619 version which is the last go nightly built with the ^1.52.0 engine requirement.

**Comment by firelizzard18** [comment]
@hyangah I added a commit to bump the engine back to 1.58 and hide the test controller registration behind a check. I think that should do it.

**Comment by firelizzard18** [comment]
> [golang.go]: testing/item/context is a proposed menu identifier and is only available when running out of dev or with the following command line switch: --enable-proposed-api golang.

The testing menu contribution blocks the extension from loading on 1.58.

**Comment by hyangah** [comment]
Thanks @firelizzard18 for investigating and filing the issue upstream. 
It's unfortunate but I am voting to switch to 1.59 at least in nightly, and let users of vscode 1.58 keep using v0.27.1 or earlier versions.

**Comment by hyangah** [comment]
I will leave this issue open - we will reevaluate this decision during v0.28.0 release.

**Comment by OneOfOne** [comment]
Understandable, thank you for looking into it.

**Comment by hyangah** [comment]
Noted the requirement in the change log. 
Sorry that the vscode issues didn't go in the direction we wanted. I hope that v0.28.2 does not have critical issues and remains usable for users who can't upgrade.
