### ISSUE TITLE
test/integration: Installation Tests are flaky

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#169]
1 failing
  1) Installation Tests
       install tools:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/travis/gopath/src/github.com/hyangah/vscode-go/out/test/integration/install.test.js)
  	at listOnTimeout (internal/timers.js:531:17)
  	at processTimers (internal/timers.js:475:7)
Error: 1 tests failed.
Error: 1 tests failed.

https://travis-ci.org/github/hyangah/vscode-go/jobs/694401146

**Comment by stamblerre** [comment]
I wonder if the tests are just slow or actually failing. I think https://go-review.googlesource.com/c/vscode-go/+/236058 might be able to help with diagnosing that.

**Comment by hyangah** [comment]
I don't see any flakiness from this test. Closing.
