### ISSUE TITLE
Detailed code coverage and benchmarking support for golang

### ISSUE THREAD

**Issue by Ankush-Goyal** [golang/vscode-go#1690]
**Is your feature request related to a problem? Please describe.**

Can we implement a formal way of viewing code coverage like a gutter, highlight based and also percentage based for files. 

**Describe the solution you'd like**
Gutter: it shows the lines of code covered by test cases on the left side similar to where debug points are shown

Highlight: shows the actual lines highlighted as different color codes

Percentage: shows a tabular format in percentages for folder as well as file level. Somewhat similar to how goland has done it.

**Additional context**
Goland supports a great ui for ease of testing. Just selecting option and it fires of the coverage. It would be great if we can get a similar feature in place. 

Note: As per my research, vs code doesn't have something similar. Correct me if I am wrong and would help if you can provide a documentation or useful tutorial for it

**Comment by hyangah** [comment]
@Ankush-Goyal I am not sure about Percentage info yet, but Coverage info visulaization using Gutter/Highlight is already available. See https://github.com/golang/vscode-go/blob/master/docs/features.md#code-coverage and `type` of https://github.com/golang/vscode-go/blob/master/docs/settings.md#gocoveragedecorator.
If the current feature is insufficient, can you show the screenshot of goland vs vscode, and repro case?

cc @pjweinb

**Comment by Ankush-Goyal** [comment]
@hyangah I created a small even odd program to show the usecase. Attaching the screenshot below for UI difference between goland and VScode. The current interface on vscode is like a terminal based detailing for test. Goland provides a user interface which is easily navigable for different type of use cases such as test, profiling etc. 
![Screenshot from 2021-08-18 07-19-11](https://user-images.githubusercontent.com/15044010/129826543-d93397d9-db1e-4b23-8d5e-accc945c682c.png)
![Screenshot from 2021-08-18 07-23-51](https://user-images.githubusercontent.com/15044010/129826545-88ed4537-7571-4f18-9a61-5b22645b4dae.png)
![Screenshot from 2021-08-18 07-34-28](https://user-images.githubusercontent.com/15044010/129826546-718ee444-7a3e-4240-82c2-fcf192985f0d.png)
![Screenshot from 2021-08-18 07-41-34](https://user-images.githubusercontent.com/15044010/129826550-035e0287-c5ad-4f26-ae58-438bf4c71bee.png)
![Screenshot from 2021-08-18 07-49-11](https://user-images.githubusercontent.com/15044010/129826552-7ed4fbcb-6b52-45e3-958a-c95c715d9386.png)
![Screenshot from 2021-08-18 07-49-13](https://user-images.githubusercontent.com/15044010/129826555-7b99a91a-bc3b-4da5-9ca3-55e17be6fbb1.png)
![Screenshot from 2021-08-18 07-49-17](https://user-images.githubusercontent.com/15044010/129826556-0076007e-0fb5-43e3-90b9-fc279d6bdc31.png)
![Screenshot from 2021-08-18 07-49-29](https://user-images.githubusercontent.com/15044010/129826559-ed60b2c3-6e61-4066-8631-e6c23990c0e3.png)
![Screenshot from 2021-08-18 07-49-32](https://user-images.githubusercontent.com/15044010/129826563-824150a9-9b65-4875-8dc0-7b72dca0876f.png)

Getting this implemented will improve user experience for golang developers.

**Comment by hyangah** [comment]
Thanks. It looks like you want CPU profile support (maybe https://github.com/golang/vscode-go/issues/1685 is the duplicate?)

For gutter-style code coverage presentation, try https://github.com/golang/vscode-go/blob/master/docs/settings.md#gocoveragedecorator

**Comment by firelizzard18** [comment]
FYI, VSCode is adding support for coverage to the testing API. See https://github.com/microsoft/vscode/issues/123713 for details on the proposed API.

**Comment by Ankush-Goyal** [comment]
@hyangah CPU profile support is one part to it. Benchmarking, testing race condition, Memory profiling, flamegraph these are some of the extra pointers I can say,. Still I would say Testing, Benchmarking, Memory and CPU profiling should be given importance for starters.

**Comment by firelizzard18** [comment]
@Ankush-Goyal That is a very broad request; in Atlassian's terminology, I would call this an [epic](https://www.atlassian.com/agile/project-management/epics). If you break this down into multiple issues, one per feature ([user stories](https://www.atlassian.com/agile/project-management/user-stories)), it would be much easier to address.

**Comment by hyangah** [comment]
Closing. Thanks for sharing ideas. @Ankush-Goyal 
As @firelizzard18 advised, please create specific issues.
