### ISSUE TITLE
check dlv-dap requires 1.15+

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1692]
In https://stackoverflow.com/questions/68753251/couldnt-start-dlv-dap, https://github.com/golang/vscode-go/issues/1686#issuecomment-898303655 and #1716, users report dlv-dap mode does not work with go versions earlier than 1.15. 
Delve DAP is slightly newer than Delve 1.7.0, and Delve 1.7.0 [dropped the official support on go1.14](https://github.com/go-delve/delve/blob/master/CHANGELOG.md#170-2021-07-19), but  strictly speaking, go1.17 is not officially out when vscode 0.27.0 was released, so not supporting 1.14 was sudden. We need to understand what's not working with 1.14 and also document the version compatibility.

cc @suzmue @polinasok

**Comment by polinasok** [comment]
We can use dlv with `--check-go-version` off.

**Comment by luojiego** [comment]
> We can use dlv with `--check-go-version` off.

I can't find where to use this options. Can you tell me? Thanks.

**Comment by polinasok** [comment]
@luojiego Try adding the following to your `launch.json` configuration:
```
"dlvFlags": ["--check-go-version=false"],
```

**Comment by luojiego** [comment]
> @luojiego Try adding the following to your `launch.json` configuration:
> 
> ```
> "dlvFlags": ["--check-go-version=false"],
> ```

![image](https://user-images.githubusercontent.com/3175699/130736583-ddf08f67-5a92-47b0-a77b-80a25733fd09.png)
![image](https://user-images.githubusercontent.com/3175699/130736613-1eeeffc9-c0d5-49aa-a29d-4d86367c98d7.png)
Thanks for your reply, it seems doesnt' work.

**Comment by polinasok** [comment]
It looks like you are adding this setting to `settings.json`, not `launch.json`. Click "Open launch.json" in the error message to get access to individual configuration that you can select from Run And Debug drop-down.

**Comment by luojiego** [comment]
> It looks like you are adding this setting to `settings.json`, not `launch.json`. Click "Open launch.json" in the error message to get access to individual configuration that you can select from Run And Debug drop-down.

Thank you very much!

**Comment by hyangah** [comment]
Duplicate of https://github.com/golang/vscode-go/issues/1692
