### ISSUE TITLE
Debug: couldn't start dlv-dap

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1693]
https://stackoverflow.com/questions/68753251/couldnt-start-dlv-dap

![image](https://user-images.githubusercontent.com/4999471/129466010-78d893c6-9ac7-4a57-b748-7743c1f4c21e.png)

launch.json: 
```
{
"version": "0.2.0",
"configurations": [
    {
        "name": "Launch file",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceFolder}",
        "showLog": true,
        "env": {
            "GO111MODULE": "on"
        }
    }
]
}
```

I suspect the default timeout [(5sec)](https://github.com/golang/vscode-go/blob/ad3a6caec015e635becccaccbb066b6f2ca85c92/src/goDebugFactory.ts#L426) is too short, or some other bug prevented the dlv dap server from starting:

If any of you encountered an issue, can you please try the following command and time how long it takes?

```
$ dlv-dap dap --listen=:12345 --log --log-output=dap
```

**Comment by miao233** [comment]
i have this issue as well

**Comment by miao233** [comment]
> i have this issue as well

i have fixxed it but dlv-dap doesn't work

add this config into "setting.json"

```config
"go.alternateTools": {
    "dlv": "dlv"
    },
    "go.delveConfig": {

        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": false,
        "debugAdapter": "legacy",
        "substitutePath": []
    }
```
but,command "dlv-dap dap --listen=:12345 --log --log-output=dap" doesn't work

**Comment by hyangah** [comment]
@miao233 Please share what you see when you run "dlv-dap dap --listen=:12345 --log --log-output=dap". If you are using windows, find where your dlv-dap.exe is installed and run `dlv-dap.exe dap --listen=:12345 --log --log-output=dap"

**Comment by malaclypse** [comment]
I'm not the original poster, but since I also ran into this issue, I thought I'd comment here to follow. 
I'm on Windows with the latest VSCode and Go, and since I also see this issue (but not all the time), I assume that the 5 second timeout is definitely too short, is there a good reason why it was set to 5 seconds specifically? Is there an easy way to increase it?

The output of the above command is fine, the DAP server starts successfully. 
```
DAP server listening at: [::]:12345
2021-08-16T19:40:49+03:00 debug layer=dap DAP server pid = 24672
```

**Comment by hyangah** [comment]
@malaclypse `5sec` is arbitrarily chosen - the command (dlv dap) does not do anything significant other than starting a tcp server on the given port. Not sure what makes it to take such a long time in reasonably performant development environment. When you ran the command, did it take long time to see the output?

**Comment by momkeller** [comment]
@hyangah, i also run into this  - vs code v1.59, go v1.16.7 - when i run the dlv dap command listed above manually, it takes about 14 seconds.

**Comment by miao233** [comment]
@hyangah i found the problem,cause firewall & safety-critical software had stopped dlv-dap on Windows with the latest VSCode and Go.i think maybe dlv-dap is new for windows? anyway,it work, it takes about 2 seconds.

**Comment by malaclypse** [comment]
@hyangah I see now that if I run start the server in a terminal outside of VSCode it's instantaneous, but it takes between 7 and 9 seconds inside the VSCode terminal, I'm honestly not sure what could be causing the discrepancy. I'm using the Windows Terminal app when outside of VSCode as my terminal, and it doesn't matter if I'm running it in CMD or a Powershell Core session (same for VSCode, in any shell it's much slower).

**Comment by joelddiaz** [comment]
I'm seeing the same thing on VSCode on linux (Fedora 34 FWIW).

![image](https://user-images.githubusercontent.com/4999586/133836195-d904d516-21dc-470d-848a-d0b27c4be3a9.png)

Running `dlv-dap dap --listen=:12345 --log-output=dap --log` is basically instantaneous:
```
[jdiaz@minigoomba ~]$ which dlv-dap
~/.gvm/pkgsets/go1.16.8/global/bin/dlv-dap
[jdiaz@minigoomba ~]$ dlv-dap dap --listen=:12345 --log-output=dap --log
DAP server listening at: [::]:12345
2021-09-17T14:11:46-04:00 debug layer=dap DAP server pid = 40275
```

If I start dlv-dap externally, and point my launch.conf to use the appropriate port `12345`, then starting up the debug session from VSCode just hangs eternally (with no indication of a connection or anything from the log output from the dlv-dap terminal session).

My launch.conf (in case it is helpful):
```json
{
            "name": "CloudCredOperator",
            "type": "go",
            //"debugAdapter": "legacy",
            "request": "launch",
            "mode": "auto",
            "remotePath": "",
            "port": 12345,
            "host": "127.0.0.1",
            "program": "${env:HOME}/projects/cloud-credential-operator/src/github.com/openshift/cloud-credential-operator/cmd/cloud-credential-operator/main.go",
            "env": {
                "KUBECONFIG": "/home/jdiaz/.kube/aws.kubeconfig",
                "CCO_SKIP_LEADER_ELECTION": "yes",
                "RELEASE_VERSION": "NEWTESTVER"
            },
            "args": [
                "operator"//,
                //"--log-level=debug"
            ],
            "showLog": true
        },
```

**Comment by hyangah** [comment]
Is this still an issue?

* We recently removed the use of `dlv-dap`, but started to use `dlv`. That will reduce the chance of firewall or security settings complaining about this unofficial binary `dlv-dap`.
* Another suspect is the use of the file descriptor for `--log-dest` flag when starting the dlv dap server. If that is suspected, please try with "integratedTerminal" or "externalTerminal" as the `console` property in launch.json and report if that helps. That will start the dlv dap server without `--log-dest` arg & file descriptor.

And, other than these,  I am currently out of ideas. :-(

**Comment by hyangah** [comment]
Closing. The dlv-dap path had been default for a while and I don't see much activity here for a few months. 
Please open a new issue if you have issues with the latest versions of the extension & delve, along with the information requested here 
https://github.com/golang/vscode-go/issues/1693#issuecomment-1039651410
