### ISSUE TITLE
Provide a way to disable the "your ... is different than before" messages

### ISSUE THREAD

**Issue by zikaeroh** [golang/vscode-go#1698]
**Is your feature request related to a problem? Please describe.**

I'm working on both the Go toolchain and my own projects. To work in the Go repo, you need to use the version of Go being edited in order for things to work. Every time I open a project, I get a popup that tells me that my Go version has changed and that I should be recompiling my tools. I know that I don't (since I use gopls, and manage my installed tools pretty carefully), so this message doesn't really help me, and I'd like to be able to hide these messages.

**Describe the solution you'd like**

Some sort of option to disable the notification, or any and all of tools checks (as I manage them myself).

**Describe alternatives you've considered**

VS Code doesn't have a way to block the messages for an extension, so that isn't an option, and there's no away around the checks at the moment. I have both:

```
"go.toolsManagement.checkForUpdates": "off",
"go.toolsManagement.autoUpdate": false,
```

But these don't get rid of everything.

**Additional context**

N/A

**Comment by hyangah** [comment]
We found this check is now too inaccurate to be useful.
In v0.28.0, we will remove this check. From cl/349742 description ---

> 
> The existing tool version checks in suggestUpdates simply compare
> the go version & GOROOT/GOPATH used with the tool last time. That is
> a hack added when there was no good way to check tool's exact versions
> and users organize compatible tools using GOPATH.
> 
> Now many of recent tools (e.g. gopls) do not depend on hardcoded
> GOROOT or the go version used while compiling the tools. It's still
> desirable to compile tools with the latest version of go but the
> go version does not have to match exactly with the go version
> used to compile the tools. For example, tools compiled with go1.16
> can be used to work with go1.16.1 or go1.15.
> 
> Now Go is released frequently, and the extension allows users to
> switch between different go versions more easily, this incorrect
> popup is often annoying and confuses users, than helping users
> stay up-to-date with latest tools. Remove this incorrect heuristic
> for now.

**Comment by zikaeroh** [comment]
Thank you!
