### ISSUE TITLE
Switch to esbuild

### ISSUE THREAD

**Issue by firelizzard18** [golang/vscode-go#1705]
Microsoft now recommends using esbuild instead of webpack, for various reasons, including performance: esbuild is considerably faster than webpack. According to [a random benchmark I found](https://blog.logrocket.com/fast-javascript-bundling-with-esbuild/), esbuild is almost two orders of magnitude faster than webpack. I would be happy to submit a CL.

**Comment by hyangah** [comment]
Good idea (most of all, eslint is written in go and has API for go :-P)
Contribution is greatly appreciated!
