### ISSUE TITLE
debug: "Pause on breakpoint" is shown when pausing with "Pause (F6)"

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#172]
Originally reported in https://github.com/microsoft/vscode-go/issues/3158.

When pausing the program with no breakpoints set with Pause F6, I see the UI say "paused on breakpoint" some of the times. I expect to see "paused on pause".
See the analysis @polinasok posted in the original report.
 
This is reproducible with Nightly & Insiders.

**Comment by suzmue** [comment]
Fixed by [cl/253578](https://go-review.googlesource.com/c/vscode-go/+/253578)

**Comment by suzmue** [comment]
This is fixed in the new debug adapter.

We do not intend to fix this in the legacy adapter, as it is very fragile.
