### ISSUE TITLE
We need method to enable golangci-lint for gopls

### ISSUE THREAD

**Issue by eaglexiang** [golang/vscode-go#1737]
**Is your feature request related to a problem? Please describe.**
We need gopls, and we also need golangci-lint. We dont find any way to enable golangci-lint for gopls on vscode.

**Describe the solution you'd like**
a way to configure gopls to enable golangci-lint

**Describe alternatives you've considered**

**Additional context**

**Comment by findleyr** [comment]
Hi, could you clarify why `go.lintTool` does not work for you?
https://github.com/golang/vscode-go/blob/33339e687f2034f80ae3018a79db121c8e04feed/docs/settings.md#golinttool

This is not integrated with gopls, but IIRC should still work.

**Comment by eaglexiang** [comment]
@findleyr 

> This is not integrated with gopls, but IIRC should still work.

Actually I'm not sure it did work or not, because a lot of style-check warning took full of my vscode problems window. You mean golangci-lint set by `go.lintTool` is still keeping working. OK, but how can I disable all code static check of gopls. We dont need them, and they covered the golangci-lint warnings we really need.

**Comment by findleyr** [comment]
> because a lot of style-check warning took full of my vscode problems window

Can you give an example of what type of warning is filling up your vscode problems window? gopls should have a high signal/noise ratio.

It might be that there's a particular analyzer that could be disabled in gopls.

**Comment by butuzov** [comment]
@eaglexiang turn on `golangci-lint` in your config, provide required arguments if needed, reload vscode. (you sill will be able to see other linters). `gopls` does not provide you anything on a top that checks.

```
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [ "--sort-results" ],
```

![image](https://user-images.githubusercontent.com/651824/131608877-48325725-f21d-4f41-bd61-b933a24a1986.png)

**Comment by eaglexiang** [comment]
You are right, gopls didnt break golangci-lint, the problems gopls reported are different. I'm sorry.
