### ISSUE TITLE
Support github codespaces web-based editor

### ISSUE THREAD

**Issue by weingart** [golang/vscode-go#1748]
**Is your feature request related to a problem? Please describe.**
It would be awesome if there was a way to use github codespaces and install the vscode-go extension.
Currently it says: "The 'Go' extension is not available in Visual Studio Code for the Web." I'm unsure what
this all entails, possibly it will be possible to do once I'm approved for Codespaces with containers.

**Describe the solution you'd like**
Ideally there would be a way to install the extension and point it at a running set of API endpoints it needs
to be able to function, without requiring running local binaries.

**Describe alternatives you've considered**
Alternative is to manage the runtimes and containers myself and use remote vscode.

**Additional context**
https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser

**Comment by hyangah** [comment]
@weingart I guess you meant VS Code for Web (web-based editor support), not Codespace.
Go is supported in GitHub Codespaces default dev container - click the green "Code" button and instantiate it.

![Screen Shot 2021-09-04 at 8 01 26 AM](https://user-images.githubusercontent.com/4999471/132093723-62ae9107-f6f3-4d5a-a70b-29cace6c2f18.png)

Or you can extend the container as you want -- see info about Go container https://docs.github.com/en/codespaces

Web-based editor support runs everything in the web browser. Most features this extension provide are coming from external tools (e.g. the `go` command) that depend on local file systems and cannot run in the web browser easily. Do you have any features in mind that can run and are useful in the web browser?

**Comment by stamblerre** [comment]
This is infeasible for us, as it would involve writing a new extension and language server. If there is more interest in this in the future, we may revisit this decision, but for now, we'll close this issue.
