### ISSUE TITLE
Color on open paren does not match close paren

### ISSUE THREAD

**Issue by heaths** [golang/vscode-go#1750]
Issue Type: <b>Bug</b>

With the recent colorization in VSCode of parenthesis, curly braces, etc., I found a problem in the Go extension where a type assertion shows both parens with color unless the type being asserted is a pointer type e.g.,

```go
// This is colored correctly i.e. both parenthesis colors match:
if s, ok := foo.(string) {
}

// Here the open paren is white but the closed paren is colored:
if s, ok := foo.(*string) {
}
```

This may be a VSCode issue, but I'm assuming it's more likely a problem with the language service. Happy to move this otherwise.

Extension version: 0.27.2
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.84-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.73GB free)|
|Process Argv|--crash-reporter-id f626689c-6e32-475a-b31a-7098b21efda7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.84-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2111)|
|Memory (System)|12.42GB (6.47GB free)|
|VM|0%|
</details>

**Comment by findleyr** [comment]
> With the recent colorization in VSCode of parenthesis, curly braces, etc.

I can take a look (though my distribution does not yet have VS Code 1.60...).

Before I do that, do you by any chance have [semantic tokens](https://github.com/golang/vscode-go/blob/master/docs/settings.md#uisemantictokens) enabled?

**Comment by heaths** [comment]
I don't, but this could be a dup of https://github.com/microsoft/vscode/issues/132394 which seems to be a dup of https://github.com/microsoft/vscode/issues/130996.

**Comment by heaths** [comment]
Confirmed. Disabling font ligatures resolved this. Sorry for the noise.

**Comment by findleyr** [comment]
Ah ok. Thanks very much for investigating this!
