### ISSUE TITLE
Github authentication via GitHub Pull Requests and Issues VS Code extension is not working

### ISSUE THREAD

**Issue by jeffkayser2** [golang/vscode-go#1752]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
gopls, built in GOPATH mode master
    gopls, built in GOPATH mode@master
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.60.0
e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff
x64

* Check your installed extensions to get the version of the VS Code Go extension
	- v0.27.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/jeffkayser/go
GOROOT: /home/jeffkayser/sdk/go1.17
PATH: /home/jeffkayser/sdk/go1.17/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jeffkayser/.local/bin:/home/jeffkayser/bin
PATH (vscode launched with): /usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jeffkayser/.local/bin:/home/jeffkayser/bin

	go:	/home/jeffkayser/sdk/go1.17/bin/go: go version go1.17 linux/amd64

	gopkgs:	/home/jeffkayser/go/bin/gopkgs: go1.17
		path	github.com/uudashr/gopkgs/v2/cmd/gopkgs
		mod	github.com/uudashr/gopkgs/v2	v2.1.2	h1:A0+QH6wqNRHORJnxmqfeuBEsK4nYQ7pgcOHhqpqcrpo=
		dep	github.com/karrick/godirwalk	v1.12.0	h1:nkS4xxsjiZMvVlazd0mFyiwD4BR9f3m6LXGhM2TUx3Y=
		dep	github.com/pkg/errors	v0.8.1	h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
	
	go-outline:	/home/jeffkayser/go/bin/go-outline: go1.17
		path	github.com/ramya-rao-a/go-outline
		mod	github.com/ramya-rao-a/go-outline	v0.0.0-20210608161538-9736a4bde949	h1:iaD+iVf9xGfajsJp+zYrg9Lrk6gMJ6/hZHO4cYq5D5o=
		dep	golang.org/x/tools	v0.1.1	h1:wGiQel/hW0NnEkJUk8lbzkX2gFJU6PFxf1v5OlCfuOs=
	
	gotests:	/home/jeffkayser/go/bin/gotests: go1.17
		path	github.com/cweill/gotests/gotests
		mod	github.com/cweill/gotests	v1.6.0	h1:KJx+/p4EweijYzqPb4Y/8umDCip1Cv6hEVyOx0mE9W8=
		dep	golang.org/x/tools	v0.0.0-20191109212701-97ad0ed33101	h1:LCmXVkvpQCDj724eX6irUTPCJP5GelFHxqGSWL2D1R0=
	
	gomodifytags:	/home/jeffkayser/go/bin/gomodifytags: go1.17
		path	github.com/fatih/gomodifytags
		mod	github.com/fatih/gomodifytags	v1.14.0	h1:4D0ZKYMUgY3bvDn2S7TwOJAsgg5o3UhpwDZtkP9FviU=
		dep	github.com/fatih/camelcase	v1.0.0	h1:hxNvNX/xYBp0ovncs8WyWZrOrpBNub/JfaMvbURyft8=
		dep	github.com/fatih/structtag	v1.2.0	h1:/OdNE99OxoI/PqaW/SuSK9uxxT3f/tcSZgon/ssNSx4=
		dep	golang.org/x/tools	v0.0.0-20180824175216-6c1c5e93cdc1	h1:EAPsk8kfGCjxQagrkWjzXlUWe2p3gj5MknO+z2o9GKc=
	
	impl:	/home/jeffkayser/go/bin/impl: go1.17
		path	github.com/josharian/impl
		mod	github.com/josharian/impl	v1.1.0	h1:gafhg1OFVMq46ifdkBa8wp4hlGogjktjjA5h/2j4+2k=
		dep	golang.org/x/mod	v0.2.0	h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
		dep	golang.org/x/tools	v0.0.0-20200522201501-cb1345f3a375	h1:SjQ2+AKWgZLc1xej6WSzL+Dfs5Uyd5xcZH1mGC411IA=
		dep	golang.org/x/xerrors	v0.0.0-20191204190536-9bdfabe68543	h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
	
	goplay:	/home/jeffkayser/go/bin/goplay: go1.17
		path	github.com/haya14busa/goplay/cmd/goplay
		mod	github.com/haya14busa/goplay	v1.0.0	h1:ED4BMrGQ3WH7H3YXrcnWMVzj1xeSepaYTkLh1DtFi/4=
		dep	github.com/skratchdot/open-golang	v0.0.0-20200116055534-eef842397966	h1:JIAuq3EEf9cgbU6AtGPK4CTG3Zf6CKMNqf0MHTggAUA=
	
	dlv:	/home/jeffkayser/go/bin/dlv: go1.17
		path	github.com/go-delve/delve/cmd/dlv
		mod	github.com/go-delve/delve	v1.7.1	h1:RJWK3sLJ/zY25ng6Q9oNsyo5Rmr2PAEWuyFoD1axlbg=
		dep	github.com/cosiner/argv	v0.1.0	h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
		dep	github.com/cpuguy83/go-md2man/v2	v2.0.0	h1:EoUDS0afbrsXAZ9YQ9jdu/mZ2sXgT1/2yyNng4PGlyM=
		dep	github.com/derekparker/trie	v0.0.0-20200317170641-1fdf38b7b0e9	h1:G765iDCq7bP5opdrPkXk+4V3yfkgV9iGFuheWZ/X/zY=
		dep	github.com/google/go-dap	v0.5.0	h1:RMHAVn5xeunBakYk65ggHXttk6qjZVdbmi+xhAoL2wY=
		dep	github.com/hashicorp/golang-lru	v0.5.4	h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
		dep	github.com/mattn/go-isatty	v0.0.3	h1:ns/ykhmWi7G9O+8a448SecJU3nSMBXJfqQkl0upE1jI=
		dep	github.com/peterh/liner	v0.0.0-20170317030525-88609521dc4b	h1:8uaXtUkxiy+T/zdLWuxa/PG4so0TPZDZfafFNNSaptE=
		dep	github.com/russross/blackfriday/v2	v2.0.1	h1:lPqVAte+HuHNfhJ/0LC98ESWRz8afy9tM/0RK8m9o+Q=
		dep	github.com/shurcooL/sanitized_anchor_name	v1.0.0	h1:PdmoCO6wvbs+7yrJyMORt4/BmY5IYyJwS/kOiWx8mHo=
		dep	github.com/sirupsen/logrus	v1.6.0	h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
		dep	github.com/spf13/cobra	v1.1.3	h1:xghbfqPkxzxP3C/f3n5DdpAbdKLj4ZE4BWQI362l53M=
		dep	github.com/spf13/pflag	v1.0.5	h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
		dep	go.starlark.net	v0.0.0-20200821142938-949cc6f4b097	h1:YiRMXXgG+Pg26t1fjq+iAjaauKWMC9cmGFrtOEuwDDg=
		dep	golang.org/x/arch	v0.0.0-20190927153633-4e8777c89be4	h1:QlVATYS7JBoZMVaf+cNjb90WD/beKVHnIxFKT4QaHVI=
		dep	golang.org/x/sys	v0.0.0-20210514084401-e8d321eab015	h1:hZR0X1kPW+nwyJ9xRxqZk1vx5RUObAPBdKVvXPDUH/E=
		dep	gopkg.in/yaml.v2	v2.4.0	h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=
	
	dlv-dap:	/home/jeffkayser/go/bin/dlv-dap: go1.17
		path	github.com/go-delve/delve/cmd/dlv
		mod	github.com/go-delve/delve	v1.7.2-0.20210901173137-5d158820f694	h1:f/XCbNT7y8/N9XJ4lgwGsBJU+Cx1BMCpj0Qt/F+XH5E=
		dep	github.com/cosiner/argv	v0.1.0	h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
		dep	github.com/cpuguy83/go-md2man/v2	v2.0.0	h1:EoUDS0afbrsXAZ9YQ9jdu/mZ2sXgT1/2yyNng4PGlyM=
		dep	github.com/derekparker/trie	v0.0.0-20200317170641-1fdf38b7b0e9	h1:G765iDCq7bP5opdrPkXk+4V3yfkgV9iGFuheWZ/X/zY=
		dep	github.com/google/go-dap	v0.5.1-0.20210713061233-c91b005e3987	h1:aghNk+kvabZ5I1OC3cNHWvfZ8svcoDLAGyKYimqyGVk=
		dep	github.com/hashicorp/golang-lru	v0.5.4	h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
		dep	github.com/mattn/go-isatty	v0.0.3	h1:ns/ykhmWi7G9O+8a448SecJU3nSMBXJfqQkl0upE1jI=
		dep	github.com/peterh/liner	v0.0.0-20170317030525-88609521dc4b	h1:8uaXtUkxiy+T/zdLWuxa/PG4so0TPZDZfafFNNSaptE=
		dep	github.com/russross/blackfriday/v2	v2.0.1	h1:lPqVAte+HuHNfhJ/0LC98ESWRz8afy9tM/0RK8m9o+Q=
		dep	github.com/shurcooL/sanitized_anchor_name	v1.0.0	h1:PdmoCO6wvbs+7yrJyMORt4/BmY5IYyJwS/kOiWx8mHo=
		dep	github.com/sirupsen/logrus	v1.6.0	h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
		dep	github.com/spf13/cobra	v1.1.3	h1:xghbfqPkxzxP3C/f3n5DdpAbdKLj4ZE4BWQI362l53M=
		dep	github.com/spf13/pflag	v1.0.5	h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
		dep	go.starlark.net	v0.0.0-20200821142938-949cc6f4b097	h1:YiRMXXgG+Pg26t1fjq+iAjaauKWMC9cmGFrtOEuwDDg=
		dep	golang.org/x/arch	v0.0.0-20190927153633-4e8777c89be4	h1:QlVATYS7JBoZMVaf+cNjb90WD/beKVHnIxFKT4QaHVI=
		dep	golang.org/x/sys	v0.0.0-20210514084401-e8d321eab015	h1:hZR0X1kPW+nwyJ9xRxqZk1vx5RUObAPBdKVvXPDUH/E=
		dep	gopkg.in/yaml.v2	v2.4.0	h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=
	
	staticcheck:	/home/jeffkayser/go/bin/staticcheck: go1.17
		path	honnef.co/go/tools/cmd/staticcheck
		mod	honnef.co/go/tools	v0.2.1	h1:/EPr//+UMMXwMTkXvCCoaJDq8cpjMO80Ou+L4PDo2mY=
		dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
		dep	golang.org/x/mod	v0.3.0	h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
		dep	golang.org/x/sys	v0.0.0-20210119212857-b64e53b001e4	h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
		dep	golang.org/x/tools	v0.1.0	h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=
		dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
	
	gopls:	/home/jeffkayser/go/bin/gopls: go1.17
		path	golang.org/x/tools/gopls
		mod	golang.org/x/tools/gopls	v0.7.1	h1:Mh3Z8Xcoq3Zy7ksSlwDV/nzQSbjFf06A+L+F8YHq55U=
		dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
		dep	github.com/google/go-cmp	v0.5.5	h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
		dep	github.com/sergi/go-diff	v1.1.0	h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
		dep	golang.org/x/mod	v0.4.2	h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
		dep	golang.org/x/sync	v0.0.0-20210220032951-036812b2e83c	h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
		dep	golang.org/x/sys	v0.0.0-20210510120138-977fb7262007	h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
		dep	golang.org/x/tools	v0.1.6-0.20210802203754-9b21a8868e16	h1:ZC/gVBZl8poJyKzWLxxlsmhayVGosF4mohR35szD5Bg=
		dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
		dep	honnef.co/go/tools	v0.2.0	h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
		dep	mvdan.cc/gofumpt	v0.1.1	h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
		dep	mvdan.cc/xurls/v2	v2.2.0	h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
	

go env
Workspace Folder (bipub): /home/jeffkayser/projects/jkayser/bipub
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/jeffkayser/.cache/go-build"
	GOENV="/home/jeffkayser/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/jeffkayser/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/jeffkayser/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/home/jeffkayser/sdk/go1.17"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/home/jeffkayser/sdk/go1.17/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.17"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1804265367=/tmp/go-build -gno-record-gcc-switches"
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

{
    "go.testFlags": [
        "-v"
    ],
    "git.autofetch": true,
    "go.alternateTools": {
    
    }
}

### Describe the bug
A clear and concise description of what the bug.

Using a private github repository.
Github authentication provided by browser (Firefox) and VS Code extension: GitHub Pull Requests and Issues

The GitHub Pull Requests and Issues extension has an option to provide github authentication to other VS Code extensions, but it only lists extensions related to git.  The Go extension was not a choice, or I would have added it.

Add an import to code:

	"github.com/jeffkayser2/jibe_general_ValueCache/ValueCache"

UI shows issue:

could not import github.com/jeffkayser2/jibe_general_ValueCache/ValueCache (no required module provides package "github.com/jeffkayser2/jibe_general_ValueCache/ValueCache")

go mod tidy:

[Error - 6:19:02 AM] 2021/09/07 06:19:02 github.com/jeffkayser2/bipub: no dep handle for github.com/jeffkayser2/jibe_general_ValueCache/ValueCache: no metadata for github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
	snapshot=354

[Error - 6:19:02 AM] 2021/09/07 06:19:02 tidy: diagnosing file:///home/jeffkayser/projects/jkayser/bipub/dm/go.mod: err: exit status 1: stderr: go: finding module for package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
github.com/jeffkayser2/bipub imports
	github.com/jeffkayser2/jibe_general_ValueCache/ValueCache: cannot find module providing package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache: module lookup disabled by GOPROXY=off

[Error - 6:19:04 AM] 2021/09/07 06:19:04 github.com/jeffkayser2/bipub: no dep handle for github.com/jeffkayser2/jibe_general_ValueCache/ValueCache: no metadata for github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
	snapshot=355

[Error - 6:19:05 AM] 2021/09/07 06:19:05 tidy: diagnosing file:///home/jeffkayser/projects/jkayser/bipub/dm/go.mod: err: exit status 1: stderr: go: finding module for package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
github.com/jeffkayser2/bipub imports
	github.com/jeffkayser2/jibe_general_ValueCache/ValueCache: cannot find module providing package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache: module lookup disabled by GOPROXY=off

[Error - 6:19:26 AM] 2021/09/07 06:19:26 DocumentSymbols failed: getting file for DocumentSymbols: no packages for non-Go file file:///home/jeffkayser/projects/jkayser/bipub/dm/go.mod
	URI=file:///home/jeffkayser/projects/jkayser/bipub/dm/go.mod

[Info  - 6:19:32 AM] 2021/09/07 06:19:32 background imports cache refresh starting

[Info  - 6:19:32 AM] 2021/09/07 06:19:32 background refresh finished after 30.917797ms

[Error - 6:19:36 AM] Request workspace/executeCommand failed.
  Message: err: exit status 1: stderr: go: finding module for package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: verifying module: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: reading https://sum.golang.org/lookup/github.com/jeffkayser2/jibe_general_!value!cache@v1.0.4: 410 Gone
	server response:
	not found: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/f0dca2a3f72c130ca598ebabeb973421825e033543e093cb5a4c0bd8c9dbdfbe: exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled
	Confirm the import path was entered correctly.
	If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

  Code: 0 
[Error - 6:19:36 AM] 2021/09/07 06:19:36 command error: err: exit status 1: stderr: go: finding module for package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: verifying module: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: reading https://sum.golang.org/lookup/github.com/jeffkayser2/jibe_general_!value!cache@v1.0.4: 410 Gone
	server response:
	not found: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/f0dca2a3f72c130ca598ebabeb973421825e033543e093cb5a4c0bd8c9dbdfbe: exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled
	Confirm the import path was entered correctly.
	If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

[Error - 6:19:39 AM] Request workspace/executeCommand failed.
  Message: err: exit status 1: stderr: go: finding module for package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: verifying module: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: reading https://sum.golang.org/lookup/github.com/jeffkayser2/jibe_general_!value!cache@v1.0.4: 410 Gone
	server response:
	not found: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/f0dca2a3f72c130ca598ebabeb973421825e033543e093cb5a4c0bd8c9dbdfbe: exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled
	Confirm the import path was entered correctly.
	If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

  Code: 0 
[Error - 6:19:39 AM] 2021/09/07 06:19:39 command error: err: exit status 1: stderr: go: finding module for package github.com/jeffkayser2/jibe_general_ValueCache/ValueCache
github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: verifying module: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: reading https://sum.golang.org/lookup/github.com/jeffkayser2/jibe_general_!value!cache@v1.0.4: 410 Gone
	server response:
	not found: github.com/jeffkayser2/jibe_general_ValueCache@v1.0.4: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/f0dca2a3f72c130ca598ebabeb973421825e033543e093cb5a4c0bd8c9dbdfbe: exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled
	Confirm the import path was entered correctly.
	If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

[jeffkayser@localhost ValueCache]$ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)
[jeffkayser@localhost ValueCache]$ uname -a
Linux localhost.localdomain 5.13.13-200.fc34.x86_64 #1 SMP Thu Aug 26 17:06:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[jeffkayser@localhost ValueCache]$ 

I was expecting it to pull the code from GitHub.

### Steps to reproduce the behavior:

Explorer => Open go.mod file.

Run go mod tidy

3. See error

Shown above.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by findleyr** [comment]
Hi, thanks for the report.

Are you able to `go build` your project from the command line? After doing so, do you still get these errors from gopls?

**Comment by jeffkayser2** [comment]
No.  I've only been able to figure out how to do the web-based github authentication from within VS Code.  It's a real pain.  Ever since I converted to it (fairly recently due to procrastination), I've only been able to do git inside VS Code.  I guess I should just switch to SSH authentication.  I was hoping to avoid that.

**Comment by findleyr** [comment]
I'm not familiar with web-based github authentication, but the long and the short of it is that `gopls` runs the `go` gommand. If you cannot `go build` your project you will almost certainly get similar errors in gopls.

Out of curiosity, have you tried building with `GOPROXY=direct`?

**Comment by jeffkayser2** [comment]
Web-based github authentication: you login to github with your normal username/password, then it github prompts for 6-digit key from an authenticator app (I use the MS authenticator app).  It's the new (to me) MFA for github.

No, I haven't tried GOPROXY=direct.  Trying...

**Comment by jeffkayser2** [comment]
GOPROXY=direct didn't help.  Same error message.

**Comment by hyangah** [comment]
I am not familiar with this either.  @jeffkayser2 are you suggesting `$HOME/.netrc` solution described in https://golang.org/doc/faq#git_https ( + `GOPRIVATE` settings) does not work for you? 

`gopls` uses the `go` command line tool underneath. I don't know what's the best way to integrate web-based github authentication with the go command. cc @bcmills who worked on the go command's interaction with private repositories.

**Comment by jeffkayser2** [comment]
Got it.  Used https://github.com/cli/cli/releases/tag/v2.0.0 tool to authenticate.  At the command line, "gh auth login".  Now I can use git from the command line.  Go an error with "go mod tidy" due to version discrepancy (CLI uses go 1.16.6, which is the default install from Fedora 34, VS Code allows you to choose, and I chose 1.17).  Modify go.mod to specify go version 1.16, ran "go mod tidy" from CLI, worked OK, pulled in referenced code.  Logged out of VS code, logged back in (to inherit whatever the "gh" tool did to the environment.  Works within VS Code now.

Thanks for humoring me.  You can close the issue.  Would be good to get some instructions for how Go devs can use web-based authentication for github (and anything that uses git, like go).

**Comment by findleyr** [comment]
Thanks, closing the issue.

This is mostly out-of-scope for vscode, though if it is a frequent issue perhaps we could add it to a FAQ. @bcmills might know if this comes up frequently for the Go command.
