### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by ReneKroon** [golang/vscode-go#1753]
gopls version: v0.6.1
gopls flags: 
update flags: proxy
extension version: 0.27.2
go version: 1.17
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, your gopls is out of date. Instructions for how to update it can be found here:
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#update-tools

See #1300 for more details.

**Comment by ReneKroon** [comment]
Yes I had some issue related to GOPROXY setting, but can't reproduce at this time.
