### ISSUE TITLE
Setting to remove pkg.go.dev link from tooltip

### ISSUE THREAD

**Issue by jsgoupil** [golang/vscode-go#1755]
**Is your feature request related to a problem? Please describe.**
The link showing here:
![image](https://user-images.githubusercontent.com/808649/132414596-0ccf53af-e630-4896-b0dd-5fe040241018.png)
is quite useful, but I can assure you that 99.999% of the time it's an accidental click.
I click on this about 50 times a day, then have to close the browser tab that just opened.

**Describe the solution you'd like**
Surely, I wouldn't want people to have this off by default, but having a setting to remove the link would be fantastic.

**Describe alternatives you've considered**
I searched maybe to slow down the apparition of that tooltip, but I don't know if that's even possible in VSCode.

**Additional context**
Most the packages I work with are private anyhow; this link is simply bringing me on a 404 most of the time.

**Comment by hyangah** [comment]
```
	"gopls": {
		"ui.documentation.linksInHover": false
	}
```

**Comment by jsgoupil** [comment]
That solves the issue... It was easier than I thought. Thank you very much.
I was searching in the code for the URL, but I didn't know the code lived somewhere else.
