### ISSUE TITLE
Cannot read go files due to corrupted path

### ISSUE THREAD

**Issue by ewestpe-seroiuvd08308** [golang/vscode-go#176]
### What version of Go, VS Code & VS Code Go extension are you using?
- Go version:
go version go1.13.7 linux/amd64
- VS code version:
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
- VS Code Go extension version:
0.14.3
- go env:
Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- <Paste VS Code version here>
- Check your installed extensions to get the version of the VS Code Go extension 
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
<pre>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ewestpe/.cache/go-build"
GOENV="/home/ewestpe/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/proj/crbs/team_tyra/app/go:/repo/ewestpe/go:/app/vbuild/RHEL7-x86_64/go/1.13.7/bin"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/app/vbuild/RHEL7-x86_64/go/1.13.7"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/app/vbuild/RHEL7-x86_64/go/1.13.7/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build220034424=/tmp/go-build -gno-record-gcc-switches"
</pre>

(A word about GOPATH="/proj/crbs/team_tyra/app/go:/repo/ewestpe/go:/app/vbuild/RHEL7-x86_64/go/1.13.7/bin":
/proj/crbs/team_tyra/app is a shared directory, used to store go packages via go get.
/repo/ewestpe/go is the user repo
/app/... is a read only installation directory for the go version

### Share the Go related settings you have added/edited
<pre>
{
    "go.formatTool": "goimports",
    "go.useLanguageServer": false,
    "go.languageServerExperimentalFeatures": {
   },
}
</pre>
Also experimented with 
<pre>
    "go.gocodeAutoBuild": true,
</pre>
And go.useLanguageServer to true.

### Describe the bug
The path shown for a problem is incorrect

The lines in the problem view has the following two lines:
<pre>
  tls.go /repo/ewestpe/go/src/github.com/go/src/github.com/buildbarn/bb-storage/pkg/util
       no Go files in /repo/ewestpe/go/src/github.com/buildbarn/bb-storage/pkg/proto/configuration/tls
</pre>

If clicking on the problem line it does display:
<pre>
Unable to open 'tls.go': Unable to read file '/repo/ewestpe/go/src/github.com/go/src/github.com/buildbarn/bb-storage/pkg/util/tls.go' (Error: Unable to resolve non-existing file '/repo/ewestpe/go/src/github.com/go/src/github.com/buildbarn/bb-storage/pkg/util/tls.go').
</pre>

For some reason <code>/go/src/github.com</code> do appear twice in some paths, but not all.
Also, there are no go directory under <code>/repo/ewestpe/go/src/github.com</code>

The file system looks as follows:
<pre>
/repo/ewestpe/buildbarn/bb-storage/...
/repo/ewestpe/go/src/github.com contains a symbolic link to /repo/ewestpe/buildbarn
</pre>
This is because a local version of buildbarn and its subrepos are used during development.

### Steps to reproduce the behavior:
1. Go to a file containing an import of proto buffer definition, when this is built problems appear in the problems view
2. Click on the problem

### Screenshots or recordings
<img width="360" alt="vscode-go-error2" src="https://user-images.githubusercontent.com/66415898/83877820-73724880-a73b-11ea-970a-2d77cea6b2eb.PNG">
<img width="366" alt="vscode-go-error" src="https://user-images.githubusercontent.com/66415898/83877283-8cc6c500-a73a-11ea-9d40-61297d95ad6d.PNG">

**Comment by ewestpe-seroiuvd08308** [comment]
Extensions installed are:
- Clang-Format 1.9.0
- Eclipse Keymap 0.12.0
- Go 0.14.3
- vscode-bazel 0.3.0
- vscode-proto3

I suppose the intention is for the proto files to generate go files, but this does not happen in VSCode. It is unclear if this is an effect of the described bugg or for some other reason.

vscode-proto3 is configured with protoc as path, and the protobuf compiler (protoc) is in path.

**Comment by stamblerre** [comment]
From a quick glance, my guess is that the filepath issue is cause by the symbolic link. I'm not sure what the right approach is here (see below).

It looks like you are working in (https://github.com/buildbarn/bb-storage, which uses Bazel. When VS Code builds your code, it just runs `go build` directly, so that's why your protos are not being generated. You will need to manually build using Bazel.

/cc @hyangah - 2 thoughts:
- What do we want to do about symlinks? I'm pretty sure that in vim-go, the maintainers don't fix most symlink bugs because we really don't encourage using them with Go. On the other hand, I think people will probably use them no matter what we encourage.
- We should probably offer some more configuration for what command VS Code Go runs to build?

**Comment by stamblerre** [comment]
Closing, as there hasn't been any activity on this issue in a while.
