### ISSUE TITLE
vscode-go fails to locate package azure-event-hubs-go in expected location

### ISSUE THREAD

**Issue by hholst80** [golang/vscode-go#1761]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.7 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.7.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.59.1
* Check your installed extensions to get the version of the VS Code Go extension
	- Go for VS Code v0.27.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /go
GOROOT: /usr/local/go
PATH: /home/om/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/bin:/go/bin:/usr/local/go/bin:/home/om/.local/bin:/home/om/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

	go:	/usr/local/go/bin/go: go version go1.16.7 linux/amd64

	gopkgs:	not installed
	go-outline:	not installed
	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	not installed
	dlv-dap:	not installed
	staticcheck:	not installed
	gopls:	/go/bin/gopls: go1.16.7
		path	golang.org/x/tools/gopls
		mod	golang.org/x/tools/gopls	v0.7.1	h1:Mh3Z8Xcoq3Zy7ksSlwDV/nzQSbjFf06A+L+F8YHq55U=
		dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
		dep	github.com/google/go-cmp	v0.5.5	h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
		dep	github.com/sergi/go-diff	v1.1.0	h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
		dep	golang.org/x/mod	v0.4.2	h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
		dep	golang.org/x/sync	v0.0.0-20210220032951-036812b2e83c	h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
		dep	golang.org/x/sys	v0.0.0-20210510120138-977fb7262007	h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
		dep	golang.org/x/tools	v0.1.6-0.20210802203754-9b21a8868e16	h1:ZC/gVBZl8poJyKzWLxxlsmhayVGosF4mohR35szD5Bg=
		dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
		dep	honnef.co/go/tools	v0.2.0	h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
		dep	mvdan.cc/gofumpt	v0.1.1	h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
		dep	mvdan.cc/xurls/v2	v2.2.0	h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
	

go env
Workspace Folder (eventgrid): /workspace/centsoft/eventgrid/eventgrid
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/om/.cache/go-build"
	GOENV="/home/om/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.16.7"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2925365042=/tmp/go-build -gno-record-gcc-switches"
	

```
</details>

1. create a docker environment based on `golang:1.16.7-buster`
2. `go get -u github.com/Azure/azure-event-hubs-go/v3`
3. paste the example found on  https://github.com/Azure/azure-event-hubs-go#quick-start
4. fail

possible related to https://stackoverflow.com/a/67320250 a recent change in go that changed where src files are expected to be found.

![image](https://user-images.githubusercontent.com/6200749/132584611-25086e28-c685-4416-a90f-df6b2efd292c.png)

**Comment by hyangah** [comment]
The quick start guide seems outdated if not incorrect. Go 1.16 and newer versions of Go use Go Modules by default. 
Go project's [tutorial](https://golang.org/doc/tutorial/getting-started) provides general guideline for starting a project. 

Still I am not sure how `eventhub` package can be located in the example code, but basically the workflow will be something like:

1. `go mod init example.com/hello`, or you can use VS Code Go's "Go: Initialize go.mod" command.
1. copy/paste the example hello world code
1. `go mod tidy` which will probably build and update the module requirement. 

And please contact the azure repo maintainer to update the instruction.
