### ISSUE TITLE
run test is failed to work on relative path

### ISSUE THREAD

**Issue by dzpt** [golang/vscode-go#1763]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	go version devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20210723180839-46d1522a5d83 h1:GfLrVgg1o0AhGbCQIiusTx7jmk4GzEx3TmbDAY5MhbM=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.6-0.20210723180839-46d1522a5d83 h1:kEnTyyIWR8GHBdSYUQ+Ucf+E54gZ/YHOu27755J6ExU=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	1.52.1
* Check your installed extensions to get the version of the VS Code Go extension
	0.27.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	GOBIN: undefined
toolsGopath: 
gopath: /mypath
GOROOT: /Users/myname/sdk/gotip
PATH: /Users/myname/sdk/gotip/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/mypath/bin:/Users/myname/Library/Android/sdk/emulator:/Users/myname/Library/Android/sdk/tools:/Users/myname/Library/Android/sdk/tools/bin:/Users/myname/Library/Android/sdk/platform-tools
PATH (vscode launched with): /Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/mypath/bin:/Users/myname/Library/Android/sdk/emulator:/Users/myname/Library/Android/sdk/tools:/Users/myname/Library/Android/sdk/tools/bin:/Users/myname/Library/Android/sdk/platform-tools

	go:	/Users/myname/sdk/gotip/bin/go: go version devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000 darwin/amd64

	gopkgs:	/mypath/bin/gopkgs: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/uudashr/gopkgs/v2/cmd/gopkgs
		mod	github.com/uudashr/gopkgs/v2	v2.1.2	h1:A0+QH6wqNRHORJnxmqfeuBEsK4nYQ7pgcOHhqpqcrpo=
		dep	github.com/karrick/godirwalk	v1.12.0	h1:nkS4xxsjiZMvVlazd0mFyiwD4BR9f3m6LXGhM2TUx3Y=
		dep	github.com/pkg/errors	v0.8.1	h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=
	
	go-outline:	/mypath/bin/go-outline: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/ramya-rao-a/go-outline
		mod	github.com/ramya-rao-a/go-outline	v0.0.0-20210608161538-9736a4bde949	h1:iaD+iVf9xGfajsJp+zYrg9Lrk6gMJ6/hZHO4cYq5D5o=
		dep	golang.org/x/tools	v0.1.1	h1:wGiQel/hW0NnEkJUk8lbzkX2gFJU6PFxf1v5OlCfuOs=
	
	gotests:	/mypath/bin/gotests: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/cweill/gotests/gotests
		mod	github.com/cweill/gotests	v1.6.0	h1:KJx+/p4EweijYzqPb4Y/8umDCip1Cv6hEVyOx0mE9W8=
		dep	golang.org/x/tools	v0.0.0-20191109212701-97ad0ed33101	h1:LCmXVkvpQCDj724eX6irUTPCJP5GelFHxqGSWL2D1R0=
	
	gomodifytags:	/mypath/bin/gomodifytags: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/fatih/gomodifytags
		mod	github.com/fatih/gomodifytags	v1.13.0	h1:fmhwoecjZ5c34Q2chjRB9cL8Rgag+1TOSMy+grissMc=
		dep	github.com/fatih/camelcase	v1.0.0	h1:hxNvNX/xYBp0ovncs8WyWZrOrpBNub/JfaMvbURyft8=
		dep	github.com/fatih/structtag	v1.2.0	h1:/OdNE99OxoI/PqaW/SuSK9uxxT3f/tcSZgon/ssNSx4=
		dep	golang.org/x/tools	v0.0.0-20180824175216-6c1c5e93cdc1	h1:EAPsk8kfGCjxQagrkWjzXlUWe2p3gj5MknO+z2o9GKc=
	
	impl:	/mypath/bin/impl: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/josharian/impl
		mod	github.com/josharian/impl	v1.1.0	h1:gafhg1OFVMq46ifdkBa8wp4hlGogjktjjA5h/2j4+2k=
		dep	golang.org/x/mod	v0.2.0	h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
		dep	golang.org/x/tools	v0.0.0-20200522201501-cb1345f3a375	h1:SjQ2+AKWgZLc1xej6WSzL+Dfs5Uyd5xcZH1mGC411IA=
		dep	golang.org/x/xerrors	v0.0.0-20191204190536-9bdfabe68543	h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
	
	goplay:	/mypath/bin/goplay: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/haya14busa/goplay/cmd/goplay
		mod	github.com/haya14busa/goplay	v1.0.0	h1:ED4BMrGQ3WH7H3YXrcnWMVzj1xeSepaYTkLh1DtFi/4=
		dep	github.com/skratchdot/open-golang	v0.0.0-20200116055534-eef842397966	h1:JIAuq3EEf9cgbU6AtGPK4CTG3Zf6CKMNqf0MHTggAUA=
	
	dlv:	/mypath/bin/dlv: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/go-delve/delve/cmd/dlv
		mod	github.com/go-delve/delve	v1.7.0	h1:MaWAD3LtvjE/LL98urSHPjaMT+OubpQ2sqF3R2Uj1rc=
		dep	github.com/cosiner/argv	v0.1.0	h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
		dep	github.com/cpuguy83/go-md2man	v1.0.10	h1:BSKMNlYxDvnunlTymqtgONjNnaRV1sTpcovwwjF22jk=
		dep	github.com/google/go-dap	v0.5.0	h1:RMHAVn5xeunBakYk65ggHXttk6qjZVdbmi+xhAoL2wY=
		dep	github.com/hashicorp/golang-lru	v0.5.4	h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
		dep	github.com/mattn/go-isatty	v0.0.3	h1:ns/ykhmWi7G9O+8a448SecJU3nSMBXJfqQkl0upE1jI=
		dep	github.com/peterh/liner	v0.0.0-20170317030525-88609521dc4b	h1:8uaXtUkxiy+T/zdLWuxa/PG4so0TPZDZfafFNNSaptE=
		dep	github.com/russross/blackfriday	v1.5.2	h1:HyvC0ARfnZBqnXwABFeSZHpKvJHJJfPz81GNueLj0oo=
		dep	github.com/sirupsen/logrus	v1.6.0	h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
		dep	github.com/spf13/cobra	v0.0.0-20170417170307-b6cb39589372	h1:eRfW1vRS4th8IX2iQeyqQ8cOUNOySvAYJ0IUvTXGoYA=
		dep	github.com/spf13/pflag	v0.0.0-20170417173400-9e4c21054fa1	h1:7bozMfSdo41n2NOc0GsVTTVUiA+Ncaj6pXNpm4UHKys=
		dep	go.starlark.net	v0.0.0-20200821142938-949cc6f4b097	h1:YiRMXXgG+Pg26t1fjq+iAjaauKWMC9cmGFrtOEuwDDg=
		dep	golang.org/x/arch	v0.0.0-20190927153633-4e8777c89be4	h1:QlVATYS7JBoZMVaf+cNjb90WD/beKVHnIxFKT4QaHVI=
		dep	golang.org/x/sys	v0.0.0-20200625212154-ddb9806d33ae	h1:Ih9Yo4hSPImZOpfGuA4bR/ORKTAbhZo2AbWNRCnevdo=
		dep	gopkg.in/yaml.v2	v2.2.1	h1:mUhvW9EsL+naU5Q3cakzfE91YhliOondGd6ZrsDBHQE=
	
	dlv-dap:	/mypath/bin/dlv-dap: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	github.com/go-delve/delve/cmd/dlv
		mod	github.com/go-delve/delve	v1.7.1-0.20210724181445-150ef04177a8	h1:fQRxxpvaeo0apcsqNPEenXdvVxbI+bd7ahkW2MxkAOQ=
		dep	github.com/cosiner/argv	v0.1.0	h1:BVDiEL32lwHukgJKP87btEPenzrrHUjajs/8yzaqcXg=
		dep	github.com/cpuguy83/go-md2man/v2	v2.0.0	h1:EoUDS0afbrsXAZ9YQ9jdu/mZ2sXgT1/2yyNng4PGlyM=
		dep	github.com/google/go-dap	v0.5.0	h1:RMHAVn5xeunBakYk65ggHXttk6qjZVdbmi+xhAoL2wY=
		dep	github.com/hashicorp/golang-lru	v0.5.4	h1:YDjusn29QI/Das2iO9M0BHnIbxPeyuCHsjMW+lJfyTc=
		dep	github.com/mattn/go-isatty	v0.0.3	h1:ns/ykhmWi7G9O+8a448SecJU3nSMBXJfqQkl0upE1jI=
		dep	github.com/peterh/liner	v0.0.0-20170317030525-88609521dc4b	h1:8uaXtUkxiy+T/zdLWuxa/PG4so0TPZDZfafFNNSaptE=
		dep	github.com/russross/blackfriday/v2	v2.0.1	h1:lPqVAte+HuHNfhJ/0LC98ESWRz8afy9tM/0RK8m9o+Q=
		dep	github.com/shurcooL/sanitized_anchor_name	v1.0.0	h1:PdmoCO6wvbs+7yrJyMORt4/BmY5IYyJwS/kOiWx8mHo=
		dep	github.com/sirupsen/logrus	v1.6.0	h1:UBcNElsrwanuuMsnGSlYmtmgbb23qDR5dG+6X6Oo89I=
		dep	github.com/spf13/cobra	v1.1.3	h1:xghbfqPkxzxP3C/f3n5DdpAbdKLj4ZE4BWQI362l53M=
		dep	github.com/spf13/pflag	v1.0.5	h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
		dep	go.starlark.net	v0.0.0-20200821142938-949cc6f4b097	h1:YiRMXXgG+Pg26t1fjq+iAjaauKWMC9cmGFrtOEuwDDg=
		dep	golang.org/x/arch	v0.0.0-20190927153633-4e8777c89be4	h1:QlVATYS7JBoZMVaf+cNjb90WD/beKVHnIxFKT4QaHVI=
		dep	golang.org/x/sys	v0.0.0-20200625212154-ddb9806d33ae	h1:Ih9Yo4hSPImZOpfGuA4bR/ORKTAbhZo2AbWNRCnevdo=
		dep	gopkg.in/yaml.v2	v2.4.0	h1:D8xgwECY7CYvx+Y2n4sBz93Jn9JRvxdiyyo8CTfuKaY=
	
	staticcheck:	/mypath/bin/staticcheck: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	honnef.co/go/tools/cmd/staticcheck
		mod	honnef.co/go/tools	v0.2.0	h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
		dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
		dep	golang.org/x/mod	v0.3.0	h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
		dep	golang.org/x/sys	v0.0.0-20210119212857-b64e53b001e4	h1:myAQVi0cGEoqQVR5POX+8RR2mrocKqNN1hmeMqhX27k=
		dep	golang.org/x/tools	v0.1.0	h1:po9/4sTYwZU9lPhi1tOrb4hCv3qrhiQ77LZfGa2OjwY=
		dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
	
	gopls:	/mypath/bin/gopls: devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000
		path	golang.org/x/tools/gopls
		mod	golang.org/x/tools/gopls	v0.0.0-20210723180839-46d1522a5d83	h1:GfLrVgg1o0AhGbCQIiusTx7jmk4GzEx3TmbDAY5MhbM=
		dep	github.com/BurntSushi/toml	v0.3.1	h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
		dep	github.com/google/go-cmp	v0.5.5	h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
		dep	github.com/sergi/go-diff	v1.1.0	h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
		dep	golang.org/x/mod	v0.4.2	h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
		dep	golang.org/x/sync	v0.0.0-20210220032951-036812b2e83c	h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
		dep	golang.org/x/sys	v0.0.0-20210510120138-977fb7262007	h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
		dep	golang.org/x/tools	v0.1.6-0.20210723180839-46d1522a5d83	h1:kEnTyyIWR8GHBdSYUQ+Ucf+E54gZ/YHOu27755J6ExU=
		dep	golang.org/x/xerrors	v0.0.0-20200804184101-5ec99f83aff1	h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
		dep	honnef.co/go/tools	v0.2.0	h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
		dep	mvdan.cc/gofumpt	v0.1.1	h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
		dep	mvdan.cc/xurls/v2	v2.2.0	h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
	

go env
Workspace Folder (tagse): /mypath/src/tagse
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/myname/Library/Caches/go-build"
	GOENV="/Users/myname/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/mypath/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/mypath"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/Users/myname/sdk/gotip"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/Users/myname/sdk/gotip/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="devel go1.18-9f928f9318e Sat Jul 24 01:54:15 2021 +0000"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/mypath/src/tagse/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ks/6cl6kxl56tsbfbgg5gvmfmr40000gn/T/go-build414344940=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
</details>

### Describe the bug
Press on the run test button on the testing method, there will be error like this
the file is located at `tagse/engine/seg/search_test.go`
```
Running tool: /mypath/sdk/gotip/bin/go test -timeout 30s -run ^TestSearch$ engine/seg -gcflags=all=-G=3 -vet=off -v

/mypath/go/src/tagse/engine/seg/seg.go:14:2: no required module provides package github.com/gofrs/flock; to add it:
	go get github.com/gofrs/flock
/mypath/go/src/tagse/engine/seg/doc.go:8:2: package util is not in GOROOT (/mypath/sdk/gotip/src/util)

```
but this package exists, if i run the command from project root:`tagse/` then  it WORKS
`/mypath/sdk/gotip/bin/go test -timeout 30s -run ^TestSearch$ engine/seg -gcflags=all=-G=3 -vet=off -v`

```
=== RUN   TestSearch
--- PASS: TestSearch (0.01s)
PASS
ok      engine/seg      (cached)
```
The run test feature might not recognize `go.mod` in my project?

**Comment by hyangah** [comment]
Can you try to run the above command from the package directory? The extension runs `go test` command from the package directory (in this specific case, `tagse/engine/seg` directory). Is `engine/seg` package in the same module as the module defined in `tagse/go.mod`? 

https://github.com/golang/vscode-go/blob/5d22417d2b3110c8f8a0617b7f573068b15754f6/src/goTest.ts#L120

This code that runs the test from the directory of the tested package existed [for long time](https://github.com/microsoft/vscode-go/commit/6c7f4c547ae67e8c706ca8dfb793733f67f676c1).

**Comment by dzpt** [comment]
@hyangah the full structure is like this
```
tagse/go.mod
tagse/engine/seg/search_test.go
```
The result after running go test from package directory `engine/seg` has the same above error.

this is my go.mod file

```
module tagse

replace httphandler v1.0.0 => ./httphandler

replace util v1.0.0 => ./util

replace engine v1.0.0 => ./engine

require (
	engine v1.0.0
	github.com/spaolacci/murmur3 v1.1.0 // indirect
	httphandler v1.0.0
	util v1.0.0
)

require (
	github.com/gofrs/flock v0.8.1 // indirect
	github.com/golang/protobuf v1.4.3 // indirect
	github.com/robfig/cron/v3 v3.0.0 // indirect
	go.uber.org/goleak v1.1.10 // indirect
	golang.org/x/lint v0.0.0-20210508222113-6edffad5e616 // indirect
	golang.org/x/net v0.0.0-20200822124328-c89045814202 // indirect
	golang.org/x/sys v0.0.0-20210806184541-e5e7981a1069 // indirect
	golang.org/x/text v0.3.0 // indirect
	golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7 // indirect
	google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013 // indirect
	google.golang.org/grpc v1.40.0 // indirect
	google.golang.org/protobuf v1.25.0 // indirect
)

go 1.18


```

**Comment by hyangah** [comment]
`engine` is in a separate module so any replace or requirement information in the `tagse/go.mod` doesn't apply. So, update the `engine` module's `go.mod` by running the `go get` command or `go mod tidy` from the module.

Alternatively, I hope the [`go.work` proposal](https://go.googlesource.com/proposal/+/master/design/45713-workspace.md) helps this situation better. It is currently available in tip (cc @matloob)

**Comment by hyangah** [comment]
Closing.
I hope we have a better workflow for users with multiple modules when `go.work` (can be tested with go1.18beta1 now) is released.

**Comment by dzpt** [comment]
@hyangah 1.18 is released. any update from it?
since Test button is useless while running on package level
