### ISSUE TITLE
Disable format tool

### ISSUE THREAD

**Issue by HiddenTesla** [golang/vscode-go#1767]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I save go file. It is formatting my source code and yields unexpected (and unnecessary) changes, say, converting indenting spaces to tabs.
I see there is a config:
```
"go.formatTool": "default"
```
But there is no `none` option for this config.

**Describe the solution you'd like**
Provide an option like `none` so that it will no longer format my code.

**Comment by hyangah** [comment]
See [Formatting Code And Organizing Imports](https://github.com/golang/vscode-go/blob/master/docs/advanced.md#formatting-code-and-organizing-imports) section to disable formatting.

And, gofmt sets the de-factor formatting style including [tab vs space](https://github.com/golang/go/issues/7101) so I recommend following the style.
