### ISSUE TITLE
Setting testAtCursor to true in go.editorContextMenuCommands has no effect

### ISSUE THREAD

**Issue by jurisbu** [golang/vscode-go#1768]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.7.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.60.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.27.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

I've consulted settings document about https://github.com/golang/vscode-go/blob/master/docs/settings.md#goeditorcontextmenucommands the subject and wanted to enable context menu item to execute test at cursor e.g. `testAtCursor`

```
    "go.editorContextMenuCommands": {
        "addImport": false,
        "addTags": false,
        "benchmarkAtCursor": false,
        "debugTestAtCursor": true,
        "fillStruct": false,
        "generateTestForFile": false,
        "generateTestForFunction": false,
        "generateTestForPackage": false,
        "playground": false,
        "removeTags": false,
        "testAtCursor": true,
        "testCoverage": true,
        "testFile": true,
        "testPackage": true,
        "toggleTestFile": false,
    },
```

### Describe the bug

Setting `testAtCursor` to `true` has no effect, there is no context menu entry available to run test at cursor.

**Comment by stamblerre** [comment]
It looks like that editor context menu item is only supported when code lenses are not available: https://github.com/golang/vscode-go/blob/d32a3269dff461a4f89ba1291cc827b134fcdf60/package.json#L2445.

Code lenses are the buttons that appear to hover around your code, like the `run test` code lens above a test function. Does that work for your use case?

**Comment by stamblerre** [comment]
We should remove the code lens check and switch the defaults off.

**Comment by jurisbu** [comment]
@stamblerre Yes, code lenses work for my use case. After some research I figured to use code lenses functionality to run a specific test. Thanks!
