### ISSUE TITLE
testExplorer: tests are not discovered after "Developer: Restart Extension Host"

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1771]
Code
Version: 1.61.0-insider (Universal)
Commit: 23cffa27b806f9e1733e15d611ec251dcdba2c42
Date: 2021-09-10T17:03:53.070Z (1 hr ago)

Go extension: golang.go-nightly v2021.9.1013

After running "Developer: Restart Extension Host", the "TESTING" tab becomes empty and never recovers until restarting window. It's possible that this can be a vscode bug, but we need inspection before filing an issue.

cc @firelizzard18

**Comment by firelizzard18** [comment]
My understanding is that VSCode is supposed to call `testController.resolveHandler(null)` after the controller is created. This *does* happen during nominal conditions (normal activation). This *does not* happen when the extension host is restarted. In that case, the extension is activated and the controller is created, but the resolve handler is never called.

**Comment by firelizzard18** [comment]
The [root cause](https://github.com/microsoft/vscode/issues/132601) appears to be the test explorer crashing after the extension host restarts. @hyangah would you verify that this issue does not occur with the latest Insiders build?

**Comment by hyangah** [comment]
Thanks! I confirm this problem no longer exists with the latest insiders.
