### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aj-brown-loop1** [golang/vscode-go#1796]
- Issue Type: `Performance`
- Extension Name: `go`
- Extension Version: `0.28.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.60.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MY_NAM~1\AppData\Local\Temp\golang.go-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by hyangah** [comment]
Empty issue. @aj-brown-loop1 Please attach the mentioned file (c:\Users\MY_NAM~1\AppData\Local\Temp\golang.go-unresponsive.cpuprofile.txt) in this issue, and also review the linked wiki page. Thanks!
