### ISSUE TITLE
debug: auto-expand Local in the variables section as done in the legacy debug adapter

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1798]
### Discussed in https://github.com/golang/vscode-go/discussions/1783

<div type='discussions-op-text'>

<sup>Originally posted by **mpetronic** September 17, 2021</sup>
I have the same vscode version installed on two workstations (versions below). 

On the Linux one, when I debug and stop at a break point in a method in Go, I see a COLLPSED "Locals" drop down that I must click to expand. I need to ALWAYS click to expand every time I start a new debug session. Not a show stopper but I think the UI should remember my intentions and repeat for me. Also, my method args show up under an "Arguments" dropdown that is separate from the "Locals" variables dropdown. 

![image](https://user-images.githubusercontent.com/6632334/133816199-d81d5fda-5861-4c02-8be0-032294dc9811.png)

However, when I do the exact same thing on Windows VSCode, the "Local" dropdown is NOT COLLAPSED as it automatically expands when the debug session restarts every time. This is the behavior that I believe should be the default.  Also, ALL the variables (func args and locals) ALL show up under the ONE "Local" dropdown. Note that here it is called "Local" but on Linux it is called "Locals"

![image](https://user-images.githubusercontent.com/6632334/133816940-4444efcc-0e0f-476e-afab-2a879041751e.png)

I surmise that, although I have the same version installed in both workstations, there are differences that are not aligned between the Windows and Linux builds of the app. One even says "Locals" while the other says "Local".

My question was how can I get the auto-expanding of local variables to work on Linux like it does on Windows thinking that there might be some configuration difference that I cannot find. If anyone knows of such a config, I would be grateful for the tip. Otherwise, do you suggest I open an issue to try to get these differences in behavior reconciled?

Thanks for any suggestions. 

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

Version: 1.60.1
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:06:57.931Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.18.0-305.3.1.el8_4.x86_64</div>

**Comment by hyangah** [comment]
From the discussion:

@polinasok asked:

> * Option 1. List Locals, Arguments, Globals in this order and then Locals will be auto-expanded as the first listed scope.
> * Option 2. Return both locals and arguments under one scope Locals without distinction and have that scope auto-expanded. Is the distinction useful?
> 

@mpetronic replied:

> I think it is fine to combine args and locals under one grouping. So my
> vote would be for#2 option. I would say to keep globals under their own
> grouping that is configurable and defaults to hidden. I don't see much use
> for separating args under their own grouping because in almost every case I
> want to see the arguments and the locals at the same time. Adding the
> globals in to that group I think would clutter things up too much. I
> appreciate you seeking my input on this.

I agree with @mpetronic and favor the same behavior as the legacy debug adapter personally.

@suzmue already has a change to implement this. I want to understand why the new debug adapter chose to separate Args and Locals and what advantage we are giving up by switching to Option 2. (performance?)

**Comment by polinasok** [comment]
Delve cli and backend return args and locals separately, so that must have been the reason, but I don't remember for sure anymore. I don't think this should impact performance either way, so whatever is most user-friendly works.
