### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by coderpen-me** [golang/vscode-go#1801]
gopls version: v0.7.2
gopls flags: 
update flags: proxy
extension version: 0.28.0
go version: 1.17
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Fri, 24 Sep 2021 07:55:11 GMT
restart history:
Fri, 24 Sep 2021 07:54:56 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11bea20]

goroutine 476 [running]:
go/types.(*Checker).handleBailout(0xc00014c780, 0xc0005f9698)
	  check.go:245  0x8b
panic({0x1852680, 0x1f9fdc0})
	  panic.go:1038  0x215
go/ast.(*Ident).Pos(0xc0005f8e28)
	  ast.go:469
go/types.spanOf({0x1a80880, 0x0})
	  errors.go:243  0x134
go/types.(*Checker).newError(0xc00014c780, {0x1a80880, 0x0}, 0x27, 0x0, {0xc00ff0d140, 0x33})
	  errors.go:154  0x4f
go/types.(*Checker).error(0x0, {0x1a80880, 0x0}, 0x0, {0xc00ff0d140, 0x40})
	  errors.go:173  0x35
go/types.(*Checker).errorf(0xc00014c780, {0x1a80880, 0x0}, 0xc0094dc6e1, {0x1970abf, 0xc001d53507}, {0x0, 0x193b8fd, 0x0})
	  errors.go:177  0x68
go/types.(*Checker).collectObjects.func1({0x1a81fa0, 0xc0094edc50})
	  resolver.go:279  0xbfd
go/types.(*Checker).walkDecl(0x800000000000, {0x1a94c60, 0xc0094d9300}, 0xc0086e9568)
	  decl.go:431  0x1c7
go/types.(*Checker).walkDecls(0xc001d53507, {0xc0094d9740, 0x4, 0x1}, 0x0)
	  decl.go:418  0x6a
go/types.(*Checker).collectObjects(0xc00014c780)
	  resolver.go:252  0x225
go/types.(*Checker).checkFiles(0xc00014c780, {0xc007a28040, 0xc0094f6320, 0x2})
	  check.go:263  0xb5
go/types.(*Checker).Files(...)
	  check.go:250
golang.org/x/tools/internal/lsp/cache.doTypeCheck({0x1a97a58, 0xc006fc2980}, 0xc007ed0b00, 0xc000c33950, 0x2, 0xc001015800, 0x1a95440)
	  check.go:536  0x893
golang.org/x/tools/internal/lsp/cache.typeCheck({0x1a97a58, 0xc006fc2980}, 0xc007ed0b00, 0xc000c33950, 0x2, 0xc001015800)
	  check.go:313  0xe5
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1({0x1a97a58, 0xc006fc2980}, {0x1a80e80, 0xc007ed0b00})
	  check.go:124  0x23e
golang.org/x/tools/internal/memoize.(*Handle).run.func1()
	  memoize.go:322  0xa9
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x1bd
[Error - 1:25:04 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
@coderpen-me This is a known issue with Go 1.17, please upgrade to 1.17.1 to get the fix.
