### ISSUE TITLE
Align "editor.suggest.snippetsPreventQuickSuggestions" with VSCode defaults

### ISSUE THREAD

**Issue by sebnyberg** [golang/vscode-go#1805]
### Setup

No Go settings. The global setting `editor.suggest.snippetsPreventQuickSuggestions` set to `true`. 

### Bug description

While inside placeholders of snippets in Go, VSCode suggest auto-completions even though the global setting `editor.suggest.snippetsPreventQuickSuggestions` is set to `true`. 

### Steps to reproduce:

Create the snippet

```json
	"Example": {
		"scope": "go",
		"prefix": "ex",
		"body": [
			"type $1 struct {}$0",
		],
	}
```

Open a Go file, type "ex" and tab three times, yielding:

```go
type type type  struct {} struct {} struct {}
```

### Discussion

By default in VSCode `editor.suggest.snippetsPreventQuickSuggestions` is set to `true`. However, in version 0.25, vscode-go introduced an override of the global default value to `false` as per #839.

The confusion is two-fold:
* The behaviour of `vscode-go` does not align with the behaviour of VSCode and other language packages
* Setting the global value has no effect

In principle, default behaviour should be coherent between languages. I don't see why snippet expansion should work differently for Go compared to other languages. For those who use only Go, there's potentially a 50/50 split between those who are happy about the setting and those who are not. In reality however, most VSCode users work with more than one language, and this change forces all of them to learn about this setting.

I therefore propose that the default setting override introduced in v0.25 is reverted.

Edit: changed proposed solution to align with title and actual concern.

**Comment by hyangah** [comment]
Like `editor.formatOnSave`, `editor.suggest.snippetsPreventQuickSuggestions` is owned and used by the vscode, so this extension has no control over how this setting is used, other than suggesting the best setting for Go development using `configurationDefaults` which is what the change for #839 did. 

Please override the Go-specific setting by using 

```
"[go]": {
   "editor.suggest.snippetsPreventQUickSuggestsions": false
 }  
```

In the mean time, how about upvoting https://github.com/Microsoft/vscode/issues/58995 to make this language-specific setting default more visible to users?

**Comment by sebnyberg** [comment]
Let me try once more to explain the situation before and after the change, and how reverting would affect these groups.

Before #839, there were two groups of people: those who preferred this setting to be true, and those who preferred it to be false. For simplicity, let's say it was a 50/50 split. So, half have to learn about the setting, half don't. 50/50 happiness no matter which programming language.

Out of all these users, the vast majority do not use Go. So there's Stackoverflow posts, guides on the VSCode website, and so on, about how to change this setting to `false`. This material makes it easy for the group of people who don't like the default value. A very small portion of these people ended up on this issue tracker, including the person in #839. Note how [OP even answered](https://github.com/golang/vscode-go/issues/839#issuecomment-817174519) that they didn't know about the setting and knowing about it solved his issue, as it does for **all other users in VSCode**.

After the change, there are now 6 groups of people in total.

1. Uses Go forever and want this to be `false` => Never learn about the setting 
2. Started with Go and want this to be `false` => Have to learn about this setting as soon as they learn any other language
3. Move to Go from another language and want this to be `false` => Already know about this setting before moving to Go, but don't need to change anything due to your default.
4. Uses Go forever and want this to be `true` => Have to learn about the setting.
5. Started with Go and want this to be `true` => Have to learn about this setting as soon as they start with Go.
6. Moves to Go from another language and want this to be `true` => Have to learn about this setting.

So out of these, 4 out of 6 groups who work with Go are not happy with this situation since they have to learn about the setting due to how it is set up currently. 1 out of 6 groups already know about the setting but don't need to do anything as they start using Go. Only 1 out of 6 groups are happy with the change.

The proposed UI improvements **is not a solution to this problem**. It's a fundamental configuration management error and will impact users negatively forever. I have used VSCode for at least 5 years and this is the first time I see a change like this, hence my frustration. I hope that we can see eye to eye on this.

**Comment by hyangah** [comment]
The latest VS Code (1.79, 2023 May) changed the default of `editor.suggest.snippetsPreventQuickSuggestions` to `false`. 

https://code.visualstudio.com/updates/v1_79#_quick-suggestions-and-snippets

In the next release, we will remove the language specific setting override since VS Code's default and what this extension wants as default now align.

**Comment by sebnyberg** [comment]
> The latest VS Code (1.79, 2023 May) changed the default of `editor.suggest.snippetsPreventQuickSuggestions` to `false`.
> 
> https://code.visualstudio.com/updates/v1_79#_quick-suggestions-and-snippets
> 
> In the next release, we will remove the language specific setting override since VS Code's default and what this extension wants as default now align.

Good. What bothered me was the inconsistency between the global default and the extension's default, forcing all developers to become aware of the option. Now that the two will align, I'll close the issue.
