### ISSUE TITLE
Failed to find the "go" binary from PATH

### ISSUE THREAD

**Issue by gcstang** [golang/vscode-go#1823]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17.1 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.7.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.60.2
7f6ab5485bbc008386c4386d08766667e155244e
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.28.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: undefined
GOROOT: 
PATH: /usr/bin:/bin:/usr/sbin:/sbin

unable to locate "go" binary in GOROOT () or PATH (/usr/bin:/bin:/usr/sbin:/sbin)
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
"go.formatFlags": [
    "-local",
    "mytech"
  ],
  "go.formatTool": "goimports",
  "go.gocodeAutoBuild": true,
  "go.installDependenciesWhenBuilding": false,
  "go.useLanguageServer": true,

### Describe the bug
A clear and concise description of what the bug.
Upon open of VSCode I receive an error for the Go Plugin
Failed to find the "go" binary from PATH

I expect the plugin to be able to resolve Go from the local environment.
When I go into the VSCode terminal I see the values it say's it can't find
$ env | grep GO
GOROOT=/Users/<myuser>/sdk/go1.17.1
GOPATH=/Users/<myuser>/tclg/GitRepositories/personal/GoLang

### Steps to reproduce the behavior:
1. Open VSCode

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

Seems very similar to https://github.com/golang/vscode-go/issues/971
However manually setting a path to the go install shouldn't be required since it's available in the VSCode terminal already.

**Comment by hyangah** [comment]
This extension uses `PATH` env var inherited from the VS Code process, which can be different from what you'd see from VS Code terminal depending on how the VS Code process started and how you configured your login shells. 

I see from `Go: Locate Configured Go Tools` output, "PATH: /usr/bin:/bin:/usr/sbin:/sbin" and "GOROOT:" that means, the VS Code program was launched with those `PATH` elements and empty `GOROOT` env var. 

Please configure your Mac to find the right PATH. I found some articles about how to set the PATH env vars for Mac launchers on web when configuring Mac. I hope they are helpful. e.g.,
 https://golangbyexample.com/understand-etc-paths-pathsd-mac/
 https://scriptingosx.com/2017/05/where-paths-come-from/
 
Alternatively, utilize `"go.alternateTools": { "go": "<path to go command>" }`  OR `"go.goroot"` settings for now.

**Comment by hyangah** [comment]
Thanks for sharing your workaround.
Closing.

**Comment by ikingye** [comment]
I just restart my vscode, and problem is solved like magic.

**Comment by xyw07** [comment]
Hi I followed instruction. I use "ssh". I changed my goroot path. However, it says "this setting cannot be applied to the current window" 
<img width="656" alt="Screen Shot 2022-01-14 at 4 09 45 PM" src="https://user-images.githubusercontent.com/59544035/149600281-4eb48769-13a1-4dc4-8222-c730cf3a24f6.png">

**Comment by bittopaz** [comment]
It works for me with the config as below:

```json
"go.alternateTools": {
    "go": "/opt/homebrew/bin/go"
}
```
