### ISSUE TITLE
debug: improve workflow of attaching to process

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#183]
See the original report: https://github.com/microsoft/vscode-go/issues/2780.

> Taking note of the PID and updating the `launch.json` file with it every time I want to attach a debugger is a bit tedious.
> 
> **Is there a way I could make this a bit easier?**
> 
> For example, I can get the PID by running:
> 
> ```shell
> pidof go
> ```
> 
> And attach the Delve debugger to the process manually:
> 
> ```shell
> dlv attach $(pidof go) --headless --listen=:2345 --api-version=2
> ```
> 
> And then use the "Connect to server" launch configuration, but then I'll have to detach manually (instead of pressing a button in VS Code).
> 
> In the built-in Node.js debugger there's an option to pick a process from a list by specifying `${command:PickProcess}` in the `processId` field. Maybe something similar is possible?

**Comment by hyangah** [comment]
This feature is available in Go Nightly for testing.

@suzmue If a user does not pick any process from the quick pick menu, I think the extension needs to give up and terminate the debugging session. Currently, it continues and lets the debug adapter start delve with insufficient info and results in crash.
