### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by adlrocha** [golang/vscode-go#1832]
gopls version: v0.7.2
gopls flags: 
update flags: proxy
extension version: 0.28.1
go version: 1.17
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 11 Oct 2021 10:15:44 GMT
restart history:
Mon, 11 Oct 2021 10:15:20 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c13a0]

goroutine 6792 [running]:
go/types.(*Checker).handleBailout(0xc0004bfa40, 0xc00c38f698)
	  check.go:245  0x8b
panic({0xc526c0, 0x139ab20})
	  panic.go:1038  0x215
go/ast.(*Ident).Pos(0xc00c38ee28)
	  ast.go:469
go/types.spanOf({0xe7fc40, 0x0})
	  errors.go:243  0x134
go/types.(*Checker).newError(0xc0004bfa40, {0xe7fc40, 0x0}, 0x27, 0x0, {0xc008c29900, 0x33})
	  errors.go:154  0x4f
go/types.(*Checker).error(0xc007ac8e40, {0xe7fc40, 0x0}, 0x0, {0xc008c29900, 0x3d})
	  errors.go:173  0x35
go/types.(*Checker).errorf(0xc0004bfa40, {0xe7fc40, 0x0}, 0xc0030ef301, {0xd6ffe5, 0xc003db4907}, {0x0, 0x0, 0x0})
	  errors.go:177  0x68
go/types.(*Checker).collectObjects.func1({0xe81260, 0xc00dd8ccf0})
	  resolver.go:279  0xbfd
go/types.(*Checker).walkDecl(0x800000000000, {0xe93f00, 0xc00db0d900}, 0xc008c5b568)
	  decl.go:431  0x1c7
go/types.(*Checker).walkDecls(0xc003db4907, {0xc00dd8e6a0, 0x2, 0x1}, 0x0)
	  decl.go:418  0x6a
go/types.(*Checker).collectObjects(0xc0004bfa40)
	  resolver.go:252  0x225
go/types.(*Checker).checkFiles(0xc0004bfa40, {0xc006e17588, 0xc00dd8a7d0, 0x2})
	  check.go:263  0xb5
go/types.(*Checker).Files(...)
	  check.go:250
golang.org/x/tools/internal/lsp/cache.doTypeCheck({0xe96bf8, 0xc00b1ac980}, 0xc00bae2d00, 0xc0042be960, 0x2, 0xc004161140, 0xe946e0)
	  check.go:536  0x893
golang.org/x/tools/internal/lsp/cache.typeCheck({0xe96bf8, 0xc00b1ac980}, 0xc00bae2d00, 0xc0042be960, 0x2, 0xc004161140)
	  check.go:313  0xe5
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1({0xe96bf8, 0xc00b1ac980}, {0xe80240, 0xc00bae2d00})
	  check.go:124  0x23e
golang.org/x/tools/internal/memoize.(*Handle).run.func1()
	  memoize.go:322  0xa9
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x1bd
[Error - 12:15:36 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
This is a regression in Go 1.17, that was fixed in 1.17.1: https://golang.org/issue/48082.
Can you please update your Go version to 1.17.1?
