### ISSUE TITLE
Pinning Tools Versions

### ISSUE THREAD

**Issue by dfarley1** [golang/vscode-go#1850]
This extension uses multiple external tools which aren't managed by the Golang organization, which introduces a potential security vulnerability. If one of those tools gets compromised, everyone using the Go extension is at risk. Hijacking one of these tools could expose a LOT of private code to a potential supply chain attack or sensitive data exfiltration.

I understand the desire to leave tool version unpinned to fix bugs quickly, but would there be support for some kind of "safe mode" which explicitly pins the versions of tools not under Golang's direct control? This would come with the understanding that bugs are fixed more slowly and that the first suggestion to any bug report would be "try to repro using latest".

Unfortunately, even if VSCode supported pinning the Go extension, Go will still pull the latest tools from Github.

Users could manually install the required tools in their dev environment, pinning their version there, but then an update to the Go extension could break stuff. That would also shift the responsibility of matching versions to individual orgs who lack relevant context and would be unable to keep pace. This is especially true since we cannot pin the Go extension to a specific version through VSCode.

**Comment by dfarley1** [comment]
Tools used by this extension also can't be tracked by systems such as GitHub's [Vulnerable Dependencies Alerts](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/about-alerts-for-vulnerable-dependencies) since the tools aren't listed in a format that GitHub understands.

Adding support for this (and/or other similar solutions) would partially alleviate this problem, then you maintainers would at least get notifications if something's gone wrong.

**Comment by suzmue** [comment]
@dfarley1 golang/vscode-go#1652 tracks the overarching issue.

**Comment by hyangah** [comment]
This is implemented. Closing.
