### ISSUE TITLE
Feature Req: Add alias with package import autocomplete

### ISSUE THREAD

**Issue by pantsmann** [golang/vscode-go#1863]
I love how typing an un-imported package name will suggest a package and then add the import for it. It would be even better if we could somehow specify an alias for the package at the same time. Maybe if the user hits shift+tab, shift+enter, or right clicks on the suggested package a dialog pops up for adding an alias which then replaces the package name where entered and adds the alias to the auto-created import line.

for example:

1. I type 'erro'
2. VSC suggests 'errors' and 'github.com/pantsmann/errors'
3. I arrow down to 'github.com/pantsmann/errors'
4. If I hit enter VSC replaces 'erro' with 'errors' and adds '"github.com/pantsmann/errors"' to my import section.
5. If instead, I hit shift+enter it would ask for an alias
    a. I enter 'perr'
    b.  VSC replaces 'erro' with 'perr' and adds 'perr "github.com/pantsmann/errors"' to my import section. 
6. there after I can just type 'perr' to access the package

**Comment by suzmue** [comment]
After accepting the completion you can immediately issue a rename of the imported package.
```
package main

import "fmt"

func main() {
   fmt<trigger rename>
}
```

**Comment by hyangah** [comment]
@pantsmann Does the workaround by @suzmue meet your need?
