### ISSUE TITLE
Add `-test.v` to single tests, verbose.

### ISSUE THREAD

**Issue by jtagcat** [golang/vscode-go#1879]
Related: #855 

For the `run test | debug test` buttons, it'd be neet, if the default was to run them verbose (t.Logf is shown).

**Comment by hyangah** [comment]
Not sure about making it default, but once we find a way to fix https://github.com/golang/vscode-go/issues/1636 ( improve `go.testFlags` handling) or allow users to provide launch.json for the test codelens, that can be covered.

**Comment by hyangah** [comment]
We discussed in our triage meeting - handling `-test.v` or `-v` is very useful, but changing the default is not ideal. Let's follow up this issue as part of #1636. 
Thanks for the suggestion, @jtagcat
