### ISSUE TITLE
Code completion in Liveshare as a guest intermittently broken.

### ISSUE THREAD

**Issue by wfaler** [golang/vscode-go#1885]
### What version of Go, VS Code & VS Code Go extension are you using?
Go: 1.17.2
VS Code: 1.62.1
VS Code Go: 0.29.0
MacOS Monterey (12.0.1) on Intel
### Share the Go related settings you have added/edited

```
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.autocompleteUnimportedPackages": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
```
### Describe the bug
As a Liveshare guest, code completion, and other IDE features do not work, apart from syntax highlighting.

Going to the `Extensions` view shows the Go extension as disabled, due to not supporting `Virtual Workspaces`.

### Steps to reproduce the behavior:
1. Have another person invite you to a Liveshare session.
2. Join the Liveshare
3. Try to edit some Go-code.

**Comment by hyangah** [comment]
@wfaler Please make sure the Go extension is installed and functioning from the Liveshare host person's machine.
Tools that provide extension's functionalities (including the language server) run on the host machine in Live Share.
I quickly verified code completion or documentation hover requests from guest machines trigger requests to the host machine's gopls.

Reference: https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/extensions 

And, we don't have a plan to support Virtual Workspace - this extension heavily relies on the `go` command for almost everything and `go` does not work in virtual workspace.

**Comment by wfaler** [comment]
I am pairing on Go code, so the other party does have Go installed. Could it be some other mismatch in installed extensions?

**Comment by hyangah** [comment]
@wfaler The host should have Go and Go extension installed. The best way to debug this is to check the session host's gopls trace following [the instruction here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)

**Comment by hyangah** [comment]
Closing. Please reopen this issue or create a new issue.
