### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by rizalreza** [golang/vscode-go#1888]
gopls version: (devel)
gopls flags: 
update flags: proxy
extension version: 0.29.0
go version: 1.17.1
environment: Visual Studio Code darwin
initialization error: Error: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
issue timestamp: Thu, 11 Nov 2021 05:30:39 GMT
restart history:
Thu, 11 Nov 2021 05:30:26 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@rizalreza gopls needs update - the extension couldn't suggest update because it couldn't determine the version of the currently used  `gopls`. (`delve`) So, please run "Go: Install/Update Tools" command, select `gopls`, and let the extension update it. Thanks!
