### ISSUE TITLE
It's amazing to delete my code automatically by default!!! It's a terrible UX!

### ISSUE THREAD

**Issue by ElapsedSoul** [golang/vscode-go#1895]
It's amazing to delete my code automatically by default!!! It's a terrible UX!

Even though,it's easy to find the solution to sovle it.  [issues-2498](https://github.com/microsoft/vscode-go/issues/2498)
But I still want to create a new issuse to stress-emphasize it is a terrible mode of thought!!!
How I stupefied after I type ctrl+/ then ctrl+s.

**Comment by findleyr** [comment]
Hi, when filing issues, please be respectful and charitable. See https://golang.org/conduct for more details.

It is also not clear what bug / behavior you are experiencing. It sounds like you are saying that goimports should not be enabled by default, but I cannot tell from the issue description.

I'm going to close this issue as not actionable.
