### ISSUE TITLE
docs: investigate window.openFoldersInNewWindow setting

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#190]
The contribution documentation says that this setting cannot be "on" when testing VS Code Go. Investigate why and see if this is still true.

**Comment by hyangah** [comment]
According to the snapshot of github.com/microsoft/vscode-go.wiki.git@5b702d8
    (4years ago)
    
    "This will open a new VS Code window which will have the title `[Extension Development Host]`. In this window, open any folder with Go code. Make sure the `window.openFoldersInNewWindow` setting is not `"on"`, otherwise a new, non-`[Extension Development Host]`, window may be opened."
    
    I cannot reproduce this problem with today's vscode.
