### ISSUE TITLE
Edit imported pkg with intellisense

### ISSUE THREAD

**Issue by blacktop** [golang/vscode-go#1908]
I often like to work on imported packages with step debugging in VSCode.  However, when I step into a package and make a change I first have to click on Overwrite to make any changes, but then the language server features don't work at all.  

Is there a way to tell the language server to work on packages that are imported and stepped into?

Perhaps there is a Go idiomatic way I'm supposed to work on an external package (that I also own) while debugging an app?  

If can we add a way to enable this via a setting variable?

Thanks!

**Comment by hyangah** [comment]
@blacktop Do you have a repro case? Or, please capture the gopls trace following [this step](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

If the package you stepped into was in the module cache directory (directory under `go env MODCACHE`), contents under the directory are read-only and not supposed to be modified. But in my brief testing, the language server seems to continue to work.

--

I don't know if there is THE way to work on an external package. People in the gophers slack (#modules-help channel) may know better. 

Some useful resources:  
* [Developing and testing against unpublished module code
](https://go.dev/doc/modules/managing-dependencies#unpublished)
* with go1.18, [`go.work`](https://github.com/golang/go/issues/45713) can be helpful - but we still need to figure out how to integrate it into this extension. 
* tools like [`gohack`](https://github.com/rogpeppe/gohack)

**Comment by blacktop** [comment]
So I'm currently working on https://github.com/blacktop/ipsw and the lib/pkg I'm working on is https://github.com/blacktop/go-macho. After some research I discovered the technique of making a dep "local"

```
replace github.com/blacktop/go-macho => ../go-macho
```

which is VERY nice because it gets rid of the issue where editing the pkg required "Overwriting" and then being out-of-sync (previously I had to copy-paste between my "cached" version that I was overwriting and the real repo 🤮)

However, when I "drill into" go-macho and try and make a change I see this:
<img width="1120" alt="Screen Shot 2021-11-24 at 1 56 54 PM" src="https://user-images.githubusercontent.com/6118188/143311885-5bf22c06-fd36-41f3-b3ee-6164952d62ea.png">

I would have expected a VERY large list of autocomplete options to show up.  Is there any settings flags I could set to have gopls also analyze the pkg `go-macho` ?

**Comment by blacktop** [comment]
`go.work` sounds exactly like what I'm trying to do.  `ipsw` was getting so large that I broke it out into many libraries, but now working on it is a pain, because I have to update the "external" package and then cut a release and THEN update my `go.mod` to pull in those changes and then continue working on `ipsw` 😩

**Comment by blacktop** [comment]
Using the `local` pkg `replace` in go.mod so far has been a life changer, but I loose all the POWER 💪 of using gopls and vscode-go 😢

**Comment by hyangah** [comment]
@blacktop How about opening vscode from the directory where you have both ipsw and go-macho as subdirs and set the workspace setting to enable the experimental workspace module?

```
    "gopls": {
        "build.experimentalWorkspaceModule": true
    },
```

This enables the experimental feature mentioned as the first related work in the `go.work` proposal, and I've been using this when working on the go language server (see its [go.mod](https://github.com/golang/tools/blob/master/gopls/go.mod)). Just make sure to inspect `go.mod` and revert modification for local development before pushing the change to the remote vcs.
