### ISSUE TITLE
Allow setting test filter for coverage

### ISSUE THREAD

**Issue by darkdragon-001** [golang/vscode-go#1909]
**Is your feature request related to a problem? Please describe.**
We have two types of tests in our projects:
- Unit tests (prefix `TestUnit`)
- Environment tests (prefix `TestEnv`)

Since environment tests need additional infrastructure (additional services running to work), we want to exclude those tests for coverage detection on save.

**Describe the solution you'd like**
Add an option to set a filter or pass additional arguments to `go test`.

**Describe alternatives you've considered**
Is there another better way to store and run our environment tests?

**Additional context**
_None_

**Comment by hyangah** [comment]
@darkdragon-001 Is it possible to pass the `-run` test flag through `go.testFlags` or prevent testing of those tests using [build tags](https://pkg.go.dev/cmd/go#hdr-Build_constraints)?

**Comment by darkdragon-001** [comment]
@hyangah This works, awesome thanks!
