### ISSUE TITLE
debug: remove the src/debugAdapter/.vscode/launch.json

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#191]
This file appears to be a relic from when the main `launch.json` did not have any configurations for the debug adapter. This is no longer the case, so we should delete this file.

**Comment by eliben** [comment]
Related: #224

**Comment by hyangah** [comment]
@ramya-rao-a said it was used when launching both extension and debug server in debug mode was necessary in old days. Now, ["Extension + Debug server"](https://github.com/golang/vscode-go/blob/91c626c2ac9c99072ea7c242ba57ab3fdc842665/.vscode/launch.json#L95) replaces it and works better. 

I just verified it works as expected. (I could set breakpoints in both extension and debug server code in one vscode instance!)

We need documentation update here https://github.com/golang/vscode-go/blob/master/docs/debug-adapter.md#debug-vs-code-and-the-debug-adapter

cc @polinasok @stamblerre @quoctruong
