### ISSUE TITLE
Editing import path freezes whole system

### ISSUE THREAD

**Issue by prakharmaurya** [golang/vscode-go#1912]
As I edit the line of import path a bit. It just freezes whole system. Only thing can only be done is to force shutdown system and it happening again and again from yesterday. I left my system overnight even display didn't gone dim. Tried to open terminal and restart desktop environment from different shortcuts but just nothing happens.
### Tried
1. Reinstalled Go Extension

### Go specs
* go version go1.17.3 linux/amd64
* gopls v0.7.3
* Vs Code - 1.62.3 - x64
* Go extension version v0.29.0
* Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/excel/go
GOROOT: /home/excel/.gobrew/versions/1.17.3/go
PATH: /home/excel/.gobrew/:/home/excel/.gobrew/bin/:/home/excel/.gobrew/current/bin/
	go:	/home/excel/.gobrew/current/bin/go: go version go1.17.3 linux/amd64
	gopkgs:	/home/excel/go/bin/gopkgs: go1.17.3
		path	github.com/uudashr/gopkgs/v2/cmd/gopkgs
		mod	github.com/uudashr/gopkgs/v2	v2.1.2
	go-outline:	/home/excel/go/bin/go-outline: go1.17.3
		path	github.com/ramya-rao-a/go-outline
		mod	github.com/ramya-rao-a/go-outline	v0.0.0-20210608161538-9736a4bde949
	gotests:	/home/excel/go/bin/gotests: go1.17.3
		path	github.com/cweill/gotests/gotests
		mod	github.com/cweill/gotests	v1.6.0
	gomodifytags:	/home/excel/go/bin/gomodifytags: go1.17.3
		path	github.com/fatih/gomodifytags
		mod	github.com/fatih/gomodifytags	v1.16.0
	impl:	/home/excel/go/bin/impl: go1.17.3
		path	github.com/josharian/impl
		mod	github.com/josharian/impl	v1.1.0
	goplay:	/home/excel/go/bin/goplay: go1.17.3
		path	github.com/haya14busa/goplay/cmd/goplay
		mod	github.com/haya14busa/goplay	v1.0.0	
	dlv:	/home/excel/go/bin/dlv: go1.17.3
		path	github.com/go-delve/delve/cmd/dlv
		mod	github.com/go-delve/delve	v1.7.2
	dlv-dap:	/home/excel/go/bin/dlv-dap: go1.17.3
		path	github.com/go-delve/delve/cmd/dlv
		mod	github.com/go-delve/delve	v1.7.3-0.20211109082426-9013a121d8bc
	staticcheck:	/home/excel/go/bin/staticcheck: go1.17.3
		path	honnef.co/go/tools/cmd/staticcheck
		mod	honnef.co/go/tools	v0.2.2
	
	gopls:	/home/excel/go/bin/gopls: go1.17.3
		path	golang.org/x/tools/gopls
		mod	golang.org/x/tools/gopls	v0.7.3
go env
Workspace Folder (banking): /run/media/excel/files/web_go/banking
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/excel/.cache/go-build"
	GOENV="/home/excel/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/excel/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/excel/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/home/excel/.gobrew/versions/1.17.3/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/home/excel/.gobrew/versions/1.17.3/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.17.3"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/run/media/excel/files/web_go/banking/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3617608867=/tmp/go-build -gno-record-gcc-switches"

Operating System: Garuda Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.5-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

### Steps to reproduce the behavior:
I don't know exactly

**Comment by hyangah** [comment]
@prakharmaurya If it happens repeatedly, can you share the example to reproduce the problem?

And, please enable tracing and share the gopls trace if you can still manage to inspect vscode's Output channel when problem happens? (Instruction: https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)

**Comment by prakharmaurya** [comment]
Yes It happens to every time when I edit import path of any package but I couldn't get any trace output at time of freeze. System just freezes. If there is a file which records the trace that may survive the restart. It is happening to me from last 5 days. I tried to updated everything OS VS code Go Extension. It still happens. Thank You for response.

**Comment by suzmue** [comment]
Sorry without the trace, we aren't going to be able to do anything about this :( If you can try having the trace window open maybe you can screenshot it?

Please feel free to reopen if you have more info.
