### ISSUE TITLE
can not debug go in vscode after install delve

### ISSUE THREAD

**Issue by ElapsedSoul** [golang/vscode-go#1919]
install delve by cmd ```$ go install github.com/go-delve/delve/cmd/dlv@latest```
then press `F5`
got error:
```
Starting: C:\Users\LENOVO\go\bin\dlv-dap.exe dap --check-go-version=false --listen=127.0.0.1:54664 from C:\Users\LENOVO\Desktop\node_exporter
DAP server listening at: 127.0.0.1:54664
Build Error: go build -o C:\Users\LENOVO\Desktop\node_exporter\__debug_bin.exe -gcflags all=-N -l .\node_exporter.go
# internal/bytealg
go_asm.h:1: expected identifier, found "%"
asm: assembly of C:\Program Files\Go\src\internal\bytealg\compare_amd64.s failed (exit status 2)
```

link with [delve issue](https://github.com/go-delve/delve/issues/2811)

**Comment by suzmue** [comment]
@ElapsedSoul The extension currently installs two versions of delve, and uses the executable with the name "dlv-dap" when not using the legacy adapter. Could you try updating dlv-dap from vscode?

Use the command: `Go: Install/ Update Tools` and select dlv-dap.

**Comment by ElapsedSoul** [comment]
I uninstalled go and install the lastest go,The problem gone!

**Comment by ZhangHongbin9** [comment]
Same issue, I had tried to update dlv-dap from vscode and uninstalled, reinstalled Go, but the problem still happened.
