### ISSUE TITLE
formatting: reconsider goreturns as the default

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#192]
`goreturns` has not been ported to work with modules. It seems that we should either send a PR that does the port, or we should change the default formatting tool.

**Comment by hyangah** [comment]
My understanding is that `go.formatTool` applies only when language server (`gopls`) is not used. And we are recommending `gopls` when users use modules mode.

Should we bother?

**Comment by stamblerre** [comment]
That's fair, it may not be worth it. It just seemed a bit strange to me that our out-of-the-box formatting wouldn't work (if you first downloaded the extension without immediately opting into `gopls`).
