### ISSUE TITLE
Adopt pre-release extension support

### ISSUE THREAD

**Issue by isidorn** [golang/vscode-go#1935]
Hi VS Code PM here 👋 

Refs: https://github.com/microsoft/vscode/issues/15756

VS Code now supports pre-release extensions. Docs that should help: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions

I know GO has a separate Go Nightly. Ideally Go would adopt to our pre-release support and we would deprecate that extension. VS Code can automatically migrate your existing Go Nightly users to the pre-release version of the Go extension once you have done the adoption.

Let me know what you think

**Comment by hyangah** [comment]
That's a great news!
Thanks @isidorn for keeping us posted.

**Comment by isidorn** [comment]
Friendly ping for this. Go is the only remaining extension in the VS Code ecosystem that is using nightly.
Can you migrate to pre-release? Are there some blockers? Thanks 🙏

**Comment by isidorn** [comment]
Once this is done just ping me and we can migrate users from your Nightly extension to the pre-release version.

**Comment by hyangah** [comment]
Our first insider version (v0.43.0) is published. 
Nightly extension publication is stopped.

@isidorn Can you please migrate the nightly extension users? Thanks!

**Comment by isidorn** [comment]
Thanks for the ping. Will do the migration later today/Monday. And deprecate the nightly one.

**Comment by hyangah** [comment]
Thanks @isidorn for your patience and help!
Verified the nightly is deprecated. It's still active in the marketplace, but I guess the change eventually will apply there too :-)

<img width="570" alt="Screenshot 2024-09-04 at 3 47 41 PM" src="https://github.com/user-attachments/assets/02db5c30-4d58-48ca-a47e-bb4a775960fb">

**Comment by isidorn** [comment]
Marketplace does not support deprecated extensions (yet).
So I think we are good. Thank you 🙏
