### ISSUE TITLE
Freezes while typing import statements

### ISSUE THREAD

**Issue by ljoxloyd** [golang/vscode-go#1940]
Issue Type: <b>Performance Issue</b>

CPU usage spikes to 100% in short bursts when typing name of the package I want to import 

Steps to reproduce:
- write
```
import (
    ""
)
```
- start typing inside quotes 

Extension version: 0.29.0
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.28GB free)|
|Process Argv|--crash-reporter-id 8ffaefbe-7c54-44c6-93a5-e11ef775729e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   103	  4980	code main
    0	   208	  1500	   window (● main.go - going - Visual Studio Code)
    0	   134	  2224	   extensionHost
    0	   161	  8912	     "C:\Users\wizard\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\wizard\.vscode\extensions\streetsidesoftware.code-spell-checker-2.0.13\packages\_server\dist\main.js --node-ipc --clientProcessId=2224
    0	    65	 16748	     C:\Users\wizard\go\bin\gopls.exe -mode=stdio
    0	    11	  9576	       console-window-host (Windows internal process)
    0	    41	  6296	   utility-network-service
    0	   100	  7632	   shared-process
    0	    78	  7000	     watcherServiceParcelSharedProcess
    0	    78	 17144	     ptyHost
    0	    75	  7980	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     7	 13924	       console-window-host (Windows internal process)
    0	   175	  9412	   gpu-process
    0	    85	 13100	   issue-reporter
    0	    26	 13172	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● main.go - going - Visual Studio Code)
|    Folder (going): 6 files
|      File types: json(1) mod(1) exe(1) go(1)
|      Conf files: settings.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsaa593:30376534
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30405999
vscexrecpromp3t2:30407763

```

</details>

**Comment by hyangah** [comment]
From the process info, I don't see anything suspicious (CPU/memory usage is not high).

Can you please provide the followings?
  - go version
  - full gopls trace (follow the instruction [here](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information) ) while reproducing the issue
  
 And make sure to disable other extensions and check no anti-virus or security program is interfering with Go and gopls's execution.

**Comment by hyangah** [comment]
Please reopen with the requested info @ljoxloyd
