### ISSUE TITLE
debug: dlv-dap attach with mode remote should show possible PIDs if processID is 0

### ISSUE THREAD

**Issue by aaomidi** [golang/vscode-go#1941]
dlv-dap is amazing and has simplified the debug workflow quite a bit when running in containers. However, the UX can use some improvement.

For context, I'm running the nightly version of vscode-go, and the HEAD version of dlv.

It seems like, currently, there is only one way of attaching to an existing process that is running in a container.

0. Find the PID of the process you're going to want to connect to. Remember it.
1. In the container: `dlv dap --listen=:1234`
2. Make sure that 1234 is reachable from the host (e.g. configuration in docker-compose)
3. Create a/edit launch.json configuration that looks somewhat similar to this:

```
   {
      "name": "Connect to server",
      "type": "go",
      "request": "attach",
      "mode": "local",
      "port": 1234,
      "host": "127.0.0.1",
      "processId": "", <---- PID GOES HERE
      "debugAdapter": "dlv-dap",
      "showLog": true,
      ]
    }
```
4. And then run this debug task.

I would've preferred if there was a way to get vscode to load the processes running on the container, and give me a dropdown (maybe with the ability to pre-filter the results?) of their PIDs. Basically similiar to how this works without the `host` and `port` values being entered.

I've also tested with using `remote` for the `mode`, but that consistently returns a no debugger found error. It seems like that's more meant to if the application had started with `dlv exec --listen`.

Thanks!

**Comment by aaomidi** [comment]
@hyangah thanks for the extra context there. I think this is generally why I wanted it as a feature request for the extension rather than dlv as a tool, or dap as a protocol.

Maybe this doesn't really belong here, and should be taken to the containers extension, but a command that can just list the PIDs inside a container would work super well here. I'll see if I can make a PR to add that support.

In that case, I can replace pid with ${some-extension's-command}.

**Comment by hyangah** [comment]
I assume the way to retrieve PIDs inside a container will vary depending on the type of containers, etc, and fit better to be handled in the corresponding container extension. Once the command is implemented, yes, you can wire up using https://code.visualstudio.com/docs/editor/variables-reference#_command-variables

Closing because at this moment, it is beyond the scope of this project.  Thanks for sharing the idea!
