### ISSUE TITLE
gopls: panic during type check (go1.15 bug)

### ISSUE THREAD

**Issue by yagezi** [golang/vscode-go#1942]
gopls version: v0.7.3
gopls flags: 
update flags: proxy
extension version: 0.29.0
go version: 1.15.11
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Mon, 13 Dec 2021 01:36:18 GMT
restart history:
Mon, 13 Dec 2021 01:31:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: assertion failed

goroutine 987 [running]:
go/types.(*Checker).handleBailout(0xc0002e6240, 0xc002e81608)
	  check.go:244  0x9f
panic(0x1bbfa40, 0x1f18700)
	  panic.go:969  0x1c7
go/types.assert(...)
	  errors.go:19
go/types.(*Checker).recordTypeAndValue(0xc0002e6240, 0x1f3eb80, 0xc001e2eb40, 0xc000fac804, 0x1f31c00, 0xc000fac820, 0x1f417c0, 0x2436588)
	  check.go:328  0x251
go/types.(*Checker).updateExprType(0xc0002e6240, 0x1f3eb80, 0xc001e2eb40, 0x1f31c00, 0xc000fac820, 0x30001)
	  expr.go:478  0x312
go/types.(*Checker).convertUntyped(0xc0002e6240, 0xc0030898c0, 0x1f31c00, 0xc000fac820)
	  expr.go:578  0x453
go/types.(*Checker).assignment(0xc0002e6240, 0xc0030898c0, 0x1f31c00, 0xc000fac820, 0x1d25b3e, 0x10)
	  assignments.go:46  0x157
go/types.(*Checker).initVar(0xc0002e6240, 0xc00130c910, 0xc0030898c0, 0x1d25b3e, 0x10, 0x1c93c00, 0xc0009474c0)
	  assignments.go:124  0x151
go/types.(*Checker).initVars(0xc0002e6240, 0xc0016dc048, 0x1, 0x1, 0xc002d67380, 0x1, 0x1, 0x88beaf)
	  assignments.go:247  0x599
go/types.(*Checker).stmt(0xc0002e6240, 0x0, 0x1f3f340, 0xc001e2eb60)
	  stmt.go:447  0x3598
go/types.(*Checker).stmtList(0xc0002e6240, 0x0, 0xc002d67390, 0x1, 0x1)
	  stmt.go:120  0xd6
go/types.(*Checker).stmt(0xc0002e6240, 0x0, 0x1f3ec00, 0xc0026fb800)
	  stmt.go:484  0x3f94
go/types.(*Checker).stmt(0xc0002e6240, 0x0, 0x1f3f0c0, 0xc00291f240)
	  stmt.go:496  0x42d9
go/types.(*Checker).stmtList(0xc0002e6240, 0x0, 0xc001e2ec60, 0x2, 0x2)
	  stmt.go:120  0xd6
go/types.(*Checker).funcBody(0xc0002e6240, 0xc001447e60, 0xc002ae0155, 0x3, 0xc001c8e660, 0xc0026fb860, 0x0, 0x0)
	  stmt.go:42  0x225
go/types.(*Checker).funcDecl.func1()
	  decl.go:662  0x6e
go/types.(*Checker).processDelayed(0xc0002e6240, 0x0)
	  check.go:290  0x45
go/types.(*Checker).checkFiles(0xc0002e6240, 0xc0029e2000, 0x30c, 0x400, 0x0, 0x0)
	  check.go:266  0xdc
go/types.(*Checker).Files(...)
	  check.go:249
golang.org/x/tools/internal/lsp/cache.doTypeCheck(0x1f41100, 0xc0018d6b40, 0xc0001d1400, 0xc00044e690, 0x2, 0xc002033ec0, 0x0, 0x0, 0x0, 0x0)
	  check.go:536  0xdc5
golang.org/x/tools/internal/lsp/cache.typeCheck(0x1f41100, 0xc0018d6b40, 0xc0001d1400, 0xc00044e690, 0x2, 0xc002033ec0, 0xc00000cde0, 0x1276baa, 0xc0001e37a0)
	  check.go:313  0xac
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1(0x1f41100, 0xc0018d6b40, 0x1f2cfa0, 0xc0001d1400, 0x0, 0xc000dd58d0)
	  check.go:124  0x1db
golang.org/x/tools/internal/memoize.(*Handle).run.func1(0xc000e1a390, 0x1f41100, 0xc0018d6b40, 0xc00305c0a0, 0x1f2cfa0, 0xc0001d1400, 0xc00179ca20)
	  memoize.go:322  0xaf
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x18d
[Error - 上午9:35:57] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report @yagezi 
I think it's one of the crashing bugs in old go/types (go1.15).
Can you please update Go (go1.17.5 recommended now) and rebuild gopls?
