### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by g10guang** [golang/vscode-go#1944]
gopls version: (devel)
gopls flags: 
update flags: proxy
extension version: 0.29.0
go version: 1.16
environment: Visual Studio Code linux
initialization error: Error: json: cannot unmarshal object into Go struct field .tagSupport of type bool
issue timestamp: Tue, 14 Dec 2021 02:03:45 GMT
restart history:
Tue, 14 Dec 2021 02:03:36 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field .tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Hi @g10guang Can you please update gopls using "Go: Install/Update Tools" command? Looks like `gopls` is quite outdated. Please open a new issue if the problem persists even after updating gopls. Thanks!
