### ISSUE TITLE
windows firewall always shows up on every start of debug session

### ISSUE THREAD

**Issue by willie68** [golang/vscode-go#1955]
### What version of Go, VS Code & VS Code Go extension are you using?
	- go version go1.17.4 windows/amd64
	- golang.org/x/tools/gopls v0.7.4
	-1.63.2 , 899d46d82c4c95423fb7e10e68eba52050e30ba3 , x64
	- VS Code Go 0.30.0
	- Tools: see go_env.txt
[go_env.txt](https://github.com/golang/vscode-go/files/7743633/go_env.txt)

### Share the Go related settings you have added/edited
{
    "go.gocodeAutoBuild": true,
    "go.useLanguageServer": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true
    },
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "gopls": {
        "usePlaceholders": true,
    },
    "go.vetOnSave": "off",
    "go.buildOnSave": "off",
    "go.testFlags": [
        "-v"
    ],
    "go.toolsManagement.autoUpdate": true,
    "editor.codeActionsOnSave": null,
}

### Describe the bug
since the last update on every start of the binary in debug mode will create a new exe files (with a number at the end, __debug_bin3043758041.exe), which will than trigger the windows firewall to add a new exception. Before the binary was always __debug_bin.exe, which will trigger the firewall only once.

### Steps to reproduce the behavior:
1. simply start a simple project
2. See the windows firewall popup

### Screenshots or recordings
![grafik](https://user-images.githubusercontent.com/5518382/146735801-fe833000-0896-47e5-8e21-422f2e1dc729.png)

**Comment by willie68** [comment]
as now the binary is always in a temp folder, i don't like the idea to put this folder to an exclusion list.

**Comment by cbiglioli** [comment]
I've the same problem. Every time I've to allow ___debug_bin**********.exe_ in Windows Defender Firewall.

**Comment by hyangah** [comment]
@willie68 @cbiglioli Thanks for the feedback.
If you configure a launch.json and add `"output": "debug"` explicitly, do you still see the issue? I suspect it's another bug in the extension - that does not set the default value as stated in package.json.

**Comment by willie68** [comment]
@hyangah when i set the output parameter, than the firewall screnn shows up only once. So, it seems youre right, the default for output is not set.

**Comment by cbiglioli** [comment]
@willie68 I've the same behavior. After the first time that VS Code starts, in the firewall there is this:

![image](https://user-images.githubusercontent.com/48820981/148179661-e18e5031-6247-4704-b875-d7c1db13f5d9.png)

@hyangah Thank you very much!

**Comment by hyangah** [comment]
@suzmue @polinasok If vscode-go always set this to be 'debug', should we revert the change in dlv dap made in https://github.com/go-delve/delve/pull/2660 ?
I dislike that dlv creates __debug_bin in random directories in my workspace but if that's the only way people with firewall setup can live with, maybe that was a good default. What do you think?
