### ISSUE TITLE
gopls: spurious errors from template files (umbrella issue)

### ISSUE THREAD

**Issue by achamoux** [golang/vscode-go#1957]
![VSCode_error_in_packages_golang-1-17](https://user-images.githubusercontent.com/32041339/146828023-a0740b29-2649-431f-a4e5-ad024d729d74.PNG)

### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

I'm using Go 1.17 in Windows 10 64

**Comment by zeripath** [comment]
Development of Gitea is also affected by this. Is there any way of excluding linting of individual template files or even directories? We have some template files which aren't even intended to be go templates.

**Comment by findleyr** [comment]
Hi, for now yes the best solution is to turn off template linting, as you have found. We will prioritize fixing this for the next release (both honoring the directoryFilters, and fixing the spurious 'empty buffer' errors)

CC @pjweinbgo

**Comment by findleyr** [comment]
And I should also add: apologies for the breakage.

**Comment by butuzov** [comment]
the other possible way is to disable template association using  `files.associations`

```
"files.associations": {
    "path/*tmpl": "plaintext"
}
```

**Comment by hyangah** [comment]
cc @pjweinb

**Comment by findleyr** [comment]
Renamed this to be a parent issue tracking spurious errors from template files.

**Comment by pjweinbgo** [comment]
Isn't this a gopls (rather than vscode-go) error?

**Comment by findleyr** [comment]
@pjweinbgo yes the errors are coming from gopls. It intersects with vscode-go in the mutually conflicting configuration: `files.associations` and gopls' `build.templateExtensions`.

I think it's worth leaving this here to track the overarching problem of improving the resolution of template files in vscode, but don't feel strongly.

**Comment by findleyr** [comment]
Transferring this to the Go issue tracker for milestone tracking.
