### ISSUE TITLE
settings: properly declare `gopls` related settings

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#197]
Since `gopls` is in alpha and the set of final flags and configurable parameters are not finalized, we are still relying on the `gopls` object that is not officially declared.  As `gopls` development becomes stable, we need to sort out settings and properly declare it.

Related: for VS Code UI feature to utilize - https://github.com/microsoft/vscode/issues/99635
Related: for automatic generation of docs (possibly, part of package.json) - https://go-review.googlesource.com/c/tools/+/212521

@stamblerre

**Comment by stamblerre** [comment]
It should now be possible to do this after [CL 252322](https://go-review.googlesource.com/c/tools/+/252322), using the settings JSON. The JSON for commands still needs to be generated.

/cc @heschik
