### ISSUE TITLE
Generic support

### ISSUE THREAD

**Issue by panyox** [golang/vscode-go#1970]
**Is your feature request related to a problem? Please describe.**
When it support generic?

**Describe the solution you'd like**
nope

**Describe alternatives you've considered**
nope

**Additional context**
nope

**Comment by lukasl-dev** [comment]
An unstable version is already available. Simply [update the gopls server](https://github.com/golang/tools/blob/master/gopls/doc/advanced.md#working-with-generic-code).

**Comment by panyox** [comment]
> An unstable version is already available. Simply [update the gopls server](https://github.com/golang/tools/blob/master/gopls/doc/advanced.md#working-with-generic-code).

Cool, thank you.
