### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by ObiajuluM** [golang/vscode-go#1973]
Hello, Awesome project guys. Are there any plans to add support for proper syntax highlighting for go in vscode?
It would be nice

**Comment by hyangah** [comment]
The default syntax highlighting is done by VSCode, not this extension.
If you want semantic syntax highlighting, you can configure gopls to do so with the [ui.semanticTokens](https://github.com/golang/vscode-go/blob/master/docs/settings.md#uisemantictokens) setting.

```
"gopls": {
  "ui.semanticTokens": true
}
```

**Comment by ObiajuluM** [comment]
thanks @hyangah
