### ISSUE TITLE
Build error by the default build flags.

### ISSUE THREAD

**Issue by zerist** [golang/vscode-go#1975]
### What version of Go, VS Code & VS Code Go extension are you using?
go version go1.12 windows/amd64

### Share the Go related settings you have added/edited
empty setting about go 

### Describe the bug
I got [Build Error] when trying to debug a simple demo go file.

Build Error: go build -o C:\Users\xuk\AppData\Local\Temp\__debug_bin841302703.exe -gcflags all=-N -l .
go build testdemo/echo: build output "C:\\Users\\xuk\\AppData\\Local\\Temp\\__debug_bin841302703.exe" already exists and is not an object file (exit status 1)

### Steps to reproduce the behavior:
1. Go to a simple helloworld file.
2. Click on 'Run and Debug'
3. See error

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/10177779/147557841-e5ad3d18-19fb-44c6-aa37-68b6952a71a9.png)

![image](https://user-images.githubusercontent.com/10177779/147557819-56af044a-529a-4771-a5ec-4d51880aac77.png)

### Other
The file can be built with command 
`go build -o C:\Users\xuk\AppData\Local\Temp\__debug_bin841302703.exe -gcflags 'all=-N -l' .`
I just need a pair of quotes on '-gcflags'.
But I dont konw how to make it.(I have tried Setting buildFlags, but it doesn't work).

**Comment by hyangah** [comment]
@zerist Can you please check what was in the C:\\Users\xuk\\AppData\\Local\\Temp\\__debug_bin841302703.exe (or whatever the file name shown in the error message) when you encounter the error? 

FYI - the command line printed in the log message is the result of printing  `[..., "-gcflags", "all=-N -l", "."]` so it looks like an error but  it's not.

**Comment by zerist** [comment]
It's an empty file. There is nothing.
Yeah, I know it, but the flag "-gcflags -all=-N -l" works wrong on my computer(and  "-gcflags '-all=-N-l'" works). But I did nothing about Golang  and go extension setting. The cmd produced by the default build action .
I wonder how to edit the default build flags or change the default build action.

**Comment by hyangah** [comment]
The `gcflags` is set by Delve, so please check if you can reproduce the issue with the equivalent `dlv` command.
If you still see an error, report the issue to delve issue tracker.

```
cd d:\work\src\testdemo\echo
D:\work\bin\dlv-dap.exe debug .
```

**Comment by zerist** [comment]
Thanks! As you say, Delve's version is the problem. 
![image](https://user-images.githubusercontent.com/10177779/147618711-ad802f34-5511-479b-aa9f-566395dadf5a.png)
