### ISSUE TITLE
Vague error messages due to failed string interpolation

### ISSUE THREAD

**Issue by tervorz** [golang/vscode-go#1976]
https://github.com/golang/vscode-go/blob/691e15fc8229d3c0e4afbd5db2769779b7a9f55d/src/debugAdapter/goDebug.ts#L2092

I was having trouble getting the vscode go extension working for DAP in emacs. I got this error message in the console:

```
Warning (emacs): Initialize request failed: Failed to continue: "{e}"
```

Manually going in and editing the extension's `goAdapter.js` file to this:
```
this.sendErrorResponse(response, 3e3, `Failed to continue: ${err.toString()}`, {
        e: err.toString()
      });
```
      
Resulted in a useful error message:
```
Warning (emacs): Initialize request failed: Failed to continue: Cannot find Delve debugger. Install from https://github.com/go-delve/delve & ensure it is in your Go tools path, "GOPATH/bin" or "PATH".
```

I've noticed a few other places in this file that use that same failing pattern, attempting to interpolate the error message using that `"{e}"` construct. It'd be worth a look for someone to do a quick fix.

Installing delve did indeed solve my issue, but I was spinning my wheels for quite a while since the error output wasn't helping me.

Using: node v16.10.0, vscode-go v0.30.0, emacs v27.2

**Comment by hyangah** [comment]
This is working as intended according to DAP spec. 

> Message
> A structured message object. Used to return errors from requests.
>
> interface Message {
> ...
>   /**
>    * A format string for the message. Embedded variables have the form '{name}'.
>    * If variable name starts with an underscore character, the variable does not
>    * contain user data (PII) and can be safely used for telemetry purposes.
>    */
>   format: string;
>  ...

Please report this to the debug adapter client plugin (emacs?).

FYI the legacy debug adapter (`src/debugAdapter/goDebug.ts`) is deprecated as `delve` natively supports DAP. https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_dap.md
