### ISSUE TITLE
Test failure: debug should cleanup when stopped

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#1993]
Flaky test in Daily Build Status: https://github.com/golang/vscode-go/runs/4701235773?check_suite_focus=true

<details><summary>DAP Trace</summary>
should cleanup when stopped FAILED: DAP Trace

>> accepted connection from client

-> server: {"type":"request","seq":1,"command":"initialize","arguments":{"adapterID":"go","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path"}}

Unable to log remote console arguments Output omitted for a large object that exceeds the limits

-> server: {"seq":0,"type":"response","success":true,"request_seq":0,"command":"runInTerminal","body":{"processId":19177}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap DAP server for a predetermined client\n2022-01-04T11:24:14Z debug layer=dap DAP server pid = 19177\n2022-01-04T11:24:14Z debug layer=dap Connected to the client at 127.0.0.1:40349\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap DAP connection 1 started\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [<- from client]{\"seq\":1,\"type\":\"request\",\"command\":\"initialize\",\"arguments\":{\"adapterID\":\"go\",\"linesStartAt1\":true,\"columnsStartAt1\":true,\"pathFormat\":\"path\"}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":1,\"success\":true,\"command\":\"initialize\",\"body\":{\"supportsConfigurationDoneRequest\":true,\"supportsFunctionBreakpoints\":true,\"supportsConditionalBreakpoints\":true,\"supportsEvaluateForHovers\":true,\"supportsSetVariable\":true,\"supportsExceptionInfoRequest\":true,\"supportTerminateDebuggee\":true,\"supportsDelayedStackTraceLoading\":true,\"supportsLogPoints\":true,\"supportsDisassembleRequest\":true,\"supportsClipboardContext\":true,\"supportsSteppingGranularity\":true,\"supportsInstructionBreakpoints\":true}}\n"}}
<- server: {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"supportsSetVariable":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsDelayedStackTraceLoading":true,"supportsLogPoints":true,"supportsDisassembleRequest":true,"supportsClipboardContext":true,"supportsSteppingGranularity":true,"supportsInstructionBreakpoints":true}}
-> server: {"type":"request","seq":2,"command":"launch","arguments":{"name":"Launch","type":"go","request":"launch","mode":"debug","program":".","stopOnEntry":false,"output":"/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output","debugAdapter":"dlv-dap","console":"integrated","logOutput":"dap,debugger","showLog":true,"trace":"verbose","packagePathToGoModPathMap":{"/home/runner/go/src/test/testfixture":"/home/runner/go/src/test/testfixture","/home/runner/go/src/test/testfixture/baseTest":"","/home/runner/go/src/test/testfixture/gogetdocTestData":"","/home/runner/go/src/test/testfixture/completions":"","/home/runner/go/src/test/testfixture/testTags":"","/tmp/legacyna9LtK/testfixture/baseTest":"/tmp/legacyna9LtK/testfixture/baseTest","/tmp/legacyna9LtK/testfixture/completions":"/tmp/legacyna9LtK/testfixture/completions","/tmp/legacyna9LtK/testfixture/testTags":"/tmp/legacyna9LtK/testfixture/testTags"},"dlvToolPath":"/home/runner/go/bin/dlv","env":{},"__buildDir":"/home/runner/work/vscode-go/vscode-go/test/testdata/loop"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [<- from client]{\"seq\":2,\"type\":\"request\",\"command\":\"launch\",\"arguments\":{\"name\":\"Launch\",\"type\":\"go\",\"request\":\"launch\",\"mode\":\"debug\",\"program\":\".\",\"stopOnEntry\":false,\"output\":\"/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output\",\"debugAdapter\":\"dlv-dap\",\"console\":\"integrated\",\"logOutput\":\"dap,debugger\",\"showLog\":true,\"trace\":\"verbose\",\"packagePathToGoModPathMap\":{\"/home/runner/go/src/test/testfixture\":\"/home/runner/go/src/test/testfixture\",\"/home/runner/go/src/test/testfixture/baseTest\":\"\",\"/home/runner/go/src/test/testfixture/gogetdocTestData\":\"\",\"/home/runner/go/src/test/testfixture/completions\":\"\",\"/home/runner/go/src/test/testfixture/testTags\":\"\",\"/tmp/legacyna9LtK/testfixture/baseTest\":\"/tmp/legacyna9LtK/testfixture/baseTest\",\"/tmp/legacyna9LtK/testfixture/completions\":\"/tmp/legacyna9LtK/testfixture/completions\",\"/tmp/legacyna9LtK/testfixture/testTags\":\"/tmp/legacyna9LtK/testfixture/testTags\"},\"dlvToolPath\":\"/home/runner/go/bin/dlv\",\"env\":{},\"__buildDir\":\"/home/runner/work/vscode-go/vscode-go/test/testdata/loop\"}}\n"}}
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap parsed launch config: {\n\t\"mode\": \"debug\",\n\t\"program\": \".\",\n\t\"output\": \"/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output\",\n\t\"backend\": \"default\",\n\t\"stackTraceDepth\": 50\n}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap building from \"/home/runner/work/vscode-go/vscode-go/test/testdata/loop\": [go build -o /home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output -gcflags all=-N -l .]\n2022-01-04T11:24:14Z debug layer=dap launching binary '/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output' with config: {\n\t\"mode\": \"debug\",\n\t\"program\": \"/home/runner/work/vscode-go/vscode-go/test/testdata/loop\",\n\t\"cwd\": \"/home/runner/work/vscode-go/vscode-go/test/testdata/loop\",\n\t\"output\": \"/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output\",\n\t\"dlvCwd\": \"/home/runner/work/vscode-go/vscode-go/test/testdata/loop\",\n\t\"backend\": \"default\",\n\t\"stackTraceDepth\": 50\n}\n2022-01-04T11:24:14Z info layer=debugger launching process with args: [/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output]\n"}}
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"initialized\"}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":2,\"success\":true,\"command\":\"launch\"}\n"}}

<- server: {"seq":0,"type":"event","event":"initialized"}

<- server: {"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}

-> server: {"type":"request","seq":3,"command":"configurationDone"}
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [<- from client]{\"seq\":3,\"type\":\"request\",\"command\":\"configurationDone\",\"arguments\":{}}\n"}}
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"output\",\"body\":{\"category\":\"console\",\"output\":\"Type 'dlv help' for list of commands.\\n\",\"source\":{}}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":3,\"success\":true,\"command\":\"configurationDone\"}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Type 'dlv help' for list of commands.\n","source":{}}}

<- server: {"seq":0,"type":"response","request_seq":3,"success":true,"command":"configurationDone"}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=debugger continuing\n"}}
adapter disposing

adapter disposed

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap DAP error: EOF\n2022-01-04T11:24:14Z debug layer=dap DAP server stopping...\n2022-01-04T11:24:14Z debug layer=dap halting\n2022-01-04T11:24:14Z debug layer=debugger halting\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap connection 1 closed - stopping \"continue\" command\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-04T11:24:14Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"output\",\"body\":{\"category\":\"console\",\"output\":\"Detaching and terminating target process\\n\",\"source\":{}}}\n2022-01-04T11:24:14Z debug layer=dap write tcp 127.0.0.1:45556->127.0.0.1:40349: use of closed network connection\n2022-01-04T11:24:14Z debug layer=debugger detaching\n"}}

</details>

```
  1) Go Debug Adapter Tests (dlv-dap, console=integrated)
       disconnect
         should cleanup when stopped:
     AssertionError [ERR_ASSERTION]: debug output /home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output wasn't cleaned up. {"dev":2065,"mode":33261,"nlink":1,"uid":1001,"gid":121,"rdev":0,"blksize":4096,"ino":280634,"size":1151676,"blocks":2256,"atimeMs":1641295454321.3447,"mtimeMs":1641295454317.3447,"ctimeMs":1641295454317.3447,"birthtimeMs":1641295454233.3447,"atime":"2022-01-04T11:24:14.321Z","mtime":"2022-01-04T11:24:14.317Z","ctime":"2022-01-04T11:24:14.317Z","birthtime":"2022-01-04T11:24:14.233Z"}
```

**Comment by hyangah** [comment]
Still failing

```
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:41Z debug layer=debugger continuing\n"}}

adapter disposing

adapter disposed

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:41Z debug layer=dap DAP error: EOF\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:41Z debug layer=dap DAP server stopping...\n2022-01-10T16:47:41Z debug layer=dap halting\n2022-01-10T16:47:41Z debug layer=debugger halting\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:41Z debug layer=dap connection 1 closed - stopping \"continue\" command\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:41Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"output\",\"body\":{\"category\":\"console\",\"output\":\"Detaching and terminating target process\\n\",\"source\":{}}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:41Z debug layer=dap write tcp 127.0.0.1:37976->127.0.0.1:42691: use of closed network connection\n2022-01-10T16:47:41Z debug layer=debugger detaching\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2022-01-10T16:47:42Z debug layer=dap DAP server stopped\n"}}
```

Maybe increase the sleep time?
