### ISSUE TITLE
Failed to find the "go" binary even though it exists in PATH

### ISSUE THREAD

**Issue by wnz27** [golang/vscode-go#1996]
```
Failed to find the "go" binary in either GOROOT(Users/f27/.go/current) or PATH(/Users/f27/go/bin:/Users/f27/.go/current/bin:xxxxxxxxxxxx
Check PATH, or Install Go and reload the window. If PATH isn't what you expected,
```
but in this dir `/Users/f27/.go/current/bin` I have go binary:
<img width="506" alt="截屏2022-01-06 00 37 50" src="https://user-images.githubusercontent.com/12094918/148254599-5844b8e0-c39d-42cc-9f32-abe5b228c01d.png">

I think these two  issue didn't solve the problem

**Comment by hyangah** [comment]
Are they symlinks?

**Comment by wnz27** [comment]
> 

what can I do this? I can't understand this problem, exist but not found

**Comment by wnz27** [comment]
I Solve this problem uninstall and re install..............But I can't understand this I thing it's very very very Affect user experience

**Comment by hyangah** [comment]
Good to hear that the problem went away. 
Unfortunately, it's not possible for us to continue investigation without a reproducer. :-( 
If someone encounter the same issue, please try to reload the window using command "Developer: Reload Window" first and see if that helps.

Closing.

**Comment by wnz27** [comment]
> Good to hear that the problem went away. Unfortunately, it's not possible for us to continue investigation without a reproducer. :-( If someone encounter the same issue, please try to reload the window using command "Developer: Reload Window" first and see if that helps.
> 
> Closing.

anyway good luck and happy new year
