### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lobtheslob** [golang/vscode-go#20]
- Issue Type: `Performance`
- Extension Name: `go-nightly`
- Extension Version: `2020.3.2823`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/tsimpson/golang.go-nightly-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by hyangah** [comment]
As the template says:
 
⚠️ Make sure to attach this file from your home-directory:
⚠️/Users/tsimpson/golang.go-nightly-unresponsive.cpuprofile.txt
