### ISSUE TITLE
debug: debugging in container fails when docker "network_mode: host" set

### ISSUE THREAD

**Issue by mmichal9** [golang/vscode-go#2001]
### What version of Go, VS Code & VS Code Go extension are you using?
Extension: Go v0.30.0
VsCode: Version: 1.63.2
Go 1.17.5

### Share the Go related settings you have added/edited
 {
            "name": "Remote Docker",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath":"/go/src/work/cmd/mapper",
            "port": 2345,
            // "host": "127.0.0.1",
            "cwd": "${workspaceFolder}/src/cmd/mapper",
            "args": [],
            "trace" : "verbose",
            "env" : {}
        },

### Describe the bug
Hi I am not sure if this is a right place to ask but I am trying to run remote debugging using delve inside a docker container with VSCode. Problem starts when I specify docker-compose flag network_mode: host instead of the specific port (This is required due to use of MQTT). This causes VSCode to throw the following error: "Failed to continue: "Error: connect ENCONNREFUSED ..."". 
How can i get a debugger to work with docker-compose flag network_mode: host specified?
More details here: https://github.com/mmichal9/Go_dlv_remote_debug

### Steps to reproduce the behavior:
1. build image: **docker build -t gotestdlv .**
2. add break point
3. run: **docker-compose up**
4. Attach debugger: From vsCode - use launch.json

### Screenshots or recordings
<img width="907" alt="img" src="https://user-images.githubusercontent.com/26767094/148530100-a895f8b8-8fa8-4cc9-8bfa-7e5c0e238ce6.png">

**Comment by hyangah** [comment]
I am not familiar with docker's host networking mode. From extension's point of view, the only requirement is whether the VSCode can access the specified host:port address (in your case 127.0.0.1:2345). Can you check what host:port is actually available outside container with your configuration?

**Comment by mmichal9** [comment]
Hi, yeah you are right, when running on Linux it works fine. As in my use case it is only required to run this on Linux i guess this issue can be closed. However, I still don't get why it fails on Mac.

**Comment by hyangah** [comment]
@mmichal9 That is because Docker doesn't support network host mode on mac, so the delve's port isn't exposed outside the container. VSCode runs outside the container in your setup so there is no way it to connect to the port if the port is not accessible. 

Closing. Thanks!
