### ISSUE TITLE
Extensions are not getting installed in vscode container

### ISSUE THREAD

**Issue by ishaRenavikar** [golang/vscode-go#2014]
### Discussed in https://github.com/golang/vscode-go/discussions/2013

<div type='discussions-op-text'>

<sup>Originally posted by **ishaRenavikar** January 13, 2022</sup>
Hello,

vscode version : 
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-46-generic

I have a docker container running on my ubuntu host.
I attach to this container from vscode using remote-container extension.
Once the container is attached, I try to install the go extension inside the container.
go extension displays a button - "Install in container <container name>"
The following message is displayed with exclamation:
This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'Container <container name>' to enable

On clicking the button , nothing happens.
I dont understand why any extension is not getting installed in vscode container.

Please help me.</div>

**Comment by hyangah** [comment]
I couldn't repro. https://github.com/golang/vscode-go/discussions/2013#discussioncomment-1966221
Can you please post the screenshot of the extension view, and the log from `Log (Remote Server)` when you install the extension? (Command Palette -> View: Toggle Output -> Select "Log (remote Server)" from the dropdown on the right side)

**Comment by hyangah** [comment]
> Have you reported the issue to https://github.com/microsoft/vscode-remote-release/issues ? This can be confusion from UI but I may be wrong - the extension should be installed on the remote side, and the extension info installed locally will be shown with the mentioned warning message when vscode is attached to the container.
> 
> If successfully installed, the extension should be shown in the extension view with the remote container icon in the remote extension side. ![Screen Shot 2022-01-13 at 6 20 33 PM](https://user-images.githubusercontent.com/4999471/149425342-07d1421c-a793-4d6a-8bff-929693ba2568.png)

Closing since we don't have sufficient info to investigate further.
