### ISSUE TITLE
noDebug mode: unable to process 'evaluate' request

### ISSUE THREAD

**Issue by allenjol** [golang/vscode-go#2015]
I use fmt.Scanln() to get keyboard input number and want to  use dlv to debug my Go code,i get this error:
```
noDebug mode: unable to process 'evaluate' request
```
who one know this and can anyone tell me how to resolve it?

**Comment by suzmue** [comment]
It appears you are running the program in noDebug mode, which will not allow you to set breakpoints or inspect the state of the program. Make sure you are starting running with debugging enabled (F5).

What steps were you taking when you got that error? How did you launch the program (in the terminal, etc)?
Where did you try to supply the keyboard input?

**Comment by allenjol** [comment]
![image](https://user-images.githubusercontent.com/28972707/149603544-83f0ea92-4787-40ec-89c7-e062cd5d58b9.png)


I want to supply keyboard input here,and i have configure vscode F5 debug mode,i don't know if this is the right configuration with my vscode 
![image](https://user-images.githubusercontent.com/28972707/149603632-4789b9c8-c22a-4961-9046-3f599f25a1e6.png)
If there is wrong way to configure golang-vscode debug mode,can you show me how to configure the right way?

**Comment by hyangah** [comment]
The default DEBUG CONSOLE does not provide access to tty. 
Currently we are experimenting the `console` attribute to address this issue.
That experimental feature is available in the Nightly version (find golang.go-nightly from marketplace).
If you provide `"console": "integratedTerminal"`, the debug session will start the debugger & the program in a terminal where your program will have access to stdin. Can you give it a try and provide feedback?
https://github.com/golang/vscode-go/issues/124#issuecomment-1006122877

**Comment by allenjol** [comment]
Firstly, I have disabled standard Go extension，and enabled go-bightly.
Secondly，i add `"console": "integratedTerminal"` to my vscode ---> settings.json
![image](https://user-images.githubusercontent.com/28972707/150047819-1d2f07c2-cc3c-4c13-a637-370d2de087ec.png)


Then i have try to F5 to debug my codes，but i got the same result.

The difference is that instead of showing the NoDebug mode, it now shows the Debug mode.

![image](https://user-images.githubusercontent.com/28972707/150047604-b605bb97-9d00-42e1-a943-a18a872d5c2d.png)

**Comment by hyangah** [comment]
The console property should be in the debug configuration in launch.json

**Comment by allenjol** [comment]
Thank you @hyangah, your advice helped me solve this problem. I've always thought configuring the Go extention was appropriate, but for now if I want to use F5 to debug code in vscode and implement keyboard input from a terminal, the go-nightly extention works better

**Comment by hyangah** [comment]
Great to hear that the new console mode worked for you.
A new version of golang.go extension will be released with the `console` feature this week. 

Closing this issue.

**Comment by Tanyangkai** [comment]
> try to type on the keyboard, the cursor



> The console property should be in the debug configuration in launch.json

i don't understand  this, can tell the details ,please .

**Comment by Tanyangkai** [comment]
> 
tit's like this?  still can't  solve it  
<img width="863" alt="image" src="https://user-images.githubusercontent.com/19951791/177021630-b1103758-ec75-41f0-9b10-c2e3df59ab3d.png">

**Comment by Emkay860** [comment]
> I have same problem too... any solutions?

Add this property to the launch.json file configurations
"console": "integratedTerminal",

**Comment by JimaDoll** [comment]
> Add this property to the launch.json file configurations

You should click "X" and choose "save" after changing the settings.

**Comment by JAVAYAMATO** [comment]
use intellj gland instead of vscode
