### ISSUE TITLE
Enable run test on subtest

### ISSUE THREAD

**Issue by ikouchiha47** [golang/vscode-go#202]
Right now in VSCode for subtest, there is no way to run it. But one can run a particular subtest from the command line.

The way is very simple, Take the first argument of `t.Run(<message_in_quotes>, ....)` and then convert spaces to  underscores, I am guessing that, when inside the subtest, there will be a way to get the parent test name and then simply

`go test <path to package> -run=<parent_test_func_name>/<sub_test_name_from_above>`

Is this possible?

**Comment by stamblerre** [comment]
Yep, this feature will be coming in the next release: https://github.com/golang/vscode-go/pull/86.

**Comment by danielhelfand** [comment]
Was this ever added? Seeing #86 was closed. Also not seeing how to do this with go extension currently.

**Comment by danielhelfand** [comment]
This was added for anyone else arriving at this issue: https://github.com/golang/vscode-go/blob/master/docs/commands.md#go-subtest-at-cursor

**Comment by jadwahab** [comment]
Oh thanks @danielhelfand didn't know about that `Go: Subtest At Cursor` feature!

Is there a way to run a subtest in debug mode? That would be ideal... It's really tough to debug a specific test when using [table-driven tests](https://dave.cheney.net/2019/05/07/prefer-table-driven-tests) - unless I'm missing something?
