### ISSUE TITLE
Proposal: move the links in the popups off the bottom line

### ISSUE THREAD

**Issue by Banyc** [golang/vscode-go#2021]
**Is your feature request related to a problem? Please describe.**

Every time I hover the cursor on a method, the editor will pop up a prompt showing its info and a link to <pkg.go.dev>, which is a cool feature. However, as big-thumb as I am, I will always mis-click those links if I want to select the previous line of code.

**Describe the solution you'd like**

That is to move the links in the popups off the bottom line IMO.

**Describe alternatives you've considered**

Or maybe remove the links?

**Additional context**

**Comment by findleyr** [comment]
I think the link is only on the bottom line if there is no docstring? For example, what could we improve in this screenshot?

![image](https://user-images.githubusercontent.com/57144380/150356047-906ce693-81a9-4588-9955-5fc9444c1363.png)

FWIW, you can remove the links altogether via the [`ui.documentation.linksInHover`](https://github.com/golang/vscode-go/blob/master/docs/settings.md#uidocumentationlinksinhover) setting, but it would be nice to solve this usability problem, if possible.

**Comment by Banyc** [comment]
@findleyr 

```json
"gopls": {
    "ui.documentation.linksInHover": false,
},
```

It works! Thanks!

In my use cases, I seldom feel like clicking those links since the `README.md` file at the Github page is more informative than what the `pkg.go.dev` page offers. Therefore, I will choose to hide the links as a feasible solution.

**Comment by findleyr** [comment]
Glad this works for you! Closing.
