### ISSUE TITLE
debug: prompt users to delete `dlv-dap` binary

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2035]
Since v0.30.0, `dlv-dap` binary is no longer needed.
Historically, this extension didn't attempt to delete any tool because they can be useful outside of VSCode.
`dlv-dap` is different - there is no reason a user has to keep this binary separate from `dlv`. 
Why not suggest for deletion if `dlv-dap` is found?

**Comment by polinasok** [comment]
Can we delete for the user?

**Comment by hyangah** [comment]
I don't think this is critical - for other tools we deprecated, we never prompted users to delete them. So, let's not bother with this.
