### ISSUE TITLE
Support Go generics

### ISSUE THREAD

**Issue by oxtoacart** [golang/vscode-go#2040]
**Is your feature request related to a problem? Please describe.**
Go generics are now stable and available in the Go 1.18 beta builds, so this seems like a good time to add support for them.

**Describe the solution you'd like**
Please support the editing and compilation of source files that use Go's new generics language support.

**Describe alternatives you've considered**
Use a different IDE?

**Additional context**
see also #1265

**Comment by hyangah** [comment]
[Instruction](https://github.com/golang/vscode-go/blob/master/docs/advanced.md#using-go118)

We've been using VSCode Go with this configuration to work with generics for a while.

**Comment by hyangah** [comment]
Closing in favor of the pinned issue.

**Comment by oxtoacart** [comment]
Thanks @hyangah !
