### ISSUE TITLE
ui: view for `go env` and important settings that affects go's functionality

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2049]
There are dozens of settings and environment variables affecting how `go` command works.
`go env` or commands to inspect environment variables is a typical way to inspect them, 
but often the environment the extension (or vscode extension host) is different from what
users see from their terminals (e.g. users use shell config that does not get invoked when
vscode launches, etc.). That causes confusions numerous times.

We added some of the info in the `Go: Locate Configured Tools` command output, but
the output is verbose and text-heavy. It's time to think about better UI. An option is [View](https://code.visualstudio.com/api/references/extension-guidelines#views).

### Info to included in the new Go Env view

  - `go env` output
      - GOWORK (related to https://github.com/golang/vscode-go/issues/2032)
      - GOMOD
      - GOOS
      - GOARCH
      - GOENV
      - GOFLAGS
      - GOPRIVATE
      - GOBIN
      - GOPATH
      - GOROOT
      ...
  - Path to the go command (or GOROOT)
  - List of tools
      - Name, path, version
  - settings affecting build/test (e.g. [go.buildFlags](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gobuildflags), or tags)

### Future work

This view may be extended in the future to have associated commands
  - to open the associated resources (e.g. open `go.mod` file)
  - to trigger setting changes (e.g. [Allow setting GOOS via UI](https://github.com/golang/vscode-go/issues/1281))
  - to update tools

### Remarks

* The info in the view may need to change depending on the workspace root folder the open file belongs to.

* I cannot think of a good existing default container (explorer/scm/debug/test) where this new view belongs to yet. We may need to create a [custom view container](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers) for Go - where we can organize more go-project specific information (Module/Package dependencies, Package doc, ...)
 
 
 cc @jamalc @golang/tools-team

**Comment by hyangah** [comment]
Of course, this is not the first time I thought about this :-)  https://github.com/golang/vscode-go/issues/1630

**Comment by hyangah** [comment]
![Screen Shot 2022-04-25 at 2 54 19 PM](https://user-images.githubusercontent.com/4999471/165155240-6e32af93-672d-4e29-a71f-ca547047d122.png)

From v0.33.0, there will be a Go view in the Explorer container by default and that will present some environment variables and tool locations and versions. We plan to extend this to provide easy access to update the env vars or flag variables in the future. Users can move the view to the activity bar directly, move to bottom of the editor, or completely hide it like other views.
 
Thanks @jamalc

**Comment by polinasok** [comment]
Should `go.toolsEnvVars` settings be reflected as well? That could help with highlighting hidden settings like in #2206.
Or maybe `settings.json` could be its own separate Explorer category. And another `launch.json` section when debug session is running could be nice too.
