### ISSUE TITLE
problems with asdf

### ISSUE THREAD

**Issue by J4c5** [golang/vscode-go#2051]
# The Problem
Today, I had to work with go, so I installed the extension. However, I had problems, the extension was not recognizing the __GOPATH__.

> Asdf is version manager.

# how to reproduce
- 1 Install the [Asdf](http://asdf-vm.com/)
- 2 Use [asdf-golang](https://github.com/kennyp/asdf-golang) for install golang in current version
- 3 Open VsCode and install the [vscode-go](https://github.com/golang/vscode-go)
- 4 Create file __main.go__ and save

# extension response
> Cannot install Go tools. Set either __go.gopath__ or __go.toolsGopath__ in settings.

**Comment by hyangah** [comment]
The extension gets GOPATH information from VS Code if not configured through `go.gopath` or `go.toolsGopath`. 
So, launch the code from the environment where GOPATH is populated.

**Comment by hyangah** [comment]
Closing. Understanding a variety of version management software is beyond the scope of this extension.
