### ISSUE TITLE
coverage: show test coverage when running the "Go: Test File" command

### ISSUE THREAD

**Issue by dcormier** [golang/vscode-go#206]
Being able to see code coverage when I'm running a specific test (`Go: Test Function At Cursor`) or all tests in a package (`Go: Test Package`) is great, but sometimes what I need is the coverage of all tests in a given file (`Go: Test File`).

**Comment by pjweinb** [comment]
In Settings, do you have
Go: Cover on Single Test
checked? I think the default is 'false'.

**Comment by dcormier** [comment]
I do, but when I went there I found this:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/216265/85595520-ee31d380-b616-11ea-8472-4fbd9312130c.png">

I guess that setting didn't exist whenever I went in and checked the other two (which must have been a long time ago).

**Comment by pjweinb** [comment]
i think it was in the 31 December 2019 update. i'm glad that the fix was simple.
