### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Jcowwell** [golang/vscode-go#2077]
gopls version: v0.7.5
gopls flags: 
update flags: proxy
extension version: 0.31.1
go version: 1.18beta1
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Tue, 22 Feb 2022 03:34:07 GMT
restart history:
Tue, 22 Feb 2022 03:32:47 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls fails to run. It tires several times to connect but never seems to. Restarting VSCode and my computer does not fix the issue. It initially crashed when implementing a local version of go's sort.go file for Numeric Types. 

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

> [Error - 10:33:18 PM] Request textDocument/codeLens failed.
> Error: Connection got disposed.
> 	at Object.dispose (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:4909:25)
> 	at Object.dispose (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:9694:35)
> 	at LanguageClient2.handleConnectionClosed (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:11902:38)
> 	at LanguageClient2.handleConnectionClosed (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:14311:15)
> 	at closeHandler (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:11890:16)
> 	at CallbackList.invoke (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:3025:35)
> 	at Emitter.fire (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:3076:34)
> 	at closeHandler (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:4171:24)
> 	at CallbackList.invoke (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:3025:35)
> 	at Emitter.fire (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:3076:34)
> 	at StreamMessageReader.fireClose (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:3218:27)
> 	at Socket.<anonymous> (c:\Users\[Removed-For-Privacy]\.vscode\extensions\golang.go-0.31.1\dist\goMain.js:3301:42)
> 	at Socket.emit (events.js:327:22)
> 	at Pipe.<anonymous> (net.js:673:12)

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by Jcowwell** [comment]
it seems the problem ceases when removing the file I was working on. I've attached it as a zip
[sort.zip](https://github.com/golang/vscode-go/files/8113541/sort.zip)
t

**Comment by Jcowwell** [comment]
narrowed the problem to doing `[N N]` in the insertionSort Function. Guess gopls didn't like that at all.

**Comment by hyangah** [comment]
@Jcowwell Thanks for the report. Can you please update to use go1.18rc1 (AND compile gopls with go1.18rc1 too) and see if you can reproduce the issue? Many issues in generics support were already fixed in go1.18beta2 and go1.18rc1 already.

**Comment by hyangah** [comment]
go1.18 was released and extension should ask users to rebuild gopls. Closing.
