### ISSUE TITLE
Unable to modify GOPROXY

### ISSUE THREAD

**Issue by why0406** [golang/vscode-go#2081]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.17.7 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.64.2 (Universal)
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.31.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Describe the bug
I want to change GOPROXY from `GOPROXY="https://proxy.golang.org,direct"` to `https://goproxy.io`,
but it still does not work even if  run the cmd `export GOPROXY=https://goproxy.io` or add it to `~/.bash_profile` and `source ~/.bash_profile`

After Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command, the GOPROXY alaways is
`https://proxy.golang.org,direct`.

But when running `go env` in my terminal , it works.
```bash
$ go env | grep GOPROXY
GOPROXY="https://goproxy.io"
```

### Steps to reproduce the behavior:
1. Go to 'vscode bash', run `go env | grep GOPROXY` , GOPROXY="https://goproxy.io"
2. Click on > `Go: Locate Configured Go Tools` , the GOPROXY="https://proxy.golang.org,direct"

**Comment by hyangah** [comment]
@why0406 There are multiple ways:

1) `go env -w GOPROXY="https://goproxy.io"`: See `go help env` for details 
2) add the env var to your login shell (`~/.profile` or `~/.bash_profile` or `~/.zprofile` depending on your login shell setup) and relaunch the vscode to pick up the new env setup.
3) or `"go.toolsEnvVars": { "GOPROXY": "https://goproxy.io" }` from your settings.json.
