### ISSUE TITLE
Failed to find the "go" binary in either。GOROOT() or PATH(/usr/bin:/bin:/usr/sbin:/sbin). Check PATH, or Install Go and reload the window.

### ISSUE THREAD

**Issue by bajizhh** [golang/vscode-go#2083]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/19441074/155643013-7e590ebd-e70f-47ec-bf69-703c6691904a.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/19441074/155644417-9e54fcea-ec42-4de8-8f1e-846637bc2372.png">

➜  ~ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/bajizhh/Library/Caches/go-build"
GOENV="/Users/bajizhh/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bajizhh/sys/sbin/go/gopath/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/bajizhh/sys/sbin/go/gopath:/Users/bajizhh/repos/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/Users/bajizhh/sys/sbin/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/bajizhh/sys/sbin/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/q_/vd1fh3l50qj3wkk4q9qm4rj80000gn/T/go-build3935183078=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by bajizhh** [comment]
how to fix this?

**Comment by hyangah** [comment]
Add the path to Go binary in your `PATH` (is it `/Users/bajizhhsys/sbin/go/bin`?)
and make sure your VS Code launches with the PATH. 
As the error message shows, the current `PATH` VS Code was launched with are `/usr/bin:/bin:/usr/sbin:/sbin`. 

Or as a last resort, you can explicitly set `"go.alternateTools": { "go": "<path/to/go>" }`.

**Comment by SeibertronSS** [comment]
Delete the .vscode-server ?
