### ISSUE TITLE
gopls: high memory usage

### ISSUE THREAD

**Issue by blurh** [golang/vscode-go#2092]
\> top
```
top - 23:41:01 up  1:13,  2 users,  load average: 3.10, 3.74, 4.91
Tasks: 232 total,   1 running, 231 sleeping,   0 stopped,   0 zombie
%Cpu(s): 19.0 us,  2.1 sy,  0.0 ni, 69.7 id,  9.1 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16543528 total,  4293568 free, 11385016 used,   864944 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  5011284 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                           
 17111 root      20   0 9598468   7.9g  10084 S  75.7 50.0   4:09.29 /opt/gowork/bin/gopls -mode=stdio
 ```
 
 \> gopls version 
 ```
golang.org/x/tools/gopls v0.8.0
    golang.org/x/tools/gopls@v0.8.0 h1:a71KO95TfIvCCMQJrZBSQIGQ9lkc0kWL+dSlEdZd7HI=
```

**Comment by szmcdull** [comment]
How to install gopls v0.8.0. It fails to install:

```
d:\>go\bin\go install golang.org/x/tools/gopls@latest
go: downloading honnef.co/go/tools v0.2.2
go: downloading mvdan.cc/gofumpt v0.3.0
golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:13:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
        server response: Not Found
golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:14:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
        server response: Not Found
golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:15:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
        server response: Not Found
golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:16:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
        server response: Not Found
golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:17:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
        server response: Not Found
golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\hooks.go:15:2: mvdan.cc/gofumpt@v0.3.0: verifying module: mvdan.cc/gofumpt@v0.3.0: reading https://gosum.io/lookup/mvdan.cc/gofumpt@v0.3.0: 404 Not Found
        server response: Not Found
```

**Comment by blurh** [comment]
> How to install gopls v0.8.0. It fails to install:
> 
> ```
> d:\>go\bin\go install golang.org/x/tools/gopls@latest
> go: downloading honnef.co/go/tools v0.2.2
> go: downloading mvdan.cc/gofumpt v0.3.0
> golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:13:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
>         server response: Not Found
> golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:14:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
>         server response: Not Found
> golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:15:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
>         server response: Not Found
> golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:16:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
>         server response: Not Found
> golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\analysis.go:17:2: honnef.co/go/tools@v0.2.2: verifying module: honnef.co/go/tools@v0.2.2: reading https://gosum.io/lookup/honnef.co/go/tools@v0.2.2: 404 Not Found
>         server response: Not Found
> golibs\pkg\mod\golang.org\x\tools\gopls@v0.8.0\internal\hooks\hooks.go:15:2: mvdan.cc/gofumpt@v0.3.0: verifying module: mvdan.cc/gofumpt@v0.3.0: reading https://gosum.io/lookup/mvdan.cc/gofumpt@v0.3.0: 404 Not Found
>         server response: Not Found
> ```

\> curl -s https://gosum.io/lookup/honnef.co/go/tools@v0.2.2 -w %{http_code} -o /dev/null
```
404
```
\> curl -s https://sum.golang.org/lookup/honnef.co/go/tools@v0.2.2 -w %{http_code} -o /dev/null
```
200
```

gosum.io returns 404, maybe you should try use sum.golang.org
```
set GOSUMDB=sum.golang.org
go install golang.org/x/tools/gopls@latest
```

or set it off
```
set GOSUMDB=off
go install golang.org/x/tools/gopls@latest
```

**Comment by findleyr** [comment]
Hi, how large (approximately) is the project you are working on? E.g. how many files / packages?

That gopls uses a lot of memory is a known issue, that we have plans to work on in the coming quarters. I just want to verify that there is nothing else going on here.

Which version of Go are you using?

**Comment by blurh** [comment]
> Hi, how large (approximately) is the project you are working on? E.g. how many files / packages?
> 
> That gopls uses a lot of memory is a known issue, that we have plans to work on in the coming quarters. I just want to verify that there is nothing else going on here.
> 
> Which version of Go are you using?

well... i add to much other project to my vscode workspace
> find -type f | wc -l 
> 183349

my go version is:

**Comment by blurh** [comment]
> Hi, how large (approximately) is the project you are working on? E.g. how many files / packages?

well, i added too many other projects to my vscode workspace
```
find -type f | wc -l 
183349
```

> 
> Which version of Go are you using?

my go version is
```
go version 
go version go1.17.3 linux/amd64
```
