### ISSUE TITLE
Smart select not too smart

### ISSUE THREAD

**Issue by dodalovic** [golang/vscode-go#2099]
It should select `fmt.Sprintf("whatever")`, but it doesn't

![Kooha-03-10-2022-22-04-27](https://user-images.githubusercontent.com/6358061/157754623-48cce18b-6257-4914-a66f-ddf4dcf65e08.gif)

---
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T15:36:26.048Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.11-76051611-generic
---

**Comment by hyangah** [comment]
@dodalovic can you please file an issue in the vscode issue tracker? That's not the functionality of this extension. If vscode needs extra info to be provided by this extension, please let us know.

**Comment by smallming** [comment]
Can we reopen this issue? Based on @hyangah's recommendation, OP created the corresponding issue at https://github.com/microsoft/vscode/issues/144881 but issue was closed with the following feedback:

> The vscode-go extension is the ideal place for this feature

Thoughts?
