### ISSUE TITLE
Download Go plugin "Server returned 404"

### ISSUE THREAD

**Issue by Alan-LOL** [golang/vscode-go#210]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- <Paste go version here>
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.8.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.4
- Run `go env` to get the go development environment details
	- <Paste the output here>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by stamblerre** [comment]
Are you able to provide a screenshot or give a summary of what happened? The extension is available in the VS Code Marketplace (https://marketplace.visualstudio.com/items?itemName=golang.Go), so any installation issues should probably be reported to https://github.com/microsoft/vscode.
