### ISSUE TITLE
Highlight package names of import paths

### ISSUE THREAD

**Issue by kidlj** [golang/vscode-go#2104]
**Is your feature request related to a problem? Please describe.**

When we have many imports, it's hard to locate the import package names.

**Describe the solution you'd like**

It's better to highlight the package names of import paths.

**Describe alternatives you've considered**
None.

**Additional context**

For the example as presented in the screenshot, we'd better highlight package names in white color, just like what has been done to custom import name `v1` and `metav1`.

<img width="706" alt="截屏2022-03-13 17 30 29" src="https://user-images.githubusercontent.com/300616/158053564-7fd1d7f3-61f2-4ebc-8a7a-e904b206e6b5.png">

**Comment by suzmue** [comment]
@kidlj The extension provides this functionality through the gopls semantic tokens feature.

Could you please add the following to your settings to enable semantic tokens?
```
"gopls": {
    "ui.semanticTokens": true
}
```

**Comment by kidlj** [comment]
> @kidlj The extension provides this functionality through the gopls semantic tokens feature.
> 
> Could you please add the following to your settings to enable semantic tokens?
> 
> ```
> "gopls": {
>     "ui.semanticTokens": true
> }
> ```

Sure, added and problem solved, and the editor became more colorful. Thank you.
