### ISSUE TITLE
vscode crashed on MacOS when debug go code at line around exec

### ISSUE THREAD

**Issue by morningspace** [golang/vscode-go#2116]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.16.6 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.8.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.65.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "go.useLanguageServer": true,
}
```

### Describe the bug

I am trying to use vscode to debug go code as usual on my MacOS, but when I step at the line around `exec` to run some executable command (or process), vscode will crash and show the following dialog:

![image](https://user-images.githubusercontent.com/16119920/158803000-a28eb7f3-223c-4250-b3f2-6985f5ba7065.png)

I am not sure if this is related to MacOS security restriction. I'm using MacOS Monterey v12.2.1. Any advice would be really appreciated, e.g.: if there is a way to collect more logs for the crash, so that can better understand the root cause.

**Comment by suzmue** [comment]
@morningspace It looks like your whole VS Code window is crashing, could you file an issue to the [vscode](https://github.com/microsoft/vscode) project?

If you could also share the exact steps you took that caused it to crash that may be helpful! Thanks!

**Comment by morningspace** [comment]
Hi @suzmue actually I opened an issue in vscode project first, but was closed by someone and suggested to open it here as it seems to be caused by extension. See: https://github.com/microsoft/vscode/issues/145280

Re: the steps, I am trying to debug the project: https://github.com/multicloudlab/crossplane-provider-ansible, starting at https://github.com/multicloudlab/crossplane-provider-ansible/blob/main/cmd/provider/main.go as the main entrance, using below `launch.json`:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${file}",
            "args": [
                "--debug"
            ]
        },
    ]
}
```

The error occurred at the line as follows where the code is trying to execute a external command, [ansible-runner](https://ansible-runner.readthedocs.io/en/stable/index.html) in this case:

![image](https://user-images.githubusercontent.com/16119920/159107937-f8880f5f-06b5-4a9a-945b-2b18d54b96a2.png)

**Comment by polinasok** [comment]
Are you able to debug this with [dlv terminal](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_debug.md) without vscode?
What exactly is the external command supposed to trigger?
