### ISSUE TITLE
Support generate implement methods code

### ISSUE THREAD

**Issue by n0trace** [golang/vscode-go#2118]
**Is your feature request related to a problem? Please describe.**
Support generate implement methods code

**Additional context**
like goland
![image](https://user-images.githubusercontent.com/18096911/158950548-538bdc88-1e22-4dbe-af5b-a52600f1f456.png)
![image](https://user-images.githubusercontent.com/18096911/158950630-58434963-6090-4dc1-8ed2-db8eb9ed170c.png)
![image](https://user-images.githubusercontent.com/18096911/158950684-32edc01d-4d0d-4d23-8143-32eb163baf82.png)

**Comment by hyangah** [comment]
Currently two ways:
* Go: Generate Interface Stubs https://github.com/golang/vscode-go/blob/master/docs/features.md#generate-interface-implementation
* Gopls-provided code action: shown in "New code action to add missing method stubs" of [gopls v0.8.0 release note](https://github.com/golang/tools/releases/tag/gopls%2Fv0.8.0)

**Comment by findleyr** [comment]
Hi, closing as it seems like this question is answered. Please reopen if there's something more to do.
