### ISSUE TITLE
Intellisense is not working properly, in Golang, Visual Studio

### ISSUE THREAD

**Issue by ijasmoopan** [golang/vscode-go#2126]
We have written the
Issue Type: <b>Bug</b>

In my Visual Studio, Intellisense is not working properly

Extension version: 0.32.0
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.02GB free)|
|Process Argv|--crash-reporter-id c365ad1d-1957-4b2b-a1d8-de87e61cc2d2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvidc:30447482
vscaat:30438848
pynewfile477cf:30450039

```

</details>

 needed data into your clipboard because it was too large to send. Please paste.

**Comment by hyangah** [comment]
@ijasmoopan We need more information. Can you please follow the troubleshooting guide https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md? Thanks!
