### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SMauricioEspinosaB** [golang/vscode-go#213]
- Issue Type: `Bug`
- Extension Name: `Go`
- Extension Version: `0.14.4`
- OS Version: `Darwin x64 19.5.0`
- VSCode version: `1.46.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stamblerre** [comment]
@SMauricioEspinosaB: Can you please provide information about the problem?
