### ISSUE TITLE
Different error msg for the same code while using ssh remote and local vscode.

### ISSUE THREAD

**Issue by lhiamgeek** [golang/vscode-go#2134]
The situation is show as the following:
1. at remote ssh server:
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/26346086/159861236-24a66aee-ab17-47a3-8566-9cd9e5bf60bf.png">
2. at local:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/26346086/159861385-a609d8b5-7eed-48e9-8ee6-f5c0b4571c5d.png">
3. vscode version:
Version: 1.65.2 (Universal)
4. go plugin vesion:
v0.32.0

**Comment by findleyr** [comment]
Hi, can you please compare your gopls version locally and remotely? (run `gopls version`)

**Comment by lhiamgeek** [comment]
local:
golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=
remote:
golang.org/x/tools/gopls@v0.8.1 h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=

**Comment by hyangah** [comment]
From the screenshot, I am guessing the diagnostic message comes from [the legacy checker](https://github.com/golang/vscode-go/blob/e2a7fb523acffea3427ad7e369c3b2abc30b775b/src/goMain.ts#L254) - which is supposed to be [disabled when gopls is in use](https://github.com/golang/vscode-go/blob/master/src/goCheck.ts#L65-L97).

@lhiamgeek Can you please check if the gopls is in use? When gopls is configured to run, you will see ⚡ is displayed next to the Go version. (https://github.com/golang/vscode-go/blob/master/docs/ui.md#language-server-status)
If gopls seems active, please share your settings.json and the gopls trace for the remote ssh case.

https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information

Thanks!

**Comment by lhiamgeek** [comment]
1.  the remote gopls is in use at the remote server.
2. the go settings:
"go.autocompleteUnimportedPackages": true,
    "go.enableCodeLens": {
        "references": true
    },
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "gopls": {
        "ui.completion.usePlaceholders": true,
    },
    "go.lintOnSave": "workspace",
    "go.toolsManagement.autoUpdate": true,
    "go.addTags": {
        "tags": "json",
        "options": "json=omitempty",
        "promptForTags": true,
        "transform": "camelcase",
        "template": ""
    },
    "go.languageServerFlags": [
        "-rpc.trace"
    ],
     "go.coverOnSingleTest": true,
    "go.coverageDecorator": {
        "type": "gutter",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "blockred"
    },
    "go.coverOnSave": true,
    "go.testExplorer.alwaysRunBenchmarks": true,
"go.editorContextMenuCommands": {
        "removeTags": true
    },
    "go.lintFlags": [
        "-c",
        "~/.golangci.yml",
        "--issues-exit-code=0"
    ],
 "go.testTimeout": "5s",
    "go.lintTool": "golangci-lint"
3. the gopls trace for remote ssh:
[Trace - 10:03:05.374 AM] Sending request 'textDocument/codeAction - (108)'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go"},"range":{"start":{"line":37,"character":6},"end":{"line":37,"character":6}},"context":{"diagnostics":[]}}


[Trace - 10:03:05.375 AM] Received response 'textDocument/codeAction - (108)' in 0ms.
Result: null


[Trace - 10:03:09.549 AM] Sending request 'shutdown - (109)'.
Params: 


[Trace - 10:03:09.549 AM] Received response 'shutdown - (109)' in 0ms.
Result: null


[Trace - 10:03:09.550 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2022/03/29 10:03:09 Shutdown session\n\tshutdown_session=1\n"}


[Trace - 10:03:09.611 AM] Sending request 'initialize - (0)'.
Params: {"processId":21028,"clientInfo":{"name":"Visual Studio Code","version":"1.65.2"},"locale":"en","rootPath":"/home/me/gopath/src/lhrpc","rootUri":"file:///home/me/gopath/src/lhrpc","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]}},"codeLens":{"refreshSupport":true},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true,"semanticTokens":{"refreshSupport":true},"fileOperations":{"dynamicRegistration":true,"didCreate":true,"didRename":true,"didDelete":true,"willCreate":true,"willRename":true,"willDelete":true}},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]},"codeDescriptionSupport":true,"dataSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true},"activeParameterSupport":true},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true,"tagSupport":{"valueSet":[1]},"labelSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"disabledSupport":true,"dataSupport":true,"resolveSupport":{"properties":["edit"]},"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"honorsChangeAnnotations":false},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true,"prepareSupportDefaultBehavior":1,"honorsChangeAnnotations":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":true},"semanticTokens":{"dynamicRegistration":true,"tokenTypes":["namespace","type","class","enum","interface","struct","typeParameter","parameter","variable","property","enumMember","event","function","method","macro","keyword","modifier","comment","string","number","regexp","operator"],"tokenModifiers":["declaration","definition","readonly","static","deprecated","abstract","async","modification","documentation","defaultLibrary"],"formats":["relative"],"requests":{"range":true,"full":{"delta":true}},"multilineTokenSupport":false,"overlappingTokenSupport":false},"linkedEditingRange":{"dynamicRegistration":true}},"window":{"showMessage":{"messageActionItem":{"additionalPropertiesSupport":true}},"showDocument":{"support":true},"workDoneProgress":true},"general":{"regularExpressions":{"engine":"ECMAScript","version":"ES2020"},"markdown":{"parser":"marked","version":"1.1.0"}}},"initializationOptions":{"ui.completion.usePlaceholders":true},"trace":"off","workspaceFolders":[{"uri":"file:///home/me/gopath/src/lhrpc","name":"lhrpc"}]}


[Trace - 10:03:09.612 AM] Received response 'initialize - (0)' in 1ms.
Result: {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."],"completionItem":{}},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor.extract","refactor.rewrite","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["gopls.add_dependency","gopls.add_import","gopls.apply_fix","gopls.check_upgrades","gopls.edit_go_directive","gopls.gc_details","gopls.generate","gopls.generate_gopls_mod","gopls.go_get_package","gopls.list_imports","gopls.list_known_packages","gopls.regenerate_cgo","gopls.remove_dependency","gopls.run_tests","gopls.start_debugging","gopls.test","gopls.tidy","gopls.toggle_gc_details","gopls.update_go_sum","gopls.upgrade_dependency","gopls.vendor"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"{\"Path\":\"golang.org/x/tools/gopls\",\"Main\":{\"Path\":\"golang.org/x/tools/gopls\",\"Version\":\"v0.8.1\",\"Sum\":\"h1:q5nDpRopYrnF4DN/1o8ZQ7Oar4Yd4I5OtGMx5RyV2/8=\",\"Replace\":null},\"Deps\":[{\"Path\":\"github.com/BurntSushi/toml\",\"Version\":\"v1.0.0\",\"Sum\":\"h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=\",\"Replace\":null},{\"Path\":\"github.com/google/go-cmp\",\"Version\":\"v0.5.7\",\"Sum\":\"h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=\",\"Replace\":null},{\"Path\":\"github.com/sergi/go-diff\",\"Version\":\"v1.1.0\",\"Sum\":\"h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\",\"Replace\":null},{\"Path\":\"golang.org/x/mod\",\"Version\":\"v0.6.0-dev.0.20220106191415-9b9b3d81d5e3\",\"Sum\":\"h1:kQgndtyPBW/JIYERgdxfwMYh3AVStj88WQTlNDi2a+o=\",\"Replace\":null},{\"Path\":\"golang.org/x/sync\",\"Version\":\"v0.0.0-20210220032951-036812b2e83c\",\"Sum\":\"h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=\",\"Replace\":null},{\"Path\":\"golang.org/x/sys\",\"Version\":\"v0.0.0-20220209214540-3681064d5158\",\"Sum\":\"h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=\",\"Replace\":null},{\"Path\":\"golang.org/x/text\",\"Version\":\"v0.3.7\",\"Sum\":\"h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=\",\"Replace\":null},{\"Path\":\"golang.org/x/tools\",\"Version\":\"v0.1.10-0.20220315142906-0c66750444e6\",\"Sum\":\"h1:AOqgMGxa5hFduIlFkKEX87HoRPO9wjyfhqf1yqwybeg=\",\"Replace\":null},{\"Path\":\"golang.org/x/xerrors\",\"Version\":\"v0.0.0-20200804184101-5ec99f83aff1\",\"Sum\":\"h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=\",\"Replace\":null},{\"Path\":\"honnef.co/go/tools\",\"Version\":\"v0.2.2\",\"Sum\":\"h1:MNh1AVMyVX23VUHE2O27jm6lNj3vjO5DexS4A1xvnzk=\",\"Replace\":null},{\"Path\":\"mvdan.cc/gofumpt\",\"Version\":\"v0.3.0\",\"Sum\":\"h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=\",\"Replace\":null},{\"Path\":\"mvdan.cc/xurls/v2\",\"Version\":\"v2.4.0\",\"Sum\":\"h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=\",\"Replace\":null}],\"GoVersion\":\"go1.17.5\",\"Version\":\"v0.8.1\"}"}}


[Trace - 10:03:09.620 AM] Sending notification 'initialized'.
Params: {}


[Trace - 10:03:09.620 AM] Sending notification 'textDocument/didOpen'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go","languageId":"go","version":3,"text":"package lhrpc\n\nimport (\n\t\"lhrpc/pkg/codec\"\n\t\"log\"\n\t\"net\"\n)\n\n// MagicNumber is the lhrpc indicator.\nconst MagicNumber = 0x3bef5c\n\n// Option is the configurable option for lhrpc's codec.\ntype Option struct {\n\tMagicNumber int        // MagicNumber marks that this is a lhrpc request.\n\tCodecType   codec.Type // client may choose different Codec to encode body.\n}\n\n// DefaultOption uses the GobCodec as the default codec.\nvar DefaultOption = &Option{\n\tMagicNumber: MagicNumber,\n\tCodecType:   codec.GobType,\n}\n\n// Server is the server implementation of lhrpc.\ntype Server struct{}\n\n// NewServer returns a new lhrpc server.\nfunc NewServer() *Server {\n\treturn &Server{}\n}\n\n// DefaultServer is the default instance of lhrpc.\nvar DefaultServer = NewServer()\n\n// Accept accepts connection on the listener and\n// serves requests for each incoming connection.\nfunc (server *Server) Accept(lis net.Listener) {\n\tfor {\n\t\tconn, err := lis.Accept()\n\t\tif err != nil {\n\t\t\tlog.Println(\"rpc server: accept error:\", err)\n\t\t\treturn\n\t\t}\n\t\tgo server.ServeConn(conn)\n\t}\n}\n\n// Accept accepts connections on the listener\n// and serve requests for each incoming connection.\nfunc Accept(lis net.Listener) { DefaultServer.Accept(lis) }\n"}}


[Trace - 10:03:09.620 AM] Received request 'window/workDoneProgress/create - (1)'.
Params: {"token":"5577006791947779410"}


[Trace - 10:03:09.621 AM] Sending response 'window/workDoneProgress/create - (1)' in 0ms.
Result: 


[Trace - 10:03:09.621 AM] Received notification '$/progress'.
Params: {"token":"5577006791947779410","value":{"kind":"begin","title":"Setting up workspace","message":"Loading packages..."}}


[Trace - 10:03:09.621 AM] Received request 'workspace/configuration - (2)'.
Params: {"items":[{"scopeUri":"file:///home/me/gopath/src/lhrpc","section":"gopls"}]}


[Trace - 10:03:09.623 AM] Sending response 'workspace/configuration - (2)' in 1ms.
Result: [{"ui.completion.usePlaceholders":true}]


[Trace - 10:03:09.632 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2022/03/29 10:03:09 go env for /home/me/gopath/src/lhrpc\n(root /home/me/gopath/src/lhrpc)\n(go version go version go1.17.5 linux/amd64)\n(valid build configuration = true)\n(build flags: [])\


[Info  - 10:03:09 AM] 2022/03/29 10:03:09 go env for /home/me/gopath/src/lhrpc
(root /home/me/gopath/src/lhrpc)
(go version go version go1.17.5 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOROOT=/usr/local/go
GOFLAGS=
GOCACHE=/home/me/.cache/go-build
GOMODCACHE=/home/me/gopath/pkg/mod
GOWORK=
GO111MODULE=on
GOMOD=/home/me/gopath/src/lhrpc/go.mod
GOINSECURE=
GOPATH=/home/me/gopath


[Trace - 10:03:09.677 AM] Sending request 'textDocument/documentSymbol - (1)'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go"}}


[Trace - 10:03:09.677 AM] Sending request 'textDocument/codeAction - (2)'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go"},"range":{"start":{"line":37,"character":6},"end":{"line":37,"character":6}},"context":{"diagnostics":[]}}


[Trace - 10:03:09.679 AM] Sending request 'textDocument/documentLink - (3)'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go"}}


[Trace - 10:03:09.710 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2022/03/29 10:03:09 go/packages.Load\n\tsnapshot=0\n\tdirectory=/home/me/gopath/src/lhrpc\n\tquery=[builtin lhrpc/...]\n\tpackages=5\n"}


[Info  - 10:03:09 AM] 2022/03/29 10:03:09 go/packages.Load
	snapshot=0
	directory=/home/me/gopath/src/lhrpc
	query=[builtin lhrpc/...]
	packages=5

[Trace - 10:03:09.741 AM] Received notification '$/progress'.
Params: {"token":"5577006791947779410","value":{"kind":"end","message":"Finished loading packages."}}


[Trace - 10:03:09.742 AM] Received request 'client/registerCapability - (3)'.
Params: {"registrations":[{"id":"workspace/didChangeWatchedFiles-0","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"**/*.{go,mod,sum,work}","kind":7},{"globPattern":"{/home/me/gopath/src/lhrpc/pkg,/home/me/gopath/src/lhrpc/pkg/codec,/home/me/gopath/src/lhrpc/pkg/lhrpc}","kind":7}]}}]}


[Trace - 10:03:09.743 AM] Sending response 'client/registerCapability - (3)' in 0ms.
Result: 


[Trace - 10:03:09.748 AM] Received request 'client/registerCapability - (4)'.
Params: {"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"}]}


[Trace - 10:03:09.748 AM] Sending response 'client/registerCapability - (4)' in 0ms.
Result: 


[Trace - 10:03:09.850 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2022/03/29 10:03:09 falling back to safe trimming due to type errors: [/usr/local/go/src/runtime/vdso_linux.go:55:38: invalid operation: division by zero /usr/local/go/src/runtime/vdso_linux.go:56:38: invalid operation: division by zero] or still-missing identifiers: map[memRecordCycle:true pageBits:true]\n\tpackage=\"runtime\"\n"}


[Info  - 10:03:09 AM] 2022/03/29 10:03:09 falling back to safe trimming due to type errors: [/usr/local/go/src/runtime/vdso_linux.go:55:38: invalid operation: division by zero /usr/local/go/src/runtime/vdso_linux.go:56:38: invalid operation: division by zero] or still-missing identifiers: map[memRecordCycle:true pageBits:true]
	package="runtime"

[Trace - 10:03:09.882 AM] Sending request 'textDocument/foldingRange - (4)'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go"}}


[Trace - 10:03:09.938 AM] Sending request 'textDocument/codeLens - (5)'.
Params: {"textDocument":{"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go"}}


[Trace - 10:03:09.962 AM] Received response 'textDocument/documentSymbol - (1)' in 285ms.
Result: [{"name":"MagicNumber","detail":"untyped int","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":9,"character":28}},"selectionRange":{"start":{"line":9,"character":6},"end":{"line":9,"character":17}}},{"name":"Option","detail":"struct{...}","kind":23,"range":{"start":{"line":12,"character":5},"end":{"line":15,"character":1}},"selectionRange":{"start":{"line":12,"character":5},"end":{"line":12,"character":11}},"children":[{"name":"MagicNumber","detail":"int","kind":8,"range":{"start":{"line":13,"character":1},"end":{"line":13,"character":16}},"selectionRange":{"start":{"line":13,"character":1},"end":{"line":13,"character":12}}},{"name":"CodecType","detail":"string","kind":8,"range":{"start":{"line":14,"character":1},"end":{"line":14,"character":23}},"selectionRange":{"start":{"line":14,"character":1},"end":{"line":14,"character":10}}}]},{"name":"DefaultOption","detail":"*Option","kind":13,"range":{"start":{"line":18,"character":0},"end":{"line":21,"character":1}},"selectionRange":{"start":{"line":18,"character":4},"end":{"line":18,"character":17}}},{"name":"Server","detail":"struct{...}","kind":23,"range":{"start":{"line":24,"character":5},"end":{"line":24,"character":20}},"selectionRange":{"start":{"line":24,"character":5},"end":{"line":24,"character":11}}},{"name":"NewServer","detail":"()","kind":12,"range":{"start":{"line":27,"character":0},"end":{"line":29,"character":1}},"selectionRange":{"start":{"line":27,"character":5},"end":{"line":27,"character":14}}},{"name":"DefaultServer","detail":"*Server","kind":13,"range":{"start":{"line":32,"character":0},"end":{"line":32,"character":31}},"selectionRange":{"start":{"line":32,"character":4},"end":{"line":32,"character":17}}},{"name":"(*Server).Accept","detail":"(lis net.Listener)","kind":6,"range":{"start":{"line":36,"character":0},"end":{"line":45,"character":1}},"selectionRange":{"start":{"line":36,"character":22},"end":{"line":36,"character":28}}},{"name":"Accept","detail":"(lis net.Listener)","kind":12,"range":{"start":{"line":49,"character":0},"end":{"line":49,"character":59}},"selectionRange":{"start":{"line":49,"character":5},"end":{"line":49,"character":11}}}]


[Trace - 10:03:09.964 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///home/me/gopath/src/lhrpc/pkg/lhrpc/server.go","version":3,"diagnostics":[{"range":{"start":{"line":43,"character":12},"end":{"line":43,"character":21}},"severity":1,"code":"MissingFieldOrMethod","codeDescription":{"href":"https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source=gopls#MissingFieldOrMethod"},"source":"compiler","message":"server.ServeConn undefined (type *Server has no field or method ServeConn)"}]}


[Trace - 10:03:09.964 AM] Received response 'textDocument/codeAction - (2)' in 287ms.
Result: null


[Trace - 10:03:09.969 AM] Received response 'textDocument/documentLink - (3)' in 290ms.
Result: [{"range":{"start":{"line":3,"character":2},"end":{"line":3,"character":17}},"target":"https://pkg.go.dev/lhrpc/pkg/codec?utm_source=gopls"},{"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":5}},"target":"https://pkg.go.dev/log?utm_source=gopls"},{"range":{"start":{"line":5,"character":2},"end":{"line":5,"character":5}},"target":"https://pkg.go.dev/net?utm_source=gopls"}]


[Trace - 10:03:09.969 AM] Received response 'textDocument/foldingRange - (4)' in 87ms.
Result: [{"startLine":2,"startCharacter":8,"endLine":5,"endCharacter":6,"kind":"imports"},{"startLine":12,"startCharacter":20,"endLine":14,"endCharacter":23},{"startLine":18,"startCharacter":28,"endLine":20,"endCharacter":27},{"startLine":27,"startCharacter":26,"endLine":28,"endCharacter":17},{"startLine":34,"startCharacter":48,"endLine":35,"endCharacter":48,"kind":"comment"},{"startLine":36,"startCharacter":48,"endLine":44,"endCharacter":2},{"startLine":37,"startCharacter":6,"endLine":43,"endCharacter":27},{"startLine":39,"startCharacter":17,"endLine":41,"endCharacter":9},{"startLine":47,"startCharacter":45,"endLine":48,"endCharacter":51,"kind":"comment"}]


[Trace - 10:03:09.969 AM] Received response 'textDocument/codeLens - (5)' in 31ms.
Result: null


[Trace - 10:03:39.966 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2022/03/29 10:03:39 background imports cache refresh starting\n"}


[Info  - 10:03:39 AM] 2022/03/29 10:03:39 background imports cache refresh starting

[Trace - 10:03:40.139 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2022/03/29 10:03:40 background refresh finished after 175.45038ms\n"}


[Info  - 10:03:40 AM] 2022/03/29 10:03:40 background refresh finished after 175.45038ms

**Comment by findleyr** [comment]
Thank you for the trace logs.

Those diagnostics don't match in a couple of ways:
- The source is different
- The range is also different

It's also odd that the codeAction was sent 16 minutes after the original diagnostic.

@hyangah should the codeAction diagnostic match exactly (I suspect so), and in that case is it possible that there are multiple sources of diagnostics getting mixed up?

**Comment by hyangah** [comment]
Thanks, @lhiamgeek 

The diagnostic seen from `codeAction` message is whatever reported by the extension (not necessarily originated from gopls) and it's sent when the editor needs a quickfix info (e.g. user's hovering over the diagnostics). 

The only explanation I can come up with is somewhere `"go.languageServerExperimentalFeatures"` is configured with non-default `"diagnostics"` value. The extension's default is true, but in ssh mode there are multiple levels of settings.json involved AFAIK. Can you please check all levels of settings and see if any of them has `"go.languageServerExperimentalFeatures"` setting? 

Command Palette ->
  * Open Settings (JSON)
  * Open Remote Settings (JSON)
  * Open Workspace Settings (JSON)
  
If you find no settings touch that property, maybe try to explicitly set 
```
"go.languageServerExperimentalFeatures": {
   "diagnostics": true
}
```
from the Workspace Settings to see.

If that solves a problem, but you see no settings from Open Settings (JSON) or Open Remote Settings (JSON), I think we need to ask vscode (or vscode remote) team if there is any difference in configuration resolution.

**Comment by lhiamgeek** [comment]
@hyangah After adding :
"go.languageServerExperimentalFeatures": {
   "diagnostics": true
}
to the ssh settings, it works.🚀🚀🚀.
Thank you very much! Really helpful!
