### ISSUE TITLE
Support Show supertypes

### ISSUE THREAD

**Issue by rectcircle** [golang/vscode-go#2142]
I want vscode-go support `>type: show supertypes` feature (or new command).

cmd + shift + p， `>type: show supertypes`, show all interfaces implemented by this type that like to VSCode Java.

![image](https://user-images.githubusercontent.com/18106246/160322628-9e59ea66-a899-4d01-bbe4-dfbfdb790b7a.png)

#### Example

```go
type A struct{}

func (A) String() string { return "a" }

var _ fmt.Stringer = A{} // selection A{}
```

cmd + shift + p, `>type: show supertypes`, show: `fmt.Stringer` .

Note: I think vscode-go should search the modules , go sdk and dependencies module (search scope same as `cmd + t` and `Go to Symbol in Workspace...`)

**Comment by hyangah** [comment]
@rectcircle can you clarify what you meant "supertypes"? 
Unlike Java, there is no concept of "supertypes" in Go. 

A close concept is interface.

If you want to see what "interface" type a given type (e.g. `A`) implements, select `A{}`, click "Find All Implementations" from the context menu, or "Cmd+Shift+P -> "References: Find ALl Implementations", which will open "REFERENCES: IMPLEMENTATION" tab.
