### ISSUE TITLE
gopls: vulncheck crash with type parameters

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#2149]
gopls version: (devel) (go1.18)
gopls flags: -rpc.trace
update flags: proxy
extension version: 0.33.0-dev
go version: 1.18
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 30 Mar 2022 02:25:53 GMT
restart history:
Wed, 30 Mar 2022 02:18:29 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Trying out the gopls.run_vulncheck_exp command and was able to cause it to crash for code with type parameters in the go/ssa package in tools.

main.go:
```
package main

import (
	"golang.org/x/text/language"
)

func main() {
	language.Parse("hello")
}

func F[T any](_ T) {
}
```

go.mod:
```
module github.com/suzmue/helloWorld

go 1.18

require golang.org/x/text v0.0.0-20170915032832-14c0d48ead0c

```

Crash Log:
<pre>panic: T

goroutine 1510 [running]:
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc0009e20d0, {0x205b858, 0xc007a20990}, 0x0)
	  methods.go:237  0xa8c
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc0009e20d0, {0x205b830, 0xc009912de0}, 0x0)
	  methods.go:233  0xca5
golang.org/x/tools/go/ssa.(*Program).needMethods(0xc0009e20d0, {0x205b7b8, 0xc0032f1a00}, 0x0)
	  methods.go:209  0x7c5
golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc0009e20d0, {0x205b7b8, 0xc0032f1a00})
	  methods.go:145  0x49
golang.org/x/tools/go/ssa.(*Package).build(0xc0076d5500)
	  builder.go:2283  0x169
sync.(*Once).doSlow(0xc0076d552c, 0xc001f60f78)
	  once.go:68  0x138
sync.(*Once).Do(0xc0076d552c, 0xc001f60f78)
	  once.go:59  0x45
golang.org/x/tools/go/ssa.(*Package).Build(0xc0076d5500)
	  builder.go:2271  0x5d
golang.org/x/tools/go/ssa.(*Program).Build.func1(0xc0076d5500)
	  builder.go:2255  0x2c
created by golang.org/x/tools/go/ssa.(*Program).Build
	  builder.go:2254  0x1bb
[Info  - 9:18:58 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by zpavlinovic** [comment]
The isolation idea sounds good to me. `govulncheck` can in theory provide json output if needed (I don't believe it is doing that at the moment).

**Comment by timothy-king** [comment]
My inclination is to not be too motivated by the near term state of ssa. If we want separation for other reasons, we should go for it.

**Comment by hyangah** [comment]
gopls 0.8.4 will have the latest updates of SSA package that fix the panics around generics. (https://github.com/golang/go/issues/48525#issuecomment-1128385150)  Thanks @timothy-king
 
Also, we are going to run vulncheck as a separate process in v0.34.0, which helps too.

Verified analysis on the example code no longer crashes.
