### ISSUE TITLE
sum.golang.org not reachable recently

### ISSUE THREAD

**Issue by lijhj** [golang/vscode-go#2154]
Hi,

It's not a bug. We can't post to stackoverflow due to network issue.

After the this go extension is installed on VSCode, the other eight modules like gopls, go-outline, ... can not be installed due to the network problem in our place:

... Get https://sum.golang.org/xxx: dial tcp xxx: i/o timeout

We need to do the following and restart VSCode to have them installed.

Can [sum.golang.org](http://sum.golang.org/) be mapped to GOPROXY when it is set?

$ go env -w GO111MODULE=on
$ go env -w GOPROXY="https://goproxy.io,direct/"
$ go env -w GOSUMDB="[sum.golang.google.cn](http://sum.golang.google.cn/)"

Thanks

**Comment by hyangah** [comment]
```
"go.toolsEnvVars": { 
  "GOSUMDB": "sum.golang.google.cn",
  "GOPROXY": "https://goproxy.io,direct/",
 }
 ```
 
 `GO111MODULE` won't be necessary if you have recent versions of go.
 Let us know how it goes.
