### ISSUE TITLE
Error loading workspace

### ISSUE THREAD

**Issue by lijhj** [golang/vscode-go#2160]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.8.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	-Version: 1.66.0 (Universal)
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/ljh/go
GOROOT: /usr/local/go
PATH: /Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/Library/Apple/usr/bin

	go:	/usr/local/go/bin/go: go version go1.18 darwin/amd64

	go-outline:	/Users/ljh/go/bin/go-outline	(version: v0.0.0-20210608161538-9736a4bde949 built with go: go1.18)
	gotests:	/Users/ljh/go/bin/gotests	(version: v1.6.0 built with go: go1.18)
	gomodifytags:	/Users/ljh/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18)
	impl:	/Users/ljh/go/bin/impl	(version: v1.1.0 built with go: go1.18)
	goplay:	/Users/ljh/go/bin/goplay	(version: v1.0.0 built with go: go1.18)
	dlv:	/Users/ljh/go/bin/dlv	(version: v1.8.2 built with go: go1.18)
	staticcheck:	/Users/ljh/go/bin/staticcheck	(version: v0.3.0 built with go: go1.18)
	gopls:	/Users/ljh/go/bin/gopls	(version: v0.8.2 built with go: go1.18)

go env
Workspace Folder (work): /Users/ljh/Documents/work
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/ljh/Library/Caches/go-build"
	GOENV="/Users/ljh/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/ljh/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/ljh/go"
	GOPRIVATE=""
	GOPROXY="https://goproxy.io,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.google.cn"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.18"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/t4/6c07s48d21dcxdwbr0vq89r80000gn/T/go-build2424684862=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

The code in the modules builds correctly. But in VSCode, the blue status bar on the bottom shows:
Error loading workspace: You are outside of a module and outside of $GOPATH/src. If you are using modules, please open your editor to a directory in your module.

### Steps to reproduce the behavior:
3. See error

$ pwd
/Users/ljh/Documents/work
$
$ find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g' 
.
|____greetings
| |____go.mod
| |____greetings.go
|____hello
| |____morestrings
| | |____reverse.go
| |____go.mod
| |____hello.go
$ 
$ 
$ cat greetings/go.mod 
module example.com/greetings
go 1.18
$ 
$ 
$ cat greetings/greetings.go 
// https://golang.google.cn/doc/tutorial/create-module
package greetings
import "fmt"
func Hello(name string) string {
    message := fmt.Sprintf("Hi, %v. Welcome!", name)
    return message
}
$ 
$ 
$ cat hello/go.mod 
module example.com/hello
go 1.18
replace example.com/greetings => ../greetings
require example.com/greetings v0.0.0-00010101000000-000000000000
$ 
$   
$ cat hello/hello.go 
// https://golang.google.cn/doc/tutorial/call-module-code
package main
import (
    "fmt"
    "example.com/greetings"
    "example.com/hello/morestrings"
)
func main() {
    message := greetings.Hello("Gladys")
    fmt.Println(message)
    fmt.Println(morestrings.ReverseRunes("!oG ,olleH"))
}
$ 
$ 
$ cat hello/morestrings/reverse.go 
// https://golang.google.cn/doc/code
package morestrings
func ReverseRunes(s string) string {
    r := []rune(s)
    for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
        r[i], r[j] = r[j], r[i]
    }
    return string(r)
}
$ 

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![Screen Shot 2022-04-04 at 12 43 46](https://user-images.githubusercontent.com/9011764/161475499-24d9b073-7170-4b74-bcc8-a61364257367.png)

**Comment by lijhj** [comment]
Sorry, I was wrong.
It can be solved by the following command at work directory:
`go work init ./hello`

**Comment by saad-uddin** [comment]
Hello, am also facing the same issue, but even after running the " go work init' the issue isn't resolved. can someone please help me on this.

**Comment by LassiHeikkila** [comment]
@saad-uddin hopefully you have resolved your issue by now, but I want to write this in case someone else comes across the same problem. This is the top google search result when searching "vscode with go workspace not working".

I had same issue when I had a workspace set up so that go.work file was not in a top-level directory. My set up was something like this:
```
toplevel
├── documentation
│   └── docs.md
├── go-project
│   ├── moduleA
│   │   └── go.mod
│   ├── moduleB
│   │   └── go.mod
│   ├── moduleC
│   │   └── go.mod
│   └── go.work
├── notes
│   └── notes.md
└── myproject.code-workspace
```
with the workspace file having content like this:
```json
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {}
}
```

After moving workspace file into `go-project` directory, and editing it include sibling directories from `toplevel` directory, VSCode was happy and did not complain about not being in a module directory anymore.

Working project layout:
```
toplevel
├── documentation
│   └── docs.md
├── go-project
│   ├── moduleA
│   │   └── go.mod
│   ├── moduleB
│   │   └── go.mod
│   ├── moduleC
│   │   └── go.mod
│   ├── go.work
│   └── myproject.code-workspace
└── notes
    └── notes.md
```

Updated workspace definition:
```json
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "../notes"
		},
		{
			"path": "../documentation"
		}
	],
	"settings": {}
}
```

**Comment by DengYuncheng27** [comment]
> 
![image](https://user-images.githubusercontent.com/56923863/221336756-fd31eed5-1653-41a3-bc0d-b893c96b96f0.png)
above is my directory tree
![image](https://user-images.githubusercontent.com/56923863/221336790-a9c5fb5e-dd2e-4094-aa82-0b37c30fc2cc.png)
and i use commond go work init, it amazingly solve this probolem.

**Comment by gnsalok** [comment]
Just run the below command in your workspace :-
```go 
go work use .
```

**Comment by RajeshV89** [comment]
just save it, it worked for me
