### ISSUE TITLE
staticcheck installation fails with go1.16 or older

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2162]
Staticcheck supports only the last two versions of go.
This broke our builders (go1.15, go1.16), and will confuse users who use go1.16 or older.

```
go install honnef.co/go/tools/cmd/staticcheck@latest
failed to install tools: installing honnef.co/go/tools/cmd/staticcheck@latest: go: downloading honnef.co/go/tools v0.3.0
go: downloading golang.org/x/tools v0.1.11-0.20220316014157-77aa08bb151a
go: downloading golang.org/x/exp/typeparams v0.0.0-20220218215828-6cf2b2019[36](https://github.com/golang/vscode-go/runs/5817503085?check_suite_focus=true#step:7:36)e
go: downloading github.com/BurntSushi/toml v0.4.1
Error: ../../../go/pkg/mod/honnef.co/go/tools@v0.3.0/go/ir/builder.go:36:2: //go:build comment without // +build comment
```

**Comment by ykfq** [comment]
Same issue when installing staticcheck in vscode 1.66.1 with go1.16.15, or just installing from command line:
```bash
go install -v honnef.co/go/tools/cmd/staticcheck@latest
go/pkg/mod/honnef.co/go/tools@v0.3.0/go/ir/builder.go:36:2: //go:build comment without // +build comment
```

**Comment by hyangah** [comment]
I hoped to encourage users to utilize `go.toolsManagement.go` and use newer versions of go for tool installations. But, I also noticed major cloud service providers still are stuck in go1.16, so I think we need more careful planning if we want to take that route. For now, in cl/400362, I am making the install picks up v0.2.2 (another special case handling).
