### ISSUE TITLE
debug: enable dlv-dap by default for remote attach in Nightly

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#2168]
See #1517 for inspiration.

**Comment by hyangah** [comment]
Given the very low number of users who use Nightly AND use the `remote` debugging, shouldn't we consider more aggressive approach to reach out to more users? I.e., prompt users about this new `remote` debugging option and provide an option to change a setting that affects the default behavior with one click?

**Comment by suzmue** [comment]
@hyangah It definitely seems likely that turning it on in nightly will not be sufficient to get enough data to enable it by default overall, but I think it still makes sense as an easy first stuff that we can then follow up with a prompt to all Go extension users that use debugging.

**Comment by polinasok** [comment]
I had the same thought. These things are not mutually exclusive.
