### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zewillyan007** [golang/vscode-go#2176]
gopls version: v0.8.2 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.18
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 12 Apr 2022 12:31:20 GMT
restart history:
Tue, 12 Apr 2022 12:30:12 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, can you share the stack trace of the gopls crash (found by navigating to View -> Output -> Tasks -> gopls (server))?
