### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by CodyEasterling** [golang/vscode-go#2177]
gopls version: v0.6.5 (undefined)
gopls flags: 
update flags: proxy
extension version: 0.32.0
go version: 1.11.4
environment: Visual Studio Code darwin
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
issue timestamp: Tue, 12 Apr 2022 17:22:26 GMT
restart history:
Tue, 12 Apr 2022 16:46:00 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, please see https://github.com/golang/vscode-go/issues/1300: gopls needs to be upgraded to v0.6.6+. I recommend using the latest version of gopls.
