### ISSUE TITLE
Force spaces convertion to tabs. 

### ISSUE THREAD

**Issue by erdongfu** [golang/vscode-go#2179]
### Describe the bug
Installing the extension forcefully change the spaces into tabs. I want to keep the spaces but I don't see a way to disable the auto conversion.

**Comment by jamalc** [comment]
You can disable the format on save feature by adding the below to your settings. The formatting tool, [gofmt](https://pkg.go.dev/cmd/gofmt), uses tabs for indentation and this is not configurable.

```
"[go]": {
   "editor.formatOnSave": false
}
```
