### ISSUE TITLE
Adding a warning if a string builder is never actually consumed?

### ISSUE THREAD

**Issue by m1212e** [golang/vscode-go#2181]
When using a string builder like this:

```
func() {
    var data strings.Builder
    data.WriteString("something")
}
```
no warning will be displayed, since the declared variable is used. On other occasions, such as not passing a reference to a json unmarshal, the addon displays a warning that the user might want something different. I think it would be pretty cool to have such a warning when never calling `.String()` or returning the string builder.

**Comment by wtask** [comment]
Such warnings are provided by golangci-lint (or similar) and depend on your local linter configuration. This is not vscode-go issue as I think.

**Comment by m1212e** [comment]
Ahh so this would be a suggestion for the go language server?
