### ISSUE TITLE
Highlight the generics funcs 

### ISSUE THREAD

**Issue by kosmgco** [golang/vscode-go#2191]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.1 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
The generics func name is not highlighted when use go1.18

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/23572982/163758807-2e3c190e-f1e1-452b-ab76-0056c7cc30a9.png)

**Comment by hyangah** [comment]
From https://github.com/golang/vscode-go#features

**⚠️ Note**: the default syntax highlighting for Go files is provided by a [TextMate rule](https://github.com/jeff-hykin/better-go-syntax) embedded in VSCode, not by this extension.

For better syntax highlighting, we recommend enabling [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) by turning on [Gopls' `ui.semanticTokens` setting](https://github.com/golang/vscode-go/blob/master/docs/settings.md#uisemantictokens).

    ```
    "gopls": { "ui.semanticTokens": true }
    ```

**Comment by kosmgco** [comment]
OK, Thanks
