### ISSUE TITLE
Cannot type closing brackets

### ISSUE THREAD

**Issue by kralicky** [golang/vscode-go#2195]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
```
go version go1.18.1 linux/amd64
```
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 h1:kQgndtyPBW/JIYERgdxfwMYh3AVStj88WQTlNDi2a+o=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c h1:rYiuK/jn6TCxjAq1hQ6MR6pgOeP3A5gIHDxgrQ8Vbys=
    golang.org/x/vuln@v0.0.0-20220324005316-18fd808f5c7f h1:9dMzk88fnONra7zrEalqkRMGa9jMGf9B5mdzhYVyI28=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.3.0 h1:2LdYUZ7CIxnYgskbUZfY7FPggmqnh6shBqfWa8Tn3XU=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.67.0-insider
e7c6ad74aff28965d0189ca1dd584f5e9829cf06
x64
```
* Check your installed extensions to get the version of the VS Code Go extension
```
v0.32.0
```
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
	go:	/home/joe/sdk/latest/bin/go: go version go1.18.1 linux/amd64

	go-outline:	/home/joe/go/bin/go-outline	(version: v0.0.0-20210608161538-9736a4bde949 built with go: go1.18)
	gotests:	/home/joe/go/bin/gotests	(version: v1.6.0 built with go: go1.18)
	gomodifytags:	/home/joe/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18)
	impl:	/home/joe/go/bin/impl	(version: v1.1.0 built with go: go1.18)
	goplay:	/home/joe/go/bin/goplay	(version: v1.0.0 built with go: go1.18)
	dlv:	/home/joe/go/bin/dlv	(version: v1.8.2 built with go: go1.18)
	golangci-lint:	/home/joe/go/bin/golangci-lint	(version: v1.45.2 built with go: go1.18)
	gopls:	/home/joe/go/bin/gopls	(version: v0.8.3 built with go: go1.18)
```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
    "go.useLanguageServer": true,
    "go.delveConfig": {
        "showGlobalVariables": true
    },
    "go.vetOnSave": "off",
    "go.toolsManagement.autoUpdate": true,
    "go.lintTool": "golangci-lint",
    "go.lintOnSave": "workspace",
```
### Describe the bug

Typing closing brackets (`}` or `]`) sometimes results in nothing happening. If the developer tools window is open, it will trigger a breakpoint with the following message: `Brackets from different language configuration cannot be used.`
Extension bisect determined that this extension causes the issue.

### Steps to reproduce the behavior:
Type the following: 
```go
var _ = struct{}{
```
Then, attempt to complete the statement by typing `}` on the next line. The closing bracket will not show up. Notably, it will work when typing the closing bracket on the same line.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by ansidev** [comment]
This is from my side. Everything works well.

https://user-images.githubusercontent.com/6688235/164165440-8e81fdb9-3c56-422a-8896-36d0ab24ed73.mov

@kralicky Could you please disable your VSCode settings and check whether the issue is solved?

**Comment by kralicky** [comment]
@ansidev I was able to reproduce this with the latest go nightly extension, but it seems to be intermittent. Starting vscode with no settings caused the issue to go away, and after restoring my settings the issue did not return. If I can reproduce it again, I will let you know.

**Comment by ansidev** [comment]
> @ansidev I was able to reproduce this with the latest go nightly extension, but it seems to be intermittent. Starting vscode with no settings caused the issue to go away, and after restoring my settings the issue did not return. If I can reproduce it again, I will let you know.
> 
> The issue also only occurred when typing closing brackets on the next line, i.e.
> 
> ```go
> var _ = struct{}{
> }
> ```

@kralicky Yes, I know. So please disable your VS Code Go extension settings one by one to determine which setting caused the issue. As provided information, you have six settings to check.

**Comment by findleyr** [comment]
Thanks for the report, and for following up!

> Switching go versions with open editors reliably causes this issue to reappear. 

@kralicky how exactly are you switching go versions? Are you updating your PATH, rebuilding Go, changing VS Code settings?

**Comment by kralicky** [comment]
@findleyr I am switching versions using the bottom toolbar button and selecting a Go version from the command palette list.
![image](https://user-images.githubusercontent.com/8194899/164333441-09ecebfd-08b0-494f-b197-c159f62ae2f5.png)
![image](https://user-images.githubusercontent.com/8194899/164333483-562ffbcf-8bd9-492c-a118-7d417b2c840a.png)

**Comment by findleyr** [comment]
I still don't have any ideas, but a few questions:
- Can you share the rest of your settings? For example, do you have `"editor.autoClosingBrackets": "never"`, since brackets aren't being automatically inserted?
- You said "The issue goes away when closing all editors." Does this reproduce with only a single editor is open?
- I see you're using 1.67.0-insider. Does the issue reproduce with the latest stable release of VS Code (v1.66.0)?

**Comment by findleyr** [comment]
> You said "The issue goes away when closing all editors." Does this reproduce with only a single editor is open?

More specifically, can you provide a precise sequence of steps that reproduces this bug? It sounds to us like it may be a VS Code issue. If we can confirm, it would be good to file upstream.

**Comment by kralicky** [comment]
I am currently unable to reproduce the issue at the moment. It is possible that there were other factors than switching go versions, or maybe today's insiders build doesn't have the problem, but I'll follow up if I can reproduce it again.

**Comment by kralicky** [comment]
Haven't encountered this again in some time, likely no longer an issue.
