### ISSUE TITLE
VSCode Go extension does not allow multiple Go Environment have the same Go version

### ISSUE THREAD

**Issue by ansidev** [golang/vscode-go#2199]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.18.1 and 1.17
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.66.2
    - dfd34e8260c270da74b5c2d86d61aee4b6d56977
    - x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
</details>

### Share the Go related settings you have added/edited

No setting.

### Describe the bug
Install Go 1.18.1 via brew and VSCode Go.
The current Go Environment 1.18.1 in the Go Environment list is Go (VSCode Go).

### Steps to reproduce the behavior:
1. Add Go 1.18.1 (brew) to the Go Environment list.
2. Reload VSCode

Expected: Two Go Environment path with the Go version is 1.18.1
Actual: Only the last added one.

### Screenshots or recordings

https://user-images.githubusercontent.com/6688235/164164567-7f227617-a282-412c-a9de-e8c18e811b50.mov

**Comment by hyangah** [comment]
The QuickPick lists

* Go the extension is currently using.
* Go versions that are under $HOME/sdk (which the extension may have downloaded using `go install go.dev/dl/...`.
* The latest two minor go versions that are not in $HOME/sdk but may be available for download.

There is no plan for supporting other ways. 
For Go versions installed with other package management tools, use PATH environment variable or "Choose From the Browser" menu.

Thanks!

**Comment by ansidev** [comment]
@hyangah So could I request this feature?
