### ISSUE TITLE
Cannot activate the 'Go Coverage Viewer' extension because it depends on an unknown 'ms-vscode.go' extension

### ISSUE THREAD

**Issue by abhijitherekar** [golang/vscode-go#2201]
I am running macOS Catalina version 10.15.7.

Vscode version :

`Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 19.6.0`

Recently, I started seeing this error when I tried to run the go coverage.

**Comment by hyangah** [comment]
@abhijitherekar Maybe the vscode no longer silently redirect `ms-vscode.go` to `golang.go`. Please contact the "Go Coverage Viewer" extension owner, or open an issue to github.com/microsoft/vscode issue tracker for help, if the extension owner no longer manages the extension.
