### ISSUE TITLE
debug: change the default adapter for remote attach to dlv-dap

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#2205]
- [x] #2168*
- [x] review our test coverage and adjust as necessary: cl/550917
   Related tests: #1456, #1043
- [x] switch the default for stable release*
(*) update documentation ([debugging](https://github.com/golang/vscode-go/blob/master/docs/debugging.md) doc and [top-level announcements](https://github.com/golang/vscode-go/blob/master/README.md)) near release time

--

Update:

- https://github.com/go-delve/delve/issues/2958: we agreed to clear breakpoints when the connection is dropped or closed (without terminating the debuggee). This is however not a requirement for this work. So, remove from the requirement for this work.
- (unplanned) prompt users about the new dlv-dap option and/or provide a way to change the default with one click at session start-up
/cc @hyangah @suzmue

**Comment by hyangah** [comment]
https://github.com/go-delve/delve/issues/2958 looks too big a change.

Assuming some problems listed there may occur in the legacy adapter based session, can you please help identifying the feature gap and deliverables? (for example, "A halt from a new connection on entry."  - is the legacy adapter handling this case better? how frequent and severe is the problem?)
