### ISSUE TITLE
When using snippet for writing test functions, extension doesn't import the testing package automatically

### ISSUE THREAD

**Issue by enkeyz** [golang/vscode-go#2208]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.8.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.66.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.32.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- https://gist.github.com/enkeyz/1bdd72fee5c62ef91324ed7666eee981
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
When using snipper for writing test functions, extension doesn't import the testing package. I'm using the language server.

### Steps to reproduce the behavior:
1. Open up a test file, and start writing `func TestFoo`
2. Complete the snippet with Tab
3. Extension doesn't import the testing package

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/17646853/164896099-f6f1e38a-ac5d-4e84-b629-6529e0f3a01a.png)
![image](https://user-images.githubusercontent.com/17646853/164896109-305eae92-7539-4010-932c-f4645bf9255f.png)

**Comment by hyangah** [comment]
@enkeyz package import fix is a code action and triggered by 

  * File save (Cmd+S|Ctrl+S) or
  
  * Quick Fix (hover over diagnostics, or Cmd+.|Ctrl+.)

![Screen Shot 2022-04-25 at 9 16 35 AM](https://user-images.githubusercontent.com/4999471/165096968-04310537-fa39-4bfe-a428-f01bd97e2a23.png)
![Screen Shot 2022-04-25 at 9 10 28 AM](https://user-images.githubusercontent.com/4999471/165097002-01a83491-331a-4947-adca-b37d41438423.png)
