### ISSUE TITLE
Save does not trigger format

### ISSUE THREAD

**Issue by Lachee** [golang/vscode-go#221]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.4 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.46.0 a5d1cc28bb5da32ec67e86cc50f84c67cc690321 x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.14.4
- Run `go env` to get the go development environment details
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lachl\AppData\Local\go-build
set GOENV=D:\Users\Lachee\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\lachl\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=D:\ccache-src\links\gcc.exe
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\lachl\AppData\Local\Temp\go-build254906210=/tmp/go-build -gno-record-gcc-switches
```

### Share the Go related settings you have added/edited

```
{
    "go.toolsEnvVars": {
        "GOOS": "js",
        "GOARCH": "wasm"
    },
    "go.vetFlags": [
        "-composites=false",
    ],
}

```

### Describe the bug
same sort of deal as this issue: https://github.com/microsoft/vscode-go/issues/520
saving (or ctrl+s) does not format the code. Using `alt + shift + f` or `format document` does however. 

I expected the document to be formatted when saved, or an option to enable / disable that feature to be present. I remember early on that this was annoying in some situations, so it would be nice if there was a option to enable/disable formatting on save, but I cannot seem to find it.

`go.lintOnSave` doesn't seem to effect this bug

### Steps to reproduce the behavior:
1. Clone `https://github.com/lachee/noodle`
2. Open the cloned folder as a new workspace
3. Open `matrix.go`
4. Save the file: Notice formatting doesnt update.
5. `Format Document`: Notice the formatting updates.

### Screenshots or recordings
Linik to a MP4 showing the formatting issues: https://i.lu.je/2020/mu9gOB6Ba0.mp4

**Comment by stamblerre** [comment]
Based on https://github.com/golang/vscode-go/issues/219, it seems like you also have the language server enabled. Can you please capture your language server logs by following [these steps](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs)?

**Comment by Lachee** [comment]
> Based on #219, it seems like you also have the language server enabled. Can you please capture your language server logs by following [these steps](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs)?

The resolution of that was to disable the language server.

**Comment by Lachee** [comment]
This has been solved, my own incompetency once again with global settings hiding shit away.
Looks like I had settings from a year or so ago when I tried to use this last time that disabled formatting on save. Sorry for wasting your time. 

Future Readers: Make sure your **USER** settings for VSCode **doesnt** have this:
```
"[go]": {
        "editor.formatOnSave": true,
        "editor.formatOnPaste": false
    },
```
