### ISSUE TITLE
Highlight go in <script type="application/x-go"></script> for .vugu and .html files 

### ISSUE THREAD

**Issue by Mopholo** [golang/vscode-go#2213]
**Possibly related to a conflict with vscode-vugu, if not a requested feature**
Using the "vsvode-vugu" syntax highlighter allows <script type="application/x-go"></script>  blocks in vugu files to be highlighted 2 times out of 10, the other 8 times it displays as plain text.    

Since I have your highlighter installed for GO it might be using your engine to highlight the x-go blocks ( I have no real idea how the plugins work or work together, maybe their plugin is calling yours as the registered GO highlighter? ) 

**Solution I would like**
VUGU allows go code to be used directly in .HTML or .VUGU files using <script type="application/x-go"></script> I would like to use your highlighter in those blocks.  

As mentioned this may be a conflict bug, but if not it would be a nice feature to have when working with the VUGU framework.

**Comment by hyangah** [comment]
Can you please file an issue to vscode-vugu project? For symple programs that can be embeddable inside the script block, I guess they can also write a simple parser from their extension side. 
This extension does not handle .html or .vugu file formats.

Thanks.
