### ISSUE TITLE
Publish extension on open-vsx.org

### ISSUE THREAD

**Issue by meysholdt** [golang/vscode-go#222]
Hi, 

congrats on moving this extension to the Go-Team!

Could you also [publish](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension) the `golang.Go` extension on https://open-vsx.org/ ?

This would make it much easier to use this great extension in project such as
- [gitpod.io](https://gitpod.io)
- [theia-ide.org](https://theia-ide.org)
- [vscodium.com](https://github.com/VSCodium/vscodium/issues/372)
- [code-server](https://github.com/cdr/code-server)

because the [ToS](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf) doesn't allow those projects to obtain the extension from  Microsoft's marketplace:
> Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use Marketplace Offerings with Visual Studio Products and Services.

**Comment by hyangah** [comment]
It looks like the go extension is already published by a published called 'open-vsx', like many other language extensions maintained by it.

**Comment by meysholdt** [comment]
You're referring to the extension [ms-vscode.Go](https://open-vsx.org/extension/ms-vscode/Go), don't you? 

The extension `golang.Go` is not yet published.

**Comment by hyangah** [comment]
@meysholdt Maybe we can contact `open-vsx` to migrate to use the new id. They are managing various extensions for other languages and own the Go extension there anyway.

**Comment by hyangah** [comment]
We will maintain the `latest` branch to have the stable version - so anyone can rebuild the released version from the source. The open-vsx bot will watch the branch and publish to open-vsx.org until we become ready to take the ownership.

**Comment by firelizzard18** [comment]
@hyangah Until someone claims the `golang` namespace on open-vsx.org, anyone can push a new version of the extension.
