### ISSUE TITLE
Textmate scope for function parameters

### ISSUE THREAD

**Issue by enkeyz** [golang/vscode-go#2226]
**Is your feature request related to a problem? Please describe.**
Currently, this extension doesn't support different color for parameter names in functions.
![image](https://user-images.githubusercontent.com/17646853/166806122-38d60591-b046-41d8-b676-6d6f6f44cfcb.png)

**Describe the solution you'd like**
Would be nice to have a new textmake scope, so themes can use it to make the parameters a different color.

**Describe alternatives you've considered**
None.

**Additional context**
Attached picture above.

**Comment by hyangah** [comment]
@enkeyz This extension does not provide TextMate-based syntax highlighting for Go file at all. Please open an issue to https://github.com/jeff-hykin/better-go-syntax/issues 

If you use the language server (`gopls`) I recommend the semantic highlighting functionality instead. https://github.com/golang/vscode-go/wiki/features#syntax-highlighting
