### ISSUE TITLE
gopls: automated issue report (crash) -- Wrong HOME in Remote SSH

### ISSUE THREAD

**Issue by psauvage0** [golang/vscode-go#2228]
gopls version: v0.8.3 (go1.18.1)
gopls flags: -rpc.trace -logfile=/home/user/goplslog
update flags: proxy
extension version: 0.33.0
go version: 1.18.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 05 May 2022 07:54:06 GMT
restart history:
Thu, 05 May 2022 07:52:06 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

When running in remote ssh, gopls fails to start. It will try to restart a few time before stopping. It appears that gopls is trying to create the goplslog file in the wrong home folder (`/home/user/goplslog` instead of `/home/debian/goplslog` in my case).

My $HOME variable from the remote is correctly set to `/home/debian`

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

```
gopls: unable to create log file: open /home/user/goplslog: no such file or directory
[Info  - 7:52:07 AM] Connection to server got closed. Server will restart.
gopls: unable to create log file: open /home/user/goplslog: no such file or directory
[Info  - 7:52:07 AM] Connection to server got closed. Server will restart.
gopls: unable to create log file: open /home/user/goplslog: no such file or directory
[Info  - 7:52:07 AM] Connection to server got closed. Server will restart.
gopls: unable to create log file: open /home/user/goplslog: no such file or directory
[Info  - 7:52:07 AM] Connection to server got closed. Server will restart.
gopls: unable to create log file: open /home/user/goplslog: no such file or directory
[Error - 7:52:07 AM] Connection to server got closed. Server will not be restarted.
```

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

Crash at log file creation

**Comment by hyangah** [comment]
@psauvage0 Can you share your settings.json?
And, if you restart the remote code server (e.g. "Remote-SSH: Kill Current Remote Code Server") and reconnect, does the problem still occur?

**Comment by psauvage0** [comment]
Alright, it was indeed a problem of settings. I had the flag "-logfile=/home/user/goplslog" in user settings instead of remote settings. Thanks for the assist ^^
