### ISSUE TITLE
Option to NOT to select the go code formatter. 

### ISSUE THREAD

**Issue by anilj1** [golang/vscode-go#223]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).
I posted this issue on VSCode team and subsequently discussed it on the Slack channel (with Tim Heckman, Site Reliability Engineer @ Netflix). 
https://github.com/microsoft/vscode/issues/100139 

**Is your feature request related to a problem? Please describe.**
There should be an option 'none' to select from the go code formatter list. I deal with legacy code and the go code formatter formats the code file on save. The go code formatter is selected by default and the user does not have the choice to disable the formatting feature.

**Describe the solution you'd like**
This list should have an option to select 'none'. 
<img width="712" alt="Screen Shot 2020-06-14 at 1 00 23 PM" src="https://user-images.githubusercontent.com/4309366/84607926-d3b46900-ae64-11ea-843c-47a730a9a661.png">

**Describe alternatives you've considered**
Earlier, the option was not to install the 'winterdrache' package, but it got installed and even after removing it, it is picking it. May be I need to clean it properly. 

**Additional context**

**Comment by stamblerre** [comment]
Disabling formatting is possible through the `"editor.formatOnSave"` setting, which is discussed in more detail in the [formatting troubleshooting documentation](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#formatting). You will need to add the following to your settings.json, which can be accessed via the Command Palette (Ctrl+Shift+P) -> Preferences: Open Settings (JSON).

```json5
"[go]": {
    "editor.formatOnSave": false
}
```

**Comment by anilj1** [comment]
I tried that. The aforementioned flag is set to true in my workspace and user settings. However, it is the Go plugin that is overriding it. If I uninstall the Go plugin, it does not format the file.

**Comment by stamblerre** [comment]
> The aforementioned flag is set to true in my workspace and user settings.

Did you mean to say false here?

This setting means that, when you save a file, the extension will not send formatting requests to the extension on save. The Go extension does not manually format files on save, but rather responds to formatting requests by VS Code, so the setting should turn off this behavior.

**Comment by anilj1** [comment]
Ok, got it. I had set this flag outside the "[go]" context. Perhaps that was the reason. After moving the flag inside, it seems to be working.

**Comment by stamblerre** [comment]
Glad to hear you got it working! Closing this issue as a result.
