### ISSUE TITLE
Django and Go

### ISSUE THREAD

**Issue by RamiSJ12** [golang/vscode-go#2233]
I have a project in Django I tried to run it in VSC but led me to error related to GO and the error message is below if anyone can help?

Failed to find the "go" binary in either GOROOT() or PATH(C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Rami\AppData\Local\Microsoft\WindowsApps;C:\Users\Rami\AppData\Roaming\npm;C:\Users\Rami\AppData\Local\Programs\Microsoft VS Code\Microsoft VS Code\bin;C:\Users\Rami\.dotnet\tools). Check PATH, or Install Go and reload the window. If PATH isn't what you expected, see https://github.com/golang/vscode-go/issues/971

**Comment by jamalc** [comment]
Thanks for the report. Could you fill out the following to help us diagnose the issue?



### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.
A clear and concise description of what you expected to happen.

### Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by OneCricketeer** [comment]
Vscode nor Django require Go.

Sounds like you are running a launch configuration that is trying to use the Go binary, which you don't have installed (and shouldn't need)

**Comment by hyangah** [comment]
@RamiSJ12 Can you please check "Output > Log (Extension Host)" and see what triggered activation of the go extension?

<img width="471" alt="Screen Shot 2022-05-17 at 10 00 53 PM" src="https://user-images.githubusercontent.com/4999471/168941773-83014f48-60a6-43a2-9692-cf5e25d2524b.png">

Look for log entries like this -

```
[2022-05-17 20:59:32.021] [exthost] [info] ExtensionService#_doActivateExtension golang.go, startup: false, activationEvent: 'onLanguage:go'
```

In the meantime, you can completely disable the extension for your Django project
(Extensions View -> Find "Go" extension -> Select the gear icon -> Disable (Workspace)).

Thanks.

**Comment by RamiSJ12** [comment]
> 

If it shouldn't need then why keep requesting it?

**Comment by RamiSJ12** [comment]
@OneCricketeer If it shouldn't need then why keep requesting it?

**Comment by RamiSJ12** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/89670401/168963166-914efa92-01b8-4c40-b453-653bc4d2d896.png)
@hyangah this is the output after installing latest PowerShell

**Comment by hyangah** [comment]
If you click the drop down menu on the right side (currently it shows "Code" in your screenshot), you can switch to "Log (Extension Host)". There is a log explaining why the go extension was **activated**.

**Comment by OneCricketeer** [comment]
Your `launch.json` clearly shows you trying to start a `runserver.py` Django/Python script.

Unclear why you're trying to run that with the Go extension, or how your error is related to it

**Comment by hyangah** [comment]
It looks to me that `PATH` is not configured correctly - as a result tools like `python`, `go` can't be located. 
This is not the go extension issue. Closing.
