### ISSUE TITLE
dlv fails to build __debug_bin under VS Code

### ISSUE THREAD

**Issue by valteem** [golang/vscode-go#2234]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	go version go1.17.9 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	Build info
----------
golang.org/x/tools/gopls v0.8.3
    golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 h1:kQgndtyPBW/JIYERgdxfwMYh3AVStj88WQTlNDi2a+o=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c h1:rYiuK/jn6TCxjAq1hQ6MR6pgOeP3A5gIHDxgrQ8Vbys=
    golang.org/x/vuln@v0.0.0-20220324005316-18fd808f5c7f h1:9dMzk88fnONra7zrEalqkRMGa9jMGf9B5mdzhYVyI28=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.3.0 h1:2LdYUZ7CIxnYgskbUZfY7FPggmqnh6shBqfWa8Tn3XU=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.17.9
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	1.67.0
57fd6d0195bb9b9d1b49f6da5db789060795de47
x64
* Check your installed extensions to get the version of the VS Code Go extension
	v0.33.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/ubuntu/go
GOROOT: /usr/local/go
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/go/bin:/usr/local/go/bin:/usr/local/go/bin

	go:	/usr/local/go/bin/go: go version go1.17.9 linux/amd64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/home/ubuntu/go/bin/dlv	(version: v1.8.3 built with go: go1.17.9)
	staticcheck:	/home/ubuntu/go/bin/staticcheck	(version: v0.3.1 built with go: go1.17.9)
	gopls:	/home/ubuntu/go/bin/gopls	(version: v0.8.3 built with go: go1.17.9)

go env
Workspace Folder (debug-bin): /home/ubuntu/00Files/Go/my-snippets/debug-bin
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/ubuntu/.cache/go-build"
	GOENV="/home/ubuntu/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/ubuntu/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/ubuntu/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.17.9"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/ubuntu/00Files/Go/my-snippets/debug-bin/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2679572446=/tmp/go-build -gno-record-gcc-switches"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
"[go]": {

        "editor.insertSpaces": false,
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        },
        "editor.suggest.snippetsPreventQuickSuggestions": false
    }

### Describe the bug
A clear and concise description of what the bug.

Consider debugging the following code:
```
package main

import "os"

func main() {
    os.Args = append(os.Args, "help")   
}
```

To test it with command line arguments I create launch.json as follows:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Test args",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${file}",
            "env": {},
            "args": ["-test.v","--","arg1","arg2","arg3"]
        }
    ]
}
```

When I run Test args configuration from Run and Debug in VS Code I get an error message Failed to launch: could not launch process: open /mypath/__debug_bin: no such file or directory

This error is because for some reason dlv fails to create 'intermediate' binary file __debug_bin from under VS Code.

However, when I run dlv directly from command line

dlv debug -- arg1 arg2 arg3

it works as expected, creates __debug_bin in /mypath directory and all further debugging features (setting breakpoints, stepping over/into, printing variables etc) are available.

Moreover, if I first run dlv debug from command line (creating thus __debug_bin) and then (without quitting dlv) switch to VS Code and run Test args from Run and Debug, it works too. Meaning that VS Code (and dlv somewhere under the hood) catches this __debug_bin and uses it for debugging.

So, the trouble is that dlv fails to build __debug_bin when called from VS Code context.

### Steps to reproduce the behavior:
1. Create file main.go (see above) in /mypath directory. Create VS Code test configuration using launch.json as above
2. Run test configuration from Run and Debug menu
3. See error 'Failed to launch: could not launch process: open /mypath/__debug_bin: no such file or directory'

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by valteem** [comment]
@hyangah  Thank you for the input, I enclose files with output from OUTPUT and DEBUG CONSOLE tabs of VS Code:
[output.log](https://github.com/golang/vscode-go/files/8652812/output.log)
[debug_console.log](https://github.com/golang/vscode-go/files/8652822/debug_console.log)
I use plain stock Ubuntu 18.04, no virus scanners and/or security software enabled

**Comment by hyangah** [comment]
Can you replace `"program": "${file}"` with `"program": "${fileDirname}"`?
Looks like you were browsing `main.go` file, so vscode filled in the field with `"program": "./main.go"` which is not a test file, so build didn't complete. I think delve or go program should provide a better error message, but at least you can avoid this problem by either making sure the test file get focused, or using `fileDirname` to specify the package directory to test.

**Comment by eric-burel** [comment]
If you need to manage multiple launch tasks, this extension may help: https://marketplace.visualstudio.com/items?itemName=DarrenLevine.auto-debug
It let's you use a "Run test" launch task on "_tests" files automatically, and for instance "Run server" for source files.
