### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by iceworldvip** [golang/vscode-go#2237]
gopls version: v0.8.3 (go1.16.15)
gopls flags: 
update flags: proxy
extension version: 0.33.0
go version: 1.16.15
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 12 May 2022 01:31:47 GMT
restart history:
Thu, 12 May 2022 01:27:53 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by iceworldvip** [comment]
[Error - 9:35:57 AM] Connection to server got closed. Server will not be restarted.

**Comment by hyangah** [comment]
Is it possible that the gopls server got killed (e.g. OOM, ...)?

**Comment by iceworldvip** [comment]
What can I do?  There is no more information in the terminal.

And I need to restart the vscode window every time

> Is it possible that the gopls server got killed (e.g. OOM, ...)?

**Comment by findleyr** [comment]
Hi @iceworldvip, can you try looking in `/var/log/messages` to see if there are kernel logs about killing the gopls process? See for example https://stackoverflow.com/questions/624857/finding-which-process-was-killed-by-linux-oom-killer
