### ISSUE TITLE
Support alternate tools for building binaries for debugging

### ISSUE THREAD

**Issue by eandre** [golang/vscode-go#2238]
Hey all, I've been working on improving [Encore's](https://github.com/encoredev/encore) support for Delve debugging in VS Code and have been running into a snag. Encore is a Go framework that does a lot of code generation prior to running go build, so it provides another set of commands for building and testing (as part of the encore command).

This works fine with Delve's "attach to a running process" support, but unfortunately it breaks the "launch" modes since Delve is currently hard-coded to build binaries with `go`. For VS Code I've currently been using `go.alternateTools` to customize this by providing a wrapper script that provides the same interface as go but invokes encore for things like running tests. Delve does not support such a configuration option.

When I brought this up in **#delve** on Gophers Slack they believe this should be changed upstream in VS Code rather than changing how Delve works, to instead of using launch requests building the binary and invoking `dlv dap` with an attach request or similar.

How would you feel about doing that? I'd be happy to do all the work necessary.

**Comment by hyangah** [comment]
@eandre If you name the script `go` and place it in the `PATH`  (or using `go.toolsEnvVar`), doesn't delve use your script as if it's `go`? Your script, of course, should call the real `go`, probably with absolute path to avoid calling itself.

**Comment by eandre** [comment]
Thanks @hyangah, I wasn't aware of `go.toolsEnvVar`. I guess we could do that, but given that we already bundle an Encore specific runtime (with its own `go` command) which we use to build the Encore app, I do worry that it becomes a lot of different `go` binaries that will confuse users. It would work technically but having a differently named binary would be a lot clearer. Still, it's better than nothing.

A related issue is that the configuration is global, but ideally using this separate binary would only happen for Encore applications (identified by the presence of an `encore.app` file in the directory or any parent directory, like `.git`). Can you think of a way for this configuration to only apply to those projects? Or would that require a separate VS Code extension?

**Comment by hyangah** [comment]
@eandre I don't know why `substitutePaths` wouldn't work. Did you try to capture the DAP trace https://github.com/golang/vscode-go/wiki/debugging#collecting-logs and see what file paths are sent back from Delve to the VS Code?

For precompile, I think you may try to utilize the `preLaunchTask` field of launch configuration. Define a task that builds your binary as you want, and run delve using `launch/exec` mode. This won't work with the debug test code lens or test explorer. How about developing an extension that provides default build/test task definition, default launch configuration, and special codelens?
