### ISSUE TITLE
New scope for region comment

### ISSUE THREAD

**Issue by angelsalascalvo** [golang/vscode-go#2241]
Hello! I think it would be quite useful to add a new scope in the extension's syntaxes.json file to have control over comments of type `//#region` ` //#endregion`

Something like:
`region.comment.line.double-slash.go`

A scope for this would allow themes to make a color distinction on those lines corresponding to region type comments.

**Comment by hyangah** [comment]
@angelsalascalvo Can you elaborate more? This extension does not have syntaxes.json file - except for go.mod/go.sum files.   Where should the rule go?
