### ISSUE TITLE
Outline does not show return type for Golang files

### ISSUE THREAD

**Issue by cmprmsd** [golang/vscode-go#2242]
**Is your feature request related to a problem? Please describe.**
Currently the outline shows argument types for functions in the current file. However, the return types are not listed. 

E.g. see this outline:
![image](https://user-images.githubusercontent.com/73472903/168095543-b219c477-893d-46b4-8057-49431fb55533.png)

where the function itself has `[]byte` as return type.
![image](https://user-images.githubusercontent.com/73472903/168095597-aeb6a899-6560-4be4-9247-5361961ed967.png)

Is this something you consider useful?

**Describe the solution you'd like**
The outline should show return types.

Side note: It'd be also nice if the global variables could be collapsed (maybe even default or globally or for a workspace)

**Comment by findleyr** [comment]
Thanks for reporting.

@hyangah -- this happens to be fixed by https://go.dev/cl/405254.
