### ISSUE TITLE
Broken multi go.mod workspace

### ISSUE THREAD

**Issue by sbstp** [golang/vscode-go#2243]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.18 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- ```Build info
        ----------
        golang.org/x/tools/gopls v0.8.3
            golang.org/x/tools/gopls@v0.8.3 h1:Mxm94ix8oSARQ6svioO6SxKEYWT/VCP54/448LOHzrk=
            github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
            github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
            github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
            golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
            golang.org/x/mod@v0.6.0-dev.0.20220106191415-9b9b3d81d5e3 h1:kQgndtyPBW/JIYERgdxfwMYh3AVStj88WQTlNDi2a+o=
            golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
            golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
            golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
            golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c h1:rYiuK/jn6TCxjAq1hQ6MR6pgOeP3A5gIHDxgrQ8Vbys=
            golang.org/x/vuln@v0.0.0-20220324005316-18fd808f5c7f h1:9dMzk88fnONra7zrEalqkRMGa9jMGf9B5mdzhYVyI28=
            golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
            honnef.co/go/tools@v0.3.0 h1:2LdYUZ7CIxnYgskbUZfY7FPggmqnh6shBqfWa8Tn3XU=
            mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
            mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
        go: go1.18
        ```

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- ```1.67.1
        da15b6fd3ef856477bf6f4fb29ba1b7af717770d
        x64
        ```
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.33.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- ```Checking configured tools....
		GOBIN: undefined
		toolsGopath: 
		gopath: /home/simon/go
		GOROOT: /opt/go
		PATH: /opt/go/bin:/home/simon/.local/bin:/home/simon/.cargo/bin:/home/simon/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/simon/.dotnet/tools:/home/simon/go/bin:/home/simon/go/bin
		PATH (vscode launched with): /opt/go/bin:/home/simon/.local/bin:/home/simon/.cargo/bin:/opt/go/bin:/home/simon/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/simon/.dotnet/tools:/home/simon/go/bin:/home/simon/go/bin

			go:	/opt/go/bin/go: go version go1.18 linux/amd64

			gotests:	/home/simon/go/bin/gotests	(version: v1.6.0 built with go: go1.18)
			gomodifytags:	/home/simon/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18)
			impl:	/home/simon/go/bin/impl	(version: v1.1.0 built with go: go1.18)
			goplay:	/home/simon/go/bin/goplay	(version: v1.0.0 built with go: go1.18)
			dlv:	/home/simon/go/bin/dlv	(version: v1.8.3 built with go: go1.18)
			staticcheck:	/home/simon/go/bin/staticcheck	(version: v0.3.1 built with go: go1.18)
			gopls:	/home/simon/go/bin/gopls	(version: v0.8.3 built with go: go1.18)

		go env
		Workspace Folder (salesforce): /home/simon/projects/nesto/backend/salesforce
			GO111MODULE=""
			GOARCH="amd64"
			GOBIN=""
			GOCACHE="/home/simon/.cache/go-build"
			GOENV="/home/simon/.config/go/env"
			GOEXE=""
			GOEXPERIMENT=""
			GOFLAGS=""
			GOHOSTARCH="amd64"
			GOHOSTOS="linux"
			GOINSECURE=""
			GOMODCACHE="/home/simon/go/pkg/mod"
			GONOPROXY="github.com/nestoca"
			GONOSUMDB="github.com/nestoca"
			GOOS="linux"
			GOPATH="/home/simon/go"
			GOPRIVATE="github.com/nestoca"
			GOPROXY="https://proxy.golang.org,direct"
			GOROOT="/opt/go"
			GOSUMDB="sum.golang.org"
			GOTMPDIR=""
			GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
			GOVCS=""
			GOVERSION="go1.18"
			GCCGO="gccgo"
			GOAMD64="v1"
			AR="ar"
			CC="gcc"
			CXX="g++"
			CGO_ENABLED="1"
			GOMOD="/dev/null"
			GOWORK="/home/simon/projects/nesto/backend/salesforce/go.work"
			CGO_CFLAGS="-g -O2"
			CGO_CPPFLAGS=""
			CGO_CXXFLAGS="-g -O2"
			CGO_FFLAGS="-g -O2"
			CGO_LDFLAGS="-g -O2"
			PKG_CONFIG="pkg-config"
			GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3049096489=/tmp/go-build -gno-record-gcc-switches"
			```
</details>

### Share the Go related settings you have added/edited

```
    "gopls": {
        "experimentalWorkspaceModule": true,
    },
    "go.toolsManagement.autoUpdate": true,
```

### Describe the bug
Warnings in every file complaining about not being able to find imports, warnings on the field saying they are undefined. Editor is pretty much unusable. 

We have a project with two go.mod files, we have a a folder called `api` and a folder called `integration/tests` in the project folder. Both of these have a go.mod in them. For about 10 months of so this setup was working perfectly with the `experimentalWorkspaceModule` option. About a month or two ago these errors started occuring. I was hoping it was just a temporary error so I switched to using GoLand for a month or two hoping it would get fixed, but it still hasn't been fixed so I'm taking the time to open a ticket now.

I have tried clearing the cache, modcache, testcache, does not help.

### Steps to reproduce the behavior:
I can't share out proprietary codehbase of course, so I recreated a dummy repo [here](https://github.com/sbstp/vscode-go-error-sample-1) with the same structure as our proprietary repo. I'm not able to replicate the error in the dummy repo at the moment. So it might not be that useful sadly.

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/862368/168326504-255085c2-549f-457d-9548-7face27cf566.png)

**Comment by findleyr** [comment]
Hi, since you're using go 1.18, can you please try removing the `experimentalWorkspaceModule` setting and just using a `go.work` file as described [here](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#go-workspaces-go-118)?

**Comment by sbstp** [comment]
Seems to address the issue, thank you.

**Comment by findleyr** [comment]
Great, thanks for confirming!
