### ISSUE TITLE
go.mod `go list` should not receive all build `buildFlags`

### ISSUE THREAD

**Issue by mkungla** [golang/vscode-go#2248]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.8.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.67.1
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.33.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
  "go.testEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm"
  },
  "go.toolsEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm"
  },
  "go.buildFlags": [
    "-exec",
    "path/to/go_js_wasm_exec"
  ],
  "go.testFlags": [
    "-exec",
    "path/to/go_js_wasm_exec"
  ]
}
```

### Describe the bug

extension throws error on `go.mod` files
```
err: exit status 2: stderr: flag provided but not defined: -exec
usage: go list [-f format] [-json] [-m] [list flags] [build flags] [packages]
Run 'go help list' for details.
: packages.Load error
```

### Steps to reproduce the behavior:
1. Create packages containing `.go` files which all have  `//go:build js && wasm`
2. Use config as shown here
3. Tests and builds work fine
4. But extension throws errors on `go.mod` files

**Comment by findleyr** [comment]
It looks like vscode-go is forwarding this flag to gopls; I think gopls should probably filter this out of `go list`.

**Comment by findleyr** [comment]
Sorry, you're running `go build` with the `-exec` flag? This is not a valid build flag.

```
> go build -exec
flag provided but not defined: -exec
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.
```

Also, you can override what is sent to gopls by setting `gopls.build.buildFlags`.
https://github.com/golang/vscode-go/blob/master/docs/settings.md#gobuildflags

**Comment by mkungla** [comment]
> Sorry, you're running `go build` with the `-exec` flag? This is not a valid build flag.
> 
> ```
> > go build -exec
> flag provided but not defined: -exec
> usage: go build [-o output] [build flags] [packages]
> Run 'go help build' for details.
> ```
> 
> Also, you can override what is sent to gopls by setting `gopls.build.buildFlags`. https://github.com/golang/vscode-go/blob/master/docs/settings.md#gobuildflags

you are right build flags were not needed at all

```json
  "go.buildFlags": [
    "-exec",
    "path/to/go_js_wasm_exec"
  ],
```

**following config is ok**

```json
{
  "go.testEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm"
  },
  "go.toolsEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm"
  },
  "go.testFlags": [
    "-exec",
    "path/to/go_js_wasm_exec"
  ]
}
```
