### ISSUE TITLE
Release - v0.34.0 

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2252]
Highlights
* LSP 3.17 & Require Visual Studio Code 1.67+ (May 2022)
* Major internal code restructuring & code health project (strict mode)
* Bug fixes
   - handling of `TestMain`.
   - vulncheck command improvement.

# Release candidate (June 2022)
- [x] Announce the release, leave enough time for teams to surface any last minute issues that need to get in before freeze. Make sure debugger and gopls teams are looped in as well.
- [x] Check [the milestone](https://github.com/golang/vscode-go/issues?q=milestone%3Av0.34.0) and resolve/move unresolved issues.
- [x] Update `master` for the release
    - [x] Update hardcoded latest version for `gopls`.
    - [x] Update [`CHANGELOG.md`](https://github.com/golang/vscode-go/blob/master/CHANGELOG.md).
    - [x] Make sure the "Thanks" section is up-to-date.
    - [x] Check the Markdown rendering to make sure everything looks good.
- [x] Update `release` for the release
    - [x] Create a branch against `release` for a pull request.
    - [x] Merge changes from `master` to prepare for the release.
    - [x] Change the version in [`package.json`](https://github.com/golang/vscode-go/blob/master/package.json) from a `-dev` suffix
    - [x] Run `npm install` to make sure [`package-lock.json`](https://github.com/golang/vscode-go/blob/master/package.json) is up-to-date
    - [x] Update the license file (`$ tools/license.sh; mv LICENSE.prod LICENSE`)
- [x] Check the [Long Tests status](https://github.com/golang/vscode-go/actions?query=workflow%3A%22Long+Tests%22)  is green. Otherwise, fix the tests, send cls for review, submit them, and repeat.
- [x] Perform manual [smoke tests](https://github.com/golang/vscode-go/blob/master/docs/smoke-test.md)
- [x] Create new RC version tag for v0.34.0-rc.1 at gerrit’s vscode-go [repo management page](https://go-review.googlesource.com/admin/repos/vscode-go,tags)
  - [x] Go to the release page https://github.com/golang/vscode-go/releases and check if the new release candidate is up. If necessary, you can manually edit the comment by clicking the “Edit” button. Don’t mutate uploaded vsix.
  - [x] Ask @golang/tools-team and contributors to this release to test the release candidate

# Final (Release Date: TBD)
-   [x] Tag the new release for v0.34.0
-   [x] Update the release description with CHANGELOG contents
-   [x] Close the milestone

# Prepare for the Next Release
-   [x] Update `master` post-release
    -   [x] Bump the `version` number to the next monthly release in the `master` branch
        -   [x] Update `package.json`
        -   [x] Update `package-lock.json`

**Comment by suzmue** [comment]
v0.34.0 is now available!

https://github.com/golang/vscode-go/releases/tag/v0.34.0
