### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by brodiep21** [golang/vscode-go#2256]
gopls version: (devel) (undefined)
gopls flags: 
update flags: proxy
extension version: 0.33.0
go version: 1.18.2
environment: Visual Studio Code linux
initialization error: Error: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
issue timestamp: Tue, 24 May 2022 16:50:50 GMT
restart history:
Tue, 24 May 2022 16:49:01 GMT: activation (enabled: true)
Tue, 24 May 2022 16:50:24 GMT: config change (enabled: true)
Tue, 24 May 2022 16:50:49 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Please update the gopls to the latest version. Thanks.

```
go install golang.org/x/tools/gopls@latest
```
