### ISSUE TITLE
Goto definition is not working across modules boundaries

### ISSUE THREAD

**Issue by esimov** [golang/vscode-go#2259]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.1 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls@v0.8.4
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.67.2
* Check your installed extensions to get the version of the VS Code Go extension

```
gotests:	/home/esimo/projects/Go/bin/gotests	(version: v1.6.0 built with go: go1.18.1)
gomodifytags:	/home/esimo/projects/Go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18.1)
impl:	/home/esimo/projects/Go/bin/impl	(version: v1.1.0 built with go: go1.18.1)
goplay:	/home/esimo/projects/Go/bin/goplay	(version: v1.0.0 built with go: go1.18.1)
dlv:	/home/esimo/projects/Go/bin/dlv	(version: v1.8.3 built with go: go1.18.1)
staticcheck:	/home/esimo/projects/Go/bin/staticcheck	(version: v0.3.2 built with go: go1.18.1)
gopls:	/home/esimo/projects/Go/bin/gopls	(version: v0.8.4 built with go: go1.18.1)

go env
Workspace Folder (esimov): /home/esimo/projects/Go/src/esimov
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/esimo/.cache/go-build"
	GOENV="/home/esimo/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/esimo/projects/Go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/esimo/projects/Go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.18.1"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2210356938=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Share the Go related settings you have added/edited

```
"go.toolsManagement.autoUpdate": true,
"go.alternateTools": {},
"go.formatTool":"goimports",
"go.useLanguageServer": true,
"[go]": {
    "editor.tabSize": 8,
    "editor.insertSpaces": false,
    "editor.detectIndentation": true
}
```
### Describe the bug
I'm using vscode for development and let's suppose that I have multiple projects inside the same directory declared as GOPATH. If I'm loading only a single project which is tagged as a valid Go module, then the GOTO definition is working for the custom methods and variables defined inside my custom module. But if I'm trying to load the whole directory structure where I have different projects, then the GOTO definition is working only for the methods of the core packages and not for the custom ones. Since I might work on multiple projects in parallel I would expect that the GOTO definition should work regardless the directory being loaded is inside a module or not.

**Comment by hyangah** [comment]
Please see if this helps you configuring your workspace https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules

> Since I might work on multiple projects in parallel I would expect that the GOTO definition should work regardless the directory being loaded is inside a module or not.

The Go language server uses the `go` command underneath. When running the `go` command, which directory the go command runs is a critical part that determines its functionality. (i.e. inside or outside of a module). Recently, the [workspace concept (aka `go.work`)](https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#go-workspaces-go-118) was added, but its functionality also depends on the location of the directory you run the go command.

**Comment by esimov** [comment]
Got it working by using the `go work use -r ./` command for searching for modules recursively on subdirectories. This will include all of the packages having a `go.mod` file.

**Comment by findleyr** [comment]
Thanks for following up! Closing as it sounds like `go.work` addresses the problem.
