### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zgjin** [golang/vscode-go#2264]
gopls version: v0.8.4 (go1.17.10)
gopls flags: 
update flags: proxy
extension version: 0.33.1
go version: 1.17.10
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 26 May 2022 14:53:45 GMT
restart history:
Thu, 26 May 2022 14:53:41 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

open vscode

<pre>panic: runtime error: index out of range [1] with length 1

goroutine 127 [running]:
golang.org/x/tools/internal/gocommand.cmdDebugStr(0xc000434000)
	  invoke.go:267  0x665
golang.org/x/tools/internal/gocommand.(*Invocation).run.func5({0x0, 0xc00009c780, 0x21519c0})
	  invoke.go:230  0x45
golang.org/x/tools/internal/gocommand.(*Invocation).run(0xc0000dea08, {0x1bd81c0, 0xc000459770}, {0x1bbfe40, 0xc0004ddc50}, {0x1bbfe40, 0xc0004ddda0})
	  invoke.go:232  0x1078
golang.org/x/tools/internal/gocommand.(*Invocation).runWithFriendlyError(0xc0000de9d0, {0x1bd81c0, 0xc000459770}, {0x1bbfe40, 0xc0004ddc50}, {0x1bbfe40, 0xc0004ddda0})
	  invoke.go:154  0x65
golang.org/x/tools/internal/gocommand.(*Runner).runConcurrent(0xc00013e960, {0x1bd81c0, 0xc000459770}, {{0x198860c, 0x4}, {0xc0003cc140, 0x5, 0x5}, {0x0, 0x0, ...}, ...})
	  invoke.go:98  0x1ea
golang.org/x/tools/internal/gocommand.(*Runner).RunRaw(0xc000135e07, {0x1bd81c0, 0xc000459770}, {{0x198860c, 0x4}, {0xc0003cc140, 0x5, 0x5}, {0x0, 0x0, ...}, ...})
	  invoke.go:73  0x90
golang.org/x/tools/internal/gocommand.(*Runner).Run(...)
	  invoke.go:55
golang.org/x/tools/internal/gocommand.GoVersion({0x1bd81c0, 0xc000459770}, {{0x198860c, 0x4}, {0xc0003cc140, 0x5, 0x5}, {0x0, 0x0, 0x0}, ...}, ...)
	  version.go:33  0x2b0
golang.org/x/tools/internal/lsp/cache.(*Session).getWorkspaceInformation(0xc00029a080, {0x1bd81c0, 0xc000459770}, {0xc000135e00, 0x7f}, 0xc00054a240)
	  view.go:738  0x1eb
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc00029a080, {0x1bd81c0, 0xc000459770}, {0xc000452800, 0xb}, {0xc000135e00, 0x7f}, 0xc00054a240, 0x0)
	  session.go:183  0xe5
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc00029a080, {0x1bd81c0, 0xc000459770}, {0xc000452800, 0xb}, {0xc000135e00, 0x7f}, 0x1bd87e0)
	  session.go:165  0x287
golang.org/x/tools/internal/lsp.(*Server).addView(0xc000456000, {0x1bd81c0, 0xc000459770}, {0xc000452800, 0xb}, {0xc000135e00, 0x7f})
	  workspace.go:40  0x1c7
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc000456000, {0x1bd81c0, 0xc000459770}, {0xc00013f3a0, 0x1, 0x21825e8})
	  general.go:233  0x6f5
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc000456000, {0x1bd81c0, 0xc000459770}, 0xc0000c19e0)
	  general.go:185  0x305
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000592370, {0x1bd81c0, 0xc000459770}, 0x184d5e0)
	  server_gen.go:160  0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1bd81c0, 0xc000459770}, {0x1c09478, 0xc000456000}, 0xc00043bb60, {0x1bd83b8, 0xc0004596b0})
	  tsserver.go:144  0x704
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1bd81c0, 0xc000459770}, 0xc00043bb60, {0x1bd83b8, 0xc0004596b0})
	  protocol.go:157  0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1bd81c0, 0xc000459770}, 0xc00043bb60, {0x1bd83b8, 0xc0004596b0})
	  lsprpc.go:511  0xa7d
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1bd81c0, 0xc000459770}, 0xc000442b88, {0x1bd83b8, 0xc0004596b0})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20f
[Error - 10:53:42 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@zgjin Can you share your settings.json? That will help us verifying the fix.
