### ISSUE TITLE
Go extension formats files without imports even if formatOnSave is false

### ISSUE THREAD

**Issue by simchev** [golang/vscode-go#2268]
### Versions
go version go1.18.2 windows/amd64
gopls -v version golang.org/x/tools/gopls v0.8.4
code -v 1.67.2
go extension v0.33.1

### Settings (user and workspace)
"editor.formatOnSave": false,
"[go]": {
    "editor.formatOnSave": false
},

### Describe the bug
Despite having my formatOnSave settings to false everywhere, the extension is formatting my go files that doesn't have imports.

### Steps to reproduce the behavior:
1. Create file bug.go
2. Write this code

```
type TestStruct struct { Test string }
func (t *TestStruct) Testing() { t.Test = "bug" }
```

3. Save and see the formatting
4. Now write this code instead that uses fmt

```
import "fmt"
type TestStruct struct { Test string }
func (t *TestStruct) Testing() { t.Test = "bug"; fmt.Println("Fixed (not really)") }
```

5. Save and it doesn't format

**Comment by findleyr** [comment]
Hi, I can't repro this, though I may be misunderstanding.

Per https://github.com/golang/vscode-go/wiki/advanced, the correct way to disable auto-formatting is as follows:

```
"[go]": {
"editor.formatOnSave": false
},
```

(which you have done)

When I do this, I don't get any formatting. Do you have any other settings (e.g. do you have `"go.useLanguageServer": false`?).

**Comment by simchev** [comment]
> Hi, I can't repro this, though I may be misunderstanding.
> 
> Per https://github.com/golang/vscode-go/wiki/advanced, the correct way to disable auto-formatting is as follows:
> 
> ```
> "[go]": {
> "editor.formatOnSave": false
> },
> ```
> 
> (which you have done)
> 
> When I do this, I don't get any formatting. Do you have any other settings (e.g. do you have `"go.useLanguageServer": false`?).

Sorry I completely missed your reply but I don't have any other settings. The file you're saving must have **no imports**, meaning that you shouldn't use any modules, otherwise it works as intended. Are you sure you tried to save a go file without any imports?

**Comment by simchev** [comment]
No, I do have a go.mod file. What I meant was no module/package used in the specific file you're saving (basically just no imports for that file). I didn't change any go settings.

You guys did my 5 steps exactly, with formatOnSave false, and couldn't reproduce?

**Comment by hyangah** [comment]
Can you help me find what I did differently? (the first part is when formatOnSave is false, the second part is when formatOnSave is true)
https://user-images.githubusercontent.com/4999471/173849368-a34e752f-05fa-4914-8309-83127b27acb0.mp4

**Comment by simchev** [comment]
It seems like it's working correctly on your end for some reason. Mine is formatting even when false. Are you using a different formatter?

**Comment by hyangah** [comment]
No I don't use a different formatter. These are all my settings

**Preference : Open Settings (JSON)**
```
{
    "go.languageServerFlags": [
        "-rpc.trace"
    ],
    "gopls": {
        "ui.semanticTokens": true
    },
}
```

**Preference: Open Workspace Settings (JSON)**
```
{
    "editor.formatOnSave": false,
    "[go]": {
        "editor.formatOnSave": false
    },
}
```

**Comment by realnatuki** [comment]
In my case new M1 mac nothing works. Can't even install tools. 
Formater is not working auto import  and auto complete is not working and when I run : Go Install/Update Tools this is what i get.


<img width="437" alt="Screenshot 2022-06-26 at 08 27 56" src="https://user-images.githubusercontent.com/85006141/175802430-4c2ef04f-6e29-4c1e-9d9c-7706f78e3e3c.png">

**Comment by hyangah** [comment]
@realnatuki It looks like a different issue to me. Please open a new issue (following the issue template) if you still experience the issue.
