### ISSUE TITLE
Please add an option to disable warnings from simplifycompositelit

### ISSUE THREAD

**Issue by rajatsingh25aug** [golang/vscode-go#227]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).

**Is your feature request related to a problem? Please describe.**
I keep on getting warnings like this `redundant type from array, slice, or map composite literal simplifycompositelit.`

![image](https://user-images.githubusercontent.com/17253992/84758081-9e358a00-afe2-11ea-8197-1337884a26dc.png)

I don't know how to disable this warning.

**Describe the solution you'd like**
Please write a feature so that I can disable the warnings like above from the VScode's `settings.json`.

**Describe alternatives you've considered**
There is no fix to this problem AFAIK.

**Additional context**
There is no issue in the code's logic or any other error whatsoever. These warnings are pretty distracting.

**Comment by hyangah** [comment]
@rajatsingh25aug Please share your go related settings.

If you are using the Go language server (`"go.useLanguageServer": true`), specific analysis can be turned off like the followings. 
```
"gopls": {
   "analyses": {
      "simplifycompositelit": false, 
   }
}
```
See https://github.com/golang/tools/blob/master/gopls/doc/settings.md#analyses-mapstringbool
(also note the settings syntax may change in the future)

Even though I hope the default set of diagnostics can help writing more readable code, 
if you think that's too distracting, you can completely turn off any diagnostics
```
    "go.languageServerExperimentalFeatures": {
        "diagnostics": false
    }
```

**Comment by rajatsingh25aug** [comment]
@hyangah My `settings.json` looks like this.
```
{
    "go.useLanguageServer": true,
    "go.buildOnSave": "package",
    "go.lintFlags": ["--disable=all"],
    "terminal.integrated.fontFamily": "Source Code Pro for Powerline",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "markdown.extension.toc.unorderedList.marker": "*",
    "markdown.extension.toc.levels": "2..2",
    "workbench.iconTheme": "eq-material-theme-icons-darker",
    "workbench.colorTheme": "Winter is Coming (Dark Black - No Italics)",
    "window.zoomLevel": 2,
    "python.jediEnabled": false,
    "workbench.editor.showTabs": true,
}
```

**Comment by hyangah** [comment]
Thanks @rajatsingh25aug for sharing the settings.
 
You are using the language server (`"go.useLanguageServer": true`), so the settings change I described in [my previous comment](https://github.com/golang/vscode-go/issues/227#issuecomment-644762002) will do what you want.

We plan to improve the discoverability of the settings. (https://github.com/golang/vscode-go/issues/197)

**Comment by stamblerre** [comment]
Just to add one more note here - you can configure your editor to automatically fix all of those errors on save by adding the following to your settings:

```json5
"[go]": {
	"editor.codeActionsOnSave": {
		"source.fixAll": true,
	}
}
```

**Comment by rajatsingh25aug** [comment]
@hyangah The settings that you provided didn't work. :/

![image](https://user-images.githubusercontent.com/17253992/84990308-96045880-b162-11ea-8778-89407e53c4ab.png)

Am I doing something wrong?.

**Comment by hyangah** [comment]
@rajatsingh25aug That "unknown configuration setting" error is fine - that's working as intended and `gopls` will process it. We didn't promote the `gopls` section as a recognized setting yet because gopls is still in alpha.

Is the settings.json file saved?

From my quick testing, it should work. 

Before:
<img width="1228" alt="Screen Shot 2020-06-18 at 7 02 36 AM" src="https://user-images.githubusercontent.com/4999471/85013344-69384d00-b132-11ea-8678-ad0981ab0bf7.png">

After:
<img width="1201" alt="Screen Shot 2020-06-18 at 7 02 01 AM" src="https://user-images.githubusercontent.com/4999471/85013385-78b79600-b132-11ea-8c5f-ddf71e2075a7.png">

**Comment by rajatsingh25aug** [comment]
@hyangah So I have applied the settings again and restarted the vscode again. Killed all the running process related to vscode from the background and **it worked.** 💯 

I was facing this issue for a long time. Thank you for being so prompt for helping out. 👍

**Comment by hyangah** [comment]
@rajatsingh25aug good to hear that the problem solved. 

Ideally `gopls` should pick up the new configuration automatically and the vscode restart shouldn't be necessary. If not, I hope the future release should handle this better.

Enjoy Go programming!
