### ISSUE TITLE
vscode integration terminal gets incorrect version of go

### ISSUE THREAD

**Issue by wushu037** [golang/vscode-go#2283]
### What version of Go, VS Code & VS Code Go extension are you using?

go   1.18
vscode  1.67.2
vscode go  0.33.1

### Share the Go related settings you have added/edited  & Describe the bug

I have go1.17 configured with my $path$
When I wanted to use go1.18, I configured it using vscode go
As you can see in the bottom left corner, this configuration is correctly recognized and I can run my go1.18 specific generic code
But the terminal in vscode is still getting go1.17
(ps: jetbrainsIDE's terminal always correctly combines IDE external and internal environment variables, but vscode does not)

![image](https://user-images.githubusercontent.com/61787040/172813308-fdcd5404-3e9d-41f6-99d5-355b6eeb0d4e.png)

**Comment by jamalc** [comment]
Could you share the output of the command 'Go: Locate Configured Go Tools' on this issue?

<img width="493" alt="Screen Shot 2022-06-09 at 10 44 18 AM" src="https://user-images.githubusercontent.com/18269441/172876091-0c1ff0d9-795a-4a67-86a7-a2141e62f2da.png">

**Comment by wushu037** [comment]
> 您能否在此问题上分享命令“Go: Locate Configured Go Tools”的输出？
> 
> <img alt="屏幕截图 2022-06-09 在 10 44 18 AM" width="493" src="https://user-images.githubusercontent.com/18269441/172876091-0c1ff0d9-795a-4a67-86a7-a2141e62f2da.png">

Yes, here's how I did it: 
![image](https://user-images.githubusercontent.com/61787040/172878573-ef4bcb15-6bd0-4bd3-b42e-d545dae90edc.png)

**Comment by jamalc** [comment]
What do you get when running `echo $PATH` from the integrated terminal? Want to rule out any rc file overwriting path after it has been set by vscode.

**Comment by wushu037** [comment]
As follows, I also found a key problem
![image](https://user-images.githubusercontent.com/61787040/173723390-18a032a8-241a-44ae-a8df-5ef04a9e97a2.png)


I have a feeling you may have already done something with the terminal environment variables, but there is a slight problem.
I tried a dozen times to start-up-close vscode and found that.
- The default terminal tab at startup was able to get go1.18 several times, **but not every time**
- The new terminal tabs that are created all get go1.17

**Comment by jamalc** [comment]
That's what I'm seeing as well. This is related to a workaround we're using for microsoft/vscode#99878 on macOS. In the workaround we use a `vscode.window.onDidOpenTerminal` callback to update the PATH value. We removed Linux shell fallback from the workaround to fix #378 in [CL 244378](https://go-review.googlesource.com/c/vscode-go/+/244378).  I've noticed however that terminal.name is often empty until about 100ms after the `vscode.window.onDidOpenTerminal` callback is run.

We could add a short delay with a timeout to wait for terminal.name to be set, or reintroduce a fallback for when terminal.name is empty string. What do you think @hyangah?

**Comment by wushu037** [comment]
Thank you for your attention to this issue
I think it's worth fixing, otherwise executing go commands (such as go work init) would become a pain
