### ISSUE TITLE
test: long test failure "Failed to get linter results"

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#2287]
The long tests have been failing on ubuntu with Go < 1.18 for quite some time.
```
1) Go Extension Tests (GOPATH mode)
       Error checking:
AssertionError [ERR_ASSERTION]: Failed to get linter results
+ expected- actual
-false
+true
  	at Context.<anonymous> (out/test/integration/extension.test.js:444:26)
```

**Comment by suzmue** [comment]
It appears it started failing after https://go-review.googlesource.com/c/vscode-go/+/405551 

cc @hyangah @jamalc

**Comment by hyangah** [comment]
Duplicate of https://github.com/golang/vscode-go/issues/2282 ?
