### ISSUE TITLE
tools: Allow adding new tools to "Go: Install/Update tools"

### ISSUE THREAD

**Issue by joeky888** [golang/vscode-go#2290]
**Is your feature request related to a problem? Please describe.**
No, not at all.

**Describe the solution you'd like**

Example configuration in my head:
```js
"go.additionalTools": {
  "wire": "github.com/google/wire/cmd/wire@latest".
  "swag": "github.com/swaggo/swag/cmd/swag@latest".
  "mockgen": "github.com/golang/mock/mockgen@latest",
  "gqlgen": "github.com/99designs/gqlgen@latest"
}
```

**Describe alternatives you've considered**

Manually install/update :(

**Additional context**

Currently, there is no way to append more tools to `Go: Install/Update tools`, it would be nice if one can just add tools to the settings.json for each project.

**Comment by hyangah** [comment]
This extension doesn't use those tools. Why should the project depend on this extension to install the tools the project depends on? Isn't tasks.json or even non-vscode-specific solution (for the project contributors who use other editors) better?

**Comment by joeky888** [comment]
> This extension doesn't use those tools.

Fair point. Though I suppose the `.vscode/settings.json` is for the workspace setting, the customizable tool set in `settings.json` wouldn't be harmful. Sometimes when it comes to “Why vscode stop working as expected?” I usually run `Go: Install/Update tools` and relaunch the workspace as a cure.

> tasks.json

This is a workaround, but not so convenient and straightforward.

> even non-vscode-specific solution

Agree. That's why `Makefile` and `Dockerfile` are used in CI/CD pipeline and then the Windows developers complain they can't use `Makefile`.

> for the project contributors who use other editors

This is interesting. When Github [sunsetting atom](https://github.blog/2022-06-08-sunsetting-atom) I know there will be more vscode developers who were exiled from atom.

So, the answer is no? It's okay. Feel free to close it and have a good day. :)

**Comment by suzmue** [comment]
Closing this as we don't plan on doing this. The extension could provide better support for default tasks in the future to make installing arbitrary Go tools easier.
