### ISSUE TITLE
Move instruction pointer while debugging

### ISSUE THREAD

**Issue by gottfired** [golang/vscode-go#2291]
**Describe the solution you'd like**
It would be great, if you could move the instruction pointer during debugging like in other languages/IDEs 

**Additional context**
This is possible e.g. with C++ in Visual Studio or Swift in XCode

**Comment by suzmue** [comment]
Hi @gottfired! Could you provide some more details about what you would like to see? How do these other languages allow moving the instruction pointer?

**Comment by gottfired** [comment]
In Xcode and Visual Studio (not Visual Studio Code) you can drag the instruction pointer (ie. the arrow indicating you current point of execution) to a new position.

<img width="240" alt="Screenshot 2022-06-14 at 12 30 29" src="https://user-images.githubusercontent.com/4855371/173557163-f2a07757-6de7-418e-b7d3-9629a9a74551.png">

This simply sets the point where program flow will continue execution, so basically the next ASM instruction. When you drag back it does not roll back any changed data or other side effects. But in many cases this is quite useful, e.g. when debugging an algorithm and you want to rerun a loop you can simply have a breakpoint after a loop and drag back to the beginning, or if you accidentally skip going into a function you can drag back to the point before.
