### ISSUE TITLE
Option for launch.json to debug as sudo.

### ISSUE THREAD

**Issue by dbourkey** [golang/vscode-go#2302]
**Is your feature request related to a problem? Please describe.**
I need to run & debug certain programs as root.

**Describe the solution you'd like**
Add a root privilege settings option in golang launch.json like [python debug](https://donjayamanne.github.io/pythonVSCodeDocs/docs/debugging_sudo-root-privileges/).

**Describe alternatives you've considered**
Run VSCode as root (Horribly insecure)

There is a long and cumbersome workaround described [here](https://github.com/microsoft/vscode-go/issues/2889) in the second-to-last comment. However, for remote development, this workaround requires me to make changes to my remote environment's sudoers file, which is not always an option.

**Additional context**
I am running on Windows through WSL2, and attempting to run remotely on several targets including ssh-VMs.

This is a continuation of the issue raised [here](https://github.com/microsoft/vscode-go/issues/2889) three years ago.

**Comment by hyangah** [comment]
Have you seen this?
https://github.com/golang/vscode-go/wiki/debugging#debugging-programs-and-tests-as-root

Let us know if there is anything we can make this feature more visible.

**Comment by dbourkey** [comment]
Does this feature work on WIndows-WSL2? When I run with this option it generates an error: 

> Couldn't start dlv dap:
> Error: cannot launch dlv dap. See DEBUG CONSOLE

**Comment by dbourkey** [comment]
This does work on Windows-WSL, so my problem is solved. Thank you hyangah.

My launch.json config:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "cmds/coredhcp/main.go",
            "asRoot": true,
            "console": "integratedTerminal"
        }
    ]
}`

Please note the integratedTerminal field.
