### ISSUE TITLE
change the icon of  test timeout 

### ISSUE THREAD

**Issue by MUCZ** [golang/vscode-go#2312]
![image](https://user-images.githubusercontent.com/73420084/176871653-eefbf8ad-41ce-4404-aca3-ace01d2f87cc.png)

It really took me quite a while to understand that the second icon means this test is timed out. 
Maybe another color more striking?

**Comment by hyangah** [comment]
Thanks for the feedback. 
This UI is owned by the vscode - this extension uses only VS Code's [testing api](https://code.visualstudio.com/api/extension-guides/testing) to provide data to the vscode. Can you please file an issue to https://github.com/microsoft/vscode ? Thanks!
