### ISSUE TITLE
Find Function by name

### ISSUE THREAD

**Issue by guettli** [golang/vscode-go#2313]
**Is your feature request related to a problem? Please describe.**

It would be nice, if vscode would support this goland feature: You can easily find a function by its name.

For example you rember that "ReadAll()" was the name, but you don't know which package it belongs to:

![image](https://user-images.githubusercontent.com/414336/176878790-604bf719-0c41-4476-88c5-5794b3134a2e.png)

**Describe the solution you'd like**

I want to find a method by its name.

**Describe alternatives you've considered**

I consider using goland instead of vscode.

**Comment by gmeligio** [comment]
I think this could be accomplished by searching for a symbol. The way I do it is like in this [StackOverflow answer]
1. `Ctrl+P` open the [command palette].
2. Write `#ReadAll`.
3. It will search by this symbol across all files and show a list will the symbols found.
4. Pick the one you want from the list.

![r7JBX](https://user-images.githubusercontent.com/22875166/177036296-cb39ad95-6f1c-4919-ad8a-c78b59ebb78a.gif)

[StackOverflow answer]: https://stackoverflow.com/a/60662664/5405601
[command palette]: https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

**Comment by guettli** [comment]
Thank you very much. I close this issue, since your answer solved it.
