### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by graceleeis** [golang/vscode-go#2316]
gopls version: v0.8.4 (go1.18.2)
gopls flags: true
update flags: proxy
extension version: 0.34.1
go version: 1.18.2
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Mon, 04 Jul 2022 05:52:45 GMT
restart history:
Mon, 04 Jul 2022 05:52:35 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@graceleeis Can you please check `"go.languageServerFlags"` setting? It looks like `true` was passed as the gopls flag value which is invalid.
