### ISSUE TITLE
GO111MODULE setting  not take effect

### ISSUE THREAD

**Issue by songkingkong** [golang/vscode-go#2318]
I setting GO111MODULE is ON but when "Import mod"，The editor always to src find the mod
![image](https://user-images.githubusercontent.com/3363577/177124460-faf6929f-b67f-49f6-9c8e-f39166eb819c.png)
this is go env setting
![image](https://user-images.githubusercontent.com/3363577/177124572-8fea091a-388f-41df-99e3-687b35478edd.png)

**Comment by hyangah** [comment]
@songkingkong Can you please share the gopls trace (from the beginning)? 
The instruction is in https://github.com/golang/vscode-go/wiki/troubleshooting#collect-gopls-information
