### ISSUE TITLE
debug: investigate inline mode debug adapter

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#232]
From https://github.com/golang/vscode-go/issues/23#issuecomment-644442473

The debug adapter library allows three different modes of launching the debug adapter. 
https://github.com/microsoft/vscode-mock-debug/blob/master/src/extension.ts#L57

In particular the inline mode is interesting. Explore and see if it's better for long term. 

@eliben already has a prototype that wires the existing GoDebugSession in the inline mode. 
https://github.com/eliben/vscode-go/commit/81042e0e813f781bb0e5d6eeb747834bb21d6d97

**Comment by eliben** [comment]
FWIW, the new DA (`debugAdapter2`) works in inline mode.

**Comment by hyangah** [comment]
Closing because this is no longer relevant. We will leave the legacy debug adapter as it is. 
The new dlv dap adapter is integrated through an inline-mode thin adapter.
