### ISSUE TITLE
go extension work abnormal, "go": executable file not found in $PATH

### ISSUE THREAD

**Issue by xiaoyang-chen** [golang/vscode-go#2323]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.3 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.9.0 golang.org/x/tools/gopls@v0.9.0 h1:nEKQdO89Fkt4QTCN1xXkZzYHWZoBvIhkjJMpUaqRKUU=
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.68.1 30d9c6cd9483b2cc586687151bcbcd635f373630 x64
* Check your installed extensions to get the version of the VS Code Go extension
	- Go v0.34.1 Go Team at Google 7,283,315 (230)
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: /usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64
gopath: /Users/xiaoyang-chen/go
GOROOT: /usr/local/Cellar/go/1.18.3/libexec
PATH: /usr/bin:/bin:/usr/sbin:/sbin

	go:	/usr/local/Cellar/go/1.18.3/libexec/bin/go: go version go1.18.3 darwin/amd64

	gotests:	/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64/bin/gotests	(version: v1.6.0 built with go: go1.18.3)
	gomodifytags:	/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64/bin/gomodifytags	(version: v1.16.0 built with go: go1.18.3)
	impl:	/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64/bin/impl	(version: v1.1.0 built with go: go1.18.3)
	goplay:	/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64/bin/goplay	(version: v1.0.0 built with go: go1.18.3)
	dlv:	/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64/bin/dlv	(version: v1.9.0 built with go: go1.18.3)
	gopls:	/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64/bin/gopls	(version: v0.9.0 built with go: go1.18.3)

go env
Workspace Folder (nis-edge-device-data-collector): /Users/xiaoyang-chen/Documents/git-repo/leshi/nisioct/nis-edge-device-data-collector
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/xiaoyang-chen/Library/Caches/go-build"
	GOENV="/Users/xiaoyang-chen/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/xiaoyang-chen/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/xiaoyang-chen/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.com.cn,direct"
	GOROOT="/usr/local/Cellar/go/1.18.3/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.18.3"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/xiaoyang-chen/Documents/git-repo/leshi/nisioct/nis-edge-device-data-collector/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v8/lqjftghd06x4bdc946hl2gsc0000gn/T/go-build2672391438=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    "go.useLanguageServer": true,
    "go.docsTool"         : "gogetdoc",
    "go.testFlags"        : ["-v","-count=1"],
    "go.buildTags"        : "",
    "go.buildFlags"       : [],
    "go.lintFlags"        : [
        "-min_confidence=.8",
        "--disable=all", 
        "--enable=errcheck"
    ],
    "go.vetFlags"                                   : [],
    "go.coverOnSave"                                : false,
    "go.buildOnSave"                                : "package",
    "go.lintOnSave"                                 : "file",
    "go.vetOnSave"                                  : "package",
    "go.gocodeAutoBuild"                            : true,
    "go.gocodePackageLookupMode"                    : "go",
    "go.gotoSymbol.includeImports"                  : true,
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.autocompleteUnimportedPackages"             : true,
    "go.useCodeSnippetsOnFunctionSuggest"           : true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true,
    },
    "go.terminal.activateEnvironment": false,
    "go.goroot"     : "/usr/local/Cellar/go/1.18.3/libexec",
    "go.toolsGopath": "/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64",
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave"      : true,
        "editor.codeActionsOnSave" : {
            "source.organizeImports": true
        }
    },
    "[go.mod]": {
        "editor.formatOnSave"     : true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "[go.work]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "gopls": {
        "codelenses": {
            "generate": true,
            "gc_details"        : false,
            "regenerate_cgo"    : true,
            "tidy"              : true,
            "upgrade_dependency": true,
            "vendor"            : true
        },
        "usePlaceholders"   : true,
        "completeUnimported": true,
        "completionDocumentation": true,
        "hoverKind": "SynopsisDocumentation",
        "staticcheck": true,
        "build.directoryFilters": [
            "-dailyDiary", 
            "-go", 
            "-minerhub",
            "-temp",
        ],
    },

### Describe the bug
open a golang project by vscode, get this error, and gopls doesn't work:
Error loading workspace folders (expected 1, got 0)
failed to load view for file:///Users/xiaoyang-chen/Documents/git-repo/xxx/nis-edge-device-data-collector: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

expect gopls work normal

### Steps to reproduce the behavior:
see bug description
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/61339960/177664665-7f71dfc5-5db3-4b15-a5c5-4f733ffe69f2.png)

**Comment by xiaoyang-chen** [comment]
add `go env GOTOOLDIR `/bin into PATH, it work again, but in last week, it work normal even if I not add `go env GOTOOLDIR `/bin into PATH, is causing by go extenison update?

**Comment by jamalc** [comment]
I don't see anything from the v0.34.1 release that stands out. Does this still happen if you change the extension version to 0.33.1? Do you have a go binary installed in `go env GOTOOLDIR`/bin? Maybe something has changed with your path, I would not expect go to be available there.

**Comment by xiaoyang-chen** [comment]
hard to locate this problem, i will close it
