### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by AnanthiSubash** [golang/vscode-go#2331]
gopls version: v0.9.0 (go1.17.1)
gopls flags: 
update flags: proxy
extension version: 0.34.1
go version: 1.17.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 11 Jul 2022 06:45:00 GMT
restart history:
Mon, 11 Jul 2022 06:31:39 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by AnanthiSubash** [comment]
I just opened the vscode

**Comment by findleyr** [comment]
Hi, did you by any chance run the go:generate codelens? (or do you have something that automatically runs it?)

**Comment by AnanthiSubash** [comment]
Yes I ran go generate

**Comment by findleyr** [comment]
Ok, there was a bug in the go:generate codelens, in v0.9.2, which has since been fixed. Please update to the latest version of gopls.
