### ISSUE TITLE
Highlight the new `any` builtin

### ISSUE THREAD

**Issue by aarondl0** [golang/vscode-go#2340]
**Is your feature request related to a problem? Please describe.**
I'm always caught off guard that `any` does not have syntax highlighting like `string` does. All the builtin types listed here otherwise have highlighting: https://pkg.go.dev/builtin

**Describe the solution you'd like**
`any` should be treated like `string` in terms of highlighting, all [builtins](https://pkg.go.dev/builtin) should be highlighted.

**Describe alternatives you've considered**
The alternative would be to not highlight as is currently done but this is not giving the proper weight to `any` since it's special compared to most other types.

**Comment by li1234yun** [comment]
![image](https://user-images.githubusercontent.com/26505658/179643048-88205bf7-a59a-4e1c-8de7-a03197862aec.png)

You can try add the setting to VSCode.

**Comment by aarondl0** [comment]
Works, thanks!
