### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bobbiprathama** [golang/vscode-go#235]
- Issue Type: `Bug`
- Extension Name: `Go`
- Extension Version: `0.14.4`
- OS Version: `Darwin x64 19.4.0`
- VSCode version: `1.46.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 8444,
		"activateCallTime": 43,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "golang.Go",
				"_lower": "golang.go"
			},
			"activationEvent": "workspaceContains:**/*.go"
		}
	},
	"runtimeErrors": []
}
```

**Comment by hyangah** [comment]
@bobbiprathama Can you describe the issues you are experiencing? The above does not include necessary details.

**Comment by hyangah** [comment]
Closing this. @bobbiprathama please reopen this or create a new one with the details. Thanks!
