### ISSUE TITLE
Incorrect visual display from debugger

### ISSUE THREAD

**Issue by kjavaherpour** [golang/vscode-go#2351]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.2 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.9.1
    golang.org/x/tools/gopls@v0.9.1 h1:SigsTL4Hpv3a6b/a7oPCLRv5QUeSM6PZNdta1oKY4B0=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.12-0.20220713141851-7464a5a40219 h1:Ljlba2fVWOA1049JjsKii44g8nZN2GjpxMlzVc8AnQM=
    golang.org/x/vuln@v0.0.0-20220613164644-4eb5ba49563c h1:r5bbIROBQtRRgoutV8Q3sFY58VzHW6jMBYl48ANSyS4=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.69.1
b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.35.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/kamronjavaherpour/go
GOROOT: /usr/local/Cellar/go/1.18.2/libexec
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki

	go:	/usr/local/bin/go: go version go1.18.2 darwin/amd64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/usr/local/bin/dlv	(version: (devel) built with go: go1.18.1)
	staticcheck:	not installed
	gopls:	/Users/kamronjavaherpour/go/bin/gopls	(version: v0.9.1 built with go: go1.18.2)

go env
Workspace Folder (no folder): undefined
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/kamronjavaherpour/Library/Caches/go-build"
	GOENV="/Users/kamronjavaherpour/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/kamronjavaherpour/go/pkg/mod"
	GONOPROXY="github.com/KargoGlobal/*"
	GONOSUMDB="github.com/KargoGlobal/*"
	GOOS="darwin"
	GOPATH="/Users/kamronjavaherpour/go"
	GOPRIVATE="github.com/KargoGlobal/*"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.18.2/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.18.2/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.18.2"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pt/qrhdf6fs4q768zc7mvmnvny80000gn/T/go-build1426598409=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

"go.toolsManagement.autoUpdate": true,

### Describe the bug
When unmarshaling a json string into a struct containing a field of type map[string]interface{}, sometimes the debugger does not show the correct visual output for what the map. Given the following program:
```
package main

import (
	"encoding/json"
	"fmt"
)

type Example struct {
	Id         string                 `json:"id"`
	Extensions map[string]interface{} `json:"ext,omitempty"`
	SomeString string                 `json:"somestring"`
}

func main() {
	jsonstr := `{
    "id": "f390f11c-33b2-608e-afdf-4551e955a6e1",
    "ext": {
        "mapKey": {
			"listKey": [
                {
                    "key1": "value1",
                    "key2": [
                        {
                            "key2mapkey": "key2mapvalue"
                        }
                    ]
                }
            ],
            "structValue": {
                "structKey1": "structValue1",
                "structKey2": "structValue2"
            }
        }
    },
    "somestring": ""
}`
	result := Example{}
	bts := []byte(jsonstr)
	err := json.Unmarshal(bts, &result)
	if err == nil {
		fmt.Println(result)
	} else {
		fmt.Println(err)
	}
}
```
one would expect to see: ```{f390f11c-33b2-608e-afdf-4551e955a6e1 map[mapKey:map[listKey:[map[key1:value1 key2:[map[key2mapkey:key2mapvalue]]]] structValue:map[structKey1:structValue1 structKey2:structValue2]]] }```
but it only shows the list as a value of the map. When printing out, it shows prints the expected output.

### Steps to reproduce the behavior:
1. Copy the above code into vscode.
2. Set debugger at `if err == nil` and note the visual display of the `result` variable
3. Print result
4. Visual display and printed result do not match.

### Screenshots or recordings
<img width="661" alt="Screen Shot 2022-07-18 at 11 38 15 AM" src="https://user-images.githubusercontent.com/985810/179580143-cdbeb095-1cf1-41a6-81fc-ca72184ec3ae.png">
The above screen shot shows the visual output with the following text output:

```{f390f11c-33b2-608e-afdf-4551e955a6e1 map[mapKey:map[listKey:[map[key1:value1 key2:[map[key2mapkey:key2mapvalue]]]] structValue:map[structKey1:structValue1 structKey2:structValue2]]] }```

The `structValue` key is missing. I suspect this has something to do with the length and the nested map.

**Comment by suzmue** [comment]
Thanks for reporting! Sent a fix for the bug to delve.

**Comment by suzmue** [comment]
Closing, this is fixed at tip in delve.
