### ISSUE TITLE
Incorrect link to module repository

### ISSUE THREAD

**Issue by trailstrider** [golang/vscode-go#2362]
Normally, ctrl+click on an import line for a module will take you to the dock page, usually hosted on https://pkg.go.dev/.

If I have a private repository holding a module referenced in an import line, ctrl+click will still try and take me to the module page at https://pkg.go.dev/.  The issue is that this won't exist, and usually shouldn't exist as it is a private repo/module.

The click of the link should take me to the git repo page of my module instead, or better yet an associated doc page that follows the same format/approach so that the tooltip can also provide some guidance on usage like it does for other modules.

**Comment by jamalc** [comment]
Have you set GOPRIVATE in your workspace?

**Comment by hyangah** [comment]
Let's document this feature (in linkTarget)
