### ISSUE TITLE
Only show inline hints on line the cursor is positioned on

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [golang/vscode-go#2366]
**Is your feature request related to a problem? Please describe.**

I really like the new inlay hints and they save me a lot of time. But they do add a lot of visual clutter making it harder to read the code.

**Describe the solution you'd like**

Add an option to only show the hints for the line the cursor is currently on.

When wondering about the name of a parameter or the type of the key/value of a range function my cursor is usually already in that line anyway. Even if not, it is faster for me to navigate the cursor to that line than looking up the quick docs.

**Describe alternatives you've considered**

Since there is no quick command to dis-/enable the hints I currently see no alternative other than to not using hints at all.

**Additional context**

**Comment by hyangah** [comment]
I don't know how to show inline hints on the cursor position. But I use

```
    "editor.inlayHints.enabled": "offUnlessPressed"
```

so I can see inlay hints when I press the short key. https://www.youtube.com/watch?v=uvrIFZYW7eg&t=3s

**Comment by ChristianHuff-DEV** [comment]
> I don't know how to show inline hints on the cursor position. But I use
> 
> ```
>     "editor.inlayHints.enabled": "offUnlessPressed"
> ```
> 
> so I can see inlay hints when I press the short key. https://www.youtube.com/watch?v=uvrIFZYW7eg&t=3s

Thanks for the tip. I didn't know about that.

**Comment by hyangah** [comment]
I hope `editor.inlayHints.enabled` options address the issue.
How & when the inlayHints are presented is controlled by the vscode. If you want finer controls beyond the provided options, please file a feature request in github.com/microsoft/vscode/issues.
Thanks!
