### ISSUE TITLE
Go Extension problems when using Remote-SSH

### ISSUE THREAD

**Issue by vicoooo26** [golang/vscode-go#237]
### What version of Go, VS Code & VS Code Go extension are you using?
- Version of Go
	- go version go1.13.12 linux/amd64
- Version of VS Code
	- 1.46.0
- Version of the VS Code Go extension and Remote-SSH 
	- 0.14.4 & 0.51.0
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/devops/workspace/project/go/bin"
GOCACHE="/home/devops/.cache/go-build"
GOENV="/home/devops/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/devops/workspace/project/go"
GOPRIVATE=""
**GOPROXY="https://goproxy.io"**
GOROOT="/home/devops/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/devops/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build606457334=/tmp/go-build -gno-record-gcc-switches"

### Describe the bug
After I connected to remote server, I tried to use Go: Install/Update Tools command to install some tools and the result is shown bellow. I have config GOPROXY for my server, but it didn't seem to work.
 
![image](https://user-images.githubusercontent.com/30412827/84928841-9f110d80-b101-11ea-8aff-834975efade6.png)

**Comment by hyangah** [comment]
@vicoooo26 How did you configure the environment variable on the remote host?

According to https://code.visualstudio.com/docs/remote/ssh#_remote-ssh-limitations 
> Local proxy settings are not reused on the remote host, which can prevent extensions from working unless the appropriate proxy information is configured on the remote host (for example global HTTP_PROXY or HTTPS_PROXY environment variables with the appropriate proxy information).

GOPROXY env var is not different from any other environment variables. If you configured following the Remote-SSH's advice and  it still doesn't work, I think it may be answered better in https://github.com/Microsoft/vscode-remote-release/.

Another idea is to set utilizing `"go.envFile"` setting or, running [`go env -w`](https://golang.org/cmd/go/#hdr-Environment_variables) on the remote host. 

cc @quoctruong @ramya-rao-a what is the recommended way for managing remote environment variable setting? Thanks!

**Comment by vicoooo26** [comment]
Hi @hyangah, thanks for your prompt reply, here is my environment variable configured in my ~/.bashrc.
```
export GOPROXY=https://goproxy.cn
export GOROOT=/home/devops/go
export GOPATH=/home/devops/workspace/project/go
export GOBIN=/home/devops/workspace/project/go/bin
export PYENV_ROOT="$HOME/.pyenv"
export PATH=$PYENV_ROOT/bin:$PATH:/home/devops/go/bin:$GOPATH/bin:$PATH
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
What makes me confusing most is that I can use go get command in VSCode remote termial to install some go tools with no errors, while I cannot install them by using  Go: Install/Update Tools command.

**Comment by hyangah** [comment]
@vicoooo26 It's indeed so confusing. I did some digging in github.com/microsoft/vscode-remote-release and found many similar issues.

So far, my findings: Assuming you are using bash...

- Integrated terminal runs only `.bashrc`, assuming the remote vscode server already applied any environment settings for login shell. (so, there are issues like https://github.com/microsoft/vscode-remote-release/issues/1671)

- The extension host (so the Go extension) inherits the environment variables from the remote vscode server.

- The remote vscode server environment is setup based on the login shell. E.g. `~/.bash_profile`, but not `~/.bashrc` automatically. So make sure your login shellscript also calls `~/.bashrc`. [reference](https://github.com/microsoft/vscode-remote-release/issues/1671#issuecomment-542818686)

- And, more confusingly, this setting is sticky - the remove vscode server caches the env values, remains alive. All subsequent ssh connections will use the cached values. [reference](https://github.com/microsoft/vscode-remote-release/issues/1671#issuecomment-543046688) Thus, just restarting vscode after editing the . files isn't sufficient. You need to explicitly run the "Remote-SSH: Kill  VS Code Server on Host" command. [reference](https://github.com/microsoft/vscode-remote-release/issues/1671#issuecomment-543046688).

So, @vicoooo26 can you check if your `~/.bash_profile` invokes your `~/.bashrc`, kill the current VS Code Server on the remote host, and restart the vscode? Let me know how it goes. 

And finally, for Remote-WSL users, it looks like an additional setting is necessary 
https://code.visualstudio.com/docs/remote/wsl#_advanced-environment-setup-script.

**Comment by vicoooo26** [comment]
@hyangah Thanks for your help, I solved the problem with reference to your suggestion. 

After I check my `~/.bash_profile` file, I find it is empty. And I add some lines to `~/.bash_profile` as bellow.

```
echo 'test remote-ssh'
if [ -f $HOME/.bashrc ]; then
        source $HOME/.bashrc
fi
```
Then I close the remote vscode server and reconnect to it via Remote-SSH, `test remote-ssh` is shown in the OUTPUT -> Remote-SSH. That's to say the vscode remote server env is indeed setup based on the login shell.

[Reference may help](https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc#comment375909_51038)
