### ISSUE TITLE
Add `go.goroot` command

### ISSUE THREAD

**Issue by OrBin** [golang/vscode-go#2379]
**Is your feature request related to a problem? Please describe.**
I want to define use `GOROOT` and `GOPATH` when defining `substitutePath` in a remote debugging (`attach`) configuration in _launch.json_.
The only possible way I could find to use `GOPATH` is add `{ "from": "${command:go.gopath}", "to": "/remote/go/path" }`, but I cannot do the same thing for `GOROOT` since there's no `go.goroot` command.

**Describe the solution you'd like**
Adding a `go.goroot` command, returning the `GOROOT` value, just as `go.gopath` does for `GOPATH`.

**Describe alternatives you've considered**
I tried to use `"${env:GOROOT}"` and  `"${env:GOPATH}"`, but these env vars are not always defined.
I tried to find a way to run a shell command in the same context (something like `"${shell:go env GOROOT}"`), but that also didn't work.
I thought of working around this with a `preLaunchTask`, but couldn't find a way to use a task's output as an input for a launch configuration.

**Additional context**
N/A

It seems pretty easy to do (unless I'm missing something), so I'm willing to submit a PR with this, if you'll accept.

**Comment by hyangah** [comment]
Sounds good (I thought the same). Feel free to send a PR.
