### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by VerasThiago** [golang/vscode-go#2384]
gopls version: v0.1.7 (undefined)
gopls flags: 
update flags: proxy
extension version: 0.35.1
go version: 1.12.4
environment: Visual Studio Code win32
initialization error: Error: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.tagSupport of type bool
issue timestamp: Mon, 01 Aug 2022 00:25:52 GMT
restart history:
Mon, 01 Aug 2022 00:25:42 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
```
go version: 1.12.4
gopls version: v0.1.7 (undefined)
```

Is there a reason to use go 1.12.4? That is quite old. The language server won't build with the version.

After upgrading the go https://go.dev/dl/, reload the vscode and reinstall gopls using Command Palette -> "Go: Install/Update Tools" -> select gopls.

Or, if you need to work with go1.12 for your project, still install the latest go and build `go install golang.org/x/tools/gopls@latest` with the latest go.
