### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by lxqan2010** [golang/vscode-go#2385]
gopls version: v0.9.1 (go1.18.4)
gopls flags: -remote=auto -logfile=auto -debug=:0 -rpc.trace
update flags: proxy
extension version: 2022.7.2516
go version: 1.18.4
environment: Visual Studio Code win32
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Mon, 01 Aug 2022 10:00:47 GMT
restart history:
Mon, 01 Aug 2022 10:00:22 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
