### ISSUE TITLE
No icon for go.work.sum file

### ISSUE THREAD

**Issue by islishude** [golang/vscode-go#2390]
**Is your feature request related to a problem? Please describe.**

<img width="355" alt="image" src="https://user-images.githubusercontent.com/24730006/182741231-a2deabe1-6251-4783-962c-5327817bf626.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
version: v0.35.1

**Comment by findleyr** [comment]
Thanks for the report. We should fix this.

**Comment by findleyr** [comment]
I think @hyangah may already be working on this.

**Comment by islishude** [comment]
fixed by vscode-icons/vscode-icons#3363
