### ISSUE TITLE
[macOS Monterey with M1 darwin/arm64]: ⚠️ VSCode can't run/debug code, but GoLang (trial) can

### ISSUE THREAD

**Issue by silvioprog** [golang/vscode-go#2391]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* System `macOS Monterey version 12.5 (M1 darwin/arm64)`
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.18.5 darwin/arm64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
```----------
golang.org/x/tools/gopls v0.9.1
    golang.org/x/tools/gopls@v0.9.1 h1:SigsTL4Hpv3a6b/a7oPCLRv5QUeSM6PZNdta1oKY4B0=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.12-0.20220713141851-7464a5a40219 h1:Ljlba2fVWOA1049JjsKii44g8nZN2GjpxMlzVc8AnQM=
    golang.org/x/vuln@v0.0.0-20220613164644-4eb5ba49563c h1:r5bbIROBQtRRgoutV8Q3sFY58VzHW6jMBYl48ANSyS4=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.4
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.69.2 3b889b090b5ad5793f524b5d1d39fda662b96a2a x64`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.35.1`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
```GOBIN: /Users/user/go/bin
toolsGopath: 
gopath: /Users/user/go
GOROOT: /opt/homebrew/Cellar/go/1.18.5/libexec
PATH: /Users/user/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/Library/Apple/usr/bin

	go:	/opt/homebrew/bin/go: go version go1.18.5 darwin/arm64

	gotests:	/Users/user/go/bin/gotests	(version: v1.6.0 built with go: go1.18.4)
	gomodifytags:	/Users/user/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18.4)
	impl:	/Users/user/go/bin/impl	(version: v1.1.0 built with go: go1.18.4)
	goplay:	/Users/user/go/bin/goplay	(version: v1.0.0 built with go: go1.18.4)
	dlv:	/Users/user/go/bin/dlv	(version: v1.9.0 built with go: go1.18.4)
	staticcheck:	/Users/user/go/bin/staticcheck	(version: v0.3.2 built with go: go1.18.4)
	gopls:	/Users/user/go/bin/gopls	(version: v0.9.1 built with go: go1.18.4)

go env
Workspace Folder (hello): /Users/user/hello
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN="/Users/user/go/bin"
	GOCACHE="/Users/user/Library/Caches/go-build"
	GOENV="/Users/user/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/user/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/user/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/opt/homebrew/Cellar/go/1.18.5/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/opt/homebrew/Cellar/go/1.18.5/libexec/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.18.5"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/user/hello/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rx/wdllvmfs51v8ck43xv3lfw2r0000gn/T/go-build1635915992=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</details>

### Describe the bug

We can't run and debug code using F5 in VSCode on macOS Monterey with M1 processor.

It should debug properly, because I have a trial version of GoLand and it can debug without any problems, then it is not a problem related to the laptop.

### Steps to reproduce the behavior:
1. Create a "hello world"-like project
2. Open the project in VSCode, try to "Run and Debug" it
3. See error `could not launch process: stub exited while waiting for connection: exit status 0`

#### VSCode with error

<img width="1056" alt="Screen Shot 2022-08-03 at 11 39 29 PM" src="https://user-images.githubusercontent.com/1456829/182753911-a7343bb4-07aa-494c-bf00-8f637fa4038c.png">

#### GoLand debugging fine

<img width="919" alt="Screen Shot 2022-08-03 at 11 40 26 PM" src="https://user-images.githubusercontent.com/1456829/182753857-24e116ac-9fb6-4d70-9346-bd47cdeaf3a6.png">

**Comment by silvioprog** [comment]
After entirely reinstalling VSCode + Extension + Go 1.19, got another error and log:

### Debug Console Log

```
Starting: /Users/user/go/bin/dlv dap --check-go-version=false --listen=127.0.0.1:53333 --log-dest=3 from /Users/user/hello
DAP server listening at: 127.0.0.1:53333
```

### Error Dialog

<img width="320" alt="Screen Shot 2022-08-04 at 2 01 50 AM" src="https://user-images.githubusercontent.com/1456829/182766927-1f4d83fe-7d65-4668-b7ee-2fe465f5983c.png">

**Comment by silvioprog** [comment]
More info. I don't know why, but running `dlv` directly from the macOS default terminal, it runs without problem, but inside the VSCode terminal, it returns the same error from my previous message. Please take a look at this image below:

<img width="776" alt="Screen Shot 2022-08-04 at 2 38 40 AM" src="https://user-images.githubusercontent.com/1456829/182771256-454c6925-4a74-407d-880e-cecbb081fdf2.png">

**Comment by silvioprog** [comment]
Oh, the problem is because `dlv` can't work in VSCode terminal by default, but by adding `arch -arch arm64`, like `arch -arch arm64 dlv debug ./main.go`, it works fine.

How do I configure the extension to call `dlv` with prefix `arch -arch arm64`?

**Comment by silvioprog** [comment]
Fixed following this thread: https://github.com/go-delve/delve/issues/2332

**Comment by silvioprog** [comment]
Just created this wrapper script:

`% cat dlv-wrapper.sh`
```bash
#!/bin/sh
exec /usr/bin/arch -arch arm64 "$HOME/go/bin/dlv" "$@"
```

and added this to my `settings.json`:

```json
...
  "go.alternateTools": {
    "dlv": "$USER/dlv-wrapper.sh"
  }
...
```

then created a `launch.json` with this:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Package",
      "type": "go",
      "request": "launch",
      "mode": "auto",
      "program": "${fileDirname}"
    }
  ]
}
```

and it worked like a charm:

<img width="993" alt="Screen Shot 2022-08-04 at 3 27 40 AM" src="https://user-images.githubusercontent.com/1456829/182778265-39a3c28c-e69f-4cdc-94b4-4ebd38108644.png">

**Comment by hyangah** [comment]
My recommendation is to ensure all the software involved are for M1 (VSCode, Go, Delve) rather than working around by adding wrapper. 

https://github.com/go-delve/delve/issues/2332#issuecomment-1110562253 is the most reliable way to do so.

**Comment by silvioprog** [comment]
@hyangah OMG man, it fixed the problem. 😮
I don't know why my VSCode was installed for AMD, just downloaded the universal installer for Darwin and now it works like a charm without a workaround with a wrapper.
Thank you so much!
