### ISSUE TITLE
Debug can only start from main

### ISSUE THREAD

**Issue by BrunoKrugel** [golang/vscode-go#2392]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>
	- go version go1.18.3 darwin/arm64
	- golang.org/x/tools/gopls v0.9.1
	- code 1.69.2 
</details>

### Describe the bug
Working in big projects on vscode, I can only start a debug session if I select the main.go and then run the debug.

If I try to start a debug session with another file selected, I receive the following error message:
`Failed to launch: could not launch process: not an executable file`

The main is located in `cmd/project-name/main.go`
The other part of the project is located in `internal/api`

I would expect to be able to start a debug with any file selected (not only the main).

My launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "cwd": "${workspaceRoot}",
            "hideSystemGoroutines": true
        }
    ]
}
```

**Comment by suzmue** [comment]
I would recommend updating your launch.json to point to the folder containing the program that you want to run.

For example:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "debug", // This is not required but this makes it explicit you are not trying to debug a test.
            "program": "${workspaceRoot}/cmd/project-name", // Path to the directory containing main.
            "cwd": "${workspaceRoot}", 
            "hideSystemGoroutines": true
        }
    ]
}
```

You may want to update cwd depending on your program.

**Comment by BrunoKrugel** [comment]
Just for records, since we follow the same pattern in every project, if I use ${workspaceFolderBasename}, I dont need to update my launch.json for every project.

`"program": "${workspaceRoot}/cmd/${workspaceFolderBasename}/"`

Thanks for the help.
