### ISSUE TITLE
variable view won't expand this nested map ... 

### ISSUE THREAD

**Issue by breathe** [golang/vscode-go#2393]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.3 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.9.1
    golang.org/x/tools/gopls@v0.9.1 h1:SigsTL4Hpv3a6b/a7oPCLRv5QUeSM6PZNdta1oKY4B0=
    github.com/BurntSushi/toml@v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
    github.com/google/go-cmp@v0.5.7 h1:81/ik6ipDQS2aGcBfIN5dHDB36BwrStyeAQquSYCV4o=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220218215828-6cf2b201936e h1:qyrTQ++p1afMkO4DPEeLGq/3oTsdlvdH4vqZUBWzUKM=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20220209214540-3681064d5158 h1:rm+CHSpPEEW2IsXUib1ThaHIjuBVZjxNgSKmBLFfD4c=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.12-0.20220713141851-7464a5a40219 h1:Ljlba2fVWOA1049JjsKii44g8nZN2GjpxMlzVc8AnQM=
    golang.org/x/vuln@v0.0.0-20220613164644-4eb5ba49563c h1:r5bbIROBQtRRgoutV8Q3sFY58VzHW6jMBYl48ANSyS4=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.0 h1:kTojdZo9AcEYbQYhGuLf/zszYthRdhDNDUi2JKTxas4=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
arm64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.35.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/ncohen/go
GOROOT: /usr/local/go
PATH: /Users/ncohen/fauna/google-cloud-sdk/bin:/Users/ncohen/fauna/ops/util/cache/dependencies/hashicorp/bin:/Users/ncohen/fauna/ops/bin:/Users/ncohen/miniconda3/bin:/Users/ncohen/miniconda3/condabin:/Users/ncohen/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/ncohen/fauna/backup-restore-functions/node_modules/.bin:/Users/ncohen/go/bin:/Users/ncohen/bin:/Users/ncohen/.deno/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/usr/local/go/bin

	go:	/usr/local/go/bin/go: go version go1.18.3 darwin/arm64

	gotests:	/Users/ncohen/go/bin/gotests	(version: v1.6.0 built with go: go1.18)
	gomodifytags:	/Users/ncohen/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18)
	impl:	/Users/ncohen/go/bin/impl	(version: v1.1.0 built with go: go1.18)
	goplay:	/Users/ncohen/go/bin/goplay	(version: v1.0.0 built with go: go1.18)
	dlv:	/Users/ncohen/go/bin/dlv	(version: v1.9.0 built with go: go1.18.3)
	staticcheck:	/Users/ncohen/go/bin/staticcheck	(version: v0.2.2 built with go: go1.18)
	gopls:	/Users/ncohen/go/bin/gopls	(version: v0.9.1 built with go: go1.18.3)

go env
Workspace Folder (ops/): /Users/ncohen/fauna/ops

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
  "go.toolsManagement.autoUpdate": true,
  "[go]": {
    "editor.defaultFormatter": "golang.go"
  },
```

### Describe the bug

I can't get the debugger view to expand certain values ...  The nested map shown below shows length 2 but I can't see the other key/value ...

![image](https://user-images.githubusercontent.com/434034/182955818-5882e7c0-6b65-45f7-9289-98f14987c886.png)

### Steps to reproduce the behavior:
1. Try to debug a deeply nested response from the faunadb driver

**Comment by findleyr** [comment]
Hmm, as you said this only applies to certain values; I wasn't able to naively reproduce:
![image](https://user-images.githubusercontent.com/57144380/183446306-e1ba8450-f3ff-4ca3-b0b6-36086404ff99.png)

CC @suzmue, who might know why this happens.

**Comment by findleyr** [comment]
Since this is a dupe, let's close. @breathe please reopen if this isn't fixed for you in the next delve release.

**Comment by breathe** [comment]
Sorry I wasn't able to test when I saw the first message and then forgot to circle back.

I just tested with delve master branch and it definitely seems to work for my case!  Thanks a ton!!!! ❤️ ❤️ 

![image](https://user-images.githubusercontent.com/434034/184198750-ad11817b-ed3d-4429-8b27-abb8844625c7.png)
