### ISSUE TITLE
Configure PATH for go generate

### ISSUE THREAD

**Issue by pckhoi** [golang/vscode-go#2396]
**Is your feature request related to a problem? Please describe.**
I am generating code using `run go generate` button at the top of editor:

<img width="708" alt="Screen Shot 2022-08-08 at 08 53 04" src="https://user-images.githubusercontent.com/370820/183323063-1e5bbca7-bf98-46c0-8dde-c9c87f1c3fe8.png">

However it fails with this error:
```
running "oapi-codegen": exec: "oapi-codegen": executable file not found in $PATH
```

I installed `oapi-codegen` with `go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest` so I expect Go to pick up executables from `$GOPATH/bin` or at least allow configuring PATH during go generate.

**Describe the solution you'd like**
One of these solutions:
1. Add `$GOPATH/bin` to $PATH during `run go generate`
2. Add a setting to configure additional paths to find executables during `run go generate`.

**Describe alternatives you've considered**
I guess I could manually copy the executable to `/usr/local/bin`, however that is less convenient.

**Additional context**

**Comment by findleyr** [comment]
Hi, you should be able to configure this path using `build.env`:
https://github.com/golang/vscode-go/blob/master/docs/settings.md#buildenv

Closing this issue as I believe this should work. Please reopen if it doesn't work.
