### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by onlySlient** [golang/vscode-go#2398]
gopls version: v0.9.2 (go1.18.3)
gopls flags: 
update flags: proxy
extension version: 0.35.1
go version: 1.18.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 11 Aug 2022 02:43:10 GMT
restart history:
Thu, 11 Aug 2022 02:26:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by onlySlient** [comment]
Thanks for the replay. But i can't reflectoring it.

**Comment by findleyr** [comment]
@onlySlient you mean it is not reproducible?

**Comment by onlySlient** [comment]
> @onlySlient you mean it is not reproducible?

yes.

**Comment by findleyr** [comment]
Ok, thank you for confirming. Closing as this is not actionable. If you do see it reproduce, please reopen this issue (or file a new one).
