### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by MeridjaNassim** [golang/vscode-go#2400]
gopls version: v0.9.2 (go1.18.4)
gopls flags: 
update flags: proxy
extension version: 2022.8.313
go version: 1.18.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 11 Aug 2022 12:34:32 GMT
restart history:
Mon, 08 Aug 2022 21:49:09 GMT: activation (enabled: true)
Mon, 08 Aug 2022 22:20:39 GMT: installation (enabled: true)
Thu, 11 Aug 2022 02:21:21 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid start/end token.Pos

goroutine 187 [running]:
golang.org/x/tools/internal/span.NewRange(...)
	  token.go:33
golang.org/x/tools/internal/lsp/cache.(*snapshot).applyCriticalErrorToFiles(0xc0000d2500, {0x1087b50, 0xc0006add70}, {0xe6e576, 0x193}, {0xc0004e2b40%3F, 0x1, 0xc0003e3570%3F})
	  load.go:383  0x58a
golang.org/x/tools/internal/lsp/cache.(*snapshot).workspaceLayoutError(0xc0000d2500, {0x1087b50, 0xc0006add70})
	  load.go:330  0x20b
golang.org/x/tools/internal/lsp/cache.(*snapshot).GetCriticalError(0xc0000d2500, {0x1087b50, 0xc0006add70})
	  snapshot.go:1391  0x2b6
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc0002f6ea0, {0x1087b50, 0xc00044b9e0}, {0x1090310, 0xc0000d2500}, 0x0)
	  diagnostics.go:264  0xecd
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc0002f6ea0, {0x1090310, 0xc0000d2500}, {0xc0004e3160, 0x1, 0x1}, 0x88%3F)
	  diagnostics.go:153  0x2f1
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshots.func1({0x1090310%3F, 0xc0000d2500%3F}, {0xc0004e3160%3F, 0xc0000e80a0%3F, 0xc000222fb8%3F})
	  diagnostics.go:130  0x85
created by golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshots
	  diagnostics.go:128  0x90
[Error - 1:34:14 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, this looks like a new crash introduced in the v0.9.2 release. Could you share any more information about your workspace? Do you have a go.work file? How many go.mod files do you have?

**Comment by findleyr** [comment]
Tracking this in golang/go#54395, so I'll close this as a duplicate.
