### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by TheLuckymadman** [golang/vscode-go#2402]
gopls version: v0.9.2 (go1.18.3)
gopls flags: 
update flags: proxy
extension version: 0.35.1
go version: 1.18.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 11 Aug 2022 15:29:39 GMT
restart history:
Thu, 11 Aug 2022 15:29:27 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid start/end token.Pos

goroutine 184 [running]:
golang.org/x/tools/internal/span.NewRange(...)
	  token.go:33
golang.org/x/tools/internal/lsp/cache.(*snapshot).applyCriticalErrorToFiles(0xc0001f6dc0, {0x1086910, 0xc0004cf2c0}, {0xe6d4ab, 0x193}, {0xc000220f50%3F, 0x1, 0xc0006cb570%3F})
	  load.go:383  0x58a
golang.org/x/tools/internal/lsp/cache.(*snapshot).workspaceLayoutError(0xc0001f6dc0, {0x1086910, 0xc0004cf2c0})
	  load.go:330  0x20b
golang.org/x/tools/internal/lsp/cache.(*snapshot).GetCriticalError(0xc0001f6dc0, {0x1086910, 0xc0004cf2c0})
	  snapshot.go:1391  0x2b6
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc00057c480, {0x1086910, 0xc0006bd170}, {0x108f0d0, 0xc0001f6dc0}, 0x0)
	  diagnostics.go:264  0xecd
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc00057c480, {0x108f0d0, 0xc0001f6dc0}, {0xc00030f9c0, 0x1, 0x1}, 0x88%3F)
	  diagnostics.go:153  0x2f1
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshots.func1({0x108f0d0%3F, 0xc0001f6dc0%3F}, {0xc00030f9c0%3F, 0xc0001740a0%3F, 0xc00031dfb8%3F})
	  diagnostics.go:130  0x85
created by golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshots
	  diagnostics.go:128  0x90
[Error - 6:29:29 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
This is https://github.com/golang/go/issues/54395, which is fixed in gopls@v0.9.3-pre.1. gopls@v0.9.3 will be released later today.
