### ISSUE TITLE
Getting code actions from 'Go' Error

### ISSUE THREAD

**Issue by hieunguyen1809** [golang/vscode-go#2410]
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
go1.17.6 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
golang.org/x/tools/gopls v0.9.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
Version: 1.70.1 (Universal)
* Check your installed extensions to get the version of the VS Code Go extension
0.35.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
GOBIN: undefined
toolsGopath: 
gopath: /Users/hieu.nguyen6/go
GOROOT: /opt/homebrew/Cellar/go/1.17.6/libexec
PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/hieu.nguyen6/go/bin
go:	/opt/homebrew/bin/go: go version go1.17.6 darwin/arm64
gotests:	/Users/hieu.nguyen6/go/bin/gotests	(version: v1.6.0 built with go: go1.17.6)
gomodifytags:	/Users/hieu.nguyen6/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.17.6)
impl:	/Users/hieu.nguyen6/go/bin/impl	(version: v1.1.0 built with go: go1.17.6)
goplay:	/Users/hieu.nguyen6/go/bin/goplay	(version: v1.0.0 built with go: go1.17.6)
dlv:	/Users/hieu.nguyen6/go/bin/dlv	(version: v1.9.0 built with go: go1.17.6)
staticcheck:	/Users/hieu.nguyen6/go/bin/staticcheck	(version: v0.3.3 built with go: go1.17.6)
gopls:	/Users/hieu.nguyen6/go/bin/gopls	(version: v0.9.3 built with go: go1.17.6)
go env
Workspace Folder (tially): /Users/hieu.nguyen6/Work/tially
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/Users/hieu.nguyen6/Library/Caches/go-build"
	GOENV="/Users/hieu.nguyen6/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/hieu.nguyen6/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/hieu.nguyen6/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/opt/homebrew/Cellar/go/1.17.6/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/opt/homebrew/Cellar/go/1.17.6/libexec/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.17.6"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/hieu.nguyen6/Work/tially/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vs/x0tqch917cxd68zdq87y_w9w0000gp/T/go-build1832282771=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
`{
    "editor.minimap.enabled": false,
    "editor.fontWeight": "normal",
    "workbench.colorTheme": "Monokai",
    "timeline.excludeSources": [
        "timeline.localHistory"
    ],
    // go settings
    "go.logging.level": "verbose",
    "go.testEnvFile": "${workspaceFolder}/test.env",
    "go.autocompleteUnimportedPackages": true,
    "go.useLanguageServer": true,
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.fixAll": true,
            "source.organizeImports": true
        },
        "editor.suggest.snippetsPreventQuickSuggestions": false,
    },
    "go.inlayHints.constantValues": true,
    "go.inlayHints.functionTypeParameters": true,
    "go.inlayHints.parameterNames": true,
    "go.inlayHints.rangeVariableTypes": true,
    "gopls": {
        "verboseOutput": true,
    }
}`

### Describe the bug
Cannot save file, Showing pop up "Getting code actions from 'Go'"

**Comment by findleyr** [comment]
It is possible that you have run into https://github.com/golang/vscode-go/issues/2406.

To check, can you install the previous gopls version?
`go install golang.org/x/tools/gopls@v0.9.1`?

(if it is not that issue, we can investigate further)

**Comment by hieunguyen1809** [comment]
I still have same issue with version 0.9.1

**Comment by findleyr** [comment]
Thanks. Can you please share the log you see in the gopls output channel?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by hieunguyen1809** [comment]
Ya sure
`
Failed to stop client: timeout
[Error - 9:19:11 AM] Stopping server timed out
[Info  - 9:19:11 AM] 2022/08/16 09:19:11 go env for /Users/hieu.nguyen6/Work/tially
(root /Users/hieu.nguyen6/Work/tially)
(go version go version go1.17.6 darwin/arm64)
(valid build configuration = true)
(build flags: [])
GOMOD=/Users/hieu.nguyen6/Work/tially/go.mod
GOPATH=/Users/hieu.nguyen6/go
GOSUMDB=sum.golang.org
GOWORK=
GOCACHE=/Users/hieu.nguyen6/Library/Caches/go-build
GOROOT=/opt/homebrew/Cellar/go/1.17.6/libexec
GOINSECURE=
GONOPROXY=
GONOSUMDB=
GOPRIVATE=
GOPROXY=https://proxy.golang.org,direct
GOFLAGS=
GO111MODULE=
GOMODCACHE=/Users/hieu.nguyen6/go/pkg/mod
`

**Comment by findleyr** [comment]
Hmm, we need to see what is happening prior to that output. Could you please enable gopls logging, and share the resulting logs?
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information

**Comment by hieunguyen1809** [comment]
Sorry for the late reply. Suddenly since yesterday, no more errors occurred. I think downgrading gopls version help

**Comment by findleyr** [comment]
Hi, can you confirm whether you are on gopls@v0.9.1, or gopls@v0.9.4? We release v0.9.4 yesterday with a fix for #2406.

Related: can you search your codebase for the string "2006-02-01"? If that string is present, it is likely that you ran into #2406, and would help us rule out a different regression.
