### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by fxjsb** [golang/vscode-go#2411]
gopls version: v0.9.3 (go1.18beta1)
gopls flags: 
update flags: proxy
extension version: 0.33.1
go version: 1.18beta1
environment: iCoding linux
initialization error: undefined
issue timestamp: Mon, 15 Aug 2022 12:35:28 GMT
restart history:
Mon, 15 Aug 2022 12:34:57 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: nil underlying

goroutine 12854 [running]:
go/types.(*Checker).handleBailout(0xc0001eba40, 0xc003bad4e0)
	  check.go:279  0x8b
panic({0xcd0f60, 0x1073bc0})
	  panic.go:838  0x207
go/types.(*Named).under(0xc008c52d00)
	  named.go:158  0x432
go/types.lookupFieldOrMethod({0x1079230%3F, 0xc008c52d00%3F}, 0x0, 0x107b7c8%3F, {0xc000920ab0, 0xd})
	  lookup.go:142  0x63d
go/types.LookupFieldOrMethod({0x1079230%3F, 0xc008c52d00%3F}, 0xc8%3F, 0xc0061acc60%3F, {0xc000920ab0%3F, 0xd%3F})
	  lookup.go:63  0xb9
go/types.(*Checker).selector(0xc0001eba40, 0xc005d17fc0, 0xc006cedc20)
	  call.go:530  0x491
go/types.(*Checker).typInternal(0xc0001eba40, {0x107ba68%3F, 0xc006cedc20%3F}, 0xc008c52d00)
	  typexpr.go:253  0x895
go/types.(*Checker).definedType(0xc0139b6f30%3F, {0x107ba68%3F, 0xc006cedc20}, 0x3%3F)
	  typexpr.go:174  0x45
go/types.(*Checker).typeDecl(0xc0001eba40, 0xc00fdeee10, 0xc002ee4980, 0x0)
	  decl.go:661  0x5c8
go/types.(*Checker).declStmt.func1({0x10773e0%3F, 0xc002ee4980%3F})
	  decl.go:976  0x365
go/types.(*Checker).walkDecl(0x435ad3%3F, {0x107b768%3F, 0xc002ee4a80%3F}, 0xc003bac828)
	  decl.go:490  0x407
go/types.(*Checker).declStmt(0xc0001eba40%3F, {0x107b768%3F, 0xc002ee4a80%3F})
	  decl.go:884  0x51
go/types.(*Checker).stmt(0xc0001eba40, 0x0, {0x107b5b8%3F, 0xc0060be880%3F})
	  stmt.go:383  0x1e3b
go/types.(*Checker).stmtList(0x0%3F, 0x0, {0xc002ee4f00%3F, 0x0%3F, 0x0%3F})
	  stmt.go:125  0xc9
go/types.(*Checker).funcBody(0xc0001eba40, 0xc003dc1860, {0x0%3F, 0xd07080%3F}, 0xc005669400, 0xc00bcde420, {0x0, 0x0})
	  stmt.go:46  0x285
go/types.(*Checker).funcDecl.func1()
	  decl.go:876  0x45
go/types.(*Checker).processDelayed(0xc0001eba40, 0x0)
	  check.go:348  0x39
go/types.(*Checker).checkFiles(0xc0001eba40, {0xc00c3454a8%3F, 0xc009b95400%3F, 0x0%3F})
	  check.go:301  0xcb
go/types.(*Checker).Files(...)
	  check.go:284
golang.org/x/tools/internal/lsp/cache.doTypeCheck({0x107cb48, 0xc009385600}, 0xc000376640, {0xc001eb1dc0, 0x1, 0x0%3F}, {0xc001eb1dd0, 0x1, 0x1}, 0xc0015722d0, ...)
	  check.go:575  0x9f3
golang.org/x/tools/internal/lsp/cache.typeCheckImpl({0x107cb48%3F, 0xc009385600}, 0xc000376640, {0xc001eb1dc0, 0x1, 0x1}, {0xc001eb1dd0, 0x1, 0x1}, 0xc0015722d0, ...)
	  check.go:339  0x345
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1({0x107cb48%3F, 0xc009385600%3F}, {0xdf8160%3F, 0xc000376640%3F})
	  check.go:150  0xb7
golang.org/x/tools/internal/memoize.(*Promise).run.func2.1()
	  memoize.go:187  0xa9
runtime/trace.WithRegion({0x107cb48%3F, 0xc009385600%3F}, {0xc01390d140, 0x22}, 0xc003d1df90)
	  annotation.go:141  0xe3
golang.org/x/tools/internal/memoize.(*Promise).run.func2()
	  memoize.go:180  0x145
created by golang.org/x/tools/internal/memoize.(*Promise).run
	  memoize.go:179  0x1d0
[Error - 8:35:08 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
This looks like golang/go#51509.

Can you please upgrade to a released version of Go (1.19 or 1.18)?

Closing as I believe this was fixed in the 1.18 release. Please reopen if now.
