### ISSUE TITLE
Language server keeps crashing

### ISSUE THREAD

**Issue by filipegorges** [golang/vscode-go#2412]
Type: <b>Bug</b>

Steps:
* Fresh install VSCode
* Fresh install Ubuntu in WSL2
* Install Go from official website
* Open a project with Go code
* Install Go extension
* Install Go gopls

Try to autocomplete methods or to navigate into, observe it to stop working after a few seconds, every further attempt will hang on "Loading..." until reloading the window, which will work for a few seconds and hang again, until you can't save the file anymore, hangs on "Saving 'filename.go': Getting code actions from "Go" (configure)."

Extension version: 0.35.1
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (4.82GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/reuwsaat/taco/services/oms --remote=wsl+Ubuntu --crash-reporter-id df7f0f6e-64ab-455f-9960-b20955e6964c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (8 x 2592)|
|Memory (System)|5.80GB (2.27GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyone:30545435

```

</details>

**Comment by berndverst** [comment]
This has been happening to me for months and causes multi-minute freezes of my IDE. So much so that I am about to give up on this extension and use GoLand (which does not suffer from this). Still happening on:

```
golang.org/x/tools/gopls v0.9.4
    golang.org/x/tools/gopls@v0.9.4 h1:YhHOxVi++ILnY+QnH9FGtRKZZrunSaR7OW8/dCp7bBk=
```

The go language server just hangs on any save action and no edits can be made to any file as a result.

FWIW - I'm on M1 Mac running Go 1.19.0 (arm64).

**Comment by findleyr** [comment]
@berndverst could you try capturing gopls output when this happens, as described in the comment above? If you are able to reproduce, and capture logs, please open a separate issue.

**Comment by berndverst** [comment]
> @berndverst could you try capturing gopls output when this happens, as described in the comment above? If you are able to reproduce, and capture logs, please open a separate issue.

False alarm actually -- deleted my original comment. My hangs stemmed from the package linting which is very slow. Disabled the linter for my workspace and all is well.
