### ISSUE TITLE
vscode 不支持 go mod

### ISSUE THREAD

**Issue by robyn-he** [golang/vscode-go#2416]
Issue Type: <b>Feature Request</b>

vscode 不支持 go mod 模式，提示找不到对应的包

Extension version: 0.35.2
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

**Comment by findleyr** [comment]
Hi, vscode does support modules. Please open your vs code workspace to a directory containing a go.mod, or use a go.work file.

Please see https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md for more information.

Can you share more information about what you're trying to do?
