### ISSUE TITLE
function documentation rendering error

### ISSUE THREAD

**Issue by 0xff-dev** [golang/vscode-go#2423]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info----------
golang.org/x/tools/gopls v0.9.4
    golang.org/x/tools/gopls@v0.9.4 h1:YhHOxVi++ILnY+QnH9FGtRKZZrunSaR7OW8/dCp7bBk=
    github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.13-0.20220812184215-3f9b119300de h1:b68wxF4nfQjj1XTRHtjVjCximbhAwjztuzDEFGU+n9o=
    golang.org/x/vuln@v0.0.0-20220725105440-4151a5aca1df h1:BkeW9/QJhcigekDUPS9N9bIb0v7gPKKmLYeczVAqr2s=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 19.6.0
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.35.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/shuang/.go
GOROOT: /usr/local/Cellar/go/1.19/libexec
PATH: /usr/local/Cellar/go/1.19/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/shuang/.cargo/bin:/Users/shuang/.go/bin:/Users/shuang/.cargo/bin
PATH (vscode launched with): /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/shuang/.cargo/bin:/Users/shuang/.go/bin:/Users/shuang/.cargo/bin

	go:	/usr/local/Cellar/go/1.19/libexec/bin/go: go version go1.19 darwin/amd64

	gotests:	/Users/shuang/.go/bin/gotests	(version: v1.6.0 built with go: go1.19)
	gomodifytags:	/Users/shuang/.go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19)
	impl:	/Users/shuang/.go/bin/impl	(version: v1.1.0 built with go: go1.19)
	goplay:	/Users/shuang/.go/bin/goplay	(version: v1.0.0 built with go: go1.19)
	dlv:	/Users/shuang/.go/bin/dlv	(version: v1.9.0 built with go: go1.19)
	staticcheck:	/Users/shuang/.go/bin/staticcheck	(version: v0.3.3 built with go: go1.19)
	gopls:	/Users/shuang/.go/bin/gopls	(version: v0.9.4 built with go: go1.19)

go env
Workspace Folder (arbiter.k8s.com.cn): /Users/shuang/worker/gitlab/arbiter.k8s.com.cn
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/shuang/Library/Caches/go-build"
	GOENV="/Users/shuang/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/shuang/.go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/shuang/.go"
	GOPRIVATE=""
	GOPROXY="https://goproxy.cn,direct"
	GOROOT="/usr/local/Cellar/go/1.19/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.19/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.19"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK="/Users/shuang/worker/gitlab/arbiter.k8s.com.cn/go.work"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1y/2t35nccn4tg5pzrjyx6bgjhw0000gn/T/go-build530321150=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/20641704/186368149-462a526b-b9ed-4da2-bebf-c3be7922d120.png">

### Describe the bug
All characters after `'s` are red.
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/20641704/186368657-cd3fc8ab-f000-4b88-82e1-e566257a8b0e.png">

### Steps to reproduce the behavior:
condition 1
```go
// TryMake it's my function.
//
//	it's my bug.
func TryMake() {
	slice := make([]int, 10)
}
```
<img width="425" alt="image" src="https://user-images.githubusercontent.com/20641704/186369436-708213e9-c2b6-4c01-8deb-9e41d7b047f9.png">

condition 2
```go
// TryMake it's my function.
//
//	it's my bug.
//	it's my second bug.
func TryMake() {
	slice := make([]int, 10)
}
```
<img width="524" alt="image" src="https://user-images.githubusercontent.com/20641704/186369496-9a1853de-2002-4126-96c2-48162883abb1.png">

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by suzmue** [comment]
Thanks for filing this issue! The coloring appears to be done from the vscode side, it may be treating it as a code snippet? More investigation needed.

**Comment by suzmue** [comment]
This is actually working as intended. 

If you look at the code blocks section about Doc Comments: https://tip.golang.org/doc/comment, you can see that indented lines are meant to be treated as lines of code. Fixing the indentation should resolve the issue.
