### ISSUE TITLE
input code will not automatically import the package

### ISSUE THREAD

**Issue by enjoycx** [golang/vscode-go#2426]
environment :
mac 
go 1.16.15  
remote local docker container

trigger：
add go.mod package rebuild  
repeatedly switch different  go.mod git branch

try:
delete .vscode
rebuild container 
download golang extend

other project no problem

**Comment by suzmue** [comment]
Hi @enjoycx! Could you please provide more details about the commands you are trying to execute? And if possible could you also provide a reproducible example? Thanks!
