### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by AdityoGunawan** [golang/vscode-go#2429]
gopls version: v0.9.4 (go1.18.5)
gopls flags: Go
update flags: proxy
extension version: 0.35.2
go version: 1.18.5
environment: Visual Studio Code win32
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 27 Aug 2022 20:09:39 GMT
restart history:
Sat, 27 Aug 2022 18:46:02 GMT: activation (enabled: true)
Sat, 27 Aug 2022 19:08:05 GMT: config change (enabled: true)
Sat, 27 Aug 2022 19:10:32 GMT: manual (enabled: true)
Sat, 27 Aug 2022 20:09:10 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by jamalc** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by AdityoGunawan** [comment]
Like this, man?

Pada tanggal Sel, 30 Agu 2022 01.51, Jamal ***@***.***>
menulis:

**Comment by AdityoGunawan** [comment]
Pada tanggal Sel, 30 Agu 2022 14.48, Muhammad Adityo Gunawan <
***@***.***> menulis:
