### ISSUE TITLE
semantic highlighting ? 

### ISSUE THREAD

**Issue by junknet** [golang/vscode-go#243]
Full lsp?

**Comment by stamblerre** [comment]
Semantic tokens are coming the LSP in [version 3.16](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/). I am not yet sure when `gopls` will have support for semantic tokens, though.

Does that answer your question?

**Comment by junknet** [comment]
> Semantic tokens are coming the LSP in [version 3.16](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/). I am not yet sure when `gopls` will have support for semantic tokens, though.
> 
> Does that answer your question?

I read the source code of gopls.
Gopls implements full lsp function,including the latest semantic tokens format.
[line:2642](https://github.com/golang/tools/blob/99be2d6e796f9bc16b66c42a44c468872fd31f66/internal/lsp/protocol/tsprotocol.go)
But vscode client not implemented.

**Comment by stamblerre** [comment]
`gopls` has the latest version of the API, but it does not yet have the implementation.
3.16 has still not been released, so the language client used by this extension does not yet support it.

**Comment by junknet** [comment]
All right，I look forward to seeing the colorful code.

**Comment by junknet** [comment]
All right，I look forward to seeing the colorful code.
