### ISSUE TITLE
The Intellisence missing sub-popup window after update vscode to 1.71.0

### ISSUE THREAD

**Issue by aaftio** [golang/vscode-go#2439]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- **go version go1.19 windows/amd64**
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- **golang.org/x/tools/gopls v0.9.4**
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- **1.71.0**
* Check your installed extensions to get the version of the VS Code Go extension
	- **0.35.2**
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- gotests:	C:\Users\go\bin\gotests.exe	(version: v1.6.0 built with go: go1.19)
	- gomodifytags:	C:\Users\go\bin\gomodifytags.exe	(version: v1.16.0 built with go: go1.19)
	- impl:	C:\Users\go\bin\impl.exe	(version: v1.1.0 built with go: go1.19)
	- goplay:	C:\Users\go\bin\goplay.exe	(version: v1.0.0 built with go: go1.19)
	- dlv:	C:\Users\go\bin\dlv.exe	(version: v1.9.1 built with go: go1.19)
	- staticcheck:	C:\Users\go\bin\staticcheck.exe	(version: v0.3.3 built with go: go1.19)
	- gopls:	C:\Users\go\bin\gopls.exe	(version: v0.9.4 built with go: go1.19)
</details>

### Share the Go related settings you have added/edited

> No custom setting, use default setting

### Describe the bug
The suggetion of method without method infomation (comment and signature)

#### My situation
<img width="701" alt="屏幕截图 2022-09-05 213457" src="https://user-images.githubusercontent.com/1856880/188464272-b9dfda63-cd71-4c15-b2f1-82a51a17a277.png">

#### Expected performance
<img width="540" alt="屏幕截图 2022-09-05 213342" src="https://user-images.githubusercontent.com/1856880/188464468-2b4f55de-ef3b-4dbc-9fa0-6bcc1bee971c.png">

**Comment by adonovan** [comment]
This looks like an "unimported completion", which doesn't have type information. The question is: why is fmt unable to be imported (hence the red squiggle)? It should always work. This suggests go list is failing entirely in the workspace.

**Comment by aaftio** [comment]
@adonovan All my package has this problem, and I found this is a feature...,  there is a hidden arrow after the selected method item, and only appear when the mouse hover on it.  The design make it hard to be noticed 🤣

![vscode-intellicense-more](https://user-images.githubusercontent.com/1856880/189274361-85373a5c-f70d-47de-8f15-fc9159bc62fc.gif)
