### ISSUE TITLE
Tooltip shows multiple method docs when two types in the same package have a method of the same name. 

### ISSUE THREAD

**Issue by brackendawson** [golang/vscode-go#244]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.4
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/alandaws/bin"
GOCACHE="/Users/alandaws/Library/Caches/go-build"
GOENV="/Users/alandaws/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.ibm.com"
GONOSUMDB="github.ibm.com"
GOOS="darwin"
GOPATH="/Users/alandaws"
GOPRIVATE="github.ibm.com"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/06/jjq25lws0cbcxv37ns0hb_mm0000gn/T/go-build816901073=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited
```
{
    "carbon.theme": "monokai",
    "workbench.colorTheme": "Monokai",
    "git.autofetch": true,
    "git.confirmSync": false,
    "files.insertFinalNewline": true,
    "update.mode": "manual",
    "editor.acceptSuggestionOnCommitCharacter": false,
    "editor.acceptSuggestionOnEnter": "off",
    "editor.rulers": [
        80
    ],
    "diffEditor.ignoreTrimWhitespace": false,
    "go.coverageOptions": "showUncoveredCodeOnly",
    "go.installDependenciesWhenBuilding": false,
    "go.testOnSave": true,
    "go.coverOnSave": true,
    "go.gocodeAutoBuild": true,
    "go.gotoSymbol.includeImports": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.testEnvFile": "",
    "terminal-tools.tools": [
        "cd"
    ],
    "go.lintTool": "golangci-lint",
    "go.formatTool": "goimports",
    "window.zoomLevel": 0,
}
```

### Describe the bug
When you hover the mouse over a method that has a duplicate by the same name on a different type in the same package, you get the documentation for both methods.

### Steps to reproduce the behavior:
1. Write this package:
```
package kata

import (
	"bufio"
)

func test() {
	b := bufio.Reader{}
	b.Size()
}
```
2. Hover over `Size()`, or finish typing it with the cursor between the parentheses.
3. See the function signature of `bufio.Reader.Size` but the docstrings of both `bufio.Reader.Size` and `bufio.Writer.Size` (the docstrings are the same). I noticed this issue on a package in a private repo that had two different docstrings but I can't find such an example in the standard library.

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/1909753/85180448-6b59f300-b27b-11ea-8a1b-3625346943fd.png)

**Comment by brackendawson** [comment]
@gopherbot this is bug not documentation

**Comment by brackendawson** [comment]
`math/big` is a better example, there are three String()ers in there with different docstrings:
![image](https://user-images.githubusercontent.com/1909753/85183422-892b5600-b283-11ea-9686-a7d8bcc6c925.png)

Found using
`for p in $(go list std); do find /usr/local/go/src/$p -name '*.go' -depth 1 | grep -v '/internal/' | xargs cat | PACK=$p perl -ne '/^func \(.*\) ([A-Z]\w*)\(/ && print "$ENV{'PACK'}.$1\n"' | sort | uniq -c | grep -v '^\s\+1'; done | sort -n`

**Comment by hyangah** [comment]
Looking at the code, that's a limitation of the underlying tool (`godef`) used to extract the symbol information passed to `go doc`. [`gogetdoc`](https://github.com/zmb3/gogetdoc)  doesn't seem to have this issue. Can you please try `"go.docsTool": "gogetdoc"` if it meets your needs?

And, switching to use the language server is another option (`"go.useLanguageServer": true`).

@gopherbot remove label Documentation

**Comment by brackendawson** [comment]
Changing the docs tool to `gogetdoc` does solve this issue.

gpls also doesn't have the issue, but it does still take quite a long time to make tooltips.

**Comment by stamblerre** [comment]
`gopls` should not be slow, so if you're experiencing slowness, please do [share your logs](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) and I can help debug why that's happening.

Otherwise, if you're happy with `gogetdoc`, that's fine as well, and we can close this issue.

**Comment by brackendawson** [comment]
Can definitely close this now.

Thanks, I'll make sure I'm running a recent release of gopls and check out the troubleshooting guide before I waste anyone else's time on that.
