### ISSUE TITLE
Cant save go file. If I save the code, code flickers in the screen

### ISSUE THREAD

**Issue by narayann7** [golang/vscode-go#2459]
go version go1.19.1 windows/amd64

Build info
----------
golang.org/x/tools/gopls v0.9.5
    golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
    github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.13-0.20220908144252-ce397412b6a4 h1:glzimF7qHZuKVEiMbE7UqBu44MyTjt5u6j3Jz+rfMRM=
    golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058 h1:YnB27EXBD8XxB0JcaOeluuvhF2kS4DrH0k+lpopG2xc=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
- go: go1.19.1
- VS Code Version: 1.71.1, (hash : e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb), x64
- OS Version: 21H2 (Windows 11)
- there is no settings with the `go.` or `["go"]` or `gopls` prefixes.

if i save the go code 
![ezgif-5-ead1351322](https://user-images.githubusercontent.com/64174995/190474168-3d906034-5d1e-459d-b6a8-a3e9acf9f011.gif)

continue flickering happens, when I type anything it stops and when I undo the code, code goes up and down it's like inserting a line and then deleting it

this wont happens for any other language

**Comment by findleyr** [comment]
Presumably VS Code is formatting the code, but I wonder what is doing the unformatting? Possibly fighting with another extension?

@hyangah do you know any way to see a trace of the editor operations causing edits?

**Comment by narayann7** [comment]
@findleyr yup you are right the issue was created by `Go Group Imports v1.1.4`, actually go default formatter and this extension as you said fighting with each out to format the code.
