### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Life-Hex** [golang/vscode-go#246]
- Issue Type: `Bug`
- Extension Name: `Go`
- Extension Version: `0.14.4`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.46.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 22965,
		"activateCallTime": 47,
		"activateResolvedTime": 38,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "golang.Go",
				"_lower": "golang.go"
			},
			"activationEvent": "onLanguage:go"
		}
	},
	"runtimeErrors": []
}
```

**Comment by stamblerre** [comment]
@Life-Hex: Can you please describe the problem you experienced?

**Comment by hyangah** [comment]
Closing this. @Life-Hex please reopen this issue or open a new one with more details. Thanks!
