### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by a0709** [golang/vscode-go#2475]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.16.3 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.9.5
    golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.13-0.20220908144252-ce397412b6a4 h1:glzimF7qHZuKVEiMbE7UqBu44MyTjt5u6j3Jz+rfMRM=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.16.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.71.2
* Check your installed extensions to get the version of the VS Code Go extension
	- go、go nightiy
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- GO111MODULE="auto"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/data/home/yuanleihao/.cache/go-build"
	GOENV="/data/home/yuanleihao/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/data/home/yuanleihao/go/pkg/mod"
	GONOPROXY="git.code.oa.com,git.woa.com"
	GONOSUMDB="git.code.oa.com,git.woa.com"
	GOOS="linux"
	GOPATH="/data/home/yuanleihao/go"
	GOPRIVATE="git.code.oa.com,git.woa.com"
	GOPROXY="https://goproxy.cn,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.16.3"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2383152569=/tmp/go-build -gno-record-gcc-switches"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
![image](https://user-images.githubusercontent.com/52312100/191673693-e29da243-f5a7-471d-9f5e-059d8c76e611.png)

### Describe the bug
![image](https://user-images.githubusercontent.com/52312100/191673780-d00f22e1-160c-49a3-9bf1-8e83af2a5d58.png)

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by a0709** [comment]
output error message:


[Error - 3:00:38 PM] 2022/09/22 15:00:38 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:00:39 PM] 2022/09/22 15:00:39 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:00:40 PM] 2022/09/22 15:00:40 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:00:40 PM] 2022/09/22 15:00:40 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:01:00 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Error - 3:01:02 PM] 2022/09/22 15:01:02 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:01:32 PM] 2022/09/22 15:01:32 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:01:32 PM] 2022/09/22 15:01:32 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:01:32 PM] 2022/09/22 15:01:32 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:01:35 PM] 2022/09/22 15:01:35 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:01:36 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Error - 3:01:37 PM] 2022/09/22 15:01:37 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:01:39 PM] 2022/09/22 15:01:39 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:01:40 PM] 2022/09/22 15:01:40 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:01:40 PM] 2022/09/22 15:01:40 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:01:47 PM] 2022/09/22 15:01:47 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:01:47 PM] 2022/09/22 15:01:47 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:01:54 PM] 2022/09/22 15:01:54 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:01:54 PM] 2022/09/22 15:01:54 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:02:10 PM] 2022/09/22 15:02:10 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:02:12 PM] 2022/09/22 15:02:12 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:02:12 PM] 2022/09/22 15:02:12 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:308:5: expected operand, found '}' (and 12 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:02:13 PM] 2022/09/22 15:02:13 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:38 PM] 2022/09/22 15:02:38 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:39 PM] 2022/09/22 15:02:39 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:02:39 PM] 2022/09/22 15:02:39 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:02:39 PM] 2022/09/22 15:02:39 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:40 PM] 2022/09/22 15:02:40 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:42 PM] 2022/09/22 15:02:42 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:43 PM] 2022/09/22 15:02:43 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:02:43 PM] 2022/09/22 15:02:43 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:43 PM] 2022/09/22 15:02:43 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:352:6: expected '(', found getXgbScore (and 4 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:02:44 PM] 2022/09/22 15:02:44 imports fixes: AllImportsFixes: /data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go:352:6: expected '(', found getXgbScore (and 4 more errors)
	file="/data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall/recaller_keyword_xgb_vector.go"

[Error - 3:02:45 PM] 2022/09/22 15:02:45 unable to compute positions for type errors: no parsed file for  in git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall
	package="git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/recall"

[Error - 3:02:45 PM] 2022/09/22 15:02:45 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:46 PM] 2022/09/22 15:02:46 tidy: diagnosing file:///data/home/yuanleihao/go/src/git.code.oa.com/csig_edu_data_service/go_edu_search_schedule/go.mod: err: signal: killed: stderr: 

[Error - 3:02:46 PM] Connection to server got closed. Server will not be restarted.

**Comment by a0709** [comment]
Open multiple windows, the code prompt causes an exception

**Comment by hyangah** [comment]
The language server (gopls) heavily depends on the `go` command. The log looks like the `go` command the gopls ran were "killed" so the gopls couldn't do its job. (And, maybe it's also killed???).

I don't know why it was killed. A couple of things to try:

* From terminal, try 
 - `/usr/local/go/bin/go mod tidy` --> was it successful?
 - `gopls -vv check <any go file>` --> was it successful? If not, what's the error like?
 
 * Any security restriction in the system?
 * If you are using dev container, etc does it have enough memory/cpu resources? (we saw cases where gopls and go were OOM-killed otherwise)

**Comment by a0709** [comment]
/usr/local/go/bin/go mod tidy----->success
gopls -vv check----->no error
If you are using dev container, etc does it have enough memory/cpu resources? (we saw cases where gopls and go were OOM-killed otherwise)----->I didn't find any problems

**Comment by findleyr** [comment]
Hi, closing this as I don't think there's enough info for us to investigate further.

Gopls' architecture has changed significantly, to require less memory. I wonder if this is still a problem.
