### ISSUE TITLE
Remote WSL crushes silently when saving the *.go file

### ISSUE THREAD

**Issue by pddg** [golang/vscode-go#2476]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.19.1 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- ```
	  Build info
          ----------
          golang.org/x/tools/gopls v0.9.5
            golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
            github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
            github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
            github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
            golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
            golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
            golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
            golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
            golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=
            golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
            golang.org/x/tools@v0.1.13-0.20220908144252-ce397412b6a4 h1:glzimF7qHZuKVEiMbE7UqBu44MyTjt5u6j3Jz+rfMRM=
            golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058 h1:YnB27EXBD8XxB0JcaOeluuvhF2kS4DrH0k+lpopG2xc=
            honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
            mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
            mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
          go: go1.19.1
          ```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.71.2 74b1f979648cc44d385a2286793c226e611f59e7 x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.35.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- ```
          Checking configured tools....
          GOBIN: undefined
          toolsGopath: 
          gopath: /home/pudding/go
          GOROOT: /home/pudding/.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.19.1.linux-amd64.tar.gz/go
          PATH: /home/pudding/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/bin/remote-cli:/home/pudding/.cargo/bin:/home/pudding/.deno/bin:/home/pudding/.local/share/aquaproj-aqua/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/GnuPG/bin:/mnt/c/Users/pudding/.cargo/bin:/mnt/c/Users/pudding/scoop/apps/vscode/current/bin:/mnt/c/Users/pudding/go/bin:/mnt/c/Users/pudding/scoop/shims:/mnt/c/Users/pudding/AppData/Local/Microsoft/WindowsApps:/home/pudding/go/bin

          	go:	/home/pudding/.local/share/aquaproj-aqua/bin/go: go version go1.19.1 linux/amd64

          	gotests:	/home/pudding/go/bin/gotests	(version: v1.6.0 built with go: go1.19.1)
          	gomodifytags:	/home/pudding/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19.1)
          	impl:	/home/pudding/go/bin/impl	(version: v1.1.0 built with go: go1.19.1)
          	goplay:	/home/pudding/go/bin/goplay	(version: v1.0.0 built with go: go1.19.1)
          	dlv:	/home/pudding/go/bin/dlv	(version: v1.9.1 built with go: go1.19.1)
          	staticcheck:	/home/pudding/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.1)
          	gopls:	/home/pudding/go/bin/gopls	(version: v0.9.5 built with go: go1.19.1)

          go env
          Workspace Folder (test): /home/pudding/ghq/github.com/pddg/test
          	GO111MODULE=""
          	GOARCH="amd64"
          	GOBIN=""
          	GOCACHE="/home/pudding/.cache/go-build"
          	GOENV="/home/pudding/.config/go/env"
          	GOEXE=""
          	GOEXPERIMENT=""
          	GOFLAGS=""
          	GOHOSTARCH="amd64"
          	GOHOSTOS="linux"
          	GOINSECURE=""
          	GOMODCACHE="/home/pudding/go/pkg/mod"
          	GONOPROXY=""
          	GONOSUMDB=""
          	GOOS="linux"
          	GOPATH="/home/pudding/go"
          	GOPRIVATE=""
          	GOPROXY="https://proxy.golang.org,direct"
          	GOROOT="/home/pudding/.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.19.1.linux-amd64.tar.gz/go"
          	GOSUMDB="sum.golang.org"
          	GOTMPDIR=""
          	GOTOOLDIR="/home/pudding/.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.19.1.linux-amd64.tar.gz/go/pkg/tool/linux_amd64"
          	GOVCS=""
          	GOVERSION="go1.19.1"
          	GCCGO="gccgo"
          	GOAMD64="v1"
          	AR="ar"
          	CC="gcc"
          	CXX="g++"
          	CGO_ENABLED="1"
          	GOMOD="/home/pudding/ghq/github.com/pddg/test/go.mod"
          	GOWORK=""
          	CGO_CFLAGS="-g -O2"
          	CGO_CPPFLAGS=""
          	CGO_CXXFLAGS="-g -O2"
          	CGO_FFLAGS="-g -O2"
          	CGO_LDFLAGS="-g -O2"
          	PKG_CONFIG="pkg-config"
          	GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3512433615=/tmp/go-build -gno-record-gcc-switches"
          ```

Other versions:

- Windows11 22H2 22621.521
- Ubuntu 22.04 (WSL)

</details>

### Share the Go related settings you have added/edited

Following Go related options are configured, and otherwise are default.

```json
{
    "go.useLanguageServer": true,
    "go.autocompleteUnimportedPackages": true,
    "go.toolsManagement.autoUpdate": true
}
```

### Describe the bug

Edit Go sources and save it, then the vscode-server daemon on the WSL crushes silently.
VSCode requires me to reload the window, or says `failed to connect`.

It is not happend when I disable vscode-go.

### Steps to reproduce the behavior:

1. Connect to WSL using Remote WSL
1. Enable vscode-go on WSL
2. Edit Go source on WSL

### Screenshots or recordings

![vscode-crushes](https://user-images.githubusercontent.com/14105201/191881199-de6d922a-9474-4b0e-b15d-24a001d12580.gif)

The displayed log shows that the VSCode server for WSL is closed unexpectedly.

```
[2022-09-23 02:19:27.110] [11:18:18] [127.0.0.1][7670689c][ExtensionHostConnection] New connection established.
[2022-09-23 02:19:27.110] [11:18:19] [127.0.0.1][7670689c][ExtensionHostConnection] <32405> Launched Extension Host Process.
[2022-09-23 02:19:27.112] VS Code Server for WSL closed unexpectedly.
[2022-09-23 02:19:27.113] C:\WINDOWS\System32\wsl.exe -d Ubuntu-22.04 -e kill 32278
[2022-09-23 02:19:27.262] Exec (2) stderr: Error: connect ECONNREFUSED 127.0.0.1:35255
[2022-09-23 02:19:27.262]     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)Remote close with error
[2022-09-23 02:19:27.262] Exec (2): Local close
[2022-09-23 02:19:27.262] Terminating exec 2
[2022-09-23 02:19:27.262] Exec (0): Local close
[2022-09-23 02:19:27.262] Terminating exec 0
[2022-09-23 02:19:27.262] Exec (0) has terminated (local socket closed) with code 0 and signal null.
[2022-09-23 02:19:27.263] Exec (2) has terminated (local socket closed) with code 1 and signal null.
[2022-09-23 02:19:27.267] Resolving wsl+ubuntu-22.04, resolveAttempt: 2
```

Then, it try to start the VSCode server again.

```
[2022-09-23 02:19:27.337] Starting VS Code Server inside WSL (wsl2)
[2022-09-23 02:19:27.337] Extension version: 0.66.3
[2022-09-23 02:19:27.337] Windows build: 22621. Multi distro support: available. WSL path support: enabled
[2022-09-23 02:19:27.337] No shell environment set or found for current distro.
[2022-09-23 02:19:27.453] WSL daemon log file: c:\Users\pudding\scoop\apps\vscode\1.71.2\data\user-data\logs\20220923T111811\exthost1\ms-vscode-remote.remote-wsl\wsl-daemon-20220923T021927.log
```

However, it is never reconnected, as shown in the Gif image.

The VSCode Server for WSL that appeared to crash actually logs that the client side disconnected gracefully.

```
❯ tail -n 5 ~/.vscode-server/data/logs/20220923T111704/remoteagent.log
[2022-09-23 11:17:04.843] [remoteagent] [trace] Started scanning user extensions
[2022-09-23 11:17:05.201] [remoteagent] [info] [127.0.0.1][e2069223][ExtensionHostConnection] New connection established.
[2022-09-23 11:17:05.207] [remoteagent] [info] [127.0.0.1][e2069223][ExtensionHostConnection] <31364> Launched Extension Host Process.
[2022-09-23 11:17:12.093] [remoteagent] [info] [127.0.0.1][ae01157f][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-09-23 11:17:12.117] [remoteagent] [info] [127.0.0.1][e2069223][ExtensionHostConnection] <31364> Extension Host Process exited with code: 0, signal: null.
```

gopls server is shutdowned normaly, too.

```
❯ tail -n 10 ~/.vscode-server/data/logs/20220923T111704/exthost1/output_logging_20220923T111705/3-gopls\ \(server\).log
        packages=2

[Info  - 11:17:06] 2022/09/23 11:17:06 go/packages.Load #1: updating metadata for 40 packages

[Info  - 11:17:07] 2022/09/23 11:17:07 falling back to safe trimming due to type errors: [/home/pudding/.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.19.1.linux-amd64.tar.gz/go/src/runtime/vdso_linux.go:53:38: invalid operation: division by zero /home/pudding/.local/share/aquaproj-aqua/pkgs/http/golang.org/dl/go1.19.1.linux-amd64.tar.gz/go/src/runtime/vdso_linux.go:54:38: invalid operation: division by zero] or still-missing identifiers: map[]
        package="runtime"

[Info  - 11:17:12] 2022/09/23 11:17:12 Shutdown session
        shutdown_session=1
```

This phenomenon does not occur if vscode-go is disabled.

![vscode-no-crush](https://user-images.githubusercontent.com/14105201/191882286-f504489e-a3e7-457d-bf65-7de152c56e86.gif)

This phenomenon occurred suddenly yesterday. It was working fine until then. Completion is still working fine in this condition, so gopls itself seems to be working fine.

**Comment by pddg** [comment]
After verifying various combinations, this seemed to be due to Go being managed by [aqua](https://aquaproj.github.io/docs/overview), not vscode-go or the Ubuntu version.

- Ubuntu 20.04 + /usr/local/go only → No problem
- Ubuntu 20.04 + aqua → Reproduced
- Ubuntu 22.04 + /usr/local/go only → No problem
- Ubuntu 22.04 + aqua → Reproduced

**Comment by pddg** [comment]
aqua makes `go` a symbolic link to a binary called `aqua-proxy` and executes it through it to execute commands with the go command.
Does vscode-go require that the `go` command point to the actual `go` binary?

**Comment by hyangah** [comment]
What is the version of aqua? Aqua had an issue a while ago that confused VSCode, Gopls, Go in their process management. https://github.com/golang/vscode-go/issues/2229

**Comment by pddg** [comment]
@hyangah 
Thank you for replying. The version of aqua is as follows. This is the latest version at this time and appears to have released the fixes for the problems mentioned. Different problems may have occurred.

```bash
❯ aqua version
aqua version 1.19.2 (b6d0cfcbafb9f8371fc6dfb16a225fecd4646444)
```

I missed that issue, sorry. I am going to consider to close this issue and post new issue to aqua, how about it?

**Comment by pddg** [comment]
Setting `export AQUA_EXPERIMENTAL_X_SYS_EXEC=true` seemed to solve this problem. I'll see how it goes for a while.

**Comment by hyangah** [comment]
Thanks for the followup @pddg. 

For workaround until aqua releases its fix official, follow @pddg' https://github.com/golang/vscode-go/issues/2476#issuecomment-1256817970
