### ISSUE TITLE
Import is changed to different library on save

### ISSUE THREAD

**Issue by Inrixia** [golang/vscode-go#2488]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.1 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.9.5
    golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
    github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.13-0.20220908144252-ce397412b6a4 h1:glzimF7qHZuKVEiMbE7UqBu44MyTjt5u6j3Jz+rfMRM=
    golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058 h1:YnB27EXBD8XxB0JcaOeluuvhF2kS4DrH0k+lpopG2xc=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19.1
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.71.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.35.2
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/inrix/.cache/go-build"
	GOENV="/home/inrix/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/inrix/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/inrix/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.19.1"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/inrix/test/FloatplaneFS/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1566723696=/tmp/go-build -gno-record-gcc-switches"
```
</details>

### Share the Go related settings you have added/edited

```json
{
"go.formatOnSave": true,
}
```

### Describe the bug
When attempting to import `"github.com/juju/persistent-cookiejar"` when saving the file the import is changed to `"net/http/cookiejar"`.

### Steps to reproduce the behavior:
1. Create go file
2. Import "github.com/juju/persistent-cookiejar"
3. Save the file

**Comment by suzmue** [comment]
@Inrixia Could you provide an example to reproduce the behavior you are seeing?

**Comment by Inrixia** [comment]
Creating a file with the above import should be sufficient. If that doesn't work I can grab the actual file

**Comment by suzmue** [comment]
Ok here is my repro:

main.go:
```
package main

import "github.com/juju/persistent-cookiejar"
	
func main()      {
  var x cookiejar.Jar
	_ = x
}
```
go.mod:
```
module example

go 1.19
```

`main.go` has two diagnostics, one because there is no dependency on the module in the go.mod. 
![Screen Shot 2022-10-03 at 4 20 51 PM](https://user-images.githubusercontent.com/6634754/193677174-2c7c59c5-dff3-4ef0-9570-aaabefdcaa6d.png)

If you select the `go get github.com/juju/persistent-cookiejar` the go get succeeds and the go.mod is updated:
go.mod:
```
module format

go 1.19

require (
	github.com/juju/persistent-cookiejar v1.0.0
)

require (
	github.com/juju/go4 v0.0.0-20160222163258-40d72ab9641a // indirect
	golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd // indirect
	gopkg.in/errgo.v1 v1.0.1 // indirect
	gopkg.in/retry.v1 v1.0.3 // indirect
)
```

The diagnostics go away in main.go, but now there are diagnostics in go.mod:
![Screen Shot 2022-10-03 at 4 24 03 PM](https://user-images.githubusercontent.com/6634754/193677138-8f71c034-c332-42ed-b344-f35ba13c7200.png)

If you hit save at any point during this, the import will be replaced with `"net/http/cookiejar"`.

Interestingly, this does not happen when using a different cookiejar (github.com/versent/saml2aws/v2/pkg/cookiejar). Looking at the source for github.com/juju/persistent-cookiejar, it appears there is no go.mod file, so maybe that can explain this difference in behavior.

If you force the editor to save without running "source.organizeImports", then all of the diagnostics go away.

**Comment by Inrixia** [comment]
Yes I am currently disabling organizeImports on save to get around this.

Sounds import organization might be using mod for validation, though it's still curious it actually replaced the import.

**Comment by suzmue** [comment]
@Inrixia To follow up, the imports organization tool does not recognize the import path "github.com/juju/persistent-cookiejar" to be a package with the name "cookiejar". We recommend that if the package name does not match the path name, that you add the package name to the import statement:

```
import cookiejar "github.com/juju/persistent-cookiejar"
```

See golang/go#43212 for some additional context.
