### ISSUE TITLE
gocode-gomod eats all my memory and freezes editor

### ISSUE THREAD

**Issue by itzmanish** [golang/vscode-go#249]
`go version`
- go version go1.14.4 linux/amd64

`code -v`
- 1.46.1
- cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
- x64

`VS Code Go extension version`
- 0.14.4

`go env`
```GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/manish/.cache/go-build"
GOENV="/home/manish/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manish/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build283301174=/tmp/go-build -gno-record-gcc-switches"
```

After working for several time after saving my go code (format on save is on) vscode freezes (everything editor, sidebar, terminal). I checked what cause freeze in system monitor and found gocode-gomod eating up my almost all available memory however that doesn't cause my window lag or any other runing app freeze. After some second vscode asks me to reload.

OS- Ubuntu 20.04

**Comment by stamblerre** [comment]
I'm sorry you're having this experience. `gocode-gomod` is in maintenance mode, so active development has been paused. I would recommend switching to the language server, [`gopls`](https://github.com/golang/vscode-go/blob/master/docs/gopls.md) for a better experience. You can enable it by setting `"go.useLanguageServer": true` in your editor.

**Comment by stamblerre** [comment]
Please follow the steps mentioned in https://github.com/golang/go/issues/36943#issue-558320672 to report a memory issue with `gopls`. I'll go ahead and close this issue.
