### ISSUE TITLE
Add ability to customize code-generating templates in plugin Settings

### ISSUE THREAD

**Issue by gmlewis** [golang/vscode-go#2510]
**Is your feature request related to a problem? Please describe.**
I use the `Go: Generate Unit Tests for Function` and `Go: Generate Unit Tests for File` on a regular basis, and they save me a great deal of time writing boilerplate table-driven tests. However, the next step for me is to always modify the generated code to be more to my liking.

**Describe the solution you'd like**
I would like to be able to customize the built-in templates for code generation in the Settings for the plugin.
Thank you!

**Describe alternatives you've considered**
Continue to manually edit the generated code, possibly writing some plugins that would automate the modification, or forking the plugin and changing the templates.

**Additional context**
n/a

**Comment by hyangah** [comment]
That function relies on https://github.com/cweill/gotests
which provides template-based generation options. 
Can you please test if `GOTESTS_TEMPLATE_DIR` and `GOTESTS_TEMPLATE`  (maybe setting them through `go.toolsEnvVars` settings) meet your need, and see if the plugin needs something extra to fully utilize the power of `gotests`?

**Comment by gmlewis** [comment]
Investigating...
:eyes: https://github.com/cweill/gotests/pull/61

**Comment by gmlewis** [comment]
It looks like the first important step is to match the version of the templates pointed to with the version of "gotests" that VSCode is using.

To replicate this error, first clone the repo:

```bash
$ cd ~/src/github.com
$ mkdir cweill && cd cweill
$ git clone git@github.com:cweill/gotests && cd gotests/internal/render/templates/
$ pwd
/home/glenn/src/github.com/cweill/gotests/internal/render/templates
```

Next, add the following env var to your VSCode `settings.json`:

```json
{
  "go.toolsEnvVars": {
    "GOTESTS_TEMPLATE_DIR": "/home/glenn/src/github.com/cweill/gotests/internal/render/templates"
  }
}
```

Now, in VSCode, visit a `.go` file and click on a function.
Execute (Ctrl-Shift-P) "Go: Generate Unit Tests for Function".
This error pops up in VSCode:

![ksnip_20221027-155904](https://user-images.githubusercontent.com/6598971/198386546-f1530b5a-31aa-4f7e-b9be-06617069bf8c.png)

Next, I'm going to see if I can find a version of the templates that work with the version of `gotests` that VSCode is using.

**Comment by gmlewis** [comment]
Success!  If I use the templates from `gotests` `v1.4.0`, then everything works!

```bash
$ pwd
/home/glenn/src/github.com/cweill/gotests/internal/render/templates
$ git checkout v1.4.0
Note: switching to 'v1.4.0'.
...
```

After this step, everything works beautifully!

Thank you very much, @hyangah !

Closing as working.

:tada:
