### ISSUE TITLE
[feature request] Add setting to disable opening imports in the browser

### ISSUE THREAD

**Issue by niedzielski** [golang/vscode-go#2514]
**Is your feature request related to a problem? Please describe.**
When I control-click on an import, sometimes it navigates to the file and other times it both navigates to the file and opens my browser. This is super disorienting as I only want to view the source locally within my IDE if it's available.

**Describe the solution you'd like**
Add a setting to disable automatic navigation.

**Describe alternatives you've considered**
I pretty much try to avoid control-clicking on imports now which really hurts the usability of vscode-go.

**Additional context**
I think [there used to be a setting called `documentLink` described here](https://github.com/microsoft/vscode-go/issues/2550) but it no longer seems to be recognized.

Thank you!

**Comment by hyangah** [comment]
```
"gopls": {
        "ui.navigation.importShortcut": "Definition"
 }
```

https://github.com/golang/vscode-go/wiki/settings#uinavigationimportshortcut

**Comment by niedzielski** [comment]
@hyangah, thank you soooo much!!
