### ISSUE TITLE
Parameter hints don't show up on autocompletion suggestion of methods.

### ISSUE THREAD

**Issue by flowchartsman** [golang/vscode-go#2515]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
```
go version go1.19.2 darwin/amd64
```

* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
Build info
----------
golang.org/x/tools/gopls v0.9.5
    golang.org/x/tools/gopls@v0.9.5 h1:F3TO5th6TUg40FHrpxZfMkMlVaaTmByeEvylgVHGH2A=
    github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
    golang.org/x/mod@v0.6.0-dev.0.20220419223038-86c51ed26bb4 h1:6zppjxzCulZykYSLyVDYbneBfbaBIQPYMevg0bEwv2s=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.0.0-20220722155257-8c9f86f7a55f h1:v4INt8xihDGvnrfjMDVXGxw9wrfxYyCjk0KbXjhR55s=
    golang.org/x/text@v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
    golang.org/x/tools@v0.1.13-0.20220908144252-ce397412b6a4 h1:glzimF7qHZuKVEiMbE7UqBu44MyTjt5u6j3Jz+rfMRM=
    golang.org/x/vuln@v0.0.0-20220901221904-62b0186a1058 h1:YnB27EXBD8XxB0JcaOeluuvhF2kS4DrH0k+lpopG2xc=
    honnef.co/go/tools@v0.3.2 h1:ytYb4rOqyp1TSa2EPvNVwtPQJctSELKaMyLfqNP4+34=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19.2
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.72.2
d045a5eda657f4d7b676dedbfa7aab8207f8a075
x64
```
* Check your installed extensions to get the version of the VS Code Go extension
```
v0.35.2
```
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/myuser/go
GOROOT: /Users/myuser/opt/go
PATH: /Users/myuser/opt/go/bin:/Users/myuser/go/bin:/Users/myuser/bin:/Users/myuser/.fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

	go:	/Users/myuser/opt/go/bin/go: go version go1.19.2 darwin/amd64

	gotests:	/Users/myuser/go/bin/gotests	(version: v1.6.0 built with go: go1.19.2)
	gomodifytags:	/Users/myuser/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19.2)
	impl:	/Users/myuser/go/bin/impl	(version: v1.1.0 built with go: go1.19.2)
	goplay:	/Users/myuser/go/bin/goplay	(version: v1.0.0 built with go: go1.19.2)
	dlv:	/Users/myuser/go/bin/dlv	(version: v1.9.1 built with go: go1.19.2)
	staticcheck:	/Users/myuser/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.2)
	gopls:	/Users/myuser/go/bin/gopls	(version: v0.9.5 built with go: go1.19.2)

go env
Workspace Folder (integration): /Users/myuser/iauto/go/integration
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/myuser/Library/Caches/go-build"
	GOENV="/Users/myuser/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/myuser/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/myuser/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/Users/myuser/opt/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/Users/myuser/opt/go/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.19.2"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/myuser/go/myproject/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/p5/flm2f5z164q98_flfgb_39r40000gn/T/go-build179849523=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</details>

### Share the Go related settings you have added/edited
```json
 "[go]": {
    "editor.parameterHints.enabled": true,
  },
  "go.lintOnSave": "workspace",
  "go.autocompleteUnimportedPackages": true,
  "go.coverageOptions": "showUncoveredCodeOnly",
  "gopls": {
    "build.experimentalWorkspaceModule": true,
    "formatting.gofumpt": true,
    "codelenses": {
      "gc_details": true,
    },
    "usePlaceholders": false,
  },
  "go.enableCodeLens": {
    "references": false,
    "runtest": true,
  },
  "go.toolsManagement.autoUpdate": true,
```

### Describe the bug
For some reason, using autocompletion for ~functions or~ methods does not trigger the hovering parameter hints.  If I select ~a function or~ method name from the autocompletion menu, I get the full method ~or function~ name with parenthesis, but I am forced to backspace over both of them and type the opening parenthesis again to get the hover.

I've researched this as much as I can online, and results are inconclusive as to whether this is supposed to work or has ever worked, though it seems to work with other languages from what I've seen so far.

### Steps to reproduce the behavior:

1. Begin typing ~function or~ method signature to trigger autocompletion.
2. Select a ~function or~ method signature

### Screenshots or recordings
Attached is a brief recording.  If I select the option from the autocompletion menu, I get `proj.ApplyProfiles()` with my cursor between the parenthesis.  If I remove them and retype the first paren, I get both parenthesis _and_ the parameter hints I desire.  If I type the entire method call manually, I get the parenthesis and the parameter hints I desire. It's only if selecting a completion option that nothing happens.

![funcparams](https://user-images.githubusercontent.com/926884/198902563-f1637fd5-c53b-48ca-8dbb-63de85f5a75b.gif)

**EDIT: This behavior is only for methods, functions appear to work normally.**

**Comment by sheikalthaf** [comment]
@flowchartsman  I'm also facing the same issue after updating my mac to v13

**Comment by findleyr** [comment]
@hyangah I can reproduce this, and it appears to be a client-side issue: for function completion, following a completion selection I see a signatureHelp request. But for method completion (as in the screencast above), there is no signatureHelp request.

Any idea why this would be the case?

**Comment by findleyr** [comment]
@flowchartsman you said this is the case for methods *or* functions, but in my case I see this only for methods. Can you please confirm that you also see this misbehavior for functions?

**Comment by flowchartsman** [comment]
> @flowchartsman you said this is the case for methods _or_ functions, but in my case I see this only for methods. Can you please confirm that you also see this misbehavior for functions?

Cannot confirm, your observation is correct, it does _not_ happen with functions. It only appears to be methods.

**Comment by flowchartsman** [comment]
Appears to be fixed in nightly, presumably thanks to @hyangah && https://go.dev/cl/446816

**Comment by hyangah** [comment]
Thanks for verifying it. I was about to ask you to test. :-). 
Closing.
Hopefully v0.36.0 is out soon.
