### ISSUE TITLE
embedded terminal insists on setting wrong go in PATH

### ISSUE THREAD

**Issue by PaulForgey-Discovery** [golang/vscode-go#2517]
Type: <b>Bug</b>

have multiple versions of go present on the system
have a clear configuration in .zprofile establishing the preferred one
invoke a terminal window - notice `export PATH=/usr/local/go/bin; export PATH` is invoked

setting `go.gopath` has no effect.

Extension version: 0.35.2
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:55.763Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|14, 19, 19|
|Memory (System)|32.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 60c2e045-bbb6-47f1-9cf1-5dd64311d1b6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by findleyr** [comment]
CC @hyangah as I'm not familiar with how terminal env is resolved.

@PaulForgey-Discovery can you share your `settings.json`? Have you determined whether your .zprofile is being executed?

**Comment by hyangah** [comment]
Try

```
"go.terminal.activateEnvironment": false
```

https://github.com/golang/vscode-go/wiki/settings#goterminalactivateenvironment

The default behavior is to ensure users use the same `go` used by the go extension.
The go extension uses the `go` binary found from the `PATH` inherited from the VS Code process. Terminal is a separate process which later launches and maybe initializes based on the login shell. In other words, there is currently no guarantee that the PATH users see from their integrated terminal and the PATH the extension will see. :-(

**Comment by PaulForgey-Discovery** [comment]
So I finally tracked this to user error; the wrong (used for bootstrapping) version of go existed in /etc/paths.d, and I had mis-typed the go.gopath value.

Once I had that right and restarted, things started working consistently - embedded shell seeing the same version of go as my other non-IDE shells and the IDE itself. phew.

> The default behavior is to ensure users use the same go used by the go extension.
The go extension uses the go binary found from the PATH inherited from the VS Code process. Terminal is a separate process which later launches and maybe initializes based on the login shell.

naturally, and a frequent source of confusion I am sure.

**Comment by PaulForgey-Discovery** [comment]
reopening as it's happening again with no explanation and it seems to be arbitrary from one day to the next.

To answer questions:
@hyangah embedded shell is using the same go the IDE is. Right now, it's using /usr/local/go/bin/go but there's nothing in any of my paths pointing to that; it's something brew installed as a dependency against my wishes. But there's no profile setting a path there and no /etc/paths.d entry for it. 

@findleyr : .zprofile _is_ being executed, settings.json is
```
{
    "go.useLanguageServer": true,
    "go.buildTags": "functional",
    "go.disableConcurrentTests": true,
    "go.testFlags": [
        "-timeout","30m",
        "-v"
    ],
    "go.toolsManagement.autoUpdate": true,
    "go.gopath": "/Users/pforgey/go"
}
```

**Comment by PaulForgey-Discovery** [comment]
ah trying `go.goroot`..

**Comment by PaulForgey-Discovery** [comment]
ok closing. sorry -- that did set it. However, my shell's environment is only ever touching `~/goroot` for GOROOT and its related PATH
