### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by osangenis** [golang/vscode-go#2520]
gopls version: v0.10.0 (go1.18.3)
gopls flags: 
update flags: proxy
extension version: 0.35.2
go version: 1.18.3
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 01 Nov 2022 09:34:03 GMT
restart history:
Tue, 01 Nov 2022 08:31:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1008bd810]

goroutine 11485 [running]:
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/gopls/internal/lsp/source/completion.isStarTestingDotF(...)
	  completion.go:1283
golang.org/x/tools/gopls/internal/lsp/source/completion.(*completer).methodsAndFields(0x1400caf8a00, {0x100d76680%3F, 0x1400509d720%3F}, 0x1, 0x0, 0x1400ee08ed0)
	  completion.go:1246  0x1f0
golang.org/x/tools/gopls/internal/lsp/source/completion.(*completer).deepSearch(0x1400caf8a00, {0x100d7a398%3F, 0x1400acfe840%3F})
	  deep_completion.go:229  0x898
golang.org/x/tools/gopls/internal/lsp/source/completion.Completion({0x100d7a328%3F, 0x14004bbae40%3F}, {0x100d82a60%3F, 0x1400f05c000}, {0x100d7a638%3F, 0x1400cba1500}, {0x734a270%3F, 0x140%3F}, {0x33dff0%3F, {0x0%3F, ...}})
	  completion.go:571  0xd74
golang.org/x/tools/gopls/internal/lsp.(*Server).completion(0x1400f029040%3F, {0x100d7a328, 0x14004bbae40}, 0x1400f029040)
	  completion.go:32  0x138
golang.org/x/tools/gopls/internal/lsp.(*Server).Completion(0x140022e9b00%3F, {0x100d7a328%3F, 0x14004bbae40%3F}, 0x100c0f720%3F)
	  server_gen.go:28  0x28
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x100d7a328, 0x14004bbae40}, {0x100d85e60, 0x1400031a200}, 0x14007595f20, {0x100d7a718, 0x14004bbadc0})
	  tsserver.go:269  0x187c
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x100d7a328, 0x14004bbae40}, 0x14007595f20, {0x100d7a718, 0x14004bbadc0})
	  protocol.go:157  0x70
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x100d7a328, 0x14004bbae40}, 0x14007595f20, {0x100d7a718%3F, 0x14004bbadc0%3F})
	  lsprpc.go:515  0x788
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x100d7a328, 0x14004bbae40}, 0x14006748588, {0x100d7a718%3F, 0x14004bbadc0%3F})
	  handler.go:35  0xf4
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1dc
[Error - 10:33:51 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by osangenis** [comment]
```
[Info  - 10:33:29 AM] 2022/11/01 10:33:29 background imports cache refresh starting

[Info  - 10:33:29 AM] 2022/11/01 10:33:29 background refresh finished after 16.283416ms

[Error - 10:33:51 AM] 2022/11/01 10:33:51 no signature help: cannot get type for Fun *ast.SelectorExpr (&{ctrl LogRefund})
	position=43:38
...
```

**Comment by findleyr** [comment]
Thank you for the report! This is https://go.dev/issue/56505, an unfortunate crasher introduced in v0.10.0. We will certainly cherry-pick and release a fix, likely today.
