### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by p9595jh** [golang/vscode-go#2521]
gopls version: v0.10.0 (go1.19.2)
gopls flags: 
update flags: proxy
extension version: 0.35.2
go version: 1.19.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 01 Nov 2022 10:29:35 GMT
restart history:
Tue, 01 Nov 2022 10:25:32 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1008639db]

goroutine 16629 [running]:
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/gopls/internal/lsp/source/completion.isStarTestingDotF({0x100d34dd8%3F, 0xc007057030%3F})
	  completion.go:1283  0x7b
golang.org/x/tools/gopls/internal/lsp/source/completion.(*completer).methodsAndFields(0xc00017ea00, {0x100d34dd8%3F, 0xc007057030}, 0x1, 0x0, 0xc012e40f00)
	  completion.go:1246  0x211
golang.org/x/tools/gopls/internal/lsp/source/completion.(*completer).deepSearch(0xc00017ea00, {0x100d38e28%3F, 0xc012548000%3F})
	  deep_completion.go:229  0xabd
golang.org/x/tools/gopls/internal/lsp/source/completion.Completion({0x100d38db8%3F, 0xc00e7d8240%3F}, {0x100d453e0%3F, 0xc01ad32c80}, {0x100d390c8%3F, 0xc008284380}, {0x1587fe8%3F, 0x1%3F}, {0x1, {0x0, ...}})
	  completion.go:571  0x1288
golang.org/x/tools/gopls/internal/lsp.(*Server).completion(0x10093d040%3F, {0x100d38db8, 0xc00e7d8240}, 0xc0011c6320)
	  completion.go:32  0x1c5
golang.org/x/tools/gopls/internal/lsp.(*Server).Completion(0xc000414fc0%3F, {0x100d38db8%3F, 0xc00e7d8240%3F}, 0x10093d040%3F)
	  server_gen.go:28  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x100d38db8, 0xc00e7d8240}, {0x100d48f00, 0xc0000d2500}, 0xc00c0403f0, {0x100d391a8, 0xc00e7d81c0})
	  tsserver.go:269  0x20c2
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x100d38db8, 0xc00e7d8240}, 0xc00c0403f0, {0x100d391a8, 0xc00e7d81c0})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x100d38db8, 0xc00e7d8240}, 0xc00c0403f0, {0x100d391a8%3F, 0xc00e7d81c0%3F})
	  lsprpc.go:515  0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x100d38db8, 0xc00e7d8240}, 0xc0078757b8, {0x100d391a8%3F, 0xc00e7d81c0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 7:29:06 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thank you for the report! This is https://go.dev/issue/56505, an unfortunate crasher introduced in v0.10.0. We will certainly cherry-pick and release a fix, likely today.
