### ISSUE TITLE
test/integration/install: installation test teardown is unsuccessful due to failed module cache cleanup

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2524]
The installation test works with a file-system based module proxy that serves fake main packages.
The copy of modules downloaded from the proxy in module cache cannot be deleted with normal permission,
so the teardown runs `go clean -modcache`.

https://github.com/golang/vscode-go/blob/master/test/integration/install.test.ts#L57-L75

However, that's still not sufficient and this is surfaced in the github action log.

https://github.com/golang/vscode-go/actions/runs/3370635297

![Screen Shot 2022-11-01 at 1 39 21 PM](https://user-images.githubusercontent.com/4999471/199300850-f3624749-55b1-4b7a-b860-b0bed5a6c9dd.png)

**Comment by findleyr** [comment]
FWIW `go clean -modcache` should be sufficent -- that's what gopls uses for regression tests. Could this be a race? Is it possible the clean failed?
