### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by iceworldvip** [golang/vscode-go#2528]
gopls version: v0.10.1 (go1.18.2)
gopls flags: 
update flags: proxy
extension version: 0.35.2
go version: 1.18.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 03 Nov 2022 02:00:29 GMT
restart history:
Thu, 03 Nov 2022 01:50:55 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by iceworldvip** [comment]
![image](https://user-images.githubusercontent.com/2902219/199991242-66a7252c-4e2b-4c89-a70b-1857b2eb034a.png)
Thank you for your reply. I try to capture a screenshot during the time of the problem. I'm not sure that it's helpful to solve the problem.

**Comment by findleyr** [comment]
Thanks. Is this reproducible for you now?

I suspect that this is a category of crash that is experienced when VS Code auto-updates gopls. As such, it should not reoccur (until gopls is auto-updated again, of course).

**Comment by iceworldvip** [comment]
`[Info  - 11:12:11 PM] 2022/11/05 23:12:11 go/packages.Load #1: updating metadata for 2975 packages

[Error - 11:12:26 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
[Error - 11:12:28 PM] Request textDocument/references failed.
  Message: context canceled
  Code: 0 
[Error - 11:12:30 PM] Request textDocument/codeAction failed.
  Message: context canceled
  Code: 0 
[Info  - 11:12:53 PM] 2022/11/05 23:12:53 background imports cache refresh starting

[Info  - 11:13:06 PM] 2022/11/05 23:13:06 background refresh finished after 14.208510322s`

**Comment by findleyr** [comment]
@iceworldvip sorry, I can't tell from those logs whether this is still a problem for you (though your workspace looks very large).

**Comment by iceworldvip** [comment]
Yes, there's a large business project in my workspace.

**Comment by hyangah** [comment]
@iceworldvip Is this reproducible now? If so, can you tell us how you could reproduce the issue?

Otherwise, we need a log (usually go panic log) before the section before the part included in the screenshot.
