### ISSUE TITLE
set build.expandWorkspaceToModule default to false

### ISSUE THREAD

**Issue by bokunodev** [golang/vscode-go#2532]
**Is your feature request related to a problem? Please describe.**

i tried to set up go workspace based [this tutorial](https://go.dev/doc/tutorial/workspaces)
but i keep getting errors `no go.mod in dir /tmp/workbla.....`
because it tried to look for `go.mod` file in root dir (which of course it wouldn't find it) even though there is `go.work` file in the root dir.
turns out i need to disable this option `build.expandWorkspaceToModule` which default to `true`.
after set it to `false`, i got another error
``` 
packages.Load error: err: exit status 1: stderr: go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
	Remove the -mod flag to use the default readonly value,
	or set GOWORK=off to disable workspace mode.go list
```
which is related to this setting `build.allowModfileModifications`.
i need to make sure that `build.allowModfileModifications` is either `unset` or `false` (which is not documented).

**Describe the solution you'd like**

set default value for `build.expandWorkspaceToModule` and `build.allowModfileModifications` to `false`

**Describe alternatives you've considered**

not relevant

**Additional context**

codes in the screenshot below compile just fine. but vscode keep complaining for some reason.
and solution i mentioned above fix the problem.

![Screenshot_2022-11-12_00-32-08](https://user-images.githubusercontent.com/54968427/201414340-3ff4a90a-a2b0-466b-b3c0-4fb7488e987e.png)

**Comment by findleyr** [comment]
Hi, I believe that this may have only been related to `build.allowModfileModifications`. Could you please try removing your non-default value of `build.expandWorkspaceToModule`?

**Comment by findleyr** [comment]
@bokunodev this is not easily reproducible for me. Could you please share your full settings.json file, as well as go version and gopls version?

@hyangah are there any additional settings enabled by the nightly?

**Comment by findleyr** [comment]
This is bizarre, as the error you report simply does not reproduce for me, with an identical setup. The error you report makes sense if `build.allowModfileModifications` is true (known bug https://go.dev/issue/56570), but once that is set to false the value for expandWorkspaceToModule should not matter.

Thank you for being so responsive. If we can pin this down, it will get fixed expediently.

More questions:
- Do you happen to have any go.mod or go.work files in parent directories of your workspace (this shouldn't matter, and didn't matter for me, but I'm trying to understand how expandWorkspaceToModule could matter. 
- Are any of these directories symlinked?

**Comment by hyangah** [comment]
`expandWorkspaceToModule` is by default `true`. This is not specific to Nightly.
https://github.com/golang/tools/blob/master/gopls/doc/settings.md#expandworkspacetomodule-bool

@findleyr vscode-go nightly sets `allExperiments: true`. 

Thanks for the workspace.zip. I tested with your settings and tested with all four combo of `expandWorkspaceToModule` and `allowModfileModifications`. I see `allowModfileModifications: true` problematic, but I cannot repro the issue with `expandWorkspaceToModule`. Nightly default configuration seems to work too. :-(

**Comment by findleyr** [comment]
I used your workspace.zip exactly, and opened vs code using `code -n .` from the workspace directly. No problems.

I reproduce the bug only with `build.allowModFileModifications` set to true.

Could you possibly capture gopls logs from a session reproducing the problem?
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information
