### ISSUE TITLE
gopls was not able to find modules in your workspace.

### ISSUE THREAD

**Issue by sfpotato** [golang/vscode-go#2534]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <go version go1.19 linux/amd64>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- 
golang.org/x/tools/gopls v0.10.1
    golang.org/x/tools/gopls@v0.10.1 h1:JoHe17pdZ8Vsa24/GUO8iTVTKPh0EOBiWpPop7XJybI=
    github.com/BurntSushi/toml@v1.2.0 h1:Rt8g24XnyGTyglgET/PRUNlrUeu9F5L+7FilkXfZgs0=
    github.com/google/go-cmp@v0.5.8 h1:e6P7q2lk1O+qJJb4BtCQXlK8vWEO8V1ZeuEdJNOqZyg=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20220722155223-a9213eeb770e h1:7Xs2YCOpMlNqSQSmrrnhlzBXIE/bpMecZplbLePTJvE=
    golang.org/x/mod@v0.6.0 h1:b9gGHsz9/HhJ3HF5DHQytPpuwocVTChQJK3AvoLRD5I=
    golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4 h1:uVc8UZUe6tr40fFVnUP5Oj+veunVezqYl9z7DYw9xzw=
    golang.org/x/sys@v0.1.0 h1:kunALQeHf1/185U1i0GOB/fy1IPRDDpuoOOqRReG57U=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.2.1-0.20221101170700-b5bc717366b2 h1:KBm+UwBaO/tdQ35tfGvxH1FUCiXRg4MoTzkznsdeab8=
    golang.org/x/vuln@v0.0.0-20221010193109-563322be2ea9 h1:KaYZQUtEEaV8aVADIHAuYBTjo77aUcCvC7KTGKM3J1I=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.3.1 h1:avhhrOmv0IuvQVK7fvwV91oFSGAk5/6Po8GXTzICeu8=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <1.73.1  x64>
* Check your installed extensions to get the version of the VS Code Go extension
	- <v0.36.0>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/root/.cache/go-build"
	GOENV="/root/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/root/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/root/go"
	GOPRIVATE="">
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
`
"go.formatTool": "gofmt",
"go.lintOnSave": "workspace",
"go.lintTool": "golint",
`
### Describe the bug
My project can pass `go build`, but extension report some error, like 
`gopls was not able to find modules in your workspace.
When outside of GOPATH, gopls needs to know which modules you are working on.`

`could not import packageName (cannot find package "packageName" in any of 
	/usr/local/go/src packageName (from $GOROOT)`
And I use `go.work` to include all directory contain `go.mod` to solve multi modules, these error report still exist.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by suzmue** [comment]
@sfpotato Could you provide some more information about your setup? What directory do you have open and where are the relevant go.mod and go.work files?

**Comment by sfpotato** [comment]
> @sfpotato Could you provide some more information about your setup? What directory do you have open and where are the relevant go.mod and go.work files?

I have  a project located at `/data/project` directory like :
<img width="266" alt="截屏2022-11-17 14 35 03" src="https://user-images.githubusercontent.com/110923769/202373804-97150644-94d1-48a3-a364-32dcc6539cc8.png">
`go.work` is 
```
use (
        .
        ./stub/proto
)
```

**Comment by findleyr** [comment]
@sfpotato which directory did you open as your workspace?

**Comment by findleyr** [comment]
FWIW this does not reproduce for me, using the suggested layout for `/data/project`.

**Comment by sfpotato** [comment]
> FWIW this does not reproduce for me, using the suggested layout for `/data/project`.

Oh. I see, `go.work` must be locate at workspace root. My workspace was open at the father directory.

**Comment by 0xdeafcafe** [comment]
Sorry for bumping an old issue, but am I right in believing that this means that if your project looks like the following, you can't open the root of the project in VSCode (`monorepo`), you have to open the project at `monorepo/go` to get workspace support to work?

```
github.com/company/monorepo
├─ go/
│  ├─ lib/
│  │  ├─ library-a/
│  │  ├─ library-b/
│  │  ├─ library-c/
│  ├─ svc/
│  │  ├─ service-a/
│  │  ├─ service-b/
│  │  ├─ service-c/
│  ├─ go.work
│  ├─ go.work.sum
├─ js/
│  ├─ lib/
│  ├─ svc/
├─ README.md
```

**Comment by findleyr** [comment]
@0xdeafcafe in that case you could move your go.work to the `monorepo` directory, or set `GOWORK` in your environment.

Note that we're trying to fix this. I just published a design to mitigate this configuration problem: golang/go#57979

**Comment by 0xdeafcafe** [comment]
Ah setting the GOWORK is a great idea, that totally skipped my mind. I'll give that a go tomorrow, cheers!

**Comment by CoderJeffrey** [comment]
I believe for some of the people this issue deserve an easier fix.
If you have create a workspace/ and then clone your projects inside the workspace/, you file structure should look like
`workspace/<project name> ` and inside the sub directory of workspace/<project name>/, you should see the go.mod

What does it mean to have `go.mod`? It means you are inside the module.
```
cd workspace/<project name>
code .
```
These two commands open VSCode in the project inside of a module.
Then you should be able to resolve the warning from VSCode.

**Comment by svitan0k** [comment]
Kinda sucks that I need to open my IDE workplace to the directory where the go.work file resides. So when working on multiple project, I need to have multiple windows open instead of just being able to have them all in one. Feels more like an impediment to an efficient workflow.

**Comment by findleyr** [comment]
@svitan0k https://github.com/golang/go/issues/57979 is my main priority for the rest of this year. Please stay tuned.

**Comment by iamshreeram** [comment]
@findleyr , Would this (https://github.com/golang/go/issues/57979) fix if my workspace looks like below?  https://github.com/golang/go/issues/45184#issuecomment-854560369

Any suggestion to fix this temporarily ?
