### ISSUE TITLE
a gray background

### ISSUE THREAD

**Issue by osmoy** [golang/vscode-go#2535]
### What version of Go, VS Code & VS Code Go extension are you using?
<details>
<summary>
vertion: 1.70.2 (user setup)<br>
&nbsp;&nbsp;&nbsp;&nbsp;submit: e4503b30fc78200f846c62cf8091b76ff5547662<br>
&nbsp;&nbsp;&nbsp;&nbsp;date: 2022-08-16T05:35:13.448Z<br>
&nbsp;&nbsp;&nbsp;&nbsp;Electron: 18.3.5<br>
</summary>
</details>

### Share the Go related settings you have added/edited

It may be caused by auto-upgrading (I guess)   I try to reinstalled vs code but don;t work

### Describe the bug

①the vs IDE display a gray background on start page / extention detail / .ipynb files

②and now my .ipynb files Unable to load or can load but Nothing will be output in outline by run（ctrl + shift）

### Screenshots or recordings
![QQ图片20221117143828](https://user-images.githubusercontent.com/16077168/202374622-b36561d9-743a-4c92-bdf8-9b73b71cfde0.png)

![4](https://user-images.githubusercontent.com/16077168/202375443-c9a839f5-9797-4aa7-b91b-14eae8ef68c6.png)

![2](https://user-images.githubusercontent.com/16077168/202375075-457a5292-21d0-4d9e-8531-34c0ec00d3cb.png)

![3](https://user-images.githubusercontent.com/16077168/202375109-d8ea9641-7894-46cc-a208-6e565d2d5bd2.png)

**Comment by suzmue** [comment]
@osmoy This appears to be unrelated to the Go extension. Consider filing this issue to the [vscode](http://github.com/microsoft/vscode/issues) project.
