### ISSUE TITLE
goLanguageService.ts: gopls update check logic is broken at head

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#254]
Parsing `GOPROXY` format in [`goProxyRequest`](https://github.com/golang/vscode-go/blob/3e1f0adb2d91c8a4843f569415b46d461c4b3476/src/goLanguageServer.ts#L669) is broken
and fails to handle values like`https://proxy.golang.org,direct`

cc @stamblerre

**Comment by stamblerre** [comment]
Oh wow I should've really written the documentation for `split`. I'll mail a fix ASAP.
