### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by dipenls** [golang/vscode-go#2547]
gopls version: v0.10.1 (go1.19.3)
gopls flags: -remote=localhost:8091
update flags: proxy
extension version: 2022.11.2218
go version: 1.19.3
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Fri, 25 Nov 2022 18:05:13 GMT
restart history:
Fri, 25 Nov 2022 18:04:38 GMT: activation (enabled: true)
Fri, 25 Nov 2022 18:04:57 GMT: installation (enabled: true)
Fri, 25 Nov 2022 18:04:57 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report.
Was the server running on localhost:8091 restarted or crashed when this happened?
If the remote server crashed, the crash log should be in the remote server's console.
Otherwise, I am not sure if there is much we need to investigate.

**Comment by dipenls** [comment]
@hyangah This is when I open VS code with Go lang extension installed. I did not start any server. 

<img width="467" alt="image" src="https://user-images.githubusercontent.com/104367258/204546311-c6318cf2-bf50-43d0-b06e-761c9763eea4.png">
<img width="732" alt="image" src="https://user-images.githubusercontent.com/104367258/204546418-906e515a-a9fa-40cd-92ea-6dd7568ae86c.png">

**Comment by hyangah** [comment]
Thanks for the report. If you encounter the same issue, please file a new issue.

Gopls v0.12.0 was released today. Closing obsolete crash reports so we can focus on new crash reports with gopls v0.12.0 promptly.
