### ISSUE TITLE
How to make VSCode-Go happy with nested Go projects (with own go.mod files)

### ISSUE THREAD

**Issue by nikitavoloboev** [golang/vscode-go#2555]
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/6391776/205443344-0882494c-ea69-4710-b573-606246b49488.png">

I have this setup where I open `~/src` in VSCode and inside it want to work on multiple Go projects.

Can I somehow make VSCode-Go happy with this arrangement?

So i.e. I have inside `cli/safari` which is a Go CLI I want to hack on. I am willing to add any config files or anything to make this work.

Thank you.

**Comment by nikitavoloboev** [comment]
Ok running `go work init` at root of `~/src` solves above error.

Just curious, is this the way I should go about solving this issue or there is a better way?

**Comment by nikitavoloboev** [comment]
I ran `go mod init nikitavoloboev/go` at root.

It then lints every `go.mod` it sees inside. I don't know why and how to stop it.

Can I not make above case work?

**Comment by hyangah** [comment]
I think `go.work` is one way to handle this case.

```
$ cd src
$ go work init ./cli/safari
$ code .
```

As you move to other projects, you will need to update the workspace file though.
This is an area that this extension needs to improve.

**Comment by nikitavoloboev** [comment]
That did work. Perfect. ♥️
