### ISSUE TITLE
"Invert `if` Condition" Refactoring

### ISSUE THREAD

**Issue by walles** [golang/vscode-go#2557]
**Is your feature request related to a problem? Please describe.**
I sometimes find code like this:
```go
func something(i int) int {
  if i > 14 {
    // Imagine lots of code here, deeply indented, computing this value...
    result := 99  
    return result 
  } else {
    return 0
  }
}
```

I want to rewrite it like this, which I find easier to follow:
```go
func something(i int) int {
  if i <= 14 {
    return 0
  }

  // Imagine lots of code here, deeply indented, computing this value...
  result := 99
  return result 
}
```

**Describe the solution you'd like**
I want the Go VSCode extension to provide an "Invert `if` Condition" refactoring.

Then I want to run that on the `if` statement in the above code.

Ideally I'd like that to do the whole transformation I outline above, but even if the refactoring kept the `else` clause it would still be helpful to me.

**Describe alternatives you've considered**
I keep doing this by hand...

**Additional context**
When working with Java in IntelliJ I used this refactoring a lot and I miss it in Go / VSCode, so I'm certain I would use this in VSCode as well.

**Comment by findleyr** [comment]
Fixed by https://go.dev/cl/481695.
