### ISSUE TITLE
Cannot run test suite on m1 / ARM64 Mac

### ISSUE THREAD

**Issue by door-bell** [golang/vscode-go#2565]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.3 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.11.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.74.0 5235c6bb189b60b01b1f49062f4ffa42384f8c91 arm64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.36.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
  ```
  Checking configured tools....
  GOBIN: undefined
  toolsGopath: 
  gopath: /Users/tbeck/go
  GOROOT: /opt/homebrew/Cellar/go/1.19.3/libexec
  PATH: /Users/tbeck/Library/Caches/fnm_multishells/96077_1670713335568/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/Users/tbeck/go/bin
  
	  go:	/opt/homebrew/bin/go: go version go1.19.3 darwin/arm64
  
	  gotests:	/Users/tbeck/go/bin/gotests	(version: v1.6.0 built with go: go1.19.3)
	  gomodifytags:	not installed
	  impl:	not installed
	  goplay:	/Users/tbeck/go/bin/goplay	(version: v1.0.0 built with go: go1.19.3)
	  dlv:	/Users/tbeck/go/bin/dlv	(version: v1.20.0 built with go: go1.19.3)
	  staticcheck:	/Users/tbeck/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.3)
	  gopls:	/Users/tbeck/go/bin/gopls	(version: v0.11.0-pre.1 built with go: go1.19.3)
  
  go env
  Workspace Folder (vscode-go): /Users/tbeck/src/vscode-go
	  GO111MODULE=""
	  GOARCH="arm64"
	  GOBIN=""
	  GOCACHE="/Users/tbeck/Library/Caches/go-build"
	  GOENV="/Users/tbeck/Library/Application Support/go/env"
	  GOEXE=""
	  GOEXPERIMENT=""
	  GOFLAGS=""
	  GOHOSTARCH="arm64"
	  GOHOSTOS="darwin"
	  GOINSECURE=""
	  GOMODCACHE="/Users/tbeck/go/pkg/mod"
	  GONOPROXY=""
	  GONOSUMDB=""
	  GOOS="darwin"
	  GOPATH="/Users/tbeck/go"
	  GOPRIVATE=""
	  GOPROXY="https://proxy.golang.org,direct"
	  GOROOT="/opt/homebrew/Cellar/go/1.19.3/libexec"
	  GOSUMDB="sum.golang.org"
	  GOTMPDIR=""
	  GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.3/libexec/pkg/tool/darwin_arm64"
	  GOVCS=""
	  GOVERSION="go1.19.3"
	  GCCGO="gccgo"
	  AR="ar"
	  CC="clang"
	  CXX="clang++"
	  CGO_ENABLED="1"
	  GOMOD="/Users/tbeck/src/vscode-go/go.mod"
	  GOWORK=""
	  CGO_CFLAGS="-g -O2"
	  CGO_CPPFLAGS=""
	  CGO_CXXFLAGS="-g -O2"
	  CGO_FFLAGS="-g -O2"
	  CGO_LDFLAGS="-g -O2"
	  PKG_CONFIG="pkg-config"
	  GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_8/dfpmy4kd00xfkb70b_fcqghw0000gn/T/go-build3080121478=/tmp/go-build -gno-record-gcc-switches -fno-common"
  ```
</details>

### Share the Go related settings you have added/edited

* N/A -- No user settings, all default settings

### Describe the bug
When running `npm run test` on an ARM-based Mac, I get the error `Failed to run gopls testsError: spawn Unknown system error -86`.

Additionally the containerized tests fail with a qemu error:
```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

### Steps to reproduce the behavior:
1. Follow the [development setup instructions](https://github.com/golang/vscode-go/wiki/contributing#developing) on an ARM-based Mac (M1 / Apple Silicon) 
2. Run `npm run test` to start the extension tests.
3. Observe the failure.

### Screenshots or recordings
Output of `npm run test`:
```
➜  vscode-go git:(master) npm run test

> go@0.37.0-dev test
> npm run test-compile && node ./out/test/runTest.js


> go@0.37.0-dev test-compile
> tsc -p ./

Found /Users/tbeck/src/vscode-go/.vscode-test/vscode-darwin-1.74.0. Skipping download.
Failed to run integration testsError: spawn Unknown system error -86
Found /Users/tbeck/src/vscode-go/.vscode-test/vscode-darwin-1.74.0. Skipping download.
Failed to run gopls testsError: spawn Unknown system error -86
```

### Fix
I was able to fix the issue and run the tests successfully by bumping the `@vscode/test-electron` devDependency to version `2.2.0`, it looks like support for the darwin-arm64 version of VSCode was added with [this commit](https://github.com/microsoft/vscode-test/commit/4bcf3d49c75e985da15aa59bf48a98b2c024f5a8#). 

Running the test suite with `build/all.bash testlocal` had zero failures, but there were a couple of failures running `npm run test` directly in the shell. 

As per the contribution guidelines, I wanted to file an issue before creating a CR for the fix.

**Comment by findleyr** [comment]
Thanks for the details, I think we'd welcome a contribution to fix this. CC @hyangah
