### ISSUE TITLE
Not able to check Go code coverage through coverage toggle command

### ISSUE THREAD

**Issue by kalpesh-scalent** [golang/vscode-go#2567]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- gopls v0.10.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.74.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.36.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/kalpeshkuhle/go
GOROOT: /usr/local/go
PATH: /Users/kalpeshkuhle/Library/Android/sdk/platform-tools:/usr/local/opt/go@1.16/bin:/Library/apache-maven-3.8.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Users/kalpeshkuhle/go/bin

	go:	/usr/local/go/bin/go: go version go1.19 darwin/arm64

	gotests:	/Users/kalpeshkuhle/go/bin/gotests	(version: v1.6.0 built with go: go1.19)
	gomodifytags:	/Users/kalpeshkuhle/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19)
	impl:	/Users/kalpeshkuhle/go/bin/impl	(version: v1.1.0 built with go: go1.19)
	goplay:	/Users/kalpeshkuhle/go/bin/goplay	(version: v1.0.0 built with go: go1.19)
	dlv:	/Users/kalpeshkuhle/go/bin/dlv	(version: v1.20.0 built with go: go1.19)
	staticcheck:	/Users/kalpeshkuhle/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19)
	gopls:	/Users/kalpeshkuhle/go/bin/gopls	(version: v0.10.1 built with go: go1.19)

go env
Workspace Folder (testing-course): /Users/kalpeshkuhle/go/src/github.com/kalpesh-scalent/testing-course
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/Users/kalpeshkuhle/Library/Caches/go-build"
	GOENV="/Users/kalpeshkuhle/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/kalpeshkuhle/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/kalpeshkuhle/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.19"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/nx/d48w_0lj4jgfj1xpb254b7th0000gn/T/go-build3712191706=/tmp/go-build -gno-record-gcc-switches -fno-common"
	
</details>

### Share the Go related settings you have added/edited

{
  "go.formatTool": "goimports",
  "go.useLanguageServer": true,
  "go.delveConfig": {},
  "[go]": {
    "editor.defaultFormatter": "golang.go"
  },
}

### Describe the bug
After running the command `Go: Toggle Test Coverage In Current Package`, VS code throws an error.
I have already tried to uninstall and install the extention and VS-Code reload after that. I Also updated all the Go tools, still the issue persists.

### Steps to reproduce the behavior:
1. Type `command + shift + p`
2. Enter the command `Go: Toggle Test Coverage In Current Package`

### Screenshots or recordings

<img width="1066" alt="Screenshot 2022-12-11 at 11 32 12 PM" src="https://user-images.githubusercontent.com/67053624/206920547-3e5fbb7d-d48f-4932-9b71-6e50a9f30043.png">

https://user-images.githubusercontent.com/67053624/206920490-8cb94457-e881-4087-876e-daffeba09961.mov

**Comment by hyangah** [comment]
Can you please share what's in the "Go Tests" output channel and verify the mentioned coverage profile actually does not exist?
