### ISSUE TITLE
testing: debug tests with go1.16/go1.17 are broken

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2572]
With Delve 1.20 release and the recent change made to the extension that doesn't pass version check bypass flag, the tests are broken. 
We need to either change the test set up to pick other delve version depending on go version
or explicitly pass the version check bypass flag during testing.

cc @suzmue @aarzilli

**Comment by aarzilli** [comment]
Passing the bypass flag will eventually start failing. Eventually we will do something that breaks 1.16 and not even notice.
