### ISSUE TITLE
Error installing gopls and other go items

### ISSUE THREAD

**Issue by objsys** [golang/vscode-go#2573]
I am using Visual Studio code on Linux 1.74 on Linux with Go v1.19.4. 

Every time I try to do something with Go, I get a notification that gopls is not installed and there is an Install button. And every time I click this button to try to install it, I get the same error:

gopls: failed to install gopls(golang.org/x/tools/gopls@latest): Error: Command failed: /home/ed/go/bin/go install -v golang.org/x/tools/gopls@latest
go: could not create module cache: stat /home/ed/go/bin/go/pkg/mod: not a directory
 
My GOPATH and GOROOT env var are set to /home/ed/go which is where Go is installed. So /home/ed/go/bin/go is the path to the go executable file and therefore this is a file. I don't know why it trying to append 'pkg/mod' to this to use as the module cache, that is never going to work.  I don't see any settings in Go env that would suggest this is the path to use. Does anyone know where this is coming from?

**Comment by hyangah** [comment]
I recommend stop setting "GOROOT", and setting "GOPATH" and "GOROOT" the same value is almost likely a mistake. 

GOROOT is the directory where Go SDK is installed so most likely they shouldn't be modified once go is installed. Most likely you shouldn't need to set GOROOT if you have your `PATH` set to include the `go` binary location correctly.

GOPATH is on the other hand a working directory for Go, traditionally used to store all the source code and checksum data downloaded from the internet.  $GOPATH/pkg/mod is the default module cache location https://pkg.go.dev/cmd/go#hdr-GOPATH_and_Modules You can set GOMODCACHE to override the default.

**Comment by objsys** [comment]
Thank you for the prompt feedback. I do not see anywhere obvious that I am setting GOROOT such as .bashrc or .profile. Do you know how I can get rid of it?

**Comment by objsys** [comment]
Also, GOMODCACHE is also to "/home/ed/go/pkg/mod" and this doesn't seem to make any difference either :(

**Comment by hyangah** [comment]
`GOMODCACHE` default is `${GOPATH}/pkg/mod`. You can override it by setting environment variables (`"go.toolsEnvVar":  { "GOMODCACHE": <path to directory you want to use as module cache>" }`). However, if you stop using the same directory for Go SDK and GOPATH, and make sure the $HOME/go/pkg/mod is a directory, I guess the default value should be ok.

You shouldn't set `GOROOT` in most cases. Just configure your `PATH`. If your `go` binary is /home/ed/go/bin/go`, in bash, add `export PATH=$PATH:/home/ed/go/bin`.

**Comment by objsys** [comment]
As mentioned, GOMODCACHE is already set to something else. And I didn't do anything to set GOROOT and GOPATH, it somehow came out of the box that way, and I don't see anyway to change them. This is my environment:

go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ed/.cache/go-build"
GOENV="/home/ed/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ed/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ed/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/ed/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/ed/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build654926840=/tmp/go-build -gno-record-gcc-switches"

**Comment by hyangah** [comment]
Install `go` somewhere else other than `/home/ed/go` directory since that's the default `GOPATH`. Or, set `GOPATH` to somewhere else you can give write permission.

**Comment by objsys** [comment]
I installed the package using snap. If I do 'sudo snap remove go' it is
removed. If I then do another install, it ends up in the same place as it
did before. There doesn't seem to be an obvious way to change the location
where something is installed that I could determine.

**Comment by hyangah** [comment]
I don't know why `snap` decided to install `go` under `$HOME/go` which is the default `GOPATH`. When I used snap a while ago, I didn't observe that behavior. 

If the install location of go is not easily configurable, configure `GOPATH` or `GOMODCACHE` to be different locations by configuring your bashrc or vscode `"go.toolsEnvVars": { "GOPATH": "<some_other_path" }`.
