### ISSUE TITLE
Issue of wrongly formatting the go-swagger comments/annotation tag

### ISSUE THREAD

**Issue by aparsapour** [golang/vscode-go#2584]
Type: Bug

Hi,
I am using go-swagger for documenting my backend API, which is build on Golang & also use go-swagger.
The auto formating on save of my Go program text, is the issue. 
The required indentation of annotations/tags is not observed on save. This violates the swagger rules of yaml comments.

As follows you see the proper indentation (**when the GO extension is disabled**) . I have manually indented & is fairly accurate & works fine:

// swagger:operation POST /api/users/login Security Login
// login entrance
// ---
// parameters:
// - name: request
// in: body
// required: true
// type: object
// schema:
// "$ref": "#/definitions/ReqBody"
//
// responses:
// '200':
// description: response to login
// schema:
// type: array
// items:
// "$ref": "#/definitions/UserIdentity"
// default:
// description: unexpected error
// schema:
// "$ref": "#/definitions/UserIdentity"
func Login() {}

But when the GO extension is enabled, the formatter changes the indentation wrongly & this results to error in generation of the spec file (swagger.yaml) .
As follows, you see the mis-formatted text after saving!:

// swagger:operation POST /api/users/login Security Login
// login entrance
// ---
// parameters:
// - name: request
// in: body
// required: true
// type: object
// schema:
// "$ref": "#/definitions/ReqBody"
//
// responses:
//
// '200':
// description: response to login
// schema:
// type: array
// items:
// "$ref": "#/definitions/UserIdentity"
// default:
// description: unexpected error
// schema:
// "$ref": "#/definitions/UserIdentity"
func Login() {}

the problem is on the line following line of the **schema:**tag, which puts the "$ref": at the same level as schema: tag

Thank you for your attention!

Extension version: 0.6.0
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

System Info
A/B Experiments

**Comment by suzmue** [comment]
This is likely related to https://github.com/go-swagger/go-swagger/issues/2759, it appears that go-swagger decided to address this by adapting to the changes in gofmt. What version of go-swagger and go are you using?

It seems like updating the version of go-swagger that you are using to the latest version may help.

Otherwise if that does not work, you can turn off format on save for Go from the VS Code settings.

**Comment by rafi0101** [comment]
Does nobody else have this problem?
I have the same problem!

Here are my system Informations:
go version `go1.19.5 linux/amd64`
go-swagger `v0.30.4`
Golang VS Code Extension: `v0.37.1`

I think I am up to date. But why does it still not work?

**Comment by findleyr** [comment]
@rafi0101 have you tried the fixes listed in https://github.com/go-swagger/go-swagger/issues/2759? There it is suggested to use spaces for indentation, or format yaml as a code block.

I'm afraid we can't diagnose problems with go-swagger. If you think VS Code is not formatting correctly according to the Go 1.19 formatting rules, please open a separate issue.

**Comment by aparsapour** [comment]
I  totally am confident that,  this is the problem of formatting & has
nothing to do with the Go lang version. Even so with the swagger.   This
promlem is from the yaml nature that indentation is . key feature. The code
formatter is the main agent that somehow tries to beautify the code AND
this is the stem of the problem!

with regards

**Comment by findleyr** [comment]
@aparsapour I believe vscode-go should be formatting exactly the same as `go fmt`. If this is breaking yaml embedded in comments, I'm afraid there's nothing we can do: we must follow `go fmt` formatting. Per https://github.com/go-swagger/go-swagger/issues/2759, there appear to be ways to format the yaml such that it doesn't get broken by `go fmt`.

If vscode were not following the style of `go fmt`, that would be a bug that we would fix.

**Comment by rafi0101** [comment]
@findleyr thank you for your feedback. Can you tell me in which comment this is mentioned, or how I have to format the yaml so that it is not broken by the formatter. Cause I cannot find it.

And then maybe we should open the issue at `go fmt` or maybe there is already one there?

**Comment by findleyr** [comment]
@rafi0101 there are some instructions for fixing the yaml here:
https://github.com/go-swagger/go-swagger/issues/2759#issuecomment-1219685223

**Comment by rafi0101** [comment]
Slowly I really do not know how to continue.
What am I doing wrong?
Is this any problem in vscode with one of this settings: Insert Spaces, Detect Indentation or Tab Size?

Original until go 1.18:
![image](https://user-images.githubusercontent.com/43086854/216054786-a9cd3e1d-aaa4-4b1a-a247-a4538f5f8d0c.png)

Changed as in the other issue described:
![image](https://user-images.githubusercontent.com/43086854/216055225-6f37879a-0ec4-42e0-9995-f3cbc5cc09fa.png)

After save/format in go 1.19:
![image](https://user-images.githubusercontent.com/43086854/216055251-45412462-d198-4a51-92d9-aa6d037f94fb.png)

--> And now this `swagger generate spec -o swagger.json --scan-models` is generating a broken configuration
