### ISSUE TITLE
staticcheck: v0.3.3 or older will not work with go1.20 

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2589]
As reported in https://github.com/dominikh/go-tools/issues/1342 https://github.com/dominikh/go-tools/issues/1343.

The version compatible with go1.20 is not yet released.

**Comment by suzmue** [comment]
Closing since Go 1.20 is supported by staticcheck as of [v0.4.0](https://github.com/dominikh/go-tools/releases/tag/2023.1)
