### ISSUE TITLE
BrokenImport incorrectly showing

### ISSUE THREAD

**Issue by TheGeordie** [golang/vscode-go#2607]
Type: <b>Bug</b>

hello,

The Import statements are showing with the RED line under them in VSC, when I perform a run/debug/build all are working ok.

<u><b>parent-child.go file:-</b></u>
package main

// Below: Module name + Path to Package directory ## THIS WORKS EVEN THOUGH SHOWN IN RED
// Refer to go.mod for the Module Name - it does not need to be the same of the folder/directory
import (
"PC/pkg/logging"
"PC/pkg/logging2"
)

func main() {

	logging.Logger("Print message in the Logger of Log Package")
	logging2.Logger("Using another logger Package")

}

![image](https://user-images.githubusercontent.com/39084076/212026153-01fcd673-2c6a-4013-9dab-6dab1de092d5.png)

Extension version: 0.37.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.93GB (4.96GB free)|
|Process Argv|--crash-reporter-id 3cd5318f-fe06-4145-a40c-6b0262f605f4|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TheGeordie** [comment]
Hello - When does this issue get triaged? Many thanks.

**Comment by hyangah** [comment]
@TheGeordie Can you please capture the gopls trace? Instruction is here: 
https://github.com/golang/vscode-go/wiki/troubleshooting#collect-gopls-information

--

I guess you opened the editor in the `Go` folder (vscode workspace folder), and
your `go.mod` is located in `Go/My-Learning/My-Library/Modules/Parent-Child-WORKING` folder (module root). Currently, the extension requires the vscode workspace folder and the module root folder to be aligned either by

* open vscode from the go module root folder, or
* use go.work from the `Go` folder.

We are working to remove this restriction, but for now, please read and follow the instruction in https://github.com/golang/vscode-go#setting-up-your-workspace and https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.
