### ISSUE TITLE
Apple m1 Pro install gopls failed

### ISSUE THREAD

**Issue by ExpLife0011** [golang/vscode-go#2612]
<img width="1142" alt="截屏2023-01-16 13 25 26的副本" src="https://user-images.githubusercontent.com/37372761/212604753-02dce405-70d1-4a53-905e-c67c19438488.png">

I install the gopls  tool and get the error message as shown above

**Comment by hyangah** [comment]
@ExpLife0011 Can you try `go clean -cache` and then try to install again? Wonder if this is the same problem as https://github.com/golang/go/issues/57397.

And what is the go version?

**Comment by ExpLife0011** [comment]
> @ExpLife0011 Can you try `go clean -cache` and then try to install again? Wonder if this is the same problem as [golang/go#57397](https://github.com/golang/go/issues/57397).
> 
> And what is the go version?

I ran the `go clean -cache` command and then installed gopls and it worked, thanks!
