### ISSUE TITLE
Go test outputs opens in terminal tab instead of output tab

### ISSUE THREAD

**Issue by jadeidev** [golang/vscode-go#2615]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.4 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.11.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.74.3
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Describe the bug
When running tests from vscode the output opens up as a new terminal window like so:
![image](https://user-images.githubusercontent.com/32917209/212993600-0ccbc18f-6b2c-4d68-b155-639f47684127.png)
I expected it to open in the output tab under "Go Test":
![image](https://user-images.githubusercontent.com/32917209/212993922-d0561647-46c4-4523-9cf1-e42e7a79c777.png)

I don't know if this is the intended behavior. if it is, then obviously go ahead and close the issue

### Steps to reproduce the behavior:
1. Run tests in VS code with the test UI

**Comment by hyangah** [comment]
Hi @jadeidev Thanks for reporting the issue.
The test explorer utilizes newer TestAPI that utilizes the terminal window. The Go Tests output channel predates TestAPI and still gets used by the old ways of running tests (e.g. test code lens, ..). We hope to clean up and remove the old ways (the Go Tests output channel) as part of the effort such as https://github.com/golang/vscode-go/issues/1702 and https://github.com/golang/vscode-go/issues/2044.

Closing in favor of existing issues.
