### ISSUE TITLE
Failed to find the "go" binary with direnv

### ISSUE THREAD

**Issue by ciiqr** [golang/vscode-go#2617]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go1.18.9 darwin/arm64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- `v0.11.0`
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.74.3`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.38.0-dev`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- not possible (due to the nature of the bug)
</details>

### Share the Go related settings you have added/edited

N/A

### Describe the bug
When using the vscode-go extension along with an extension like [direnv](https://marketplace.visualstudio.com/items?itemName=mkhl.direnv) that updates the `PATH`, I get the error:
`Failed to find the "go" binary in either GOROOT() or PATH(...)`

After some brief debugging I determined the issue to be with `getBinPathWithPreferredGopathGorootWithExplanation` which uses the cached `envPath` instead of the most up to date `PATH` from `process.env`.

I tested with this function updated to pull the path every time and this has resolved the issue. Code I used in my fork here for reference: https://github.com/golang/vscode-go/compare/master...ciiqr:vscode-go:fix/direnv-support

### Steps to reproduce the behavior:
1. install go/direnv extensions
2. added an `.envrc` to my project with the contents: `PATH_add /path/to/go/bin` (assuming go isn't already in your path)
3. ran command: `direnv: Reset and reload environment` to update the path
4. clicked `Restart` on the popup direnv produces to reload all extensions
5. go extension pops up with the `Failed to find the "go" binary...` error (with `/path/to/go/bin` clearly not in the path it shows)

### Screenshots or recordings
-

**Comment by findleyr** [comment]
In general we do not update our environment after the extension host has started (doing so in full generality could be quite complicated).

I'm not sure we will be able to fix this. Do you find that other extensions do not have this problem?

**Comment by ciiqr** [comment]
this is the only extension I've had issues with (ie. rust-analyzer handle this just fine). The change shouldn't actually be that complicated. The direnv extension already reloads all extensions after updating `process.env`, it's just that vscode-go is storing the path from process.env once instead of reading it from `process.env` when it needs it, so it doesn't see the updated path. The change set I linked above was sufficient to fix the issue:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/2072378/213566097-6cd802f8-7a3c-4115-b677-60544e3e50e9.png">

**Comment by findleyr** [comment]
Aha, thanks for the additional info -- much appreciated. Also: I missed your patch above, thanks for highlighting it.

We'll investigate. If you want, feel free to send a PR with your fix -- it looks reasonable to me, though I'm not an expert on the extension.

**Comment by sun617** [comment]
I had the same issue
