### ISSUE TITLE
unknown environment setting GO111MODULE

### ISSUE THREAD

**Issue by jonathanRomeroP** [golang/vscode-go#2620]
Hola tengo este problema 
![image](https://user-images.githubusercontent.com/118024547/213750780-b1e08859-a0ba-4552-b8e7-b343fefe3d33.png)
intento instalar la extensión y aparase este error.

ya intente cambiar la variable de entorno 

![image](https://user-images.githubusercontent.com/118024547/213751083-9e719cad-888a-460c-aa29-7c95a994be43.png)

como también cambie la variable del .env en la ruta C:\Users\jhoro\AppData\Roaming\go

**Comment by findleyr** [comment]
Hola, estás ejecutando "go env" desde la terminal integrada? Está configurado "GO111MODULE" en su settings.json?

"off" es un valor no válido para GO111MODULE, por lo que aparece ese error.

**Comment by jonathanRomeroP** [comment]
@findleyr si estoy ejecutando go env desde la terminal integrada y el settings.json lo tengo de esta menera
![image](https://user-images.githubusercontent.com/118024547/213784165-9d34945c-c39c-42f0-8a94-14ac35adecd2.png)

**Comment by jonathanRomeroP** [comment]
Intente desinstalar y volver a instalar  el visual code y go, pero todo sigue igual

**Comment by findleyr** [comment]
Lo siento, pero no conozco ningún lugar en la extensión vscode que pueda causar esto.

Preguntaré en nuestra reunión de hoy.

**Comment by findleyr** [comment]
Lo siento, pero no creo que podamos diagnosticar esto. No sabemos de dónde viene esta configuración.
