### ISSUE TITLE
Support single-string `args` in `launch.json`

### ISSUE THREAD

**Issue by weikanglim** [golang/vscode-go#2621]
**Is your feature request related to a problem? Please describe.**

I'd like the ability to create a `launch.json` that prompts the user for the exact args to be passed through to my debugging program. The user types in the args into the prompt, and the args is passed through to the launching program.

For example, if launching `go.exe` with debugger, I expect the user to be able to type `test ./...` in the prompt, and the resulting program `go.exe test ./...` is ran with debugging:
![image](https://user-images.githubusercontent.com/2322434/213801457-85ad2c68-eb1f-42b2-b474-a78b1f89642e.png)

My understanding based on this [comment](https://github.com/microsoft/vscode/issues/83678#issuecomment-1236381454), is that VSCode now allows `args` to be either a string-array or a string type. However, it is up to the debugging extension to support the newly-added string type.

Desired supported `launch.json`:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}",
            "console": "integratedTerminal",
            "args": "${input:args}"
        }
    ],
    "inputs": [
        {
            "id": "args",
            "type": "promptString",
            "description": "Args for launch package",
        }
      ]
}
```

Currently, this configuration results in the following error:
![image](https://user-images.githubusercontent.com/2322434/213801221-7f078e0a-9645-4f36-b2e3-e9a39dec0726.png)
 
**Describe the solution you'd like**
The string-typed `args` should be handled to support this scenario.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by findleyr** [comment]
Thanks for the report. This makes sense to me.

**Comment by findleyr** [comment]
Marking this as HelpWanted as I think it would be reasonable for an external contributor to pick this up.

**Comment by weikanglim** [comment]
@findleyr I submitted a change for this with tests if anyone on the team would like to take a look. I couldn't find any existing package that provided a shell-like word splitting, ended up implementing one that is consistent with `bash` / POSIX.

**Comment by weikanglim** [comment]
Hello @findleyr , hope this finds you well. I double checked my changes and tests today, and I like where it is and hope that a maintainer is able to provide review. Would love to be able to take advantage of this feature in my own work/personal projects.

For context, I tried to implement basic whitespace splitting `.split(' ')`, but then with the need to also interpret whitespace as being part of an argument made it more complicated. Perhaps a simple way would have been to provide backslash+whitespace as an escape mechanism, but I wanted to see if we could just make the args string feel familiar to the user, and ended up implementing bash-like semantics for word parsing. I think the tests do give pretty good coverage but would love any feedback on it.

**Comment by weikanglim** [comment]
Tested it on nightly today and things work as expected. One of the things I didn't test well was the schema. It looks like VSCode [supports ](https://code.visualstudio.com/api/references/contribution-points) `type: ["array", "string"]`, so we'll want to make a follow-up change to update `package.json accordingly. The user gets squiggly lines otherwise when editing `launch.json`.
