### ISSUE TITLE
Improve semantic highlighting to allow different styles for struct and interface types

### ISSUE THREAD

**Issue by till-kolditz** [golang/vscode-go#2631]
**Is your feature request related to a problem? Please describe.**
Highlighting interface type names differently from struct type names is not possible.
For instance, I'd like to have the type name of interfaces shown _italic_ .
In vscode you can use the "Inspect Editor Tokens and Scopes" tool to see which types tokens have.
For both struct types and interface types, the name has following properties (which should IMHO be different):

    standard token type = Other
    textmate scopes = [entity.name.type.go , source.go]
    foreground = entity.name.type

so both are indistinguishable and it's not possible to have them highlighted differently. Please see the two attached screenshots, taken with vscode on a Xubuntu 22.10 system with following package version: `code/stable,now 1.74.3-1673284829 amd64 [installed]` (apt list --installed code).
The vscode docs provide a list of "standard token types and modifiers" here: https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#standard-token-types-and-modifiers which include which include `struct` and `interface`.

**Describe the solution you'd like**
Provide different textmate scopes / foreground attributes to allow configuring those independently.
For instance, I could imagine following attribute values.

For struct:

    standard token type = struct
    textmate scopes = [entity.name.struct.go , source.go]
    foreground = entity.name.struct

For interface

    standard token type = interface
    textmate scopes = [entity.name.interface.go , source.go]
    foreground = entity.name.interface

![image](https://user-images.githubusercontent.com/1200049/215436031-d57da5b5-a335-471c-a60f-70ed267b923d.png)
![image](https://user-images.githubusercontent.com/1200049/215436689-18f17466-3919-497d-b540-a774c62e7ba4.png)

**Comment by hyangah** [comment]
As mentioned in https://github.com/golang/vscode-go/wiki/features#syntax-highlighting 
this extension is not providing textmate rules. If you want textmate rule adjustment, please open an issue in https://github.com/jeff-hykin/better-go-syntax/issues. 

I was curious if the LSP-based semantic highlighting distinguishes `interface` and `struct` types. 
Unfortunately, it looks like Gopls assigns `type` semantic token to both `interface` and `struct` types. (Indeed they are types :-) ) @pjweinb Can you tell us why `type` is more appropriate than `interface` and `struct` token types?

**Comment by pjweinb** [comment]
I'm neutral, but if someone wants it changed, it would be nice to have a
full specification of what's desired.
E.g., in type T = []B, presumably T is still "type", no matter what B is.
But then in type T B, should T be whatever B is?

[That is, the language definition describes all the places a type name can
occur. For each of those, what should the new semantic token be?]

**Comment by hyangah** [comment]
Thanks @pjweinb

That's a good point.  For `type T B` or type alias, it would be ideal if we can infer T's type as much as possible, but that mandates full type checking.

Closing as out of scope + unfortunate.
