### ISSUE TITLE
Automatically clear previous Go test results

### ISSUE THREAD

**Issue by rootulp** [golang/vscode-go#2632]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see the output from previous test runs in the Go Tests output pane.

**Describe the solution you'd like**
An option to automatically clear previous test run output.

**Describe alternatives you've considered**
I've enabled auto scrolling but if I scroll up far enough, I see the previous test run's output and get confused on which test output I should be looking at. I almost always only care about the last test run invocation.

**Additional context**

For example, in the screenshot below I would only like to see the most recent "ok ..." test run results.

<img width="1429" alt="Screenshot 2023-01-30 at 2 04 56 PM" src="https://user-images.githubusercontent.com/3699047/215591297-609b874a-6ab8-4f82-89c9-57b4a88ff4c3.png">

**Comment by hyangah** [comment]
@rootulp How do you run tests? 
I tried to reproduce it but I couldn't when I run a test with, for example, "Run Test" codelens.
[This code](https://github.com/golang/vscode-go/blob/32a643f674ca4e3d322ccffc22f28cf93a9c1f82/src/testUtils.ts#L286-L288) is supposed to clear the output page - except when multiple test processes are running. Did you start a new test before the previous one completed? Or maybe there is a bug in active test counting.

**Comment by rootulp** [comment]
I am also starting tests via "Run Test" in codelens. I'm only running one test at a time. Do you see historical test output if you scroll up in the bottom pane?

**Comment by hyangah** [comment]
Do you mean "output.smartScroll.enabled"? I see that is enabled by default.

Very strange. As shown in the code mentioned in https://github.com/golang/vscode-go/issues/2632#issuecomment-1409669192,  the extension calls `outputChannel.clear()` before starting a new test.

https://user-images.githubusercontent.com/4999471/216224388-744f017e-5bf4-475f-b464-bfb0e568a368.mp4

Can you reproduce the issue when all other extensions but this Go extension are disabled? 
Can you share your vscode settings (both user/workspace settings if you have)

Thanks!

**Comment by rootulp** [comment]
Thanks for attempting to reproduce the issue. I just attempted to reproduce but I see the behavior displayed in your GIF (where the previous output is cleared). I don't know what caused the difference in behavior but I'll try to capture a GIF when historical test output is preserved.

**Comment by rootulp** [comment]
Let's close this and I can re-open if I can reliably repro.
