### ISSUE TITLE
getting undeclared name warnings for methods defined in the same package but different file

### ISSUE THREAD

**Issue by 211217613** [golang/vscode-go#2638]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.19.5 darwin/arm64`

* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- 
```
Build info
----------
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19.5
```

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- `1.69.1 b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a arm64`
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.37.1`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: $HOME/.golib/bin
toolsGopath: 
gopath: $HOME/.golib
GOROOT: /opt/homebrew/Cellar/go/1.19.5/libexec
PATH: $HOME/.pyenv/shims:$HOME/.pyenv/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/go/bin:/usr/local/munki:/Users/vruben/.local/bin:$HOME/.golib/bin:$HOME/.sledge/bin:$HOME/.local/bin:/opt/google-cloud-sdk/bin:/opt/homebrew/opt/fzf/bin

	go:	/opt/homebrew/bin/go: go version go1.19.5 darwin/arm64

	gotests:	$HOME/.golib/bin/gotests	(version: v1.6.0 built with go: go1.19.5)
	gomodifytags:	$HOME/.golib/bin/gomodifytags	(version: v1.16.0 built with go: go1.19.5)
	impl:	$HOME/.golib/bin/impl	(version: v1.1.0 built with go: go1.19.5)
	goplay:	$HOME/.golib/bin/goplay	(version: v1.0.0 built with go: go1.19.5)
	dlv:	$HOME/.golib/bin/dlv	(version: v1.20.1 built with go: go1.19.5)
	staticcheck:	$HOME/.golib/bin/staticcheck	(version: v0.3.3 built with go: go1.19.5)
	gopls:	$HOME/.golib/bin/gopls	(version: v0.11.0 built with go: go1.19.5)

go env
Workspace Folder (single-tenant-api): $HOME/Dev/wcnp/single-tenant-api
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN="$HOME/.golib/bin"
	GOCACHE="$HOME/Library/Caches/go-build"
	GOENV="$HOME/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="$HOME/.golib/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="$HOME/.golib"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.19.5"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="$HOME/Dev/wcnp/single-tenant-api/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/rc/8_65603j3zb5552p5yhnckz00000gq/T/go-build4235758297=/tmp/go-build -gno-record-gcc-switches -fno-common"
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
    "go.lintOnSave": "file",
    "go.toolsManagement.autoUpdate": true,
    "go.toolsManagement.checkForUpdates": "off",
"gopls": {
        "ui.semanticTokens": true
    }
```
### Describe the bug
vscode is giving warnings about methods and variables that are undeclared. The variables are declared under the same package but different files.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/7006850/216184522-2e7d4f46-a910-4dfc-a4e9-3cfe3d918a24.png">

<img width="271" alt="image" src="https://user-images.githubusercontent.com/7006850/216184785-53edff09-1174-4382-95db-3da0ff6558c1.png">

**Comment by hyangah** [comment]
@211217613 Can you try if you get the same error when you switch to `"go.lintOnSave": "package"`?

**Comment by 211217613** [comment]
> @211217613 Can you try if you get the same error when you switch to `"go.lintOnSave": "package"`?

ya that seems to have fixed the issue. Is this a bug or should I leave the `go.lintOnSave` set to package?

What is the difference between `file` and `package` for this setting?

**Comment by hyangah** [comment]
Lint is done by calling your choice of the linter (by default `staticcheck`).
For file mode, the extension calls the linter with the current file.
For package mode, it calls the linter with the current file's package.

Many modern go linters nowadays runs the `go` command underneath and `go` command is unhappy about the symbols not being present when processing a single file. So, `(compile)` annotation in the error message. I think this is working as intended.

> should I leave the `go.lintOnSave` set to package?
Most likely I think so.

When will this `file` mode be useful? I think this setting was added when linters didn't depend on the go commands and weren't powerful enough to have precise checkers. Nowadays, I think this mode has more limited utility e.g. when a user is working on script-like go files in a directory where each individual file is supposed to run with `go run <script.go>`.
