### ISSUE TITLE
Go Definitions stop showing after opening the second .go file

### ISSUE THREAD

**Issue by Impjegat** [golang/vscode-go#264]
Issue Type: <b>Bug</b>

When opening a .go file for the first time when vscode is launched, there are no issues with getting definitions for the various methods used and so on.

Upon opening up a second .go file, the hovering feature does not load. Neither does the ability to search for definitions as an error "No definitions found" is displayed.

Re-opening the first file does not give any issues. The above persist till you close vscode and re-open it.

Please help!

Extension version: 0.14.4
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (25.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>

**Comment by hyangah** [comment]
@Impjegat thanks for the report. For triaging this issue, we need more details about your setup.

- The extension settings ("Preferences: Open Settings (JSON)" and "Preferences: Open Workspace Settings (JSON)", find all fields starting with `"go"`, `"[go]"`, `"gopls"`. 
- If you have `"go.useLanguageServer": true` in the settings, follow the instruction https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code and capture the logs when the problem (missing intellisense) occurs.
- The workspace directory structure (where the two `.go` files are located, and if there are any `go.mod` files in the directories and the parents directories)

**Comment by Impjegat** [comment]
Hi @hyangah,

Thanks for getting back.

Please find below the replies to your queries:

- The following are the settings in my "Preferences: Open Settings (JSON)". The "Preferences: Open Workspace Settings (JSON)" is empty:
```
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "go.formatTool": "goimports",
    "git.autofetch": true,
    "workbench.editorAssociations": [
        {
            "viewType": "default",
            "filenamePattern": "*.html"
        }
    ],
    "files.associations": {
        "*.html": "html",
        "*.gohtml": "gohtml"
    },
    "git.enableSmartCommit": true,
    "explorer.confirmDragAndDrop": false,
    "svg.preview.mode": "img",
    "explorer.confirmDelete": false,
    "go.docsTool": "gogetdoc",
    "go.useLanguageServer": true
}
```

- As can be seen, the "go.useLanguageServer" is set to `true`. The following text file shows the relevant logs being captured: [Output.txt](https://github.com/golang/vscode-go/files/4850704/Output.txt)

- I am currently in the process of learning Go. I am following the tutorial provided by GoesToEleven (https://github.com/GoesToEleven/golang-web-dev). My directory structure is a git clone of the repository on a mapped server I have at home. No `go.mod` files are included or have been created.

Let me know if there are any other questions.

**Comment by hyangah** [comment]
@Impjegat When working in the GOPATH mode (i.e. no `go.mod`), the source code needs to be laid out following the convention described in https://golang.org/cmd/go/#hdr-GOPATH_environment_variable.

Since your GOPATH is `C:\Users\Bernard\go`, you will need to clone the tutorial repo under `C:\Users\Bernard\go\src\golang-web-dev`, and open vscode from the root of the repo. 

If you want to keep the cloned repo in a different drive, change your GOPATH (either by setting the GOPATH environment variable, or using the `"go.gopath"` setting) but still lay out your code following the suggested directory structure. 

In modules mode (`go.mod`), this is unnecessary. See https://golang.org/doc/code.html for intro to writing code in modules mode.

**Comment by Impjegat** [comment]
Thanks a lot @hyangah. Managed to resolve this!
