### ISSUE TITLE
format behavior of format on save and manually format are different

### ISSUE THREAD

**Issue by swhoro** [golang/vscode-go#2640]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

Go 1.109.5

VS Code 1.75.0

extension 0.37.1

gopls 0.11.0

</details>

### Share the Go related settings you have added/edited
```
    "[go]": {
        "editor.defaultFormatter": "golang.go"
    },
    "gopls": {
        "formatting.local": "b.carriage.fun",
        "ui.semanticTokens": true
    }
```

### Describe the bug

when I use manually format, the 3rd-party package are mixed with my local package

but if I use save to format, these are splitted

### Steps to reproduce the behavior:
1. write sample code:
![image](https://user-images.githubusercontent.com/34229589/216561461-faaa1762-5e74-4fa8-8786-8805ce90d897.png)
2. use manually format (right click and choose format), they are mixed:
![image](https://user-images.githubusercontent.com/34229589/216561186-2d7c8946-ffbe-4fac-bf7f-f20e25269a29.png)
3. use format on save, they are splitted, which is what I want:
![image](https://user-images.githubusercontent.com/34229589/216561721-8cb8d327-78d4-4eac-a1e4-c4e4e9a0a011.png)

**Comment by suzmue** [comment]
The difference between these two cases, is that only the second runs the code action for organizing imports (see https://github.com/golang/vscode-go/wiki/advanced#formatting-code-and-organizing-imports).

The regular formatting does some minimal formatting of the imports (sorting within group and maybe deleting duplicates) but does not delete unused imports or regroup them, this is done by organize imports.

VS Code also has an `Organize Imports` command similar to `Format Document`, which you can run to achieve this manually.

<img width="872" alt="Screenshot 2023-02-07 at 3 40 17 PM" src="https://user-images.githubusercontent.com/6634754/217383390-dccb8219-01d9-4dd6-8197-211996952faf.png">

**Comment by hyangah** [comment]
As @suzmue said, `formatting.local` controls organize imports, not formatting. And, organize imports on save is enabled by default. The setting naming is unfortunate but I am afraid it's too late to change the setting name. Making the formatting to organize import is also undesirable - some people depend on the manual formatting to format without organizing imports.
