### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by hypeitnow** [golang/vscode-go#2644]
gopls version: v0.11.0 (go1.19.5)
gopls flags: 
update flags: local
extension version: 0.37.1
go version: 1.19.5
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 05 Feb 2023 18:24:57 GMT
restart history:
Sun, 05 Feb 2023 18:21:36 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Information about connection crash 

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 6:22:41 PM] 2023/02/05 18:22:41 go/packages.Load #1
	snapshot=0
	directory=file:///workspaces/juju
	query=[builtin github.com/juju/juju/...]
	packages=2315

[Info  - 6:22:41 PM] 2023/02/05 18:22:41 go/packages.Load #1: updating metadata for 4865 packages

[Info  - 6:22:56 PM] 
[Info  - 6:22:57 PM] 2023/02/05 18:22:57 go env for /workspaces/juju
(root /workspaces/juju)
(go version go version go1.19.5 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOROOT=/usr/local/go
GONOPROXY=
GOINSECURE=
GOPRIVATE=
GONOSUMDB=
GO111MODULE=
GOSUMDB=sum.golang.org
GOPROXY=https://proxy.golang.org,direct
GOFLAGS=
GOMODCACHE=/go/pkg/mod
GOMOD=/workspaces/juju/go.mod
GOWORK=
GOCACHE=/home/codespace/.cache/go-build
GOPATH=/go

[Info  - 6:23:16 PM] 2023/02/05 18:23:16 go/packages.Load #1
	snapshot=0
	directory=file:///workspaces/juju
	query=[builtin github.com/juju/juju/...]
	packages=2315

[Info  - 6:23:16 PM] 2023/02/05 18:23:16 go/packages.Load #1: updating metadata for 4865 packages

[Info  - 6:23:32 PM] 
[Info  - 6:23:33 PM] 2023/02/05 18:23:33 go env for /workspaces/juju
(root /workspaces/juju)
(go version go version go1.19.5 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOMOD=/workspaces/juju/go.mod
GOCACHE=/home/codespace/.cache/go-build
GONOPROXY=
GOMODCACHE=/go/pkg/mod
GOWORK=
GOROOT=/usr/local/go
GO111MODULE=
GOFLAGS=
GOSUMDB=sum.golang.org
GOPRIVATE=
GONOSUMDB=
GOPROXY=https://proxy.golang.org,direct
GOINSECURE=
GOPATH=/go

[Info  - 6:23:50 PM] 2023/02/05 18:23:50 go/packages.Load #1
	snapshot=0
	directory=file:///workspaces/juju
	query=[builtin github.com/juju/juju/...]
	packages=2315

[Info  - 6:23:50 PM] 2023/02/05 18:23:50 go/packages.Load #1: updating metadata for 4865 packages

[Info  - 6:24:07 PM] 
[Info  - 6:24:08 PM] 2023/02/05 18:24:08 go env for /workspaces/juju
(root /workspaces/juju)
(go version go version go1.19.5 linux/amd64)
(valid build configuration = true)
(build flags: [])
GO111MODULE=
GOMOD=/workspaces/juju/go.mod
GOPROXY=https://proxy.golang.org,direct
GOWORK=
GOPATH=/go
GOMODCACHE=/go/pkg/mod
GOPRIVATE=
GOFLAGS=
GONOPROXY=
GOCACHE=/home/codespace/.cache/go-build
GOROOT=/usr/local/go
GONOSUMDB=
GOINSECURE=
GOSUMDB=sum.golang.org

[Info  - 6:24:27 PM] 2023/02/05 18:24:27 go/packages.Load #1
	snapshot=0
	directory=file:///workspaces/juju
	query=[builtin github.com/juju/juju/...]
	packages=2315

[Info  - 6:24:27 PM] 2023/02/05 18:24:27 go/packages.Load #1: updating metadata for 4865 packages

[Error - 6:24:43 PM] Connection to server got closed. Server will not be restarted.
Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@hypeitnow Thanks for the report. By any chance, were you using a dev container or running a gopls in a resource capped container? Looks like the gopls was killed a few seconds after starting to load all packages in the workspace.

**Comment by adonovan** [comment]
It's hard to know exactly what happened here but @hyangah's guess is as good as any. The good news is that the next version of gopls expected in March should include major reductions in memory usage.
