### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by NeverlandMJ** [golang/vscode-go#2645]
gopls version: v0.11.0 (go1.18.10)
gopls flags: 
update flags: proxy
extension version: 0.37.1
go version: 1.18.10
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Mon, 06 Feb 2023 07:19:11 GMT
restart history:
Mon, 06 Feb 2023 07:15:37 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by NeverlandMJ** [comment]
[Info  - 10:33:19 AM] 2023/02/07 10:33:19 go env for C:\Users\sumbula\Desktop\minstroy
(root C:\Users\sumbula\Desktop\minstroy)
(go version go version go1.18.10 windows/386)
(valid build configuration = true)
(build flags: [])
GOFLAGS=
GONOPROXY=
GO111MODULE=
GOMODCACHE=C:\Users\sumbula\go\pkg\mod
GOCACHE=C:\Users\sumbula\AppData\Local\go-build
GOROOT=C:\
GOINSECURE=
GONOSUMDB=
GOMOD=NUL
GOPRIVATE=
GOSUMDB=sum.golang.org
GOPATH=C:\Users\sumbula\go
GOPROXY=https://proxy.golang.org,direct
GOWORK=


[Info  - 10:34:08 AM] 2023/02/07 10:34:08 go/packages.Load #1
	snapshot=0
	directory=file:///C:/Users/sumbula/Desktop/minstroy
	query=[builtin qurilish/qv_admin_api_gateway/... qurilish/qv_analytic_service/... qurilish/qv_auth_service/... qurilish/qv_journal_service/... qurilish/qv_mspd_integration_service/... qurilish/qv_object_service/... qurilish/qv_settings_service/... qurilish/qv_sms_service/...]
	packages=189

[Info  - 10:34:08 AM] 2023/02/07 10:34:08 go/packages.Load #1: updating metadata for 681 packages

[Error - 10:34:34 AM] 2023/02/07 10:34:34 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_object_service/go.mod: err: exit status 1: stderr: go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: github.com/klauspost/cpuid@v1.3.1: module lookup disabled by GOPROXY=off


[Error - 10:34:40 AM] 2023/02/07 10:34:40 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_settings_service/go.mod: err: exit status 1: stderr: go: downloading github.com/google/go-cmp v0.5.6
go: downloading github.com/dustin/go-humanize v1.0.0
go: github.com/jackc/pgconn@v1.11.0 requires
	github.com/jackc/pgproto3/v2@v2.1.1: module lookup disabled by GOPROXY=off


[Error - 10:34:44 AM] 2023/02/07 10:34:44 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_sms_service/go.mod: err: exit status 1: stderr: go: downloading github.com/goccy/go-json v0.9.7
go: downloading github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: github.com/streamingfast/logging@v0.0.0-20220511154537-ce373d264338 requires
	golang.org/x/crypto@v0.0.0-20220214200702-86341886e292: module lookup disabled by GOPROXY=off


[Error - 10:34:50 AM] 2023/02/07 10:34:50 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_admin_api_gateway/go.mod: err: exit status 1: stderr: go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: github.com/klauspost/cpuid@v1.3.1: module lookup disabled by GOPROXY=off


[Error - 10:34:56 AM] 2023/02/07 10:34:56 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_analytic_service/go.mod: err: exit status 1: stderr: go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/google/go-cmp v0.5.6
go: github.com/go-openapi/spec@v0.20.4 requires
	github.com/go-openapi/swag@v0.19.15: module lookup disabled by GOPROXY=off


[Error - 10:35:01 AM] 2023/02/07 10:35:01 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_auth_service/go.mod: err: exit status 1: stderr: go: downloading github.com/google/go-cmp v0.5.6
go: downloading github.com/json-iterator/go v1.1.9
go: github.com/go-openapi/spec@v0.20.4 requires
	github.com/go-openapi/swag@v0.19.15: module lookup disabled by GOPROXY=off


[Error - 10:35:02 AM] 2023/02/07 10:35:02 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_journal_service/go.mod: err: exit status 1: stderr: go: downloading github.com/google/go-cmp v0.5.6
go: downloading github.com/dustin/go-humanize v1.0.0
go: github.com/go-openapi/spec@v0.20.4 requires
	github.com/go-openapi/swag@v0.19.15: module lookup disabled by GOPROXY=off


[Error - 10:35:03 AM] 2023/02/07 10:35:03 tidy: diagnosing file:///C:/Users/sumbula/Desktop/minstroy/qv_mspd_integration_service/go.mod: err: exit status 1: stderr: go: downloading github.com/google/go-cmp v0.5.6
go: github.com/go-openapi/spec@v0.20.4 requires
	github.com/go-openapi/swag@v0.19.15: module lookup disabled by GOPROXY=off

> Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)? ![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by suzmue** [comment]
Thanks! What were you doing at the time that you saw the crash?
