### ISSUE TITLE
It's impossible to uninstall the extension

### ISSUE THREAD

**Issue by artm** [golang/vscode-go#2646]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.75.0 
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.37.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/abaguinski/go
GOROOT: /usr/local/go
PATH: /home/abaguinski/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/bin/remote-cli:~/go/bin:/usr/local/go/bin:/home/abaguinski/.local/bin:/home/abaguinski/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/a.baguinski/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/a.baguinski/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin

	go:	/usr/local/go/bin/go: go version go1.17.3 linux/amd64

	gotests:	/home/abaguinski/go/bin/gotests	(version: v1.6.0 built with go: go1.17.3)
	gomodifytags:	/home/abaguinski/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.17.3)
	impl:	/home/abaguinski/go/bin/impl	(version: v1.1.0 built with go: go1.17.3)
	goplay:	/home/abaguinski/go/bin/goplay	(version: v1.0.0 built with go: go1.17.3)
	dlv:	/home/abaguinski/go/bin/dlv	(version: v1.7.3 built with go: go1.17.3)
	staticcheck:	/home/abaguinski/go/bin/staticcheck	(version: v0.2.2 built with go: go1.17.3)
	gopls:	/home/abaguinski/go/bin/gopls	(version: v0.11.0 built with go: go1.17.3)

go env
Workspace Folder (abaguinski): /home/abaguinski
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/abaguinski/.cache/go-build"
	GOENV="/home/abaguinski/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/abaguinski/go/pkg/mod"
	GONOPROXY="gitlab.hotflo.net"
	GONOSUMDB="gitlab.hotflo.net"
	GOOS="linux"
	GOPATH="/home/abaguinski/go"
	GOPRIVATE="gitlab.hotflo.net"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.17.3"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build831441956=/tmp/go-build -gno-record-gcc-switches"
```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

- find the extension
- uninstall
- restart vscode
- the extension installs itself

- extension remains uninstalled

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

initial situation:

![image](https://user-images.githubusercontent.com/64227/216981675-bd8f65e2-d739-4f8c-8bd9-c045b05354b6.png)

after clicking uninstall:

![image](https://user-images.githubusercontent.com/64227/216981868-0a4b2dc3-28f6-429c-8c3a-86c2f4c613ea.png)

i'm not fast enough to screenshot the extension page saying "installing"

![image](https://user-images.githubusercontent.com/64227/216981956-36164fc2-1472-4b9b-b438-637736daf629.png)

**Comment by suzmue** [comment]
@artm We do not manage the installation, that is done by VS Code itself You can file an issue upstream at itself https://github.com/microsoft/vscode/issues.

It's possible this is related to the WSL environment you are developing in (from the last screenshot you can see it is enabled on `WSL: Ubuntu-20.04). They have some guidance related to managing extensions in wsl:
- https://code.visualstudio.com/docs/remote/wsl#_managing-extensions
- https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-vscode

**Comment by artm** [comment]
Thanks Suzy. I've refiled this issue at VS Code.

**Comment by hyangah** [comment]
Thanks.

Closing since the installation process belongs to outside of individual extensions.
