### ISSUE TITLE
Intellisense doesn't work inside nested project directories

### ISSUE THREAD

**Issue by infixint943** [golang/vscode-go#265]
### What version of Go, VS Code & VS Code Go extension are you using?
- go version go1.14.4 linux/amd64
- 1.47.0-insider 9bf6af04dcb5c2e531cedca83cd188939ca1b0db x64
- 0.14.4
```
GO111MODULE="auto"
GOARCH="amd64"
GOBIN="/home/gevacrt/go/bin"
GOCACHE="/home/gevacrt/.cache/go-build"
GOENV="/home/gevacrt/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/gevacrt/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/gevacrt/cptool/pkg/codeforces/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build524846832=/tmp/go-build -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited
```
"go.useLanguageServer": true,
```

### Describe the bug
Here is what my project directory looks like
```
.
├── cmd/
│   ├── myapp/
│   │   ├── file1.go
│   │   └── file2.go
│   └── myanotherapp/
│       ├── file1.go
│       └── file2.go
└── pkg/
    └── mylibrary/
        ├── file1.go
        ├── file2.go
        ├── go.mod
        └── go.sum
```

Importing any external library in `mylibrary` module (and even `myapp/myotherapp`), causes intellisense suggestions to not show up. However, opening any of the folders individually (like opening only folder `mylibrary` or `myapp`), resolves the error.

### Steps to reproduce the behavior:
1. Create a similar project directory structure as above
2. Try importing an external package (in my example, `github.com/urfave/cli/v2`).
3. You will observe intellisense suggestions not appearing.
4. Doing the same by opening only the folder `myapp` on `vscode`, causes the intellisense to work correctly.

### Screenshots or recordings
![Screenshot_20200629_022139](https://user-images.githubusercontent.com/45997896/85957987-bbd5fc80-b9af-11ea-9916-1c28a7cfd47d.png)
![Screenshot_20200629_022352](https://user-images.githubusercontent.com/45997896/85957988-bd072980-b9af-11ea-8d9b-e606c186e269.png)

**Comment by hyangah** [comment]
@infixint943 thanks for the report. That's a known issue. https://github.com/golang/go/issues/36899 describes the current limitation and the improvement plan. Currently the best workaround is to use Workspace Folders per module - for every `go.mod`, add the module root using "File" > "Add Folder to Workspace".  (https://github.com/golang/go/issues/32394)

@stamblerre Let's create a pinned issue on vscode-go side. It became the most common issues users face nowadays.

**Comment by stamblerre** [comment]
Good idea - done: https://github.com/golang/vscode-go/issues/275.

**Comment by hyangah** [comment]
Thanks @stamblerre 

I will close this issue in favor of the pinned issue.
