### ISSUE TITLE
user snippet seem not working properly

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [golang/vscode-go#2650]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.20
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- 0.11.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.75.0
* Check your installed extensions to get the version of the VS Code Go extension
	- 0.37.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Workspace Folder (progress_form): e:\root\_astro\progress_form
	set GO111MODULE=
	set GOARCH=amd64
	set GOBIN=
	set GOCACHE=C:\Users\k0108\AppData\Local\go-build
	set GOENV=C:\Users\k0108\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOEXPERIMENT=
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=C:\Users\k0108\go\pkg\mod
	set GONOPROXY=
	set GONOSUMDB=
	set GOOS=windows
	set GOPATH=C:\Users\k0108\go
	set GOPRIVATE=
	set GOPROXY=https://proxy.golang.org,direct
	set GOROOT=C:\Program Files\Go
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	set GOVCS=
	set GOVERSION=go1.20
	set GCCGO=gccgo
	set GOAMD64=v1
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=0
	set GOMOD=NUL
	set GOWORK=
	set CGO_CFLAGS=-O2 -g
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-O2 -g
	set CGO_FFLAGS=-O2 -g
	set CGO_LDFLAGS=-O2 -g
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\k0108\AppData\Local\Temp\go-build2957487532=/tmp/go-build -gno-record-gcc-switches
</details>

- User Snippet isnt working both stable and nightly verison
- Some snippets are shown when i use at outside of function, never work inside.
- i think that is occured recent update.

**Comment by cmsax** [comment]
Same issue. Snippets like `ife` (if err != nil) not working, even the snippets I manually created not work either.

**Comment by eryajf** [comment]
Same issue. 

When I type the letter f, press the up and down keys to see that the forr is in the optional list, as shown in the figure:

![](https://cdn.staticaly.com/gh/eryajf/tu/main/img/image_20230209_120636.png)

When I continued to type letters, I couldn't find any matching complements, as shown in the figure:

![](https://cdn.staticaly.com/gh/eryajf/tu/main/img/image_20230209_120733.png)

**Comment by kurimi1** [comment]
Same issue.

**Comment by Knorway** [comment]
same here.

**Comment by webberpuma** [comment]
same here

**Comment by Knorway** [comment]
@suzmue it's working after the update. thank you!
