### ISSUE TITLE
Invalid value when you point the mouse at a variable

### ISSUE THREAD

**Issue by scootpl** [golang/vscode-go#2651]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.19.4 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19.3

* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

* Check your installed extensions to get the version of the VS Code Go extension
	- v0.37.1

* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- go:	/usr/local/bin/go: go version go1.19.4 darwin/amd64

	gotests:	/Users/scoot/go/bin/gotests	(version: v1.6.0 built with go: go1.19.1)
	gomodifytags:	/Users/scoot/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.19.1)
	impl:	/Users/scoot/go/bin/impl	(version: v1.1.0 built with go: go1.19.1)
	goplay:	/Users/scoot/go/bin/goplay	(version: v1.0.0 built with go: go1.19.1)
	dlv:	/Users/scoot/go/bin/dlv	(version: v1.9.1 built with go: go1.19.1)
	staticcheck:	/Users/scoot/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.1)
	gopls:	/Users/scoot/go/bin/gopls	(version: v0.11.0 built with go: go1.19.3)

go env
Workspace Folder (rtd): /Users/scoot/go/src/github.com/scootpl/rtd
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/scoot/Library/Caches/go-build"
	GOENV="/Users/scoot/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/scoot/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/scoot/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.19.4/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.19.4/libexec/pkg/tool/darwin_amd64"
	GOVCS=""
	GOVERSION="go1.19.4"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/scoot/go/src/github.com/scootpl/rtd/go.mod"
	GOWORK=""
	CGO_CFLAGS="-mmacosx-version-min=11.2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vz/n0zz1ht53bg3xz7njjzpjyhr0000gp/T/go-build1704131766=/tmp/go-build -gno-record-gcc-switches -fno-common"
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

"go.gopath": "~/go",

### Describe the bug
Invalid value when you point the mouse at a variable.

### Steps to reproduce the behavior:
1. Define a variable or constant and comment it out
2. Redefine the same variable with different value line below
3. Use variable in your app
4. When you point the mouse at a variable, you will see an invalid value

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="826" alt="216848178-4ce5c690-3df5-4fe0-b881-06378fe20e7b" src="https://user-images.githubusercontent.com/22987898/217296739-8f6dd659-3a7c-4306-a3bc-e1610ff8815f.png">

**Comment by suzmue** [comment]
The commented out value is treated as a doc comment (https://tip.golang.org/doc/comment) since it appears directly before a var, which is then included in the hover as additional information. If you don't want it to be included as a doc comment, you can add an empty new line between the comment and `a int = 10`.

```
var (
  // a = 50
  //

  a int = 10
)
```

**Comment by scootpl** [comment]
I thought that in this particular case the commented variable should not be considered as a doc comment. But it is not a big problem. Thank you.

**Comment by findleyr** [comment]
I noticed this as well, and agree!

This is filed as https://go.dev/issue/58220. I just revamped our hover logic, and will fix this for the next release.

**Comment by findleyr** [comment]
Closing this in favor of golang/go#58220

**Comment by findleyr** [comment]
Closing this in favor of golang/go#58220
