### ISSUE TITLE
扩展冲突

### ISSUE THREAD

**Issue by liuxiaobopro** [golang/vscode-go#2653]
Type: <b>Bug</b>

1. region 范围注释不好使
2. 工作区代码块必须打全prefix再删除几个字符才能出现建议结果

Extension version: 0.37.1
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.07GB free)|
|Process Argv|--crash-reporter-id 32d6e3db-d387-43e2-b1d2-24fbe9a9d737|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548
vsctsb:30659830

```

</details>

**Comment by hyangah** [comment]
From google translate:

> The region range annotation is not easy to use
> The code block in the workspace must be fully prefixed and a few characters deleted before the suggested results appear

I am afraid some context is lost in translation.
Do you mind sharing a screenshot that show what it is like currently and what you are proposing?
Thanks!

**Comment by liuxiaobopro** [comment]
1. 第一个问题: 扩展打开后, region就不能折叠了
![image](https://user-images.githubusercontent.com/54826000/224929625-ca47cfd6-c301-47e0-87bf-287cc59bf7a0.png)
![image](https://user-images.githubusercontent.com/54826000/224929753-1beb7d25-f0b4-4ad6-97a6-c4f50e67b4b6.png)

2. 第二个问题: 复现不出来了, 可能是我当初电脑问题

**Comment by hyangah** [comment]
Thanks for the screenshots.
I guess the first issue is about `#region`/`#endregion` support. 
Use `"editor.foldingStrategy": "indentation"` setting.
See https://github.com/golang/vscode-go/issues/134#issuecomment-662990667.

The `#region` is not part of the Go language, so the go language server does not understand it when computing folding. 

If you encounter the second issue, please open a new issue with gopls trace, that will help our investigation greatly. Thanks!
