### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Sandeep-Narahari** [golang/vscode-go#2661]
gopls version: v0.11.0 (go1.19.3)
gopls flags: 
update flags: proxy
extension version: 0.37.1
go version: 1.19.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 12 Feb 2023 16:05:37 GMT
restart history:
Sun, 12 Feb 2023 12:15:17 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by Sandeep-Narahari** [comment]
![Screenshot from 2023-02-22 21-41-29](https://user-images.githubusercontent.com/46187761/220686232-8b835ca4-4b7d-4aae-85c0-54ccde68b6ec.png)

**Comment by adonovan** [comment]
Hi Sandeep, could you provide the Output log? The latest screenshot shows the environment configuration, but not the output of the tool itself. Thanks.

**Comment by hyangah** [comment]
Thanks for the report. If you encounter the same issue, please file a new issue.

Gopls v0.12.0 was released today. Closing obsolete crash reports so we can focus on new crash reports with gopls v0.12.0 promptly.
