### ISSUE TITLE
Breakpoint doesn't work when expression condition uses `call`

### ISSUE THREAD

**Issue by GKilm** [golang/vscode-go#2673]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.4 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.11.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.75.1
	- 441438abd1ac652551dbe4d408dfcec8a499b8bf
	- x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.37.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- GOBIN: undefined
          toolsGopath: 
          gopath: /root/go
          GOROOT: /root/.g/go
          PATH: /root/.g/go/bin:/root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/mnt/d/code/github/cloudpods/_output/bin/:/root/bin:/root/go/bin:/mnt/d/code/github/cloudpods/_output/bin/:/root/bin:/root/go/bin:/opt/rh/rh-postgresql10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
PATH (vscode launched with): /root/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/mnt/d/code/github/cloudpods/_output/bin/:/root/bin:/root/.g/go/bin:/root/go/bin:/mnt/d/code/github/cloudpods/_output/bin/:/root/bin:/root/.g/go/bin:/root/go/bin:/opt/rh/rh-postgresql10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
	go:	/root/.g/go/bin/go: go version go1.18.4 linux/amd64
	gotests:	/root/go/bin/gotests	(version: v1.6.0 built with go: go1.18.4)
	gomodifytags:	/root/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.18.4)
	impl:	/root/go/bin/impl	(version: v1.1.0 built with go: go1.18.4)
	goplay:	/root/go/bin/goplay	(version: v1.0.0 built with go: go1.18.4)
	dlv:	/root/go/bin/dlv	(version: v1.20.1 built with go: go1.18.4)
	staticcheck:	/root/go/bin/staticcheck	(version: v0.3.3 built with go: go1.18.4)
	gopls:	/root/go/bin/gopls	(version: v0.11.0 built with go: go1.18.4)
        go env
        Workspace Folder (cloudpods): /opt/onecloud/cloudpods
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/root/.cache/go-build"
	GOENV="/root/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/root/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/root/go"
	GOPRIVATE=""
	GOPROXY=""
	GOROOT="/root/.g/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/root/.g/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.18.4"
	GCCGO="/usr/bin/gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/opt/onecloud/cloudpods/go.mod"
	GOWORK=""
	CGO_CFLAGS="-g -O2 -I/opt/qemu-2.12 -I/opt/qemu-2.12/include"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2 -laio -lqemuio -lpthread -lgnutls -lnettle -lz -lglib-2.0 -lstdc++ -lm -L /opt/qemu-2.12"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build925510042=/tmp/go-build -gno-record-gcc-switches"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
> none

### Describe the bug
Expression condition with `call` doesn't work when debugged.
Example : `call strings.Contains("12","1")`
Error Info : `1:7: expected 'EOF', found strings`

### Steps to reproduce the behavior:
...

### Screenshots or recordings
![expression](https://user-images.githubusercontent.com/28996322/219993344-985df867-6338-4be9-bff1-ad346625bd4a.png)

![error-info](https://user-images.githubusercontent.com/28996322/219993351-99414759-51c6-48ac-848c-1dcc4b70dcf9.png)

**Comment by adonovan** [comment]
@aarzilli, should this be filed in the Delve issue tracker?

**Comment by aarzilli** [comment]
Already exists: https://github.com/go-delve/delve/issues/1766
