### ISSUE TITLE
gopls: spawns cc1 processes on file save when using imports that use cgo

### ISSUE THREAD

**Issue by elegos** [golang/vscode-go#268]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.3 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.46.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.0
- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/elegos/.cache/go-build"
GOENV="/home/elegos/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/elegos/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build151379296=/tmp/go-build -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
{
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "git.confirmSync": false
}
```

### Describe the bug
Whenever I try to save my go sources that import a dependency which makes use of cgo, the file save is blocked until all the `cc1` instances that have been spawned (using 100% of a thread each) end, which usually takes ~10 seconds

### Steps to reproduce the behavior:
1. write a source which imports "github.com/therecipe/qt/widgets", like this:
```go
package whatever

import (
	"github.com/therecipe/qt/widgets"
)

// InstagoMainWindow the main window
type InstagoMainWindow struct {
	widgets.QMainWindow
}

// BuildInstagoMainWindow generate a new main window
func BuildInstagoMainWindow() InstagoMainWindow {
	mw := InstagoMainWindow{}

	return mw
}
```
2. Save (CTRL+S)
3. Multiple cc1 processes will spawn, temporarely preventing you to save the file (follows a filtered `ps aux` command):

```
elegos      9494  100  0.3  78688 55912 ?        R    09:09   0:25 /usr/libexec/gcc/x86_64-redhat-linux/10/cc1 -quiet -I /tmp/go-build871050079/b035/ -I . /tmp/cgo-gcc-input-836666895.c -quiet -dumpbase cgo-gcc-input-836666895.c -m64 -mtune=generic -march=x86-64 -auxbase-strip /tmp/go-build871050079/b035//_cgo_.o -gdwarf-2 -O0 -Wno-error -w -o /tmp/ccud6fE1.s
elegos      9496  101  0.3  80732 56324 ?        R    09:09   0:25 /usr/libexec/gcc/x86_64-redhat-linux/10/cc1 -quiet -I /tmp/go-build186212497/b035/ -I . /tmp/cgo-gcc-input-162233745.c -quiet -dumpbase cgo-gcc-input-162233745.c -m64 -mtune=generic -march=x86-64 -auxbase-strip /tmp/go-build186212497/b035//_cgo_.o -gdwarf-2 -O0 -Wno-error -w -o /tmp/cc5ImAsa.s
elegos      9882  101  0.3  76604 53680 ?        R    09:09   0:22 /usr/libexec/gcc/x86_64-redhat-linux/10/cc1 -quiet -I /tmp/go-build192614965/b035/ -I . /tmp/cgo-gcc-input-928280638.c -quiet -dumpbase cgo-gcc-input-928280638.c -m64 -mtune=generic -march=x86-64 -auxbase-strip /tmp/go-build192614965/b035//_cgo_.o -gdwarf-2 -O0 -Wno-error -w -o /tmp/ccVYw7oo.s
elegos     10079  100  0.2  71908 48400 ?        R    09:09   0:17 /usr/libexec/gcc/x86_64-redhat-linux/10/cc1 -quiet -I /tmp/go-build052863757/b035/ -I . /tmp/cgo-gcc-input-787651463.c -quiet -dumpbase cgo-gcc-input-787651463.c -m64 -mtune=generic -march=x86-64 -auxbase-strip /tmp/go-build052863757/b035//_cgo_.o -gdwarf-2 -O0 -Wno-error -w -o /tmp/ccv0Umob.s
elegos     10087  102  0.2  69748 45692 ?        R    09:10   0:14 /usr/libexec/gcc/x86_64-redhat-linux/10/cc1 -quiet -I /tmp/go-build611592304/b035/ -I . /tmp/cgo-gcc-input-696381330.c -quiet -dumpbase cgo-gcc-input-696381330.c -m64 -mtune=generic -march=x86-64 -auxbase-strip /tmp/go-build611592304/b035//_cgo_.o -gdwarf-2 -O0 -Wno-error -w -o /tmp/ccoOkvBS.s
```

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
@stamblerre @heschik What is the current status of cgo support in the language server?

My understanding is completely avoiding invocation of cgo tool and c compilation isn't 
possible because it's necessary to extract the type info, but I see various progress and improvement 
has made for https://github.com/golang/go/issues/35720 and https://github.com/golang/go/issues/35721,
and some will require go1.15.

**Comment by stamblerre** [comment]
Heschi can probably speak to this a bit more than I can, but significant progress has been made for users of Go 1.15. `gopls` now has a command to re-run the cgo tool on-demand.

**Comment by heschik** [comment]
For a program that doesn't directly use cgo, cgo compilation should only happen once, but it has to completely finish. Until it does, each save will probably kick off a new compilation process. Note that each of those are running the same compilation step with different working directories.

By now I would expect this to be resolved. If not, please run `go build`, wait for it to finish, and then run it again. The second invocation should be instant, and  gopls should no longer trigger cgo. If not, we can try to investigate further.

**Comment by elegos** [comment]
@heschik it's actually happening for each file which references a file which includes that dependency (i.e. a main.go file that references that InstagoMainWindow.go file). So every time I create a new file it will keep my CPU busy for ~a minute. Though yes, after it finishes it will not spawn cc1 processes anymore. Can't this process, which is highly expensive CPU-wise, be queued and executed asynchronously, so that you can keep on saving and working?

**Comment by heschik** [comment]
Then the most likely explanation is that compilation is failing each time. Have you run `go build`? Can you upload a repro case somewhere?

**Comment by elegos** [comment]
@heschik you can find a repro case here:

- Repository: https://github.com/elegos/instago
- Branch: feature/gui
- Path: source/gui

```bash
git clone git@github.com:elegos/instago.git
cd instago
git checkout feature/gui
pushd source/gui
make setup
popd
code .
```

Then open `source/gui/main.go` and save. Now open `source/gui/ui/MainWindow.go` and save.

**Comment by heschik** [comment]
I have successfully built qt projects before, but this one fails with a missing symbol:
`vendor/github.com/therecipe/qt/core/core-minimal.go:15:42: undefined: NewQByteArrayFromPointer`

I noticed that the `source/gui` folder is a nested module. That is likely to cause problems. Opening the nested module as the workspace directory in VSCode, or using Add Folder to add it to the workspace as a top-level directory, may work better.

You still haven't answered my question. Does `go build` succeed?

**Comment by elegos** [comment]
Hello @heschik 

Yes, `go build` succedes.

As for the submodule, it was not my intention, but apparently the chain tool used to build the solution including the library (provided by the library itself) is cumbersome to say the least and didn't allow me to specify the main package rather than the root of the project. I'll try to make one go module and, if successful, see if there are differences in VSCode.

**Comment by stamblerre** [comment]
@elegos: Were you able to resolve this issue? Is it OK to close this?
