### ISSUE TITLE
cmd

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2681]
Type: <b>Feature Request</b>

Cwd cannot change the running directory

Extension version: 0.37.1
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Connection to 'ssh-remote+175.178.40.128' could not be established

**Comment by adonovan** [comment]
I'm sorry, I can't understand this bug report. Could you provide more detail? Thanks.
