### ISSUE TITLE
Semantic tokens for escape/placeholder characters like %s, %.2f or \n

### ISSUE THREAD

**Issue by RedStylzZ** [golang/vscode-go#2682]
**Is your feature request related to a problem? Please describe.**
I am coming from Goland and tried to modify my VSCode to have a pretty syntax highlighing. It seems like not all semantic tokens have been added, or only as textmate scopes. It seems like escape/placeholder characters like "%s" "%.2f" or "\n" are not captured as semantic tokens and are just seen as "string". I then tried to modify them with the textmate scopes. But it seems like semantic tokens overwrite textmate scopes.

**Describe the solution you'd like**
I would like to have semantic token for these escape/placeholder sequences to highlight them like here:

**Describe alternatives you've considered**
It is possible (if you know some regex) to use the Highlight Extension and try to build a regex to capture these escape sequences.

**Additional context**
Current VSCode token type:
![image](https://user-images.githubusercontent.com/19490975/221127770-5cea2940-e9e5-45d5-a315-3bf5690aa683.png)

Goland example:
![image](https://user-images.githubusercontent.com/19490975/221127832-15e003c7-48b7-4d4b-a080-fefeac98438f.png)

**Comment by pjweinb** [comment]
To enable semantic tokens, but let the underlying string processing show
through,
with these settings in the "gopls" section of settings.json:
"ui.noSemanticNumber": true,
"ui.noSemanticString": true,
"ui.semanticTokens": true,
