### ISSUE TITLE
Why there doesn't have a nil check in vscode for golang?

### ISSUE THREAD

**Issue by yingshaoxo** [golang/vscode-go#2689]
For example, if I define a `*string` variable inside of a class (struct)

Whenever I use it, it will always ask `coder` to check and handle two different situations, one is `it == nil`, another is `it == a string`.

So that in this case, we'll never have to make mistakes with empty values. (Like getting an `nil dereference error`

You can have a look at flutter in vscode to see how they handle None.

**Comment by hyangah** [comment]
@yingshaoxo can you please clarify if this is a question about the language design or a feature request looking for a new type of analyzer? And can you please check the list of analyzers and see if any of them match your need? (for example, `nilness` analyzer is off by default)

I've seen many programs that uses pointer types to express special meaning with the `nil`, so it's not clear to me what type of analysis you want. Example code can be helpful for us to understand what you want.

**Comment by yingshaoxo** [comment]
Hi, @hyangah 

Use `nilness` is probably is a good idea

But the problem is, how can I use it with vscode?

___

Let me make it clear, for the following case, if we use it directly, there has high possibility it will throw errors, because text can be nil

```go
func Test_nil(text *string) {
	println(len(*text))
}
```

But if the analyzer did a nil check, it will force you to write code like the following, so it will always run smoothly without error:

```go
func Test_perfect_nil_handling(text *string) {
	if text == nil {
		// do nothing
	}
	if text != nil {
		println(len(*text))
	}
}
```

**Comment by adonovan** [comment]
The kind of interprocedural nilness analysis that I think you're asking for is something that doesn't currently exist in Go, and generally it requires the programmer to do at least some of the work by annotating places in their code where types are allowed (or not allowed) to be nil. Without annotations, tools tend to produce very high rates of false-positive reports. Go also has weaker construction invariants than other languages such as Java, which can make the problem more challenging. 

In any case, it would be a significant project and we have no plans to do it.

**Comment by hyangah** [comment]
To enable the `nilness` check in gopls, add the followings to the settings.json. 
This `nilness` check is pretty conservative and will not detect the case you mentioned however.

```
"gopls": {
         "ui.diagnostic.analyses": {
            "nilness": true
        }
}
```

Staticcheck offers some nil pointer dereference check https://staticcheck.io/docs/checks/#SA5011 
that is also enabled by default. However, as @adonovan said, the nil check you want is hard to
implement in Go without producing false-positive reports.
