### ISSUE TITLE
Go extension creating pkg folder in non-go projects

### ISSUE THREAD

**Issue by jmhtfiserv** [golang/vscode-go#2694]
This was reported twice before (1695, 1696?) but they have been closed without any meaningful comment.  I wanted to bump this as it is very irritating.  I use many project types beyond Go and when working on them, Go itself isn't even configured for my environment.  For now, I'm manually disabling the extension.

**Comment by hyangah** [comment]
#1695 and #1696 are duplicates filed by the same person, so duplicate.
Please follow the instruction and share the asked info. https://github.com/golang/vscode-go/issues/1696#issuecomment-899497897

This extension itself doesn't create a folder. Based on the name of the folder, I guess that may be related to GOPATH-related settings in your workspace, but there could be other reasons. If you are not using Go, I think disabling the extension is the right choice.

**Comment by jmhtfiserv** [comment]
As you say, disabling it seems the right path.  I configure my environment dynamically, so for non-Go projects, there is no (execution search) path to Go (so **go env GOPATH** returns an error), GOROOT points to v1.20, and GOPATH references a workspace directory for my Golang projects. 
The annoyance, such as it is, is that pkg gets created locally (by whatever mechanism) for a non-go project. Ideally (my ideal), the extension should note that there is no Go (for example, no go.mod) and do nothing.  My reason for posting is just as I noted. I have a lot of tools installed and having to disable them except precisely when wanted is just, well, an irritation. 

However, for the record, as requested (I apologize, I've elided IDs and paths in deference to security, real or imagined):

Go: Locate Configured Go Tools
`	set GO111MODULE=on
	set GOARCH=amd64
	set GOBIN=
	set GOCACHE=C:\Users\...\AppData\Local\go-build
	set GOENV=C:\Users\...\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOEXPERIMENT=
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=<current project directory>\pkg\mod
	set GONOPROXY=<A Git repo>
	set GONOSUMDB=<A Git repo>
	set GOOS=windows
	set GOPATH=<current project directory>;C:\Users\...\Projects\go-workspace\
	set GOPRIVATE=<A Git repo>
	set GOPROXY=https://proxy.golang.org,direct
	set GOROOT=c:\programs\go\go-1.20.0
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=c:\programs\go\go-1.20.0\pkg\tool\windows_amd64
	set GOVCS=
	set GOVERSION=go1.20
	set GCCGO=gccgo
	set GOAMD64=v1
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=0
	set GOMOD=NUL
	set GOWORK=
	set CGO_CFLAGS=-O2 -g
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-O2 -g
	set CGO_FFLAGS=-O2 -g
	set CGO_LDFLAGS=-O2 -g
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\...\AppData\Local\Temp\1\go-build3552624547=/tmp/go-build -gno-record-gcc-switches
`

I do not see any reference to "Preferences: Open Settings" or "Preferences: Open Workspace Settings" in settings.json

`
PS > go env GOPATH
go: The term 'go' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
`
(this latter is because I configure my environments dynamically at the windows level and Go is not configured for this project).
