### ISSUE TITLE
Indicate calls to Deprecated functions

### ISSUE THREAD

**Issue by fedorareis** [golang/vscode-go#2697]
**Is your feature request related to a problem? Please describe.**
Visually indicate when a deprecated function is being used.

**Describe the solution you'd like**
Something similar to other editors (like GoLand) where strikethrough is put over the use of a deprecated function. It might be nice to allow users to customize how this is displayed, but I think starting with a strikethrough is a good starting point.

**Describe alternatives you've considered**
I don't think there are any good alternatives that make the use of deprecated functions obvious to the programmer.

**Additional context**
[Doc comments support a `Deprecated:` section](https://github.com/golang/go/wiki/Deprecated) but there isn't an easy way to tell if something that has been deprecated is being used without reading the documentation or hovering over the function call.

**Comment by findleyr** [comment]
This looks a lot like https://go.dev/issue/40447.

I agree that we should add this. It is one of our most requested features.

**Comment by hyangah** [comment]
If you use `staticcheck` (that's this extension's default 3rd party linter run by "go.lintOnSave" feature, and you can also enable this in gopls by using `"gopls": { "ui.diagnostic.staticcheck": true }`), [SA1019 check](https://staticcheck.io/docs/checks#SA1019) will report this as diagnostic.

We have some ideas to integrate this as a default diagnostic but let's discuss this in the golang/go#40447.
