### ISSUE TITLE
Cannot use k8s controller and get EOF error in VSCode Debug mode. Code works fine in command line.

### ISSUE THREAD

**Issue by so2liu** [golang/vscode-go#2699]
Error message: `Get "https://10.100.13.28:6443/api?timeout=32s": context deadline exceeded - error from a previous attempt: EOF unable to start manager`

`config := ctrl.GetConfigOrDie()` can successfully read config file from `~/.kube/config`

```go
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"k8s.io/apimachinery/pkg/runtime"
	_ "k8s.io/client-go/plugin/pkg/client/auth"

	corev1 "k8s.io/api/core/v1"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

var logger = log.Default()

func createManger() manager.Manager {
	scheme := runtime.NewScheme()
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	config := ctrl.GetConfigOrDie()

	mgr, err := ctrl.NewManager(config, ctrl.Options{
		Scheme:           scheme,
		LeaderElectionID: "e6ceb2e8.aiotos.io",
	})
	if err != nil {
		fmt.Println(err, "unable to start manager")
		os.Exit(1)
	}
	go func() {
		fmt.Println("starting manager")
		if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
			fmt.Println(err, "problem running manager")
			os.Exit(1)
		}
	}()
	time.Sleep(time.Second * 1)
	return mgr
}

func main() {
	fmt.Println("start")
	mgr := createManger()

	podList := &corev1.PodList{}
	if err := mgr.GetClient().List(context.TODO(), podList, client.InNamespace("aiotos-system")); err != nil {
		log.Fatal(err, "List Pod Fail")
	}
	if len(podList.Items) > 0 {
		for _, podItem := range podList.Items {
			println(podItem.Name)
		}
	}

}
```

### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.4 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.18.4
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.76.0
92da9481c0904c6adfe372c12da3b7748d74bdcb
arm64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.38.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- 1.76.0
92da9481c0904c6adfe372c12da3b7748d74bdcb
arm64
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

#### Not working for debug mode
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/9153390/224662441-45b0813b-aa6f-48d6-afa2-2139ce1681a0.png">

#### Works for command line
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/9153390/224662629-a850e093-46f7-4061-89ce-6568b09f4dae.png">

#### Works for Goland IDE debug mode
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/9153390/224662715-b3967d62-c0bf-4c87-811d-bdb2f8cd0300.png">

**Comment by hyangah** [comment]
Does `ctrl.NewManager` require a special token or environment variable to be configured?
(If so, try to configure `env` attribute in the launch.json configuration)

If env var is not an issue, I'd set a breakpoint on line 28, and step into `ctrl.NewManager` to investigate what's going on.

**Comment by so2liu** [comment]
> Does `ctrl.NewManager` require a special token or environment variable to be configured? (If so, try to configure `env` attribute in the launch.json configuration)
> 
> If env var is not an issue, I'd set a breakpoint on line 28, and step into `ctrl.NewManager` to investigate what's going on.

Thank you for your quick reply. K8s controller has successfully read the config from `~/.kube/config`. At breakpoint we can see this. But I am not familiar with k8s and don't know what happened inside... I am hopping anyone familiar with k8s know this strage thing.

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/9153390/224883726-17104007-d6d9-4e8f-9765-b3253c70b61c.png">

**Comment by so2liu** [comment]
Resolved when I update VSCode today mysteriously.
