### ISSUE TITLE
upon file save, none of the format / import actions are applied 

### ISSUE THREAD

**Issue by kslater-sb** [golang/vscode-go#2700]
Type: <b>Bug</b>

open VS code - edit go file save, nothing imports and the dot to the right of file name stays there and loading bar low left loads but does not fill up or ever do the imports

Extension version: 0.38.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:48:08.231Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|13, 38, 31|
|Memory (System)|16.00GB (2.36GB free)|
|Process Argv|--crash-reporter-id 863b365e-a4ba-406b-8fba-e6a9076badeb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hyangah** [comment]
We need more info to triage. Please share your settings, and gopls logs from the beginning (including the `initialize` request) to the point you see file save hang. 

https://github.com/golang/vscode-go/wiki/troubleshooting#collect-extension-logs

Would be very helpful if you can share a repro case too.
