### ISSUE TITLE
About <variable_name>.print! This code snippet

### ISSUE THREAD

**Issue by Byxs20** [golang/vscode-go#2706]
Hi, I am absolutely very smooth on my side when writing code with this plugin, but I am currently experiencing a problem.

Question：
When I type a.print! it automatically generates fmt.Printf("a: %v\n", a)
So I'm going to imitate you and write a code snippet for the variable type
Typing a.type! gets fmt.Printf("a type: %T\n", a)

I tried for a long time to try to find a way to write the code snippet for a.print! but I didn't find it, so I hope you have enough to teach me.

**Comment by jamalc** [comment]
These are code completions powered by the LSP server gopls. Here is an example implementation: http://go.dev/cl/438415 and the issue where it was requested: https://github.com/golang/go/issues/55154. You can file requests for additional completions in the [gopls issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fgopls%3A%20%3Cfill%20this%20in%3E).
