### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by eddwinpaz** [golang/vscode-go#2710]
gopls version: v0.11.0 (go1.20.1)
gopls flags: -tags=e2e
update flags: proxy
extension version: 0.38.0
go version: 1.20.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Tue, 21 Mar 2023 22:15:24 GMT
restart history:
Tue, 21 Mar 2023 22:15:10 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by jamalc** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by hyangah** [comment]
`-tags=e2e`  is not a valid gopls flag.
Please add that in `"go.buildTags"` or `"go.buildFlags"` or `"gopls": { "build.buildFlags": "-tags=e2e" }` depending on your need.

**Comment by hyangah** [comment]
Thanks for the report. If you encounter the same issue, please file a new issue.

Gopls v0.12.0 was released today. Closing obsolete crash reports so we can focus on new crash reports with gopls v0.12.0 promptly.
