### ISSUE TITLE
Support for paths with spaces in Go stacktrace

### ISSUE THREAD

**Issue by matwachich** [golang/vscode-go#2728]
Go extension 0.38.0 on VSConde 1.77.1 on Golang 1.20 Windows 10 x64

When clicking on the filepath in stack trace will not work if that path has spaces, they will be considered as 2 different paths when holding Ctrl+Click

PS: Sorry for not filling all the form, but I think all the info are irrelevant to this simple bug

**Comment by hyangah** [comment]
@matwachich Can you please share a screenshot or repro case? We need to know which stack trace we are talking about here (stack trace appearing in debug UI? TERMINAL? Test Output?) and depending on the location, the problem needs to be handled by VS Code or this extension, or something else.

**Comment by matwachich** [comment]
You are right, sorry.
I'm talking about the terminal panel
![image](https://user-images.githubusercontent.com/1791230/233306761-fdfa7574-e6e3-42dc-b38e-4b281f55f126.png)
