### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by salemarsm** [golang/vscode-go#2729]
gopls version: undefined (undefined)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.12.9
environment: Visual Studio Code win32
initialization error: Error: json: cannot unmarshal object into Go struct field .tagSupport of type bool
issue timestamp: Sun, 09 Apr 2023 13:35:49 GMT
restart history:
Sun, 09 Apr 2023 13:35:41 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by pjweinb** [comment]
The log would be very helpful here. I don't see any TagSupport fields of
type bool in the current version of gopls.

**Comment by hyangah** [comment]
Thanks for the issue report. @salemarsm 
Looks like the system requires newer `go` and `gopls`.
Currently, the go version installed on your machine is 1.12.9, which is no longer supported by the Go project.
Please download the newer version of Go from https://go.dev/dl/ 
Then, follow the extension set up instruction in https://github.com/golang/vscode-go#quick-start

Thanks!
