### ISSUE TITLE
Support check.v1 test suite

### ISSUE THREAD

**Issue by tylfin** [golang/vscode-go#274]
**Is your feature request related to a problem? Please describe.**

This is a feature request to support the [`check.v1`](https://github.com/go-check/check/tree/v1) test suite. It looks like the extension already has a lot of the machinery to do this given the [`stretchr/testify/suite`](https://github.com/golang/vscode-go/blob/master/src/testUtils.ts#L140).

**Describe the solution you'd like**

Auto-detect the `check.v1` test suite and generate the same CodeLens as native Go test functions and `stretchr/testify/suite` test methods.

**Describe alternatives you've considered**

At first, I thought this was a larger change so I attempted to use vscode-go as a base and implement it myself here: github.com/tylfin/vscode-go-check but I realized the changes are so minimal it makes more sense to make these changes upstream.

Another option would be to generalize this part of the code to allow for other test suite packages to plug-in to the VSCode Go extension.

**Additional context**

**Comment by tylfin** [comment]
I'm also happy to work on this if the solution I described is adequate 👍

**Comment by hyangah** [comment]
It looks like a duplicate of https://github.com/golang/vscode-go/issues/111

**Comment by tylfin** [comment]
Thanks @hyangah closing as dup of #111
