### ISSUE TITLE
Ability to lint whole workspace on workspace level events, but only package/file when updating a go file

### ISSUE THREAD

**Issue by seaneagan** [golang/vscode-go#2747]
**Is your feature request related to a problem? Please describe.**

The default lintOnSave=package works well when updating go files, since it performs much better than linting the whole workspace. It would useful to be able to keep this default for this scenario, while linting the entire workspace in other scenarios which can result in in addition/removal of linting issues across the workspace:

1. updating the rule set / severity levels / etc in the linter config file (e.g. .golangci.yaml)
2. updating lintFlags to point to a different config file and/or config settings e.g. --config=my/.golangci-lint.yml
3. cloning/fetching repo changes

**Describe the solution you'd like**

Either or both of:

1. An option, or default behavior, which lints the whole workspace in the above mentioned scenarios.
2. A button to press to lint the whole workspace

**Describe alternatives you've considered**

My current workflow is to temporarily set lintOnSave=workspace anytime i need to update the linter config, and then move it back to the default package after that. But this is quite tedious.

**Comment by findleyr** [comment]
Thanks for the request.

My first impression is that is might be difficult to get this right. Does [`Go: Lint Workspace`](https://github.com/golang/vscode-go/blob/master/docs/commands.md#go-lint-workspace) work for you? That seems like a better option for linting the workspace on-demand.
