### ISSUE TITLE
Compilation errors / no autocompletion with gopls and Go modules

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#275]
This is a general issue to help guide users of the language server, [`gopls`](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).

If you see unexpected error messages, make sure that you are opening your directory at or below the module root (the directory containing the `go.mod` file). You can also open a directory within the module. This is a current limitation of `gopls`, which the `gopls` team are working on addressing.

If you are working with multiple modules, you can use VS Code's [Workspace Folders](https://code.visualstudio.com/docs/editor/multi-root-workspaces) feature. You can add another module to your workspace by selecting File -> Add Folder to Workspace. Note that features will not work across modules.

More context here: https://github.com/golang/go/issues/32394, https://github.com/golang/go/issues/36899.
For further help, see the `gopls` [Troubleshooting Guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md).

**Comment by jcbritobr** [comment]
it doesn't work while using workspaces sometimes. It's frustrating

**Comment by hyangah** [comment]
@jcbritobr Sorry to hear that. Can you please share the gopls trace and the symptom when it doesn't work?  https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs

**Comment by jcbritobr** [comment]
May you help me to know how to get the traces?

Em qua, 15 de jul de 2020 10:34, Hyang-Ah Hana Kim <notifications@github.com>
escreveu:

**Comment by stamblerre** [comment]
@jcbritobr: The link @hyangah shared above (https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs) has an explanation of how to capture `gopls` logs.

**Comment by jcbritobr** [comment]
> 
> 
> @jcbritobr Sorry to hear that. Can you please share the gopls trace and the symptom when it doesn't work? https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs

Can't reproduce it anymore. I'll close for a while, until get the data for you guys.

**Comment by stamblerre** [comment]
This issue should be fixed by the improved error messages in `gopls/v0.6.0`, so I think it can now be closed.
