### ISSUE TITLE
{"ui.semanticTokens": true} affecting syntax highlight

### ISSUE THREAD

**Issue by DevDorrejo** [golang/vscode-go#2752]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.3 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.3
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.77.3
704ed70d4fd1c6bd6342c436f1ede30d1cff4710
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.38.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/IND/wdorrejo/go
GOROOT: /usr/local/go
PATH: /home/IND/wdorrejo/bin/DevTools/pipenv/bin:/home/IND/wdorrejo/bin:/usr/local/bin:/usr/bin:/bin:/home/IND/wdorrejo/bin/DevTools/flutter/bin/:/home/IND/wdorrejo/bin/DevTools/Android/Sdk/platform-tools/:/usr/local/go/bin:/home/IND/wdorrejo/go/bin

	go:	/usr/local/go/bin/go: go version go1.20.3 linux/amd64

	gotests:	/home/IND/wdorrejo/go/bin/gotests	(version: v1.6.0 built with go: go1.20.3)
	gomodifytags:	/home/IND/wdorrejo/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.20.3)
	impl:	/home/IND/wdorrejo/go/bin/impl	(version: v1.1.0 built with go: go1.20.3)
	goplay:	/home/IND/wdorrejo/go/bin/goplay	(version: v1.0.0 built with go: go1.20.3)
	dlv:	/home/IND/wdorrejo/go/bin/dlv	(version: v1.20.2 built with go: go1.20.3)
	staticcheck:	/home/IND/wdorrejo/go/bin/staticcheck	(version: v0.4.3 built with go: go1.20.3)
	gopls:	/home/IND/wdorrejo/go/bin/gopls	(version: v0.11.0 built with go: go1.20.3)

go env
Workspace Folder (Curso profesional de Go - De cero a Master 2023): /home/IND/wdorrejo/OneDrive/System/Learning/Certificaciones/Udemy/Golang/Curso profesional de Go - De cero a Master 2023
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/IND/wdorrejo/.cache/go-build"
	GOENV="/home/IND/wdorrejo/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/IND/wdorrejo/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/IND/wdorrejo/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.20.3"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK=""
	CGO_CFLAGS="-O2 -g"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-O2 -g"
	CGO_FFLAGS="-O2 -g"
	CGO_LDFLAGS="-O2 -g"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2734721213=/tmp/go-build -gno-record-gcc-switches"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

- "go.diagnostic.vulncheck": "Imports"
- "go.logging.level": "verbose",
- "go.liveErrors": { enabled": true }
- "go.inlayHints.compositeLiteralFields": true,
- "go.inlayHints.compositeLiteralTypes": true,
- "go.inlayHints.constantValues": true,
- "go.inlayHints.functionTypeParameters": true,
- "go.inlayHints.parameterNames": true,
- "go.inlayHints.rangeVariableTypes": true,
- "gopls": { "ui.semanticTokens": true    },
- "go.autocompleteUnimportedPackages": true,
- "go.editorContextMenuCommands": {"removeTags": true, "fillStruct": true },

### Describe the bug
_"ui.semanticTokens": true_ not working for fmt verbs, disabling will correctly show the syntax color for the verbs and variables in the print, but will not be an easy read color for the code.

### Steps to reproduce the behavior:
1. add "gopls": { "ui.semanticTokens": true }
2. Look at the code, for i.e. `fmt.Printf("Hi, %s and your age is %d \n", name, age)` 
3. %s %d and \n will have the same color as the normal strings.

### Screenshots or recordings
with: "gopls": { "ui.semanticTokens": false }
![image](https://user-images.githubusercontent.com/7697566/234877315-9c16a0da-9dfe-4d54-8174-dd98a5343e78.png)
with: "gopls": { "ui.semanticTokens": true }
![image](https://user-images.githubusercontent.com/7697566/234877453-f01471c7-a231-4d02-b9fa-49003f036bfa.png)

**Comment by pjweinb** [comment]
Yes, try

      "ui.semanticTokens": true,
      "ui.noSemanticNumber": true,
      "ui.noSemanticString": true,

which doesn't use semantic tokens for numbers or strings.

**Comment by DevDorrejo** [comment]
> "ui.semanticTokens": true, "ui.noSemanticNumber": true, "ui.noSemanticString": true,

thank you very much, this help a lot, at the moment to read the code, this recommendation need to be added in extension description.
