### ISSUE TITLE
Go debugger won't start on M1 Mac with "Failed to launch: could not launch process: EOF"

### ISSUE THREAD

**Issue by ducpx** [golang/vscode-go#2762]
After I upgraded my Mac to Ventura 13.3.1, I can not run golang debug.

.vscode/launch.json

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch file",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "main.go"
        }
    ]
}
```

go version: go version go1.20.2 darwin/arm64

![image](https://user-images.githubusercontent.com/38505126/236592744-a70fd522-13bd-4022-897a-f465399fa8fd.png)

I could run debug successfully before upgrading.

**Comment by jybp** [comment]
Reinstall xcode command line tools:

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by findleyr** [comment]
As @jybp points out, this is usually caused by tools compiled for the wrong architecture. Please try reinstalling.

**Comment by ducpx** [comment]
It works for me. Thanks!

**Comment by findleyr** [comment]
Thanks for following up!
