### ISSUE TITLE
Error with installing go extensions

### ISSUE THREAD

**Issue by mantra20** [golang/vscode-go#2766]
Type: <b>Bug</b>

showing path error when im try to download the golang extensions 

Extension version: 0.38.0
VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.96GB free)|
|Process Argv|C:\\Users\\Administrator\\Desktop\\all\\youtube\\.vscode\\settings.json --crash-reporter-id d377152f-f5f0-4bbf-b435-9434ef60f984|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30730054
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmvfstr:30731969
fixshowwlkth:30730052
showsbindicator:30730056

```

</details>

**Comment by findleyr** [comment]
Hi, which error do you see? Where do you see it?

We need more information to advise on this issue.

**Comment by ed-randall-blk** [comment]
Whenever I start vscode I get a prompt that go tools (goplay) need recompiling:
```
Tools (goplay) need recompiling to work with go version go1.19.8 darwin/amd64

Source: Go (Extension)
```

Clicking "Update tools" then produces the following error:
```
Tools environment: GOPATH=/Users/erandall/go
Installing 1 tool at /Users/erandall/go/bin in module mode.
  goplay

Installing github.com/haya14busa/goplay/cmd/goplay@v1.0.0 FAILED
{
 "code": 1,
 "killed": false,
 "signal": null,
 "cmd": "/usr/local/bin/go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0",
 "stdout": "",
 "stderr": "go: finding module for package github.com/skratchdot/open-golang/open\n../../../go/pkg/mod/github.com/haya14busa/goplay@v1.0.0/cmd/goplay/main.go:11:2: no matching versions for query \"latest\"\n"
}

1 tools failed to install.

goplay: failed to install goplay(github.com/haya14busa/goplay/cmd/goplay@v1.0.0): Error: Command failed: /usr/local/bin/go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0
go: finding module for package github.com/skratchdot/open-golang/open
../../../go/pkg/mod/github.com/haya14busa/goplay@v1.0.0/cmd/goplay/main.go:11:2: no matching versions for query "latest"
 
```

**Comment by hyangah** [comment]
@ed-randall-blk Did you intend to open a new issue? In your case, it looks like the `goplay` tool couldn't get installed because it couldn't get the dependency from the network. Try `go install -v -x github.com/haya14busa/goplay/cmd/goplay@v1.0.0` from the terminal. If it fails, please check your proxy setting or try `GOPROXY=direct go instll -v -x github.com/haya14busa/goplay/cmd/goplay@v1.0.0`.

**Comment by ed-randall-blk** [comment]
Thanks - the second one, worked.
We have a (what I thought was transparent) GOPROXY pointing through a corporate artifactory server like `https://artifactory.corp.domain/artifactory/api/go/goproxy`, which caches libraries on the way through (afaik).

It seems to have an issue with certain libraries though, I'm not sure what is going on between the `v1.0.0` and `latest` there.
