### ISSUE TITLE
Variables and types marked as Undeclared when they are declared in another .go file of the same package

### ISSUE THREAD

**Issue by saulortega** [golang/vscode-go#277]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.14.3 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.46.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.0
- Run `go env` to get the go development environment details
	`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/saul/.cache/go-build"
GOENV="/home/saul/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/saul/go:/home/saul/go/src/algo/Librerias"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build371168830=/tmp/go-build -gno-record-gcc-switches"`

### Describe the bug
A few days ago I was prompted for install the Go extension (I already had it installed and working well, but I clicked in order to maybe update)
After that new installation, it doesn't recognize the variables/types in another file of the same package. They are marked as Undeclared.

### Screenshots or recordings
"Sitio" type defined in sitio.go:

![image](https://user-images.githubusercontent.com/6834676/86248686-d3f67900-bb73-11ea-9379-2d1bf70de8df.png)

Sitio declared in another file:

![image](https://user-images.githubusercontent.com/6834676/86248759-ecff2a00-bb73-11ea-883a-421aac33376b.png)

![image](https://user-images.githubusercontent.com/6834676/86249003-49fae000-bb74-11ea-8e58-20592010c8a8.png)

**Comment by hyangah** [comment]
Thanks for the report @saulortega 
Can you please provide the following details?

* Go related settings: any fields starting with `"go"`, `"[go]"`, `"gopls"` from `Preferences: Open Settings (JSON)` and `Preferences: Open Workspace Settings (JSON)` commands.

* Where your source files located (the directory structure relative to your `GOPATH` directory).

* If `"go.useLanguageServer": true`, set
```
"go.languageServerFlags": [
  "-rpc.trace"
]
```
and capture the traces from `gopls (server)` Output channel.

**Comment by saulortega** [comment]
I'm not sure where is that menu. The closest is this:

![image](https://user-images.githubusercontent.com/6834676/86250820-b24ac100-bb76-11ea-8dae-f644c9b52a3c.png)

The files are out of GOPATH. Is that the reason?

**Comment by hyangah** [comment]
@saulortega You can select commands from the Command Palette (Ctrl+Shift+P)  https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette

The project should be under `GOPATH/src` if you work in the GOPATH mode (not the modules mode).

You can install the previous extension version following this instruction https://code.visualstudio.com/updates/v1_30#_install-previous-versions

**Comment by saulortega** [comment]
Ok.

```
"go.formatTool": "goimports",
"go.useLanguageServer": true
```

I added this:

```
"go.languageServerFlags": [
	"-rpc.trace"
]
```

But, I dont know how to do the traces from gopls.

**Comment by saulortega** [comment]
Oh, and there are no other versions availble of the extension, so it's not possible.

**Comment by hyangah** [comment]
@saulortega If you are using the language server and your project is outside the GOPATH (assuming you are working in GOPATH mode - i.e. no `go.mod` file in the project root), that's the culprit. 

The traces is in the `gopls (server)` item from OUTPUT window. 
Command Palette (Ctrl+Shift+P) -> `View: Toggle Output`, then select the 'gopls (server)'

**Comment by hyangah** [comment]
To install the previous version (more than a month old code base, so I guess that's sufficient for testing),
visit https://github.com/golang/vscode-go/releases/tag/v0.14.4 and download the vsix file. 
From the Command Palette again, choose the "Extensions: Install from VSIX" command and provide the donwloaded vsix file.

**Comment by saulortega** [comment]
What is "language server"?

The project is outside the GOPATH. I'm using go.mod in the root (it can be seen in the last image I uploaded above (bottom left)).

The output is large. Here a small part:

![image](https://user-images.githubusercontent.com/6834676/86257150-cd213380-bb7e-11ea-8390-260d60d1598e.png)


When I click on Install Another Version:

![image](https://user-images.githubusercontent.com/6834676/86256177-9dbdf700-bb7d-11ea-8bb9-851f64ecb62a.png)

Thank you, I will follow that last instructions.

**Comment by hyangah** [comment]
It seems like the VS Code's "Install another version" feature doesn't work for our extension for now. I filed https://github.com/microsoft/vscode/issues/101509

Language server is the one that compute intellisense, and Go program analysis. https://github.com/golang/vscode-go#language-server 

From your original report, I see `GOMOD=""` which indicates there is no `go.mod` file in the directory where you ran `go env`. So, I assumed you were not using the modules mode.

If you are using the modules mode, check the pinned issue https://github.com/golang/vscode-go/issues/275 explaining the current limitation depending on how the repository is origanized. 

If the previous version works, let us know.

**Comment by saulortega** [comment]
Well, y ran that outside of my work directory. Here is `go env` again inside work directory:

`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/saul/.cache/go-build"
GOENV="/home/saul/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/saul/go:/home/saul/go/src/algo/Librerias"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/saul/repositorios/sitios/servidor/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build843390947=/tmp/go-build -gno-record-gcc-switches"`

The previous version doesn't work.

**Ok, I realized the checks work fine when I open VS Code from my Go code's root directory.**  I was opening it one level above, same as the `go env`. I have in my repository two directories: One for backend in Go, and another for frontend in Javascript.

**Comment by hyangah** [comment]
@saulortega Thanks for the update. Yes, currently, the workspace root and the module root need to be aligned when working in modules mode. https://github.com/golang/vscode-go/issues/275 describes a workaround. We hope to be fixed in the future releases of the language server (`gopls`). 

I will close this issue because we already have open cases for this problem.
--
BTW if the frontend/backend are developed/released together, it's not a bad idea to place go.mod at the root of the repo. By placing `go.mod` in a directory that's not the root of the repo, you are creating a multi-module repository (the repo root is a module too). In many cases, we observed multi-module repositories need a lot more care. For details about maintaining multi-module repositories, see https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories
