### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ranlee2** [golang/vscode-go#2776]
gopls version: v0.11.0 (go1.18.3)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.18.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 17 May 2023 18:40:03 GMT
restart history:
Wed, 17 May 2023 18:39:32 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Not sure what happened. I was writing code and then saw a pop-up saying "Connection to server got closed. Server will not be restarted". One of obvious malfunction as a result is hovering the mouse over functions doesn't do anything.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 11:39:47 AM] 
[Info  - 11:39:48 AM] 2023/05/17 11:39:48 go env for /local/ranlee2/ws/caelumfork
(root /local/ranlee2/ws/caelumfork/caelum)
(go version go version go1.18.3 linux/amd64)
(valid build configuration = true)
(build flags: [])
GOPROXY=https://proxy.golang.org,direct
GOWORK=
GOCACHE=/home/ranlee2/.cache/go-build
GO111MODULE=
GOPRIVATE=
GOROOT=/usr/local/go
GOSUMDB=sum.golang.org
GOPATH=/home/ranlee2/go
GOFLAGS=
GONOPROXY=
GOMOD=/dev/null
GONOSUMDB=
GOMODCACHE=/home/ranlee2/go/pkg/mod
GOINSECURE=

[Info  - 11:39:50 AM] 2023/05/17 11:39:49 go/packages.Load #1
	snapshot=0
	directory=file:///local/ranlee2/ws/caelumfork
	query=[aci-github.cisco.com/nexusdash/cloudsvc/caelum/... builtin]
	packages=29

[Info  - 11:39:50 AM] 2023/05/17 11:39:50 go/packages.Load #1: updating metadata for 695 packages

panic: runtime error: slice bounds out of range [:3266] with capacity 3265

goroutine 11702 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.fixArrayType(0xc00060e840, {0x10a2958, 0xc000c59c00}, 0x0?, {0xc003c8a880, 0x50e04e?, 0xcc1})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:996 +0x31c
golang.org/x/tools/gopls/internal/lsp/cache.fixAST.func1({0x10a23e0?, 0xc00060e840?}, {0x10a2958?, 0xc000c59c00})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:568 +0x23f
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent.func1({0x10a23e0?, 0xc00060e840?})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:628 +0xbe
go/ast.inspector.Visit(0xc00427a660, {0x10a23e0?, 0xc00060e840?})
	/usr/local/go/src/go/ast/walk.go:387 +0x31
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a23e0?, 0xc00060e840?})
	/usr/local/go/src/go/ast/walk.go:52 +0x62
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a2958?, 0xc000c59c00?})
	/usr/local/go/src/go/ast/walk.go:241 +0x1208
go/ast.walkStmtList({0x10a0ee0, 0xc00427a660}, {0xc000c59c40?, 0x3, 0x10a6890?})
	/usr/local/go/src/go/ast/walk.go:32 +0x91
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a24d0?, 0xc004b4cb70?})
	/usr/local/go/src/go/ast/walk.go:235 +0x10e5
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a27f0?, 0xc000c59c80?})
	/usr/local/go/src/go/ast/walk.go:286 +0x953
go/ast.walkStmtList({0x10a0ee0, 0xc00427a660}, {0xc001807200?, 0x9, 0x10a6890?})
	/usr/local/go/src/go/ast/walk.go:32 +0x91
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a24d0?, 0xc004b4cba0?})
	/usr/local/go/src/go/ast/walk.go:235 +0x10e5
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a2840?, 0xc0048bc960?})
	/usr/local/go/src/go/ast/walk.go:100 +0x1c36
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a2520?, 0xc000c59dc0?})
	/usr/local/go/src/go/ast/walk.go:144 +0xa65
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a28b8?, 0xc0048bc610?})
	/usr/local/go/src/go/ast/walk.go:221 +0x695
go/ast.walkStmtList({0x10a0ee0, 0xc00427a660}, {0xc0039ae180?, 0x5, 0xc0042eee10?})
	/usr/local/go/src/go/ast/walk.go:32 +0x91
go/ast.Walk({0x10a0ee0?, 0xc00427a660?}, {0x10a24d0?, 0xc004b4c300?})
	/usr/local/go/src/go/ast/walk.go:235 +0x10e5
go/ast.Inspect(...)
	/usr/local/go/src/go/ast/walk.go:399
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent({0x10a24d0?, 0xc004b4c300?}, 0xc0042eee10?)
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:611 +0xac
golang.org/x/tools/gopls/internal/lsp/cache.fixAST({0x10a6890?, 0xc0045de7e0}, {0x10a24d0, 0xc004b4c300}, 0xc002c51aa0, {0xc003c8a880, 0xcc1, 0xcc1})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:557 +0x147
golang.org/x/tools/gopls/internal/lsp/cache.fixAST.func1({0x10a2408?, 0xc0006d6f30?}, {0x10a24d0?, 0xc004b4c300})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:562 +0x1af
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent.func1({0x10a2408?, 0xc0006d6f30?})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:628 +0xbe
go/ast.inspector.Visit(0xc00427a480, {0x10a2408?, 0xc0006d6f30?})
	/usr/local/go/src/go/ast/walk.go:387 +0x31
go/ast.Walk({0x10a0ee0?, 0xc00427a480?}, {0x10a2408?, 0xc0006d6f30?})
	/usr/local/go/src/go/ast/walk.go:52 +0x62
go/ast.walkStmtList({0x10a0ee0, 0xc00427a480}, {0xc0039ae180?, 0x5, 0x10a6890?})
	/usr/local/go/src/go/ast/walk.go:32 +0x91
go/ast.Walk({0x10a0ee0?, 0xc00427a480?}, {0x10a24d0?, 0xc004b4c300?})
	/usr/local/go/src/go/ast/walk.go:235 +0x10e5
go/ast.Walk({0x10a0ee0?, 0xc00427a480?}, {0x10a2818?, 0xc004b4c3c0?})
	/usr/local/go/src/go/ast/walk.go:358 +0x4b0
go/ast.walkDeclList({0x10a0ee0, 0xc00427a480}, {0xc0043fbe80?, 0x8, 0xc0042eec30?})
	/usr/local/go/src/go/ast/walk.go:38 +0x91
go/ast.Walk({0x10a0ee0?, 0xc00427a480?}, {0x10a27c8?, 0xc0039ae200?})
	/usr/local/go/src/go/ast/walk.go:367 +0x1890
go/ast.Inspect(...)
	/usr/local/go/src/go/ast/walk.go:399
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent({0x10a27c8?, 0xc0039ae200?}, 0xc0042eec30?)
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:611 +0xac
golang.org/x/tools/gopls/internal/lsp/cache.fixAST({0x10a6890?, 0xc0045de7e0}, {0x10a27c8, 0xc0039ae200}, 0xc002c51aa0, {0xc003c8a880, 0xcc1, 0xcc1})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:557 +0x147
golang.org/x/tools/gopls/internal/lsp/cache.parseGoImpl({0x10a67e8, 0xc001844f00}, 0xd35cc0?, {0x10a6af8, 0xc00055ca10}, 0x2)
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:195 +0x9a5
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).ParseGo.func1({0x10a67e8?, 0xc001844f00?}, {0xe1be00?, 0xc0025e86e0?})
	/home/ranlee2/go/pkg/mod/golang.org/x/tools/gopls@v0.11.0/internal/lsp/cache/parse.go:63 +0x59
golang.org/x/tools/internal/memoize.(*Promise).run.func2.1()
	/home/ranlee2/go/pkg/mod/golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8/internal/memoize/memoize.go:187 +0xa9
runtime/trace.WithRegion({0x10a67e8?, 0xc001844f00?}, {0xc0014eec40, 0x1a}, 0xc000687f90)
	/usr/local/go/src/runtime/trace/annotation.go:141 +0xe3
golang.org/x/tools/internal/memoize.(*Promise).run.func2()
	/home/ranlee2/go/pkg/mod/golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8/internal/memoize/memoize.go:180 +0x145
created by golang.org/x/tools/internal/memoize.(*Promise).run
	/home/ranlee2/go/pkg/mod/golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8/internal/memoize/memoize.go:179 +0x1d0
[Error - 11:39:51 AM] Connection to server got closed. Server will not be restarted.

Failed to auto-collect gopls trace: incomplete panic trace.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
This looks like it might be the same issue as #2574, though this crash is with go 1.18.3 and the previous issue was with go 1.17.13. 

cc @findleyr

**Comment by hyangah** [comment]
golang/go#2574 recommends upgrading to go1.19 or newer. 
@ranlee2  can you please try to upgrade to the newer version of go (the latest is 1.20.x and we are expecting 1.21 in a couple of months) and see if the problem is fixed? Thanks!
