### ISSUE TITLE
Allow PKG_CONFIG_PATH in settings.json to be seen by go.tools

### ISSUE THREAD

**Issue by onthegit** [golang/vscode-go#2784]
PKG_CONFIG_PATH in settings.json  in "go.toolsEnvVars" is not picked up by gopls from vscode.

workaround discussed here:
https://github.com/asticode/go-astiav/issues/24

**Comment by hyangah** [comment]
The example in the original report in asticode/go-astiav#24 uses `${workspaceFolder}`.

```
{
  "go.toolsEnvVars": {
    "CGO_ENABLED": "1",
    "CGO_LDFLAGS": "-L${workspaceFolder}/tmp/n5.1.2/lib",
    "CGO_CXXFLAGS": "-I${workspaceFolder}/tmp/n5.1.2/include",
    "PKG_CONFIG_PATH": "${workspaceFolder}/tmp/n5.1.2/lib/pkgconfig",
  },
}
```

Do you observe the same issue when using absolute paths (without the vscode variable syntax)?
(Related: https://github.com/microsoft/vscode/issues/2809)

**Comment by onthegit** [comment]
It does not work when setting PKG_CONFIG_PATH with absolute or not.

**Comment by hyangah** [comment]
@onthegit Unfortunately, I couldn't reproduce the issue. I see the extension start the gopls process with the provided environment variables as expected.

You can check what environment variables are passed to gopls by either wrapping gopls in a shell script which also prints out the environment variables to stderr, or by building a gopls with the following patch:

```
diff --git a/gopls/main.go b/gopls/main.go
index 41c7cdbff8..93fe2eb07c 100644
--- a/gopls/main.go
+++ b/gopls/main.go
@@ -15,7 +15,9 @@ package main // import "golang.org/x/tools/gopls"
 
 import (
        "context"
+       "fmt"
        "os"
+       "strings"
 
        "golang.org/x/tools/gopls/internal/hooks"
        "golang.org/x/tools/gopls/internal/lsp/cmd"
@@ -24,5 +26,7 @@ import (
 
 func main() {
        ctx := context.Background()
+       fmt.Fprintf(os.Stderr, "environment: %v\n", strings.Join(os.Environ(), "\n"))
+
        tool.Main(ctx, cmd.New("gopls", "", nil, hooks.Options), os.Args[1:])
 }
 ```

That will print the environment variables in the `gopls (server)` Output Channel. 
Even I see the `${workspaceFolder}` variables are correctly replaced.


CGO_ENABLED=1
CGO_LDFLAGS=-L/Users/hakim/projects/vscode-go/tmp/n5.1.2/lib
CGO_CXXFLAGS=-I/Users/hakim/projects/vscode-go/tmp/n5.1.2/include
PKG_CONFIG_PATH=/Users/hakim/projects/vscode-go/tmp/n5.1.2/lib/pkgconfig
[Trace - 20:17:21.590 PM] Sending request 'initialize - (0)'.
```
