### ISSUE TITLE
Disable auto format on typing

### ISSUE THREAD

**Issue by lrstolk** [golang/vscode-go#2788]
**Is your feature request related to a problem? Please describe.**
I installed go on vscode. I've searched in the settings and online for a few hours, cant seem to find anything to stop this "annoying" formatting on typing. I cant use enters or backspaces. 

**Describe the solution you'd like**
I want this formatting off. There should be better and more clear options for this. Why would you want this by default? 

**Describe alternatives you've considered**
More clear options and off by default. 

**Additional context**
[video](https://github.com/golang/vscode-go/assets/35999180/40c5c07c-5b5c-4ae0-9b43-b5fcaf4aba2b)

**Comment by findleyr** [comment]
Hi can you share your `settings.json`? Can you

By default, the extension should not behave this way, and indeed does not behave this way for me. My first guess is that perhaps there is some bad interaction of auto-saving and auto-formatting.

Another possibility is that there is another extension that is fighting with gopls. Do you have any other extensions installed that may interact with Go files?

**Comment by lrstolk** [comment]
> Hi can you share your `settings.json`?
> 
> By default, the extension should not behave this way, and indeed does not behave this way for me. My first guess is that perhaps there is some bad interaction of auto-saving and auto-formatting.
> 
> Another possibility is that there is another extension that is fighting with gopls. Do you have any other extensions installed that may interact with Go files?

I changed the setting.json to this: 
<details><summary><code>settings.json</code> Output</summary><br><pre>
{
    "terminal.integrated.shell.windows": "C:/WINDOWS/system32/cmd.exe",
    // "terminal.integrated.cwd": "C:/esp/esp-adf/esp-idf/",
    // "terminal.integrated.shellArgs.windows": [
    //     "/k",
    //     "C:/Users/LRSPC/.espressif/idf_cmd_init.bat",
    //     "C:/Users/LRSPC/AppData/Roaming/Python/Python37",
    //     "C:/Program Files/Git/cmd/",
    // ],
    "terminal.integrated.env.windows": {
    "CHERE_INVOKING": "1",
    "CURR_PATH": "${fileDirname}",
    },
    "cmake.configureOnOpen": true,
    "C_Cpp.updateChannel": "Insiders",
    "C_Cpp.autoAddFileAssociations": false,
    "diffEditor.ignoreTrimWhitespace": true,
    "go.toolsEnvVars": {
    },

    "[go]": { 
        "editor.formatOnSave": false, 
        // "editor.formatOnType": true, 
        // "editor.formatOnPaste": false,
        // "editor.formatOnSaveMode": true,
        // "editor.defaultFormatter": null,
        // "editor.foldingImportsByDefault": false, 
        "editor.codeActionsOnSave": {
            "source.organizeImports": false,
            "source.fixAll": true,
            "source.formatOnPaste": false, 
            "source.formatting": true
        }, 
    },
    "files.autoSave": "off"
}
</pre></details>

But now I cant use Ctrl Shift I to format. I want one of the two options to format with: the shortkey/shortcut or by saving. But now none work. If I put "editor.formatOnSave" to true, instead of false. I have the same issue as seen in the video.

**Comment by hyangah** [comment]
@lrstolk I don't know if you are using a custom keyboard binding. If you are using the default key bindings, "shift+alt+f" is document formatting and "shift+alt+o" is organize imports. (Preferences: Open Default Keyboard Shortcuts)

```
{ "key": "shift+alt+f",
  "command": "editor.action.formatDocument",
  "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly && !inCompositeEditor"},
{ "key": "shift+alt+o", 
  "command": "editor.action.organizeImports",
  "when": "textInputFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)source\\.organizeImports\\b/" },
```

I see that the keybindings work as expected with the settings you shared in https://github.com/golang/vscode-go/issues/2788#issuecomment-1569776850 If not, can you capture the gopls log following the instruction and share it with us? If editor works, we should be able to see the relevant code action request/response messages exchanged as you press the keys.
