### ISSUE TITLE
More problems appear on the problems panel than on golangci-lint output

### ISSUE THREAD

**Issue by pipe01** [golang/vscode-go#279]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.1 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.46.1
cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.0
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/pipe/.cache/go-build"
GOENV="/home/pipe/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/MouseHatGames"
GONOSUMDB="github.com/MouseHatGames"
GOOS="linux"
GOPATH="/home/pipe/go"
GOPRIVATE="github.com/MouseHatGames"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/media/pipe/****/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build173731856=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

```json
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--config=${workspaceFolder}/../.golangci.yml",
    ],
```

### Describe the bug
When running golangci-lint through a terminal it comes back with 1 error, this can also be seen in VS Code's Go extension output:
![golangci-lint issue](https://user-images.githubusercontent.com/3885705/86360613-e73c3e00-bc72-11ea-87ba-5853e7243921.png)

However, in the problems panel and in the code editor itself there are two more errors reported, both of which I have excluded in the .golangci.yml file:

```yaml
issues:
  exclude-rules:
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"
```

**Comment by hyangah** [comment]
@pipe01 Thanks for the report. It looks like the diagnostics came from the language server (`gopls`).

You can configure gopls's analysis settings (https://github.com/golang/tools/blob/master/gopls/doc/settings.md#analyses-mapstringbool) like 
```
"gopls": {
   "analyses": {
        "composites": false,
       ...
   }
}
```

Or you can disable diagnostics from `gopls` completely

```
"go.languageServerExperimentalFeatures": {
        "diagnostics": false
}
```

**Comment by pipe01** [comment]
That works, thank you!
