### ISSUE TITLE
Can't hit breakpoint with a Remote-SSH session

### ISSUE THREAD

**Issue by ColinRegal** [golang/vscode-go#2793]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.18.10 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.12.0
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.78.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.38.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- I can't provide all these information but if you need a specific detail, don't hesitate to ask me.
</details>

### Describe the bug
The breakpoint of my debugger doesn't work with my Remote-SSH session.

At first, the error was "could not find file" then I added a "substiturePath". Now my error is "breakpoint 1 can not be enabled".

You can see below my launch.json.
![cap3](https://github.com/golang/vscode-go/assets/90198526/ef194da0-5334-4e77-91e6-c679e0bb714f)

### Steps to reproduce the behavior:
1. Add a random breakpoint reachable
![cap1](https://github.com/golang/vscode-go/assets/90198526/d1e14008-77c0-48d8-8d71-3906950545a4)
2.  Press F5 or click on Start debugging
3. The debug session runs normally but the breakpoint is not working 
![cap2](https://github.com/golang/vscode-go/assets/90198526/c1b0b8be-caf2-44c4-9cc8-ea57ba3399d1)

**Comment by findleyr** [comment]
Sorry for the slow response.

Setting "substitutePath".To to `""` is not going to work. What are you trying to do?

**Comment by ColinRegal** [comment]
With a clear head, it doesn't make sense but remember why I set  "substitutePath".To to "". I had the error "could not find file" that a lot of issue talks about but I didn't succeeded to solve my problem with the help of all of them after hours. So I probably tried this a bit randomly and the error changed and obviously, there was no topics about this error because it has no sense. 
I haven't solve the problem yet, but this is no longer a problem for me, I'm working on a VM and the debugger works perfectly.

**Comment by findleyr** [comment]
Thanks.

@hyangah @suzmue any other ideas as to what this could be?

**Comment by findleyr** [comment]
Gentle ping: any guidance here would be appreciated.

**Comment by hyangah** [comment]
"from" should be the local path part to be replaced with "to".  The current launch configuration suggests stripping out the file name (from is the full path of the file).

[substitutePath](https://github.com/golang/vscode-go/wiki/debugging#launchjson-attributes): 
"An array of mappings from a local path (editor) to the remote path (debugee). This setting is useful when working in a file system with symbolic links, running remote debugging, or debugging an executable compiled externally. The debug adapter will replace the local path with the remote path in all of the calls."

https://github.com/golang/vscode-go/wiki/debugging#my-program-does-not-stop-at-breakpoints
