### ISSUE TITLE
GO executable file path needs to support configurable

### ISSUE THREAD

**Issue by CongAn** [golang/vscode-go#2812]
## **Is your feature request related to a problem? Please describe.**

When my Golang language environment uses a very common installation path, I get `The argument' file 'cannot be empty Received ''` error.

I spent several hours and finally realized that I could debug the source code before finding the reason.

In the plugin code `dist/debugAdapter. js:15635` line, the code is as follows:

```js
const defaultPathsForGo = process.platform === "win32" ? ["C:\\Program Files\\Go\\bin\\go.exe", "C:\\Program Files (x86)\\Go\\bin\\go.exe"] : ["/usr/local/go/bin/go", "/usr/local/bin/go"];
```
The code forcibly specifies installation and only throws an error, without any prompt that the go executable file was not found.

## **Describe the solution you'd like**
I hope to add configuration items to the go executable file instead of being written dead in the code. 
And provide a boot prompt when the go executable cannot be found.

## **Describe alternatives you've considered**
Currently, I have softwired the go executable file to `/usr/local/bin/go`.

------

## Chinese original text

 **Is your feature request related to a problem? Please describe.**
当我的golang语言环境是非常用安装路径时，会得到 `The argument 'file' cannot be empty. Received ''` 的错误。
我花费了数个小时，最后想起来可以debug源码，才找到了原因。
在插件代码 `dist/debugAdapter.js:15635` 行，其代码如下：
```js
const defaultPathsForGo = process.platform === "win32" ? ["C:\\Program Files\\Go\\bin\\go.exe", "C:\\Program Files (x86)\\Go\\bin\\go.exe"] : ["/usr/local/go/bin/go", "/usr/local/bin/go"];
```
代码强制指定了安装，并且只会抛出错误，并且没有任何go可以执行文件未找到的提示。

**Describe the solution you'd like**
希望增加go可执行文件的配置项，而非写死在代码中。并且在找不到go可执行文件时给出引导提示。

**Describe alternatives you've considered**
目前我把go可执行文件软连接到了`/usr/local/bin/go`。

**Comment by hyangah** [comment]
@CongAn Can you tell us more about your settings.json and launch.json , and when you saw the error message? (screenshot is also welcome)

The extension by default does not use `debugAdapter.js` (aka legacy debug adapter) but directly communicates with Delve using DAP. (We are keeping this code for users who have issues with the new debug adapter, and the code shouldn't be relevant in most case).
