### ISSUE TITLE
Failed to install 'golang.go' in macOS 10.15.5

### ISSUE THREAD

**Issue by HUANGChaoLi** [golang/vscode-go#282]
### Version of Go, VS Code & VS Code Go extension
- Run `go version` to get version of Go
	- go version go1.14.4 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.46.1 cd9ea6488829f560dc949a8b2fb789f3cdc05f5d x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.0
- Run `go env` to get the go development environment details
```
O111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/quinze/Library/Caches/go-build"
GOENV="/Users/quinze/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/quinze/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kh/4k0_w5k91r9cjxtxss9gj7g80000gn/T/go-build165314202=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Describe the bug
I updated to the latest macOS system version, and then the go plug-in will not work. I reinstalled vscode and found that the go plug-in cannot be installed, but python and other plug-ins can still be installed.

### Steps to reproduce the behavior:
1. search for go extension
2. install

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/13926164/86510237-94a08480-be20-11ea-80a4-85a5e46aa3ce.png)

**Comment by HUANGChaoLi** [comment]
Manual installation is also unresponsive

**Comment by hyangah** [comment]
@HUANGChaoLi Do you see any error messages from (Command Palette -> View: Toggle Output -> Log (Extension Host) from the dropdown menu on the top right corner of the output panel)?

Also, have you tried to delete the installed extension from `$HOME/.vscode/extensions/golang.go-0.15.0` and reinstall it?

**Comment by HUANGChaoLi** [comment]
Thanks! the way to remove the directory `$HOME/.vscode/extensions/golang.go-0.15.0` is work, but it gets error when i delete the directory `$HOME/.vscode/extensions/golang.go-0.15.0/node_modules/json-schema`. Maybe this is why i fail to install the go extension! 

there are some infos about the error:
```
rm: /Users/quinze/.vscode/extensions/golang.go-0.15.0/node_modules/json-schema: Directory not empty
rm: /Users/quinze/.vscode/extensions/golang.go-0.15.0/node_modules: Directory not empty
rm: /Users/quinze/.vscode/extensions/golang.go-0.15.0: Directory not empty
```

**Comment by HUANGChaoLi** [comment]
I tried many ways to delete this folder but they all failed, why? Is there any way you know about this?
