### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by chase-allen-tech** [golang/vscode-go#2843]
gopls version: v0.12.3 (go1.20.4)
gopls flags: 
update flags: proxy
extension version: 0.39.0
go version: 1.20.4
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 23 Jun 2023 07:40:58 GMT
restart history:
Fri, 23 Jun 2023 07:22:23 GMT: activation (enabled: true)
Fri, 23 Jun 2023 07:28:03 GMT: config change (enabled: true)
Fri, 23 Jun 2023 07:29:00 GMT: manual (enabled: true)
Fri, 23 Jun 2023 07:29:58 GMT: manual (enabled: true)
Fri, 23 Jun 2023 07:30:57 GMT: manual (enabled: true)
Fri, 23 Jun 2023 07:34:11 GMT: manual (enabled: true)
Fri, 23 Jun 2023 07:36:35 GMT: manual (enabled: true)
Fri, 23 Jun 2023 07:37:53 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Aggregating into #2847. Please do share the fatal log message if you can.
