### ISSUE TITLE
Go Extension not working or importing packages

### ISSUE THREAD

**Issue by Fishyva** [golang/vscode-go#2858]
### What version of Go, VS Code & VS Code Go extension are you using?
go version go1.20.5 darwin/arm64 vs code 1.79.2  go extension v0.39.0
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited
I haven't added or edited any settings
Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

The bug is your extension is not working at all ! 

### Steps to reproduce the behavior:
3. See error
There is no steps your extension is just not working. When I had my old computer the extension would auto suggest packages but as you can see now nothing is happening no auto suggestions. I'm not even able to get imported packages after saving :/
### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="1704" alt="Screenshot 2023-07-01 at 1 55 51 AM" src="https://github.com/golang/vscode-go/assets/97076661/2cffbb23-371e-47b8-aac9-22c4f11db96f">

**Comment by hmtrii** [comment]
I faced the same problem. Any idea?

**Comment by findleyr** [comment]
Hi, please share your gopls version information?

```
gopls -v version
```

Do you have a `go.work` file? The error message in that notification indicates that you do, but that it is empty or malformed.
