### ISSUE TITLE
Deprecate "Go: Extract to variable/function" command (obsolete by gopls's code action)

### ISSUE THREAD

**Issue by benclauss** [golang/vscode-go#2862]
**Is your feature request related to a problem? Please describe.**
I would like to be able to extract a value to a `const`. I can only extract to a variable.

![Screenshot 2023-07-06 at 10 55 38 AM](https://github.com/golang/vscode-go/assets/53198018/96bc3d51-ed7f-43f9-93d1-35fd7cfe1ca3)

![Screenshot 2023-07-06 at 10 55 54 AM](https://github.com/golang/vscode-go/assets/53198018/7766e21d-2652-4966-ab19-289d708e22c6)

**Describe the solution you'd like**
`Go: Extract to const`

**Describe alternatives you've considered**
N/A

**Comment by findleyr** [comment]
Thanks.

Not sure if this belongs in VS Code or gopls issue tracker, but this is a useful feature suggestion (and should be easy to implement, given that we already support extracting to variable).

**Comment by findleyr** [comment]
@hyangah if I'm reading the source correctly this command still uses godoctor? Is that right? We should use gopls instead.

**Comment by hyangah** [comment]
Yes, the Extract to variable/function commands still use godoctor.
We need equivalent gopls commands (takes the current cursor position, and new variable/const/function names).

**Comment by hyangah** [comment]
@benclauss I filed https://github.com/golang/go/issues/63852 for the followup. In cl/5387566, we are moving the "Go: Extract to variable" and "Go: Extract to function" vscode commands. Equivalent functionalities are currently available through code action. How important is it in your workflow to access them through the vscode command interface?

To access the gopls-based extract features, you can either find the light bulb, or use refactoring context menu or key bindings https://code.visualstudio.com/docs/getstarted/keybindings#_custom-keybindings-for-refactorings. If they are not as convenient, we can consider to add back the "Go: Extract to variable/function" commands interface to minimize disruption.

**Comment by hyangah** [comment]
Sorry for using this feature request (extending a legacy feature) for deprecating the legacy feature. I hope we can get to golang/go#63842. Please follow the issue. Thanks!
