### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zhu13818202655** [golang/vscode-go#2865]
gopls version: v0.12.2 (go1.20.5)
gopls flags: 
update flags: local
extension version: 0.38.0
go version: 1.20.5
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 11 Jul 2023 13:30:23 GMT
restart history:
Tue, 11 Jul 2023 13:29:08 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, please upgrade gopls to gopls@v0.12.4. There were a couple crashes in v0.12.2 that have since been fixed.
