### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by golfxiao** [golang/vscode-go#2881]
gopls version: v0.12.4 (go1.20.2)
gopls flags: --remote=off
update flags: proxy
extension version: 0.39.1
go version: 1.20.2
environment: Visual Studio Code darwin
initialization error: Error: write EPIPE
issue timestamp: Thu, 20 Jul 2023 06:42:14 GMT
restart history:
Thu, 20 Jul 2023 06:28:43 GMT: activation (enabled: true)
Thu, 20 Jul 2023 06:41:12 GMT: config change (enabled: true)
Thu, 20 Jul 2023 06:41:52 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by jamalc** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
