### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by Whiting-117** [golang/vscode-go#2887]
gopls version: v0.12.4 (go1.20.6)
gopls flags: -remote=localhost:8091
update flags: proxy
extension version: 0.39.1
go version: 1.20.6
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Mon, 24 Jul 2023 13:29:31 GMT
restart history:
Mon, 24 Jul 2023 13:28:59 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@Whiting-coder Was the remote gopls (on localhost:8091) up and running? (Or temporarily restarting at that time?)
