### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by yueyueaa** [golang/vscode-go#2896]
gopls version: v0.13.0-pre.3 (go1.20.6)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.20.6
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 31 Jul 2023 02:35:30 GMT
restart history:
Mon, 31 Jul 2023 02:29:13 GMT: activation (enabled: false)
Mon, 31 Jul 2023 02:29:15 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)? This is especially important as you are using the new prerelease, and we'd like to catch any new crashes before releasing.

![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by yueyueaa** [comment]
> Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)? This is especially important as you are using the new prerelease, and we'd like to catch any new crashes before releasing.
> 
> ![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

This issue has been resolved, thank you for your answer, I will close this issue.
