### ISSUE TITLE
debug test

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2907]
Type: <b>Bug</b>

I am a Windows operating system, and every time I debug, I need to set the directory, environment, test, or debug. If there is a mistake, I cannot debug. I hope these can be automated, and the execution commands during debugging should be fully displayed and not hidden

Extension version: 0.39.1
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.94GB (4.13GB free)|
|Process Argv|--crash-reporter-id 8cccf0a5-623c-4d6c-9df1-f05cb9c1b469|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
89544117:30613380
vscrp:30673768
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590
cmakesidepanelv2:30779593

```

</details>

**Comment by hyangah** [comment]
Can you tell us more what happens?

The extension has the default debug configuration invokable through various means
(e.g. "debug test" codelens, "F5", ..) in most cases. You can also enable verbose logging with
the following setting for all your debug sessions if you need to investigate broken debugging session.

```
    "go.delveConfig": {
        "showLog": true,
        "logOutput": "dap"
    },
```
