### ISSUE TITLE
go json struct yaml 

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2912]
Type: <b>Feature Request</b>

During development, there will be a JSON conversion to struct. After copying and pasting a JSON, the structure will be automatically generated. There is a prompt, and there is also a structure conversion to JSON. Sometimes, it is necessary to convert to yaml. After a sting, entering 'will prompt JSON, yaml, and the structure name will be

Extension version: 0.39.1
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by hyangah** [comment]
Is this a feature improvement request for the existing "Go: Add Tags To Struct Fields"? 

Or is it about conversion between JSON and Yaml? For latter, I am afraid that's beyond this extension's feature and [other extensions in vscode marketplace](https://marketplace.visualstudio.com/search?term=json%20yaml%20convert&target=VSCode&category=All%20categories&sortBy=Relevance) may offer similar functionalities.
