### ISSUE TITLE
go interface

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2913]
Type: <b>Feature Request</b>

The function of the go interface cannot be found when using ctrl+left click, and the query function is there. You need to query the function yourself. In fact, it is also in this project and you need to use the query function yourself. I hope this improvement can be made

Extension version: 0.39.1
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by hyangah** [comment]
@yupor5 sorry that I am not familiar with vscode keyboard shortcuts on windows. Can you help me know what "ctrl+left" is bound to? And, can you share a screenshot or code example that demonstrates the issue? That will help us understand the problem. Thanks.
