### ISSUE TITLE
Can not connect gopls when start vscode

### ISSUE THREAD

**Issue by tayalone** [golang/vscode-go#2914]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.7 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.13.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.80.2
2ccd690cbff1569e4a83d7c43d45101f817401dc
arm64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	-
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/phanupongrong-o/go
GOROOT: /Users/phanupongrong-o/goroot
PATH: /Users/phanupongrong-o/goroot/bin:/usr/local/opt/poppler-qt5/bin:/usr/local/opt/poppler-qt5/bin:/Users/phanupongrong-o/google-cloud-sdk/bin:/usr/local/opt/poppler-qt5/bin:/usr/local/opt/openjdk/bin:/Users/phanupongrong-o/.nvm/versions/node/v16.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/phanupongrong-o/go/bin://flutter/bin
PATH (vscode launched with): /usr/local/opt/poppler-qt5/bin:/usr/local/opt/poppler-qt5/bin:/Users/phanupongrong-o/google-cloud-sdk/bin:/usr/local/opt/poppler-qt5/bin:/usr/local/opt/openjdk/bin:/Users/phanupongrong-o/.nvm/versions/node/v16.15.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/phanupongrong-o/goroot/bin:/Users/phanupongrong-o/go/bin://flutter/bin

	go:	/Users/phanupongrong-o/goroot/bin/go: go version go1.20.7 darwin/arm64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/phanupongrong-o/go/bin/dlv	(version: v1.21.0 built with go: go1.20.7)
	golint:	not installed
	gopls:	/Users/phanupongrong-o/go/bin/gopls	(version: v0.13.1 built with go: go1.20.7)

go env
Workspace Folder (2docrm): /Users/phanupongrong-o/Work/Freelance/2docrm
	GO111MODULE=""
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/Users/phanupongrong-o/Library/Caches/go-build"
	GOENV="/Users/phanupongrong-o/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/phanupongrong-o/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/phanupongrong-o/go"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/Users/phanupongrong-o/goroot"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/Users/phanupongrong-o/goroot/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.20.7"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/dev/null"
	GOWORK=""
	CGO_CFLAGS="-O2 -g"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-O2 -g"
	CGO_FFLAGS="-O2 -g"
	CGO_LDFLAGS="-O2 -g"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xn/h2rxdpwn51l_v1c4228wy3cm0000gn/T/go-build1531774915=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
````
    "go.toolsManagement.autoUpdate": true,
    "go.buildTags": "uint",
    "go.lintTool": "golint",
    "editor.inlineSuggest.enabled": true,
    "window.zoomLevel": -1,
    "gopls": {},

````

### Describe the bug
Cann't Connect gopls when start vscode and I got error
````
fatal: morestack on g0
[Info  - 11:59:22 AM] 
true
[Error - 11:59:22 AM] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
fatal: morestack on g0
[Error - 11:59:22 AM] The gopls server failed to initialize.
[Error - 11:59:22 AM] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposed
````

### Screenshots or recordings
<img width="858" alt="Screenshot 2566-08-04 at 11 59 31" src="https://github.com/golang/vscode-go/assets/11792728/21cbeb67-86d9-48d1-bbcc-6a6bc3f07032">

**Comment by bdarcet** [comment]
👋 @tayalone Having a similar issue on my VSCode since yesterday. Did you find a workaround? I've tried to change the version but doesn't look like it worked

**Comment by findleyr** [comment]
Yes, this looks like a broken binary due to golang/go#61190. @tayalone could you confirm that `gopls version` is broken?

**Comment by AasmundN** [comment]
I am experiencing a similar issue.

**Comment by findleyr** [comment]
@AasmundN are you on darwin? What happens when you run `gopls version`?
See also https://go.dev/issue/63997

**Comment by AasmundN** [comment]
@findleyr thanks for quick reply. I am on Sonoma 14.2.1. I have tried the solution suggested in https://github.com/golang/go/issues/61190. I am currently using xcode devltools fro xcode 15.1, considering trying to downgrade. I have not checked out the issue you link to, I will do that before downgrading.

**Comment by AasmundN** [comment]
@findleyr I installed it via homebrew, and also copied it over to /usr/local/go/bin/gopls like suggested in https://github.com/golang/go/issues/61190#issuecomment-1663426102.

**Comment by findleyr** [comment]
Hmm, can you please try running gopls as a daemon in a terminal, to see if it gets a connection?

In a terminal, can you start gopls with `gopls -listen=localhost:8091`
In VS Code, can you set [go.languageServerFlags](https://github.com/golang/vscode-go/wiki/settings#golanguageserverflags) to have `-remote=localhost:8091`.

When you restart the language server in VS Code (via the command palette: `Go: Restart Language Server`), you should see a connection logged in your terminal. Can you confirm?

**Comment by AasmundN** [comment]
I ran the daemon using the command you provided, it seem to start like it should. However I still get the same error when restarting the language server in vscode. This are my vscode settings.
```json
"gopls": { "ui.semanticTokens": true },
"go.useLanguageServer": true,
"go.languageServerFlags": [-remote=localhost:8091],
"[go]": {
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "golang.go"
},
```
![Screenshot 2024-01-08 at 23 53 47](https://github.com/golang/vscode-go/assets/48122613/5dcf98b5-b0b5-4dc1-89a0-c8ab8715ebf6)
![Screenshot 2024-01-08 at 23 53 56](https://github.com/golang/vscode-go/assets/48122613/ec903cdf-9c7e-4608-b434-4713ca337a24)

**Comment by findleyr** [comment]
Hi, I believe `-remote=localhost:8091` needs to be a string, in quotes. Then you should see a log message in your terminal about the gopls instance connecting to the daemon.

**Comment by AasmundN** [comment]
Changed it to a string, still no luck.

**Comment by AasmundN** [comment]
@findleyr I was able to make it connect to the language server by setting _alternateTools.gopls_ to the gopls binary path in my homebrew directory. My current settings are
```json
"go.alternateTools": {
  "gopls": "/opt/homebrew/bin/gopls"
},
"[go]": {
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "golang.go"
},
```

Intellisense and formatting seems to be working now. However I am getting some error regarding the modules in my workspace that I am not quite sure how to resolve.
![Screenshot 2024-01-09 at 22 38 52](https://github.com/golang/vscode-go/assets/48122613/81c623a3-36f8-4270-9c6d-2a117fe2395d)
