### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by GimTaeGyun** [golang/vscode-go#2915]
gopls version: v0.13.1 (go1.18.1)
gopls flags: [object Object]
update flags: proxy
extension version: 0.39.1
go version: 1.18.1
environment: Visual Studio Code win32
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Fri, 04 Aug 2023 07:34:55 GMT
restart history:
Fri, 04 Aug 2023 07:34:52 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@GimTaeGyun I guess the settings.json is somehow corrupted, and a wrong value was added to `"go.languageServerFlags". Can you open VS Code's settings.json and see if there is any error around it? Thanks.
