### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by xingzhenxiang** [golang/vscode-go#2917]
gopls version: v0.13.1
gopls flags: 
extension version: 0.23.0
environment: Visual Studio Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@xingzhenxiang Please update the VS Code extension to the newer version. The latest extension version is 0.39.1.

**Comment by hyangah** [comment]
BTW, are you using some dev container? Recently many users report issues with this outdated version 0.23.0, so I am wondering if this is due to some popular dev container or some editor service. In that case, please contact the maintainer of it and update the outdated extension embedded in the container.
