### ISSUE TITLE
Can not use the debugger rewind feature

### ISSUE THREAD

**Issue by eqinox76** [golang/vscode-go#2918]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.5 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	-  golang.org/x/tools/gopls v0.13.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.80.1 74f6148eb9ea00507ec113ec51c489d6ffb4b771 x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/carsten/go
GOROOT: /usr/lib/go-1.20
PATH: /home/carsten/.vscode-server/bin/74f6148eb9ea00507ec113ec51c489d6ffb4b771/bin/remote-cli:/home/carsten/.local/bin:/home/carsten/.nvm/versions/node/v16.17.0/bin:/opt/distrod/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/carsten/go/bin/

	go:	/usr/bin/go: go version go1.20.5 linux/amd64

	gotests:	/home/carsten/go/bin/gotests	(version: v1.6.0 built with go: go1.20.1)
	gomodifytags:	/home/carsten/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.20.1)
	impl:	/home/carsten/go/bin/impl	(version: v1.1.0 built with go: go1.20.1)
	goplay:	/home/carsten/go/bin/goplay	(version: v1.0.0 built with go: go1.20.1)
	dlv:	/home/carsten/go/bin/dlv	(version: v1.20.1 built with go: go1.20.1)
	staticcheck:	/home/carsten/go/bin/staticcheck	(version: v0.4.1 built with go: go1.20.1)
	gopls:	/home/carsten/go/bin/gopls	(version: v0.13.1 built with go: go1.20.5)

go env
Workspace Folder (importer): /home/carsten/repos/xtp/tca/importer
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/carsten/.cache/go-build"
	GOENV="/home/carsten/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/carsten/go/pkg/mod"
	GOOS="linux"
	GOPATH="/home/carsten/go"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/lib/go-1.20"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/lib/go-1.20/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.20.5"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/carsten/repos/importer/go.mod"
	GOWORK=""
	CGO_CFLAGS="-O2 -g"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-O2 -g"
	CGO_FFLAGS="-O2 -g"
	CGO_LDFLAGS="-O2 -g"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1488701135=/tmp/go-build -gno-record-gcc-switches"
</details>

### Share the Go related settings you have added/edited
setting.json
```
  "gopls": {
    "buildFlags": ["-tags=integration"]
  },
  "go.toolsManagement.autoUpdate": true,
```
launch.json
```
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Package",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "program": "${fileDirname}",
      "backend": "rr",
    }
  ]
}
```

### Describe the bug
I tried to get rewind debugging to work as described in #110 and shown here https://twitter.com/belbaoverhill/status/1466911997174464513.
But it is not working and i see no error messages. Neither can i find further pointers in the documentation.

### Steps to reproduce the behavior:
1. Make sure the 'rr' backend is choosen in launch.json.
2. Set a break point in a unit test.
3. Start debugging the unit test.
4. When hitting the break point i expect a rewind button. But i only see the normal options:
![image](https://github.com/golang/vscode-go/assets/5861557/e653c0be-2745-48fe-8a68-d86723a282b1)
Debug Console shows:
```
Starting: /home/carsten/go/bin/dlv dap --listen=127.0.0.1:41843 --log-dest=3 from /home/carsten/repos/importer
DAP server listening at: 127.0.0.1:41843
Type 'dlv help' for list of commands.
```

Many thanks in advance for looking into this.

**Comment by jamalc** [comment]
Are you using the Code Lens "debug test" to start your test? This does not use your launch config. See more [here](https://github.com/golang/vscode-go/wiki/debugging#debug-sessions-started-with-the-debug-test-codelens-or-the-test-ui-does-not-use-my-launchjson-configuration).

**Comment by eqinox76** [comment]
Ah thank you that was indeed the solution. For anyone finding this issue in the future be sure to also install [rr](https://github.com/rr-debugger/rr/wiki/Building-And-Installing) to have the rr backend available.
