### ISSUE TITLE
autocomplete is slow

### ISSUE THREAD

**Issue by MetaMmodern** [golang/vscode-go#292]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.14.4
</pre>

### Does this issue reproduce with the latest release?

Idk.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Bunyamin\AppData\Local\go-build
set GOENV=C:\Users\Bunyamin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Bunyamin\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Bunyamin\AppData\Local\Temp\go-build068588934=/tmp/go-build -gno-record-gcc-switches
</pre></details>

### What did you do?

Just install the add-on and try using autocomplete.

### What did you expect to see?

No lags.

### What did you see instead?

Freezes and lags)
![image](https://user-images.githubusercontent.com/42899786/86528332-a54c0b80-beaf-11ea-9f50-71b5a596a32f.png)
Here on the screenshot you can see, that the add-on doesn't give fast response and shows "Loading...". During such behaviour whole system starts to lag and work slowly until some info about autocomplete is shown. It is very uncomfortable when you try using fast autocomplete and arrows to choose the function(structure/type/etc) you need. While writing code on html/js/css there is no such behaviour.

**Comment by codecat** [comment]
> One question would be whether or not you are using Go Modules?

I'm not the issue submitter, but I'm noticing some heavy autocompletion delays since adding Go Modules to my project. Prior to that, everything was super fast and snappy. Is this a known problem?

**Comment by MetaMmodern** [comment]
> > One question would be whether or not you are using Go Modules?
> 
> I'm not the issue submitter, but I'm noticing some heavy autocompletion delays since adding Go Modules to my project. Prior to that, everything was super fast and snappy. Is this a known problem?
> 
> Edit: Just found out my VS Code actually wasn't using gopls, despite me thinking it was.. enabling it in the settings made it a lot faster. 👍

Great, i'm not using go and go extensions anymore but i'm glad that you found a solution.
