### ISSUE TITLE
go func ()info,error

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2922]
Type: <b>Bug</b>

1. The go function has multiple returns, one with a prompt, and if there are multiple returns, there is no prompt
2. When creating a go file, the package prompt is slow and you need to wait for the prompt
3. When there is an error, the prompt will get stuck. First, fix the error before there is a prompt. I often work on several files during development. One side just added it, and the other side prompts to wait for it to appear, so I won't respond immediately,
4. When inputting a structure into {} without prompting whether to write all writable variables, you need to find those variables yourself and copy them one by one. I hope this improvement can be achieved

Extension version: 0.39.1
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (10.46GB free)|
|Process Argv|I:\\source\\python\\yz_ht_opencvole\\super_faceoss --crash-reporter-id 8cccf0a5-623c-4d6c-9df1-f05cb9c1b469|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
3biah626:30602489
89544117:30613380
vscrp:30673768
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by hyangah** [comment]
@yupor5 Sorry it must be very frustrating. We need more info about your setup to triage. Can you please follow the troubleshooting guide https://github.com/golang/vscode-go/wiki/troubleshooting and provide missing info?

We need settings.json and ideally, the gopls trace. Screenshots or example for repro is also greatly appreciated. Thanks.
