### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by Hammad887** [golang/vscode-go#2928]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.7 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- uild info
----------
golang.org/x/tools/gopls v0.13.1
    golang.org/x/tools/gopls@v0.13.1 h1:Q0cfPbEG1WVfgxcRZ9uKTA6/ckIRNXx6Ym7KgT/VFE4=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.12.0 h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=
    golang.org/x/sync@v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
    golang.org/x/sys@v0.10.0 h1:SqMFp9UcQJZa+pmYuAKjd9xq1f0j5rLcDIk0mj4qAsA=
    golang.org/x/text@v0.11.0 h1:LAntKIrcmeSKERyiOh0XMV39LXS8IE9UL2yP7+f5ij4=
    golang.org/x/tools@v0.11.2-0.20230801165449-23c7f589706c h1:YilyjKn3EDn6X+x+kP+4REeEtG3WeM52dJAr7AWzVrQ=
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.7
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.81.0
6445d93c81ebe42c4cbd7a60712e0b17d9463e97
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: C:\Users\hamma\go
GOROOT: C:\Program Files\Go
PATH: C:\Program Files\Go\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Eclipse Adoptium\jdk-19.0.2.7-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\GitHub CLI\;C:\Users\hamma\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\PuTTY\;C:\Program Files\MongoDB\Server\6.0\bin;C:\Users\hamma\anaconda3;C:\Users\hamma\anaconda3\Library\mingw-w64\bin;C:\Users\hamma\anaconda3\Library\usr\bin;C:\Users\hamma\anaconda3\Library\bin;C:\Users\hamma\anaconda3\Scripts;C:\Users\hamma\AppData\Local\Microsoft\WindowsApps;C:\Users\hamma\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.3\bin;;C:\Users\hamma\AppData\Roaming\npm;C:\Users\hamma\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\hamma\go\bin;C:\Users\hamma\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\GoLand 2023.2\bin;
PATH (vscode launched with): C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Eclipse Adoptium\jdk-19.0.2.7-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\GitHub CLI\;C:\Users\hamma\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\PuTTY\;C:\Program Files\MongoDB\Server\6.0\bin;C:\Program Files\Go\bin;C:\Users\hamma\anaconda3;C:\Users\hamma\anaconda3\Library\mingw-w64\bin;C:\Users\hamma\anaconda3\Library\usr\bin;C:\Users\hamma\anaconda3\Library\bin;C:\Users\hamma\anaconda3\Scripts;C:\Users\hamma\AppData\Local\Microsoft\WindowsApps;C:\Users\hamma\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.3.3\bin;;C:\Users\hamma\AppData\Roaming\npm;C:\Users\hamma\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\hamma\go\bin;C:\Users\hamma\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\GoLand 2023.2\bin;

	go:	C:\Program Files\Go\bin\go.exe: go version go1.20.7 windows/amd64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	C:\Users\hamma\go\bin\dlv.exe	(version: v1.21.0 built with go: go1.20.7)
	staticcheck:	C:\Users\hamma\go\bin\staticcheck.exe	(version: v0.4.3 built with go: go1.20.7)
	gopls:	C:\Users\hamma\go\bin\gopls.exe	(version: v0.13.1 built with go: go1.20.7)

go env
Workspace Folder (ham): c:\Users\hamma\Desktop\ham
	set GO111MODULE=
	set GOARCH=amd64
	set GOBIN=
	set GOCACHE=C:\Users\hamma\AppData\Local\go-build
	set GOENV=C:\Users\hamma\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOEXPERIMENT=
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=C:\Users\hamma\go\pkg\mod
	set GONOPROXY=
	set GONOSUMDB=
	set GOOS=windows
	set GOPATH=C:\Users\hamma\go
	set GOPRIVATE=
	set GOPROXY=https://proxy.golang.org,direct
	set GOROOT=C:\Program Files\Go
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	set GOVCS=
	set GOVERSION=go1.20.7
	set GCCGO=gccgo
	set GOAMD64=v1
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=0
	set GOMOD=c:\Users\hamma\Desktop\ham\go.mod
	set GOWORK=
	set CGO_CFLAGS=-O2 -g
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-O2 -g
	set CGO_FFLAGS=-O2 -g
	set CGO_LDFLAGS=-O2 -g
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\hamma\AppData\Local\Temp\go-build914789411=/tmp/go-build -gno-record-gcc-switches
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

"go.toolsManagement.autoUpdate": true,
"go.useLanguageServer": true,
    "gopls": {
        "ui.semanticTokens": true
    },

### Describe the bug
A clear and concise description of what the bug.: "Intellisense is not working"
A clear and concise description of what you expected to happen. " If I type wrong spelling of a word e.g servr instead of server. It doesn't red underline it. Means Intellisense is not working at all.

### Steps to reproduce the behavior:
1. Go to 'any .go file'
2. Click on 'a word and change the spellings'
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://github.com/golang/vscode-go/assets/46949390/7fc27869-bced-42ec-ba3d-93c7ae9fdb6f)
[](url)
I have changed the spellings of Router and there is no red underlining to show any error to me.

**Comment by jamalc** [comment]
Do other features of the extension work: hover, goto, etc. If so, can you confirm you have intellisense enabled for Go in your settings?
<img width="701" alt="Screenshot 2023-08-10 at 8 28 32 AM" src="https://github.com/golang/vscode-go/assets/18269441/617d62f6-93c1-4a24-bdbd-9c74c2e2db0c">
