### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by martoc** [golang/vscode-go#2938]
gopls version: v0.4.1 (undefined)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.20.7
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 12 Aug 2023 15:11:10 GMT
restart history:
Sat, 12 Aug 2023 15:10:51 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

go version 1.20.7 and 1.21.0

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

Tools environment: GOPATH=/Users/martoc/go
Installing 1 tool at /Users/martoc/go/bin in module mode.
  gopls

Installing golang.org/x/tools/gopls@latest FAILED
{
 "code": 1,
 "killed": false,
 "signal": null,
 "cmd": "/usr/local/go/bin/go install -v golang.org/x/tools/gopls@latest",
 "stdout": "",
 "stderr": "go: golang.org/x/tools/gopls@latest (in golang.org/x/tools/gopls@v0.4.1):\n\tThe go.mod file for the module providing named packages contains one or\n\tmore replace directives. It must not contain directives that would cause\n\tit to be interpreted differently than if it were the main module.\n"
}

1 tools failed to install.

gopls: failed to install gopls(golang.org/x/tools/gopls@latest): Error: Command failed: /usr/local/go/bin/go install -v golang.org/x/tools/gopls@latest
go: golang.org/x/tools/gopls@latest (in golang.org/x/tools/gopls@v0.4.1):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
 

Failed to auto-collect gopls trace: incomplete panic trace.

**Comment by findleyr** [comment]
Hi, gopls@v0.4.1 is very, very old. Could you please use a more recent version? The last published version is gopls@v0.13.1.
