### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by praveenvoonna** [golang/vscode-go#2950]
gopls version: v0.13.2 (go1.21.0)
gopls flags: -remote=auto -gocodecompletion
update flags: proxy
extension version: 0.39.1
go version: 1.21.0
environment: Visual Studio Code win32
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Tue, 22 Aug 2023 18:09:58 GMT
restart history:
Tue, 22 Aug 2023 18:09:48 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@praveenvoonna Looks like `"go.languageServerFlags"` includes an invalid value `-gocodecompletion`. Can you please check your settings.json (both workspace and user configuration) and see if that fixes the issue?
