### ISSUE TITLE
Can not run the program correctly!

### ISSUE THREAD

**Issue by pwango** [golang/vscode-go#2958]
Recently, I used golang as backend for building a web, and want to import other local module after using go mod and go work command. Vscode always notified me "package xxx is not in std( goroot path)". However, when I tried to input "go run test.go" in CMD, the computer give me a correct result. And if I import local module, the exGo often delete the name. Maybe there is a issue in vscode or some settings.

![go](https://github.com/golang/vscode-go/assets/143368172/cc85976b-49a6-42d8-9ace-ce0c403803d1)

**Comment by hyangah** [comment]
@pwango Can you please share more info about
  * where your `go.mod` files for `t/t2` and `t11` modules are defined, 
  * from which directory you opened the vscode, and
  * where your `go.work` is located? 
  
And are you using any other extension? The OUTPUT panel (Code) shown in the screenshot doesn't seem to belong to this extension.

**Comment by pwango** [comment]
> 

This problem has been solved. Maybe vscode runned a different version code instead of what I saw when I closed the IDE.

**Comment by pwango** [comment]
> This probl

You know, in China I often can not  connect Github easily.
