### ISSUE TITLE
Debugger: show pprof labels in stack trace view

### ISSUE THREAD

**Issue by stefanhaller** [golang/vscode-go#2960]
**Is your feature request related to a problem? Please describe.**
It would be nice if pprof labels could be shown in the stack trace view when debugging.

While debugging it can often be hard to identify which go routine is which in the stack trace view. Go has this feature of attaching labels to go routines via the runtime/pprof module; see https://blog.jetbrains.com/go/2020/03/03/how-to-find-goroutines-during-debugging/. The Jetbrains Goland IDE shows these in the stack frame view; it would be nice if the VS Code debugger could do the same.

**Describe the solution you'd like**
Show labels after the go routine ID. For example, instead of showing just `[Go 42]`, show `[Go 42 key1: value1, key2: value2]`.

**Comment by stefanhaller** [comment]
I now realize this is a delve issue, so I filed it there: https://github.com/go-delve/delve/issues/3493.

**Comment by mgabeler-lee-6rs** [comment]
The release notes advertise this as working now, but AFAICT it doesn't: https://github.com/golang/vscode-go/discussions/3173
