### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by santiago-wjq** [golang/vscode-go#2964]
gopls version: v0.13.2 (go1.21.0)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.0
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sat, 09 Sep 2023 08:09:08 GMT
restart history:
Sat, 12 Aug 2023 01:14:06 GMT: activation (enabled: false)
Sat, 12 Aug 2023 01:15:08 GMT: installation (enabled: true)
Sat, 12 Aug 2023 01:20:00 GMT: installation (enabled: true)
Wed, 16 Aug 2023 20:27:04 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
