### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by ipsita-npg** [golang/vscode-go#2969]
gopls version: v0.13.2
gopls flags: 
extension version: 0.23.0
environment: Visual Studio Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
  Code: -32700 </pre>

**Comment by hyangah** [comment]
Please update the vscode go extension. v0.23.0 is no longer supported. Thanks!
