### ISSUE TITLE
when open vscode with a URI with ?windowId=_blank ,the go extenion get a error

### ISSUE THREAD

**Issue by change520** [golang/vscode-go#2980]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error
open vscode with url like "vscode://vscode-remote/ssh-remote+root@HOST/data/workspace/?windowId=_blank"
after go extension install ,the error will show on the PROBLEM tab
### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
<img width="664" alt="image" src="https://github.com/golang/vscode-go/assets/3221783/75bc5757-543f-428b-8121-17b23af27e28">

**Comment by findleyr** [comment]
I'm not sure what `?windowId=_blank` has to do with this report.

Can you share the contents of your go.mod file, or a minimal repo that reproduces the problem? There is a workspace layout issue here, but without more information about the workspace, I can't diagnose it.  (the 'within module "."' message looks suspicious, however).
