### ISSUE TITLE
Copying from JSON to GO files cannot automatically convert to a universal structure. We hope to add

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2985]
Type: <b>Feature Request</b>

Copying from JSON to GO files cannot automatically convert to a universal structure. We hope to add

Extension version: 0.39.1
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by findleyr** [comment]
Sorry, I don't understand this request. Could you explain more specifically what you would like VS Code to do when copying JSON files into Go files? What do you mean by "universal structure"?
