### ISSUE TITLE
Characters Disappearing after saving the file in VS Code 

### ISSUE THREAD

**Issue by sauntheninja2** [golang/vscode-go#2987]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.20.5 windows/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Not Installed
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.82.0
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- set GO111MODULE=
	set GOARCH=amd64
	set GOBIN=
	set GOCACHE=C:\Users\Sujay\AppData\Local\go-build
	set GOENV=C:\Users\Sujay\AppData\Roaming\go\env
	set GOEXE=.exe
	set GOEXPERIMENT=
	set GOFLAGS=
	set GOHOSTARCH=amd64
	set GOHOSTOS=windows
	set GOINSECURE=
	set GOMODCACHE=C:\Users\Sujay\go\pkg\mod
	set GONOPROXY=
	set GONOSUMDB=
	set GOOS=windows
	set GOPATH=C:\Users\Sujay\go
	set GOPRIVATE=
	set GOPROXY=https://proxy.golang.org,direct
	set GOROOT=C:\Program Files\Go
	set GOSUMDB=sum.golang.org
	set GOTMPDIR=
	set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
	set GOVCS=
	set GOVERSION=go1.20.5
	set GCCGO=gccgo
	set GOAMD64=v1
	set AR=ar
	set CC=gcc
	set CXX=g++
	set CGO_ENABLED=0
	set GOMOD=c:\Users\Sujay\Desktop\Dev\Golang\PG\go.mod
	set GOWORK=
	set CGO_CFLAGS=-O2 -g
	set CGO_CPPFLAGS=
	set CGO_CXXFLAGS=-O2 -g
	set CGO_FFLAGS=-O2 -g
	set CGO_LDFLAGS=-O2 -g
	set PKG_CONFIG=pkg-config
	set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\Sujay\AppData\Local\Temp\go-build278249291=/tmp/go-build -gno-record-gcc-switches
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
When I am typing golang code in VS Code and after writing a few characters like "log" if I save the file using ctrl s or using the gui to save the file the typed characters disappear.

### Steps to reproduce the behavior:
1. Type some valid GO code
2. Save the unsaved go file and the characters disappear

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

https://github.com/golang/vscode-go/assets/48253973/210c093a-719d-43fb-adb2-4c27c29f6c15

**Comment by findleyr** [comment]
Hi, this is currently how goimports work: since it is a build error to have unused imports, goimports deletes them.

One can get used to this behavior: instead of typing out the import, just start using `fmt`, save, and goimports will add the missing import. But you are not the first person to have run into this and been confused, and we're going to add an option to change this behavior: https://go.dev/issue/54362.

Closing this in favor of golang/go#54362.
