### ISSUE TITLE
debut test

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#2992]
Type: <b>Feature Request</b>

Unable to start debug test under win

Extension version: 0.39.1
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by hyangah** [comment]
@yupor5 We need more information to triage. Do you mind following the instruction https://github.com/golang/vscode-go/wiki/debugging#troubleshooting and sharing the logs and configuration you collected as you investigated the issue?
