### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by kunnoh** [golang/vscode-go#2993]
gopls version: v0.13.2
gopls flags: 
extension version: 0.39.1
environment: Code - OSS linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
@kunnoh Could you try upgrading your editor and see if that helps? If not, could you include the version of the editor you are using? Thanks!

**Comment by kunnoh** [comment]
![goerr](https://github.com/golang/vscode-go/assets/20157251/a72cb78d-88cd-4369-a6b8-a554d54635f2)

**Comment by kunnoh** [comment]
Y
