### ISSUE TITLE
go.testFlags allows me to get what I need from run test, but breaks debug test

### ISSUE THREAD

**Issue by pardanmeme** [golang/vscode-go#2994]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.8 darwin/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.13.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.76.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/nstypczynski/go
GOROOT: /usr/local/go
PATH: /usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin
PATH (vscode launched with): /usr/bin:/bin:/usr/sbin:/sbin

  go: /usr/local/go/bin/go: go version go1.20.8 darwin/amd64

  gotests:  /Users/nstypczynski/go/bin/gotests  (version: v1.6.0 built with go: go1.20.8)
  gomodifytags: /Users/nstypczynski/go/bin/gomodifytags (version: v1.16.0 built with go: go1.20.8)
  impl: /Users/nstypczynski/go/bin/impl (version: v1.1.0 built with go: go1.20.8)
  goplay: /Users/nstypczynski/go/bin/goplay (version: v1.0.0 built with go: go1.20.8)
  dlv:  /Users/nstypczynski/go/bin/dlv  (version: v1.21.0 built with go: go1.20.8)
  staticcheck:  /Users/nstypczynski/go/bin/staticcheck  (version: v0.4.6 built with go: go1.20.8)
  gopls:  /Users/nstypczynski/go/bin/gopls  (version: v0.13.2 built with go: go1.20.8)

go env
Workspace Folder (cyclescript): /Users/nstypczynski/ts/code/parser/cyclescript
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/Users/nstypczynski/Library/Caches/go-build"
  GOENV="/Users/nstypczynski/Library/Application Support/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="darwin"
  GOINSECURE=""
  GOMODCACHE="/Users/nstypczynski/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="darwin"
  GOPATH="/Users/nstypczynski/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/usr/local/go"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
  GOVCS=""
  GOVERSION="go1.20.8"
  GCCGO="gccgo"
  GOAMD64="v1"
  AR="ar"
  CC="clang"
  CXX="clang++"
  CGO_ENABLED="1"
  GOMOD="/Users/nstypczynski/code/parser/myscript/go.mod"
  GOWORK=""
  CGO_CFLAGS="-O2 -g"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-O2 -g"
  CGO_FFLAGS="-O2 -g"
  CGO_LDFLAGS="-O2 -g"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xr/616kdx6d4j7cb_p95y_q0k6m0000gn/T/go-build983036330=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

  "go.autocompleteUnimportedPackages": true,
  "go.inlayHints.parameterNames": false,
  "go.toolsManagement.autoUpdate": true,
  "go.testFlags": ["-v", "-nocolor"],

### Describe the bug
With this in my settings:
`"go.testFlags": ["-v", "-nocolor"]`
I cannot use _Debug test_.  I get an error:
`Build Error: go test -c -o /Users/nstypczynski/code/<blah_blah>/__debug_bin3809004473 -gcflags all=-N -l -v -nocolor .
go: unknown flag -nocolor cannot be used with -c
usage: go test [build/test flags] [packages] [build/test flags & test binary flags]
Run 'go help test' and 'go help testflag' for details. (exit status 2)`

I expect that either:
1. The extension detects conflicting flags and resolves them reasonably when possible.
2. The extension allows me to configure testFlags for _run test_ separately from testFlags for _debug test_.

### Motivation
Why am I specifying -nocolor?
I am using _github.com/matryer/is_ while testing and it produces failures with unhandled, distracting escape sequences.
Specifying _-nocolor_ omits the escape sequences.
`[90msome_test.go:22: [39mone != two`

### Steps to reproduce the behavior:
1. Create any test.
2. Have `"go.testFlags": ["-v", "-nocolor"]` in your settings.json.
3. Click on 'debug test'.
4. See error containing: `go: unknown flag -nocolor cannot be used with -c`

**Comment by hyangah** [comment]
@pardanmeme can you try the following setting?

```
"go.testFlags": ["-v", "-args", "-nocolor"]
```

`-args` test flag indicate the subsequent flag elements are application's flag. VS Code extension looks for this marker flag and uses it to distinguish the build/test flags and the user's application flags.

**Comment by pardanmeme** [comment]
Perfect.  Thank you.
