### ISSUE TITLE
Remove dependency on deprecated `request` package

### ISSUE THREAD

**Issue by mnoah1** [golang/vscode-go#2995]
### What version of Go, VS Code & VS Code Go extension are you using?
Current version on `master`

### Share the Go related settings you have added/edited
N/A

### Describe the bug
The extension has a dependency on `web-request`, which has not been updated in 7 years, and depends on the `request` package which was deprecated 4 years ago.

Request depends on an outdated version of the `tough-cookie` package which flags the following vulnerability: `Versions of the package tough-cookie before 4.1.3 are vulnerable to Prototype Pollution due to improper handling of Cookies when using CookieJar in rejectPublicSuffixes=false mode. This issue arises from the manner in which the objects are initialized.`. Since request is deprecated, this creates challenges in upgrading this.

### Steps to reproduce the behavior:
Ran a security report on the extension using FOSSA

### Screenshots or recordings
https://security.snyk.io/vuln/SNYK-JS-TOUGHCOOKIE-5672873

**Comment by hyangah** [comment]
Can you help us understand how this vulnerability is actually affecting this extension?

**Comment by hyangah** [comment]
Thanks for investigating the risk.
