### ISSUE TITLE
debug: debug

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#300]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hyangah** [comment]
Empty issue

**Comment by polinasok** [comment]
oops, sorry, I am not sure what happened there... thank you for closing
