### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by Wenhaoooooo** [golang/vscode-go#3002]
gopls version: v0.14.0-pre.2 (go1.18.1)
gopls flags: --log=debug --logtostderr
update flags: proxy
extension version: 2023.9.2722
go version: 1.18.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 07 Oct 2023 02:22:54 GMT
restart history:
Sat, 07 Oct 2023 02:22:25 GMT: activation (enabled: true)
Sat, 07 Oct 2023 02:22:42 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

[Error - 10:22:26 AM] gopls client: couldn't create connection to server.
  Message: Cannot call write after a stream was destroyed
  Code: -32099 
Error starting language server: Error: Cannot call write after a stream was destroyed[Error - 10:22:26 AM] The gopls server failed to initialize.
flag provided but not defined: -log

[Info  - 10:22:42 AM] 
true
[Error - 10:22:42 AM] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
flag provided but not defined: -log

Error starting language server: Error: Pending response rejected since connection got disposed

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Trace - 10:22:26 AM] Sending request 'initialize - (0)'.
[Trace - 10:22:42 AM] Sending request 'initialize - (0)'.
[Trace - 10:22:42 AM] Sending request 'initialize - (0)'.

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@Wenhaoooooo Can you please fix the `go.languageServerFlags` setting or errors around it? `-log=debug` `--logtostderr` are not recognized flags and gopls is pretty picky about invalid flags.
