### ISSUE TITLE
Hope to increase experience development for development

### ISSUE THREAD

**Issue by yupor5** [golang/vscode-go#3003]
Type: <b>Bug</b>

JSON automatically converts to structure, YAML automatically converts to structure, hoping that the prompt will not affect errors. When developing errors, the prompt will be very slow, and new files will need to wait for a prompt. The internal file structure call prompt is too slow

Extension version: 0.39.1
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-693.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (4.94GB free)|
|Process Argv|I:\\source\\golang\\hanzhong\\short_link\\gin-vue-admin.code-workspace --crash-reporter-id 8cccf0a5-623c-4d6c-9df1-f05cb9c1b469|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.16.142|
|OS|Linux x64 3.10.0-693.el7.x86_64|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (4 x 2096)|
|Memory (System)|7.64GB (5.31GB free)|
|VM|12%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30856252
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
vscrp:30673768
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
asynctok:30821568
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by hyangah** [comment]
@yupor5 Can you please provide examples to explain what you want and what you've tried?
That way, we can help us understand this feature request and have productive discussion. Thanks.

**Comment by yupor5** [comment]
type Data struct{
  Name string `json:"name"`    JSON will prompt JSON with 'name' as long as j is entered
}

**Comment by yupor5** [comment]
{"data":"11","name":"test"}When copying JSON to the go language proxy, it will prompt whether to convert to a structure
type T struct {
    Data string 
    Name string
}

**Comment by hyangah** [comment]
```
type Data struct{
Name string json:"name" JSON will prompt JSON with 'name' as long as j is entered
}
```

Usually, VS Code Go users use "Go: Add Tags To Struct Fields" command instead of typing the struct tag.
That fully automates the process. It also supports yaml.

```
{"data":"11","name":"test"}When copying JSON to the go language proxy, it will prompt whether to convert to a structure
type T struct {
Data string
Name string
}
```

That can be a convenient feature, but I think that's beyond the scope of the go language server and this extension.
I see there are a couple of extensions that provide the functionalities. Please try them.

For performance problems, please file an issue following the instruction in https://github.com/golang/vscode-go/wiki/troubleshooting.
