### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by SamDzomba** [golang/vscode-go#3018]
gopls version: v0.13.2
gopls flags: 
extension version: 0.39.1
environment: Gitpod Code linux
initialization error: Error: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: JSON RPC parse error: json: cannot unmarshal bool into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type protocol.PrepareSupportDefaultBehavior
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report. Do you still see the problem.
Looks like this is a transient error caused while updating the gopls.
