### ISSUE TITLE
Getting issue closing connection from different user (127.0.0.1:57254): connections to localhost are only accepted from the same UNIX user for security reasons

### ISSUE THREAD

**Issue by tanmay-rao** [golang/vscode-go#3024]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![image](https://github.com/golang/vscode-go/assets/88539410/4a0cf902-da71-4834-b76e-efc4cb32120f)

**Comment by ansaba** [comment]
@tanmay-rao , Can you provide information asked in various sections of the issue and elaborate more on the steps to reproduce ?

**Comment by hyangah** [comment]
I don't know how you ended up using different users for `dlv` process (server) and `vscode` process (client). Or it can be a bug in delve.

As the error message indicates, a workaround is to supply `--only-same-user` flag. You can supply the dlv flags with  `go.delveConfig` configuration. Something like `"go.delveConfig": { "dlvFlags": ["--only-same-users"] }`. Let us know if the workaround works for you.

**Comment by findleyr** [comment]
Closing as unactionable. See the workaround suggested in https://github.com/golang/vscode-go/issues/3024#issuecomment-1781832370.
