### ISSUE TITLE
Failed to run '/usr/bin/go env. The config change may not be applied correctly.

### ISSUE THREAD

**Issue by 6yy66yy** [golang/vscode-go#3036]
Type: <b>Bug</b>

Failed to run '/usr/bin/go env. The config change may not be applied correctly.

but in shell (bash)

[user@Wang vsmserver]$ /home/user/sdk/go1.21.0/bin/go env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE
{
        "GOBIN": "",
        "GOMODCACHE": "/home/user/go/pkg/mod",
        "GOPATH": "/home/user/go",
        "GOPROXY": "https://goproxy.cn,direct",
        "GOROOT": "/home/user/sdk/go1.21.0"
}

Extension version: 0.39.0
VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.76GB free)|
|Process Argv|--crash-reporter-id c779d28a-6d14-4024-a207-fb458d546982|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: AlmaLinux-8|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|Memory (System)|7.65GB (6.82GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pythonmypyd1:30879173
pythoncet0:30874138
pythontbext0:30879054

```

</details>

**Comment by 6yy66yy** [comment]
![image](https://github.com/golang/vscode-go/assets/44695760/b9c445ab-32d9-4ff5-aa38-44abef1d7b26)
![image](https://github.com/golang/vscode-go/assets/44695760/af52b038-3aae-42cc-bbe6-ef463ecf389b)

**Comment by findleyr** [comment]
It looks like you have GOPATH set somewhere else. Unfortunately, the logic to derive GOPATH is rather complex:
https://github.com/golang/vscode-go/blob/ed92a0c250e8941abb9adab973c129a263ba1e41/src/util.ts#L338

Can you run the command `Go: Current GOPATH`? What does that output?

**Comment by michelkaporin** [comment]
For those who face same issue with some projects but not others: make sure you have installed Go version that matches the version your Go project uses.

**Comment by Asef264** [comment]
check the GOPATH . it was changed for me ! when i brought back the setting to the right path the problem solved 
the path for me was : /home/MY_USER_NAME/go

**Comment by maoueh** [comment]
I'm facing similar issue right one where for one specific project, `vscode-go` tries to run a Golang at `/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/bin/go` but this is an older path that is not relevant anymore.

```
2025-05-02 20:09:03.651 [info] Failed to run '/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/bin/go env' (cwd: /Users/maoueh/work/sf/nitro): Error: Command failed: /opt/homebrew/Cellar/go@1.20/1.20.14/libexec/bin/go env -json GOPATH GOROOT GOPROXY GOBIN GOMODCACHE
```

Now the thing is that every attempt at running any tool like `Go: Location Tools` and similar, I get a `Command not found go.install` error so I have a hard time forcing it to switch to somewhere else.

I'm searching for where it could still pick up this old Golang, but I'm failing to find it. Still searching :$

**Comment by maoueh** [comment]
Ok, the problem was not actually that `/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/bin/go` didn't exist anymore. The problem was that `/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/bin/go env` command was actually failing.

And it was failing because I had did `go env -w "GOEXPERIMENT=synctest"` to try out the feature and this seems to remain valid throughout the whole system for any Go version, even if I had run using Go 1.24.

So I did `go env -w "GOEXPERIMENT="`, then `/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/bin/go env` was working again. At which point I was able to reload VScode, then was then able to `Select Go Environment` and switch to another version within VSCode then worked again.

**Comment by mpictor** [comment]
Thank you for that tip @michelkaporin ! While this is an older bug, it seems that a recent vscode change made it likely that you'll hit it. What's particularly annoying is that having any non-go project folders in the workspace breaks go support for _all_ loaded project folders: it tries to run `go env` in each project, fails in one that lacks a `go.mod`, and then doesn't bother starting `gopls`.

**Comment by Meekohi** [comment]
Ran into this issue because I had a local `go` version but also one installed by `snap`.
