### ISSUE TITLE
Gopls forces tab indentation of imports on go file save

### ISSUE THREAD

**Issue by pcbuildpluscoding** [golang/vscode-go#3044]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.19.5 linux/amd64 
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.14.1
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	-   Version: 1.84.2
            Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1

* Vscode go preferences
    "go.gopath": "/home/<username>/go",
    "go.vetOnSave": "off",
    "go.buildOnSave": "off",
    "go.lintOnSave": "off",
    "[go]": {
      "editor.formatOnSave": false
    },
    "go.toolsManagement.autoUpdate": true,
    "gopls": {
      "formatting.gofumpt": true
    },
    "go.enableCodeLens": {
      "runtest": false
    }

* Vscode generic settings relating to indentation
    "editor.indentSize": "tabSize",
    "editor.autoIndent": "brackets",
    "editor.detectIndentation": false,
    "terminal.integrated.tabStopWidth": 2,
    "editor.tabSize": 2,
    "remove-tabs-on-save.ignoreFileExtensions": [],

### Describe the bug

I've applied vscode settings to replace tab indentation with spaces in any source file
However, gopls overrides my preference by indenting with tabs **only the imports section**
Seems that gopls does not succeed all the time, because sometimes I'll run git diff on my vscode edited go source file and the imports show up with space versus tab diff output
I can run git diff -b to avoid space changes, but that's not a solution anyway
I enjoy using golang, but not gopls because it forces tab indentation by **running after the preferences have been applied**
Please don't override my preferences !
Is there a vscode setting I can add or update to stop gopls overriding my space indention preference
Thanks

**Comment by findleyr** [comment]
Hi, if you don't want gopls to organize imports on save, use the following settings:

```
"[go]": {
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        }
}
```
https://github.com/golang/vscode-go/blob/master/docs/advanced.md#formatting-code-and-organizing-imports

Go tooling uses tabs, and a conscious decision was made to standardize on this behavior (for reference, see e.g. https://go-proverbs.github.io/: "Gofmt's style is no one's favorite, yet gofmt is everyone's favorite."). If you choose to use tabs over spaces in Go code, a lot of tools will not work as desired.

Closing as the above settings are the way to disable auto-formatting.

**Comment by pcbuildpluscoding** [comment]
Hi, thanks for your answer and solution.
In regard to the editor.codeActionsOnSave config. The benefit of gopls removing unused imports plus space indentation is not hard to achieve. Gopls is great but it demands to run **after** other OnSave extensions. The perfect result would be configuration and code that allows the user to define either 1. the execution order of OnSave extensions 2. or which extension must **run last**. If gopls ran before my other space-to-tab extension then I'd have organised imports PLUS spaces instead of tabs.
Thanks again for the help
