### ISSUE TITLE
Go intelisense and autocomplete not working in vscode

### ISSUE THREAD

**Issue by dmgcoding** [golang/vscode-go#3048]
I have installed go in my mac. In vscode I have installed official go extension. But autocomplete doesn't work.

When I open a go folder I get this in output tab in terminal.

`Tools environment: GOPATH=/Users/drexter/go
Installing 1 tool at /Users/drexter/go/bin in module mode.
  gopls@0.14.1

Installing golang.org/x/tools/gopls@v0.14.1 (/Users/drexter/go/bin/gopls) SUCCEEDED

All tools successfully installed. You are ready to Go. :)`

go version - 
`go version go1.21.3 darwin/arm64`

`which go` gives '/usr/local/go/bin/go'

I didn't have goroot env variable set. So I set go root export GOROOT=/Users/drexter/go/bin in terminal.

printenv command gives
`
...
GOPATH=/Users/drexter/go
GOROOT=/Users/drexter/go/bin
...
`

vscode settings.json -
`"go.languageServerFlags": [

  ],
  "go.toolsManagement.autoUpdate": true,
  "editor.tabCompletion": "on",
  "go.installDependenciesWhenBuilding": true,
  "go.formatTool": "gofmt",
  "go.gopath": "~/go",
  "go.useLanguageServer": true,
  "gopls": {
    // Add parameter placeholders when completing a function.
   "usePlaceholders": true,

   // If true, enable additional analyses with staticcheck.
   // Warning: This will significantly increase memory usage.
   "staticcheck": false,
  },
  "go.lintTool": "golangci-lint",
  "go.delveConfig": {
  
  },
  // "go.goroot": "~go/bin",
  "editor.fontSize": 14,
  "[go]": {

    "editor.insertSpaces": false,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  }`

I also uninstalled and installed go extension. tried go nightly extension. None of them working.

Any Idea how to get go autocompletion working.

**Comment by suzmue** [comment]
@dmgcoding could you provide an example where autocomplete was not working? A code snippet would be helpful. Thank you!

**Comment by dmgcoding** [comment]
If i import fmt package. and try to use it. 
'fmt.Pr' it doesn't give me autocomplete/intelisense

**Comment by dmgcoding** [comment]
I also get these logs from go extension...
`Info  - 12:51:44] 
true
[Error - 12:51:44] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 12:51:44] The gopls server failed to initialize.
[Error - 12:51:44] gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Error starting language server: Error: Pending response rejected since connection got disposed`

**Comment by dmgcoding** [comment]
It was fixed when I reinstalled go. Not sure what was the issue. but it is ok now.
