### ISSUE TITLE
Unused import is not removed during format

### ISSUE THREAD

**Issue by 17hao** [golang/vscode-go#3049]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.20.10 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- golang.org/x/tools/gopls v0.14.1
    golang.org/x/tools/gopls@v0.14.1 h1:XaTETpi7Q67XO8nftquJitcx+9c2bPclO8Kz2sBVvec=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.13.0 h1:I/DsJXRlw/8l/0c24sM9yb0T4z9liZTduXvdAWYiysY=
    golang.org/x/sync@v0.4.0 h1:zxkM55ReGkDlKSM+Fu41A+zmbZuaPVbGMzvvdUPznYQ=
    golang.org/x/sys@v0.13.0 h1:Af8nKPmuFypiUBjVoU9V20FiaFXOcuZI21p0ycVYYGE=
    golang.org/x/telemetry@v0.0.0-20231011160506-788d5629a052 h1:1baVNneD/IRxmu8JQdBuki78zUqBtZxq8smZXQj0X2Y=
    golang.org/x/text@v0.13.0 h1:ablQoSUd0tRdKxZewP80B+BaqeKJuVhuRxj/dkrun3k=
    golang.org/x/tools@v0.14.1-0.20231026192422-8b5abd452b28 h1:5YgdZAe2w0x3Xrjv0+GXrI0jvm7qCQK/ySGFfiEHMfU=
    golang.org/x/vuln@v1.0.1 h1:KUas02EjQK5LTuIx1OylBQdKKZ9jeugs+HiqO5HormU=
    honnef.co/go/tools@v0.4.5 h1:YGD4H+SuIOOqsyoLOpZDWcieM28W47/zRO7f+9V3nvo=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.10
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.84.2
1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.40.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/sqh/go
GOROOT: /usr/local/go
PATH: /home/sqh/.local/bin:/home/sqh/.nvm/versions/node/v16.20.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin:/home/sqh/go/bin:/usr/local/jdk-11.0.18/bin

	go:	/usr/local/go/bin/go: go version go1.20.10 linux/amd64

	gopls:	/home/sqh/go/bin/gopls	(version: v0.14.1 built with go: go1.20.10)
	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/home/sqh/go/bin/dlv	(version: v1.21.2 built with go: go1.20.10)
	staticcheck:	not installed

go env
Workspace Folder (test): /home/sqh/codebase/test
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/sqh/.cache/go-build"
	GOENV="/home/sqh/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/sqh/go/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="linux"
	GOPATH="/home/sqh/go"
	GOPRIVATE=""
	GOPROXY="https://goproxy.cn,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.20.10"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD="/home/sqh/codebase/test/go.mod"
	GOWORK=""
	CGO_CFLAGS="-O2 -g"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-O2 -g"
	CGO_FFLAGS="-O2 -g"
	CGO_LDFLAGS="-O2 -g"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1730167805=/tmp/go-build -gno-record-gcc-switches"
	

</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
None
### Describe the bug
A clear and concise description of what the bug.
1. Setup autoSave
```
"files.autoSave": "afterDelay",
```
2. Write following code
```go
package main

import (
	"fmt"
	"math"
)

func main() {
	fmt.Printf("hello")
}
```
3. Format Document, but unused import was not removed

### Steps to reproduce the behavior:
1. Write an unused import statement
2. Format Document
3. Unused import is not removed

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

https://github.com/golang/vscode-go/assets/18420212/8a382a44-e7bf-4f78-b616-5e6a5678d347

**Comment by 17hao** [comment]
Hit ctrl+s to save file, the unused import is removed. But I turned on autoSave😂

**Comment by findleyr** [comment]
IIRC autosave does not run the organizeImport code action. Wouldn't that be very annoying if trying to type out an import manually? Also, organizeImports has non-trivial cost, so running it so frequently could be expensive.

Note that this issue is the exact opposite of the feedback aggregated into https://go.dev/issue/54362, where many users dislike that the import is removed at all!

**Comment by 17hao** [comment]
@findleyr Thanks for your reply. One more question, does [Format Document] run the organizeImport code action?
![2023-11-19-23-23](https://github.com/golang/vscode-go/assets/18420212/30ff9ab0-db16-49c8-8f83-a7068ee79e2f)

**Comment by 17hao** [comment]
@findleyr Thanks for your reply. [Similar issue](https://github.com/golang/vscode-go/issues/2640#issuecomment-1421569979)😂
