### ISSUE TITLE
debug: define descriptive constants for error IDs in the DA

### ISSUE THREAD

**Issue by eliben** [golang/vscode-go#305]
Right now the DA is using a multitude of error codes for sending an `ErrorResponse`, all as magic numbers within the code: 3000, 2008, 2003, etc.

It's not clear where the meaning of these codes is assigned (the DAP protocol only says they should be unique).

We should define these as constants and use the same constants in relevant places in debugAdapter2

**Comment by polinasok** [comment]
I was able to clarify this with vscode back in Feb. Please see https://github.com/go-delve/delve/pull/2103 for details.

Where in the debug adapter do you plan to use the constants?
To fulfill the uniqueness requirement, we can agree to reserve numbers in some range (e.g. 5000s) and add a comment in delve's error code enum that those values are reserved for the use by the adapter that might be working in tandem with delve.

**Comment by hyangah** [comment]
If neither DA or VSCode uses this constant, why not just leaving it unset or just giving the same number?

**Comment by eliben** [comment]
> I was able to clarify this with vscode back in Feb. Please see [go-delve/delve#2103](https://github.com/go-delve/delve/pull/2103) for details.
> 

Thanks for double-checking!

> Where in the debug adapter do you plan to use the constants?

There's a number of places where even the thin DA has to send `ErrorResponse` back to the editor. For example, failing to launch Delve, or failing to launch the debuggee in noDebug mode, or if delve exits with an error code unexpectedly; even internal errors of various kinds.

> If neither DA or VSCode uses this constant, why not just leaving it unset or just giving the same number?

Yes, this is unclear to me too. Does VSCode actually surface these codes in any way observable to users (or developers)?

We can also use our own range as Polina suggests, and designate several error codes for various things. The current DA already has some codes it's using, though, so it may make sense to just use those?

**Comment by polinasok** [comment]
Filed issue for clarification: https://github.com/microsoft/debug-adapter-protocol/issues/133

**Comment by polinasok** [comment]
From microsoft/debug-adapter-protocol#133: "The purpose of these error IDs is to help those extension authors that have the requirement that every error message needs a corresponding error number, so that users or customer support can find information about the specific error more easily. The ID is not used by VS Code."

It can be handy to check the constant in the tests and not rely on the text that could change. So I think we can keep defining them in dlv-dap like we have been - see https://github.com/go-delve/delve/blob/master/service/dap/error_ids.go.
