### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by aida00** [golang/vscode-go#3052]
gopls version: v0.6.5 (undefined)
gopls flags: 
update flags: proxy
extension version: 0.40.0
go version: 1.15.7
environment: Visual Studio Code win32
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
issue timestamp: Fri, 17 Nov 2023 20:26:08 GMT
restart history:
Fri, 17 Nov 2023 20:26:01 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi! Your gopls version is very old. Please upgrade: `go install golang.org/x/tools/gopls@latest`.
