### ISSUE TITLE
The dlv version in the compatibility description may be incorrect

### ISSUE THREAD

**Issue by xuqianjins** [golang/vscode-go#3054]
Signed-off-by: Qianjin Xu <xuqianjins@gmail.com>

### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- 1.21.4
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- v0.14.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.84.2
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.40.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- gopls: (version: v0.14.2 built with go: go1.21.4)
	- dlv: (version: v1.21.2 built with go: go1.21.4)
</details>

### Share the Go related settings you have added/edited

default

### Describe the bug
A clear and concise description of what the bug.

> The extension has been tested with gopls v0.14 and delve v0.21.

> The extension has been tested with gopls v0.14 and delve v1.21.

### Steps to reproduce the behavior:
1. Go to '[...](https://github.com/golang/vscode-go/blob/master/CHANGELOG.md?plain=1#L66C60-L66C65)'
2. See error

### Screenshots or recordings
The latest released version of [delve](https://github.com/go-delve/delve/releases) tool is 1.21.x

**Comment by hyangah** [comment]
Thanks for catching it and reading the release note. Sent cl/544056 (but since the extension is already released, embedded changelog won't be updated until the next release). Updated the release note github page.

**Comment by xuqianjins** [comment]
:thumbsup: Thank you for your fix @hyangah !
