### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by kramanathan01** [golang/vscode-go#306]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

After I added gopls configuration from the documentation at https://github.com/golang/tools/blob/master/gopls/doc/vscode.md

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

[Error - 10:11:06 AM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

[Error - 10:11:06 AM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF
[Trace - 10:14:56.918 AM] Sending request 'initialize - (0)'.
Params: {"processId":17041,"clientInfo":{"name":"vscode","version":"1.46.1"},"rootPath":null,"rootUri":null,"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"initializationOptions":{},"trace":"off","workspaceFolders":null}

[Error - Received] 10:14:56.922 AM #0 unsupported URI scheme:  (gopls only supports file URIs)

[Error - 10:14:56 AM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
[Trace - 10:14:56.926 AM] Sending request 'shutdown - (1)'.
Params: 

[Trace - 10:14:56.926 AM] Received response 'shutdown - (1)' in 0ms.
Result: null

[Trace - 10:14:56.926 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/08 10:14:56 server shutdown without initialization\n"}

[Trace - 10:14:56.926 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/08 10:14:56 Shutdown session\n\tshutdown_session=1\n"}

[Trace - 10:14:56.928 AM] Sending notification 'exit'.
Params: 

gopls: failed reading header line: EOF

**Comment by hyangah** [comment]
@kramanathan01 Thank you for the detailed bug report. Currently, `gopls` is not supporting a single file mode edit and requires to open a directory. (https://github.com/golang/go/issues/39987) Good news is that the change to fix this is ready to be released and will be available in gopls v0.4.4. 

Meanwhile, please open a directory where the file is located.

**Comment by kramanathan01** [comment]
@hyangah Thank you very much for the help. I confirmed gopls is working correctly at the folder level. Thanks for the heads up on v0.4.4. I'll look for the update.
