### ISSUE TITLE
 Restarting server failed   Message: Pending response rejected since connection got disposed   Code: -32097 

### ISSUE THREAD

**Issue by Hasy7201** [golang/vscode-go#3066]
Error showed in VSCODE

Error log:

Nov 26, 2023 8:40:26 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Nov 26, 2023 8:40:26 PM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
[Error - 8:40:28 PM] Connection to server got closed. Server will not be restarted.
[Error - 8:40:28 PM] Language Support for Java client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:40:28 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by findleyr** [comment]
Hi, are you still seeing this problem?

Can you please share the output of `gopls version`?
Are you on MacOS arm64, by any chance?

**Comment by Hasy7201** [comment]
I am using Windows*64 Machine

**Comment by hyangah** [comment]
@Hasy7201 are the error message from the "Go" output channel? The log indicates it's about Java, not Go.

```
[Error - 8:40:28 PM] Connection to server got closed. Server will not be restarted.
[Error - 8:40:28 PM] Language Support for Java client: couldn't create connection to server.
Message: Pending response rejected since connection got disposed
```

**Comment by hyangah** [comment]
Closing since this is unrelated to the Go extension.
