### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by yuqiandoudou** [golang/vscode-go#3077]
gopls version: v0.14.2 (go1.19.5)
gopls flags: 
update flags: proxy
extension version: 0.40.0
go version: 1.21.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 04 Dec 2023 08:44:02 GMT
restart history:
Mon, 04 Dec 2023 07:17:20 GMT: activation (enabled: true)
Mon, 04 Dec 2023 07:19:03 GMT: config change (enabled: true)
Mon, 04 Dec 2023 07:19:11 GMT: config change (enabled: true)
Mon, 04 Dec 2023 08:29:00 GMT: config change (enabled: true)
Mon, 04 Dec 2023 08:29:14 GMT: config change (enabled: true)
Mon, 04 Dec 2023 08:29:18 GMT: config change (enabled: true)
Mon, 04 Dec 2023 08:29:34 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by yuqiandoudou** [comment]
[Info  - 4:41:36 PM] 2023/12/04 16:41:35 go/packages.Load #1: updating metadata for 3951 packages

[Error - 4:41:45 PM] Request textDocument/semanticTokens/full failed.
  Message: semantictokens are disabled
  Code: 0 
[Error - 4:41:45 PM] Request textDocument/semanticTokens/full failed.
  Message: semantictokens are disabled
  Code: 0 
[Error - 4:41:45 PM] Request textDocument/semanticTokens/range failed.
  Message: semantictokens are disabled
  Code: 0 
[Info  - 4:42:28 PM] 2023/12/04 16:42:27 background imports cache refresh starting

[Error - 4:43:11 PM] Request textDocument/definition failed.
  Message: context canceled
  Code: 0 
[Error - 4:43:35 PM] Connection to server got closed. Server will not be restarted.

**Comment by adonovan** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
