### ISSUE TITLE
cannot set breakpoints when debugging the extension

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#308]
Related to #53 and https://go-review.googlesource.com/c/vscode-go/+/241041 -
currently we cannot set breakpoints. 

Debug console shows an error message like 

```
Could not read source map for file:///Users/hakim/vscode-go/dist/goMain.js: ENOENT: no such file or directory, open '/Users/hakim/vscode-go/dist/performance-now.js.map'
```

cc @OneOfOne

**Comment by hyangah** [comment]
The sourcemap allows to set breakpoints, but I still can't access or inspect local variables.
Does webpack destroy necessary debug information?
Should we use the old way then in debugging?

**Comment by OneOfOne** [comment]
Sadly I don't have enough experience with debugging using webpack.
