### ISSUE TITLE
show enclosing method name, when searching for usages

### ISSUE THREAD

**Issue by guettli** [golang/vscode-go#3083]
**Is your feature request related to a problem? Please describe.**

I press ctrl-click on a function name:

```
func (s *Service) handleIncompleteBoot(isRebootIntoRescue, isTimeout) (failed bool, err error) {
```

Now I see all usages of that function.

![image](https://github.com/golang/vscode-go/assets/414336/5d7b450a-5fca-46ea-adf9-03eb7b6752e5)

I see 4 usages of the method in host.go (right side of the screenshot).

I am missing the surrounding method name. The method in which `handleIncompleteBoot()` gets called.

**Describe the solution you'd like**

If I click on a search result (right side of screenshot), then I see the preview. 

New: At the top, I want to see the method name of the lines I see in the preview.

In the above example, I would like to see which method the line `1286` belongs to.

**Comment by hyangah** [comment]
The preview UI and reference UX are implemented by microsoft/vscode. This extension and the language server just offers just [reference location list](https://code.visualstudio.com/api/references/vscode-api#ReferenceProvider) and the vscode renders the list. So, I think discussion there will be more fruitful.

Existing alternatives (not convenient as what you are proposing) are:

* If you click each item with Option+Click, the location will open the location in the outer editor on the next column. From there you can use breadcrumb to find the surrounding function or method.

* Searching reference from callgraph hierarchy (Right click -> Show Call Hierarchy) opens the call hierarchy view. From there you can navigate call-in and call-out graph.

**Comment by hyangah** [comment]
@guettli Can you try the alternatives? The same feature request was open multiple times in microsoft/vscode e.g https://github.com/microsoft/vscode/issues/67268, but rejected in favor of an alternative like [sticky-scroll](https://code.visualstudio.com/updates/v1_71#_sticky-scroll).

Closing. Out-of-scope.
