### ISSUE TITLE
Install gopls with CGO disabled

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#3088]
Cgo is unnecessary to build gopls (and probably some of other tools).
Disable cgo (`CGO_ENABLED=0`), to avoid crashes (https://github.com/golang/vscode-go/issues/3085, https://github.com/golang/vscode-go/issues/3039, https://github.com/golang/go/issues/63997) caused by misconfigured C toolchain.

**Comment by hyangah** [comment]
I think most tools VS Code Go depends on don't need CGO.
(@derekparker @aarzilli Is it ok to use dlv compiled with `CGO_ENABLED=0`?)

**Comment by hyangah** [comment]
From my mac,

```
$ go list -f '{{if .CgoFiles}}{{.ImportPath}}{{end}}' -deps ./cmd/dlv
runtime/cgo
net
```

I think disabling CGO will be ok.

**Comment by aarzilli** [comment]
It should be fine everywhere except freebsd.

**Comment by hyangah** [comment]
According to @findleyr, gopls's CGO dependency was real (fastwalk). The dependency is removed from the dev branch so once gopls v0.15 is released next year, this problem will go away.
Delve and other tools don't have CGO dependency, so the go command won't rely on the CGO and we don't need to worry about it.

I will abandon the cl.
