### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by phoenixbms** [golang/vscode-go#309]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls updated itself and after that there is a message saying gopls failed to start.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

[Error - 10:13:15 AM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF

**Comment by hyangah** [comment]
@phoenixbms Thanks for providing the requested details.

This looks like the same problem as https://github.com/golang/go/issues/39987.  
Currently `gopls` (0.4.2, 0.4.3)  doesn't support single file edit, but requires to open a folder.  So, try to open the folder of the file for now.

The future version 0.4.4 will include the single file edit support.

Please reopen or file a new issue if it's a different case.
