### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by shmily1012** [golang/vscode-go#3099]
gopls version: v0.5.1 (undefined)
gopls flags: 
update flags: proxy
extension version: 0.40.0
go version: 1.13.4
environment: Visual Studio Code win32
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
issue timestamp: Wed, 20 Dec 2023 02:03:50 GMT
restart history:
Wed, 20 Dec 2023 02:03:32 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@shmily1012 Can you please update gopls and restart the editor?

`go install golang.org/x/tools/gopls@latest`
