### ISSUE TITLE
Go: Fill struct is missing.

### ISSUE THREAD

**Issue by ekkoful** [golang/vscode-go#3101]
Type: <b>Bug</b>

The Go: fill struct is missing when i use mac os remote ssh a ubuntu server.

![image](https://github.com/golang/vscode-go/assets/42363586/b42b63cb-5225-4e9d-9d49-5e877ae2969a)

Extension version: 0.40.1
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 21.6.0
Modes:
Remote OS version: Linux x64 5.4.0-117-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id ff734aa8-5d43-4482-a6d6-25efb50f9d48|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: devbox|
|OS|Linux x64 5.4.0-117-generic|
|CPUs|Intel(R) Xeon(R) KVM CPU @ 2.50GHz (12 x 2499)|
|Memory (System)|45.09GB (24.16GB free)|
|VM|24%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
f6dab269:30613381
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184c:30925681

```

</details>

**Comment by hyangah** [comment]
"Go: Fill struct" command was retired https://github.com/golang/vscode-go/issues/2107


Sorry for interrupting your workflow. We considered to leave `Go: Fill struct` but concluded this doesn't add much value any more. Can you try `Cmd` + `.` default binding?

https://github.com/golang/vscode-go/issues/2107#issuecomment-1788110528

**Comment by ekkoful** [comment]
OK，Thank you ! @hyangah

**Comment by GAZ082** [comment]
Booo
