### ISSUE TITLE
gopls: automated issue report (initialization) - gopls is not installed

### ISSUE THREAD

**Issue by vigneshramesh08** [golang/vscode-go#3109]
gopls version: undefined/undefined
gopls flags: 
update flags: proxy
extension version: 0.40.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Tue, 02 Jan 2024 06:08:08 GMT
restart history:
Tue, 02 Jan 2024 06:08:07 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@vigneshramesh08 Looks like gopls is not installed. Didn't the extension prompt and ask to install gopls?
