### ISSUE TITLE
Support goimports when when the language server is enabled

### ISSUE THREAD

**Issue by nicklaus-dev** [golang/vscode-go#3119]
![screen](https://github.com/golang/vscode-go/assets/118952483/0ef54368-ebf4-4ea1-b42b-5b63143e3764)

Why goimports is disabled when using gopls

**Comment by hyangah** [comment]
Gopls already does goimports-compatible import & formatting functionalities, so this is unnecessary.

**Comment by nicklaus-dev** [comment]
Thanks:)
