### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Y-xiaohang** [golang/vscode-go#3130]
gopls version: v0.14.2/go1.21.5
gopls flags: 
update flags: proxy
extension version: 0.40.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Mon, 15 Jan 2024 15:21:42 GMT
restart history:
Mon, 15 Jan 2024 15:21:25 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after running for 1046ms
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@Y-xiaohang Can you check if you were affected by https://github.com/golang/go/issues/63997 ?

The instruction is here
https://github.com/golang/vscode-go/issues/3085#issuecomment-1850368404

Or, alternatively, you can try the prerelease that avoids the problem

```
go install golang.org/x/tools/gopls@v0.15.0-pre.1
```
