### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by lokrain** [golang/vscode-go#3136]
gopls version: v0.14.2/go1.18.1
gopls flags: -hover -diagnostics -signatureHelp
update flags: proxy
extension version: 0.40.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Tue, 16 Jan 2024 14:55:43 GMT
restart history:
Tue, 16 Jan 2024 14:55:42 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 3,
    "TestdataFiles": 0,
    "GoFiles": 0,
    "ModFiles": 1,
    "Dirs": 2
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.14.2",
  "InitialWorkspaceLoadDuration": "182.013368ms",
  "MemStats": {
    "HeapAlloc": 2251536,
    "HeapInUse": 4481024,
    "TotalAlloc": 8811928
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2,
      "Largest": 201,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.18.1",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Please fix `"go.languageServerFlags"` setting. `-hover`, `-diagnostics`, `-signatureHelp` aren't recognized flags.
