### ISSUE TITLE
survey: 2024 survey link is expired

### ISSUE THREAD

**Issue by mauri870** [golang/vscode-go#3149]
Just got the prompt for the 2024 Go Developer survey, uppon clicking the "Yes" button it opens the browser but the link is expired.

I see the link was updated 4 days ago [here](https://github.com/golang/vscode-go/commit/0c3385775af7feca6bb9ea2f7e9350267c4352e2#diff-759c7e97e2c0d79647a56a3238c42cd2f371a3f7628f852285626b5c42361a80R142)

Survey URL: https://google.qualtrics.com/jfe/form/SV_083SVAUCji98YeO?s=p

Related https://github.com/golang/vscode-go/issues/3115
cc @hyangah 

![image](https://github.com/golang/vscode-go/assets/10168637/554e5e56-f96e-4e40-9a5a-b0f4c4d7408c)

**Comment by mauri870** [comment]
Additionally ccing @alicemerrick @fflewddur @findleyr

**Comment by hyangah** [comment]
Thanks a lot for the report! @mauri870 
The link is now up and running. Thanks @fflewddur for fixing it.
