### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by whr819987540** [golang/vscode-go#3170]
gopls version: v0.14.2/go1.19.1
gopls flags: 
update flags: proxy
extension version: 0.40.3
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 12 Feb 2024 09:18:23 GMT
restart history:
Mon, 12 Feb 2024 09:09:26 GMT: activation (enabled: false)
Mon, 12 Feb 2024 09:09:53 GMT: manual (enabled: false)
Mon, 12 Feb 2024 09:10:42 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after running for 61494ms
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by whr819987540** [comment]
Sure. The abstract directory path contains some privacy information, so I hide part of the output.
```bash
go: downloading github.com/bits-and-blooms/bitset v1.2.2
go: downloading github.com/mschoch/smat v0.2.0
go: downloading github.com/anacrolix/lsan v0.0.0-20211126052245-807000409a62
go: downloading crawshaw.io/iox v0.0.0-20181124134642-c51c3df30797
go: downloading gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
go: downloading github.com/tv42/httpunix v0.0.0-20191220191345-2ba4b9c3382c
go: downloading google.golang.org/grpc v1.20.1
go: downloading filippo.io/edwards25519 v1.0.0-rc.1
go: downloading github.com/alecthomas/assert/v2 v2.0.0-alpha3
github.com/anacrolix/torrent imports
	github.com/anacrolix/utp: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent/backup imports
	google.golang.org/grpc/benchmark/flags: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent imports
	github.com/RoaringBitmap/roaring imports
	github.com/bits-and-blooms/bitset: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent imports
	github.com/RoaringBitmap/roaring imports
	github.com/mschoch/smat: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent imports
	github.com/anacrolix/go-libutp tested by
	github.com/anacrolix/go-libutp.test imports
	github.com/anacrolix/lsan: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent/storage imports
	crawshaw.io/sqlite/sqlitex tested by
	crawshaw.io/sqlite/sqlitex.test imports
	crawshaw.io/iox/ioxtest: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent imports
	github.com/anacrolix/dht/v2 imports
	github.com/anacrolix/dht/v2/bep44 tested by
	github.com/anacrolix/dht/v2/bep44.test imports
	filippo.io/edwards25519: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent/fs imports
	github.com/anacrolix/fuse tested by
	github.com/anacrolix/fuse.test imports
	github.com/anacrolix/fuse/fs/fstestutil/spawntest imports
	github.com/tv42/httpunix: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent/test imports
	github.com/stretchr/testify/assert imports
	gopkg.in/yaml.v3 tested by
	gopkg.in/yaml.v3.test imports
	gopkg.in/check.v1: module lookup disabled by GOPROXY=off
github.com/anacrolix/torrent imports
	github.com/anacrolix/dht/v2 imports
	github.com/anacrolix/dht/v2/traversal imports
	github.com/anacrolix/dht/v2/containers imports
	github.com/anacrolix/stm/stmutil imports
	github.com/anacrolix/stm imports
	github.com/alecthomas/atomic tested by
	github.com/alecthomas/atomic.test imports
	github.com/alecthomas/assert/v2: module lookup disabled by GOPROXY=off
```

If this can't help you to fix, please feel free to tell me.

**Comment by whr819987540** [comment]
The reason is clear. I backup the .history directory generated by VScode and copy it. In the backup directory, there is go.mod file.

**Comment by hyangah** [comment]
Thanks for sharing info. 

>The reason is clear. I backup the .history directory generated by VScode and copy it. In the backup directory, there is go.mod file.

Do you mean that the extra go.mod file in the backup directory caused the gopls to crash? 

Now gopls v0.15.x is released, so I think this is obsolete. If you observe a crash when using the latest gopls, please let us know. Thanks again!
