### ISSUE TITLE
Stop auto insertion of square brackets when using a generic function

### ISSUE THREAD

**Issue by drunkenplatypus** [golang/vscode-go#3176]
I find it annoying when you use IntelliSense to autocomplete a generic function and are left with e.g. `slices.Contains[]()` with your cursor between the square brackets. 

In a lot of cases providing an explicit type isn't required, and it can be inferred from the provided argument e.g. `slices.Contains([]string{}, "foo")`

It would be nice if this behaviour was configurable so that generic functions behaved like any other function.

**Comment by hyangah** [comment]
What version of gopls are you using?
Can you give a try to v0.15.0 prerelease? When the types can be inferred, v0.15.0-pre.3 omits type param.
![Screenshot 2024-02-16 at 11 52 00 AM](https://github.com/golang/vscode-go/assets/4999471/42789499-ab87-4a16-a20a-910179abfe6b)

**Comment by findleyr** [comment]
Indeed: gopls@v0.15.0 indends to fix this:

```
go install golang.org/x/tools/gopls@v0.15.0-pre.3
```

**Comment by drunkenplatypus** [comment]
Yeah installing that version of gopls fixed it for me, thanks both!
