### ISSUE TITLE
Allow for choosing which grammar syntax highlighting you want

### ISSUE THREAD

**Issue by eliaswood** [golang/vscode-go#3177]
**Is your feature request related to a problem? Please describe.**
Upon the Jan 2024 release, the grammar syntax highlighting has changed for go, as seen [here](https://code.visualstudio.com/updates/v1_86#_languages:~:text=New%20Go%20grammar,the%20previous%20grammar). For the theme I use this ends up looking horrible and I really enjoyed the way it looked before. If there is already a way to do this please let me know. 

**Describe the solution you'd like**
I would like to be able to choose which syntax grammar highlighting is used. 

**Describe alternatives you've considered**
The only known work around I have found is to downgrade to the Nov 2023 version. However, this does not allow me to use copilot chat and some other features. 

**Additional context**
This is how it looked before 
![Screenshot 2024-02-16 at 11 16 09 AM](https://github.com/golang/vscode-go/assets/30331021/236deb12-4f56-433d-8be1-8d603d0e6b2d)

and this is how it looks now. 
![Screenshot 2024-02-16 at 11 15 12 AM](https://github.com/golang/vscode-go/assets/30331021/2c037f6b-7756-446e-a7d9-fb2da541fd67)

**Comment by hyangah** [comment]
Can you please file an issue to VSCode? This extension has nothing to do with the Go grammar syntax. The default syntax highlighting you are referring to is from VS Code.
We only support Semantic Token based syntax highlighting through LSP.  Thanks!
