### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by javy1103** [golang/vscode-go#3196]
gopls version: v0.15.0/go1.21.5
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 27 Feb 2024 21:57:38 GMT
restart history:
Tue, 27 Feb 2024 14:49:03 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 7736,
    "TestdataFiles": 0,
    "GoFiles": 19,
    "ModFiles": 1,
    "Dirs": 1484
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.5",
  "GoplsVersion": "v0.15.0",
  "InitialWorkspaceLoadDuration": "926.331126ms",
  "MemStats": {
    "HeapAlloc": 40543216,
    "HeapInUse": 62005248,
    "TotalAlloc": 611509800
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2128,
      "Largest": 935931,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.5",
        "AllPackages": {
          "Packages": 412,
          "LargestPackage": 147,
          "CompiledGoFiles": 2129,
          "Modules": 43
        },
        "WorkspacePackages": {
          "Packages": 8,
          "LargestPackage": 6,
          "CompiledGoFiles": 24,
          "Modules": 1
        },
        "Diagnostics": 1
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
@javy1103 can you say more about what you were doing when the crash occurred? Could this be #3194?
