### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by vpuglisi1** [golang/vscode-go#3206]
gopls version: v0.14.2/go1.19.1
gopls flags: -remote=10.100.45.181:4433
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Thu, 29 Feb 2024 09:48:13 GMT
restart history:
Thu, 29 Feb 2024 09:48:05 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 196819,
    "TestdataFiles": 17902,
    "GoFiles": 38136,
    "ModFiles": 911,
    "Dirs": 33539
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GoVersion": "go1.19.1",
  "GoplsVersion": "v0.14.2",
  "InitialWorkspaceLoadDuration": "3.0946005s",
  "MemStats": {
    "HeapAlloc": 269821112,
    "HeapInUse": 324640768,
    "TotalAlloc": 1591334496
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2784,
      "Largest": 879179,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.19.1",
        "AllPackages": {
          "Packages": 519,
          "LargestPackage": 131,
          "CompiledGoFiles": 2788,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 344,
          "LargestPackage": 131,
          "CompiledGoFiles": 1772,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
