### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by rick-syncbak** [golang/vscode-go#3233]
gopls version: v0.15.1/go1.21.6
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code win32
initialization error: Error: invalid WorkspaceFolder.URI: DocumentURI scheme is not 'file': C:/\Users\rick\codebook
issue timestamp: Thu, 07 Mar 2024 20:42:15 GMT
restart history:
Thu, 07 Mar 2024 20:42:09 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

:warning: dialog

<pre>gopls client: couldn't create connection to server.
  Message: invalid WorkspaceFolder.URI: DocumentURI scheme is not 'file': C:/\Users\rick\codebook
  Code: 0 </pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after running for 60022ms
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, this looks like a legitimate error in configuration.

How did you start VS Code, and how did you open this folder?
