### ISSUE TITLE
VS Code autocomplete very slow, consuming high memory / CPU.

### ISSUE THREAD

**Issue by mjyeaney** [golang/vscode-go#325]
### What version of Go, VS Code & VS Code Go extension are you using?

NOTE: I'm using VSCode on Windows, but opening solution in WSL Ubuntu 18.04. VS Code extension is installed in WSL.

- Run `go version` to get version of Go
	- go version go1.14.4 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.47.0 d5e9aa0227e057a60c82568bf31c04730dc15dcd x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.15.1
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mjyeaney/.cache/go-build"
GOENV="/home/mjyeaney/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mjyeaney/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/c/Projects/IL6-Core/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build309892363=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

None - stock config

### Describe the bug

When using a Go project that uses modules, the default installation of the Go Extension is causing very laggy autocomplete (3-5 seconds) and spinning CPU cycles while hovering. Eventually, the `gocode-gomod` (IIRC) process will eventually consume upwards of ~1GB RAM (however, I can't figure out what is triggering this).

Tried switching to `gopls` as recommended, however this breaks current project module imports immediately stating that "could not import XXX (no package for import XXX)". Tried running `go clean -modcache` and `go mod tidy -v`, but doesn't help. 

Not sure what else to try - not sure if this is a known issue, or I'm missing a RTFM issue.

**Comment by stamblerre** [comment]
> Tried switching to gopls as recommended, however this breaks current project module imports immediately stating that "could not import XXX (no package for import XXX)". Tried running go clean -modcache and go mod tidy -v, but doesn't help.

I think this is the right solution here. Let's investigate why `gopls` isn't working. The most common reason for errors is that you have to open your directory at the root of your module (the directory containing the `go.mod`). If you work in a multi-module repository, you can add the module root to your workspace through File -> Add Folder to Workspace.

**Comment by mjyeaney** [comment]
So here's the basic layout:

```
/ProjectRoot
--> /tests/
  --> /helpers (package, existing code)
  --> /tests (I'm coding in here)
  --> go.mod
  --> go.sum
```

However, even packages which aren't part of my code base (e.g., `github.com/stretchr/testify/assert`) report the same error. Feels like I'm missing something fundamental with where the lang server is looking. I'm not super familiar with it's config...any pointers / things to check?

**Comment by stamblerre** [comment]
It sounds like you need to be opening the `/ProjectRoot/tests` directory when you open VS Code (`code /ProjectRoot/tests` if you're starting from the command-line). A quick way to get logs, if you're able to share them, is by running `gopls -rpc.trace -v check path/to/file.go`.

**Comment by mjyeaney** [comment]
Here's that trace:

```
2020/07/10 12:44:08 Info:2020/07/10 12:44:08 Build info
----------
golang.org/x/tools/gopls 0.4.3
    golang.org/x/tools/gopls@v0.4.3 h1:irz7Q+XdHNECamFKbNWKvMV2Ak6zBbwdwbZndG4545I=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.2.0 h1:KU7oHjnv3XNWfa5COkzUifxZmxp1TyI7ImMXqFxLwvQ=
    golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e h1:vcxGaoTs7kV8m5Np9uUNQin4BrLOthgV7252N8V+FwY=
    golang.org/x/tools@v0.0.0-20200708181441-6004c8539734 h1:Vc0Vx98oU/O3+qPQ36fnTT5UduS55KLh2uSGbL7mqEo=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.4 linux/amd64


2020/07/10 12:44:09 Info:2020/07/10 12:44:09 go env for /mnt/c/Projects/IL6-Core/test
(valid build configuration = true)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mjyeaney/.cache/go-build"
GOENV="/home/mjyeaney/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/mjyeaney/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/c/Projects/IL6-Core/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build646370267=/tmp/go-build -gno-record-gcc-switches"

2020/07/10 12:44:09 Info:2020/07/10 12:44:09 go/packages.Load
        snapshot=0
        directory=/mnt/c/Projects/IL6-Core/test
        query=[./... builtin]
        packages=7
/mnt/c/Projects/IL6-Core/test/terraform/03_networking_mgmt_subnet_test.go:15:2: struct field tag `10.200.70.0/24` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```

This interesting...I don't see the `import` errors in here - so where are they coming from since they only show up when using the lang server?

![image](https://user-images.githubusercontent.com/1410150/87178571-5802dc00-c2ab-11ea-915e-661763e4ae1f.png)

**Comment by stamblerre** [comment]
My guess is that you've opened the wrong directory in VS Code, as I mentioned above. Please confirm if that's not the case.
The next step would be to share your `gopls` logs in VS Code. The steps to do so are described here: https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs.

**Comment by mjyeaney** [comment]
So, opening the project in the nested `tests` folder does fix the problem, but that is a big discrepancy against the OSX experience (and also makes it a challenge to look at other files which I need to reference visually that are in the tree). 

What changed, and is this expected behavior in code based which have multiple modules?

**Comment by stamblerre** [comment]
As described in https://github.com/golang/vscode-go/issues/325#issuecomment-656761360, you can open a top-level directory and add each module to your workspace. I think this should address your use case.

There is no discrepancy between OSes as far as I know. It is the current expected behavior with `gopls`, but we are working on addressing this before we mark `gopls` as stable. More details about the workspace root can be found here: https://github.com/golang/go/issues/36899.

**Comment by mjyeaney** [comment]
Appreciate the info - good to close.
