### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by fuzzybook** [golang/vscode-go#3252]
gopls version: v0.15.2/go1.19.3
gopls flags: 
update flags: proxy
extension version: 0.41.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 14 Mar 2024 13:20:17 GMT
restart history:
Thu, 14 Mar 2024 13:20:00 GMT: activation (enabled: true)
Thu, 14 Mar 2024 13:20:21 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 6654,
    "TestdataFiles": 0,
    "GoFiles": 5,
    "ModFiles": 1,
    "Dirs": 1222
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "2.017892287s",
  "MemStats": {
    "HeapAlloc": 20949568,
    "HeapInUse": 32423936,
    "TotalAlloc": 352628600
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1213,
      "Largest": 935931,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 187,
          "LargestPackage": 154,
          "CompiledGoFiles": 1209,
          "Modules": 18
        },
        "WorkspacePackages": {
          "Packages": 3,
          "LargestPackage": 3,
          "CompiledGoFiles": 5,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)? You may also want to try recompiling gopls with a more recent version of Go.

![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
