### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by kkoehler** [golang/vscode-go#326]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls did not start. Just started VSCode. That's all...

This is the error:
```
[Error - 18:31:21] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF
```

**Comment by kkoehler** [comment]
Maybe this helps:

---
`console.ts:137 [Extension Host] stack trace: Error: unsupported URI scheme:  (gopls only supports file URIs)	at handleResponse (c:\Users\Kristian\.vscode\extensions\golang.go-0.15.1\node_modules\vscode-jsonrpc\lib\main.js:449:48)	at processMessageQueue (c:\Users\Kristian\.vscode\extensions\golang.go-0.15.1\node_modules\vscode-jsonrpc\lib\main.js:276:17)	at Immediate.<anonymous> (c:\Users\Kristian\.vscode\extensions\golang.go-0.15.1\node_modules\vscode-jsonrpc\lib\main.js:260:13)	at processImmediate (internal/timers.js:439:21)`
---

**Comment by hyangah** [comment]
Thanks for the issue report @kkoehler 
Did you try to open a single file with vscode? Currently `gopls` does not support a single file edit mode, so we need to open the directory where the file is. Can you try it?

A good news is that the next version of `gopls` (0.4.4) will support this use case. Thanks!

**Comment by kkoehler** [comment]
Hi @hyangah 

I opened VSCode via the Windows Start Menu. But you're right, VSCode opens just one file not a folder.
When I open a folder and reopen VSCode everything works.

Thanks,
Kristian

**Comment by hyangah** [comment]
@kkoehler Thanks for the update! I hope this gets handled better with the next `gopls` release. 

Closing.
