### ISSUE TITLE
delve: config output debug binary in setting.json

### ISSUE THREAD

**Issue by hoang-cao-long** [golang/vscode-go#3264]
dlvFlags have suggest --output for debug file but i can't using that
![image](https://github.com/golang/vscode-go/assets/57308712/9047b76b-5701-4599-a271-9e658c686bf1)
Here is my config
![image](https://github.com/golang/vscode-go/assets/57308712/89735dab-c363-410a-ab36-79b0e4968f53)
And I have error
![image](https://github.com/golang/vscode-go/assets/57308712/86e6054f-5e2b-4846-a4d4-227cfaf6fac8)

**Comment by findleyr** [comment]
Hi, it sounds like you may be using an old version of dlv. Which version of `dlv` do you have installed?

Can you please check  `dlv help`, as suggested by the error message, to see if `--output` is supported?

CC @suzmue
