### ISSUE TITLE
ejhgcblcifncunvevdtidchtleccbtbnbfrehdbnldbkgopls: automated issue report (crash)

### ISSUE THREAD

**Issue by viktorMirev** [golang/vscode-go#3268]
gopls version: v0.14.2/go1.22.0
gopls flags: -logfile /home/user/gopls.log -rpc.trace
update flags: off
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 21 Mar 2024 11:32:19 GMT
restart history:
Thu, 21 Mar 2024 11:31:47 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 1119 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
Please clarify the bug report and re-open if this is still a problem.
