### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by mokaris** [golang/vscode-go#3282]
gopls version: v0.15.2/go1.21.3
gopls flags: -rpc.trace serve --debug=localhost:6060 -v -logfile /path/to/log/file
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Tue, 26 Mar 2024 05:00:17 GMT
restart history:
Tue, 26 Mar 2024 05:00:13 GMT: activation (enabled: true)
Tue, 26 Mar 2024 05:00:17 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 6422,
    "TestdataFiles": 11,
    "GoFiles": 412,
    "ModFiles": 2,
    "Dirs": 754
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.3",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "5.805684792s",
  "MemStats": {
    "HeapAlloc": 114208856,
    "HeapInUse": 171671552,
    "TotalAlloc": 1385002128
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 5749,
      "Largest": 701525,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 1267,
          "LargestPackage": 155,
          "CompiledGoFiles": 5865,
          "Modules": 216
        },
        "WorkspacePackages": {
          "Packages": 159,
          "LargestPackage": 23,
          "CompiledGoFiles": 518,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
