### ISSUE TITLE
Support for context based Refactoring

### ISSUE THREAD

**Issue by imkernel** [golang/vscode-go#329]
**Is your feature request related to a problem? Please describe.**
vscode is the most used editor by golang survey and currently it lacks the refactoring feature.

**Describe the solution you'd like**

1. When a variable, function or any identifier  is selected there should be an option to refactor the variable, the result should be that all the references to this identifier in the current context is refactored
2. When a piece of code is selected there should be an option to extract it as a function

**Describe alternatives you've considered**
`vim-go` is an alternative editor plugin that has this functionality.

**Additional context**
This issue was tracked in microsoft vscode repo, the issue is https://github.com/microsoft/vscode-go/issues/1173

**Comment by stamblerre** [comment]
The issue you linked above was resolved. The features you describe are supported via these commands: https://github.com/golang/vscode-go/blob/master/docs/features.md#refactor. These features do not work with Go modules, but we are adding support for them in `gopls`, and they will be available in `gopls/v0.4.4`: https://github.com/golang/go/issues/37170.

**Comment by imkernel** [comment]
@stamblerre should this issue be closed then?

**Comment by stamblerre** [comment]
Yep, closing.
