### ISSUE TITLE
go into polyglot

### ISSUE THREAD

**Issue by JCzz** [golang/vscode-go#3310]
Are you considering to get go in to polyglot: https://code.visualstudio.com/docs/languages/polyglot

Projects like this runs in Jupyter Notebook: https://github.com/janpfeifer/gonb

Regards
Christian

**Comment by hyangah** [comment]
`gonb` looks very cool!
It looks like happening between gonb and polyglot dotnet/interactive#3511,
and I think they are better positioned than this extension.

If there is any part of `gopls` reusable/extendable to assist the integration,
don't hesitate to open an issue in the golang/go issue tracker for discussion.
(cc @janpfeifer)
