### ISSUE TITLE
gopls: automated issue report (crash):  gopls built with go1.18.1

### ISSUE THREAD

**Issue by apexDream** [golang/vscode-go#3311]
gopls version: v0.15.2/go1.18.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Wed, 03 Apr 2024 19:41:45 GMT
restart history:
Wed, 03 Apr 2024 18:49:05 GMT: activation (enabled: true)
Wed, 03 Apr 2024 18:59:55 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 183,
    "TestdataFiles": 0,
    "GoFiles": 79,
    "ModFiles": 1,
    "Dirs": 46
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "4.114357s",
  "MemStats": {
    "HeapAlloc": 33414192,
    "HeapInUse": 61079552,
    "TotalAlloc": 437838744
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1594,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 278,
          "LargestPackage": 148,
          "CompiledGoFiles": 1634,
          "Modules": 34
        },
        "WorkspacePackages": {
          "Packages": 20,
          "LargestPackage": 18,
          "CompiledGoFiles": 122,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report. @apexDream  Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

Looks like the gopls crashed after upgrade.

**Comment by hyangah** [comment]
I noticed the gopls was compiled with go1.18.1. 
If you are working on a project that require a newer version of go, can you please upgrade go and rebuild gopls?
Thanks!
