### ISSUE TITLE
Setting go.showWelcome to false does not disable showing the welcome

### ISSUE THREAD

**Issue by sfiggins** [golang/vscode-go#3319]
After setting go.showWelcome to false in User or Workspace settings, the go welcome page is still shown.

Noted in version 0.39.1.

I believe that this is because getConfiguration returns a configuration object rather than a value, [so the check on the setting](https://github.com/golang/vscode-go/blob/ad37a53c96677da8fb620e2320bc52a15268622c/extension/src/welcome.ts#L34-L36) always returns true. 

I think this could work:

```typescript
		if (!extensionInfo.isInCloudIDE && vscode.workspace.getConfiguration('go').get('showWelcome')) {
			showGoWelcomePage();
		}
```

Though it might be easier to add a test on this if it used getGoConfig to retrieve the configuration. The check could also be moved to shouldShowGoWelcome.

**Comment by hyangah** [comment]
Thanks @sfiggins!
Sent a change and added a test. Thanks for the good suggestion!

**Comment by exodustx0** [comment]
It should be noted that the implemented fix didn't just fix and move the if-condition, it also changed its logic: previously, if `isInCloudIDE`, it would ignore `go.showWelcome` and *not show,* whereas now, if `isInCloudIDE`, it would ignore `go.showWelcome` and *show.*

**Comment by hyangah** [comment]
Thanks @exodustx0 That's obviously a bug. v0.41.4 released now should address the issue. Let us know if you are still seeing the issue.
