### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by marwankous** [golang/vscode-go#3321]
gopls version: v0.13.2/go1.17
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 07 Apr 2024 05:51:46 GMT
restart history:
Sun, 07 Apr 2024 02:54:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 1142,
    "TestdataFiles": 0,
    "GoFiles": 270,
    "ModFiles": 1,
    "Dirs": 311
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GoVersion": "go1.17",
  "GoplsVersion": "v0.13.2",
  "InitialWorkspaceLoadDuration": "1.29870847s",
  "MemStats": {
    "HeapAlloc": 97317448,
    "HeapInUse": 144056320,
    "TotalAlloc": 1297257200
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 3667,
      "Largest": 9258641,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.17",
        "AllPackages": {
          "Packages": 694,
          "LargestPackage": 126,
          "CompiledGoFiles": 3871,
          "Modules": 151
        },
        "WorkspacePackages": {
          "Packages": 43,
          "LargestPackage": 103,
          "CompiledGoFiles": 477,
          "Modules": 1
        },
        "Diagnostics": 353
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by adonovan** [comment]
Please update both your Go toolchain and gopls to the latest version: both of the ones your are using are now very old.
