### ISSUE TITLE
save file is so slow

### ISSUE THREAD

**Issue by stingshen** [golang/vscode-go#3326]
Type: <b>Bug</b>

save go file

Extension version: 0.41.2
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:25:57.039Z)
OS version: Linux x64 5.4.0-176-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 3|
|Memory (System)|62.60GB (48.67GB free)|
|Process Argv|--unity-launch --crash-reporter-id f9695126-44a9-470f-a4e3-ff931a337ec9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
g1icg217:30999571
f3je6385:31013174

```

</details>

**Comment by findleyr** [comment]
@stingshen, thanks for the report.  Can you please answer the following questions:

-  What is the output of `gopls -v version`?
- Are you working in an open-source repo?
- Could you please capture logs from a brief that reproduces the slowness? (note, logs may snippets of your code, so you may want to scrub them; I really just care about rpc timings
https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information
- Does downgrading to gopls@v0.14.2 fix the issue for you? `go install golang.org/x/tools/gopls@v0.14.2`

**Comment by stingshen** [comment]
> @stingshen, thanks for the report. Can you please answer the following questions:
> 
> * What is the output of `gopls -v version`?
> * Are you working in an open-source repo?
> * Could you please capture logs from a brief that reproduces the slowness? (note, logs may snippets of your code, so you may want to scrub them; I really just care about rpc timings
>   https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information
> * Does downgrading to gopls@v0.14.2 fix the issue for you? `go install golang.org/x/tools/gopls@v0.14.2`

Thank you for the reply. The issue isn't reproducible now. Close the issue. I will answer your questions if it reproduces again.
