### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by HideOnBush1999** [golang/vscode-go#3329]
gopls version: v0.15.2/go1.20.3
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Thu, 11 Apr 2024 02:39:42 GMT
restart history:
Thu, 11 Apr 2024 02:32:09 GMT: activation (enabled: true)
Thu, 11 Apr 2024 02:32:32 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 28,
    "TestdataFiles": 0,
    "GoFiles": 4,
    "ModFiles": 1,
    "Dirs": 15
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.3",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.4586492s",
  "MemStats": {
    "HeapAlloc": 29431240,
    "HeapInUse": 41820160,
    "TotalAlloc": 242748920
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 987,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.1",
        "AllPackages": {
          "Packages": 145,
          "LargestPackage": 146,
          "CompiledGoFiles": 986,
          "Modules": 6
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 4,
          "CompiledGoFiles": 4,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
