### ISSUE TITLE
Use the new Testing API to show coverage counts for files and "Run With Coverage" button

### ISSUE THREAD

**Issue by dundee** [golang/vscode-go#3331]
**Is your feature request related to a problem? Please describe.**

VSCode 1.88 comes with new [testing API ](https://code.visualstudio.com/api/extension-guides/testing#test-coverage). 
New button for "Run With Coverage" can be added and also a new box with visual representation of coverage of individual files was added.

**Describe the solution you'd like**
Go extension should add the "Run With Coverage" button and box for coverage counts.

**Additional context**

<img width="1349" alt="Screenshot 2024-04-11 at 2 03 27" src="https://github.com/golang/vscode-go/assets/27106/4b96c3fb-62bd-4a4f-8564-8825a3bcf162">

**Comment by adonovan** [comment]
Related:
- https://github.com/golang/go/issues/59445
- https://github.com/golang/vscode-go/issues/3022
- https://github.com/golang/vscode-go/issues/2504

**Comment by firelizzard18** [comment]
This is addressed by #3523 as of today.
