### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by itsshreyashk** [golang/vscode-go#3334]
gopls version: v0.15.2/go1.18.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code - Insiders linux
initialization error: undefined
issue timestamp: Fri, 12 Apr 2024 13:13:43 GMT
restart history:
Fri, 12 Apr 2024 13:13:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 3,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "483.347974ms",
  "MemStats": {
    "HeapAlloc": 13830400,
    "HeapInUse": 20815872,
    "TotalAlloc": 182191112
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 860,
      "Largest": 395043,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.1",
        "AllPackages": {
          "Packages": 133,
          "LargestPackage": 146,
          "CompiledGoFiles": 856,
          "Modules": 2
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 2
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, please install gopls with a more recent version of Go (Go 1.21 or later, ideally).

I suspect this is a known crash with older Go versions.

**Comment by itsshreyashk** [comment]
alrighty
