### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by tomoyukikino** [golang/vscode-go#3335]
gopls version: v0.15.2/go1.20.4
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sat, 13 Apr 2024 08:31:28 GMT
restart history:
Sat, 13 Apr 2024 08:31:13 GMT: activation (enabled: true)
Sat, 13 Apr 2024 08:31:36 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 2667 [running]:
go/types.NewChecker(0x0%3F, 0xc00031f9c0, 0xc000d116d0, 0x0%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc001221ef0, {0xc001e916b0, 0x3, 0x3})
	  analysis.go:1028  0x73d
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc001221ef0, {0x1e500f8%3F, 0xc0010685d0})
	  analysis.go:810  0x218
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc001221ef0, {0x1e500f8%3F, 0xc0010685d0})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 42,
    "TestdataFiles": 0,
    "GoFiles": 7,
    "ModFiles": 1,
    "Dirs": 21
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.2",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "1.448162468s",
  "MemStats": {
    "HeapAlloc": 16747976,
    "HeapInUse": 25665536,
    "TotalAlloc": 236328368
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1125,
      "Largest": 395043,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 175,
          "LargestPackage": 154,
          "CompiledGoFiles": 1123,
          "Modules": 11
        },
        "WorkspacePackages": {
          "Packages": 5,
          "LargestPackage": 3,
          "CompiledGoFiles": 9,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
This is fixed in gopls@v0.15.3. Please upgrade gopls with the following command. I also recommend upgrading your Go version to Go 1.21 or later.

```
go install golang.org/x/tools/gopls@latest
```
