### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by lapulgaatomica** [golang/vscode-go#3336]
gopls version: v0.15.2/go1.18.1
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 14 Apr 2024 06:10:42 GMT
restart history:
Sun, 14 Apr 2024 06:10:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.2" (should be something like "go1.12")

goroutine 881 [running]:
go/types.NewChecker(0x0%3F, 0xc0001a1400, 0xc001373ea0, 0x0%3F)
	  check.go:240  0x279
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc0009f4b00, {0xc0006ceab8, 0x1, 0x1})
	  analysis.go:1028  0x6f1
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc0009f4b00, {0x1031b58, 0xc00038ae40})
	  analysis.go:810  0xd9
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc0009f4b00, {0x1031b58%3F, 0xc00038ae40})
	  analysis.go:672  0x145
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xda
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 161,
    "TestdataFiles": 0,
    "GoFiles": 81,
    "ModFiles": 70,
    "Dirs": 100
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "307.069458ms",
  "MemStats": {
    "HeapAlloc": 3293528,
    "HeapInUse": 6135808,
    "TotalAlloc": 42906768
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 0,
      "Largest": 0,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
This is fixed in gopls@v0.15.3. Please upgrade gopls with the following command. I also recommend upgrading your Go version to Go 1.21 or later.

```
go install golang.org/x/tools/gopls@latest
```
