### ISSUE TITLE
debug: spurious error message about killing process when 'Run without Debug' ends normally

### ISSUE THREAD

**Issue by liyisker** [golang/vscode-go#334]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- <go version go1.14.4 windows/amd64>
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- <1.47.0
d5e9aa0227e057a60c82568bf31c04730dc15dcd
x64>
- Check your installed extensions to get the version of the VS Code Go extension 
	- <0.15.1>
- Run `go env` to get the go development environment details
```
	- <set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\liyis\AppData\Local\go-build
set GOENV=C:\Users\liyis\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Go\PATH\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Go\PATH
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\liyis\AppData\Local\Temp\go-build222914178=/tmp/go-build -gno-record-gcc-switches>

```
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
{
    "extensions.autoUpdate": false,
    "files.autoSave": "afterDelay",
    "editor.fontSize": 17,
    "go.useLanguageServer": true,
    "workbench.colorTheme": "Ayu Light",
    "python.languageServer": "Pylance",
    "go.coverOnSave": true,
    "go.coverOnSingleTestFile": true,
    "go.coverOnSingleTest": true,
    "go.gocodeAutoBuild": true,
    "go.enableCodeLens": {
        "references": false,
        "runtest": true
    },
}
```
### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
1. Go to 'Run'
2. Click on 'Run Without Debugging'
3. Error killing process 7664: Error: Command failed: taskkill /pid 7664 /T /F
����: û���ҵ����� "7664"��

### Screenshots or recordings
All settings are default, and appear after the 1.5 plug-in version. I have tried to reinstall the system, but it cannot be solved.
        Although there is an error message, No problem with function
<img width="801" alt="捕获" src="https://user-images.githubusercontent.com/26356428/87272841-fc825980-c509-11ea-828f-c961f2ceb7c6.PNG">

**Comment by hyangah** [comment]
@liyisker Thanks for the bug report. 

It would be clear if we could see the error message. I guess this is a bug related to the process clean up logic added in 1.15.

https://github.com/golang/vscode-go/blob/371dfec4a15946d12384db39a111b8dc57bccb4b/src/debugAdapter/goDebug.ts#L2317

When the program terminated normally, this cleanup shouldn't trigger process killing because it's already gone.
I think we can check the exitCode since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44703 is released.
