### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by archerwq** [golang/vscode-go#3345]
gopls version: v0.15.3/go1.20.4
gopls flags: -rpc.trace serve --debug=localhost:6060 -run=lint
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: Error: write EPIPE
issue timestamp: Thu, 18 Apr 2024 04:00:01 GMT
restart history:
Thu, 18 Apr 2024 04:00:01 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 1397,
    "TestdataFiles": 0,
    "GoFiles": 113,
    "ModFiles": 1,
    "Dirs": 309
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.20.4",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "352.474852ms",
  "MemStats": {
    "HeapAlloc": 3697016,
    "HeapInUse": 6651904,
    "TotalAlloc": 41607840
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1,
      "Largest": 370,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.20.4",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@archerwq Can you remove `-run=lint` flag from your `"go.languageServerFlags"` setting?
