### ISSUE TITLE
gopls: crash due to use of workspace folders with non-file uri scheme

### ISSUE THREAD

**Issue by gilde1337** [golang/vscode-go#3368]
gopls version: v0.15.3/go1.22.2
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code win32
initialization error: Error: invalid WorkspaceFolder.URI: DocumentURI scheme is not 'file': decompileFs:/
issue timestamp: Fri, 26 Apr 2024 17:59:38 GMT
restart history:
Fri, 26 Apr 2024 17:59:35 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 0,
    "TestdataFiles": 0,
    "GoFiles": 0,
    "ModFiles": 0,
    "Dirs": 3
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.2",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "413.9466ms",
  "MemStats": {
    "HeapAlloc": 2536344,
    "HeapInUse": 4997120,
    "TotalAlloc": 10544536
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 0,
      "Largest": 0,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks @gilde1337 Are you using the decompiler extension, while working on Go files in other workspace folders?

Looks like the extension is registering a workspace folder over this virtual file system
https://github.com/tintinweb/vscode-decompiler/blob/master/src/features/decompile.js#L88
but gopls cannot handle it.

cc @golang/tools-team

**Comment by findleyr** [comment]
I don't think this is still waiting for info: it was actionable.

**Comment by adonovan** [comment]
@hyangah fixed it in https://github.com/golang/go/issues/67225, I think.
