### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by robertsdpg** [golang/vscode-go#3375]
gopls version: v0.15.3/go1.22.2
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code win32
initialization error: Error: invalid WorkspaceFolder.URI: DocumentURI scheme is not 'file': gitlens://7b22726566223a2230613364373137326539326630626232393363323937363334613861653063623332306338643532222c227265706f50617468223a22633a2f55736572732f726f6265722f4f6e6544726976652f446f63756d656e74732f6c6c616d6133227d/c:/Users/rober/OneDrive/Documents/llama3%3F{"ref":"0a3d717"}
issue timestamp: Thu, 02 May 2024 22:44:46 GMT
restart history:
Thu, 02 May 2024 22:44:37 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 49,
    "TestdataFiles": 0,
    "GoFiles": 0,
    "ModFiles": 0,
    "Dirs": 20
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.2",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "433.9225ms",
  "MemStats": {
    "HeapAlloc": 2485888,
    "HeapInUse": 4931584,
    "TotalAlloc": 10385608
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 0,
      "Largest": 0,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.2",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report @robertsdpg 

Can you teach us how you configured your workspace?

It looks like GitLens' virtual folder is registered as a vscode workspace folder, but I don't know what functionality of GitLens enables this setup.

I think our extension and the language server should be prepared and defensive about virtual workspace folder.
This is the same issue as https://github.com/golang/vscode-go/issues/3368
