### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by mukuls9971** [golang/vscode-go#3379]
gopls version: v0.15.3/go1.22.1
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Wed, 08 May 2024 12:14:18 GMT
restart history:
Wed, 08 May 2024 12:12:41 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: file not found for pos = 1 (-)

goroutine 40029 [running]:
go/types.(*Checker).handleBailout(0x1400efbc000, 0x14000b67878)
	  check.go:367  0x9c
panic({0x1030cccc0%3F, 0x14004e3cec0%3F})
	  panic.go:770  0x124
go/types.(*Checker).fileFor(0x1400efbc000, 0x1)
	  version.go:131  0x154
go/types.(*Checker).allowVersion(0x1400efbc000, 0x10317e9e0%3F, {0x103249380%3F, 0x140045338a0%3F}, {0x102d890db, 0x6})
	  version.go:97  0x64
go/types.(*Checker).genericExprList(0x1400efbc000, {0x140045344d0, 0x1, 0x14004536258%3F})
	  call.go:383  0xb64
go/types.(*Checker).callExpr(0x1400efbc000, 0x14000aab000, 0x140045385c0)
	  call.go:303  0x560
go/types.(*Checker).exprInternal(0x1400efbc000, 0x0, 0x14000aab000, {0x10324f0b0, 0x140045385c0}, {0x0, 0x0})
	  expr.go:1374  0xd0
go/types.(*Checker).rawExpr(0x1400efbc000, 0x0, 0x14000aab000, {0x10324f0b0%3F, 0x140045385c0%3F}, {0x0%3F, 0x0%3F}, 0x1)
	  expr.go:979  0x12c
go/types.(*Checker).genericExpr(0x1400efbc000, 0x14000aab000, {0x10324f0b0%3F, 0x140045385c0%3F})
	  expr.go:1520  0x48
go/types.(*Checker).genericExprList(0x1400efbc000, {0x14004538600, 0x3, 0x14004536210%3F})
	  call.go:444  0xaa8
go/types.(*Checker).callExpr(0x1400efbc000, 0x14000aaae80, 0x14004538640)
	  call.go:303  0x560
go/types.(*Checker).exprInternal(0x1400efbc000, 0x0, 0x14000aaae80, {0x10324f0b0, 0x14004538640}, {0x0, 0x0})
	  expr.go:1374  0xd0
go/types.(*Checker).rawExpr(0x1400efbc000, 0x0, 0x14000aaae80, {0x10324f0b0%3F, 0x14004538640%3F}, {0x0%3F, 0x0%3F}, 0x0)
	  expr.go:979  0x12c
go/types.(*Checker).multiExpr(0x1400efbc000, {0x10324f0b0, 0x14004538640}, 0x1)
	  expr.go:1532  0x60
go/types.(*Checker).initVars(0x1400efbc000, {0x14004e3ce30, 0x2, 0x2}, {0x140045344e0, 0x1, 0x1}, {0x0, 0x0})
	  assignments.go:408  0x104
go/types.(*Checker).shortVarDecl(0x1400efbc000, {0x103249320, 0x1400e17b5f0}, {0x14004533740, 0x2, 0x14007edbf80%3F}, {0x140045344e0, 0x1, 0x1})
	  assignments.go:556  0x6f4
go/types.(*Checker).stmt(0x1400efbc000, 0x0, {0x10324f260, 0x14004538680})
	  stmt.go:473  0x10d4
go/types.(*Checker).stmtList(0x1400efbc000, 0x0, {0x14000bfc900%3F, 0x0%3F, 0x14006b21200%3F})
	  stmt.go:121  0x88
go/types.(*Checker).funcBody(0x1400efbc000, 0x10324c210%3F, {0x140005c4d40%3F, 0x140000c6380%3F}, 0x14002c197c0, 0x14004530fc0, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x21c
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x44
go/types.(*Checker).processDelayed(0x1400efbc000, 0x0)
	  check.go:467  0x12c
go/types.(*Checker).checkFiles(0x1400efbc000, {0x14008588080, 0x5, 0x8})
	  check.go:411  0x188
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0x1400d9224e0, {0x1032509e8, 0x1400dcf5f20}, 0x1400bfd8480)
	  check.go:1532  0x764
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0x1400d9224e0, {0x1032509e8, 0x1400dcf5f20}, 0x0, {0x14000b3f800, 0x58})
	  check.go:563  0x534
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:414  0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 38297
	  errgroup.go:75  0x98
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 2544,
    "TestdataFiles": 0,
    "GoFiles": 2091,
    "ModFiles": 2,
    "Dirs": 539
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.1",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "1.428285041s",
  "MemStats": {
    "HeapAlloc": 61482488,
    "HeapInUse": 89014272,
    "TotalAlloc": 1114787096
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2758,
      "Largest": 879006,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 508,
          "LargestPackage": 170,
          "CompiledGoFiles": 2761,
          "Modules": 62
        },
        "WorkspacePackages": {
          "Packages": 14,
          "LargestPackage": 5,
          "CompiledGoFiles": 28,
          "Modules": 1
        },
        "Diagnostics": 12
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
This appears to be another instance of golang/go#66790.

Closing as a duplicate.
