### ISSUE TITLE
New Feature: Copy Go Package Path

### ISSUE THREAD

**Issue by xhd2015** [golang/vscode-go#3394]
**Is your feature request related to a problem? Please describe.**
When working with go code, it is quite common to import packages by path, however I found there were no quick way to do this. I must go to the dir of the package I want to import, copy it's relative path, and  concatenate that with the go module path to form a package path. It's just so painful how many times I needed to do this, and it's also too ineffective! 

**Describe the solution you'd like**
Add a quick action in vscode-go plugin to copy the go package path with one click.

**Describe alternatives you've considered**
As described above, previously I manually concatenate strings together.

**Additional context**

I actually have made a vscode plugin that already does this,  want to check here if it is generally needed by the community. If so, we may add it to vscode-go.

Step 1: copy
<img width="394" alt="image" src="https://github.com/golang/vscode-go/assets/14964938/8e8d85a5-4674-4d44-b1da-71bd45a85280">

Step 2: paste
<img width="766" alt="image" src="https://github.com/golang/vscode-go/assets/14964938/a2624dfe-db99-45ca-b527-2503a15909d6">

The repository is at https://github.com/xhd2015/VSCode-Ext-Copy-Go-Package-Path .

I'll later propose a PR for reviewing purpose.

Thanks.

**Comment by hyangah** [comment]
Good to develop and share the extension. I think it's good to have it a separate extension.

**Ideally,** users shouldn't worry about imports - users just start to use the package, and the language server should be able to auto-import the package (especially those already in the workspace). For example, in the following example, I didn't import `counter` package yet, but the language server recognizes the package and includes suggestions based on the API of the package. As I accept one of them, the language server provides the extra edit for the import block. This is the workflow we want to support.

![Screenshot 2024-05-20 at 10 05 35 AM](https://github.com/golang/vscode-go/assets/4999471/35d91e76-a428-48c0-8aef-b1280eda395c)

We understand that currently some bugs in package imports sometimes prevent this ideal workflow. The gopls team is actively working on fixing and improving the import logic.

**Comment by xhd2015** [comment]
Agreed, I'll publish the extension alone. Thansk.

**Comment by xhd2015** [comment]
In case if anyone have similar needs, this is the standalone extension: https://marketplace.visualstudio.com/items?itemName=xhd2015.copy-go-package-path
