### ISSUE TITLE
Wrap long lines using golines

### ISSUE THREAD

**Issue by sjackman** [golang/vscode-go#3397]
**Is your feature request related to a problem? Please describe.**
I'd like to wrap long lines.

**Describe the solution you'd like**
I'd like to wrap long lines using `golines` when I save a file.

**Describe alternatives you've considered**
- Configure `pre-commit` to run `golines` (see https://github.com/segmentio/golines/blob/master/.pre-commit-hooks.yaml)
- Configure `emeraldwalk.runonsave` to run `golines` (see https://github.com/golang/vscode-go/issues/847#issuecomment-777566491)

**Additional context**
On 2021-04-09 in https://github.com/golang/vscode-go/issues/847#issuecomment-816992225, @stamblerre wrote…
> You can now setting `"go.formatTool": "golines"` and it will work together with `gopls`. Closing.

but when I set this configuration option `go.formatTool": "golines`, I get the error message:
`Value is not accepted. Valid values: "default", "gofmt", "goimports", "goformat", "gofumpt", "custom".`

**Comment by hyangah** [comment]
```
    "go.formatTool": "custom",
    "go.alternateTools": {
        "customFormatter": "golines" <--- or exact path like "~/go/bin/golines". 
    }
}
```

**Comment by hyangah** [comment]
Add this to https://github.com/golang/vscode-go/wiki/features#custom-formatter 
and https://github.com/golang/vscode-go/wiki/faq

**Comment by sjackman** [comment]
Nice! Thank you for the quick and helpful response, @hyangah! 😁
