### ISSUE TITLE
all: require go 1.21+ for tools installation

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#3411]
The upcoming gopls requires go1.21+ for installation.
https://github.com/golang/go/issues/65917

Update the min version in the README and tools installation logic.

**Comment by findleyr** [comment]
Putting this in the v0.42.0 milestone. @hyangah please remilestone if that is incorrect.

**Comment by sonvirgo** [comment]
How to manual install?
Install @latest will fail.
No version compatibility info?

**Comment by daniel-santos** [comment]
> How to manual install? Install [@latest](https://github.com/latest) will fail. No version compatibility info? `Failed to find a go command (go1.21.0 or newer) needed to install tools. The go command (C:\Program Files\Go\bin\go.exe) is too old (go1.19.2). If your project requires a Go version older than go1.21.0, please manually install the tools or, use the "go.toolsManagement.go" setting to configure a different go command (go 1.21.0+) to be used for tools installation. See https://github.com/golang/vscode-go/issues/3411.`

Yes, exactly. The error message should list the "required" tools.

Keep in mind that not every software project *needs* or ***should use*** rolling releases! In fact, it is a horrific strategy for the stability of critical environments. I need exactly 1.19 for my current release cycle, so this shouldn't be made so difficult.

**Comment by sonvirgo** [comment]
> > How to manual install? Install [@latest](https://github.com/latest) will fail. No version compatibility info? `Failed to find a go command (go1.21.0 or newer) needed to install tools. The go command (C:\Program Files\Go\bin\go.exe) is too old (go1.19.2). If your project requires a Go version older than go1.21.0, please manually install the tools or, use the "go.toolsManagement.go" setting to configure a different go command (go 1.21.0+) to be used for tools installation. See https://github.com/golang/vscode-go/issues/3411.`
> 
> Yes, exactly. The error message should list the "required" tools.
> 
> Keep in mind that not every software project _needs_ or _**should use**_ rolling releases! In fact, it is a horrific strategy for the stability of critical environments. I need exactly 1.19 for my current release cycle, so this shouldn't be made so difficult.

I ask chatGPT then make a guess to install each dependency one by one. From the lowest version. It is nightmare when setup new vscode machine.

**Comment by recursionbane** [comment]
These are the tools installed as of v1.99.3:

```
[info] Installing 2 tools at <GOPATH>
[info]   gopls
[info]   staticcheck
[info] 
[info] Installing golang.org/x/tools/gopls@latest SUCCEEDED
[info] Installing honnef.co/go/tools/cmd/staticcheck@latest SUCCEEDED
[info] 
[info] All tools successfully installed. You are ready to Go. :)
[info] Try to start language server - activation (enabled: true)
[info] Running language server gopls(v0.20.0/go1.24.9)
```
