### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by DarwinOL** [golang/vscode-go#3426]
gopls version: v0.15.3/go1.21.6
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Thu, 20 Jun 2024 12:29:31 GMT
restart history:
Thu, 20 Jun 2024 12:29:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

TREND anitivirus detected a Ransomware program.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 7:29:20 AM] 2024/06/20 07:29:20 go info for C:\Projects\Innova-Drilling\API\icp-api
(view type GoModView)
(root dir C:\Projects\Innova-Drilling\API\icp-api)
(go version go version go1.21.6 windows/amd64)
(build flags: [])
(go env: {GOOS:windows GOARCH:amd64 GOCACHE:C:\Users\Darwin\AppData\Local\go-build GOMODCACHE:C:\Users\Darwin\go\pkg\mod GOPATH:C:\Users\Darwin\go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:21 GoVersionOutput:go version go1.21.6 windows/amd64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])

[Info  - 7:29:22 AM] 
true
[Info  - 7:29:22 AM] 2024/06/20 07:29:22 go info for C:\Projects\Innova-Drilling\API\icp-api
(view type GoModView)
(root dir C:\Projects\Innova-Drilling\API\icp-api)
(go version go version go1.21.6 windows/amd64)
(build flags: [])
(go env: {GOOS:windows GOARCH:amd64 GOCACHE:C:\Users\Darwin\AppData\Local\go-build GOMODCACHE:C:\Users\Darwin\go\pkg\mod GOPATH:C:\Users\Darwin\go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:21 GoVersionOutput:go version go1.21.6 windows/amd64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])

[Info  - 7:29:24 AM] 
true
[Info  - 7:29:25 AM] 2024/06/20 07:29:25 go info for C:\Projects\Innova-Drilling\API\icp-api
(view type GoModView)
(root dir C:\Projects\Innova-Drilling\API\icp-api)
(go version go version go1.21.6 windows/amd64)
(build flags: [])
(go env: {GOOS:windows GOARCH:amd64 GOCACHE:C:\Users\Darwin\AppData\Local\go-build GOMODCACHE:C:\Users\Darwin\go\pkg\mod GOPATH:C:\Users\Darwin\go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:21 GoVersionOutput:go version go1.21.6 windows/amd64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])

[Info  - 7:29:27 AM] 
true
[Info  - 7:29:27 AM] 2024/06/20 07:29:27 go info for C:\Projects\Innova-Drilling\API\icp-api
(view type GoModView)
(root dir C:\Projects\Innova-Drilling\API\icp-api)
(go version go version go1.21.6 windows/amd64)
(build flags: [])
(go env: {GOOS:windows GOARCH:amd64 GOCACHE:C:\Users\Darwin\AppData\Local\go-build GOMODCACHE:C:\Users\Darwin\go\pkg\mod GOPATH:C:\Users\Darwin\go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:21 GoVersionOutput:go version go1.21.6 windows/amd64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])

[Info  - 7:29:29 AM] 
true
[Info  - 7:29:29 AM] 2024/06/20 07:29:29 go info for C:\Projects\Innova-Drilling\API\icp-api
(view type GoModView)
(root dir C:\Projects\Innova-Drilling\API\icp-api)
(go version go version go1.21.6 windows/amd64)
(build flags: [])
(go env: {GOOS:windows GOARCH:amd64 GOCACHE:C:\Users\Darwin\AppData\Local\go-build GOMODCACHE:C:\Users\Darwin\go\pkg\mod GOPATH:C:\Users\Darwin\go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:21 GoVersionOutput:go version go1.21.6 windows/amd64
 GOWORK: GOPACKAGESDRIVER:})
(env overlay: map[])

[Error - 7:29:31 AM] 

Failed to auto-collect gopls trace: unrecognized crash pattern.

<details><summary>gopls stats -anon</summary>

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks @DarwinOL 
Can you please try two things?

- from the terminal, try
```
   cd C:\Projects\Innova-Drilling\API\icp-api
   gopls.exe stats
```

If the `gopls.exe stats` failed without any output, please check if your system or anti-virus software is blocking the gopls binary. If it outputs anything, please share it with us.

- try the latest prerelease version of gopls 
     `go install golang.org/x/tools/gopls@v0.16.0-pre.2`
   and then, from VS Code Command palette, run "Go: Restart Language Server"
