### ISSUE TITLE
settings wiki refers to deprecated `go.languageServerExperimentalFeatures`

### ISSUE THREAD

**Issue by bgerrity** [golang/vscode-go#3428]
The `go.languageServerExperimentalFeatures` config was [deprecated](https://github.com/golang/vscode-go/blob/master/extension/CHANGELOG.md#v0390---12-jun-2023) some time ago though the wiki makes many [mentions](https://github.com/golang/vscode-go/blob/master/extension/CHANGELOG.md#v0390---12-jun-2023).

**Comment by ansaba** [comment]
cc : @hyangah

**Comment by ansaba** [comment]
@bgerrity The mentioned page is CHANGELOG. Did you intend to point out mention somewhere else ?
