### ISSUE TITLE
Support .templ files with Go auto complete etc

### ISSUE THREAD

**Issue by Req23** [golang/vscode-go#3435]
When trying to work on a `.tmpl` file in a Go project I lose auto completion on structs/packages etc. Also the imports are not found resulting in a warning/error in VSCode.

example:
`/views/login/index.templ`
```
package login

import (
	"app/models"
)

templ LoginForm(errors models.LoginError) {
	<form>
            ***
	<input type="password" name="password" required placeholder="Password" class="input input-bordered w-full"/>
	if len(errors.Password) > 0 {
	    <span class="text-sm text-error">
	       { errors.Password }
            </span>
	}
	 ***
```

`errors.Password` (the errors struct has multiple items, this does not do code auto completion or suggestions)
The package error shows: `No packages found for open file /views/login/index.templ` even though this is incorrect as the package is valid.

I would like the IDE in VSCode to be able to handle all the auto completions etc as if it was a `.go` file.

**Comment by hyangah** [comment]
I guess you are using a-h/templ. Isn't the templ extension able to handle auto-complete? 

https://templ.guide/commands-and-tools/ide-support/#visual-studio-code 

cc @a-h

**Comment by Req23** [comment]
Yeah I am using a-h/templ along with the vscode-go extension. I followed the guide for VSC with vscode-go + a-h/templ. I thought maybe the go side of it was responsible for the imports, auto completes, etc.

**Comment by Req23** [comment]
Auto completion is working with:
`gopls v. 0.15.3`
and
`a-h/templ from @main`

The newest version of gopls and templ didn't seem to work together. Just letting you know what I found.

**Comment by hyangah** [comment]
Thanks @Req23. That's helpful!

I don't know the details on how `templ` LSP server proxies gopls. 
gopls v0.16.0+ started to use `InsertReplaceEdits` if the client sets the capability. (https://github.com/golang/tools/blob/master/gopls/internal/protocol/tsprotocol.go#L1024).
If the `templ` LSP relies on github.com/a-h/protocol, I see that it does not handle `InsertReplaceEdits` type yet
(https://github.com/a-h/protocol/blob/b4eec67c1c223e5a747d39f3d07f62d25236aa4a/language.go#L260).

I think the `templ` LSP server needs to either

1) update the protocol to support `InsertReplaceEdits`, or
2) adjust the client capability so [`InsertReplaceSupport`](https://github.com/a-h/protocol/blob/b4eec67c1c223e5a747d39f3d07f62d25236aa4a/capabilities_client.go#L433) is unset before forwarding the capability. 

Can you please open an issue to the a-h/templ repo? Thanks!

**Comment by hyangah** [comment]
I will close this issue since this is beyond the go extension's scope. 
Thank you so much for filing the issue in a-h/templ!

**Comment by a-h** [comment]
Thanks for raising this. Without this feature, `gopls v0.16.x` won't work properly.

I've updated protocol in https://github.com/a-h/protocol/commit/1e461c188041cecf07f6e39ac25503a1ac1b0513

And I've updated templ in https://github.com/a-h/templ/commit/26c1d79761e7800837caffdd3c8c2abab96e0794

**Comment by a-h** [comment]
Nice investigation @hyangah!
