### ISSUE TITLE
NON retour a la ligne et Non espace 

### ISSUE THREAD

**Issue by MohamedStaili** [golang/vscode-go#3441]
Type: <b>Bug</b>

je peux pas faire un retour a la ligne et une espace

Extension version: 0.41.4
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.75GB free)|
|Process Argv|--crash-reporter-id d4187639-b458-446d-a7ac-2c82857e7ca0|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31082723

```

</details>

**Comment by findleyr** [comment]
Pouvez-vous fournir plus d’informations ? Qu’avez-vous fait, qu’espériez-vous qu’il se passe et que s’est-il réellement passé ?

En attendant, je vais clore ceci, car il n'y a pas suffisamment d'informations pour vous aider.

**Comment by MohamedStaili** [comment]
Lorsque j'ai installé go extension lorsque je fais des retours a la ligne
ou bien des espaces ces actions automatiquement supprimées par l'éditeur vs
