### ISSUE TITLE
debug golang project, breakpoint is invalid

### ISSUE THREAD

**Issue by Jerry-yz** [golang/vscode-go#3447]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <go1.22>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <v1.91>
* Check your installed extensions to get the version of the VS Code Go extension
	- <v0.41.4>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <{
    "debug.allowBreakpointsEverywhere": true,
    "go.alternateTools": {}
}>
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
3. See error
Steps to Reproduce:
breakpoint main.go line fmt.Println(i), it invalid
func main() {
for i := 0; i < 10; i++ {
fmt.Println(i)
}
}
2.terminal immediate output
### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
@Jerry-yz thanks for reaching out. I cannot reproduce it myself.

Can you capture the log and share it with us? Here is the instruction:
https://github.com/golang/vscode-go/wiki/debugging#collect-logs 

And, please let us know how exactly you launched the debug session - pressing F5? or clicking "Run and Debug" button in the debug view, or having launch.json?

**Comment by Jerry-yz** [comment]
> @Jerry-yz thanks for reaching out. I cannot reproduce it myself.
> 
> Can you capture the log and share it with us? Here is the instruction: https://github.com/golang/vscode-go/wiki/debugging#collect-logs
> 
> And, please let us know how exactly you launched the debug session - pressing F5? or clicking "Run and Debug" button in the debug view, or having launch.json?

this is my launch.json:
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}"
        },

        {
            "name": "Python 调试程序: 当前文件",
            "type": "debugpy",
            "request": "launch",
            "program": "/home/yz/learn/test/mysql/py.py",
            "console": "integratedTerminal"
        }
    ]
}

**Comment by Jerry-yz** [comment]
i edit launch.json:
 {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto", 
            "program": "${fileDirname}",
            "logOutput": "dap",
            "showLog": true,
            "stopOnEntry": true
        }
then, terminal log:
2024-07-11T21:52:55+08:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"initialized"}
2024-07-11T21:52:55+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}
2024-07-11T21:52:56+08:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/home/yz/learn/test/mysql/main.go"},"breakpoints":[{"line":14}],"lines":[14]}}
2024-07-11T21:52:56+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":false,"message":"could not find file /home/yz/learn/test/mysql/main.go"}]}}
2024-07-11T21:52:56+08:00 debug layer=dap [<- from client]{"seq":4,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/home/yz/learn/test/main.go"},"breakpoints":[{"line":25}],"lines":[25]}}
2024-07-11T21:52:56+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":4,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":false,"message":"could not find statement at /home/yz/learn/test/main.go:25, please use a line with a statement"}]}}
2024-07-11T21:52:56+08:00 debug layer=dap [<- from client]{"seq":5,"type":"request","command":"setFunctionBreakpoints","arguments":{"breakpoints":[]}}
2024-07-11T21:52:56+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":5,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]}}
2024-07-11T21:52:56+08:00 debug layer=dap [<- from client]{"seq":6,"type":"request","command":"setInstructionBreakpoints","arguments":{"breakpoints":[]}}
2024-07-11T21:52:56+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":6,"success":true,"command":"setInstructionBreakpoints","body":{"breakpoints":[]}}

**Comment by hyangah** [comment]
Thanks. It's a bit confusing that there are two different breakpoints involving `main.go` and neither worked.

Let's try what path the binary is built with.

1) Since you already have `"stopOnEntry": true`, the debugging should stop at the beginning, right?
2) When the debugging stops, open "DEBUG CONSOLE", enter "dlv sources main.go"
![Screenshot 2024-07-15 at 10 36 05 AM](https://github.com/user-attachments/assets/bbc2ffc1-0672-47ae-b4a7-7a80bd0f03d9)

What source code path does it show?

**Comment by Jerry-yz** [comment]
> Thanks. It's a bit confusing that there are two different breakpoints involving `main.go` and neither worked.
> 
> Let's try what path the binary is built with.
> 
> 1. Since you already have `"stopOnEntry": true`, the debugging should stop at the beginning, right?
> 2. When the debugging stops, open "DEBUG CONSOLE", enter "dlv sources main.go"
>    ![Screenshot 2024-07-15 at 10 36 05 AM](https://private-user-images.githubusercontent.com/4999471/348744685-bbc2ffc1-0672-47ae-b4a7-7a80bd0f03d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTY5MDMsIm5iZiI6MTcyMTA5NjYwMywicGF0aCI6Ii80OTk5NDcxLzM0ODc0NDY4NS1iYmMyZmZjMS0wNjcyLTQ3YWUtYjRhNy03YTgwYmQwZjAzZDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDIyMzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQzMzllNjkyY2ZhNjNlMzMzNmU3NTFlOWY2YTg3OTFmOGZlZjkyMGQwNWZjMTM1ZjlmZGJlY2VhYTYxMTBmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iuyxETXSdTpzuP9rXQBsU93Hs9xL6LXSZb7TV9VI-3I)
> 
> What source code path does it show?

the log output source code path
/home/yz/learn/test/mysql/main.go

**Comment by hyangah** [comment]
That is strange.  Then, if line 14 is indeed `fmt.Println(i)`, that should work. 

```
2024-07-11T21:52:55+08:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"initialized"}
2024-07-11T21:52:55+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}
2024-07-11T21:52:56+08:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/home/yz/learn/test/mysql/main.go"},"breakpoints":[{"line":14}],"lines":[14]}}
2024-07-11T21:52:56+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":false,"message":"could not find file /home/yz/learn/test/mysql/main.go"}]}}
```

The launch request `arguments` and the following build messages were redacted, so I don't know exactly how you built the binary. Do you use any non-default build flags added in the launch arg or environment variables? (`go env`)

I am running out of ideas and cannot reproduce.

Can you try if dlv command line tool works? 

```
$ cd /home/yz/learn/test/mysql
$ dlv debug
Type 'help' for list of commands.
(dlv) b /home/yz/learn/test/mysql/main.go:14
Breakpoint 1 set at 0x10ae6ca for main.main() ./main.go:14
(dlv) c
> [Breakpoint 1] main.main() ./main.go:14 (hits goroutine(1):1 total:1) (PC: 0x10ae6ca)
     9: )
    10:
    11: // main
    12: func main() {
    13:         for i := 0; i < 10; i++ {
=>  14:                 fmt.Println(i)
    15:         }
    16: }
 ```
 
 Does it work for you?

**Comment by Jerry-yz** [comment]
> That is strange. Then, if line 14 is indeed `fmt.Println(i)`, that should work.
> 
> ```
> 2024-07-11T21:52:55+08:00 debug layer=dap [-> to client]{"seq":0,"type":"event","event":"initialized"}
> 2024-07-11T21:52:55+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}
> 2024-07-11T21:52:56+08:00 debug layer=dap [<- from client]{"seq":3,"type":"request","command":"setBreakpoints","arguments":{"source":{"name":"main.go","path":"/home/yz/learn/test/mysql/main.go"},"breakpoints":[{"line":14}],"lines":[14]}}
> 2024-07-11T21:52:56+08:00 debug layer=dap [-> to client]{"seq":0,"type":"response","request_seq":3,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"verified":false,"message":"could not find file /home/yz/learn/test/mysql/main.go"}]}}
> ```
> 
> The launch request `arguments` and the following build messages were redacted, so I don't know exactly how you built the binary. Do you use any non-default build flags added in the launch arg or environment variables? (`go env`)
> 
> I am running out of ideas and cannot reproduce.
> 
> Can you try if dlv command line tool works?
> 
> ```
> $ cd /home/yz/learn/test/mysql
> $ dlv debug
> Type 'help' for list of commands.
> (dlv) b /home/yz/learn/test/mysql/main.go:14
> Breakpoint 1 set at 0x10ae6ca for main.main() ./main.go:14
> (dlv) c
> > [Breakpoint 1] main.main() ./main.go:14 (hits goroutine(1):1 total:1) (PC: 0x10ae6ca)
>      9: )
>     10:
>     11: // main
>     12: func main() {
>     13:         for i := 0; i < 10; i++ {
> =>  14:                 fmt.Println(i)
>     15:         }
>     16: }
> ```
> 
> Does it work for you?

it not workl:
 dlv debug                       
Type 'help' for list of commands.
(dlv) b /home/yz/learn/test/mysql/main.go:14
Command failed: could not find statement at /home/yz/learn/test/mysql/main.go:14, please use a line with a statement
(dlv)
