### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Aamir-Alam01** [golang/vscode-go#3449]
gopls version: v0.16.1/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Fri, 12 Jul 2024 11:34:52 GMT
restart history:
Fri, 12 Jul 2024 09:36:41 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 2627 [running]:
go/types.(*Checker).handleBailout(0x14006d40800, 0x14007021878)
	  check.go:367  0x9c
panic({0x1050c73a0%3F, 0x140055510e0%3F})
	  panic.go:770  0x124
go/types.assert(0x0%3F)
	  errors.go:28  0x60
go/types.(*Checker).rangeStmt(0x14006d40800, 0x3, 0x140050ab440)
	  stmt.go:932  0xb58
go/types.(*Checker).stmt(0x14006d40800, 0x3, {0x105250e80, 0x140050ab440})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x14006d40800, 0x3, {0x14005014fa0%3F, 0x104d48115%3F, 0x5%3F})
	  stmt.go:121  0x88
go/types.(*Checker).stmt(0x14006d40800, 0x3, {0x105250e20, 0x140051332f0})
	  stmt.go:562  0x1974
go/types.(*Checker).rangeStmt(0x14006d40800, 0x3, 0x140050ab4a0)
	  stmt.go:993  0x570
go/types.(*Checker).stmt(0x14006d40800, 0x0, {0x105250e80, 0x140050ab4a0})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x14006d40800, 0x0, {0x14000770b00%3F, 0x104d48115%3F, 0x5%3F})
	  stmt.go:121  0x88
go/types.(*Checker).stmt(0x14006d40800, 0x0, {0x105250e20, 0x14005133320})
	  stmt.go:562  0x1974
go/types.(*Checker).stmt(0x14006d40800, 0x0, {0x105250df0, 0x14005140600})
	  stmt.go:574  0x258c
go/types.(*Checker).stmtList(0x14006d40800, 0x0, {0x14005140640%3F, 0x1058b5ee0%3F, 0x140070216d8%3F})
	  stmt.go:121  0x88
go/types.(*Checker).funcBody(0x14006d40800, 0x10524e588%3F, {0x140050c1a50%3F, 0x1400012e380%3F}, 0x140047d4f80, 0x14005133440, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x21c
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x44
go/types.(*Checker).processDelayed(0x14006d40800, 0x0)
	  check.go:467  0x12c
go/types.(*Checker).checkFiles(0x14006d40800, {0x14006d70be0, 0x4, 0x4})
	  check.go:411  0x188
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0x14006d95bc0, {0x105252168, 0x140046d4420}, 0x14005720120)
	  check.go:1543  0x788
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0x14006d95bc0, {0x105252168, 0x140046d4420}, 0x0, {0x14000794640, 0x10})
	  check.go:568  0x534
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 132
	  errgroup.go:75  0x98
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 622 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report @Aamir-Alam01
Looks similar to the issue golang/go#68334, but the stack trace is slightly different.
(no `types.(*Checker).exprInternal.func1()`, etc). cc @timothy-king @findleyr 
Transferring to the go issue tracker.
