### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by rsrini7** [golang/vscode-go#345]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Installed Gitlens and switched to another branch.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

The language server is not able to serve any features. Initialization failed: Error: unsupported URI scheme:  (gopls only supports file URIs). 

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

Couldn't start client gopls

[Trace - 19:24:05.935 PM] Sending request 'initialize - (0)'.
Params: {"processId":25380,"clientInfo":{"name":"vscode","version":"1.47.0"},"rootPath":null,"rootUri":null,"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"initializationOptions":{},"trace":"off","workspaceFolders":[]}

[Error - Received] 19:24:05.944 PM #0 unsupported URI scheme:  (gopls only supports file URIs)

[Error - 7:24:05 PM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
[Trace - 19:24:05.952 PM] Sending request 'shutdown - (1)'.
Params: 

[Trace - 19:24:05.953 PM] Received response 'shutdown - (1)' in 0ms.
Result: null

[Trace - 19:24:05.953 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/14 19:24:05 server shutdown without initialization\n"}

[Trace - 19:24:05.953 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/07/14 19:24:05 Shutdown session\n\tshutdown_session=1\n"}

[Trace - 19:24:05.954 PM] Sending notification 'exit'.
Params: 

gopls: failed reading header line: EOF

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
When you saw this error, had you opened with VS Code with a single file or a directory?
This error message looks like what currently happens when you open a single file, but this will be fixed in `gopls/v0.4.4`.

**Comment by hyangah** [comment]
@rsrini7 Thanks for the bug report and the trace! 

Did you try to open a single file? 
`gopls` currently only supports opening directories, and v0.4.4 (the next version) will support opening single files. Until then, please open the directory where the file you want to edit exists.

**Comment by rsrini7** [comment]
Opened as workspace folder and not a single file. My workspace have multiple go projects. Thanks for addressing this issue.

**Comment by stamblerre** [comment]
I see, so likely a symptom of the same issue. Until `gopls/v0.4.4` is released, please always open directories rather than individual files.
