### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by hehehahayang** [golang/vscode-go#3455]
gopls version: v0.15.0/go1.21.7
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 17 Jul 2024 02:00:07 GMT
restart history:
Thu, 11 Jul 2024 02:32:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb715da]

goroutine 202 [running]:
golang.org/x/tools/gopls/internal/golang.highlightFuncControlFlow({0xc000877180, 0x7, 0xb%3F}, 0xc0033090b0)
	  highlight.go:241  0x3ba
golang.org/x/tools/gopls/internal/golang.highlightPath({0xc000877180, 0x7, 0x8}, 0xc00067c090%3F, 0xc004dff220)
	  highlight.go:102  0x28e
golang.org/x/tools/gopls/internal/golang.Highlight({0x124b1c8%3F, 0xc000679020%3F}, 0xc003af0180%3F, {0x124c480, 0xc003af0180}, {0x4e6690%3F, 0xc0%3F})
	  highlight.go:53  0x2c7
golang.org/x/tools/gopls/internal/server.(*server).DocumentHighlight(0xc0004e6690%3F, {0x124b200, 0xc000396c30}, 0xc0006787b0)
	  highlight.go:32  0x229
golang.org/x/tools/gopls/internal/protocol.serverDispatch({0x124b200, 0xc000396c30}, {0x125dce0, 0xc0000cc000}, 0xc0006786f0, {0x124b3c0, 0xc000346700})
	  tsserver.go:376  0x6566
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3({0x124b200, 0xc000396c30}, 0xc0006786f0, {0x124b3c0, 0xc000346700})
	  protocol.go:160  0x85
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4({0x124b200, 0xc000396c30}, 0xc0006786f0, {0x124b3c0%3F, 0xc000346700%3F})
	  lsprpc.go:509  0x923
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1({0x124b200, 0xc000396c30}, 0xc0001c3290, {0x124b3c0%3F, 0xc000346700%3F})
	  handler.go:35  0xe5
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2()
	  handler.go:103  0x96
created by golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2 in goroutine 131
	  handler.go:100  0x1ed
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 11678,
    "TestdataFiles": 0,
    "GoFiles": 3406,
    "ModFiles": 1,
    "Dirs": 1044
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.7",
  "GoplsVersion": "v0.15.0",
  "InitialWorkspaceLoadDuration": "2.23927702s",
  "MemStats": {
    "HeapAlloc": 67676744,
    "HeapInUse": 109035520,
    "TotalAlloc": 1015743576
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 3928,
      "Largest": 1654271,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.7",
        "AllPackages": {
          "Packages": 511,
          "LargestPackage": 748,
          "CompiledGoFiles": 3929,
          "Modules": 92
        },
        "WorkspacePackages": {
          "Packages": 43,
          "LargestPackage": 41,
          "CompiledGoFiles": 240,
          "Modules": 1
        },
        "Diagnostics": 2
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, please update gopls to the latest version. This bug has been fixed. Thanks.

```
go install golang.org/x/tools/gopls@latest
```
