### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by MollyWM** [golang/vscode-go#3458]
gopls version: (devel)/go1.22.5
gopls flags: -logfile /path/to/logfile.log -rpc.trace -debug=:0
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Thu, 18 Jul 2024 03:37:09 GMT
restart history:
Thu, 18 Jul 2024 03:20:18 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:20:24 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:20:27 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:20:37 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:20:45 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:31:37 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:31:39 GMT: config change (enabled: true)
Thu, 18 Jul 2024 03:32:00 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:32:10 GMT: config change (enabled: true)
Thu, 18 Jul 2024 03:37:08 GMT: config change (enabled: false)
Thu, 18 Jul 2024 03:37:09 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 70,
    "TestdataFiles": 0,
    "GoFiles": 37,
    "ModFiles": 1,
    "Dirs": 35
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "(devel)",
  "InitialWorkspaceLoadDuration": "3.532776458s",
  "MemStats": {
    "HeapAlloc": 23093072,
    "HeapInUse": 33456128,
    "TotalAlloc": 41927600
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1624,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.5",
        "AllPackages": {
          "Packages": 287,
          "LargestPackage": 155,
          "CompiledGoFiles": 1620,
          "Modules": 25
        },
        "WorkspacePackages": {
          "Packages": 17,
          "LargestPackage": 6,
          "CompiledGoFiles": 37,
          "Modules": 1
        },
        "Diagnostics": 37
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for reporting an issue. Looks like gopls restarted multiple times as the configuration is changed.
Can you tell us what configuration section you were changing?
Do you still experience the issue?
