### ISSUE TITLE
debug not working - can not run under Rosetta

### ISSUE THREAD

**Issue by chandani2411** [golang/vscode-go#3466]
Type: <b>Bug</b>

Failed to launch: could not launch process: can not run under Rosetta, check that the installed build of Go is right for your CPU architecture

Extension version: 0.42.0
VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by hyangah** [comment]
As the error message shows

"can not run under Rosetta, check that the installed build of Go is right for your CPU architecture"

Delve (the Go debugger, and VS Code Go's debug backend) requires the right go that matches your machine's underlying architecture. My guess is that your go is for "darwin/amd64", not for "darwin/arm64". Please download and reinstall the right go (https://go.dev/dl/go1.22.5.darwin-arm64.pkg), and restart VS Code.
