### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by genjudev** [golang/vscode-go#3469]
gopls version: v0.16.1/go1.22.5
gopls flags: -remote=localhost:8091
update flags: local
extension version: 0.42.0
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Fri, 26 Jul 2024 21:24:39 GMT
restart history:
Fri, 26 Jul 2024 21:24:31 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 63,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 49
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "5.167101792s",
  "MemStats": {
    "HeapAlloc": 34070936,
    "HeapInUse": 47505408,
    "TotalAlloc": 239015112
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 922,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.5",
        "AllPackages": {
          "Packages": 141,
          "LargestPackage": 161,
          "CompiledGoFiles": 920,
          "Modules": 3
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
