### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by jwbda** [golang/vscode-go#3470]
gopls version: v0.16.1/go1.21.5
gopls flags: -remote=:37374 -logfile=auto -rpc.trace
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 27 Jul 2024 07:23:30 GMT
restart history:
Fri, 26 Jul 2024 21:10:41 GMT: activation (enabled: true)
Sat, 27 Jul 2024 07:22:57 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 4845,
    "TestdataFiles": 68,
    "GoFiles": 3667,
    "ModFiles": 4,
    "Dirs": 829
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.5",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "38.146739808s",
  "MemStats": {
    "HeapAlloc": 507826424,
    "HeapInUse": 672497664,
    "TotalAlloc": 3721557672
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 9231,
      "Largest": 4950165,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.5",
        "AllPackages": {
          "Packages": 2254,
          "LargestPackage": 147,
          "CompiledGoFiles": 11081,
          "Modules": 261
        },
        "WorkspacePackages": {
          "Packages": 763,
          "LargestPackage": 88,
          "CompiledGoFiles": 3625,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
