### ISSUE TITLE
Whether to consider adding authentication for the socket connection between the debug extension client and the delve debugger？

### ISSUE THREAD

**Issue by yuan92111246** [golang/vscode-go#3481]
**Is your feature request related to a problem? Please describe.**
The socket connection between the debugging extension client and the delve debugger is not authenticated.

**Describe the solution you'd like**
Why are the client and server not authenticating? Are there any security risks?
![go](https://github.com/user-attachments/assets/15df4ad8-5cdd-44bd-b5d9-2843a52fd33e)

**Describe alternatives you've considered**

**Additional context**

**Comment by hyangah** [comment]
@yuan92111246 The referenced source code is a legacy debug adapter which is scheduled to be removed.

Delve does not support authentication yet
https://github.com/go-delve/delve/issues/861
https://github.com/go-delve/delve/issues/2669

If one wants to use authentication with delve remotely running, ssh+port forwarding seems like the only option. https://github.com/go-delve/delve/blob/master/Documentation/faq.md#-how-can-i-use-delve-for-remote-debugging 

Closing. Please open a new issue when delve can utilize it.
