### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zhiwenweb3** [golang/vscode-go#3483]
gopls version: v0.16.1/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 08 Aug 2024 11:06:29 GMT
restart history:
Thu, 08 Aug 2024 11:06:26 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 4771 [running]:
go/types.(*Checker).handleBailout(0x14005bf4200, 0x14004f3f878)
	  check.go:367  0x9c
panic({0x102d0b3a0%3F, 0x14003f8c480%3F})
	  panic.go:770  0x124
go/types.assert(0x0%3F)
	  errors.go:28  0x60
go/types.(*Checker).rangeStmt(0x14005bf4200, 0x3, 0x1400323ad20)
	  stmt.go:932  0xb58
go/types.(*Checker).stmt(0x14005bf4200, 0x3, {0x102e94e80, 0x1400323ad20})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x14005bf4200, 0x3, {0x14002261290%3F, 0x10298c115%3F, 0x5%3F})
	  stmt.go:121  0x88
go/types.(*Checker).stmt(0x14005bf4200, 0x3, {0x102e94e20, 0x140038de9f0})
	  stmt.go:562  0x1974
go/types.(*Checker).rangeStmt(0x14005bf4200, 0x3, 0x1400323ad80)
	  stmt.go:993  0x570
go/types.(*Checker).stmt(0x14005bf4200, 0x0, {0x102e94e80, 0x1400323ad80})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x14005bf4200, 0x0, {0x14000526900%3F, 0x0%3F, 0x140004b8758%3F})
	  stmt.go:121  0x88
go/types.(*Checker).funcBody(0x14005bf4200, 0x102e92588%3F, {0x140004b8930%3F, 0x140000dc380%3F}, 0x14002832d00, 0x140038dea20, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x21c
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x44
go/types.(*Checker).processDelayed(0x14005bf4200, 0x0)
	  check.go:467  0x12c
go/types.(*Checker).checkFiles(0x14005bf4200, {0x14000d85f50, 0x2, 0x2})
	  check.go:411  0x188
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0x14005d403c0, {0x102e96168, 0x1400141e960}, 0x14004a68000)
	  check.go:1543  0x788
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0x14005d403c0, {0x102e96168, 0x1400141e960}, 0x0, {0x140009e4f48, 0x16})
	  check.go:568  0x534
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 81
	  errgroup.go:75  0x98
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 1337 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Dup of https://github.com/golang/go/issues/68334

Looks like the fix will be available in go1.22.6 and go1.23.0.
go1.22.6 was released recently. @zhiwenweb3 can you please update go to go1.22.6 and rebuild gopls?
Thanks!

**Comment by zhiwenweb3** [comment]
> Dup of [golang/go#68334](https://github.com/golang/go/issues/68334)
> 
> Looks like the fix will be available in go1.22.6 and go1.23.0. go1.22.6 was released recently. @zhiwenweb3 can you please update go to go1.22.6 and rebuild gopls? Thanks!

ok i will do it, thanks
