### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by cat3306** [golang/vscode-go#3485]
gopls version: v0.16.1/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Sat, 10 Aug 2024 07:50:10 GMT
restart history:
Sat, 10 Aug 2024 03:11:28 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 5,
    "TestdataFiles": 0,
    "GoFiles": 2,
    "ModFiles": 1,
    "Dirs": 2
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "761.782833ms",
  "MemStats": {
    "HeapAlloc": 34532912,
    "HeapInUse": 51347456,
    "TotalAlloc": 580751128
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2040,
      "Largest": 717922,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.5",
        "AllPackages": {
          "Packages": 376,
          "LargestPackage": 141,
          "CompiledGoFiles": 2036,
          "Modules": 55
        },
        "WorkspacePackages": {
          "Packages": 2,
          "LargestPackage": 1,
          "CompiledGoFiles": 2,
          "Modules": 1
        },
        "Diagnostics": 2
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
A related [bug](https://github.com/golang/go/issues/68334) in go/types was fixed in go1.22.6, so it might be worth upgrading your Go toolchain and reinstalling gopls to see if this fixes the problem.
