### ISSUE TITLE
vscode show staticcheck errors despite staticcheck:false in gopls settings

### ISSUE THREAD

**Issue by pjweinb** [golang/vscode-go#3486]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go version go1.22.2 darwin/arm64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- 
Build info
----------
golang.org/x/tools/gopls v0.16.1
    golang.org/x/tools/gopls@v0.16.1 h1:1hO/dCeUvjEYx3V0rVvCtOkwnpEpqS29paE+Jw4dcAc=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.18.0 h1:5+9lSbEzPSdWkH32vYPBwEpX8KwDbM52Ud9xBUvNlb0=
    golang.org/x/sync@v0.7.0 h1:YsImfSBoP9QPYL0xyKJPq0gcaJdG3rInoqxTWbfQu9M=
    golang.org/x/telemetry@v0.0.0-20240607193123-221703e18637 h1:3Wt8mZlbFwG8llny+t18kh7AXxyWePFycXMuVdHxnyM=
    golang.org/x/text@v0.16.0 h1:a94ExnEXNtEwYLGJSIUxnWoxoRz/ZcCsV63ROupILh4=
    golang.org/x/tools@v0.22.1-0.20240628205440-9c895dd76b34 h1:Kd+Z5Pm6uwYx3T2KEkeHMHUMZxDPb/q6b1m+zEcy62c=
    golang.org/x/vuln@v1.0.4 h1:SP0mPeg2PmGCu03V+61EcQiOjmpri2XijexKdzv8Z1I=
    honnef.co/go/tools@v0.4.7 h1:9MDAWxMoSnB6QoSqiVr7P5mtkT9pOc1kSxchzPCnqJs=
    mvdan.cc/gofumpt@v0.6.0 h1:G3QvahNDmpD+Aek/bNOLrFR2XC6ZAdo62dZu65gmwGo=
    mvdan.cc/xurls/v2@v2.5.0 h1:lyBNOm8Wo71UknhUs4QTFUNNMyxy2JEIaKKo0RWOh+8=
go: go1.22.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- code 1.92.0 (commit b1c0a14de1414fcdaa400695b4db1c0799bc3124) BUT RUNNING code -v produces an error. code --version worked
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.42.0
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- # Tools Configuration

## Environment

GOBIN: undefined
toolsGopath: 
gopath: /Users/pjw/go
GOROOT: /Users/pjw/sdk/go1.22.6
PATH: /Users/pjw/sdk/go1.22.6/bin:/Users/pjw/google-cloud-sdk/bin:/Users/pjw/perl5/bin:/usr/local/git/git-google/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/usr/local/go/bin:/Users/pjw/.cargo/bin:/Users/pjw/go/bin:/Library/PostgreSQL/16/bin:/Library/Developer/CommandLineTools/usr/bin
PATH (vscode launched with): /Users/pjw/google-cloud-sdk/bin:/Users/pjw/perl5/bin:/usr/local/git/git-google/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/Library/TeX/texbin:/usr/local/go/bin:/Users/pjw/.cargo/bin:/Users/pjw/go/bin:/Library/PostgreSQL/16/bin:/Library/Developer/CommandLineTools/usr/bin

## Tools

	go:	/Users/pjw/sdk/go1.22.6/bin/go: go version go1.22.6 darwin/arm64

	gopls:	/Users/pjw/go/bin/gopls	(version: v0.16.1 built with go: go1.22.2)
	gotests:	/Users/pjw/go/bin/gotests	(version: v1.6.0 built with go: go1.22.0)
	gomodifytags:	/Users/pjw/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.22.0)
	impl:	/Users/pjw/go/bin/impl	(version: v1.1.0 built with go: go1.22.0)
	goplay:	/Users/pjw/go/bin/goplay	(version: v1.0.0 built with go: go1.22.0)
	dlv:	/Users/pjw/go/bin/dlv	(version: v1.22.0 built with go: go1.22.0)
	staticcheck:	/Users/pjw/go/bin/staticcheck	(version: v0.4.6 built with go: go1.22.0)

## Go env

Workspace Folder (doit): /Users/pjw/doit

	GO111MODULE=''
	GOARCH='arm64'
	GOBIN=''
	GOCACHE='/Users/pjw/Library/Caches/go-build'
	GOENV='/Users/pjw/Library/Application Support/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='arm64'
	GOHOSTOS='darwin'
	GOINSECURE=''
	GOMODCACHE='/Users/pjw/go/pkg/mod'
	GONOPROXY=''
	GONOSUMDB=''
	GOOS='darwin'
	GOPATH='/Users/pjw/go'
	GOPRIVATE=''
	GOPROXY='https://proxy.golang.org,direct'
	GOROOT='/Users/pjw/sdk/go1.22.6'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/Users/pjw/sdk/go1.22.6/pkg/tool/darwin_arm64'
	GOVCS=''
	GOVERSION='go1.22.6'
	GCCGO='gccgo'
	AR='ar'
	CC='clang'
	CXX='clang++'
	CGO_ENABLED='1'
	GOMOD='/Users/pjw/doit/go.mod'
	GOWORK='/Users/pjw/doit/go.work'
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/xx/sy8s7hy16mnfcj8kyn5hwq5800052r/T/go-build1336814232=/tmp/go-build -gno-record-gcc-switches -fno-common'
	0
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    "gopls": {
      "usePlaceholders": true, // add parameter placeholders when completing a function
      "completionDocumentation": true, // this is the default
      "verboseOutput": false,
      "build.directoryFilters": ["-foof","-internal/lsp/protocol/typescript"],
      "codelenses": {
        "reference": true,
        "gc_details": true,
      },
      "ui.diagnostic.analyses": {
        "deepequalerrors": false, // mod_cache_test.go noise
        "composites": true, // too noisy?
        "fillstruct": true,
        "staticcheck": false, // https://staticcheck.io/docs/checks/
        "unusedparams": false, // not interested in hearing about ctx
      },
      "semanticTokens": true,
      "noSemanticString": true,
      "noSemanticNumber": true,
      "templateExtensions": ["tmpl", "gotmpl"],
      "ui.completion.matcher": "Fuzzy",
    },

### Describe the bug: 
I get the warning message:
"func compose is unused (U1000)go-staticcheck
package testing"

I don't want to hear about unused functions from staticcheck in this project. The gopls documentation says that staticcheck is off by default, and it is explicitly off in my settings.json.

Possibly vscode-go is what is running staticcheck, but how would one know that from looking at the error message?

**Comment by hyangah** [comment]
`go-staticcheck` indicates, this is from the linter. https://github.com/golang/vscode-go/wiki/features#lint-errors

The following setting will disable the linter.

```
"go.lintOnSave": "off"
```

**Comment by pjweinb** [comment]
Thanks.
