### ISSUE TITLE
How to solve gopls version problem？

### ISSUE THREAD

**Issue by DouFuJuShi** [golang/vscode-go#3491]
<img width="516" alt="image" src="https://github.com/user-attachments/assets/65708e59-5971-4561-a576-ff22de0a49c2">.  

vscode Version: 1.92.1 (Universal)

vscode go extension version: v0.42.0

gopls v0.16.1 (built with go version 1.22.6 darwin/amd64)

We use different go versions on different projects？
tks!!!!

**Comment by findleyr** [comment]
Hi, sorry but gopls@v0.16.1 doesn't support integrating with Go 1.17. Can you upgrade your Go to be a more recent, supported version (only the last two versions of Go are supported by the Go team).

The support matrix here has more information:
https://github.com/golang/tools/tree/master/gopls#support-policy

If you absolutely cannot upgrade Go, you can use gopls@v0.11.0

**Comment by findleyr** [comment]
BTW, in general it should be OK to use a more recent Go version for development, even if you are targeting compatibility with an older Go version.

**Comment by DouFuJuShi** [comment]
> Hi, sorry but gopls@v0.16.1 doesn't support integrating with Go 1.17. Can you upgrade your Go to be a more recent, supported version (only the last two versions of Go are supported by the Go team).
> 
> The support matrix here has more information: https://github.com/golang/tools/tree/master/gopls#support-policy
> 
> If you absolutely cannot upgrade Go, you can use gopls@v0.11.0

tks！

**Comment by DouFuJuShi** [comment]
tks
