### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Ashlyn-cm123** [golang/vscode-go#3493]
gopls version: v0.14.2/go1.22.5
gopls flags: -logfile /home/user/gopls.log -rpc.trace
update flags: off
extension version: 0.40.3-upstream-0.1.11-uber
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 16 Aug 2024 19:30:47 GMT
restart history:
Fri, 16 Aug 2024 19:29:35 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: incomplete panic trace.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 861,
    "TestdataFiles": 21,
    "GoFiles": 539,
    "ModFiles": 0,
    "Dirs": 221
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GoVersion": "go1.22.5",
  "GoplsVersion": "v0.14.2",
  "InitialWorkspaceLoadDuration": "789.231183ms",
  "MemStats": {
    "HeapAlloc": 23689456,
    "HeapInUse": 33669120,
    "TotalAlloc": 73526976
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1399,
      "Largest": 1351282,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.5",
        "AllPackages": {
          "Packages": 286,
          "LargestPackage": 161,
          "CompiledGoFiles": 1400,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

Most likely this crash would be fixed by upgrading gopls to the latest version (v0.16.1).
