### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by aydgelee** [golang/vscode-go#3496]
gopls version: v0.6.4/undefined
gopls flags: 
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code win32
initialization error: Error: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
issue timestamp: Mon, 19 Aug 2024 01:27:00 GMT
restart history:
Mon, 19 Aug 2024 01:26:58 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 58 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Gopls is too old. Please update the gopls with the following command and restart the vscode.

`go install golang.org/x/tools/gopls@latest`
