### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by rmuddana** [golang/vscode-go#350]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

[Error - 10:04:21 PM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EO

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

<PASTE STACK TRACE HERE>
No stack trace!

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>
Simple main.go code:
package main

import (
	"fmt"
	"math/rand"
	"time"
)

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")

const passPhraseTimeout = 3

func GeneratePassphrase(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}
	return string(b)
}

func main() {
	passPhraseTimer := time.NewTimer(passPhraseTimeout * time.Second)

	go func() {
		for {
			select {
			case <-passPhraseTimer.C:
				fmt.Println("Passphrase", GeneratePassphrase(10), "expires at", time.Now().Add(passPhraseTimeout*time.Second))
				passPhraseTimer.Reset(passPhraseTimeout * time.Second)
			}
		}
	}()

	time.Sleep(10 * time.Second)
}

**Comment by stamblerre** [comment]
@rmuddana: Did you open VS Code with a directory or with a single file? `gopls` currently only supports opening a directory, but we will support opening files in v0.4.4.

**Comment by rmuddana** [comment]
I have opened the single file and i didnt mean to use the gopls for it. Every time i open the file this error pops up!

**Comment by stamblerre** [comment]
Yep, as I said, `gopls` currently only supports opening a directory, so it should work fine if you open the directory containing the file. Otherwise, you can disable `gopls` by setting `"go.useLanguageServer": false` in your settings.

**Comment by rmuddana** [comment]
Got it. Thank you very much for the quick response. I will close the issue then.
