### ISSUE TITLE
golang code syntax highlight color.

### ISSUE THREAD

**Issue by ripplewang888** [golang/vscode-go#3515]
I have set the color of function parameter to red, but the related variable in this function doen't change to red.
![image](https://github.com/user-attachments/assets/7ee2aea6-5046-41d9-b5ff-c928f7194b5d)

function parameter is set to red, but the variable s of function body doesn't set to red. How resolve this issue?

**Comment by hyangah** [comment]
@ripplewang888 Did you enable the semantic highlightng? 
Please see https://github.com/golang/vscode-go/wiki/faq#syntax-highlighting-doesnt-seem-to-work Syntax highlighting without semantc tokens is not handled by this extension, and is out of scope.

**Comment by zhulingbiezhi** [comment]
**watch detail for [vscode golang highlight](https://www.ququ123.top/2025/03/vscode-cursor-theme-guide/)**

![Image](https://github.com/user-attachments/assets/753d20ed-7824-4b92-8ba6-1adc6b488390)
