### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ShuaiXu32167** [golang/vscode-go#3524]
gopls version: v0.16.1/go1.22.5
gopls flags: 
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 05 Sep 2024 07:58:52 GMT
restart history:
Thu, 05 Sep 2024 07:58:49 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 2297 [running]:
go/types.(*Checker).handleBailout(0x140026ba200, 0x14003f8b878)
	  check.go:367  0x9c
panic({0x1035ab3a0%3F, 0x14002422230%3F})
	  panic.go:770  0x124
go/types.assert(0x0%3F)
	  errors.go:28  0x60
go/types.(*Checker).rangeStmt(0x140026ba200, 0x3, 0x14000610480)
	  stmt.go:932  0xb58
go/types.(*Checker).stmt(0x140026ba200, 0x3, {0x103734e80, 0x14000610480})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x140026ba200, 0x3, {0x140021087d0%3F, 0x10322c115%3F, 0x5%3F})
	  stmt.go:121  0x88
go/types.(*Checker).stmt(0x140026ba200, 0x3, {0x103734e20, 0x1400210da40})
	  stmt.go:562  0x1974
go/types.(*Checker).rangeStmt(0x140026ba200, 0x3, 0x140006104e0)
	  stmt.go:993  0x570
go/types.(*Checker).stmt(0x140026ba200, 0x0, {0x103734e80, 0x140006104e0})
	  stmt.go:827  0x874
go/types.(*Checker).stmtList(0x140026ba200, 0x0, {0x14000190880%3F, 0x0%3F, 0x14003e93c50%3F})
	  stmt.go:121  0x88
go/types.(*Checker).funcBody(0x140026ba200, 0x103732448%3F, {0x140004bc990%3F, 0x14002509b60%3F}, 0x14001e446c0, 0x1400210da70, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x21c
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x44
go/types.(*Checker).processDelayed(0x140026ba200, 0x0)
	  check.go:467  0x12c
go/types.(*Checker).checkFiles(0x140026ba200, {0x14003da8320, 0x4, 0x4})
	  check.go:411  0x188
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0x14003f5dbc0, {0x103736168, 0x140015b45d0}, 0x14001d8f7a0)
	  check.go:1543  0x788
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0x14003f5dbc0, {0x103736168, 0x140015b45d0}, 0x0, {0x14000910080, 0x19})
	  check.go:568  0x534
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1706
	  errgroup.go:75  0x98
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 757 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Please upgrade to Go 1.22.6 or later. This was a bug in go/types that has since been fixed.
