### ISSUE TITLE
`go generate` on save

### ISSUE THREAD

**Issue by myaaaaaaaaa** [golang/vscode-go#3527]
**Is your feature request related to a problem? Please describe.**
`go generate && go test` is a common idiom used when code generators [(such as the well-known `stringer` command)](https://pkg.go.dev/golang.org/x/tools/cmd/stringer) are involved in a project. It elegantly distills almost everything that Go programmers need from the command line, and the ability to run it on save would reduce this need to almost zero.

**Describe the solution you'd like**
An option to run `go generate` on save. It should run before testing (if `go.testOnSave` is enabled), and should probably abort the test step if code generation fails.

**Comment by hyangah** [comment]
Have you considered using tasks.json and other extensions that offer the functionality to run tasks on save instead?

As we are moving much of the test discovery/execution logic to vscode's testing API, I think it will be harder to wire `go generate` that way. If your project heavily depends on `go generate`, I think more natural flow would be

 * you define a task that runs code generate for your project. (this can be done by the other onSave extension)
 * as a post task, trigger running some go tests you like, or, if testOnSave can eventually discover tests that need to rerun upon code generation, it's automatically handled, ... etc (details are still undetermined)

**Comment by myaaaaaaaaa** [comment]
> Have you considered using tasks.json and other extensions that offer the functionality to run tasks on save instead?
> 

My current workaround actually involves a `/usr/local/bin/go` wrapper script, which works by shadowing the `go` program and injecting a call to `go generate`:

```bash
#!/bin/bash -e

if [[ "$VSCODE_PID" && "$1" = "test" ]]; then
	/usr/bin/go generate
fi

exec /usr/bin/go "$@"
```

This works, but it's rather awkward and (more importantly) doesn't benefit the wider Go community.

Since the `go generate` command is already standardized, I think there's an opportunity here to do better than making everyone come up with a custom solution to run the exact same command.

> As we are moving much of the test discovery/execution logic to vscode's testing API, I think it will be harder to wire `go generate` that way.

In that case, how about changing this into a "run `go generate` before running any tests" option? That should be easier to wire in (and is basically what I'm using already).

**Comment by adonovan** [comment]
The go generate command may be standard, but running it on save is not. I think request lives in the domain of personal workflow customizations. Closing, will not fix.

**Comment by myaaaaaaaaa** [comment]
What about a "run `go generate` before running any tests" option, which should be easier to implement?

**Comment by adonovan** [comment]
Same counterargument. This is not a typical way to use `go generate`. Projects that need complex multi-stage builds can evaluate Bazel or other tools.
