### ISSUE TITLE
Code highlighting color error

### ISSUE THREAD

**Issue by miller-star** [golang/vscode-go#3530]
When I enable` "ui.semanticTokens": true`, the syntax highlights are confused
![XiaojunScreenshot2024-09-11 20 03 57](https://github.com/user-attachments/assets/935fd432-d448-4b0f-9303-5c81fbcefbe4)

**Comment by hyangah** [comment]
That color theme doesn't seem to assign a different color for `namespace` tokens. You can verify with different color themes. Or,
you can inspect what semantic tokens are assigned by using "Developer: Inspect Editor Tokens And Scope" command. See the syntax highlighting doc I linked in my previous command.

**Comment by adonovan** [comment]
Closing as not actionable.
