### ISSUE TITLE
Cannot Launch Go App with VScode

### ISSUE THREAD

**Issue by bennettfintron** [golang/vscode-go#3539]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.22.3 darwin/arm64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
	Build info
----------
golang.org/x/tools/gopls v0.16.2
    golang.org/x/tools/gopls@v0.16.2 h1:K1z03MlikHfaMTtG01cUeL5FAOTJnITuNe0TWOcg8tM=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.20.0 h1:utOm6MM3R3dnawAiJgn0y+xvuYRsm1RKM/4giyfDgV0=
    golang.org/x/sync@v0.8.0 h1:3NFvSEYkUoMifnESzZl15y791HH1qU2xm6eCJU5ZPXQ=
    golang.org/x/telemetry@v0.0.0-20240829154258-f29ab539cc98 h1:Wm3cG5X6sZ0RSVRc/H1/sciC4AT6HAKgLCSH2lbpR/c=
    golang.org/x/text@v0.16.0 h1:a94ExnEXNtEwYLGJSIUxnWoxoRz/ZcCsV63ROupILh4=
    golang.org/x/tools@v0.22.1-0.20240829175637-39126e24d653 h1:6bJEg2w2kUHWlfdJaESYsmNfI1LKAZQi6zCa7LUn7eI=
    golang.org/x/vuln@v1.0.4 h1:SP0mPeg2PmGCu03V+61EcQiOjmpri2XijexKdzv8Z1I=
    honnef.co/go/tools@v0.4.7 h1:9MDAWxMoSnB6QoSqiVr7P5mtkT9pOc1kSxchzPCnqJs=
    mvdan.cc/gofumpt@v0.6.0 h1:G3QvahNDmpD+Aek/bNOLrFR2XC6ZAdo62dZu65gmwGo=
    mvdan.cc/xurls/v2@v2.5.0 h1:lyBNOm8Wo71UknhUs4QTFUNNMyxy2JEIaKKo0RWOh+8=
go: go1.22.3
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
1.92.1
eaa41d57266683296de7d118f574d0c2652e1fc4
arm64
```

* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.42.1`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
# Tools Configuration


## Environment

GOBIN: undefined
toolsGopath: 
gopath: /Users/bennettlee/go
GOROOT: /usr/local/go
PATH: /Users/bennettlee/Desktop/Fintron/Code/FTron/tools:/Users/bennettlee/Library/pnpm:/Users/bennettlee/.nvm/versions/node/v20.9.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/usr/local/go/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/bin:/bin:/Users/bennettlee/.local/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/usr/local/mysql/bin/:/Users/bennettlee/.pyenv/shims:/Users/bennettlee/.yarn/bin

## Tools

	go:	/usr/local/go/bin/go: go version go1.22.3 darwin/arm64

	gopls:	/Users/bennettlee/go/bin/gopls	(version: v0.16.2 built with go: go1.22.3)
	gotests:	not installed
	gomodifytags:	/Users/bennettlee/go/bin/gomodifytags	(version: v1.16.0 built with go: go1.22.3)
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/bennettlee/go/bin/dlv	(version: v1.23.0 built with go: go1.22.3)
	staticcheck:	/Users/bennettlee/go/bin/staticcheck	(version: v0.4.7 built with go: go1.22.3)

## Go env

Workspace Folder (FTron): /Users/bennettlee/Desktop/Fintron/Code/FTron

	GO111MODULE='on'
	GOARCH='arm64'
	GOBIN=''
	GOCACHE='/Users/bennettlee/Library/Caches/go-build'
	GOENV='/Users/bennettlee/Library/Application Support/go/env'
	GOEXE=''
	GOEXPERIMENT=''
	GOFLAGS=''
	GOHOSTARCH='arm64'
	GOHOSTOS='darwin'
	GOINSECURE=''
	GOMODCACHE='/Users/bennettlee/go/pkg/mod'
	GONOPROXY=''
	GONOSUMDB=''
	GOOS='darwin'
	GOPATH='/Users/bennettlee/go'
	GOPRIVATE=''
	GOPROXY='https://proxy.golang.org,direct'
	GOROOT='/usr/local/go'
	GOSUMDB='sum.golang.org'
	GOTMPDIR=''
	GOTOOLCHAIN='auto'
	GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
	GOVCS=''
	GOVERSION='go1.22.3'
	GCCGO='gccgo'
	AR='ar'
	CC='clang'
	CXX='clang++'
	CGO_ENABLED='1'
	GOMOD='/Users/bennettlee/Desktop/Fintron/Code/FTron/go.mod'
	GOWORK=''
	CGO_CFLAGS='-O2 -g'
	CGO_CPPFLAGS=''
	CGO_CXXFLAGS='-O2 -g'
	CGO_FFLAGS='-O2 -g'
	CGO_LDFLAGS='-O2 -g'
	PKG_CONFIG='pkg-config'
	GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/zy/fft_9k4x03g90dfjxj59tsx80000gn/T/go-build3495627388=/tmp/go-build -gno-record-gcc-switches -fno-common'
	
```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
{
    "editor.defaultFormatter": "golang.go",
}
```

### Describe the bug
Our program launcher just doesn't work. It stops during the build process, doesn't launch the app, and we are seeing following the error message

```
Failed to launch: could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)
```

And in the console we see 
```
Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.
```

I've tried trying to explicitly set the build flag `-gcflags=all="-N -l"` in the launch configuration and in the go extension settings, but no go

### Steps to reproduce the behavior:
Click on "Run and Debug" and click on one of our existing launch configurations that has worked

```
{
        "name": "Launch Service",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceFolder}/cmd/ftron/main.go",
        "args": ["email-service"],
        "buildFlags": "-tags=UAT",
        "envFile": "${workspaceFolder}/.envrc.local"
      }
```

I also tried going to `main.go` and create a new launch configuration, but same problem.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![Screenshot 2024-09-16 at 9 49 12 AM](https://github.com/user-attachments/assets/f679e534-16cb-43d9-9a3c-0a85d8b3763d)

**Comment by clemcvlcs** [comment]
Upgrade Go to `go1.23.1` fixed the problem for me

**Comment by bennettl** [comment]
Thanks @clemcvlcs !! Yes that solved it! 

Any idea why the dlv debugger wasn't working with the previous go version `1.22.3`?

**Comment by clemcvlcs** [comment]
Actually it was working, but suddenly broke. 

I think that for me, it was right after an xcode update. Not sure if it can be related

**Comment by brucemcclure** [comment]
@clemcvlcs that's exactly what happened to me. 
Did you manage to solve it?

**Comment by JhaDmoore** [comment]
why was this closed?
There is apparently an issue .
<img width="466" alt="image" src="https://github.com/user-attachments/assets/58245627-362a-49a8-bda3-804aec4a250f">

**Comment by mciricean** [comment]
this worked for me https://stackoverflow.com/a/78997746

**Comment by tzookb** [comment]
tried all the above, any other pointers? :|

```
Failed to launch: could not launch process: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member
```

<img width="429" alt="Screenshot 2024-09-24 at 10 09 59" src="https://github.com/user-attachments/assets/7fb62462-3653-4878-96c6-e903da5f358a">

**Comment by Gby56** [comment]
Broke for me too, on `1.22.2 darwin/arm64` and `golang.org/x/tools/gopls v0.16.2`
I did the macOS Sequoia update, but I wouldn't expect that to be the culprit ?

**Comment by austin-millan** [comment]
> I was getting this same issue on a select few golang projects.
> 
> I updated to macOS Sequoia @Gby56, and your comment triggered me to try to reinstall the Xcode command line tools:
> 
> ```
> sudo rm -rf /Library/Developer/CommandLineTools
> xcode-select --install
> ```
> 
> Everything was back to normal after that

This did not resolve the issue for me. However upgrading go via `homebrew`  did work:

```bash
brew install go@1.23
```

**Comment by bishnu-open** [comment]
I was using GO 1.22.4 and got the above issue after upgrading to MacOS Sanoma 14.7.1
After upgrading to GO 1.22.8 it started working

**Comment by LucasBBueno** [comment]
I had the same issue. Solved afeter updated go to 1.23 😃

**Comment by Modestying** [comment]
i resovle this question  by upgrade go to  1.23 .Anyone knows why ?

**Comment by jacksonwuu** [comment]
Try upgrade to go1.23.x and go1.24.x, but not works.
Try reinstall xcode command line tools but now works.
Try upgrade dlv but not works.

But finally upgrade to go1.22.10 works.
