### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by fananchong2016** [golang/vscode-go#3553]
gopls version: v0.16.2/go1.22.5 (Red Hat 1.22.5-1.el9)
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sat, 12 Oct 2024 02:48:37 GMT
restart history:
Sat, 12 Oct 2024 02:48:36 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic:   stmt.go:932: assertion failed

goroutine 2982 [running]:
go/types.(*Checker).handleBailout(0xc00247f600, 0xc003b3f898)
	  check.go:367  0x88
panic({0xecfc00%3F, 0xc0020a3b70%3F})
	  panic.go:770  0x132
go/types.assert(0x78%3F)
	  errors.go:28  0x54
go/types.(*Checker).rangeStmt(0xc00247f600, 0x3, 0xc003cdb800)
	  stmt.go:932  0xe70
go/types.(*Checker).stmt(0xc00247f600, 0x3, {0x135c3e8, 0xc003cdb800})
	  stmt.go:827  0xab9
go/types.(*Checker).stmtList(0xc00247f600, 0x3, {0xc0027af3e0%3F, 0x1056e65%3F, 0x5%3F})
	  stmt.go:121  0x85
go/types.(*Checker).stmt(0xc00247f600, 0x3, {0x135c388, 0xc00274d7a0})
	  stmt.go:562  0x20f2
go/types.(*Checker).stmt(0xc00247f600, 0x0, {0x135c3b8, 0xc001df1bc0})
	  stmt.go:823  0x2946
go/types.(*Checker).stmtList(0xc00247f600, 0x0, {0xc0027b0000%3F, 0x0%3F, 0xc0001bf008%3F})
	  stmt.go:121  0x85
go/types.(*Checker).funcBody(0xc00247f600, 0x13588f8%3F, {0xc003963490%3F, 0xc0020a3420%3F}, 0xc001dfa000, 0xc00274d860, {0x0%3F, 0x0%3F})
	  stmt.go:41  0x331
go/types.(*Checker).funcDecl.func1()
	  decl.go:852  0x3a
go/types.(*Checker).processDelayed(0xc00247f600, 0x0)
	  check.go:467  0x162
go/types.(*Checker).checkFiles(0xc00247f600, {0xc001df7440, 0x6, 0x8})
	  check.go:411  0x1cc
go/types.(*Checker).Files(...)
	  check.go:372
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackage(0xc003d146c0, {0x135d7e8, 0xc002c7e5a0}, 0xc001b8e7e0)
	  check.go:1543  0xa25
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).handleSyntaxPackage(0xc003d146c0, {0x135d7e8, 0xc002c7e5a0}, 0x0, {0xc000622f90, 0x15})
	  check.go:568  0x5e5
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func2()
	  check.go:418  0x2b
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 2310
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 468 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, this was fixed in Go 1.22.6. Please upgrade and reinstall gopls.
