### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by alyanm** [golang/vscode-go#3558]
gopls version: v0.16.2/go1.23.1
gopls flags: -gocodecompletion -diagnostics
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code darwin
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Thu, 03 Oct 2024 16:00:11 GMT
restart history:
Wed, 02 Oct 2024 16:52:08 GMT: activation (enabled: true)
Thu, 03 Oct 2024 15:56:11 GMT: config change (enabled: true)
Thu, 03 Oct 2024 15:56:43 GMT: config change (enabled: true)
Thu, 03 Oct 2024 15:59:29 GMT: config change (enabled: true)
Thu, 03 Oct 2024 15:59:40 GMT: config change (enabled: true)
Thu, 03 Oct 2024 15:59:43 GMT: config change (enabled: true)
Thu, 03 Oct 2024 15:59:57 GMT: config change (enabled: true)
Thu, 03 Oct 2024 16:00:11 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 4,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "amd64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.23.1",
  "GoplsVersion": "v0.16.2",
  "InitialWorkspaceLoadDuration": "371.62034ms",
  "MemStats": {
    "HeapAlloc": 7387336,
    "HeapInUse": 12582912,
    "TotalAlloc": 78099416
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 496,
      "Largest": 213040,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.23.1",
        "AllPackages": {
          "Packages": 57,
          "LargestPackage": 158,
          "CompiledGoFiles": 492,
          "Modules": 2
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report.

If this is still occurring, can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
