### ISSUE TITLE
internal/vscgo: convert pprof to json

### ISSUE THREAD

**Issue by firelizzard18** [golang/vscode-go#3573]
**Is your feature request related to a problem? Please describe.**
I want to create a pprof viewer integrated directly into vscode.

**Describe the solution you'd like**
I want a vscgo command that converts a pprof file into JSON.

**Describe alternatives you've considered**
The only real alternative (to using a tool written in Go) is to do the protobuf decoding directly in JavaScript. However that would add a substantial amount of code (at the very least, protobuf types) and would not be as performant.

**Additional context**
The pprof viewer:
![image(2)](https://github.com/user-attachments/assets/985ae39b-59be-4536-8328-cfef52e5cb61)

**Comment by findleyr** [comment]
Very cool, thanks!
