### ISSUE TITLE
Clean up the extension API

### ISSUE THREAD

**Issue by firelizzard18** [golang/vscode-go#3574]
The exported extension API includes optional fields that are never populated. These should be removed.

https://github.com/golang/vscode-go/blob/884a05caf9c0ce9db8266537c7883753264d2bee/extension/src/export.d.ts#L9-L14

**Comment by findleyr** [comment]
This makes sense, thanks. Did you have a CL for this issue?

**Comment by firelizzard18** [comment]
Yes, evidently I forgot to add the "fixes" note
