### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by amirk85** [golang/vscode-go#3577]
gopls version: v0.16.2/go1.23.2
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Tue, 22 Oct 2024 19:17:58 GMT
restart history:
Tue, 22 Oct 2024 19:17:50 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>golist.go:560: internal error: go list returned non-absolute Package.Dir: \Program Files\Go\src\internal\goarch</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 1375 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
This is a very interesting failure message.

What is the volume name you're working on?

Can you please run the following command from one of your packages?

```
go list -f {{.Dir}} .
```

Thanks.
