### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by arthurnet** [golang/vscode-go#3578]
gopls version: v0.15.2/go1.18.3
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Cursor darwin
initialization error: undefined
issue timestamp: Wed, 23 Oct 2024 19:54:34 GMT
restart history:
Wed, 23 Oct 2024 19:47:16 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.0" (should be something like "go1.12")

goroutine 2020 [running]:
go/types.NewChecker(0x140003cda88%3F, 0x14000906940, 0x1400229e8c0, 0x0%3F)
	  check.go:240  0x204
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x140006429a0, {0x140021400e0, 0x2, 0x2})
	  analysis.go:1028  0x600
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x140006429a0, {0x102d3f398, 0x1400197f5f0})
	  analysis.go:810  0xa4
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x140006429a0, {0x102d3f398%3F, 0x1400197f5f0})
	  analysis.go:672  0x11c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xa8
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa8
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 3,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.3",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "534.493625ms",
  "MemStats": {
    "HeapAlloc": 15360856,
    "HeapInUse": 24346624,
    "TotalAlloc": 202440448
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1000,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.23.2",
        "AllPackages": {
          "Packages": 164,
          "LargestPackage": 159,
          "CompiledGoFiles": 996,
          "Modules": 5
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, you are using an old version of gopls. Please upgrade to the latest version (v0.16.2).

```
go install golang.org/x/tools/gopls@latest
```
