### ISSUE TITLE
Syntax highlight is not working on Visual Studio Code or Cursor

### ISSUE THREAD

**Issue by andergmartins** [golang/vscode-go#3580]
I've installed the official Go plugin, closed and reopened the IDE and it is still not working.

I've tried with the default theme on both VSCode and Cursor. All the other plugins are disabled. 

The editor is recognizing the file as a Go file. I can confirm that in the status bar.

Please, what info do you need to help me to debug this?

## Plugin

v0.42.1

## Cursor
Version: 0.42.3
VSCode Version: 1.93.1
Commit: 949de58bd3d85d530972cac2dffc4feb9eee1e40
Date: 2024-10-16T17:56:07.754Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

## VSCode
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

**Comment by findleyr** [comment]
@andergmartins what is that warning symbol on the 'extensions' icon? Looks related...

**Comment by andergmartins** [comment]
Just upgraded to 1.23.2 and updated all tools. Same result

**Comment by andergmartins** [comment]
Hey guys, please could reopen this issue? I removed that extension which were deprecated, but still have the issue.

**Comment by findleyr** [comment]
@andergmartins we can reopen the issue, but I'm not sure what could cause this behavior or how to help you. This is the only case I've heard of this happening, and it doesn't reproduce with a fresh VS Code install. However, I will continue to ask questions:

- Does this happen for other languages?
- Do other features such as autocomplete work?
- What does `gopls version` say from the integrated terminal?
- What is that notification on your settings gear in the screenshot?

**Comment by andergmartins** [comment]
Thanks, @findleyr, I appreciate it. 

_**1. Does this happen for other languages?**_

No. I've been testing using PHP, Shellscript, Rust, JS, JSX, HTML, Python, and all those work well. I use the IDE daily for PHP, JS, and Shellscript with no issues.

**_2. Do other features such as autocomplete work?_**

Yes, I can see the autocomplete working on `.go` files.

**_3. What does gopls version say from the integrated terminal?_**

```
golang.org/x/tools/gopls v0.16.2
```
**_4. What is that notification on your settings gear in the screenshot?_**

Sorry, I don't see it anymore to double-check. But since I opened this issue, I've disabled all the other extensions, updated all the Go tools, and removed that deprecated extension.

**Comment by andergmartins** [comment]
@findleyr I just tried using Visual Code Studio Insiders with Go for VS Code v0.42.1 and the syntax worked for `.go` files. I will try to reinstall the IDE.

**Comment by hyangah** [comment]
From the screenshot, I see that other extensions are activated even though the original report says you tested with other extensions disabled. First make sure if the syntax highlighting is broken when you disable all extensions, including the Go extension. As stated in this repo's README.md, the default syntax highlighting is offered by the VS Code, not by this extension.

"⚠️ Note: the default syntax highlighting for Go files is provided by a [TextMate rule](https://github.com/worlpaker/go-syntax) embedded in VS Code, not by this extension."

If you don't get syntax highlight when disabled the Go extension, please report the issue to VS Code issue tracker.

If you do get syntax highlighting without the Go extension, but don't with the Go extension (while all other extensions are disabled), try to run "Developer: Inspect Editor Tokens and Scopes" from command palette and hover over the text that you think there should be syntax highlighting. Share the screenshot. (see example)

<img width="782" alt="Screenshot 2024-11-07 at 12 13 16 PM" src="https://github.com/user-attachments/assets/ea57db8d-dbd8-4da3-9667-2f91c3390dfe">

Also, make sure you are using the default color theme during testing, and testing with the default setting (use empty profile or make sure nothing in "Preferences: Open User Settings (JSON)" or .vscode/settings.json.

**Comment by andergmartins** [comment]
Thanks @hyangah for clarifying that. Sorry, I completely missed that note in the README.md file.
I will contact VS Code support. It says to me: `No grammar or semantic tokens available.` 

![image](https://github.com/user-attachments/assets/1bccb2a7-ae81-4ac1-bf05-da66ec31b7bc)

I appreciate your help, guys

**Comment by mansoorkhan96** [comment]
facing this exact same issue

**Comment by viralvaghela** [comment]
same issue

**Comment by abhaybissa31** [comment]
> same issue

I also am facing the same issue, Is there any way you updated vscode or linux if you are working on it?

**Comment by zhulingbiezhi** [comment]
I encountered a similar issue with syntax highlighting for Go in VSCode, but I managed to resolve it. Here are the steps I took, which might be helpful for others facing the same problem: 
 
**watch detail for [vscode golang highlight](https://www.ququ123.top/2025/03/vscode-cursor-theme-guide/)**
 
1. **Ensure the Latest `gopls` is Installed**:
   - Run the following command in your terminal to install the latest version of `gopls`:
     ```bash
     go install golang.org/x/tools/gopls@latest
     ```
   - This ensures that you have the most up-to-date language server, which is crucial for proper syntax highlighting and other language features.

2. **Check and Update Your VSCode Settings**:
   - Open your `settings.json` file in VSCode (you can do this by pressing `Ctrl+Shift+P` and searching for "Open Settings (JSON)").
   - These settings enable the use of the language server and enhance syntax highlighting through semantic tokens.

3. **Customize Syntax Highlighting**:
   - If you want to further customize the syntax highlighting to match a specific theme (like Material Theme), you can add custom color rules to your `settings.json`.
   - This customization helps in making the syntax highlighting more visually appealing and easier to read.

4. **Restart VSCode**:
   - After making these changes, restart VSCode to ensure that all configurations are applied correctly.

5. **Check for Extensions**:
   - Ensure that no other extensions are interfering with the Go extension. Sometimes, disabling unnecessary extensions can resolve unexpected issues.

By following these steps, I was able to get syntax highlighting working properly for Go in VSCode. I hope this helps you as well!

Best regards,
