### ISSUE TITLE
[Refactor] When extracting a function, comments were left out

### ISSUE THREAD

**Issue by vector090** [golang/vscode-go#3583]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- <Paste go version here>
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- <Paste gopls version here>
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- <Paste VS Code version here>
* Check your installed extensions to get the version of the VS Code Go extension
	- <Paste Go extension version here>
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- <Paste the output here>
</details>

go version go1.23.1 windows/amd64

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
When extracting a function, comments were left out, i.e. they didn't go into the new function.

### Steps to reproduce the behavior:
Selected code, 
right click, 
"Refactor", 
"Extract Function", 

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://github.com/user-attachments/assets/b9631934-56cc-4855-a55e-b54970ac4e20)

![image](https://github.com/user-attachments/assets/ce33a08f-9cb1-44fc-9a20-0d0093883b3a)

![image](https://github.com/user-attachments/assets/7d71cbe1-8ba1-46e6-8511-8dba3d7afd92)

issue: the comments were stripped and left there
![image](https://github.com/user-attachments/assets/674f2d6d-3453-40a6-88ca-df7ef6458db6)

the new function missed all the comments
![image](https://github.com/user-attachments/assets/9fe5d9af-e71b-46f2-a18d-b36986f5b628)

**Comment by findleyr** [comment]
This is effectively a consequence of golang/go#20744, which Alan is working on. Closing as a dupe.
