### ISSUE TITLE
 Enhanced Syntax Highlighting for Go Package Names, Constants, and Variables

### ISSUE THREAD

**Issue by RelicOfTesla** [golang/vscode-go#3584]
Description:
﻿
The current Go extension for VS Code lacks specific syntax highlighting for package names, constants, and variables. This makes it difficult to visually differentiate these important elements in Go code.
﻿
Current Limitation:
﻿
Package names, constants, and variables all use the general 'variable.other.go' scope, making them visually indistinguishable from each other.
﻿
Feature Request:
﻿
Implement dedicated scopes for Go package names, constants, and variables (e.g., "entity.name.package.go", "variable.constant.go", "variable.other.go" or similar).
﻿
Benefits:
- Improved code readability
- Better visual distinction between package names, constants, and variables
- Enhanced customization options for users to highlight these elements differently
﻿
Version Information:
VS Code Go Extension: v0.42.1
VS Code: [1.95]
﻿
Thank you for considering this feature request. This enhancement would significantly improve the coding experience for Go developers using VS Code by providing clearer visual distinctions between these key language elements.

**Comment by wtask** [comment]
These settings are already available. At least most of them are.
![image](https://github.com/user-attachments/assets/fe309734-08f3-4f36-8478-a56064778e08)
![image](https://github.com/user-attachments/assets/70aa4dd3-3319-477b-86ee-66eb02b9225a)

**Comment by RelicOfTesla** [comment]
thanks.  Open the ui.semanticTokens option to solve the problem
