### ISSUE TITLE
"Unused something" compile error should not disable renaming other symbols.

### ISSUE THREAD

**Issue by ohir** [golang/vscode-go#3589]
`renaming "byLabel" to "byName" not possible because "acuterm.fairbe.org" has errors`

Stubbing a function often results in a period of tinkering with names.  As of now if you have a bunch of vars declared (eg multiple result parameters from a call) but not all are used yet the F2 rename _does not work_ – because of a compilation error "unused variable".

This is frustrating as some of declared symbols are already used, sometimes in more than one place, but some are not.  Safe changing via F2 can not be done unless one adds `_,_,_=` just to please vscode-go for a second or two.`

The extension should recognize such "coding in progress" state and allow to rename symbols.

**Comment by findleyr** [comment]
Renaming with gopls does work in the presence of many errors. Can you please share your gopls version (`gopls -v version`), as well as a reproducer where you would expect renaming to succeed and it doesn't?
