### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by dgiridharan** [golang/vscode-go#359]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

On starting of VS code, I get an error notifying: Couldn't start client gpls. Please see attached image below.

![image](https://user-images.githubusercontent.com/1533894/87615623-f934cc80-c6c7-11ea-9f02-57c109f9329a.png)

![image](https://user-images.githubusercontent.com/1533894/87615762-4add5700-c6c8-11ea-8842-d055a27212ad.png)

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

[Error - 6:20:02 PM] Starting client failed
  Message: json: cannot unmarshal object into Go struct field .capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
I think you may be using an old version of `gopls`. Can you please update by running the Go: Install/Update Tools command from the Command Palette (Ctrl + Shift + P)?

**Comment by dgiridharan** [comment]
Yep, that was it. Thanks for the super quick reply and apologies for the trouble!
