### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by sauronxg** [golang/vscode-go#3591]
gopls version: v0.14.2/go1.18
gopls flags: -rpc.trace -memprofile=100MB
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code win32
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Tue, 05 Nov 2024 07:37:08 GMT
restart history:
Tue, 05 Nov 2024 07:30:31 GMT: activation (enabled: true)
Tue, 05 Nov 2024 07:34:17 GMT: config change (enabled: true)
Tue, 05 Nov 2024 07:34:47 GMT: config change (enabled: true)
Tue, 05 Nov 2024 07:37:08 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>gopls client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 </pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 5811,
    "TestdataFiles": 0,
    "GoFiles": 334,
    "ModFiles": 1,
    "Dirs": 374
  },
  "GOARCH": "amd64",
  "GOOS": "windows",
  "GoVersion": "go1.18",
  "GoplsVersion": "v0.14.2",
  "InitialWorkspaceLoadDuration": "2.3115383s",
  "MemStats": {
    "HeapAlloc": 75370008,
    "HeapInUse": 108568576,
    "TotalAlloc": 291079984
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 5396,
      "Largest": 1739363,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.18",
        "AllPackages": {
          "Packages": 1089,
          "LargestPackage": 182,
          "CompiledGoFiles": 5401,
          "Modules": 127
        },
        "WorkspacePackages": {
          "Packages": 83,
          "LargestPackage": 25,
          "CompiledGoFiles": 342,
          "Modules": 1
        },
        "Diagnostics": 4
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
`-memprofile=100MB` --> this is not a valid gopld flag. Can you please fix `go.languageServerFlags` setting?
