### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by karvir26** [golang/vscode-go#3596]
gopls version: v0.9.1/go1.23.3
gopls flags: --check-go-version=false
update flags: off
extension version: 0.42.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Mon, 11 Nov 2024 11:53:47 GMT
restart history:
Mon, 11 Nov 2024 11:28:39 GMT: activation (enabled: true)
Mon, 11 Nov 2024 11:30:30 GMT: manual (enabled: true)
Mon, 11 Nov 2024 11:46:51 GMT: installation (enabled: true)
Mon, 11 Nov 2024 11:51:34 GMT: config change (enabled: false)
Mon, 11 Nov 2024 11:52:18 GMT: config change (enabled: true)
Mon, 11 Nov 2024 11:53:47 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 60 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
`--check-go-version=false` is not a valid gopls flag. Can you please check your vscode setting?

And, also it looks like the gopls version is very old. (v0.9.1)
The latest version is v0.16.x currently. Looks like the extension tried to update at some point, but the gopls is still stuck in the old version. Can you share what was printed in the "Go" Output channel?
