### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dortizrv** [golang/vscode-go#3599]
gopls version: v0.16.2/go1.23.1
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Mon, 11 Nov 2024 16:30:45 GMT
restart history:
Mon, 11 Nov 2024 12:38:27 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 68,
    "TestdataFiles": 0,
    "GoFiles": 3,
    "ModFiles": 1,
    "Dirs": 49
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.23.1",
  "GoplsVersion": "v0.16.2",
  "InitialWorkspaceLoadDuration": "674.502277ms",
  "MemStats": {
    "HeapAlloc": 20409816,
    "HeapInUse": 30908416,
    "TotalAlloc": 425255672
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 991,
      "Largest": 925627,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.23.1",
        "AllPackages": {
          "Packages": 166,
          "LargestPackage": 165,
          "CompiledGoFiles": 987,
          "Modules": 9
        },
        "WorkspacePackages": {
          "Packages": 3,
          "LargestPackage": 1,
          "CompiledGoFiles": 3,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)
