### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by tmarwen** [golang/vscode-go#3603]
gopls version: v0.15.2/go1.18.3
gopls flags: 
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Thu, 14 Nov 2024 09:03:30 GMT
restart history:
Thu, 14 Nov 2024 09:02:54 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.0" (should be something like "go1.12")

goroutine 10519 [running]:
go/types.NewChecker(0x14000e1cb60%3F, 0x140066069c0, 0x1400be47450, 0x0%3F)
	  check.go:240  0x204
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x140030ce580, {0x14009879cb0, 0x1, 0x1})
	  analysis.go:1028  0x600
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x140030ce580, {0x101a63398, 0x14009778c90})
	  analysis.go:810  0xa4
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x140030ce580, {0x101a63398%3F, 0x14009778c90})
	  analysis.go:672  0x11c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xa8
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x60
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa8
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 303015,
    "TestdataFiles": 6,
    "GoFiles": 19082,
    "ModFiles": 6,
    "Dirs": 43310
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.18.3",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "128.597958ms",
  "MemStats": {
    "HeapAlloc": 2317376,
    "HeapInUse": 4440064,
    "TotalAlloc": 17422648
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 0,
      "Largest": 0,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.18.3",
        "AllPackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "WorkspacePackages": {
          "Packages": 0,
          "LargestPackage": 0,
          "CompiledGoFiles": 0,
          "Modules": 0
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

**Comment by findleyr** [comment]
Hi, this is a known issue in gopls@v0.15.2. Please update to the latest version of gopls (`go install golang.org/x/tools/gopls@latest`).
