### ISSUE TITLE
Rename receiver on all methods of type with a single operation

### ISSUE THREAD

**Issue by jmalloc** [golang/vscode-go#3615]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I want to rename the receiver of a type and I have to manually visit each method to rename it's "copy" of the receiver name.

**Describe the solution you'd like**

I'd like to be able to use (a variant of) the existing variable rename feature that targets all methods of a type at once.

**Describe alternatives you've considered**

1. At the moment I begin the rename at the top of the file and then "jump to next problem" to find the instances where my linter complains about the use of different receiver names. This works best when all methods of a type are in the same file, but that is not always the case.

2. Search/replace is the obvious tool, and it can work, but with Go's tendency to use short variable names it's easy to get false positives, even when using full-word matches.

3. Once the linter is complaining I can use "Fix using Copilot", but this doesn't seem to support fixing all instances of the problem in one operation either. It's also quite slow.

**Additional context**

I've using the revive linter, which produces the following error message when two receivers for the same type have different names:

> receiver name `x` should be consistent with previous receiver name `y` for `SomeType`

**Comment by adonovan** [comment]
We agree that this would be useful feature. Since we already have an open issue for it (https://github.com/golang/go/issues/41892), I'm going to close this one as a duplicate.
