### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by tsinow** [golang/vscode-go#3623]
gopls version: v0.16.2/go1.23.4
gopls flags: -proxy https://goproxy.cn
update flags: proxy
extension version: 0.42.1
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Sat, 07 Dec 2024 15:20:31 GMT
restart history:
Sat, 07 Dec 2024 15:16:33 GMT: activation (enabled: true)
Sat, 07 Dec 2024 15:20:31 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 3703,
    "TestdataFiles": 0,
    "GoFiles": 3023,
    "ModFiles": 2,
    "Dirs": 783
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.23.4",
  "GoplsVersion": "v0.16.2",
  "InitialWorkspaceLoadDuration": "1.95507426s",
  "MemStats": {
    "HeapAlloc": 147174376,
    "HeapInUse": 201613312,
    "TotalAlloc": 1032282248
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 3724,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.23.4",
        "AllPackages": {
          "Packages": 700,
          "LargestPackage": 165,
          "CompiledGoFiles": 3723,
          "Modules": 123
        },
        "WorkspacePackages": {
          "Packages": 14,
          "LargestPackage": 12,
          "CompiledGoFiles": 77,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Looks like this is an understood initialization problem. Please try removing the unrecognized flag.
