### ISSUE TITLE
Documentation about the debugAdapter configuration of debugger is contradictory

### ISSUE THREAD

**Issue by rostidev** [golang/vscode-go#3629]
From #2205 the default value of the `debugAdapter` configuration is `dlv-dap`. Following documentation still states in some places that the default value is `legacy` and in other places that it's `dlv-dap`

https://github.com/golang/vscode-go/blob/master/docs/debugging.md

For example:

> The [headless dlv server](https://github.com/go-delve/delve/tree/master/Documentation/api) can now be used with both `"debugAdapter": "legacy"` (default value) and `"debugAdapter": "dlv-dap"`

>```
>    "debugAdapter": "dlv-dap", // `legacy` by default
>```

> `debugAdapter`: Controls which debug adapter to use (default: `legacy`).

Please fix this to prevent confusion.

**Comment by hyangah** [comment]
For remote debugging, "legacy" is still the default.

https://github.com/golang/vscode-go/issues/3096
