### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by MrTolqinbek** [golang/vscode-go#3630]
gopls version: v0.17.0/go1.23.3
gopls flags: -tags=dev
update flags: proxy
extension version: 0.45.0
environment: Visual Studio Code linux
initialization error: Error: Pending response rejected since connection got disposed
issue timestamp: Wed, 18 Dec 2024 05:39:26 GMT
restart history:
Wed, 18 Dec 2024 05:39:26 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: no gopls log.

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 202,
    "TestdataFiles": 0,
    "GoFiles": 80,
    "ModFiles": 1,
    "Dirs": 102
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.23.3",
  "GoplsVersion": "v0.17.0",
  "InitialWorkspaceLoadDuration": "577.398998ms",
  "MemStats": {
    "HeapAlloc": 164798544,
    "HeapInUse": 184598528,
    "TotalAlloc": 201498024
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 2969,
      "Largest": 12398145,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.23.3",
        "AllPackages": {
          "Packages": 550,
          "LargestPackage": 165,
          "CompiledGoFiles": 2965,
          "Modules": 65
        },
        "WorkspacePackages": {
          "Packages": 22,
          "LargestPackage": 18,
          "CompiledGoFiles": 78,
          "Modules": 1
        },
        "Diagnostics": 8
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)?
![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

**Comment by MrTolqinbek** [comment]
> Thanks for the report. Can you please share the log you see in the gopls output channel and tell us when you observed this popup (e.g. I was updating `gopls`, I just opened the vscode, I did refactoring, ...)? ![Screen Shot 2021-01-27 at 2 53 49 PM](https://user-images.githubusercontent.com/4999471/106151310-3899a680-614a-11eb-9be7-42f2ae0592c9.png)

hi thanks for attention , i just fixed my vs code settings json file  , after that this error pop-up gone  ,   my added fields : 📄 File: .vscode/settings.json

{
  "go.languageServerFlags": ["-tags=dev"],
  "go.buildTags": "dev"
} , i deleted  this line "go.languageServerFlags": ["-tags=dev"]

**Comment by findleyr** [comment]
Thanks. The `-tags=dev` flag has never worked, but `go.buildTags` should achieve the desired result.

Appreciate the update.
