### ISSUE TITLE
test/gopls: test is flaky

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#37]
e.g. https://github.com/golang/vscode-go/runs/668160281?check_suite_focus=true

This is a synchronization issue - gopls is not up and ready before the hover test starts.

**Comment by stamblerre** [comment]
@hyangah: Is it possible https://go-review.googlesource.com/c/vscode-go/+/234719 fixed this issue?

**Comment by hyangah** [comment]
We are still getting test failures -
```
  1 failing

  1) gopls update tests
       prompt for update:

      AssertionError [ERR_ASSERTION]: outdated, tagged (pre-release): failed
      + expected - actual


  	at /home/runner/work/vscode-go/vscode-go/out/test/gopls/update.test.js:97:20
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/gopls/update.test.js:9:58)
  	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

investigating...

**Comment by stamblerre** [comment]
In case you didn't see my comment on your CL....another day, another couple of hours spent very confused: https://go-review.googlesource.com/c/vscode-go/+/235617.
