### ISSUE TITLE
buildOnSave does not output the built binary in the current directory

### ISSUE THREAD

**Issue by sudheej** [golang/vscode-go#373]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.6 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	1.47.2
17299e413d5590b14ab0340ea477cdd86ff13daf
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.1
- Run `go env` to get the go development environment details
	set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\sudhe\AppData\Local\go-build
set GOENV=C:\Users\sudhe\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\sudhe\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\sudhe\AppData\Local\Temp\go-build029709158=/tmp/go-build -gno-record-gcc-switches
### Share the Go related settings you have added/edited
Default unchanged
### Describe the bug
On save the below operations run but never produce any output, i just added an example of a sample calculator app

![image](https://user-images.githubusercontent.com/11006234/87856075-6aec6080-c8ea-11ea-9c4f-351141632663.png)

### Steps to reproduce the behavior:
1. Write a sample program under the GO workspace
2. Save the program in vscode
3. Output window shows finished execution but nothing happens. 

### Screenshots or recordings

See above in problem

**Comment by hyangah** [comment]
@sudheej Thanks for filing the issue but what do you expect to happen? The last command says 'go build' and output is the file specified with `-o` - I am guessing that's just to check whether the problem compiles (with go.buildOnSave) and the program successfully compiled.

**Comment by sudheej** [comment]
> @sudheej Thanks for filing the issue but what do you expect to happen? The last command says 'go build' and output is the file specified with `-o` - I am guessing that's just to check whether the problem compiles (with go.buildOnSave) and the program successfully compiled.

Thanks for the response, when I manually run the last command a build exe is created in the current folder. I am not sure if I am missing something.

**Comment by hyangah** [comment]
@sudheej Since the command invoked for `buildOnSave` feature uses `-o` flag, the go build command does not produce the output in the current directory. If you want the feature, for now, you can configure `Tasks` for build like https://github.com/golang/vscode-go/blob/master/docs/tasks.md. 

Would be nice if this extension offers default tasks and utilizes them for `buildOnSave` etc (https://github.com/golang/vscode-go/issues/194) but, that support is not implemented yet.

**Comment by sudheej** [comment]
> @sudheej Since the command invoked for `buildOnSave` feature uses `-o` flag, the go build command does not produce the output in the current directory. If you want the feature, for now, you can configure `Tasks` for build like https://github.com/golang/vscode-go/blob/master/docs/tasks.md.
> 
> Would be nice if this extension offers default tasks and utilizes them for `buildOnSave` etc (#194) but, that support is not implemented yet.

Thank you
