### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dminca** [golang/vscode-go#379]
- Issue Type: `Bug`
- Extension Name: `go`
- Extension Version: `0.15.1`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.47.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 10050,
		"activateCallTime": 16,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "golang.go",
				"_lower": "golang.go"
			},
			"activationEvent": "workspaceContains:**/*.go"
		}
	},
	"runtimeErrors": []
}
```

**Comment by stamblerre** [comment]
@dminca: Can you please describe the problem you experienced?

**Comment by dminca** [comment]
Opened VS Code with 2 Go projects and the extension had a burst of 2-3 seconds when loading the Go modules.

The warning from the IDE directed me to open a ticket.

**Comment by hyangah** [comment]
@dminca thanks for the report. We need more info to investigate. 

If it's a CPU issue, we need at least the process status info and cpu profile. Here are instructions to capture useful data.

* https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu
* https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions

If it's a problem of loading Go modules, 
* we need the settings you are using (Command Palette -> Preferences: Open Settings (JSON) -> any fields starting with `"go"` or `"gopls"` or `"[go]"`), 
* directory structure (in particular, where `go.mod` files are located in the project directory, and where is the workspace root)
* if you are using the language server (`"go.useLanguageServer": true`), gopls traces. The instruction to capture traces is 
https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs

Thanks!

**Comment by hyangah** [comment]
Since 0.16.x released a month ago, the extension bundles all modules in one file, which reduced the overhead of loading thousands of files. I hope that helps. 

@dminca Please open a new issue if you continue experiencing this issue. Thanks for the report!
