### ISSUE TITLE
Extension issueI think there is something wrong with this. It takes 226ms to activate and cannot be debugged (timeout after 1000 ms is displayed)

### ISSUE THREAD

**Issue by nothasson** [golang/vscode-go#382]
- Issue Type: `Bug`
- Extension Name: `go-nightly`
- Extension Version: `2020.7.820`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.47.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

I think there is something wrong with this. It takes 226ms to activate and cannot be debugged (timeout after 1000 ms is displayed)

**Comment by nothasson** [comment]
And no debugging information such as variables is displayed

**Comment by nothasson** [comment]
Using wsl2
![微信截图_20200720104147](https://user-images.githubusercontent.com/22558541/87894660-f1817900-ca75-11ea-9b94-c24a2fb46a1f.png)

**Comment by hyangah** [comment]
@nothasson thanks for the report. 

Have you tried uninstall the extension completely (delete `golang.go-nightly-*` from `%USERPROFILE%\.vscode\extensions`) and reinstall it? I saw some cases where installation was corrupted.

Also, do you have the same issue with the stable version of extension (golang.go)?

**Comment by nothasson** [comment]
Yep. I have tried uninstall all extensions and vscode completely,then einstall it .and the same situation happend when using the stable version.

**Comment by hyangah** [comment]
@nothasson Can you share your `launch.json` and if possible a minimal repo? 

And try to enable logging if it reveals more info. 
https://github.com/golang/vscode-go/blob/master/docs/debugging.md#enable-logging
