### ISSUE TITLE
Install dlv fails with strings.Builder undefined

### ISSUE THREAD

**Issue by arctouch-eltonsantana** [golang/vscode-go#385]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.9.2 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.47.1
485c41f9460bdb830c4da12c102daff275415b53
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.15.1
- Run `go env` to get the go development environment details
	- GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/eltonsantana/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/kl/fyd28tfj5hz99mk2d6lc2xbw0000gn/T/go-build414336557=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

### Describe the bug
**When trying to install Dlv either on vscode or on the terminal it will fail with the message:**

Tools environment: GOPATH=/Users/eltonsantana/go
Installing 1 tool at /Users/eltonsantana/go/bin
  dlv

Installing github.com/go-delve/delve/cmd/dlv FAILED

1 tools failed to install.

dlv: failed to install [object Object]: Error: Command failed: /usr/local/bin/go get -v -u github.com/go-delve/delve/cmd/dlv
github.com/go-delve/delve (download)
github.com/go-delve/delve/service/api
github.com/go-delve/delve/vendor/go.starlark.net/syntax
github.com/go-delve/delve/vendor/go.starlark.net/syntax
/Users/eltonsantana/go/src/github.com/go-delve/delve/vendor/go.starlark.net/syntax/quote.go:97:13: undefined: strings.Builder
/Users/eltonsantana/go/src/github.com/go-delve/delve/vendor/go.starlark.net/syntax/quote.go:206:13: undefined: strings.Builder
/Users/eltonsantana/go/src/github.com/go-delve/delve/vendor/go.starlark.net/syntax/scan.go:836:14: undefined: strings.Builder
github.com/go-delve/delve/service/api
/Users/eltonsantana/go/src/github.com/go-delve/delve/service/api/prettyprint.go:401:8: undefined: strings.Builder
 undefined  

### Steps to reproduce the behavior:
1. go get github.com/go-delve/delve/cmd/dlv
2. See error

**Comment by hyangah** [comment]
@arctouch-eltonsantana thanks for the bug report. 

`strings.Builder` is available in go1.10+, and dlv at head wouldn't build with old versions of Go. 
Currently released go version is 1.14, and soon there will be 1.15. Is there a reason that you can't update go?
