### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by sankarp-kavach** [golang/vscode-go#391]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Started VS Code with a Golang project

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

[Error - 4:33:55 pm] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF
[Error - 10:43:09 pm] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@sankarp-kavach: Did you try to open `gopls` with a single file or with a directory? My guess is that you may have tried to open a single file, but gopls currently only supports opening directories. v0.4.4 will support opening single files.
