### ISSUE TITLE
VSCode Go extension incorrectly identifying errors in code

### ISSUE THREAD

**Issue by scottslowe** [golang/vscode-go#397]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?

- Run `go version` to get version of Go
	- `go version go1.14.4 linux/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.47.2`
`17299e413d5590b14ab0340ea477cdd86ff13daf`
`x64`

- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.1
- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/slowe/.cache/go-build"
GOENV="/home/slowe/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/slowe/Code/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build522889516=/tmp/go-build -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your `settings.json` file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

Only `go.useLanguageServer: true`

### Describe the bug

I have a couple `main.go` files that import a number of modules on GitHub. The paths in both file are _exactly_ the same. In one of the `main.go` files, VSCode is reporting "could not import ...", while in the other `main.go` file VSCode doesn't flag any errors. The modules being imported are exactly the same. The code works as expected.

### Steps to reproduce the behavior:

The behavior occurs every time I open the files in this specific directory.

### Screenshots or recordings

If applicable, add screenshots or recordings to help explain your problem.

**Comment by stamblerre** [comment]
Can you please follow the steps in the [`gopls` troubleshooting guide](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#troubleshooting)? Specifically, any logs that you can share would be very helpful. An easy way to collect logs is by running `gopls -rpc.trace -v check path/to/file.go`.

**Comment by scottslowe** [comment]
This is a known issue (see https://github.com/golang/go/issues/32394), sorry.
