### ISSUE TITLE
settings: support predefined variables in go.toolsEnvVars

### ISSUE THREAD

**Issue by edp1096** [golang/vscode-go#413]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.4 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 버전: 1.47.2
커밋: 17299e413d5590b14ab0340ea477cdd86ff13daf
날짜: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
- Check your installed extensions to get the version of the VS Code Go extension 
	- 이름: Go
ID: golang.go
설명: Rich Go language support for Visual Studio Code
버전: 0.15.2
게시자: Go Team at Google
VS Marketplace 링크: https://marketplace.visualstudio.com/items?itemName=golang.Go
- Run `go env` to get the go development environment details
```sh
	- ws$ go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=D:\devs\pcbangstudio\user\gocache
set GOENV=D:\devs\pcbangstudio\user\userprofile\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=D:\devs\pcbangstudio\user\gopath
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\devs\pcbangstudio\tools\langs\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\devs\pcbangstudio\tools\langs\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\devs\pcbangstudio\workspace\chsn-inventory\ws\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=D:\devs\pcbangstudio\user\tmp\go-build876394286=/tmp/go-build -gno-record-gcc-switches
ws$
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```json
    "go.toolsEnvVars": {
        "GOARCH": "amd64",
        "GOOS": "windows",
        "GOBIN": "${workspaceFolder}/bin"
    },
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
            "source.fixAll": true,
        },
        "editor.defaultFormatter": "golang.go"
    },
    "files.eol": "\n",
    "gopls": {
        "usePlaceholders": true // add parameter placeholders when completing a function
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "rename": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "goToImplementation": true,
        "documentSymbols": true, // =outline
        "workspaceSymbols": true,
        "findReferences": true
    },
    "go.languageServerFlags": [],
    "go.docsTool": "gogetdoc",
    "go.formatTool": "goimports",
    "go.gocodeAutoBuild": true,
```

### Describe the bug
A clear and concise description of what the bug.

When use install features with `Predefined variable` of vscode, vscode-go cannot recognize the path value.

* `Go: Install Current Package` - Output message when try to install my source to GOBIN where I specified.
```sh
Installing current package
Installation failed: cannot install, GOBIN must be an absolute path
```

* `Go: Install/Update Tools` - Output message when try to install go tools by vscode-go.
```sh
Tools environment: GOPATH=D:\devs\pcbangstudio\user\gopath, GOBIN=${workspaceFolder}/bin
Installing 1 tool at the configured GOBIN: ${workspaceFolder}/bin in module mode.
  gopls

Installing golang.org/x/tools/gopls FAILED

1 tools failed to install.

gopls: failed to install [object Object]: Error: Command failed: D:\devs\pcbangstudio\tools\langs\go\bin\go.exe get -v golang.org/x/tools/gopls
go: golang.org/x/tools/gopls upgrade => v0.4.3
cannot install, GOBIN must be an absolute path
 undefined  
```

**Comment by stamblerre** [comment]
I'm not sure if specifying `${workspaceFolder}` in your settings will work the same way as in a `launch.json`. Can you remove that setting or use the `go.toolsGopath` setting to specify a location in which to install tools?

**Comment by edp1096** [comment]
Hello Rebecca,
Solved `tools installation` by adding `"go.toolsGopath": "${env:GOPATH}"`, thank you but, `Go: Install Current Package` feature is still showing same message `failed`.
Is there not possible using `go.toolsEnvVars` with `Predefined variables` at settings.json anymore?

**Comment by edp1096** [comment]
> I'm not sure if specifying `${workspaceFolder}` in your settings will work the same way as in a `launch.json`. Can you remove that setting or use the `go.toolsGopath` setting to specify a location in which to install tools?

Hello Rebecca,
Solved `tools installation` by adding `"go.toolsGopath": "${env:GOPATH}"`, thank you but, `Go: Install Current Package` feature is still showing same message `failed`.
Is there not possible using `go.toolsEnvVars` with `Predefined variables` at settings.json anymore?

**Comment by edp1096** [comment]
Hello Rebecca,
Solved tools installation by adding "go.toolsGopath": "${env:GOPATH}", thank you but, Go: Install Current Package feature is still showing same message failed.
Is there not possible using go.toolsEnvVars with Predefined variables at settings.json anymore?

**Comment by stamblerre** [comment]
It's possible that we accidentally made a change that broke this. You're right - this does seem like it should work, and I am able to reproduce the error. Thanks for the report - we'll look into it.
