### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by AmanoKokoro** [golang/vscode-go#415]
gopls server failed to initialize.

[Error - 9:36:28] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF

**Comment by stamblerre** [comment]
@AmanoKokoro: Did you open a single file or a directory in VS Code? My guess is that you may have tried to open a single file, but gopls currently only supports opening directories. v0.4.4 will support opening single files.

**Comment by AmanoKokoro** [comment]
Thank you. I'm going to be late for a comfortable Go life.

**Comment by hyangah** [comment]
0.4.4 has been out for a while. Closing.
