### ISSUE TITLE
test/integration: add thorough tests for the tool installation process

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#42]
The extension manages installing tools for users, but this process is currently not covered by any tests. The biggest danger here is that we don't have an effective way of noticing issues in the tools that the extension depends on.

We need both some form of testing for the installation process that can run in the normal test suite, as well as integration tests that use the network to install tools. These tests should only run in CI (perhaps only before a Nightly release). @hyangah suggested using an environment variable to control this behavior, which sounds reasonable -- unless @ramya-rao-a, is there is a better way that you're aware of?

Also, the tests that check for updates to `gopls` rely on the current versions of `gopls`, so when new versions of `gopls` are published - they break. We need to make these tests more resilient.

**Comment by hyangah** [comment]
So, the nightly release process will exercise the installation path daily. 
Can we declare this is done?

**Comment by stamblerre** [comment]
Yep! Closed.
