### ISSUE TITLE
test: make sure user's configuration or environment does not affect tests

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#43]
Some tests in the extension fail when the user running them has unexpected configurations or when they don't have the correct tools installed. We should make sure all test runs are independent of the user's environment.

https://github.com/microsoft/vscode-go/issues/801 describes a specific fix that should be applied to one of the tests.

**Comment by hyangah** [comment]
That's one of the motivation I had the docker-based setup  [`build/all.bash`](https://github.com/golang/vscode-go/blob/master/build/all.bash#L92). 

Another approach is to utilize `--user-data-dir` e.g., 
https://github.com/golang/vscode-go/blob/master/.vscode/launch.json#L66

(reference: https://vscode-dev-community.slack.com/archives/C74CB59NE/p1585956905048000)

**Comment by hyangah** [comment]
Seems like the `--user-data-dir` trick no longer works. Filed https://github.com/microsoft/vscode/issues/97995

**Comment by hyangah** [comment]
The adjustment made by https://go-review.googlesource.com/c/vscode-go/+/267217 fixed this issue. Thanks @suzmue !
