### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by fedorovaru** [golang/vscode-go#434]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

```
Tools environment: GOPATH=/Users/fedorovaru/go
Installing 1 tool at /Users/fedorovaru/go/bin in module mode.
  gopls@0.4.1

Installing golang.org/x/tools/gopls@v0.4.1 FAILED

1 tools failed to install.

gopls: failed to install [object Object]: Error: Command failed: /Users/fedorovaru/.goenv/versions/1.11.11/bin/go get -v golang.org/x/tools/gopls@v0.4.1
golang.org/x/tools/internal/jsonrpc2
# golang.org/x/tools/internal/jsonrpc2
/Users/fedorovaru/go/pkg/mod/golang.org/x/tools@v0.0.0-20200513154647-78b527d18275/internal/jsonrpc2/messages.go:168:5: undefined: errors.As
 undefined  
```

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@fedorovaru: It looks like you're using Go 1.11. `gopls` only supports Go 1.12 and above. Can you try upgrading your Go version?

**Comment by fedorovaru** [comment]
@stamblerre 
Oh,I didn't know that so I will try it.
Thank you!
