### ISSUE TITLE
go.environment.choose command fails when there is no network

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#438]
How to reproduce
- Disable the network
- Select the Go status bar
- Warning prompt ("getaddrinfo ENOTFOUND golang.org") will popup.

This is because the command tries to retrieve the available Go version list from golang.org/dl but fails.
There is no reason to disable this feature because we don't have the list of available go versions.
In case of network failure, just list locally available Go versions. 

/cc @mcjcloud

**Comment by mcjcloud** [comment]
Good point. If the network call fails, it should probably just show the installed versions. Do you think the user should be notified of the network failure? @hyangah

**Comment by hyangah** [comment]
Probably, they don't need to be notified.
