### ISSUE TITLE
Add "Refactoring commands" to "Quick Fix" menu

### ISSUE THREAD

**Issue by doggy8088** [golang/vscode-go#440]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

There are few refactoring commands in Go extension such as `Go: Extract to function` and `Go: Extract to variable`. I have to make selection then press `F1`, then choose the command to run.

**Describe alternatives you've considered**

In VSCode, there is a very common command called `Quick Fix` ( `Ctrl+.` ). This command also called `Code Action`. I'd like to suggest Go extension can put some of the reactoring commands into `Quick Fix` menu. That will be very very useful.

**Additional context**

In Typescript, you select a piece of code, then hit `Ctrl+.` can trigger code action:

![image](https://user-images.githubusercontent.com/88981/88872022-e388e080-d24b-11ea-84db-d816e426a89e.png)

In Go, nothing happening.

![image](https://user-images.githubusercontent.com/88981/88871955-b89e8c80-d24b-11ea-8e0e-0bc2aeeb542a.png)

**Comment by stamblerre** [comment]
`gopls` supports code actions and will be adding support for the extract feature in the next release. I think that all code actions in this extension will be powered by `gopls` in the future. More details on how to enable `gopls` here: https://github.com/golang/vscode-go/blob/master/docs/gopls.md.

**Comment by doggy8088** [comment]
After installed `gopls@v0.4.4-pre3`, this works! 

```sh
GO111MODULE=on go get golang.org/x/tools/gopls@v0.4.4-pre3
```

As @joshbaum said in Gophers slack #vscode channel, the tool is still in progress and will be expanded in 0.4.5.
