### ISSUE TITLE
gopls: append completions not being shown

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#441]
See the discussion on https://github.com/golang/go/issues/39507, specifically https://github.com/golang/go/issues/39507#issuecomment-666084463.

**Comment by hyangah** [comment]
It seems to work for me with the latest, not released gopls, and the basic vscode setup (code 1.47.3, `"go.useLanguageServer": true`). Am I missing something?

![image](https://user-images.githubusercontent.com/4999471/89052930-6da47800-d324-11ea-941d-f637b4480763.png)

**Comment by muirdm** [comment]
```
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

Go extension seems to be v0.15.2

```
{
    "window.zoomLevel": 0,
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
         "source.organizeImports": true,
        }
    },
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function

        // Experimental settings
        "completeUnimported": true, // autocomplete unimported packages
    },

    "go.languageServerFlags": [
        "-rpc.trace", // for more detailed debug logging

        "-logfile", "/tmp/vscode.log",
    ],
}
```

![vscode](https://user-images.githubusercontent.com/11356572/89055789-e0efbf00-d30f-11ea-8e03-e769799fabb8.gif)

```
[Trace - 09:22:47.424 AM] Sending request 'textDocument/completion - (245)'.
Params: {"textDocument":{"uri":"file:///Users/muir/scratch/foo/foo.go"},"position":{"line":4,"character":10},"context":{"triggerKind":1}}


[Trace - 09:22:47.434 AM] Received response 'textDocument/completion - (245)' in 10ms.
Result: {"isIncomplete":true,"items":[{"label":"append(foo, )","kind":3,"preselect":true,"sortText":"00000","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"append(foo, ${1:})"}},{"label":"append","kind":3,"detail":"func(slice []Type, elems ...Type) []Type","sortText":"00001","filterText":"append","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"append(${1:slice []Type}, ${2:elems ...Type})"}},{"label":"appmesh","kind":9,"detail":"\"github.com/aws/aws-sdk-go/service/appmesh\"","sortText":"00002","filterText":"appmesh","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"appmesh"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"github.com/aws/aws-sdk-go/service/appmesh\"\n"}]},{"label":"appmesh","kind":9,"detail":"\"github.com/aws/aws-sdk-go-v2/service/appmesh\"","sortText":"00003","filterText":"appmesh","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"appmesh"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"github.com/aws/aws-sdk-go-v2/service/appmesh\"\n"}]},{"label":"appmeshiface","kind":9,"detail":"\"github.com/aws/aws-sdk-go/service/appmesh/appmeshiface\"","sortText":"00004","filterText":"appmeshiface","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"appmeshiface"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"github.com/aws/aws-sdk-go/service/appmesh/appmeshiface\"\n"}]},{"label":"appsync","kind":9,"detail":"\"github.com/aws/aws-sdk-go/service/appsync\"","sortText":"00005","filterText":"appsync","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"appsync"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"github.com/aws/aws-sdk-go/service/appsync\"\n"}]},{"label":"appengine","kind":9,"detail":"\"google.golang.org/api/appengine/v1\"","sortText":"00006","filterText":"appengine","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"appengine"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"google.golang.org/api/appengine/v1\"\n"}]}]}
```

**Comment by hyangah** [comment]
@muirdm Thanks for the info. Yes, suddenly, my editor started to stop suggesting and I could repro. (Not sure how I got the suggestion and took the screenshot before :-P) 

Looking at the trace, I think the culprit is the missing `filterText` entry in the first element. 

```
Result: {"isIncomplete":true,"items":[{"label":"append(foo, )","kind":3,"preselect":true,"sortText":"00000","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"append(foo, ${1:})"}},{"label":"append","kind":3,"detail":"func(slice []Type, elems ...Type) []Type","sortText":"00001","filterText":"append","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":7},"end":{"line":4,"character":10}},"newText":"append(${1:slice []Type}, ${2:elems ...Type})"}}, ...
```

Not sure what VS Code is doing but it's dropping the entry with empty `filterText` field. What's worse is that we have some hack to prevent vscode from messing up with the completion ranking/matching. The hack replaces `filterText` of all other elements with the `filterText` entry from the very first element. As a result, vs code drops all the entries from the suggestion. 

Is there a reason `gopls` doesn't set the `filterText` field of the `append(foo,)` entry?

**Comment by muirdm** [comment]
Ah, missing filterText - didn't notice that.

> we have some hack to prevent vscode from messing up with the completion ranking/matching. The hack replaces filterText of all other elements with the filterText entry from the very first element. 

I think that hack was removed from gopls. Was it moved into the VSCode extension?

> Is there a reason gopls doesn't set the filterText field of the append(foo,) entry?

Not really - certainly not intentional. gopls normally uses InsertText as the filterText but these candidates have no InsertText (because they only have snippets with no fallback non-snippet text). If we sent the snippet contents as the filterText would that work? I seem to remember VSCode not liking funny characters in the filterText, so I'm a bit worried the snippets might mess something different up.

**Comment by hyangah** [comment]
> > we have some hack to prevent vscode from messing up with the completion ranking/matching. The hack replaces filterText of all other elements with the filterText entry from the very first element.
> 
> I think that hack was removed from gopls. Was it moved into the VSCode extension?

@stamblerre is the one who added [the hack](https://github.com/golang/vscode-go/blob/c22bbe54ba13c1498f77a66f251bf868f7d1eacf/src/goLanguageServer.ts#L344-L350), so I guess she knows the history :-) 

> > Is there a reason gopls doesn't set the filterText field of the append(foo,) entry?
> 
> Not really - certainly not intentional. gopls normally uses InsertText as the filterText but these candidates have no InsertText (because they only have snippets with no fallback non-snippet text). If we sent the snippet contents as the filterText would that work? I seem to remember VSCode not liking funny characters in the filterText, so I'm a bit worried the snippets might mess something different up.

It seems like at list for this entry, the text in the `label` field (i.e. `append(foo,)`) seems to work. 
But if the character restriction as mentioned [here completion.go](https://github.com/golang/tools/blob/b2d8b03366329f6cb0ff15138a7732def14679a7/internal/lsp/completion.go#L101-L103) is true, yes, that's not good. 

Looking at LSP spec, I still think this is a vscode bug. It's undefined, so falsy. Thus, the `label` should be used, right? 

```
	/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used.
	 */
	filterText?: string;
```

I will try to add a hack to vscode-go side. :-(

**Comment by hyangah** [comment]
With https://go-review.googlesource.com/c/vscode-go/+/246297, now vscode handles the completion as we hoped.
 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4999471/89077462-38ae1a80-d350-11ea-84a3-8b063d08fc7d.gif)
