### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by manoj-guglani-sp** [golang/vscode-go#444]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Following errors were observed: 

"Couldn't start client gopls"

"The language server is not able to serve any features. Initialization failed: Error: unsupported URI scheme: (gopls only supports file URIs)."

[Error - 9:50:08 AM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF

Please attach the stack trace from the crash.
no stack trace available

Go version - 1.14.2

vs-code details:

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by hyangah** [comment]
@manoj-guglani-sp Thanks for the report. Did you observe this crash while trying to open a single file? The current version of gopls doesn't support it. For now, try to open the directory where the file exists if that's the case. 

The next version of gopls will support a single file edit mode.

**Comment by manoj-guglani-sp** [comment]
yes it was a single file. I had a session open with a .proto file open and was adding corresponding interface in a .go file that's when I saw the issue. After that I did "Add folder to workspace" at the directory level and things worked fine. I recall someone had mentioned that in one of the threads that for making gopls work with vscode and go 1.14 I need to do "Add folder to workspace".

**Comment by stamblerre** [comment]
Glad to hear you were able to resolve it. Closing this issue.
