### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by AlekSi** [golang/vscode-go#453]
https://direnv.net is a popular tool for setting per-directory or per-project environment variables. Currently, the Go plugin is not compatible with it. More specifically, there is no way to use `.envrc`-exported environment variables in Go tests:
* the is no way to run go test helper in the full shell environment;
* Test Env File setting expects `key=value` format, while `.envrc` requires one to use `export key=value`.

**Comment by hyangah** [comment]
@AlekSi I think this is beyond the scope of this extension's function. This extension inherits all the environment variables from the vscode. So, make sure the vscode understands the `direnv` per-project environment settings - i.e. launch vscode from the terminal that recognizes and processes direnv settings. If vscode fails to handle that as you hoped, please file an issue in `github.com/microsoft/vscode`.

**Comment by AlekSi** [comment]
> I think this is beyond the scope of this extension's function.

I wonder why those settings are in scope then:

![image](https://user-images.githubusercontent.com/11512/89189833-401c3080-d5a9-11ea-9e7c-51ffc68500da.png)

> So, make sure the vscode understands the direnv per-project environment settings - i.e. launch vscode from the terminal that recognizes and processes direnv settings.

I always do that, but I also never saw VSCode inherit environment variables from the shell. And to be honest, I would consider that behavior to be a bug.

What can solve this ticket relatively easier is an ability to start `go test` in a shell environment.

**Comment by hyangah** [comment]
@AlekSi The `Test Env File` assumes .env file format (`KEY=VALUE`). My understanding is that `.envrc` is more flexible than `.env` and may contain not only `export` but unsetting, etc. Please see https://github.com/direnv/direnv/issues/284

If VS Code fails to inherit environment variables from the shell, that's a bug of VS Code.
