### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by zsy619** [golang/vscode-go#454]
[Error - 9:49:21 PM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
gopls: failed reading header line: EOF

**Comment by hyangah** [comment]
@zsy619 thanks for the report. Do you still see the issue when you are using the latest `gopls` (v0.4.4)? 

To install the latest version, `Go: Update/Install Tools` -> choose `gopls`. 
Or, from the integrated terminal, run 
```
cd $HOME
GO111MODULE=on go get golang.org/x/tools/gopls
```

**Comment by bgentry** [comment]
@hyangah I had this same issue. I received the same error / crash when attempting to update the Go tools (as soon as the menu to select which tools appears, it crashes with the error logged above).

However, your suggestion to update this tool from the integrated VSCode terminal appears to have resolved the issue for me.

**Comment by hyangah** [comment]
@zsy619 did the new gopls address your problem?
@bgentry thanks for the update.

**Comment by hyangah** [comment]
0.4.4 has been out for a while. Closing.
