### ISSUE TITLE
activation: command 'go.locate.tools' not found

### ISSUE THREAD

**Issue by decitrig** [golang/vscode-go#457]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.6 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.47.3
          91899dcef7b8110878ea59626991a18c8a6a1b3e
          x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.2
- Run `go env` to get the go development environment details

GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rwsims/.cache/go-build"
GOENV="/home/rwsims/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rwsims/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build559895274=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

None

### Describe the bug
When I run 'Go: Locate Configured Go Tools' I get an error that `command 'go.locate.tools' not found`

### Steps to reproduce the behavior:
1. Ctrl+Shift+P
2. Select `Go: Locate Configured Go Tools`

**Comment by hyangah** [comment]
@decitrig Thanks for the report. I guess the extension fails to activate successfully. 

Have you seen any popup or error messages when you opened the file and activated the extension? 
Do you see any error or crash message in the extension logs output channel: `View: Toggle Output` > see `Log (Extension Host)` and `Go` output channels from the dropdown menu.

**Comment by aranw** [comment]
I've just experienced this issue after VSCode updated my go extension has stopped working. I've checked my `go env` and everything seems to be working fine but for some reason now my extension fails 

When I look in the log I see the following
```
[2020-09-15 13:00:34.159] [exthost] [error] Activating extension golang.go failed due to an error:
[2020-09-15 13:00:34.167] [exthost] [error] TypeError: Cannot read property 'then' of undefined
	at activate (/Users/aran/.vscode/extensions/golang.go-0.16.2/dist/goMain.js:13951:46)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:917:841)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:917:492)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:915:724
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
```

**Comment by aranw** [comment]
Okay so I downgraded back to v0.16.1 and it all seems to be working again for me

**Comment by hyangah** [comment]
That's strange - I am guessing when running with 0.16.2, the extension failed to find the go binary for some reason. 
0.16.2 has only minor fixes around `go test` run [compared to 0.16.1](https://github.com/golang/vscode-go/compare/v0.16.2..v0.16.1), otherwise they are identical.

**Comment by aranw** [comment]
@hyangah I'll try an upgrade again and see whether I get the same issue

**Comment by aranw** [comment]
@hyangah so I managed to upgrade the extension and it worked for a bit but after a restart I've ended up with the following error again

```
[2020-09-18 15:50:29.097] [exthost] [error] Activating extension golang.go failed due to an error:
[2020-09-18 15:50:29.103] [exthost] [error] TypeError: Cannot read property 'then' of undefined
	at activate (/Users/aran/.vscode/extensions/golang.go-0.16.2/dist/goMain.js:13951:46)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:917:841)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:917:492)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:915:724
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
```

**Comment by hyangah** [comment]
@aranw Thanks for the report. I am guessing the PATH is not initialized when the vscode did the clean relaunch after restart.
Can you 

1) close the vscode app (make sure to remove from the dock since mac app launcher is sticky) 
2) open a terminal app outside vscode, 
3) verify `go` is accessible, and 
4) then relaunch the vscode from the terminal and check if it works without your settings.json change for `"go.alternateTool"`?

I also filed #660 to avoid this hard crash.

**Comment by aranw** [comment]
Okay something strange I just found. One of my open project windows had a new `.vscode` folder with `settings.json` file inside of it that had the `"go.inferGopath": false` inside of it. Removing this has completely fixed my setup?

**Comment by aranw** [comment]
In fact, it seems to keep adding this file back each time with the `inferGopath` set to `false`? 

Why is vscode/go extension keep creating these files in my repo?

**Comment by hyangah** [comment]
@aranw The extension doesn't create the file. `"go.inferGopath": false` is the default so the setting doesn't do anything effectively. If you have other extensions installed, try to disable all and test only with the go extension.
