### ISSUE TITLE
WSL2 all intellisense features extremely slow

### ISSUE THREAD

**Issue by H-Richard** [golang/vscode-go#458]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.13.8 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.47.3
91899dcef7b8110878ea59626991a18c8a6a1b3e
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.15.2
- Run `go env` to get the go development environment details

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/{name}/.cache/go-build"
GOENV="/home/{name}/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/mnt/c/Users/{name}/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/mnt/c/Users/{name}/go/src/github.com/H-Richard/temp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build437456268=/tmp/go-build -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited

```
    "go.formatTool": "goformat",
    "go.gopath": "/mnt/c/Users/{Name}/go",
    "go.goroot": "/usr/lib/go",
    "go.autocompleteUnimportedPackages": true,
```

### Describe the bug
All go intellisense features hangs on loading, hover, signature and autocomplete all for a good 20s.

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/44233784/89128058-d45e9880-d4c0-11ea-9ffe-daedfa2f5fa9.png)
![image](https://user-images.githubusercontent.com/44233784/89128076-ff48ec80-d4c0-11ea-8f76-790a4cf6bbc8.png)
Installed Tools: 
```
   gocode: /mnt/c/Users/{name}/go/bin/gocode installed
   gopkgs: /mnt/c/Users/{name}/go/bin/gopkgs installed
   go-outline: /mnt/c/Users/{name}/go/bin/go-outline installed
   go-symbols: /mnt/c/Users/{name}/go/bin/go-symbols installed
   guru: /mnt/c/Users/{name}/go/bin/guru installed
   gorename: /mnt/c/Users/{name}/go/bin/gorename installed
   gotests: /mnt/c/Users/{name}/go/bin/gotests installed
   gomodifytags: /mnt/c/Users/{name}/go/bin/gomodifytags installed
   impl: /mnt/c/Users/{name}/go/bin/impl installed
   fillstruct: /mnt/c/Users/{name}/go/bin/fillstruct installed
   goplay: /mnt/c/Users/{name}/go/bin/goplay installed
   godoctor: /mnt/c/Users/{name}/go/bin/godoctor installed
   dlv: /mnt/c/Users/{name}/go/bin/dlv installed
   gocode-gomod: /mnt/c/Users/{name}/go/bin/gocode-gomod installed
   godef: /mnt/c/Users/{name}/go/bin/godef installed
   goformat: /mnt/c/Users/{name}/go/bin/goformat installed
   golint: /mnt/c/Users/{name}/go/bin/golint installed
```

**Comment by hyangah** [comment]
@H-Richard Thanks for the report. It looks like you are using the modules mode, but not using the language server. As explained in https://github.com/golang/vscode-go/blob/master/docs/modules.md, many traditional tools this extension depended on to offer intenllisense don't support modules mode. So, we recommend the language server (`gopls`) when you work with modules. 

Please see https://github.com/golang/tools/blob/master/gopls/doc/vscode.md for the instruction to switch.
