### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by acnologia000** [golang/vscode-go#459]
go pls failed to start

<My Vscode output window says>

[Error - 11:34:53 PM] Starting client failed
Message: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
Code: -32700

**Comment by hyangah** [comment]
@acnologia000 thanks for the report. Can you share the versions of the followings?

1) vscode (from About Visual Studio menu)
2) go extension (from the extension view), and 
3) gopls (`gopls -v verison`)

Some of them seem outdated.

**Comment by joe-getcouragenow** [comment]
I just got the same as soon as updated to this: https://www.reddit.com/r/golang/comments/i2yez9/gopls_v044/

I am using standard VSCODE, golang, etc via brew.

**Comment by stamblerre** [comment]
@joe-getcouragenow - can you please provide the versions of the tools you are using, as @hyangah requested above?

**Comment by joe-getcouragenow** [comment]
@stamblerre Happy to.

In the bottom right of the screenshot  i get this error even after restarting VSCODE. It comes up every time now.
How can i see the log or other of where the error message is coming from.  Clicking on the dialog does nothing.
Want to be able to dig deeper as i get hit with this quite a bit.


<img width="1920" alt="Screenshot 2020-08-03 at 18 02 58" src="https://user-images.githubusercontent.com/59567750/89202737-aefe8700-d5b3-11ea-9fb1-cae8939ac50a.png">


---

### Environment

````
go version
go version go1.14.6 darwin/amd64


go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/apple/workspace/go/bin"
GOCACHE="/Users/apple/Library/Caches/go-build"
GOENV="/Users/apple/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/apple/workspace/go/src/github.com/ctessum/cityaq/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build163211138=/tmp/go-build -gno-record-gcc-switches -fno-common"



code --list-extensions --show-versions
Arjun.swagger-viewer@3.0.1
ban.spellright@3.0.50
bpruitt-goddard.mermaid-markdown-syntax-highlighting@1.0.3
bungcip.better-toml@0.3.2
Dart-Code.dart-code@3.13.1
Dart-Code.flutter@3.13.1
DavidAnson.vscode-markdownlint@0.36.2
dtsvet.vscode-wasm@1.3.1
golang.go@0.16.0
googlecloudtools.cloudcode@1.4.1
ms-azuretools.vscode-docker@1.4.1
ms-kubernetes-tools.vscode-kubernetes-tools@1.2.1
mtxr.sqltools@0.22.11
octref.vetur@0.25.0
redhat.vscode-yaml@0.9.1
rust-lang.rust@0.7.8
vstirbu.vscode-mermaid-preview@1.5.2
wholroyd.HCL@0.0.5


code -v
1.47.3
91899dcef7b8110878ea59626991a18c8a6a1b3e
x64






````



VSCODE Setting

``` 

 //-------- Golang configuration --------
    // From: https://github.com/golang/tools/blob/master/gopls/doc/vscode.md
    "go.useLanguageServer": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        // Optional: Disable snippets, as they conflict with completion ranking.
        "editor.snippetSuggestions": "none",
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "gopls": {
        // Add parameter placeholders when completing a function.
        "usePlaceholders": true,

        // If true, enable additional analyses with staticcheck.
        // Warning: This will significantly increase memory usage.
        "staticcheck": false,
    },


```

**Comment by stamblerre** [comment]
@joe-getcouragenow: This actually does seem like a different error from the original report. Do you mind opening a separate issue? Thanks!

**Comment by hyangah** [comment]
@joe-getcouragenow thanks for the bug report - let's follow up this specific issue in #463.

**Comment by acnologia000** [comment]
The error hot fixed after deleting vscode data/cache , deleting the extension and letting it reinstall needed items on opening go file

**Comment by hyangah** [comment]
Thanks for sharing how you fixed the issue @acnologia000 

I am curious how the vscode extension data got into the bad state, but I am afraid it's hard to inspect further without knowing how to reproduce the issue. Closing this issue.
