### ISSUE TITLE
It showing error when you use same named funtion in two different files

### ISSUE THREAD

**Issue by tutoraddicts** [golang/vscode-go#461]
I created two files one is **hello.go** and another one is **Variable.go** 
I write same code in both files
**CODE**
`package main

import "fmt"

func print() {
	fmt.Println("We Done Printing!")
}

func main() {

	var integer int
	var floating float32
	var hello string

	integer = 23
	floating = 25.6
	hello = "Hello, World!"
	fmt.Println(hello)
	fmt.Println(integer)
	fmt.Println(floating)
}
`

The issue is it shows me an error that the functions already declared in Hello.go I can understand why it is showing me this but It is really irritating.

**Comment by hyangah** [comment]
@tutoraddicts Are both files (hello.go and variable.go) in the same package? If so, this is an intended behavior and the error is coming from the go compiler and the error indicates this package doesn't build. Please place each file in a separate directory.

**Comment by tutoraddicts** [comment]
I can build them separately and run them without any problem.
