### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by rafa-acioly** [golang/vscode-go#462]
After opening a project this errors shows up

> Couldn't start client gopls

> The language server is not able to serve any features. Initialization failed: Error: json: cannot unmarshal object into Go struct field .tagSupport of type bool.

> [Error - 1:18:31 PM] Starting client failed
>  Message: json: cannot unmarshal object into Go struct field .tagSupport of type bool
>  Code: -32700 

Go version: go1.12.5 linux/amd64
SO: Ubuntu 18.04.4 LTS
Vscode version: 1.47.3

**Comment by stamblerre** [comment]
@rafa-acioly:  What version of `gopls` are you using? (`gopls version`). Please make sure you are using the latest - you can update by opening the command palette (Ctrl + Shift + P) and running the Go: Install/Update Tools command.

**Comment by hyangah** [comment]
@rafa-acioly And please provide the extension version as well. (`code --list-extensions --show-versions`)

**Comment by rafa-acioly** [comment]
@hyangah the list:

```
akamud.vscode-theme-onedark@2.2.2
andyyaldoo.vscode-json@1.5.0
arcticicestudio.nord-visual-studio-code@0.14.0
Arjun.swagger-viewer@3.0.1
batisteo.vscode-django@0.20.0
bierner.markdown-mermaid@1.5.1
bungcip.better-toml@0.3.2
daylerees.rainglow@1.5.2
eamodio.gitlens@10.2.2
Equinusocio.vsc-community-material-theme@1.4.1
Equinusocio.vsc-material-theme@32.8.0
equinusocio.vsc-material-theme-icons@1.2.0
extr0py.vscode-relative-line-numbers@0.0.5
gerane.Theme-Dark-Dracula@0.0.5
ginfuru.ginfuru-better-solarized-dark-theme@0.9.4
GitHub.vscode-pull-request-github@0.18.0
golang.go@0.16.0
GrapeCity.gc-excelviewer@3.0.39
jcbuisson.vue@0.1.5
kevinkyang.auto-comment-blocks@1.0.1
mikestead.dotenv@1.0.1
ms-azuretools.vscode-docker@1.4.1
ms-python.python@2020.7.96456
ms-vsliveshare.vsliveshare@1.0.2478
mtxr.sqltools@0.22.11
octref.vetur@0.26.0
PKief.material-icon-theme@4.2.0
pnp.polacode@0.3.4
redhat.vscode-yaml@0.9.1
sdras.night-owl@1.1.3
Shan.code-settings-sync@3.4.3
teabyii.ayu@0.20.1
tomphilbin.gruvbox-themes@1.0.0
vscode-icons-team.vscode-icons@10.2.0
wangweixuan.yithemes@0.15.0
zhuangtongfa.material-theme@3.8.5
```

**Comment by rafa-acioly** [comment]
@stamblerre after running the `Install/Update`

> Tools environment: GOPATH=/home/rafael/go
> Installing 0 tool at /home/rafael/go/bin in module mode.

> All tools successfully installed. You are ready to Go :).

When i try to run the file `cd ~/go/bin/gopls && ./gopls version`

> no module information, gopls not built in module mod

**Comment by stamblerre** [comment]
Sounds like something is going wrong with tool installation in VS Code Go. @hyangah will have more advice on how to investigate that, but in the meantime, you can install the latest version of `gopls` by running `GO111MODULE=on go get golang.org/x/tools/gopls`.

**Comment by rafa-acioly** [comment]
@stamblerre i've updated all plugins on vscode and how the `gopls version` works fine, but now i'm getting this:

```
The code in the workspace failed to compile (see the error message below). If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new. go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./... builtin]: exit status 1: go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9 go: extracting golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9 go: extracting golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd build github.com/rafa-acioly/fry: cannot load github.com/rafa-acioly/teste/api/sellingprice: cannot find module providing package github.com/rafa-acioly/teste/api/sellingprice : packages.Load error
```

**Comment by stamblerre** [comment]
Is `github.com/rafa-acioly/teste` a private module? You may need to set the GOPRIVATE environment variable: https://golang.org/doc/go1.13#modules.

**Comment by hyangah** [comment]
Based on https://github.com/golang/vscode-go/issues/462#issuecomment-668717634, it looks like the original issue (failed to start gopls) was resolved by uninstalling/reinstalling the plugin. Looks pretty similar to https://github.com/golang/vscode-go/issues/459 which I have no idea why that happened. I am closing this issue because the discussion was diverged from the original problem. 
 
@rafa-acioly if setting `GOPRIVATE` env var does not fix the issue you had, please file a new issue to continue discussion.
