### ISSUE TITLE
installation: improve tool installation process

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#47]
Some ideas:

- Make sure all tools that can be installed with modules
- Consider using one of the newest stable Go versions to build tools regardless what target go version user is using for the project.
- Consider pinning tools at specific major versions to avoid breakages (an idea, not necessarily something I'm advocating for)
- Any tool that self-reports its version should be used to offer upgrades (like is done for `gopls`)

I'm sure there are other improvements we can make, so please add more here.

**Comment by stamblerre** [comment]
Also, see @hyangah's suggestions on https://github.com/golang/vscode-go/issues/66.

**Comment by hyangah** [comment]
We are using module mode already.
We will pin the versions of tools to handle compatibility and security - which will be tracked in https://github.com/golang/go/issues/52017 

Closing.
