### ISSUE TITLE
Go Tests Are Verbose By Default

### ISSUE THREAD

**Issue by swtch1** [golang/vscode-go#471]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.4 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.47.1
          485c41f9460bdb830c4da12c102daff275415b53
          x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.16.0
- Run `go env` to get the go development environment details

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/josh/.cache/go-build"
GOENV="/home/josh/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="bitbucket.org"
GONOSUMDB="bitbucket.org"
GOOS="linux"
GOPATH="/home/josh/go"
GOPRIVATE="bitbucket.org"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build567801905=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

Ran with all vscode settings disabled.

### Describe the bug
*What I did:*
Use any of the `Go: Test ...` commands

*What did I expect:*
For `go test` to run with less verbosity

*What happend:*
Go test appears to run increased verbosity, as if the `-v` flag is being implicitly passed to `go test`.

### Steps to reproduce the behavior:
- Install vscode-go v0.16.0
- Ensure vscode-go settings do **not** include `-v` flag.
- Execute `Go: Test All Packages In Workspace` command

v0.16.0
![image](https://user-images.githubusercontent.com/12050926/89325769-4537b900-d657-11ea-90fc-7af94c6cdc84.png)

v0.15.2
![image](https://user-images.githubusercontent.com/12050926/89326025-a790b980-d657-11ea-926d-06bad8d14cbe.png)

**Comment by hyangah** [comment]
@swtch1 thanks for the report. This is an oversight while transitioning to use `go test -json` underneath. 
If `-v` is not specified, we should suppress output from successful tests.

**Comment by leguminosa** [comment]
Hello @hyangah I am already using v0.16.1 but I still face this problem, it output all logs from the code, but it doesn't verbose out the go test log (such as === RUN etc)

**Comment by hyangah** [comment]
@leguminosa can you open a new issue and share your settings and the Go Test output?
