### ISSUE TITLE
Debugging using golang project standard (<root>/cmd/main.go)

### ISSUE THREAD

**Issue by baalimago** [golang/vscode-go#474]
Hello,

I recently adapted the [golang project standard](https://github.com/golang-standards/project-layout) for a new project I'm starting in order to keep up with best practices, but I no longer know how to debug the application using vscode. 

I used to use `"program": "{workspaceFolder}"` in launch.json, but this is no longer an option since the relative imports become incorrect. I build the application using `git build gitlab./.../<packagename>.git/cmd` as would be expected, and since the files then are based around the root of the directory, the relative imports (such as `<root>/config/configs.json` become fine. But I can't figure out how to achieve the same using vscode launch.json. 
Note, doing something like `{workspaceFolder}/cmd` will make the relative imports incorrect. And fixing this using `../` (to go back to root directory, from `<root>/cmd/main.go`) will break the building, since it then would look at `<root>../`. So it's either one or the other, and then I'll have to chose the golang project standard. 

Any help is appreciated, thanks.

**Comment by hyangah** [comment]
@baalimago `"program": "${workspaceFolder}"` maybe?

**Comment by hyangah** [comment]
@baalimago I hope you resolved the issue by now. Feel free to reopen the issue if the problem continues. The `#vscode` slack channel (http://gophers.slack.com/) is also good for questions.
