### ISSUE TITLE
Intellisense for Bazel projects with protos

### ISSUE THREAD

**Issue by Michaelhobo** [golang/vscode-go#479]
**Is your feature request related to a problem? Please describe.**
I'm starting a Go project (https://github.com/Michaelhobo/nrfbazel) which uses protos. I have a library (nrfbazelify/nrfbazelify.go) which imports a local generated proto as "github.com/Michaelhobo/nrfbazel/bazelifyrc" - this import path is from a go_proto_library Bazel rule. Since this doesn't resolve to anything, I get an import error that shows up under the bazelifyrc import, and intellisense for the import is broken.

**Describe the solution you'd like**
Ideally, I'd like the language server to support Bazel - use Bazel to build targets, and pull intellisense data from there. I could also stop putting all my dependencies in a separate go.mod just for vscode.

**Describe alternatives you've considered**
Is there some workaround for pointing the proto to a local proto file? I'd have to generate the Go code and store it somewhere though, not sure how easy that is. Is there any tooling around to do something like this?

**Comment by hyangah** [comment]
cc @stamblerre

**Comment by stamblerre** [comment]
There is an issue tracking this work for `gopls`: https://github.com/golang/go/issues/37205. The language server will work once there is a Bazel gopackagesdriver (https://github.com/bazelbuild/rules_go/issues/512).

**Comment by hyangah** [comment]
Closing in favor of the issues in the upstream repos.
