### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by lechnertech** [golang/vscode-go#489]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Writing a new function in vscode when a popup opened about the connection was lost to gopls.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

panic: runtime error: index out of range [2952] with length 2951

goroutine 11592 [running]:
golang.org/x/tools/internal/lsp/source.adjustRangeForWhitespace(0xc00032dc80, 0x1282686, 0x12826c8, 0x1aa3b60, 0xc00c85fff0, 0xc009f2a0c0, 0xc000517800, 0xb87, 0x1707, 0x0, ...)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/source/extract.go:591 +0x1c6
golang.org/x/tools/internal/lsp/source.canExtractFunction(0xc00032dc80, 0xc00032dc80, 0x1282685, 0x12826c8, 0x1aa3b60, 0xc00c85fff0, 0xc000517800, 0xb87, 0x1707, 0xc003d85400, ...)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/source/extract.go:542 +0xb0
golang.org/x/tools/internal/lsp/source.(*Command).Applies(0x1ffff40, 0x1ab18e0, 0xc008660ec0, 0x1ac5040, 0xc00ca77900, 0x1ab5720, 0xc009a25140, 0x4033000000000000, 0x0, 0x4038000000000000, ...)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/source/command.go:131 +0x1ac
golang.org/x/tools/internal/lsp.extractionFixes(0x1ab18e0, 0xc008660ec0, 0x1ac5040, 0xc00ca77900, 0x1ab5760, 0xc009f17800, 0xc00d5852c0, 0x4b, 0x4033000000000000, 0x0, ...)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/code_action.go:426 +0x32c
golang.org/x/tools/internal/lsp.(*Server).codeAction(0xc00028b100, 0x1ab18e0, 0xc008660ec0, 0xc002a7f880, 0xc002a7f880, 0x0, 0x0, 0x0, 0xc00157c580)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/code_action.go:169 +0xcb4
golang.org/x/tools/internal/lsp.(*Server).CodeAction(0xc00028b100, 0x1ab18e0, 0xc008660ec0, 0xc002a7f880, 0xc002a7f880, 0x0, 0x0, 0x1ab19a0, 0xc00b0bf860)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/server_gen.go:12 +0x4d
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ab18e0, 0xc008660ec0, 0x1acc400, 0xc00028b100, 0xc00b14b200, 0x1ab1b20, 0xc008660e40, 0x0, 0x0, 0x1a9f360)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/tsserver.go:311 +0x1c8a
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ab18e0, 0xc008660ec0, 0xc00b14b200, 0x1ab1b20, 0xc008660e40, 0xbfc3386d4de910d0, 0x70bcd244)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/protocol.go:62 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ab18e0, 0xc008660ec0, 0xc00b14b200, 0x1ab1b20, 0xc008660e40, 0x0, 0x0)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/lsprpc/lsprpc.go:521 +0x417
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ab18e0, 0xc008660ec0, 0xc00d03aee0, 0x1ab1b20, 0xc008660e40, 0x100786f, 0xc000210358)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00cb95bc0, 0xc00b0bf8f0, 0xc000332760, 0x1ab18e0, 0xc008660ec0, 0xc00d03aee0, 0x1ab1b20, 0xc008660e40)
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/Users/lechner/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:100 +0x171
[Error - 4:38:13 PM] Connection to server got closed. Server will not be restarted.
[Error - 4:38:13 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:14648:25)
    at Object.dispose (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:11283:35)
    at LanguageClient.handleConnectionClosed (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:13518:42)
    at LanguageClient.handleConnectionClosed (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:72336:15)
    at closeHandler (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:13505:18)
    at CallbackList.invoke (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:25578:39)
    at Emitter.fire (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:25637:36)
    at closeHandler (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:13984:26)
    at CallbackList.invoke (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:25578:39)
    at Emitter.fire (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:25637:36)
    at StreamMessageReader.fireClose (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:30113:27)
    at Socket.<anonymous> (/Users/lechner/.vscode/extensions/golang.go-0.16.0/dist/goMain.js:30153:46)
    at Socket.emit (events.js:208:15)
    at Pipe.<anonymous> (net.js:588:12)

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Thanks for the report! I believe this should have been fixed by https://go-review.googlesource.com/c/tools/+/246757 and https://go-review.googlesource.com/c/tools/+/247182. If you're encountering this frequently, you can update to `gopls@master` by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.
