### ISSUE TITLE
gopls: Couldn't start client gopls(Initialization failed: Error: json: cannot unmarshal object into Go struct field .tagSupport of type bool.)  

### ISSUE THREAD

**Issue by manfredchester** [golang/vscode-go#494]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.
### Couldn't start client gopls

The gopls server failed to initialize. Would you like to report a gopls issue on GitHub? You will be asked to provide additional information and logs, so PLEASE READ THE CONTENT IN YOUR BROWSER.

The language server is not able to serve any features. Initialization failed: **_Error: json: cannot unmarshal object into Go struct field .tagSupport of type bool._**

<ANSWER HERE>

**[Error - 上午11:41:40] Starting client failed
  Message: json: cannot unmarshal object into Go struct field .tagSupport of type bool
  Code: -32700 
[Error - 上午11:41:40] server not initialized**

Couldn't start client gopls

The gopls server failed to initialize. Would you like to report a gopls issue on GitHub? You will be asked to provide additional information and logs, so PLEASE READ THE CONTENT IN YOUR BROWSER.

The language server is not able to serve any features. Initialization failed: Error: json: cannot unmarshal object into Go struct field .tagSupport of type bool.

<PASTE STACK TRACE HERE>

{
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "window.zoomLevel": 1,
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "files.autoSave": "afterDelay",
    "workbench.iconTheme": "vscode-icons",
    "files.eol": "\n",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.autocompleteUnimportedPackages": true,
    // "go.docsTool": "gogetdoc",
    // "go.formatTool": "goimports",
    "editor.multiCursorModifier": "ctrlCmd",
    "go.testTimeout": "3000s",
    "go.testFlags": [
        "-v"
    ],
    "diffEditor.ignoreTrimWhitespace": false,
    "git.suggestSmartCommit": false,
    "gitlens.gitCommands.closeOnFocusOut": true,
    "go.languageServerExperimentalFeatures": {
    },
    "go.enableCodeLens": {
    },
    "gitlens.views.repositories.files.layout": "tree",
    "gitlens.views.compare.files.layout": "tree",
    "go.gopath": "",
    "go.playground": {
        "openbrowser": true,
        "share": true,
        "run": true
    },
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.inferGopath": true,
    "go.gotoSymbol.includeImports": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.formatTool": "gofmt",
    "editor.rulers": [
    {}
    ],
    "go.useLanguageServer": true,
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
}

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Please update your `gopls` version: `GO111MODULE=on go get golang.org/x/tools/gopls@latest`.

**Comment by manfredchester** [comment]
nice~i got it √
