### ISSUE TITLE
proposal: break line in long function declarations

### ISSUE THREAD

**Issue by bancek** [golang/vscode-go#511]
`gofmt` does not break line function declarations but I find it quite annoying to do it by hand.

I've created a simple VS Code extension (unpublished) to do that for me. The extension does not do it automatically. You have a editor command to break the line if you want to.

Would you be interested to have this functionality in the official Go extension?

https://github.com/bancek/vscode-go-utils

Example:

```go
func (p *receiver) funcName(arg1 func (a1 t1, a2 t2) (tres), arg2 type2, arg3 type3) (func (a1 t1, a2 t2) (tres), error) {
	body
}
```
```go
func (p *receiver) funcName(
	arg1 func (a1 t1, a2 t2) (tres),
	arg2 type2,
	arg3 type3,
) (
	func (a1 t1, a2 t2) (tres),
	error,
) {
	body
}
```

**Comment by hyangah** [comment]
Per https://github.com/golang/go/wiki/CodeReviewComments#line-length, that is against the recommendation.
