### ISSUE TITLE
Debug Arrow Not Showing

### ISSUE THREAD

**Issue by recfish** [golang/vscode-go#520]
Breakpoints work, but vscode does not tell me what line I'm on (via the yellow arrow). How can I fix this?

**Comment by hyangah** [comment]
@recfish Do you mean this yellow arrow is missing?

![image](https://user-images.githubusercontent.com/4999471/90162299-6b99da80-dd62-11ea-8b23-9a64b8b2cebc.png)

That must be annoying. Can you please provide repro the case?

**Comment by beaniebag** [comment]
I'm getting the same issue.  I can see data in the variables column in the sidebar, but no data displays if I hover over the variable in the code.

**Comment by hyangah** [comment]
@beaniebag @recfish First make sure the dlv is up to date (the current released version is v1.5.0). 
Then, can you enable logging and see if the debug (https://github.com/golang/vscode-go/blob/master/docs/debugging.md#enable-logging)? The log should have `StoppedEvent("breakpoint")` and following `ThreadsRequest/ThreadsResponse` and `StackTraceRequest` with the stopped location info.

**Comment by beaniebag** [comment]
I originally was running version 1.1.
I've upgraded to version 1.5 and enabled the logging settings.  I get the StoppedEvent and the other information.
Further troubleshooting I'm finding that I'll get the yellow marker for the main package, and when it runs a go routine, and when it panics.  Once it enters the package I created in the same project, debug no longer highlights the current line.  Haven't confirmed if it stops on different file, or if it's a different package than main.

**Comment by hyangah** [comment]
@beaniebag Is it possible to share with us the trace when the issue occurs, or the repro-case?

**Comment by beaniebag** [comment]
I figured out what was going wrong.  My import had a different case-sensitivity than the directory it belonged to.

I.e. I had: import "testdigital/new/test"
but the directory was: import "test**D**igital/new/test"

Compiling was fine so long as every import followed the "testdigital" convention, but the debugger wouldn't work correctly unless they were all "testDigital"

**Comment by hyangah** [comment]
@beaniebag Thanks for the followup!

@recfish please check if you have the same misconfiguration. If not, please reopen or file a new issue with the example to reproduce the problem. Thanks!
