### ISSUE TITLE
UI: clearly indicate whether gopls is enabled or not

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#525]
The very first question we ask users is often whether they are using the language server or not.
I hope it's obvious for users by checking `"go.useLanguageServer"` setting, but there are multiple layers of the settings (user, workspace, remote, ...) and we need to inspect every layer.

We can replace the 'Go Module' status bar with the language server status - https://github.com/golang/vscode-go/issues/156 Or, add a small icon or emoji character in the new 'Go' status bar.

/cc @stamblerre @suzmue

**Comment by stamblerre** [comment]
We should also add `gopls version` to the issue template.

**Comment by hyangah** [comment]
This is also fixed. The little lightning icon next to the go version in the unified Go status bar indicates whether the language server is activated or not. Users can also access the gopls server log output channel using the status bar item. Thanks @suzmue !
