### ISSUE TITLE
Go test prints out all logs from the code without verbose option

### ISSUE THREAD

**Issue by leguminosa** [golang/vscode-go#528]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.48.0
db40434f562994116e5b21c24015a2e40b2504e6
x64

- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.16.1
- Run `go env` to get the go development environment details
	- GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/nakama/.cache/go-build"
GOENV="/home/nakama/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/nakama/.gvm/pkgsets/go1.13/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/nakama/.gvm/gos/go1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/nakama/.gvm/gos/go1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build061898164=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    "go.lintTool": "golangci-lint",
    "go.lintFlags": [
        "--fast",
        "--enable=gocyclo",
        "--enable=goconst",
        "--enable=gocognit",
        "--disable=errcheck",
        "--disable=staticcheck",
        "--disable=govet"
    ],
    "go.vetFlags": [
        "-composites=false"
    ],
    "go.coverageDecorator": {
        "type": "highlight",
        "coveredHighlightColor": "rgba(64,128,128,0.5)",
        "uncoveredHighlightColor": "rgba(128,64,64,0.25)",
        "coveredGutterStyle": "blockgreen",
        "uncoveredGutterStyle": "blockred"
    },
    // "go.testOnSave": true,
    "go.coverOnSave": true,
    "go.coverOnSingleTest": true,
    "go.coverOnSingleTestFile": true,
    "go.testFlags": [],
    "go.formatTool": "goimports",
    "go.gopath": "/home/nakama/.gvm/pkgsets/go1.13/global",
    "go.goroot": "/home/nakama/.gvm/gos/go1.13",
    "go.useLanguageServer": true,
    "go.languageServerFlags": [
        "-rpc.trace",
        "serve",
        "--debug=localhost:6060",
    ],

### Describe the bug
A clear and concise description of what the bug.
I don't put verbose flag in go test, but in output go test tab, the logs from the code all appears even if the tests are all succeed

### Steps to reproduce the behavior:
1. With cover on save set to true, just save the code anywhere, and vscode shall run go test for that package.
![image](https://user-images.githubusercontent.com/38403278/90266485-47332080-de7e-11ea-8e53-02fc05ed29be.png)

2. I tried running the go test via terminal as a comparison, and it clearly is verboseless, so it's not the problem from the code.
![image](https://user-images.githubusercontent.com/38403278/90266539-5c0fb400-de7e-11ea-90ac-b61b133a8848.png)

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
Strangely the output is different from the verbose output either. Can you try the exact same command the extension is running (no target arg) from the package directory?

`/home/nakama/.gvm/gos/go1.13/bin/go test -timeout 30s`

**Comment by leguminosa** [comment]
> Strangely the output is different from the verbose output either. Can you try the exact same command the extension is running (no target arg) from the package directory?
> 
> `/home/nakama/.gvm/gos/go1.13/bin/go test -timeout 30s`  

I did, the screenshot is attached above

**Comment by hyangah** [comment]
@leguminosa From the screenshot, I see you specified the target (the package path). 
Based on the log output, I guess the output is printed outside of the testing package.
https://user-images.githubusercontent.com/38403278/90266485-47332080-de7e-11ea-8e53-02fc05ed29be.png

Not sure what utilities you are using to generate the log, but if they are using the standard `log` or `fmt` packages, they appear in non-verbose `go test` output. See below. 

```
$ cat quote_test.go
... 
func TestGlass(t *testing.T) {
	fmt.Println("here is fmt.Println(`fmt msg`)")
	log.Println("here is log.Println(`log msg`)")
}
...

$ go test
here is fmt.Println(`fmt msg`)
2020/08/14 13:43:17 here is log.Println(`log msg`)
PASS
ok      rsc.io/quote    0.075s
```

**Comment by leguminosa** [comment]
It wasn't logged out at all before, and the logging tools hasn't changed since. We're using custom logger (not standard fmt nor log.logger instance). 

I will try again without specifying the package, 

But even if the command shown in the output doesn't include package, the command runs package test (as in, not a whole packages test, but only one package in whichever I press save - with cover on save option enabled)

**Comment by hyangah** [comment]
@leguminosa Thanks for providing more info. I hope the cl/248738 to address the regression.

**Comment by leguminosa** [comment]
Thank you @hyangah

**Comment by hyangah** [comment]
@leguminosa Once this is released as Go Nightly, would be nice if you have time to test it. Thanks!

**Comment by leguminosa** [comment]
Thank you very much for your help @hyangah !

I tried installing older version (before 0.16) and yes it is returning to previous state (clean output for success test), so all changes mentioned in this issue is in 0.16 cycles...

btw what is Go Nightly? like beta / pre-release version?

**Comment by leguminosa** [comment]
what should I do right now? @hyangah 
0.16.2 hasn't released yet, but there is pre-release, should I try download the .vsix https://github.com/golang/vscode-go/releases/tag/v0.16.2-rc.1 and install it on my vscode?

**Comment by hyangah** [comment]
@leguminosa Yes, please. The prerelease vsix loading instruction is here (https://github.com/golang/vscode-go/blob/master/docs/nightly.md#testing-pre-releases).

**Comment by hyangah** [comment]
I manually tested it and made it 0.16.2.

**Comment by leguminosa** [comment]
I just updated my vscode-go to 0.16.2, and the go test works like it used to do, it solved this issue.

Thank you very much @hyangah 
![FB_IMG_1597807776896](https://user-images.githubusercontent.com/38403278/92072484-83053a00-eddb-11ea-9c16-c99f76322b1b.jpg)
