### ISSUE TITLE
performance: consider bundling extension

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#53]
Original bug report is https://github.com/microsoft/vscode-go/issues/2997

This extension got bigger. vsce recommends https://aka.ms/vscode-bundle-extension

```
This extension consists of 2266 files, out of which 1509 are JavaScript files. 
For performance reasons, you should bundle your extension: 
https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary 
files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
```

https://github.com/microsoft/vscode-extension-telemetry/issues/41 
(due to https://github.com/microsoft/ApplicationInsights-node.js-native-metrics/issues/4) was one of the road blockers. We can probably prune the dependency. 

Not sure about interaction with debug adapter yet.

**Comment by OneOfOne** [comment]
Is anyone working on this? if not I'd like to take work on it.

**Comment by hyangah** [comment]
@OneOfOne i don't know anyone working on this. Last time I attempted, I was stuck at testing. Contribution is welcome!
