### ISSUE TITLE
package.json: considering using pre-releases of the language client in the Nightly

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#532]
This would allow us to test out new `gopls` features. The main concern would be backwards-incompatible APIs (it seems v0.7.0 will require changes in our code). Or maybe we could have a dev branch for it? It'd just be nice to have a simple way of building VS Code Go with the most recent language client.

**Comment by hyangah** [comment]
Master is our dev branch. The main purpose of the nightly is to test the features for the next release. If the version of the language client is *pretty close* to be official and the api is relatively stable, we can simply check into the master from which we cut our nightly.
