### ISSUE TITLE
colors gone awry on non-selected text

### ISSUE THREAD

**Issue by meling** [golang/vscode-go#541]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.15 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.48.0 db40434f562994116e5b21c24015a2e40b2504e6 x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `v0.16.1`
- Run `go env` to get the go development environment details
	- 

```text
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/meling/Library/Caches/go-build"
GOENV="/Users/meling/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/meling/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/meling/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/meling/work/quickfeed/kit/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qf/stfl1sbn3p9939ylh7v1fm680000gn/T/go-build519744011=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "go.enableCodeLens": {
        "references": false,
        "runtest": true
    },
    "go.autocompleteUnimportedPackages": true,
    "go.lintTool": "golangci-lint",
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.coverOnSave": true,
    "go.coverOnSingleTest": true,
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true,
        "documentLink": true,
    },
    "gopls": {
        "usePlaceholders": true,
        "completeUnimported": true,
        "buildFlags": [
            "-tags=solution"
        ],
    },
    "go.testFlags": [],
    "go.useLanguageServer": true
}
```

### Describe the bug

Best description is the attached picture below.

Often, when editing a Go file, VSCode suddenly turns on some weird coloring (almost looks like it is diffing something with grey and red, but it is in the main editor.) The coloring does not go away after Restart of the language server, or Reloading the developer window.

I expected it to not display these "overlay/background" grey/red colors, and just display black.

### Steps to reproduce the behavior:
Currently, I'm not able to get rid of the problem, and I'm also not able to find a reliable way to reproduce.

### Screenshots or recordings

![Screen Shot 2020-08-18 at 09 15 45](https://user-images.githubusercontent.com/810999/90484549-a0c57480-e136-11ea-8e32-31389d5254be.png)
![Screen Shot 2020-08-18 at 09 10 29](https://user-images.githubusercontent.com/810999/90484562-a4f19200-e136-11ea-9e49-fdd18f403d26.png)

**Comment by meling** [comment]
The coloring also carries over to the git / diff view:
![Screen Shot 2020-08-18 at 09 53 21](https://user-images.githubusercontent.com/810999/90486125-cbb0c800-e138-11ea-90ca-a4b30e56a47f.png)

And if I click in the left-most window, also this gets the bad coloring:
![Screen Shot 2020-08-18 at 09 53 41](https://user-images.githubusercontent.com/810999/90486199-eaaf5a00-e138-11ea-8faf-1fb97ac1c23f.png)

**Comment by hyangah** [comment]
It looks like this is the test coverage information. (red is for the lines that are not covered, greenish ones are those covered).
If you didn't mean to get the coverage info, you can disable it with "go.coverOnSave". And also there is "Go: Toggle test Coverage in Current Package" command you can conveniently turn it on/off. If you want to compute the coverage info but want different visualization, you can try `"go.coverageDecorator": { "type": "gutter"}`.
