### ISSUE TITLE
Debug -> variables -> copy value: cropped!

### ISSUE THREAD

**Issue by sir-farfan** [golang/vscode-go#549]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.4 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.48.0 
           db40434f562994116e5b21c24015a2e40b2504e6 
           x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/farfan/.cache/go-build"
GOENV="/home/farfan/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/farfan/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build873650948=/tmp/go-build -gno-record-gcc-switches"

### Describe the bug
I want to copy the values of a lengthy JWT token, from a variable, while using the debugger, but when I click "copy value" I only get a cropped version of the variable:
`"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.IjEyMzQeyJhY2NpZCI61NnJzYTQ...+816 more"`

I also tried just writing the variable name in the console, but I only got that cropped string.

Putting a bunch of fmt.Println all over the place defeats the purpose of the debugger... right?

### Steps to reproduce the behavior:
1. Initialize some string variable with a thousand characters
2. Start debugger
3. Attempt to copy the value

**Current Result**
"The Eurasian crag martin (Ptyonoprogne rupestris) is a small swa...+921 more"

**Expected Result**
Full wikipedia paragraph

**Simple debug sample**
https://gist.github.com/sir-farfan/b81eb9788ce44db93fd677d19f0c2299

**Comment by hyangah** [comment]
@sir-farfan Is it not printing the long string even after adjusting `dlvLoadConfig`/`maxStringLen`?

https://github.com/golang/vscode-go/blob/master/docs/debugging.md#configuration

**Comment by sir-farfan** [comment]
OK, I was missing that configuration, now it works.
