### ISSUE TITLE
"gopls" preference is saying: "Unknown Configuration Setting"

### ISSUE THREAD

**Issue by macintacos** [golang/vscode-go#556]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.15 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	```
	1.48.1
	3dd905126b34dcd4de81fa624eb3a8cbe7485f13
	x64
	```
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.16.1
- Run `go env` to get the go development environment details
	```
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/Users/juliant/Library/Caches/go-build"
	GOENV="/Users/juliant/Library/Application Support/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/juliant/GoWorkspace/pkg/mod"
	GONOPROXY=""
	GONOSUMDB=""
	GOOS="darwin"
	GOPATH="/Users/juliant/GoWorkspace"
	GOPRIVATE=""
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/Cellar/go/1.15/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/Cellar/go/1.15/libexec/pkg/tool/darwin_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="1"
	GOMOD="/Users/juliant/GitLocal/Work/conduit/go.mod"
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/h_/3f3z91t936q41d46hflhqq640000gn/T/go-build119823570=/tmp/go-build -gno-record-gcc-switches -fno-common"
	```

### Share the Go related settings you have added/edited

```
  "[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.snippetSuggestions": "none"
  },
  "go.autocompleteUnimportedPackages": true,
  "go.buildOnSave": "package",
  "go.formatTool": "goimports",
  "go.lintFlags": ["--fast"],
  "go.lintOnSave": "package",
  "go.lintTool": "golangci-lint",
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
  "go.useLanguageServer": true,
  "go.vetOnSave": "package",
```

### Describe the bug

I'm trying to add some `gopls`-related settings, but it doesn't appear to be working properly since the settings editor is showing "Unknown Configuration Setting". Some links I'm referencing that is making me believe that this is unexpected behavior and not me just doing something wrong:

- https://github.com/golang/tools/blob/master/gopls/doc/vscode.md
- https://github.com/golang/go/issues/32049#issuecomment-549998644 (I was actually trying to set this option)

When I enter the `gopls` option, the editor grays out, which is typical for options that aren't in  any extensions that are loaded. Other options work fine. Is this option gone? Is there another way I'm supposed to set `gopls` options that I'm unaware of?

### Steps to reproduce the behavior:
1. Try to add `gopls` as a preference in `settings.json`
2. It doesn't seem to work for me.

### Screenshots or recordings

This is from a workspace's `settings.json`, however I see this in the global `settings.json` as well:
<img width="380" alt="settings json — conduit 2020-08-20 at 18 00 41" src="https://user-images.githubusercontent.com/8128941/90830546-d83b4900-e30f-11ea-8193-55a4aa6e6ea9.png">

**Comment by hyangah** [comment]
Closing in favor of  https://github.com/golang/vscode-go/issues/197
