### ISSUE TITLE
When using vscode workspaces, third party packages fails to get imported

### ISSUE THREAD

**Issue by jcbritobr** [golang/vscode-go#563]
When using vscode workspaces, third party packages fails to get imported all time. I have tryed go mod tidy, go get -u and nothing works to fix this issue.

go version - 1.15 amd64
os - windows 10 amd64

vscode - code -v : 1.48.1 3dd905126b34dcd4de81fa624eb3a8cbe7485f13 x64

**Comment by hyangah** [comment]
@jcbritobr Can you elaborate what you meant by 'failing to get imported'? It can mean multiple different things.  
Example code and repro step, or screenshot/video to demonstrate what you meant may be helpful.

**Comment by jcbritobr** [comment]
> 
> 
> @jcbritobr Can you elaborate what you meant by 'failing to get imported'? It can mean multiple different things.
> Example code and repro step, or screenshot/video to demonstrate what you meant may be helpful.

```go
import "github.com/gorilla/mux"
```

when using workspaces, this code do not work. It can't import gorilla mux, and gopls mark it with red.

**Comment by stamblerre** [comment]
Can you please share your `gopls` logs when you see this? Instructions for how to capture them can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs). Also, please make sure to open your workspace to the directory containing your `go.mod` file. This is currently a requirement of `gopls`, but something that we're working on changing in future versions.

**Comment by jcbritobr** [comment]
I will try put a go.mod in root folder and reference other modules in it, and see if it will work. I'll put what you ask here also.

**Comment by jcbritobr** [comment]
The workspace starts to working again. For some reason. 'll close this issue for a while until get it reproduced yet. Maybe was vscode issue, and not from vscode-go.

![image](https://user-images.githubusercontent.com/6579862/91167990-38811080-e6ab-11ea-8e06-7986dedee013.png)

**Comment by jcbritobr** [comment]
Got it reproduced. It happens only when the module folder is under a workspace. Look below:
![image](https://user-images.githubusercontent.com/6579862/91168582-41bead00-e6ac-11ea-836d-e43cd4be4906.png)

Gorilla mux cant be imported inside a workspace. Hope you guys may undertand the issue now.

**Comment by jcbritobr** [comment]
I'll look for more info and post it here

**Comment by stamblerre** [comment]
It looks like you are opening the directory at the `github` directory, but the `gorilla` directory contains the `go.mod` file. When you add a folder to your workspace, it has to be the directory containing the `go.mod` file or a subdirectory.

**Comment by jcbritobr** [comment]
> 
> 
> It looks like you are opening the directory at the `github` directory, but the `gorilla` directory contains the `go.mod` file. When you add a folder to your workspace, it has to be the directory containing the `go.mod` file or a subdirectory.

Well, if this works as you say, then vscode-go do not supports workspace feature from vscode. In modules root folder all works as expected.

**Comment by stamblerre** [comment]
You can continue using VS Code workspaces, you just have to add the modules to your workspace (View -> Add Folders to Workspace).

**Comment by jcbritobr** [comment]
I did this. All folders have a go.mod file
![image](https://user-images.githubusercontent.com/6579862/91224185-19f53680-e6f8-11ea-8305-0cfc26230374.png)

**Comment by stamblerre** [comment]
To clarify, the folders added to the workspace have to be **exactly** the directories that contain the `go.mod` file. In your case, this would be the `gds` and `gorilla` folders--you have to add them as folders to the workspace.

**Comment by jcbritobr** [comment]
> 
> 
> To clarify, the folders added to the workspace have to be **exactly** the directories that contain the `go.mod` file. In your case, this would be the `gds` and `gorilla` folders--you have to add them as folders to the workspace.

Now I understood. All is working correctly. I'll close the issue. You had solve it. Thank you @stamblerre
