### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by carljia999** [golang/vscode-go#565]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls cannot started.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

go/bin/gopls: error while loading shared libraries: unexpected PLT reloc type 0x00
[Error - 11:58:02 AM] Connection to server got closed. Server will not be restarted.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
Hi @carljia999, seems like there may be an issue with your gopls binary. Could you try deleting it and reinstalling gopls and see if that helps?

**Comment by carljia999** [comment]
Thanks a lot. It is fixed after reinstalling gopls.
