### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by xrfang** [golang/vscode-go#572]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

This is the error message in the "output" panel:

[Error - 下午9:23:45] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0 
[Info  - 下午9:23:45] 2020/08/25 21:23:45 server shutdown without initialization

What I did is just use "open file" menu command to open a **local** Go source code. there is no non-file URIs envolved as far as I can see.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

There is **NO** stack trace available.   One suggestion about such automated crash reporting is that you should send the log files or crash reports automatically, put it in there awaiting user approval.    I have had such error reporting twice and never find any crash logs!

**Comment by stamblerre** [comment]
@xrfang: What version of `gopls` are you using (`gopls version`)? Make sure to download the latest version by opening the Command Palette (Ctrl + Shift + P) and selecting Go: Install/Update Tools.

The error message you pasted in here is the crash log in your case, so thank you for sharing it. Older versions of `gopls` did not support opening a single file, which is the error that you're seeing here.

**Comment by xrfang** [comment]
@stamblerre 

golang.org/x/tools/gopls 0.4.1
    golang.org/x/tools/gopls@v0.4.1 h1:0e3BPxGV4B3cd0zdMuccwW72SgmHp92lAjOyxX/ScAw=

I used ctrl-shift-p to update go tools, it seems that I am already using the latest version.

**Comment by stamblerre** [comment]
The latest version is `gopls/v0.4.4`. If you need to update manually, you can do so by running `GO111MODULE=on go get golang.org/x/tools/gopls@latest`.

**Comment by xrfang** [comment]
@stamblerre with 0.4.4, there are no problem opening a single go source file
