### ISSUE TITLE
Duplicate information in ctrl+hover popup

### ISSUE THREAD

**Issue by emil14** [golang/vscode-go#576]
Why am I see duplicate information when I put my mouse on variable with a ctrl?

![Screenshot from 2020-08-26 23-56-38](https://user-images.githubusercontent.com/6453537/91356124-d2ee6a80-e7f7-11ea-9334-81d6f0ad369a.png)

Without ctrl everything is okay

**Comment by stamblerre** [comment]
Ctrl + hover in VS Code triggers "Peek definition", so it's actually showing you where the code is defined and the hover text for the symbol. In the case of the struct, these are the same, which is why you see the duplication.
