### ISSUE TITLE
vscode Go navigation stops when importing C code at the top

### ISSUE THREAD

**Issue by DariusParvin** [golang/vscode-go#579]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.12.1 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.48.1
3dd905126b34dcd4de81fa624eb3a8cbe7485f13
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.16.1
- Run `go env` to get the go development environment details
	- 
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/dariuscognac/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/dariuscognac/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/dariuscognac/Documents/GitHub/lnd/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r5/yk8yg2xs1gs8xzkn5l8vr72w0000gn/T/go-build550879609=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
    "go.useLanguageServer": true,
    "go.gopath": "",

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
1. When I import some C code using these lines of code, the code navigation stops working. Code:
```
/*
    struct Receive_return receive_cgo(char* msg, int length, void* p);
	char* send_cgo(void* p);
*/
import "C"
```
2. When I try to do 'Go to Definition' on an imported interface, it says 'No definition found'
However, if I remove the quoted code from the top and reload vs code, then code navigation works as expected.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/41220998/91497686-3bc6f880-e873-11ea-83a1-fcf8cb1ce64c.png)
![image](https://user-images.githubusercontent.com/41220998/91497922-aaa45180-e873-11ea-92e5-4a28daaa2461.png)

**Comment by stamblerre** [comment]
Please take a look at https://github.com/golang/go/issues/35721, as it has more detail about authoring cgo packages using `gopls`. But first, I would suggest updating to the latest version of Go (1.15). It has a number of cgo-related improvements that enable `gopls` to work with cgo packages.
