### ISSUE TITLE
Using vscode to build the WSL environment, i found that vscode can debug breakpoints  for C + + code on WSL Ubuntu, but can't debug go code.

### ISSUE THREAD

**Issue by wangyanzibai** [golang/vscode-go#583]
Using vscode to build the WSL environment, i found that vscode can debug breakpoints
 for C + + code on WSL Ubuntu, but can't debug go code.
vscode debug console display  underlay infomation doing nothing
API server listening at: 127.0.0.1:4181

root@LAdPTOP-ISG2Q1AE:/mnt/c/Users/wangyan# ps -ef |grep go
bt         160    99  0 09:50 tty2     00:00:00 /home/bt/.vscode-server/bin/3dd905126b34dcd4de81fa624eb3a8cbe7485f13/node /home/bt/.vscode-server/extensions/golang.go-0.16.1/dist/debugAdapter.js
bt         173   160  0 09:50 tty2     00:00:00 /usr/local/bin/dlv debug /mnt/d/gocode/src/test/testmain.go --headless=true --listen=127.0.0.1:18854 --api-version=2
bt         259   173  0 09:50 tty2     00:00:00 /mnt/d/gocode/src/test/__debug_bin
root       262    33  0 09:52 tty1     00:00:00 grep --color=auto go

root@LAPTOP-ISG2Q1AE:/mnt/c/Users/wangyan# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.10"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build102009680=/tmp/go-build -gno-record-gcc-switches"
root@LAPTOP-ISG2Q1AE:/mnt/c/Users/wangyan#

**Comment by hyangah** [comment]
@wangyanzibai Thanks for the issue report. 
Can you please check if the problem occurs when using the delve directly? Need to check first if this is the underlying tools issue or the debug extension's issue.

`/usr/local/bin/dlv debug /mnt/d/gocode/src/test/testmain.go` 

And, sample code and step for reproducing the problem is greatly appreciated.
