### ISSUE TITLE
activation: cannot find GOROOT directory (Go 1.8.3)

### ISSUE THREAD

**Issue by MitchTalmadge** [golang/vscode-go#595]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.8.3
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.48.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.16.1
- Run `go env` to get the go development environment details
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/talmadge/go"
GORACE=""
GOROOT="/home/talmadge/usr/local/share/go"
GOTOOLDIR="/home/talmadge/usr/local/share/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build842807144=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
"go.inferGopath": true
```

### Describe the bug
A clear and concise description of what the bug.
When trying to use Go 1.8.3 on Linux on a remote machine (via SSH), the following error is given and the extension does not load:

```
failed to run "/home/talmadge/usr/local/share/go/bin/go version": Error: Command failed: /home/talmadge/usr/local/share/go/bin/go version
go: cannot find GOROOT directory: /usr/local/go
```

I have tested versions 1.11.2 and 1.15.1 without problems. I need to use 1.8.3 for a college assignment.

After downgrading to 0.16.0, the extension loads but it does not find version 1.8.3. However, if I add:
```
"go.goroot": "/home/talmadge/usr/local/share/go"
```
Then it will give the error above. `go.goroot` does not change anything in 0.16.1.

The command in the error works fine in my terminal:
```
~ » /home/talmadge/usr/local/share/go/bin/go version                                                                                                                                             talmadge@lab1-32
go version go1.8.3 linux/amd64
```

I expect the extension to find and use Go 1.8.3 as it has been installed in my home directory at `~/usr/local/share/go`. 

### Steps to reproduce the behavior:
1. On Linux, download and extract go 1.8.3 (https://golang.org/dl/go1.8.3.linux-amd64.tar.gz) into a home directory.
2. Set the GOROOT environment variable in your shell to point to this install.
3. Open the vscode and try to load 1.8.3.
4. See the error appear in the Go output.
5. To verify, run `Go: Locate Configured Go Tools` and notice the output error.

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
@MitchTalmadge Go 1.8.x has been deprecated since early 2018. The recent versions of the extension will break in various ways with the old versions of Go even when it detects the GOROOT.
 
Old versions of the extensions are available for download in https://github.com/microsoft/vscode-go/releases. 
(Download the vsix file, and use the "Extensions: Install From VSIX..." command).

Can you tell me why does the college assignment require 1.8.3? The Go project runs with the [Go1 compatibility rule](https://golang.org/doc/go1compat) so, the newest versions of Go will continue to compile  programs developed with old Go versions. Except some rare cases, there is no reason to require old, unsupported versions.

**Comment by MitchTalmadge** [comment]
Thanks @hyangah. The reason for using 1.8.3 is that the assignment is graded (and more importantly, timed) by running it on 1.8.3. It's outdated lecture material that was never updated. New changes in later versions could cause timing differences. It's okay though, I don't really expect you to continue maintaining such old versions of Go. 

I have resorted to developing in 1.15 while manually testing my code in 1.8.3 through a terminal to make sure it's backwards compatible. This is working for me.

Thanks!
