### ISSUE TITLE
test: remove dependency on source code in GOPATH

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#6]
Current tests require GOPATH env var to be explicitly set 
(https://github.com/golang/vscode-go/blob/341a4fffaaeab1b90e74cb5b2d30705f6ca5b908/test/integration/extension.test.ts#L43)

and depend on source code preexisting under GOPATH/src. 
(https://github.com/golang/vscode-go/blob/341a4fffaaeab1b90e74cb5b2d30705f6ca5b908/test/integration/extension.test.ts#L663)

That is not ideal. Fix that.

**Comment by stamblerre** [comment]
@gopherbot please remove label Testing
