### ISSUE TITLE
Graceful termination of debugged process

### ISSUE THREAD

**Issue by segevfiner** [golang/vscode-go#601]
**Is your feature request related to a problem? Please describe.**
When stopping a debugging session, the debugged process is forcefully terminated. Some Go programs handle termination signals and can exit gracefully (`SIGTERM`, `SIGINT`), such as cleaning up locks, flushing to disk, etc., if given enough time.

**Describe the solution you'd like**
I want the ability to gracefully terminate debugged process, sending them `SIGTERM` and giving them enough time to exit, hard terminating them if they don't exit within some period. (Similar to `ContainerStop` in Docker, systemd daemon stop behavior, etc)

**Describe alternatives you've considered**
Have to send such signals myself rather than hitting "stop", just rely on the software knowing to recover from hard exits.

**Additional context**
vscode-go 0.16.1
dlv 1.5.0

I'm not sure what other language debuggers do, or if they handle this, and whether this is supported properly by the DAP.

**Comment by hyangah** [comment]
@segevfiner Thank you for the report. Can you share your launch settings? 

For local debugging, the current code (https://github.com/golang/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L719-L725) seems to send the `halt` message first so `dlv` can initiate a graceful termination, and then kills the debug process after 1sec. Maybe that's not sufficient.

**Comment by hyangah** [comment]
It turned out to be there is already an issue https://github.com/golang/vscode-go/issues/120
with the long history. Let's continue discussion there.
