### ISSUE TITLE
Completion is added to function documentation

### ISSUE THREAD

**Issue by DasJott** [golang/vscode-go#602]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.48.2
a0479759d6e9ea56afa657e454193f72aef85bd0
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.16.2
### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
```
	"go.buildOnSave": "off",
	"go.lintOnSave": "workspace",
	"go.vetOnSave": "package",
	"go.buildFlags": [],
	"go.lintFlags": [],
	"go.vetFlags": [],
	"go.coverOnSave": false,
    "go.formatTool": "goreturns",
	"go.docsTool": "godoc",
	"go.testFlags": [ "-v", "-count=1" ],
	"go.formatFlags": [],
	"go.gocodeAutoBuild": true,
    "go.useLanguageServer": true,
    "go.autocompleteUnimportedPackages": false,
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true
    },
```
### Describe the bug
On documenting a function, a autocomplete is provided. By accepting the choice pressing TAB, it appends the completion.  
It should replace the already written part.

### Steps to reproduce the behavior:
1. Write a public function
2. Start writing a comment above it
3. See the completion suggestion
4. Press Tab key
5. See the completion was added to the already written string

### Screenshots or recordings
![CompletionBugDoc](https://user-images.githubusercontent.com/6298761/92105595-5ce39800-ede3-11ea-90dc-02078130de1c.gif)

**Comment by hyangah** [comment]
@gopherbot upstream-tools, remove Documentation

**Comment by hyangah** [comment]
@DasJott Thanks for the report. The completion is done by gopls, and it looks like it's already fixed in upstream (https://github.com/golang/go/issues/39262)  - which I expect to be released soon.

For now, either
 - try the dev version of gopls (`GO111MODULE=on go get golang.org/x/tools/gopls@master`), or
 - if you trigger the completion after `// `, gopls will suggest the function name.
