### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zeffron** [golang/vscode-go#604]
gopls version: v0.4.4

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

I joined a VS Code remote session to pair and received a prompt to report and error

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

No stack trace was shown

**Comment by hyangah** [comment]
@zeffron Thanks for the report. Did you see the stack trace from the crash? 
It is in the OUTPUT pane > "gopls (server)" channel.

**Comment by zeffron** [comment]
Unfortunately, there was no output in that panel.

**Comment by hyangah** [comment]
@zeffron That's strange. "View: Toggle Output"   command > select "gopls (server)" should show stderr/stdout (crash dump) from the gopls execution. For example...

![Screen Shot 2020-09-03 at 1 49 43 PM](https://user-images.githubusercontent.com/4999471/92149675-5574bc80-edec-11ea-8d21-fce912bc110b.png)

Can you share your vscode go settings?

**Comment by zeffron** [comment]
I see 
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/6539680/92153583-21000100-edea-11ea-839e-c8997d3211e1.png"> in that window.

I suspect the issue is somehow related to the remote, which seems to not have gopls installed.

User settings:
```json
{
    "go.useLanguageServer": true,
    "terminal.integrated.scrollback": 100000,
    "editor.rulers": [
    80
    ],
    "go.alternateTools": {
        "go": "/usr/local/bin/go"
    }
}
```

Workspace settings:
```json
{
    "folders": [
        {
            "uri": "vsls:/",
            "name": "packetcop-api"
        },
        {
            "name": "packetcop-deploy",
            "uri": "vsls:/~1"
        },
        {
            "name": "packetcop",
            "uri": "vsls:/~2"
        },
        {
            "name": "packetcop.appliance",
            "uri": "vsls:/~3"
        }
    ],
    "settings": {
        "vsliveshare.join.reload.workspaceId": "AC4ED955817B4D0863E4DF1C5A950ED45EA5",
        "vsliveshare.join.reload.workspaceFolder": "/var/folders/xn/36p33m8s7sx2gwp699qvwwwr0000gp/T/vsliveshare/tmp-AC4ED955817B4D0863E4DF1C5A950ED45EA5",
        "files.hotExit": "off",
        "extensions.ignoreRecommendations": true,
        "typescript.tsc.autoDetect": "off",
        "jake.autoDetect": "off",
        "grunt.autoDetect": "off",
        "gulp.autoDetect": "off",
        "npm.autoDetect": "off",
        "debug.allowBreakpointsEverywhere": true,
        "html.autoClosingTags": false
    }
}
```

**Comment by hyangah** [comment]
@zeffron The fix for vscode live share crash will be available in the next gopls release https://github.com/golang/go/issues/41026 but that's basically just ignoring the vsls files. We are not yet sure if gopls or even this extension would work with the live share yet. 

Unfortunately, we don't know how vsls, vs code live share's internal works yet.

**Comment by zeffron** [comment]
All good. I wasn't really expecting it to work. Just saw the crash notification that asked me to file a report, so I did.

Thank you!

**Comment by hyangah** [comment]
I created https://github.com/golang/vscode-go/issues/605 to follow up.
