### ISSUE TITLE
Investigate compatibility with live share

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#605]
We've received multiple user requests and crash reports related to VS Code Live Share

https://code.visualstudio.com/blogs/2017/11/15/live-share
https://github.com/MicrosoftDocs/live-share

Many tools this extension depend on assumes all files in the repo are 
accessible with usual file API, outside VS Code. We are not yet sure
how they would work with Live Share yet.

**Comment by hyangah** [comment]
Let's make sure to discuss this before turning on gopls by default (even though I don't think gopls is the only part that doesn't support live share now).

**Comment by hyangah** [comment]
I just tried it and it looks like all the computation occurs on the server-side (i.e. gopls on the host's machine).
All other participants can simply turn off (iow disable) vscode-go extension during the session.

**Comment by stamblerre** [comment]
Should the extension disable itself if it encounters VSLS URIs or should users do that manually?

**Comment by hyangah** [comment]
I confirmed now the extension doesn't complain about gopls's crashes on the live share guest side.
Most of intellisense features offered by the language server and some features like adding tags, etc are working as expected. Some of the code lenses, debug features are not available without host's configuration, but it's also working as intended.

I will close this issue for now. As we find individual issues, we will address them in separate issues. 

Thanks for being patient. The feature is available in v0.19.0.

**Comment by hyangah** [comment]
Strange - when I tested, it worked. Now I can reproduce this issue again.
The language client library is still sending the initialization request with vsls: URI and gopls is unhappy about it of course.
