### ISSUE TITLE
debug: unreadable variables should be displayed with the unreadable error

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#607]
Give the following code snippet:
```
func main() {
	unread := (*int)(unsafe.Pointer(uintptr(12345)))
	runtime.Breakpoint()
	var x interface{}
	_ = x
	_ = unread
}
```

The variable pane shows:
![image](https://user-images.githubusercontent.com/51177946/92179061-d1750180-edf8-11ea-9af1-ffb74215d5e2.png)

while dlv prints:
```
(dlv) locals
unread = (*int)(0x3039)
x = (unreadable invalid interface type: key not found)
(dlv) p unread
*(unreadable protocol error E08 during memory read for packet $m3039,8)
(dlv) p x
(unreadable invalid interface type: key not found)
```

**Comment by suzmue** [comment]
This appears to be working in delve dap as well:

<img width="858" alt="Screen Shot 2021-06-07 at 5 38 32 PM" src="https://user-images.githubusercontent.com/6634754/121091341-da479900-c7b7-11eb-948c-06996bf56ce7.png">

@polinasok can we close? displaying x as nil seems fine to me, even though it is not the exact behavior of dlv cli

**Comment by polinasok** [comment]
Just wanted to add that x should be consistent with how dlv cli prints things because in dlv-dap we now use the same value printer. But how it is initialized might differ based on your system/set-up. I am seeing this:

![image](https://user-images.githubusercontent.com/51177946/123700826-d7b7ec80-d815-11eb-9487-b61812f7a0c4.png)

Nil that you are seeing is fine too. And it is likely that if you try to do the same with cli you might see it that as well.
