### ISSUE TITLE
code coverage: Apply Cover Profile runs without cwd

### ISSUE THREAD

**Issue by galli-leo** [golang/vscode-go#610]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.15 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.48.2`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `0.16.2` (though latest master also has this issue)
- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/leonardogalli/Library/Caches/go-build"
GOENV="/Users/leonardogalli/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/leonardogalli/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/leonardogalli/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/leonardogalli/Code/VIS/cdn/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/20/0vlkhfx51rv66qm56m4y1rhm0000gn/T/go-build195617975=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Share the Go related settings you have added/edited

```json
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.languageServerFlags": [],
    "go.lintOnSave": "off",
    "go.vetOnSave": "off",
    "go.lintTool": "golangci-lint",
    "go.languageServerExperimentalFeatures": {

    
    },
    "go.delveConfig": {
    
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": true
    },
    "go.testFlags": [
        "-coverpkg=all"
    ],
```

### Describe the bug
`Go: Apply Cover Profile` does not work.
Using the debugger, I traced this back to `go list` being ran without a `cwd`. I am guessing, it is not ran in the workspaceRoot in this case. This leads to it not being able to find the package paths.

By passing along the workspace root when calling `applyCodeCoverage` from the command handler, seemed to fix this issue for me.

### Steps to reproduce the behavior:
1. Execute `Go: Apply Cover Profile`
2. Select some profile
3. Coverage is not shown in editor.

### Screenshots or recordings
N/A

**Comment by hyangah** [comment]
@galli-leo thanks for the report with diagnostics.

When invoked directly through the command, `testDir` is not set https://github.com/golang/vscode-go/blob/d05379ecef48902830bf831906a8872ce3756f24/src/goCover.ts#L210
I don't know why it didn't cause an issue for @pjweinbgo and me earlier, but I agree it's better to run with the cwd set properly.

There are a couple of things to check:

1) what directory should we choose if this is a multi-folder workspace (`vscode.workspace.workspaceFolders` has more than one entry)? All?  Or can we use the directories of the open editors?
2) will `go list` from the workspace root always work - when we start to support multi-modules repo?

**Comment by galli-leo** [comment]
> 1. what directory should we choose if this is a multi-folder workspace (vscode.workspace.workspaceFolders has more than one entry)? All? Or can we use the directories of the open editors?

From a user perspective, it would make sense to me to try all folders. At least I would expect to have the coverage applied to all files in the workspace, meaning all folder would probably have to be checked.

> 2. will go list from the workspace root always work - when we start to support multi-modules repo?
From my limited testing, using `go list importPath` does not work, if you are not in the module directory. However, `go list ./...` will list all packages found in subdirectories and hence could be used instead? With that, the command only needs to be called once as well.

**Comment by hyangah** [comment]
> > 1. what directory should we choose if this is a multi-folder workspace (vscode.workspace.workspaceFolders has more than one entry)? All? Or can we use the directories of the open editors?
> 
> From a user perspective, it would make sense to me to try all folders. At least I would expect to have the coverage applied to all files in the workspace, meaning all folder would probably have to be checked.

Seems reasonable.

> 
> > 1. will go list from the workspace root always work - when we start to support multi-modules repo?
> 
> From my limited testing, using `go list importPath` does not work, if you are not in the module directory. However, `go list ./...` will list all packages found in subdirectories and hence could be used instead? With that, the command only needs to be called once as well.

go list importPath should work if your code is located in `GOPATH/src` as described in https://golang.org/cmd/go/#hdr-GOPATH_environment_variable. There is a similar issue #553. @pjweinbgo what do you think about switching to use `go list ./...` instead of gathering the seenPath from parsing of the profile first?

**Comment by pjweinb** [comment]
I'm having trouble reproducing this. running the go list command in my home directory (or in /tmp) it works fine. Perhaps it finds the answer in my module cache. If so, maybe it could get the wrong result if the local copy has changed.

I think we have to give it a real directory. vscode's working directory could be anywhere.

Working on a fix (or more robust code, at least)

**Comment by pjweinb** [comment]
There are two natural ways to find a directory in which to run go list.
1. go.apply.coverageProfile only works when there's a .go file active in the editor. We could use that directory.
2. There's a variable vscode.workspace.workspaceFolders which is a list of vscode workspace folders.

The advantage of the first is that presumably the user is interested in that .go file. The disadvantage is that information about other packages in the coverage file might be lost, although the user can repeat the command on other .go files without retyping the name of the coverage file.

The advantage of the second is that it seems to cover all possible places the coverage information could have come from. The disadvantage is that the implementation seems complex when there are multiple workspace folders.

**Comment by hyangah** [comment]
@galli-leo Can you please check if https://go-review.googlesource.com/c/vscode-go/+/253600 is sufficient to address the issue? (The cl will not check multi folders yet) 

```
$ git fetch https://go.googlesource.com/vscode-go refs/changes/00/253600/1 && git checkout -b change-253600 
FETCH_HEAD
```
https://github.com/golang/vscode-go/blob/master/docs/contributing.md#developing

**Comment by galli-leo** [comment]
@hyangah Works great on my end! Even across multiple packages :)

Thanks a lot for the quick turn around, great to see the extension improved every day :)
