### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by AugustineLi** [golang/vscode-go#616]
gopls version: v0.2.2

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Your `gopls` version appears to be very out-of-date. Please update by opening the Command Palette (Ctrl+Shift+P) and selecting the Go: Install/Update Tools command.

**Comment by hyangah** [comment]
@AugustineLi thanks for the report. Please file a new issue if the problem persists even after updating `gopls`. Thanks!
