### ISSUE TITLE
debug: breakpoints don't work when working with symlink

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#622]
Continuation of https://github.com/microsoft/vscode-go/issues/2958 (lost during repo migration) and https://github.com/microsoft/vscode-go/issues/1935. If we can't find a fix, we need to document this problem at least. 

cc @suzmue @quoctruong 

From microsoft/vscode-go#2958:

It is a continuation of an issue #1935

Unfortunately, the conversation there was locked to members only, so I had to open this card.

I have been able to reproduce the behavior (VSCode does not stop at breakpoints, while dlv itself does) for the symlinked GOPATH on two separate Ubuntu 19.10 installations, and I am pretty sure the issue is reproducible in other distros this way as well.

### Set up to reproduce:
1. Install go via package manager (both apt and snap work, mainly tested with snap, version go1.13.5 linux/amd64)
2. Create a future GOPATH as ~/go
3. Add GOPATH to your ~/.bashrc:
```
export GOPATH=`builtin cd ~/go && pwd`
export PATH=$PATH:$GOPATH/bin
```
4. Create/clone a project folder in ~/go/src/github.com/<your_github_name>/<your_repo_name>
5. Symlink ~/go/src/github.com to ~/GitHub
6. Set up Go support for VSCode just as it is recommended in the guide, or follow the UI recommendations & install all the libraries it now wants
7. Create a trivial main.go to try out the breakpoints:
<pre>
package main

import "fmt"

func main() {
	fmt.Println("Hello World!")
	i := 101
	fmt.Println(i)
}
</pre>

### Reproducing
- If you open ~/go/src/github.com/<your_github_name>/<your_repo_name> folder and set a breakpoint at i := 101, the execution would be successfully paused at it.
- However, if you open ~/GitHub/<your_github_name>/<your_repo_name> folder and set the breakpoint, it will never be hit.
No launch configuration was created, all default - debug was in both cases launched just by a press of F5.

Unfortunately, I have not been able to take a look inside the debugger yet, but at least this reproduction scenario might be helpful

**Comment by hyangah** [comment]
I think `config substitute-path` belongs to the `dlv` cli. (@polinasok can you please correct me if I am wrong). If true, that 
 implies this path resolution should be done on our side. Is it possible to swap with the resolved path from src/goDebugConfiguration.ts?

**Comment by polinasok** [comment]
Yes "config" command is part of the interactive dlv cli and is fully handled in the terminal frontend. I don't think we have a way of doing this interactively, do we? But we could support upfront session-long substitution via launch.json (like when config file is used with dlv).

**Comment by suzmue** [comment]
We plan to address this issue by providing a user configuration to map directories to each other. This would allow users to specify <symlink-dir> to <original-dir> and the debug adapter would translate all paths that it sends to delve and receives from delve. 

This will not attempt to resolve symlinked paths, but should make debugging more usable for users that are debugging symlinked directories.

**Comment by hyangah** [comment]
@suzmue Do we need anything more to close this issue?

**Comment by suzmue** [comment]
The substitutePath configuration will allow users to configure their projects so they can link from symlinked directories. For more information see the [documentation](https://github.com/golang/vscode-go/blob/master/docs/debugging.md#debugging-symlink-directories).
