### ISSUE TITLE
How to change Go build switches from within VSCode

### ISSUE THREAD

**Issue by GWevroy** [golang/vscode-go#630]
Hi,
I have been using Go for a short while now, and am now trying to cross compile for Raspberry Pi (running Linux on an ARM processor) and building code on my main desktop (Ubuntu Linux / Intel Arch).

When I attempt to compile, I am getting a series of errors as follows:

![Screenshot from 2020-09-11 09-11-57](https://user-images.githubusercontent.com/32412266/92807448-0099fd00-f40f-11ea-9084-2436daf5b3c5.png)

Reading online it appears that this is due to a "bug/feature" in more recent versions of Go, due to the -i switch being implemented at build time.
[See here for example](https://github.com/golang/go/issues/26071)

My question is, how can I disable this switch from within VS Code?

Another (perhaps slightly off topic) question: How can I change Go environment variables from within my VSCode Go code? IE I should be able to set Go compiler environment/switch directives from within the IDE, and not have to implement global changes that are going to affect other program builds where I am not cross compiling.

I am running Go Version 1.14.3
Compiling on Ubuntu 20.04 System (64Bit fully up to date)
VSCode Version: 1.47.3
VS Code Go extension Version: 0.16.2
Thank you for your assistance.

**Comment by hyangah** [comment]
If `-i` is the only issue, can you try to disable it by setting `"go.installDependenciesWhenBuilding"` to false? 

We are going to change the default in the next release (cl: https://go-review.googlesource.com/c/vscode-go/+/251263/)

For environment, see [`"go.toolsEnvVars"`](https://github.com/golang/vscode-go/blob/master/docs/settings.md#gotoolsenvvars) if it works for you.

**Comment by Witenite** [comment]
Thanks @hyangah, that worked for me. Unfortunately I have hit the next hurdle in that I can't find how to get VSCode to ONLY build and NOT attempt to run. I just end up with more errors, and no built executable. If I go into the command line terminal, navigate to my project.go file and build it from there, it builds just fine. I could find no way to make VSCode just build but not run my project.

Anyway, I have a working process that I can use, at least until somebody posts documentation online as to how to build a project in Go when cross compiling :)

Thanks again

**Comment by hyangah** [comment]
@Witenite I'd suggest 'Go: Build Current Package' command (accessible from the command palette) - but it doesn't produce the build executable in an accessible place. I filed #632 to follow up.

**Comment by stamblerre** [comment]
Closing, as this seems to be resolved.
