### ISSUE TITLE
There is no formatter for 'go' files installed.

### ISSUE THREAD

**Issue by williamsko** [golang/vscode-go#633]
Hello after updating my version of visual studio code I suddenly got this error : **There is no formatter for 'go' files installed.** while trying to format my code.

Moreover another strange error is displayed: **Error: TypeError: Cannot read property 'lt' of undefined**

Could you please give me a hand. I put here the current settings of my `settings.json `file.

`
{
    "window.zoomLevel": -1,
    "terminal.integrated.shell.osx": "zsh",
    "editor.codeLens": true,
    "python.linting.pylintArgs": [
        "--enable=W0614"
    ],
    "cornflakes.linter.executablePath": "/usr/local/bin/flake8",
    "sonarlint.rules": {
        "python:S107": {
            "level": "off"
        }
    },
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "todo-tree.tree.showScanModeButton": false,
    "terminal.integrated.rendererType": "dom",
    "go.inferGopath": false,
    "go.useLanguageServer": false,
    "go.addTags": {},
    "editor.accessibilitySupport": "off",
    "python.languageServer": "Microsoft",
    "typescript.preferences.importModuleSpecifier": "relative",
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "go.formatTool": "goimports"
}

`

**Comment by stamblerre** [comment]
What version of the Go extension are you using? The latest version if 0.16.2, so please update to that if you're using an older version.

**Comment by williamsko** [comment]
Hello Thanks for your message. I am using 0.16.2. I try to reinstall this and reload my vscode window.
After that I try to format my code mais the issue remains the same **There is no formatter for 'go' files installed.**

**Comment by stamblerre** [comment]
What is the output of `go version` and `go env`? Also, can you run the `Go: Locate Configured Go Tools` command from the Command Palette (Ctrl+Shift+P) and share its output?

The "Error: TypeError: Cannot read property 'lt' of undefined" error might indicate that the extension is not finding your go version.

**Comment by williamsko** [comment]
go version output : `go version go1.14.3 darwin/amd64`
go env oupt : 
`GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/alkengueleoua/Library/Caches/go-build"
GOENV="/Users/alkengueleoua/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/alkengueleoua/Documents/golang"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/alkengueleoua/Documents/projets/dmp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/75/clrsb44s2533mg1gq1_5nq7h0000gn/T/go-build475728489=/tmp/go-build -gno-record-gcc-switches -fno-common"`

and the last command : 

`Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/alkengueleoua/Documents/golang
GOROOT: /libexec
PATH: /usr/local/opt/python@3.8/bin:/usr/local/opt/openssl@1.1/bin:/Users/alkengueleoua/.nvm/versions/node/v10.15.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alkengueleoua/Documents/golang/bin:/libexec/bin

failed to run "/usr/local/bin/go version": Error: Command failed: /usr/local/bin/go version
go: cannot find GOROOT directory: /libexec

failed to run "/usr/local/bin/go version": Error: Command failed: /usr/local/bin/go version
go: cannot find GOROOT directory: /libexec`

**Comment by stamblerre** [comment]
Thanks for sharing that. Looks like an issue with your Go installation or the way that VS Code Go is picking it up. Your actual GOROOT is `usr/local/Cellar/go/1.14.3/libexec`, but VS Code Go thinks it is `/libexec`. Do you have the `GOROOT` environment variable set in your environment?

@hyangah: Any guesses for what's going on?

**Comment by hyangah** [comment]
@williamsko Can you please verify if your settings posted in the original report are complete?

VS Code maintains separate 'per-user' (`Preferences: Open Settings (JSON)`), 'per-workspace' (`Preferences: Open Workspace Settings (JSON)`).

Also, from the command palette, choose `Developer: Toggle Developer Tools`. It will open the chrome developer tools window. Select "Console" tab, and enter 
`process.env["GOROOT"]` 

![Screen Shot 2020-09-14 at 11 28 55 AM](https://user-images.githubusercontent.com/4999471/93105935-a3f04980-f67d-11ea-9d05-0feb09fea557.png)

This will show what GOROOT env var was set when launching the VS Code. The VS Code Go extension inherits the environment variables the VS Code sees.

**Comment by williamsko** [comment]
Hello, I have finally dealt with it. I just make an update of my golang version and everything seems to be working.
Thanks a lot for your help.
