### ISSUE TITLE
vscode remote mode env can't work

### ISSUE THREAD

**Issue by wkdzzb** [golang/vscode-go#635]
launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "host": "192.168.1.21",
            "port": 2345,
            "remotePath": "/root/sriov/cmd/sriov/sriov.go",
            "program": "/root/sriov/cmd/sriov/sriov.go",
            "env": {
                "CNI_COMMAND": "ADD",
                "CNI_CONTAINERID": "6b586b4912ee",
                "CNI_NETNS": "/var/run/netns/6b586b4912ee",
                "CNI_PATH": "/opt/cni/bin",
                "CNI_IFNAME": "net1"
            },
            "args": [],
            "showLog": true,
        }
    ]
}
```
The problem has been solved!
In 192.168.1.21:/root/sriov/cmd/sriov/
Start: `dlv debug  --headless=true --listen=:2345 --log --api-version=2`
**The env of launch.json doesn't work,it doesn't seem to support mode of remote.**
Start:`CNI_COMMAND=ADD CNI_CONTAINERID=6b586b4912ee CNI_NETNS=/var/run/netns/6b586b4912ee CNI_PATH=/opt/cni/bin CNI_IFNAME=net1 dlv debug  --headless=true --listen=:2345 --log --api-version=2`
In actuality,my process need env and stdin when i debugging.I read the following:

How to read input when debugging GO in Visual Studio Code:
[https://stackoverflow.com/questions/50884981/how-to-read-input-when-debugging-go-in-visual-studio-code](url)

Cannot debug programs which read from STDIN:
[https://github.com/microsoft/vscode-go/issues/219](url)

I try it ,the tasks.json can also resolve the env problem,like this:
tasks.json:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "dlv debug --headless --listen=:2345 --log --api-version=2",
            "problemMatcher": [],
            "options": {
                "cwd": "/root/sriov/cmd/sriov/sriov",
                "env": {
                    "CNI_COMMAND": "ADD",
                    "CNI_CONTAINERID": "6b586b4912ee",
                    "CNI_NETNS": "/var/run/netns/6b586b4912ee",
                    "CNI_PATH": "/opt/cni/bin",
                    "CNI_IFNAME": "net1"
                }
            },
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```
launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "remote",
            "host": "192.168.1.21",
            "port": 2345,
            "remotePath": "/root/sriov/cmd/sriov/sriov.go",
            "program": "/root/sriov/cmd/sriov/sriov.go",
            // "env": {
            //     "CNI_COMMAND": "ADD",
            //     "CNI_CONTAINERID": "6b586b4912ee",
            //     "CNI_NETNS": "/var/run/netns/6b586b4912ee",
            //     "CNI_PATH": "/opt/cni/bin",
            //     "CNI_IFNAME": "net1"
            // },
            "args": [],
            "showLog": true,
        }
    ]
}
```
Finally,i run 
`echo '{"cniVersion":"0.4.0","type":"sriov","deviceID":"0000:03:00.0","master":"ens160f0","pfOnly":true,"ipam":{"ty":"fixipam","subnet":"192.168.2.0/26","routes":[{"dst": "0.0.0.0/0" }],"gateway": "192.168.2.1"}}'|CNI_COMMAND=ADD CNI_CONTAINERID=6b586b4912ee CNI_NETNS=/var/run/netns/6b586b4912ee CNI_PATH=/opt/cni/bin CNI_IFNAME=net1 dlv debug  --headless=true --listen=:2345 --log --api-version=2`
The command is a little long.

**Comment by suzmue** [comment]
Hi @wkdzzb, could you describe the issue that you are experiencing a bit? What did you expect to happen and what actually happened? Thank you!
