### ISSUE TITLE
Digits in a number literal not displayed correctly

### ISSUE THREAD

**Issue by paoloteti** [golang/vscode-go#636]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.15.2 windows/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.49.0 e790b931385d72cf5669fcefc51cdf65990efa5d x64`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `v0.16.2`
- Run `go env` to get the go development environment details
	- Not relevant for this issue

### Share the Go related settings you have added/edited

Default settings

### Describe the bug

If digits in a number literal are separated by underscores only the first digit is displayed.

Number should be displayed including with digits separated by underscores.

### Steps to reproduce the behavior:
1. Type the following piece of code
```
const (
	// FOO bla bla bla
	FOO = 10
	// BAR bla bla bla
	BAR = 1_000
)
```
2. Move mouse pointer over the `BAR` constant
3. BAR is diplayed as `const BAR int = 1` instead of  `const BAR int = 1_000`

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![immagine](https://user-images.githubusercontent.com/35451649/93086907-1ec65e00-f698-11ea-9cfd-e425096e267c.png)

**Comment by suzmue** [comment]
I can recreate this issue in a project in the GOPATH with useLanguageServer=false, so the bug appears to be in the extension's implementation of the hover feature.

**Comment by suzmue** [comment]
Thanks for filing this issue, @paoloteti!

This hover is provided by the [godef](https://github.com/rogpeppe/godef) tool which we do not plan to maintain as we are moving towards using the language server. You can use the language server by setting useLanguageServer=true in the extension settings. This issue is already fixed in the language server!

**Comment by paoloteti** [comment]
@suzmue Thanks for the feedback. Switching to `gopls` fixed the issue.
