### ISSUE TITLE
performance: slow file save & autocompletion on Windows

### ISSUE THREAD

**Issue by itsgitz** [golang/vscode-go#638]
- Issue Type: `Bug`
- Extension Name: `go`
- Extension Version: `0.16.2`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.0`

My VS Code is running slowly while using Go extension in Windows 10. This was faster when using VS Code in Linux Ubuntu.

**Comment by hyangah** [comment]
@itsgitz Can you please describe the issue you are experiencing?

**Comment by itsgitz** [comment]
My VS Code is running slowly while using Go extension in Windows 10. This was faster when using VS Code in Linux Ubuntu.
The VS Code performance is slow even when I'm saving the file and the code suggestion is too slow.

![image](https://user-images.githubusercontent.com/20938898/93110706-e2b6eb80-f6df-11ea-8fce-b46792ded0a9.png)

**Comment by hyangah** [comment]
@itsgitz thanks for clarifying the issue. It would be super helpful if you can capture the profile  (instruction https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load) and share your vscode settings.

**Comment by itsgitz** [comment]
Thank you very much for your help! I've read the explanation. I tried to restart the VS Code then disable some extensions which I'm not using. And now there's no performance issues in VS Code, especially for autocompletion.

![image](https://user-images.githubusercontent.com/20938898/93168751-d1a4c380-f74d-11ea-8707-63a23b118730.png)

**Comment by hyangah** [comment]
@itsgitz thanks a lot for the update and figuring out the fix on your own. Will close this issue.

Do you mind sharing what extensions (One Dark Pro?) caused a trouble in particular, or whether it's just the general cpu exhaustion issue - too many extensions fighting for the scarce cpu?

**Comment by itsgitz** [comment]
Yes, I do. One Dark Pro is the color theme extension for my VS Code. Sometimes it takes longer time for startup activation. So, I decided to disable it for a while.

**Comment by itsgitz** [comment]
Hey! This extension is run faster after I enabled the `Go: Use Language Server` (set it to true) and install `gopls`. I thought `gopls` was installed along with `vscode-go`.

**Comment by hyangah** [comment]
Good to hear that. (cc @stamblerre and gopls contributors are actively working on it!) All tools this extension use have to be installed separately. When you enable the language server, but the binary is not found, the extension prompts users to install the tools. Also there is a command `Go: Install/Update Tools` to help the installation process.
