### ISSUE TITLE
Value hint dialog with bogus value

### ISSUE THREAD

**Issue by carvalhais** [golang/vscode-go#639]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
`go version go1.15 linux/amd64`

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
```
1.49.0
e790b931385d72cf5669fcefc51cdf65990efa5d
x64
```
- Check your installed extensions to get the version of the VS Code Go extension 
`0.16.2`

- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/carvalhais/.cache/go-build"
GOENV="/home/carvalhais/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/carvalhais/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/carvalhais/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build195558366=/tmp/go-bu
ild -gno-record-gcc-switches"
```

### Share the Go related settings you have added/edited
None.

### Describe the bug
The hint dialog that shows up when you hover you mouse over a const name shows up the wrong value. Compiling the code and printing the values with `fmt.Printf()` does show up the expected value though, which suggests this might be an extension problem.

### Steps to reproduce the behavior:
1. Download sources from https://github.com/adonovan/gopl.io/
2. Open the source file at ch3/surface/main.go
3. Hover you mouse over `const height`
4. See wrong value

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/5495377/93136886-0c0d5280-f6b3-11ea-99c1-9db394db6ad7.png)

**Comment by stamblerre** [comment]
What are your VS Code Go settings? You can find them by opening the Command Palette (Ctrl + Shift + P) and selecting "Preferences: Open Settings (JSON). Are you using the language server?

**Comment by carvalhais** [comment]
Hi Rebecca,
All my vscode-go settings are at their defaults, hence my settings.json files have no options related to the extension at all. Her's te entire content of my settings.json file:
```
{
    "remote.SSH.remotePlatform": {
        "172.16.32.12": "linux",
        "niagara": "linux"
    }
}
```

I'm using the Remote SSH extension, running the server instance with a default Go installation. I also search on the web, and believe that I would have to have done further configuration to get a language server working, which I didn't. So I don't believe I have a language server running.

**Comment by stamblerre** [comment]
Thanks for clarifying! Without the language server, this hover is provided by the godef tool which we do not plan to maintain as we are moving towards using the language server, which doesn't have this issue. You can use the language server by setting `"go.useLanguageServer": true` in the extension settings.

**Comment by carvalhais** [comment]
Hi Rebecca, I have done according to your instructions, and can confirm now the hint is displaying the correct value. Thanks very much for you kind help and advice.
