### ISSUE TITLE
debug: nicer display of panics while debugging

### ISSUE THREAD

**Issue by segevfiner** [golang/vscode-go#644]
**Is your feature request related to a problem? Please describe.**
Panics currently just break on the internal `fatalpanic` function and don't display as nicely as in some other language debuggers.

**Describe the solution you'd like**
I would like panics to stop on the actual that triggered the panic rather than the implementation of panic itself and display nicely like the Python extension displays uncaught exceptions:
<img width="666" alt="Screenshot of Python uncaught exception" src="https://user-images.githubusercontent.com/24731903/93236758-e00fd100-f787-11ea-923d-c7c7d736dfae.png">

**Comment by polinasok** [comment]
vscode-go provides a graphical interface over what the underlying delve debugger does,  which in turn is based on what the runtime does. We cannot stop at a line that causes the panic before we know it is an unrecovered panic, which comes with a set of extra stack frames. The stack frame that corresponds to the user's code that caused all this is buried a couple of levels down. If clicked to expand, it will show the code location and variables. I do not know of a way to force the editor to expand that stack frame by default. The only way around this that comes to mind is a hack that would artificially hide the top panic-related frames and return the stacktrace to the editor starting from the user frame.

We have looked into displaying richer error messages in the past, but were not able to get this working with just the options in StoppedEvent (see https://github.com/microsoft/vscode/issues/104475). ExceptionInfo request would be the next option to look into.

**Comment by polinasok** [comment]
If we were to implement a way to provide more detailed messages, we should do this for panic, fatal throw and runtime errors like bad access.

**Comment by suzmue** [comment]
Improved handling of panics is available using the `dlv-dap` debug adapter.

<img width="1114" alt="Screen Shot 2021-06-07 at 5 48 58 PM" src="https://user-images.githubusercontent.com/6634754/121091849-a620a800-c7b8-11eb-968c-d67e6fb65c16.png">

@segevfiner Could you try this by setting `"debugAdapter": "dlv-dap"` in your launch configuration and let us know if this seems sufficient to resolve this issue?

There is also a pending PR to deemphasize the runtime frames (https://github.com/go-delve/delve/pull/2522): 

<img width="1163" alt="Screen Shot 2021-06-07 at 5 49 52 PM" src="https://user-images.githubusercontent.com/6634754/121091934-c5b7d080-c7b8-11eb-927a-c280e1bdd26b.png">

**Comment by suzmue** [comment]
I'm going to close this as completed in delve dap. If you have further feature requests or bugs related to panics while debugging, please open another issue!
