### ISSUE TITLE
debug: make it easier to display long strings while debugging

### ISSUE THREAD

**Issue by segevfiner** [golang/vscode-go#645]
**Is your feature request related to a problem? Please describe.**
delve trims strings to 64 characters by default. Very very often I have to jump through hoops around this to be able to see the string I need to figure out what went wrong. The current ways to work with this leave something to be desired.

I can index the string, each time with a larger offset to try and see the next part of the string, though that's obviously rather inconvenient.

The limit is settable via the launch configuration (I don't know if delve reads any config file when launched via VS Code?), or by the `go.delveConfig` configuration value. Increasing it makes it more convenient yet I'm not sure of the performance implications or why the limit is so low to begin with. Also the limit cannot be set while already debugging, which is annoying.

**Describe the solution you'd like**
This might need a better default, a way to set it while debugging, and/or a better way to see the whole string even with the current default, for example having a button/link next to a trimmed string that allows to view the rest of it (Not sure if that is possible with the DAP)

**Describe alternatives you've considered**
Just set the configuration (Possibly making it easier for new users to discover it). Keep jumping through hoops with indexing.

**Additional context**
<img width="1792" alt="Screenshot" src="https://user-images.githubusercontent.com/24731903/93238946-cae87180-f78a-11ea-9bad-798112a2a153.png">
Argh...

**Comment by hyangah** [comment]
Longer string limit is not ideal for the variables UI that pulls all the variables in scope automatically.
If there are huge strings or bytes arrays, that will slow down debugging significantly.

I wonder if we can use a different limit for the requests that come through the DEBUG CONSOLE, and make it even dynamically configurable. 

cc @polinasok @suzmue @quoctruong

**Comment by emil14** [comment]
This one should not be closed because it's a real problem

Instead it would be great if you will provide settings to control this behaviour

**Comment by arxeiss** [comment]
@emil14 there is a setting to control this. Add those lines into JSON settings of VS Code.

```
    "go.delveConfig": {
        "dlvLoadConfig": {
            "maxStringLen": 5000,
            "maxArrayValues": 1000,
        },
    },
```

**Comment by emil14** [comment]
@arxeiss 

Thank you much!

**Comment by polinasok** [comment]
These setting are only available in the legacy adapter and are not available in dlv-dap. Please see the discussion at https://github.com/go-delve/delve/pull/2144.
We will be looking into ways to load these on demand.

**Comment by polinasok** [comment]
This is a dup of #1318. As the other issue has more discussion now, I am going to close this in favor of it.
