### ISSUE TITLE
debug: "Paused on breakpoint" is shown when program stops on panic

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#648]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.2 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.48.2
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.16.2
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/suzmue/Library/Caches/go-build"
GOENV="/Users/suzmue/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/suzmue/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/suzmue/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/2x/hlwbwjzd1vd4brlfs80676fw00fkl_/T/go-build758570292=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited
None 

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug
When running a program that panics with no breakpoints, the debugger stops at the panic and displays "Paused on breakpoint" in the UI. I would expect it to say "Paused on exception" to indicate why it was paused since I did not set any breakpoints, but delve did.

Delve sets its own breakpoints in order to catch the panics that do not recover. 	
```
	// UnrecoveredPanic is the name given to the unrecovered panic breakpoint.
	UnrecoveredPanic = "unrecovered-panic"

	// FatalThrow is the name given to the breakpoint triggered when the target
	// process dies because of a fatal runtime error.
	FatalThrow = "runtime-fatal-throw"

	unrecoveredPanicID = -1
	fatalThrowID       = -2

```

We can probably check for the breakpoint names and/or ids to display the correct information in the UI.

### Steps to reproduce the behavior:
Create a simple Go program with a panic:
```
package main

func main() {
	panic("hello")
}
```

Launch the debugger with the following config:
```
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Launch Package",
        "type": "go",
        "request": "launch",
        "mode": "debug",
        "program": "${workspaceFolder}",
      }
    ]
  }
```
Inspect the stack trace:
<img width="466" alt="Screen Shot 2020-09-15 at 1 53 43 PM" src="https://user-images.githubusercontent.com/6634754/93247352-3109d000-f75c-11ea-856e-50033cf435e0.png">
<img width="1012" alt="Screen Shot 2020-09-15 at 2 03 52 PM" src="https://user-images.githubusercontent.com/6634754/93247449-4f6fcb80-f75c-11ea-8da4-c2a5773bc884.png">

cc @polinasok @hyangah

**Comment by polinasok** [comment]
It can say "paused on panic" if we want to. We are free to supply whatever reason we want and don't have to rely on standard ones that might or might not make sense for Go. I have seen this before, and while not completely accurate, it did not seem like a big problem because everything else indicated that it is a panic. But since we are touching this code anyway, this could be a good time to clean this up.

**Comment by polinasok** [comment]
We will need to make a matching change & tests for this in dlv-dap as well:
https://github.com/go-delve/delve/blob/84328ed8703eb493072899d418ab04a4b37759e5/service/dap/server.go#L1158

**Comment by polinasok** [comment]
For completeness of records: this was also addressed in dlv dap in https://github.com/go-delve/delve/pull/2186. Thank you, @suzmue.
