### ISSUE TITLE
Support fill function

### ISSUE THREAD

**Issue by ysmood** [golang/vscode-go#653]
Currently, we only have `fill struct`. `fill function` is similar to it. For example:

```go
m := &sync.Map{}

m.Range(/* fill function here */)
```

After the fill:

```go
m.Range(func(key, value interface{}) bool {
	return false
})
```

**Comment by hyangah** [comment]
@ysmood Thanks for the feature request. Are you using the language server (`gopls`) already?
If not, please try that.

`gopls` provides a basic function type param suggestion already.
For example, if I trigger the auto suggestion (`editor.action.triggerSuggest`), the first candidate is the function type arg. 
![Screen Shot 2020-09-17 at 9 08 54 AM](https://user-images.githubusercontent.com/4999471/93474779-ce344800-f8c5-11ea-8c33-7f56a6102901.png)

If I select the first one, the code completes like the following.

```
	m.Range(func(key, value interface{}) bool {})
```

This doesn't do all of what you are requesting yet though - missing return statement. I thought gopls offers `fill return` codeaction but I couldn't trigger it yet. @stamblerre is this feature available?

**Comment by ysmood** [comment]
Thanks for your replay, can you help me to figure out why?

<img width="886" alt="Screen Shot 2020-09-17 at 22 23 38" src="https://user-images.githubusercontent.com/1415488/93476160-7123ab00-f934-11ea-8acc-27eec3dfd41b.png">

gopls version
golang.org/x/tools/gopls v0.5.0
    golang.org/x/tools/gopls@v0.5.0 h1:XEmO9RylgmaXp33iGrWfCGopVYDGBmLy+KmsIsfIo8Y=

vscode: Version: 1.49.0

<img width="1123" alt="Screen Shot 2020-09-17 at 22 23 57" src="https://user-images.githubusercontent.com/1415488/93476366-ac25de80-f934-11ea-895a-9bc099ece0f5.png">

**Comment by hyangah** [comment]
@ysmood looks like the gopls didn't seem to be working (the first one is from the snippet :-( ) 
Can you enable gopls trace to see why gopls is not returning completion candidates?

```
		"go.useLanguageServer": true,
		"go.languageServerFlags": ["-rpc.trace"],		
```

**Comment by ysmood** [comment]
Ah, figured it out. Seems like if you type `func` it won't auto-suggest the `fill function`, you have to trigger it with `Trigger Suggest` command.

But I think it will be more intuitive to filter commands by typing the prefix:

![bug](https://user-images.githubusercontent.com/1415488/93477531-1b500280-f936-11ea-802b-0450da6c8a1c.gif)

**Comment by ysmood** [comment]
Can I say it's a bug?

**Comment by hyangah** [comment]
I think https://github.com/golang/vscode-go/issues/49

**Comment by ysmood** [comment]
Thanks, then I'm closing this one.
