### ISSUE TITLE
Autocompletion: "invalid type" with go modules import

### ISSUE THREAD

**Issue by quentinlesceller** [golang/vscode-go#661]
Did a clean reinstall of vscode this morning and got an issues where the autocomplete does not work with go modules import.

Example:

```go
package main

import (
	"fmt"
	"log"

	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, err := ethclient.Dial("test")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(client)
}
```

give me this error when writing:
<img width="1272" alt="Capture d’écran 2020-09-18 à 13 06 45" src="https://user-images.githubusercontent.com/11842328/93626196-12504700-f9b1-11ea-9c47-7bf4b81d2aa6.png">

When running gocode as debug I get this error:
```
2020/09/18 13:16:55 -------------------------------------------------------
2020/09/18 13:16:55 gbimporter: no package found for github.com/ethereum/go-ethereum/ethclient: can't find import: "github.com/ethereum/go-ethereum/ethclient"
2020/09/18 13:16:55 Elapsed duration: 6.901204ms
2020/09/18 13:16:55 Offset: 0
2020/09/18 13:16:55 Number of candidates found: 7
2020/09/18 13:16:55 Candidates are:
2020/09/18 13:16:55   func cap(v Type) int
2020/09/18 13:16:55   func close(c chan<- Type)
2020/09/18 13:16:55   func complex(real FloatType, imag FloatType) ComplexType
2020/09/18 13:16:55   func copy(dst []Type, src []Type) int
2020/09/18 13:16:55   type complex128 complex128
2020/09/18 13:16:55   type complex64 complex64
2020/09/18 13:16:55   var client invalid type
2020/09/18 13:16:55 =======================================================
```

but the package is there

**Comment by hyangah** [comment]
@quentinlesceller thanks for the report. If `go build` from the integrated terminal didn't fix the issue,

can you share your 
- vscode go settings
- the `go.mod` file in your workspace
- check `gomod-gocode` is installed
- output of `go env`  from the integrated terminal

And, if you are curious, the language server (`gopls`) is a new shiny thing. So, please consider to switch to use the language server. gocode is unmaintained.

**Comment by quentinlesceller** [comment]
@hyangah thank you very much for the answer. Switching to gopls fixed it! 🎆 
<img width="1122" alt="Capture d’écran 2020-09-18 à 13 51 52" src="https://user-images.githubusercontent.com/11842328/93629374-2fd3df80-f9b6-11ea-9680-b2f687e48a40.png">
For anyone with this issue please be sure to check this box.
Closing.
