### ISSUE TITLE
generated code warning shown only if comment on first line of file

### ISSUE THREAD

**Issue by butuzov** [golang/vscode-go#68]
This is a copy of the [vscode-go#3243](https://github.com/microsoft/vscode-go/issues/3243)

**Is your feature request related to a problem? Please describe.**
`vscode-go` only notice generated files with `// Code generated ... DO NOT EDIT` pattern at the first line.  There are actually two problems with this.

1. ~ `// Code generated ... DO NOT EDIT` described by `go help generate`  and in [https://golang.org/s/generatedcode](https://golang.org/s/generatedcode) is more *desirable* state than, actual fact. See Examples (`1`, `2`).  As of now people still put (sometimes) "different code generated message", except all of them have `DO NOT EDIT` marker.
2. Quoting Rob Pike `The text may appear anywhere in the file.`, not just on the first line (as it done now).

#### Examples
1.  some examples from `golang/go` 
```
find . -name "*.go" -exec cat "{}" \;  | grep -E "^// .*?DO NOT EDIT" | uniq -c | sort -nr 
...
155 // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT
 18 // Created by cgo -godefs - DO NOT EDIT
  5 // DO NOT EDIT
  1 // GENERATED BY make_perl_groups.pl; DO NOT EDIT.
```
2. Search for `go` files on a GitHub gives more examples of the same behavior

### Propose 
What community really follows is a `DO NOT EDIT` phrase in a comment. Can we also have this a trigger to show `This file seems to be generated. DO NOT EDIT.` error message?

### PR
This issue is followed by PR that implements described/desirable behavior.

**Comment by butuzov** [comment]
Hi @hyangah any updates (code review pls?)

**Comment by hyangah** [comment]
@butuzov Thanks a lot for working on the PR (cl/234359) to implement this feature. We are currently very close to enable `gopls` by default, and gopls already has this feature. As we wind down the dev work for the legacy code path, I am proposing to close this issue.

**Comment by butuzov** [comment]
Agree. Cheers!
