### ISSUE TITLE
Failed to run 'c:\go\bin\go.exe env: null

### ISSUE THREAD

**Issue by sridharchalimeti** [golang/vscode-go#682]
Hi,

When I start Visual Studio Code I am having following output and Go related syntax check is not working.

`Failed to run 'c:\go\bin\go.exe env: null
warning: GOPATH set to GOROOT (c:\go) has no effect
failed to run "c:\go\bin\go.exe version": stdout: go version go1.14.3 windows/amd64
, stderr: warning: GOPATH set to GOROOT (c:\go) has no effect

failed to run "c:\go\bin\go.exe version": stdout: go version go1.14.3 windows/amd64
, stderr: warning: GOPATH set to GOROOT (c:\go) has no effect`

Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- warning: GOPATH set to GOROOT (c:\go) has no effect
go version go1.14.3 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.49.1
58bb7b2331731bf72587010e943852e13e6fd3cf
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.17.0
- Run `go env` to get the go development environment details
	- `warning: GOPATH set to GOROOT (c:\go) has no effect
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Sridhar\AppData\Local\go-build
set GOENV=C:\Users\Sridhar\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=c:\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Go\src\management\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Sridhar\AppData\Local\Temp\go-build027168010=/tmp/go-build -gno-record-gcc-switches`

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

`{
    "[go]": {
    "breadcrumbs.showInterfaces": true,

        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    }    
}`

### Describe the bug
Failed to configure the project settings related to go due to c:\go\bin\go.exe env is giving null. But when run the same command in integrated terminal I am having output which I supplied above.

### Steps to reproduce the behavior:
1. Open Visual Code Studio where GO extension is already installed
2. Open any Golang project
3. See  following error
`Failed to run 'c:\go\bin\go.exe env: null
warning: GOPATH set to GOROOT (c:\go) has no effect
failed to run "c:\go\bin\go.exe version": stdout: go version go1.14.3 windows/amd64
, stderr: warning: GOPATH set to GOROOT (c:\go) has no effect

failed to run "c:\go\bin\go.exe version": stdout: go version go1.14.3 windows/amd64
, stderr: warning: GOPATH set to GOROOT (c:\go) has no effect`

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/25439010/94120544-26c88f80-fe48-11ea-94b6-79e26e6d1fe9.png)

**Comment by hyangah** [comment]
@sridharchalimeti thanks for the report.

Using the same directory for `GOPATH` and `GOROOT` is not recommended. Please change `GOPATH` to be something else. See this instruction https://github.com/golang/go/wiki/SettingGOPATH#windows

Probably, this condition can be relaxed and the extension tries to continue parsing of `stdout` in the presence of `stderr`.
The extension is currently very strict about the correct execution of `go env`. 
https://github.com/golang/vscode-go/blob/9d97bb55f8bbaf2a49adcfd28912405a36ff8ffc/src/goInstallTools.ts#L358
