### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by hhq163** [golang/vscode-go#687]
gopls version: v0.4.1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

I see a tip:
The gopls server failed to initialize. Would you like to report a gopls issue on GitHub? You will be asked to provide additional information and logs, so PLEASE READ THE CONTENT IN YOUR BROWSER

and function jump is not nomal in my go program.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version (the latest version is v0.5.0)? You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by hhq163** [comment]
thank you , I solve this problem after update gopls to V0.5.0

**Comment by stamblerre** [comment]
Glad to hear it! I'll close this issue then.
