### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by broady** [golang/vscode-go#695]
gopls version: v0.4.2

```
[Error - 2:51:52 PM] Starting client failed
  Message: unsupported URI scheme:  (gopls only supports file URIs)
  Code: 0
```

I launched code from my terminal running WSL2:

```
code main.go
```

When I open it as part of the project/module, gopls works fine:
```
code .
code main.go
```

I don't what scheme it was trying to send, I'm guessing it's blank? (In any case, might want to update the log message to use %q just so that's clearer.)

**Comment by stamblerre** [comment]
The latest version of `gopls` is v0.5.0, so please update to the latest - you can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools". Do you still see the same error?
