### ISSUE TITLE
"Go to interface" command

### ISSUE THREAD

**Issue by emil14** [golang/vscode-go#698]
Can we have a `go to interface` command? Maybe `Go to type definition` should do it?

I understand that one type's method could implement multiple interfaces but there should be an easy way to go to that interface from implementation. It will also great to have an ability to see all the interfaces that some implementation satisfies (if there are multiple of them)

**Comment by hyangah** [comment]
@emil14 Is it different from how `Find All Implementations` context menu on a concrete type works now when gopls is enabled? (`"go.useLanguageServer": true`)

![image](https://user-images.githubusercontent.com/4999471/94575311-1ba7a200-0242-11eb-8ca6-46084340221d.png)

https://github.com/golang/go/issues/35550

I admit `Find All Implementations` was not the first thing that came into my mind. It behaves differently when it runs against an interface and when it runs against a concrete type, which is not very intuitive.

**Comment by emil14** [comment]
Okay, got it
