### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by minhluuquang** [golang/vscode-go#704]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 77 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0x1ac8300, 0xc000432390, 0x0, 0x199a7ab, 0x7, 0xc000414f28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1adc3c0, 0xc000362580, 0x1ac8300, 0xc000432390, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0001d5a40, 0x1adc3c0, 0xc000362580, 0xc000408000, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0001d5a40, 0x1adc3c0, 0xc000362580, 0xc000408000, 0xc000408000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1adc3c0, 0xc000362580, 0x1af02c0, 0xc0001d5a40, 0xc0004063c0, 0x1adc600, 0xc000362500, 0x0, 0x1ac9c40, 0xc0003d00b0)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1adc3c0, 0xc000362580, 0xc0004063c0, 0x1adc600, 0xc000362500, 0x432346b, 0x1f34aa0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1adc3c0, 0xc000362580, 0xc0004063c0, 0x1adc600, 0xc000362500, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1adc3c0, 0xc000362580, 0xc0003537e0, 0x1adc600, 0xc000362500, 0x0, 0x0)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003cea0, 0xc00035f260, 0xc0003548c0, 0x1adc3c0, 0xc000362580, 0xc0003537e0, 0x1adc600, 0xc000362500)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 12:09:30 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@hodtien: Looks like your `go` binary is not on your `$PATH`. You can check where `go` is installed on your machine by running `Go: Locate Go Tools` from the Command Palette (Ctrl+Shift+P). Then, please add it to your `$PATH`.

**Comment by minhluuquang** [comment]
@stamblerre my GOBIN is undefined in vscode but it have a value in when I run `go env` in terminal

**Comment by minhluuquang** [comment]
@stamblerre interesting that the problem disappears when I start vscode from terminal
