### ISSUE TITLE
gopls and tools fail to find 'go' after upgrade to v0.17.1

### ISSUE THREAD

**Issue by aswin-cm** [golang/vscode-go#707]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 86 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc0004831a0, 0x0, 0xd98f28, 0x7, 0xc00027cf28)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc00035c580, 0xec5e40, 0xc0004831a0, 0x1, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000360320, 0xed9d60, 0xc00035c580, 0xc00017ec00, 0x0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000360320, 0xed9d60, 0xc00035c580, 0xc00017ec00, 0xc00017ec00, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc00035c580, 0xeed8e0, 0xc000360320, 0xc00026d1d0, 0xed9fa0, 0xc00035c500, 0x0, 0xec7680, 0xc00017c9a0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc00035c580, 0xc00026d1d0, 0xed9fa0, 0xc00035c500, 0x1b84fb5, 0x132dce0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc00035c580, 0xc00026d1d0, 0xed9fa0, 0xc00035c500, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc00035c580, 0xc00034b020, 0xed9fa0, 0xc00035c500, 0x407fc5, 0xc00030e358)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00030e9c0, 0xc0003518c0, 0xc000305c90, 0xed9d60, 0xc00035c580, 0xc00034b020, 0xed9fa0, 0xc00035c500)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x173
[Info  - 5:55:36 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 89 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc000435350, 0x0, 0xd98f28, 0x7, 0xc00041ef28)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc0002b39c0, 0xec5e40, 0xc000435350, 0x1, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0002c8320, 0xed9d60, 0xc0002b39c0, 0xc000412000, 0x0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0002c8320, 0xed9d60, 0xc0002b39c0, 0xc000412000, 0xc000412000, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc0002b39c0, 0xeed8e0, 0xc0002c8320, 0xc000401380, 0xed9fa0, 0xc0002b3940, 0x0, 0xec7680, 0xc0003c60b0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc0002b39c0, 0xc000401380, 0xed9fa0, 0xc0002b3940, 0x1f4cc71, 0x132dce0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc0002b39c0, 0xc000401380, 0xed9fa0, 0xc0002b3940, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc0002b39c0, 0xc0002b4be0, 0xed9fa0, 0xc0002b3940, 0x407fc5, 0xc00020e3b8)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000294ae0, 0xc0002e2540, 0xc000283780, 0xed9d60, 0xc0002b39c0, 0xc0002b4be0, 0xed9fa0, 0xc0002b3940)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x173
[Info  - 5:55:36 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 98 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc0003c8090, 0x0, 0xd98f28, 0x7, 0xc0003b0f28)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc00048a080, 0xec5e40, 0xc0003c8090, 0x1, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc00046e280, 0xed9d60, 0xc00048a080, 0xc0000e0c00, 0x0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc00046e280, 0xed9d60, 0xc00048a080, 0xc0000e0c00, 0xc0000e0c00, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc00048a080, 0xeed8e0, 0xc00046e280, 0xc0003a80c0, 0xed9fa0, 0xc00048a000, 0x0, 0xec7680, 0xc0000de840)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc00048a080, 0xc0003a80c0, 0xed9fa0, 0xc00048a000, 0x1a9c837, 0x132dce0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc00048a080, 0xc0003a80c0, 0xed9fa0, 0xc00048a000, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc00048a080, 0xc000460c60, 0xed9fa0, 0xc00048a000, 0x407fc5, 0xc00003e358)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00011ab40, 0xc0004635f0, 0xc000113eb0, 0xed9d60, 0xc00048a080, 0xc000460c60, 0xed9fa0, 0xc00048a000)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x173
[Info  - 5:55:36 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 76 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc000279380, 0x0, 0xd98f28, 0x7, 0xc000264f28)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc000402340, 0xec5e40, 0xc000279380, 0x1, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0001baf00, 0xed9d60, 0xc000402340, 0xc000250000, 0x0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0001baf00, 0xed9d60, 0xc000402340, 0xc000250000, 0xc000250000, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc000402340, 0xeed8e0, 0xc0001baf00, 0xc00024d3b0, 0xed9fa0, 0xc0004022c0, 0x0, 0xec7680, 0xc00024e000)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc000402340, 0xc00024d3b0, 0xed9fa0, 0xc0004022c0, 0x1467465, 0x132dce0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc000402340, 0xc00024d3b0, 0xed9fa0, 0xc0004022c0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc000402340, 0xc0001e93a0, 0xed9fa0, 0xc0004022c0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003ecc0, 0xc0001f9bc0, 0xc0001ddcf0, 0xed9d60, 0xc000402340, 0xc0001e93a0, 0xed9fa0, 0xc0004022c0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x173
[Info  - 5:55:36 pm] Connection to server got closed. Server will restart.
panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 44 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:58 +0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc0003c95f0, 0x0, 0xd98f28, 0x7, 0xc0003c0f28)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:69 +0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc00024a700, 0xec5e40, 0xc0003c95f0, 0x1, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/debug/info.go:52 +0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000252320, 0xed9d60, 0xc00024a700, 0xc0003b2000, 0x0, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/general.go:87 +0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000252320, 0xed9d60, 0xc00024a700, 0xc0003b2000, 0xc0003b2000, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/server_gen.go:108 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc00024a700, 0xeed8e0, 0xc000252320, 0xc00039f620, 0xed9fa0, 0xc00024a680, 0x0, 0xec7680, 0xc0003a8000)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/tsserver.go:235 +0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc00024a700, 0xc00039f620, 0xed9fa0, 0xc00024a680, 0x142a934, 0x132dce0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/protocol/protocol.go:63 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc00024a700, 0xc00039f620, 0xed9fa0, 0xc00024a680, 0x0, 0x0)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/lsp/lsprpc/lsprpc.go:557 +0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc00024a700, 0xc0002017a0, 0xed9fa0, 0xc00024a680, 0x407fc5, 0xc00003e2f8)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00020c600, 0xc000245530, 0xc000202cc0, 0xed9d60, 0xc00024a700, 0xc0002017a0, 0xed9fa0, 0xc00024a680)
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/aswin/go/pkg/mod/golang.org/x/tools@v0.0.0-20200914163123-ea50a3c84940/internal/jsonrpc2/handler.go:100 +0x173
[Error - 5:55:36 pm] Connection to server got closed. Server will not be restarted.

**Comment by hyangah** [comment]
@aswin-cm Thanks for the report. 
- What is the version of the Go extension? 
- Can you share the output of `Go: Locate Go Tools`? 
The crash was caused because gopls couldn't find 'go' from the given PATH environment. The `Go: Locate Go Tools` should show the PATH environment variable used by the gopls.

**Comment by aswin-cm** [comment]
Version of go extention is 0.17.1
This is the response for `Go: Locate Go Tools`

Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /home/aswin/go
GOROOT: /usr/local/go
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/aswin/go/bin:/home/aswin/go/bin

   gocode: /home/aswin/go/bin/gocode installed
   gopkgs: /home/aswin/go/bin/gopkgs installed
   go-outline: /home/aswin/go/bin/go-outline installed
   go-symbols: /home/aswin/go/bin/go-symbols installed
   guru: /home/aswin/go/bin/guru installed
   gorename: /home/aswin/go/bin/gorename installed
   gotests: /home/aswin/go/bin/gotests installed
   gomodifytags: /home/aswin/go/bin/gomodifytags installed
   impl: /home/aswin/go/bin/impl installed
   fillstruct: /home/aswin/go/bin/fillstruct installed
   goplay: /home/aswin/go/bin/goplay installed
   godoctor: /home/aswin/go/bin/godoctor installed
   dlv: /home/aswin/go/bin/dlv installed
   gocode-gomod: /home/aswin/go/bin/gocode-gomod installed
   godef: /home/aswin/go/bin/godef installed
   goimports: /home/aswin/go/bin/goimports installed
   golint: /home/aswin/go/bin/golint installed
   gopls: /home/aswin/go/bin/gopls installed

go env
Workspace Folder (go-basics): /home/aswin/go/src/github.com/aswinudhayakumar/go-basics
	GO111MODULE=""
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/aswin/.cache/go-build"
	GOENV="/home/aswin/.config/go/env"
	GOEXE=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/aswin/go/pkg/mod"
	GOOS="linux"
	GOPATH="/home/aswin/go"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GCCGO="gccgo"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="1"
	GOMOD=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build263585323=/tmp/go-build -gno-record-gcc-switches"

**Comment by hyangah** [comment]
Thanks @aswin-cm!

PATH the extension was launched with doesn't include `/usr/local/go/bin` - this is a regression caused by the fix for #679. 

You can try one of the followings for now:

Option 1) downgrade to 0.17.0 for now (Extension view -> select 'Go' extension -> click the gear icon -> install another version -> select 0.17.0), or

Option 2) add `"go.goroot": "/usr/local/go"` temporarily until 0.17.1 is out, or

Option 3) add `/usr/local/go/bin` to your `PATH` and relaunch code for linux/mac users. `C:\Go\bin` to `Path` for windows users.

I recommend the Option 3

**Comment by aswin-cm** [comment]
yeah, its finally working when I switched to `v0.17.0`, thanks! @hyangah
