### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by sunnyregion** [golang/vscode-go#710]
gopls version: v0.1.7
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.tagSupport of type bool
  Code: -32700 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@sunnyregion gopls v0.1.7 is pretty old. Can you please update the gopls to the latest one? 

* "Go: Install/Update Tools" -> select gopls
If the above does not work, go to your home directory and run the following command
`GO111MODULE=on go get golang.org/x/tools/gopls@latest`
