### ISSUE TITLE
gopls: report file change notifications for "gopls.mod"

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#712]
Right now, we only look at files with the name `go.mod`, but for multi-module workspace support, we also need file change notifications for the `gopls.mod` "configuration" file.

**Comment by hyangah** [comment]
I think these are the relevant code path: 

https://github.com/golang/vscode-go/blob/9bf9d642c76369144bc85323622240a121868454/src/goLanguageServer.ts#L223

https://github.com/golang/vscode-go/blob/9bf9d642c76369144bc85323622240a121868454/package.json#L110-L118
  (not sure why `go.mod` is configured in the extension property...)

**Comment by stamblerre** [comment]
We do think that the `workspace/didChangeWatchedFiles` should be enough for our current purposes, but it might be worth adding this support earlier rather than later in case we need overlays for the gopls.mod for whatever reason.
