### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by AaronReboot** [golang/vscode-go#715]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 104 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0x1ac8320, 0xc0003e8420, 0x0, 0x199a7c5, 0x7, 0xc0003d4f28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1adc3e0, 0xc000480380, 0x1ac8320, 0xc0003e8420, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0000c2460, 0x1adc3e0, 0xc000480380, 0xc0001f6c00, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0000c2460, 0x1adc3e0, 0xc000480380, 0xc0001f6c00, 0xc0001f6c00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1adc3e0, 0xc000480380, 0x1af02e0, 0xc0000c2460, 0xc0003ca450, 0x1adc620, 0xc000480300, 0x0, 0x1ac9c60, 0xc0001f46e0)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1adc3e0, 0xc000480380, 0xc0003ca450, 0x1adc620, 0xc000480300, 0x2f41b9b, 0x1f34aa0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1adc3e0, 0xc000480380, 0xc0003ca450, 0x1adc620, 0xc000480300, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1adc3e0, 0xc000480380, 0xc0000cff00, 0x1adc620, 0xc000480300, 0x1008325, 0xc00003c2f8)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000b6a80, 0xc0000f39b0, 0xc0000fe130, 0x1adc3e0, 0xc000480380, 0xc0000cff00, 0x1adc620, 0xc000480300)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 11:48:19 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>
![image](https://user-images.githubusercontent.com/14034112/94715442-72cd7580-031b-11eb-821b-cd10507c2e34.png)

**Comment by hyangah** [comment]
@AaronReboot thanks for the report. This issue is now tracked here in https://github.com/golang/vscode-go/issues/713

Either downgrade to 0.17.0 or try one of other options described in the bug. Sorry for the trouble.

**Comment by hyangah** [comment]
Please try https://github.com/golang/vscode-go/releases/tag/v0.17.2-rc.1 to see if it fixes the issue.
Or try one of the workarounds described in the issue.
