### ISSUE TITLE
Go to definition fails with godef - 'go list' driver requires 'go', but executable file not found in $PATH

### ISSUE THREAD

**Issue by Frug** [golang/vscode-go#717]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.9 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.49.2
e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.17.1
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tread/.cache/go-build"
GOENV="/home/me/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/me/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build893268772=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited
```
    "go.formatTool": "goimports",
    "go.gopath": "/home/me/go",
```

### Describe the bug
Right click > go to definition stopped working, and started saying "no definition found ..." on everything. It worked previously, I'm not aware of any changes I made that would have affected it.

This happened in both the latest go 1.15.2 and 1.14.9 after I tried downgrading.

Tracking it down in the extension logs shows
```
[2020-09-30 14:41:50.269] [exthost] [error] [golang.go] provider FAILED
[2020-09-30 14:41:50.269] [exthost] [error] Command failed: /home/me/go/bin/godef -t -i -f /home/me/go/mystuff/.../file.go -o 2208
godef: 'go list' driver requires 'go', but executable file not found in $PATH 
```

I was able to work around the issue by putting my full $PATH in vscode settings go.toolsEnvVars:
```
"go.toolsEnvVars": {
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/me/go/bin"
    },
```

### Steps to reproduce the behavior:
1. Don't have anything set for go.toolsEnvVars and a standard go setup using godef (not gopls) and a project that uses modules.
2. Right click on a function and pick go to definition
3. No definitions found, even if it compiles

**Comment by hyangah** [comment]
@Frug thanks for reporting the issue. This is a duplicate of #713. 
Please try  https://github.com/golang/vscode-go/releases/tag/v0.17.2-rc.1 
or try one of the workarounds described in the issue.

**Comment by saada** [comment]
Even with the nightly build, I'm still facing this issue.

**Comment by hyangah** [comment]
@saada The nightly build doesn't include the fix yet - today's nightly was built earlier than the fix.

**Comment by Frug** [comment]
> @Frug thanks for reporting the issue. This is a duplicate of #713.
> Please try https://github.com/golang/vscode-go/releases/tag/v0.17.2-rc.1
> or try one of the workarounds described in the issue.

Ah ok. I did my best to look for this issue by the error I was getting but couldn't find that one. Thanks for the quick reply, and the explanation of why this happens in the other issue. I'll close this and refer people there.
