### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by glavposhtamt** [golang/vscode-go#718]
gopls version: v0.4.4
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 102 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0xe9d780, 0xc0002f8180, 0x0, 0xd2bcb1, 0x7, 0xc0002def50)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xeb1540, 0xc00040af40, 0xe9d780, 0xc0002f8180, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000414280, 0xeb1540, 0xc00040af40, 0xc0002d0000, 0x0, 0x0, 0x0)
	  general.go:75  0x45f
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000414280, 0xeb1540, 0xc00040af40, 0xc0002d0000, 0xc0002d0000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xeb1540, 0xc00040af40, 0xecbd40, 0xc000414280, 0xc0002c6180, 0xeb1780, 0xc00040aec0, 0x0, 0x0, 0xe9efa0)
	  tsserver.go:235  0x485
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xeb1540, 0xc00040af40, 0xc0002c6180, 0xeb1780, 0xc00040aec0, 0xbfd55c51d7326d37, 0xe95be3)
	  protocol.go:62  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xeb1540, 0xc00040af40, 0xc0002c6180, 0xeb1780, 0xc00040aec0, 0x0, 0x0)
	  lsprpc.go:521  0x417
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xeb1540, 0xc00040af40, 0xc000406900, 0xeb1780, 0xc00040aec0, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00041e3c0, 0xc0004055f0, 0xc000400340, 0xeb1540, 0xc00040af40, 0xc000406900, 0xeb1780, 0xc00040aec0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 00:33:59] </pre>

**Comment by stamblerre** [comment]
@glavposhtamt: Please update your `gopls` version--the latest is v0.5.0. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
