### ISSUE TITLE
Frequent pop-up when saving with "Getting code actions: Go, Go, ..."

### ISSUE THREAD

**Issue by kotyara85** [golang/vscode-go#719]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.1 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
1.49.2
e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
0.17.1
- Run `go env` to get the go development environment details
```
GO111MODULE=""
GOARCH="amd64"
GOBIN="/Users/user/go/bin"
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/user/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/user/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yb/s_1qnvf57y1fw6d1wdp84m6jbgbh9s/T/go-build011190530=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Describe the bug
Description

rpc debug shows these - 

```
[Trace - 17:13:42.037 PM] Sending notification '$/cancelRequest'.
Params: {"id":286}


[Trace - 17:16:30.039 PM] Sending notification '$/cancelRequest'.
Params: {"id":287}
```

**Comment by hyangah** [comment]
@kotyara85 Thanks for the report. We need more details to figure out why gopls is slow. Is it possible to share the full logs (without confidential/private infos) - what happened before those `$/cancelRequest` events is more important.
