### ISSUE TITLE
Inline status of test

### ISSUE THREAD

**Issue by emil14** [golang/vscode-go#727]
It would be great to have inline status of the test, for example [here](https://github.com/jest-community/vscode-jest) it's implemented very well:
 
![Screenshot from 2020-10-01 16-09-06](https://user-images.githubusercontent.com/6453537/94813434-a8985a00-0400-11eb-808f-fd73d4df998a.png)

**Comment by hyangah** [comment]
@emil14 thanks for the feature request. Do you mean you want to see the test pass/fail status presented next to each Test* function?

**Comment by wrslatz** [comment]
I was looking for this feature today, actually.

Having the status of the test appear next to the test `func` would be helpful. It would also be helpful to highlight the error on the failed line itself.

**Comment by emil14** [comment]
@hyangah yep

**Comment by hyangah** [comment]
An idea for implementation

After test run:
 - Retrieve the test function names by processing the test `-json` output. ([relevant code](https://github.com/golang/vscode-go/blob/0aea0bfa77587ca63fd08c2a44b2bbbfe37eeb5f/src/testUtils.ts#L421)) A bit of parsing work may be necessary to handle subtests, skipped tests, etc.
 - Find the location of each test function in the active text document.
    One possibility is to utilize the `run test` CodeLens locations if gopls is enabled. (`textDocument/codeLens`)
    Another possibility is to utilize DocumentSymbol providers (LSP's `textDocument/documentSymbol` or the existing [GoDocumentSymbolProvider](https://github.com/golang/vscode-go/blob/0aea0bfa77587ca63fd08c2a44b2bbbfe37eeb5f/src/goOutline.ts#L198))
 - Then, apply text decoration ([`setDecorations`](https://code.visualstudio.com/api/references/vscode-api#TextEdit)).
 - This decoration should be disposed when test reruns. I expect this to be similar to the coverage feature ([`src/goCover.ts`](https://github.com/golang/vscode-go/blob/0aea0bfa77587ca63fd08c2a44b2bbbfe37eeb5f/src/goCover.ts)).

**Comment by wrslatz** [comment]
Potentially related  https://github.com/microsoft/vscode/issues/107467. Might drive implementation.

**Comment by hyangah** [comment]
v0.28.0 has Test API integration (done by @firelizzard18) and it comes with the inline status of test. 

![Screen Shot 2021-09-22 at 6 46 40 PM](https://user-images.githubusercontent.com/4999471/134431983-c533df9f-f5a4-412e-85a2-c2026d5dbada.png)
