### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by agustin-gonzalez** [golang/vscode-go#728]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 118 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0x1ac8320, 0xc0004c8960, 0x0, 0x199a7ab, 0x7, 0xc0004b4f28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1adc3e0, 0xc0003d42c0, 0x1ac8320, 0xc0004c8960, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0003d8280, 0x1adc3e0, 0xc0003d42c0, 0xc0000e8c00, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0003d8280, 0x1adc3e0, 0xc0003d42c0, 0xc0000e8c00, 0xc0000e8c00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1adc3e0, 0xc0003d42c0, 0x1af02e0, 0xc0003d8280, 0xc0004a0990, 0x1adc620, 0xc0003d4240, 0x0, 0x1ac9c60, 0xc0000e6840)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1adc3e0, 0xc0003d42c0, 0xc0004a0990, 0x1adc620, 0xc0003d4240, 0x3368788, 0x1f37aa0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1adc3e0, 0xc0003d42c0, 0xc0004a0990, 0x1adc620, 0xc0003d4240, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1adc3e0, 0xc0003d42c0, 0xc00022bf40, 0x1adc620, 0xc0003d4240, 0x1008345, 0xc000214838)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000214d20, 0xc0003e67b0, 0xc0003cc780, 0x1adc3e0, 0xc0003d42c0, 0xc00022bf40, 0x1adc620, 0xc0003d4240)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 11:11:59 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@agustin-gonzalez Thanks for the report. 
This is a regression caused by v0.17.1 release. We are currently preparing for the fix release. Please see #713 for workarounds.

**Comment by hyangah** [comment]
Please try v0.17.2 that's just released.
