### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by jonathansalfen** [golang/vscode-go#730]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 93 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0x1ad14c0, 0xc000374990, 0x0, 0x1956f38, 0x7, 0xc000368f18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1ae5520, 0xc000394ec0, 0x1ad14c0, 0xc000374990, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0003a2320, 0x1ae5520, 0xc000394ec0, 0xc000162c00, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0003a2320, 0x1ae5520, 0xc000394ec0, 0xc000162c00, 0xc000162c00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ae5520, 0xc000394ec0, 0x1b009c0, 0xc0003a2320, 0xc0003549c0, 0x1ae5760, 0xc000394e40, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ae5520, 0xc000394ec0, 0xc0003549c0, 0x1ae5760, 0xc000394e40, 0x0, 0xbfd59d0722c95d70)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ae5520, 0xc000394ec0, 0xc0003549c0, 0x1ae5760, 0xc000394e40, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ae5520, 0xc000394ec0, 0xc0000dbea0, 0x1ae5760, 0xc000394e40, 0x1007a9f, 0xc00003e5f8)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00009d0e0, 0xc000397a10, 0xc00038cba0, 0x1ae5520, 0xc000394ec0, 0xc0000dbea0, 0x1ae5760, 0xc000394e40)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 8:58:20 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@jonathansalfen: Thanks for the report.
This is a regression caused by v0.17.1 release. We are currently preparing for the fix release. Please see #713 for workarounds.
