### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by marcofloripa** [golang/vscode-go#731]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 98 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc000426a20, 0x0, 0xd98f28, 0x7, 0xc000410f28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc000480d40, 0xec5e40, 0xc000426a20, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0001baf00, 0xed9d60, 0xc000480d40, 0xc000404000, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0001baf00, 0xed9d60, 0xc000480d40, 0xc000404000, 0xc000404000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc000480d40, 0xeed8e0, 0xc0001baf00, 0xc0003fea50, 0xed9fa0, 0xc000480cc0, 0x0, 0xec7680, 0xc0003d40b0)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc000480d40, 0xc0003fea50, 0xed9fa0, 0xc000480cc0, 0xcb959c, 0x132dce0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc000480d40, 0xc0003fea50, 0xed9fa0, 0xc000480cc0, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc000480d40, 0xc0001f3520, 0xed9fa0, 0xc000480cc0, 0x407fc5, 0xc00003e9b8)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003efc0, 0xc0004833b0, 0xc000490020, 0xed9d60, 0xc000480d40, 0xc0001f3520, 0xed9fa0, 0xc000480cc0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 2:52:18 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@marcofloripa: Thanks for the report.
This is a regression caused by v0.17.1 release. We are currently preparing for the fix release. Please see #713 for workarounds.
