### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dobau** [golang/vscode-go#733]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

My notebook was in sleep mode, when "woke up" the vscode that was opened show me this message.

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 95 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0x1ad1ec0, 0xc0003ddb30, 0x0, 0x1957578, 0x7, 0xc0003d8f18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1ae5f20, 0xc000447f00, 0x1ad1ec0, 0xc0003ddb30, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc0000b1180, 0x1ae5f20, 0xc000447f00, 0xc0001fac00, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc0000b1180, 0x1ae5f20, 0xc000447f00, 0xc0001fac00, 0xc0001fac00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ae5f20, 0xc000447f00, 0x1b013c0, 0xc0000b1180, 0xc0003c1b60, 0x1ae6160, 0xc000447e80, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ae5f20, 0xc000447f00, 0xc0003c1b60, 0x1ae6160, 0xc000447e80, 0x0, 0xbfd5528e2c23d5d0)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ae5f20, 0xc000447f00, 0xc0003c1b60, 0x1ae6160, 0xc000447e80, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ae5f20, 0xc000447f00, 0xc000474280, 0x1ae6160, 0xc000447e80, 0x1007a9f, 0xc000292358)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00009cea0, 0xc00045ca80, 0xc00044a8a0, 0x1ae5f20, 0xc000447f00, 0xc000474280, 0x1ae6160, 0xc000447e80)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 3:47:20 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@dobau: Thanks for the report.
This is a regression caused by v0.17.1 release. The v0.17.2 release has the fix and is now available -- please update to this version.
