### ISSUE TITLE
gopls:  issue report (crash)

### ISSUE THREAD

**Issue by PabloSalvatierra2020** [golang/vscode-go#736]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 102 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x22e
golang.org/x/tools/internal/lsp/debug.section(0x1ad19a0, 0xc00043dc80, 0x0, 0x19572d8, 0x7, 0xc00043af18)
	  info.go:69  0x319
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0x1ae5a00, 0xc0003b4a80, 0x1ad19a0, 0xc00043dc80, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc00022ebe0, 0x1ae5a00, 0xc0003b4a80, 0xc00042c000, 0x0, 0x0, 0x0)
	  general.go:87  0x58b
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc00022ebe0, 0x1ae5a00, 0xc0003b4a80, 0xc00042c000, 0xc00042c000, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ae5a00, 0xc0003b4a80, 0x1b00ea0, 0xc00022ebe0, 0xc00041dcb0, 0x1ae5c40, 0xc0003b4a00, 0x0, 0x0, 0x0)
	  tsserver.go:235  0x4bb
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ae5a00, 0xc0003b4a80, 0xc00041dcb0, 0x1ae5c40, 0xc0003b4a00, 0x0, 0xbfd5eb514a5998e0)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ae5a00, 0xc0003b4a80, 0xc00041dcb0, 0x1ae5c40, 0xc0003b4a00, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ae5a00, 0xc0003b4a80, 0xc0003b8680, 0x1ae5c40, 0xc0003b4a00, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003d4a0, 0xc0003b12c0, 0xc00039d5b0, 0x1ae5a00, 0xc0003b4a80, 0xc0003b8680, 0x1ae5c40, 0xc0003b4a00)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 11:14:29 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by PabloSalvatierra2020** [comment]
check these errors please

**Comment by hyangah** [comment]
@PabloSalvatierra2020 This may be a regression in v0.17.1 (#713). Are you experiencing the same with the latest version of the extension (v0.17.2)?
