### ISSUE TITLE
goLanguageServer: prompt users to file an issue before opting out of it

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#738]
We are enabling gopls by default for Nightly users (golang/vscode-go#680).
Before enabling this for everyone, ask users to file an issue if they choose to opt out.

From @stamblerre's comment in https://go-review.googlesource.com/c/vscode-go/+/257959.
> we'll need to say that we're deprecating the old stuff and make it clear that they really shouldn't opt out (maybe file a bug if you can't use it? something like that).

**Comment by stamblerre** [comment]
As discussed today, when we enable the language server, we should pop up a web view with documentation, links to further information, and an option to opt-out.
