### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by mastodilu** [golang/vscode-go#742]
gopls version: null
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 
</pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@mastodilu thanks for the report - Can you please check whether you are using the latest version of gopls? 
- To check gopls version: run `gopls version` from your vscode integrated terminal. If it doesn't output any, your gopls version is too old .
- To upgrade gopls, use `Go: Install/Update Tools` command -> select 'gopls'. If that doesn't work, please run
   `GO111MODULE=on go get golang.org/x/tools/gopls@latest` from a directory where there is no `go.mod` (e.g. home directory)
The current latest version should be 0.5.x.

**Comment by stamblerre** [comment]
Based on that error message, it also sounds like you may be using an old version of the VS Code Go extension, so please make sure to update to the latest version of the extension as well.
