### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by korableg** [golang/vscode-go#744]
gopls version: v0.3.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: gopls does not yet support editing a single file. Please open a directory.
  Code: 0 
</pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@korableg: I know you closed this, but just wanted to let you know that the latest version of `gopls` is v0.5.0, so please make sure to update by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by korableg** [comment]
@stamblerre thank's
