### ISSUE TITLE
Docs wrong about hotkeys re: macOS

### ISSUE THREAD

**Issue by mcandre** [golang/vscode-go#755]
For macOS, the hotkeys are often Command-centered as opposed to Control-centered. Please update the documentation to make this more obvious, for each hotkey mentioned in the README.

**Comment by hyangah** [comment]
@mcandre Thanks for the report. Documentation needs a lot of help - here is the contribution guide https://github.com/golang/vscode-go/blob/master/docs/contributing.md#mail-your-change-for-review
Please send us PRs!

**Comment by hyangah** [comment]
We rewrote the documentation recently and made changes to include both hotkeys whenever necessary.
