### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by angelhvargas** [golang/vscode-go#760]
gopls version: v0.4.4
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: only file URIs are supported, got "vsls" from "vsls:/"

goroutine 103 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	  uri.go:32
golang.org/x/tools/internal/lsp/cache.(*View).setBuildInformation(0xc0000e8c00, 0x1ab1e40, 0xc0003e8e40, 0xc00020bce0, 0x6, 0xc0003f0000, 0x33, 0x33, 0x1, 0x198f6a8, ...)
	  view.go:814  0x5a4
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc0003ec1a0, 0x1ab1e40, 0xc0003e8e40, 0xc00020bcf0, 0xb, 0xc00020bce0, 0x6, 0x4000000000000000, 0x10101, 0xc00020bc40, ...)
	  session.go:163  0x4f7
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc0003ec1a0, 0x1ab1e40, 0xc0003e8e40, 0xc00020bcf0, 0xb, 0xc00020bce0, 0x6, 0x4000000000000000, 0x10101, 0xc00020bc40, ...)
	  session.go:113  0x12b
golang.org/x/tools/internal/lsp.(*Server).addView(0xc0003ea180, 0x1ab1e40, 0xc0003e8e40, 0xc00020bcf0, 0xb, 0xc00020bce0, 0x6, 0xc0003e6d00, 0xa, 0x10, ...)
	  workspace.go:41  0x1e4
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc0003ea180, 0x1ab1e40, 0xc0003e8e40, 0xc000216100, 0x1, 0x4, 0x0, 0x0)
	  general.go:206  0x220
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc0003ea180, 0x1ab1e40, 0xc0003e8e40, 0x204ac60, 0x0, 0x0)
	  general.go:157  0x3a5
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc0003ea180, 0x1ab1e40, 0xc0003e8e40, 0x204ac60, 0x204ac60, 0x0)
	  server_gen.go:112  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ab1e40, 0xc0003e8e40, 0x1acc8a0, 0xc0003ea180, 0xc000271290, 0x2765180, 0xc0003e8de0, 0x0, 0x0, 0x1a9f7c0)
	  tsserver.go:92  0x647
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ab1e40, 0xc0003e8e40, 0xc000271290, 0x2765180, 0xc0003e8de0, 0xbfd83501aaa88840, 0x2899d11)
	  protocol.go:62  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ab1e40, 0xc0003e8e40, 0xc000271290, 0x2765180, 0xc0003e8de0, 0x0, 0x0)
	  lsprpc.go:521  0x417
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ab1e40, 0xc0003e8e40, 0xc0003cbe20, 0x2765180, 0xc0003e8de0, 0x1007a9f, 0xc00011e178)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000392c0, 0xc0003e9260, 0xc0003dea20, 0x1ab1e40, 0xc0003e8e40, 0xc0003cbe20, 0x2765180, 0xc0003e8de0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 1:50:14 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@angelhvargas thanks for the report! 
Please update `gopls` by running 'Go: Install/Update Tools` -> select `gopls`,
Or, running the following command from the integrated command line
   `GO111MODULE=on go get golang.org/x/tools/gopls@latest`

The extension doesn't support vsls yet, but by updating gopls to the latest version, it will no longer crash.
