### ISSUE TITLE
 multi-line comment formatting error

### ISSUE THREAD

**Issue by ssqf** [golang/vscode-go#769]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	go version go1.15 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
1.50.0
93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	 0.17.2
- Run `go env` to get the go development environment details
set GO111MODULE=
set GOARCH=amd64
set GOBIN=E:\golang_project\bin
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env  
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=E:\golang_project\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\golang_project;C:\Users\Administrator\go;
set GOPRIVATE=
set GOPROXY=https://goproxy.cn
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=D:\appTools\mingw64\bin\x86_64-w64-mingw32-gcc.exe
set CXX=D:\appTools\mingw64\bin\x86_64-w64-mingw32-g++.exe
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build351191470=/tmp/go-build -gno-record-gcc-switches

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
    "go.useLanguageServer": true,
    "go.testTags": "",
    "go.addTags": {
        "tags": "json",
        "options": "json=omitempty",
        "promptForTags": false,
        "transform": "snakecase"
    },
    "go.gopath": "E:\\golang_project",
    "go.alternateTools": {
        "go-langserver": "gopls",
        "go": "go"
    },
    "go.languageServerExperimentalFeatures": {
        "format": true,
        "autoComplete": true,
        "diagnostics": true,
        "goToDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "goToTypeDefinition": true,
        "documentSymbols": true,
    },
    "go.autocompleteUnimportedPackages": true,
    "go.buildOnSave": "off",
    "[go]": {

        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "go.formatTool": "gofmt"

### Steps to reproduce the behavior:
gofmt，goimports，goreturns all the same
![](http://image.ssqf.site/bug.gif)

**Comment by hyangah** [comment]
@ssqf thanks for the report. When the language server is enabled, the language server is used as a formatter, so `go.formatTool` is not relevant.

- Can you please update your settings based on the recommendation in  https://github.com/golang/tools/blob/master/gopls/doc/vscode.md ?
  - Most attributes in your `go.languageServerExperimentalFeatures` are invalid.
  - `go.alternateTools` doesn't seem necessary (`go-langserver` is no longer used and `gopls` is the default).

- Make sure you are using the latest `gopls` version (v0.5.1): `Go: Install/Update Tools` from the command palette and check `E:\golang_project\bin\gopls.exe version`.

**Comment by stamblerre** [comment]
This looks like https://github.com/golang/go/issues/41128, which should be fixed with the latest version of `gopls`, so please do update to the latest version.

**Comment by stamblerre** [comment]
There hasn't been any activity on this issue for a few months, so going to close this.
@ssqf: Please open a new issue if you encounter this problem again.
