### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by SO-BEBOP** [golang/vscode-go#770]
gopls version: v0.3.2
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@SO-BEBOP Please update your `gopls`. The latest version is v0.5.1.

Command Palette (Cmd+Shift+P or Ctrl+Shift+P) -> 'Go: Install/Update Tools' -> choose 'gopls'.
