### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by frankful** [golang/vscode-go#773]
gopls version: v0.5.1
gopls flags: -remote=aut -logfile=auto -debug=:0 -rpc.trace

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version (the latest is v0.5.1)? You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by hyangah** [comment]
@frankful Please check the error message printed out in `Output` -> `gopls (server)` channel. 
It looks like the value you pass for `-remote` flag is invalid. 

@stamblerre Crash when the -remote flag value is invalid, is not very visible (just one line :-). Can we make it more visually standing out?

**Comment by stamblerre** [comment]
> @stamblerre Crash when the -remote flag value is invalid, is not very visible (just one line :-). Can we make it more visually standing out?

Sure, let me transfer this to the `gopls` issue tracker.
