### ISSUE TITLE
Failed to run go.exe: Error: spawn go.exe ENOENT, but the file does exist

### ISSUE THREAD

**Issue by leep-frog** [golang/vscode-go#774]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.15.2 windows/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders

```
1.50.0
93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
x64
```

- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.17.2
- Run `go env` to get the go development environment details

```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gleep\AppData\Local\go-build
set GOENV=C:\Users\gleep\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\gleep\Desktop\Coding\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gleep\Desktop\Coding\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\gleep\Desktop\Coding\go\src\clis\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\gleep\AppData\Local\Temp\go-build398277210=/tmp/go-build -gno-record-gcc-switches
```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

### Describe the bug

When starting up VS Code, I get the following errors in the "Output" tab:

```
Failed to run 'C:\Go\bin\go.exe env: Error: spawn C:\Go\bin\go.exe ENOENT
failed to run "C:\Go\bin\go.exe version": Error: spawn C:\Go\bin\go.exe ENOENT
```

I also get a vs code notification with the message:

```
Failed to run 'C:\Go\bin\go.exe env. The config change may not be applied correctly
```

Because of these errors (I'm assuming), the Go extension isn't working--no linting, completion suggestions, etc.

The path in question (`C:\Go\bin\go.exe`) also exists (see attached image), so I'm not quite sure what's causing the issue.

### Steps to reproduce the behavior:
1. Start VS Code
2. See error

### Screenshots or recordings

![File exists image](https://user-images.githubusercontent.com/66687468/95790591-af9b5400-0cad-11eb-9c8b-e2828457fa3f.png)

**Comment by hyangah** [comment]
@leep-frog Are you running any antivirus programs that would prevent vscode/node.js program from running executables?
What happens if you run the command `C:\Go\bin\go.exe version` or `C:\Go\bin\go.exe env` from the integrated terminal of vscode?

**Comment by leep-frog** [comment]
McAfee is installed and running.

The commands execute successfully from the integrated terminal.

**Comment by leep-frog** [comment]
@hyangah any idea on how to resolve this?

**Comment by hyangah** [comment]
@leep-frog Thanks - another possibility is the cwd where the command starts from is invalid.

Can you please check if you see a bit more details with the latest version? The latest version of extension should be able to log the directory in the message. [[code](https://github.com/golang/vscode-go/blob/master/src/util.ts#L365)].

**Comment by funknapkin** [comment]
I'd like to drop in here because I had the same issue and the cwd information helped me find a solution. Hopefully this will help you as well. In my case, the error was:

> Failed to run 'C:\Go\bin\go.exe env' (cwd: C:\Users\misc\go\src\simplefileserver): Error: spawn C:\Go\bin\go.exe ENOENT

The folder src\simplefileserver is a folder that doesn't exist anymore, I moved it recently. However, I forgot to remove it from my workspace. Removing that folder from my workspace fixes the issue.

**Comment by hyangah** [comment]
Wonder if we shouldn't give up but keep trying with other folders in the workspace. 
Or, was it a bad decision to require `cwd` for `go version` or `go env`?

@pjweinb @suzmue

**Comment by leep-frog** [comment]
@funknapkin yup, the folder from the error message didn't exist.  Removing it from my workspace got everything to work!  Thanks for the help!
