### ISSUE TITLE
debug: Add Tests for Remote Debugging

### ISSUE THREAD

**Issue by quoctruong** [golang/vscode-go#779]
Currently, we don't have any tests for remote debugging in `goDebug.test.ts`. These tests should validate common scenarios where the debugger ran into problems before like:

1. Attach to a `dlv` headless instance and set a breakpoint.
2. Debug information returned when a breakpoint is hit.
3. Unsetting breakpoints work correctly.
4. Disconnecting closes the connection and changes the program to running state if it was halted.

**Comment by hyangah** [comment]
cc @suzmue
