### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by manfredchester** [golang/vscode-go#784]
gopls version: v0.4.4
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 下午3:19:55] 2020/10/14 15:19:55 Build info
----------
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c h1:jLQLIAedRoS9I2Py7l/ZAGGzUxLFsdg42JXEpS/a+ow=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.2 windows/amd64

[Info  - 下午3:19:55] 2020/10/14 15:19:55 go env for E:\manfredchester\src\cloudroom
(root E:\manfredchester\src\cloudroom)
(valid build configuration = true)
(build flags: [])
GOMODCACHE=
GOCACHE=C:\Users\zhenghao.xu\AppData\Local\go-build
GONOSUMDB=
GOINSECURE=
GOPATH=C:\Users\zhenghao.xu\go;D:\gitProject;E:\zhxu
GOPRIVATE=
GOPROXY=https://goproxy.io,direct
GOSUMDB=off
GO111MODULE=on
GOFLAGS=
GOMOD=E:\manfredchester\src\cloudroom\go.mod
GONOPROXY=
GOROOT=D:\go1.14.2

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xad6c94]

goroutine 92 [running]:
golang.org/x/tools/internal/lsp/mod.ExtractGoCommandError(0xea5000, 0xc000440090, 0xeb8f60, 0xc0000a1c00, 0xea8ec0, 0xc000222140, 0xe91fa0, 0xc00008c740, 0x0, 0x26, ...)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/mod/diagnostics.go:142 +0x7e4
golang.org/x/tools/internal/lsp.(*Server).handleFatalErrors(0xc000211200, 0xea5000, 0xc000440090, 0xeb8f60, 0xc0000a1c00, 0xe91fa0, 0xc00008c740, 0xe91fa0, 0xc00008c740, 0xc000440120)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:334 +0x1b3
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000211200, 0xea55c0, 0xc000052000, 0xeb8f60, 0xc0000a1c00, 0x0, 0x0, 0x0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:95 +0xb57
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc000211200, 0xeb8f60, 0xc0000a1c00)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:33 +0xdb
golang.org/x/tools/internal/lsp.(*Server).addFolders.func2(0xc000211200, 0xeb8f60, 0xc0000a1c00, 0xc000405ba0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:222 +0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:221 +0x8d5
[Info  - 下午3:19:55] Connection to server got closed. Server will restart.
[Info  - 下午3:19:55] 2020/10/14 15:19:55 Build info
----------
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c h1:jLQLIAedRoS9I2Py7l/ZAGGzUxLFsdg42JXEpS/a+ow=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.2 windows/amd64

[Info  - 下午3:19:55] 2020/10/14 15:19:55 go env for E:\manfredchester\src\cloudroom
(root E:\manfredchester\src\cloudroom)
(valid build configuration = true)
(build flags: [])
GOMODCACHE=
GONOSUMDB=
GONOPROXY=
GOSUMDB=off
GOMOD=E:\manfredchester\src\cloudroom\go.mod
GOROOT=D:\go1.14.2
GO111MODULE=on
GOFLAGS=
GOPATH=C:\Users\zhenghao.xu\go;D:\gitProject;E:\zhxu
GOPRIVATE=
GOPROXY=https://goproxy.io,direct
GOCACHE=C:\Users\zhenghao.xu\AppData\Local\go-build
GOINSECURE=

[Error - 下午3:19:55] 2020/10/14 15:19:55 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.832036439.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.

	snapshot=0
	directory=E:\manfredchester\src\cloudroom
	query=[./... builtin]
	packages=0

[Error - 下午3:19:55] 2020/10/14 15:19:55 initial workspace load failed: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.832036439.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
: packages.Load error

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xad6c94]

goroutine 116 [running]:
golang.org/x/tools/internal/lsp/mod.ExtractGoCommandError(0xea5000, 0xc0003dd650, 0xeb8f60, 0xc0003a0b00, 0xea8ec0, 0xc0001cea00, 0xe91fa0, 0xc000090300, 0x0, 0x26, ...)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/mod/diagnostics.go:142 +0x7e4
golang.org/x/tools/internal/lsp.(*Server).handleFatalErrors(0xc000315380, 0xea5000, 0xc0003dd650, 0xeb8f60, 0xc0003a0b00, 0xe91fa0, 0xc000090300, 0xe91fa0, 0xc000090300, 0xc0003dd6e0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:334 +0x1b3
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000315380, 0xea55c0, 0xc000052eb0, 0xeb8f60, 0xc0003a0b00, 0xc0000a3f00, 0x0, 0x0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:95 +0xb57
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc000315380, 0xeb8f60, 0xc0003a0b00)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:33 +0xdb
golang.org/x/tools/internal/lsp.(*Server).addFolders.func2(0xc000315380, 0xeb8f60, 0xc0003a0b00, 0xc000086f10)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:222 +0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:221 +0x8d5
[Info  - 下午3:19:55] Connection to server got closed. Server will restart.
[Info  - 下午3:19:56] 2020/10/14 15:19:56 Build info
----------
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c h1:jLQLIAedRoS9I2Py7l/ZAGGzUxLFsdg42JXEpS/a+ow=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.2 windows/amd64

[Info  - 下午3:19:56] 2020/10/14 15:19:56 go env for E:\manfredchester\src\cloudroom
(root E:\manfredchester\src\cloudroom)
(valid build configuration = true)
(build flags: [])
GOMODCACHE=
GONOPROXY=
GOROOT=D:\go1.14.2
GOINSECURE=
GOMOD=E:\manfredchester\src\cloudroom\go.mod
GONOSUMDB=
GOPRIVATE=
GOSUMDB=off
GO111MODULE=on
GOPATH=C:\Users\zhenghao.xu\go;D:\gitProject;E:\zhxu
GOCACHE=C:\Users\zhenghao.xu\AppData\Local\go-build
GOFLAGS=
GOPROXY=https://goproxy.io,direct

[Error - 下午3:19:56] 2020/10/14 15:19:56 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.574287255.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.

	snapshot=0
	directory=E:\manfredchester\src\cloudroom
	query=[./... builtin]
	packages=0

[Error - 下午3:19:56] 2020/10/14 15:19:56 initial workspace load failed: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.574287255.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
: packages.Load error

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xad6c94]

goroutine 114 [running]:
golang.org/x/tools/internal/lsp/mod.ExtractGoCommandError(0xea5000, 0xc000444330, 0xeb8f60, 0xc000294b00, 0xea8ec0, 0xc000296370, 0xe91fa0, 0xc00005ed00, 0x0, 0x26, ...)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/mod/diagnostics.go:142 +0x7e4
golang.org/x/tools/internal/lsp.(*Server).handleFatalErrors(0xc000095300, 0xea5000, 0xc000444330, 0xeb8f60, 0xc000294b00, 0xe91fa0, 0xc00005ed00, 0xe91fa0, 0xc00005ed00, 0xc0005423f0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:334 +0x1b3
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000095300, 0xea55c0, 0xc000202040, 0xeb8f60, 0xc000294b00, 0x0, 0x0, 0x0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:95 +0xb57
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc000095300, 0xeb8f60, 0xc000294b00)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:33 +0xdb
golang.org/x/tools/internal/lsp.(*Server).addFolders.func2(0xc000095300, 0xeb8f60, 0xc000294b00, 0xc000354c00)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:222 +0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:221 +0x8d5
[Info  - 下午3:19:56] Connection to server got closed. Server will restart.
[Info  - 下午3:19:56] 2020/10/14 15:19:56 Build info
----------
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c h1:jLQLIAedRoS9I2Py7l/ZAGGzUxLFsdg42JXEpS/a+ow=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.2 windows/amd64

[Info  - 下午3:19:56] 2020/10/14 15:19:56 go env for E:\manfredchester\src\cloudroom
(root E:\manfredchester\src\cloudroom)
(valid build configuration = true)
(build flags: [])
GOPATH=C:\Users\zhenghao.xu\go;D:\gitProject;E:\zhxu
GOPRIVATE=
GOROOT=D:\go1.14.2
GOMODCACHE=
GONOSUMDB=
GOPROXY=https://goproxy.io,direct
GOCACHE=C:\Users\zhenghao.xu\AppData\Local\go-build
GOFLAGS=
GOINSECURE=
GONOPROXY=
GOSUMDB=off
GO111MODULE=on
GOMOD=E:\manfredchester\src\cloudroom\go.mod

[Error - 下午3:19:56] 2020/10/14 15:19:56 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.342414307.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.

	snapshot=0
	directory=E:\manfredchester\src\cloudroom
	query=[./... builtin]
	packages=0

[Error - 下午3:19:56] 2020/10/14 15:19:56 initial workspace load failed: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.342414307.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
: packages.Load error

[Error - 下午3:19:56] 2020/10/14 15:19:56 warning: diagnose go.mod: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.342414307.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
: packages.Load error
	directory=E:\manfredchester\src\cloudroom

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xad6c94]

goroutine 104 [running]:
golang.org/x/tools/internal/lsp/mod.ExtractGoCommandError(0xea5000, 0xc000506030, 0xeb8f60, 0xc00028ac00, 0xea8ec0, 0xc0000d4780, 0xe91fa0, 0xc000206000, 0x0, 0x26, ...)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/mod/diagnostics.go:142 +0x7e4
golang.org/x/tools/internal/lsp.(*Server).handleFatalErrors(0xc000067380, 0xea5000, 0xc000506030, 0xeb8f60, 0xc00028ac00, 0xe91fa0, 0xc000206000, 0xe91fa0, 0xc000206000, 0xc0005060c0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:334 +0x1b3
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000067380, 0xea55c0, 0xc00018a030, 0xeb8f60, 0xc00028ac00, 0x0, 0x0, 0x0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:95 +0xb57
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc000067380, 0xeb8f60, 0xc00028ac00)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:33 +0xdb
golang.org/x/tools/internal/lsp.(*Server).addFolders.func2(0xc000067380, 0xeb8f60, 0xc00028ac00, 0xc000341840)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:222 +0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:221 +0x8d5
[Info  - 下午3:19:56] Connection to server got closed. Server will restart.
[Info  - 下午3:19:56] 2020/10/14 15:19:56 Build info
----------
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c h1:jLQLIAedRoS9I2Py7l/ZAGGzUxLFsdg42JXEpS/a+ow=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.2 windows/amd64

[Info  - 下午3:19:56] 2020/10/14 15:19:56 go env for E:\manfredchester\src\cloudroom
(root E:\manfredchester\src\cloudroom)
(valid build configuration = true)
(build flags: [])
GOPATH=C:\Users\zhenghao.xu\go;D:\gitProject;E:\zhxu
GOPROXY=https://goproxy.io,direct
GOSUMDB=off
GOINSECURE=
GONOPROXY=
GOMOD=E:\manfredchester\src\cloudroom\go.mod
GONOSUMDB=
GOCACHE=C:\Users\zhenghao.xu\AppData\Local\go-build
GOPRIVATE=
GOROOT=D:\go1.14.2
GO111MODULE=on
GOMODCACHE=
GOFLAGS=

[Error - 下午3:19:56] 2020/10/14 15:19:56 go/packages.Load: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.815187347.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.

	snapshot=0
	directory=E:\manfredchester\src\cloudroom
	query=[./... builtin]
	packages=0

[Error - 下午3:19:56] 2020/10/14 15:19:56 initial workspace load failed: go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -modfile=C:\Users\zhenghao.xu\AppData\Local\Temp\go.22f26e3105d1e564092019fb60256ee4bf77024b.815187347.mod -- ./... builtin]: exit status 1: go: cannot determine module path for source directory E:\manfredchester\src\cloudroom (outside GOPATH, module path must be specified)

Example usage:
	'go mod init example.com/m' to initialize a v0 or v1 module
	'go mod init example.com/m/v2' to initialize a v2 module

Run 'go help mod init' for more information.
: packages.Load error

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xad6c94]

goroutine 76 [running]:
golang.org/x/tools/internal/lsp/mod.ExtractGoCommandError(0xea5000, 0xc000376270, 0xeb8f60, 0xc000216980, 0xea8ec0, 0xc000062910, 0xe91fa0, 0xc000202100, 0x0, 0x41053e, ...)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/mod/diagnostics.go:142 +0x7e4
golang.org/x/tools/internal/lsp.(*Server).handleFatalErrors(0xc000216900, 0xea5000, 0xc000376270, 0xeb8f60, 0xc000216980, 0xe91fa0, 0xc000202100, 0xe91fa0, 0xc000202100, 0xc000376300)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:334 +0x1b3
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000216900, 0xea55c0, 0xc00043c070, 0xeb8f60, 0xc000216980, 0x0, 0x0, 0x0)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:95 +0xb57
golang.org/x/tools/internal/lsp.(*Server).diagnoseDetached(0xc000216900, 0xeb8f60, 0xc000216980)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/diagnostics.go:33 +0xdb
golang.org/x/tools/internal/lsp.(*Server).addFolders.func2(0xc000216900, 0xeb8f60, 0xc000216980, 0xc000285550)
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:222 +0x46
created by golang.org/x/tools/internal/lsp.(*Server).addFolders
	C:/Users/zhenghao.xu/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:221 +0x8d5
[Error - 下午3:19:56] Connection to server got closed. Server will not be restarted.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
I know you closed this, but can you please try updating your `gopls` version? The latest version is v0.5.1. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
