### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by alejo3094** [golang/vscode-go#786]
gopls version: v0.4.3
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: only file URIs are supported, got "gitlens" from "gitlens://bb5b268/home/alejandro/go/src/bitbucket.org/truora/scrap-services%3F{"path":"/home/alejandro/go/src/bitbucket.org/truora/scrap-services","ref":"bb5b26875005b6a05471ab052c9a21db8137500c","repoPath":"/home/alejandro/go/src/bitbucket.org/truora/scrap-services"}"

goroutine 103 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	  uri.go:32
golang.org/x/tools/internal/lsp/cache.(*View).setBuildInformation(0xc0004ca2c0, 0xe721a0, 0xc000484870, 0xc000264580, 0x14c, 0xc0003bc000, 0x55, 0x55, 0x1, 0xd59cd8, ...)
	  view.go:755  0x4ac
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc0003b6180, 0xe721a0, 0xc000484870, 0xc000422880, 0x18, 0xc000264580, 0x14c, 0x4000000000000000, 0x10101, 0xc000409ae0, ...)
	  session.go:160  0x4a7
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc0003b6180, 0xe721a0, 0xc000484870, 0xc000422880, 0x18, 0xc000264580, 0x14c, 0x4000000000000000, 0x10101, 0xc000409ae0, ...)
	  session.go:112  0x138
golang.org/x/tools/internal/lsp.(*Server).addView(0xc000392280, 0xe721a0, 0xc000484870, 0xc000422880, 0x18, 0xc000264580, 0x14c, 0xe846e0, 0xc00027cb00, 0xe852e0, ...)
	  workspace.go:41  0x1fe
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc000392280, 0xe721a0, 0xc000484870, 0xc000216c80, 0x2, 0x4, 0x0, 0x0)
	  general.go:207  0x22d
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc000392280, 0xe721a0, 0xc000484870, 0x13e79e0, 0x0, 0x0)
	  general.go:157  0x3b2
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000392280, 0xe721a0, 0xc000484870, 0x13e79e0, 0x13e79e0, 0x0)
	  server_gen.go:112  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xe721a0, 0xc000484870, 0xe8c4c0, 0xc000392280, 0xc000417f20, 0x7efdc44d14c8, 0xc000484810, 0x0, 0x0, 0xbfd9e7862c8e1599)
	  tsserver.go:92  0x647
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xe721a0, 0xc000484870, 0xc000417f20, 0x7efdc44d14c8, 0xc000484810, 0x0, 0x0)
	  protocol.go:62  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xe721a0, 0xc000484870, 0xc000417f20, 0x7efdc44d14c8, 0xc000484810, 0x0, 0x0)
	  lsprpc.go:509  0x40e
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xe721a0, 0xc000484870, 0xc00048e260, 0x7efdc44d14c8, 0xc000484810, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0003aa420, 0xc000484c90, 0xc0003843d0, 0xe721a0, 0xc000484870, 0xc00048e260, 0x7efdc44d14c8, 0xc000484810)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Info  - 11:26:01 AM] 2020/10/14 11:26:01 go env for /home/alejandro/go/src/bitbucket.org/truora/scrap-services
(valid build configuration = true)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/alejandro/.cache/go-build"
GOENV="/home/alejandro/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/alejandro/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/alejandro/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6439"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6439/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g  "
CGO_ENABLED="1"
GOMOD="/home/alejandro/go/src/bitbucket.org/truora/scrap-services/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build804920951=/tmp/go-build -gno-record-gcc-switches"

[Error - 11:26:01 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version (the latest is v0.5.1)? You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
