### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by perrito666** [golang/vscode-go#792]
gopls version: v0.4.1
gopls flags: 

Describe what you observed.

- gopls was running through visual studio code go plugin
- from an unrelated shell I ran a git merge from a reasonably divergent branch into the one currently open in vscode
- there were conflicts
- vscode informed me that this had crashed gopls.

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7054b9]

goroutine 121 [running]:
golang.org/x/tools/internal/imports.(*ModuleResolver).init(0xc00056e000, 0x0, 0x0)
	  mod.go:107  0xc69
golang.org/x/tools/internal/imports.(*ModuleResolver).ClearForNewMod(0xc00056e000)
	  mod.go:194  0xa2
golang.org/x/tools/internal/lsp/cache.(*view).RunProcessEnvFunc(0xc0000ef080, 0xe848c0, 0xc000442750, 0xc0001c8370, 0x0, 0x0)
	  view.go:303  0x33b
golang.org/x/tools/internal/lsp/source.AllImportsFixes(0xe848c0, 0xc000442750, 0xe978c0, 0xc00050a310, 0xe82980, 0xc000590720, 0xc0005fa300, 0x28, 0x0, 0x3, ...)
	  format.go:84  0x2bb
golang.org/x/tools/internal/lsp.(*Server).codeAction(0xc0001c7400, 0xe84800, 0xc0000f4b40, 0xc0001c0180, 0xc0001c0180, 0x0, 0x0, 0x0, 0xc0003ff080)
	  code_action.go:80  0x1250
golang.org/x/tools/internal/lsp.(*Server).CodeAction(0xc0001c7400, 0xe84800, 0xc0000f4b40, 0xc0001c0180, 0xc0001c0180, 0x0, 0x0, 0x8785d1f, 0x13c2660)
	  server_gen.go:12  0x4d
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xe84800, 0xc0000f4b40, 0xc0002ef8c0, 0xe84a40, 0xc0000f49c0, 0x0, 0x0)
	  tsserver.go:295  0x281f
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xe84800, 0xc0000f4b40, 0xc0002ef8c0, 0xe84a40, 0xc0000f49c0, 0x0, 0x0)
	  lsprpc.go:531  0x57d
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xe84800, 0xc0000f4b40, 0xc00000e0c0, 0xe84a40, 0xc0000f49c0, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0001b6240, 0xc00026d200, 0xc00007bf60, 0xe84800, 0xc0000f4b40, 0xc00000e0c0, 0xe84a40, 0xc0000f49c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 1:23:37 PM] </pre>

**Comment by perrito666** [comment]
@hyangah  To be fair is the first time it crashes when I do this, usually It just get's a bit confused, I will try to reproduce it after updating

**Comment by hyangah** [comment]
@perrito666 Please open a new issue when you encounter crashes. The newer versions should address these crash bugs. Thanks!
