### ISSUE TITLE
Incorrectly reporting compiler errors

### ISSUE THREAD

**Issue by huttarichard** [golang/vscode-go#793]
Go pls 0.5.1
go version go1.15.2 darwin/amd64

This happens way to often, it is possible it is duplicate, idk.

![Screenshot 2020-10-15 at 16 43 38](https://user-images.githubusercontent.com/1809268/96146029-216dda80-0f06-11eb-8ff0-461ef78cf097.png)

restart of gopls server will clean up the error

**Comment by hyangah** [comment]
@huttarichard thanks for reporting the issue.

Can you please share the gopls log when the problem occurs? To enable logging,

`"go.languageServerFlags": ["-rpc.trace"]`

https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#vs-code for more detailed instruction.

**Comment by huttarichard** [comment]
@hyangah 

I don't think RPC logs will be any help.

```
[Trace - 10:57:05.675 AM] Sending request 'textDocument/codeAction - (21562)'.
Params: {"textDocument":{"uri":"file://......."},"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":9}},"context":{"diagnostics":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":10}},"message":"could not import strings (no package for import strings)","severity":1,"source":"compiler"}]}}
```

**Comment by hyangah** [comment]
@huttarichard I meant the  trace from the beginning to the time you triggered the issue.
That would reveal the workspace structure and build mode `gopls` uses.

Yes, this is most likely a problem of `gopls`.  Once we gather enough info for gopls, we transfer the issue to the gopls issue tracker.

**Comment by huttarichard** [comment]
@hyangah I understood what you meant.

Due to bureaucracy I cant really do what you need. But, 

I went trough rpc logs myself, and Im telling you there is not much of helpful info.
Not to mention there is bunch of noise which is completely unrelated to the issue. 

I suggest following, lets close this, next time this will appear I'll dig into it myself, I will report more closely what is wrong with gopls.
