### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by shifucun** [golang/vscode-go#799]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16ccd08]

goroutine 177 [running]:
golang.org/x/tools/internal/lsp/mod.vendorLens(0x1ae5b20, 0xc000387480, 0x1afa0a0, 0xc00040f8c0, 0x9e41840, 0xc000431ad0, 0xc000435a40, 0xc000438500, 0xb, 0x10, ...)
	  code_lens.go:129  0x158
golang.org/x/tools/internal/lsp.(*Server).codeLens(0xc00021b180, 0x1ae5b20, 0xc000387480, 0xc0001db3e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	  code_lens.go:38  0x4a1
golang.org/x/tools/internal/lsp.(*Server).CodeLens(0xc00021b180, 0x1ae5b20, 0xc000387480, 0xc0001db3e0, 0xc0001db3e0, 0x0, 0x0, 0xc0004a11a0, 0x1ae5be0)
	  server_gen.go:16  0x4d
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ae5b20, 0xc000387480, 0x1b00fc0, 0xc00021b180, 0xc0001db3b0, 0x1ae5d60, 0xc000387300, 0x0, 0x0, 0x0)
	  tsserver.go:325  0x263d
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ae5b20, 0xc000387480, 0xc0001db3b0, 0x1ae5d60, 0xc000387300, 0x0, 0xbfdaa304117cd650)
	  protocol.go:63  0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ae5b20, 0xc000387480, 0xc0001db3b0, 0x1ae5d60, 0xc000387300, 0x0, 0x0)
	  lsprpc.go:557  0x420
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ae5b20, 0xc000387480, 0xc000459000, 0x1ae5d60, 0xc000387300, 0x0, 0x0)
	  handler.go:35  0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000128300, 0xc000335110, 0xc0004308d0, 0x1ae5b20, 0xc000387480, 0xc000459000, 0x1ae5d60, 0xc000387300)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x171
[Error - 2:45:52 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.1, and I believe this was fixed in that version. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
