### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by i-curve** [golang/vscode-go#801]
gopls version: v0.4.1
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: parse "file://wsl$/Ubuntu/root": invalid URL escape "$"

goroutine 100 [running]:
golang.org/x/tools/internal/span.URI.Filename(0xc000281ee0, 0x19, 0x5, 0xe)
	  uri.go:32  0xcd
golang.org/x/tools/internal/lsp/cache.(*view).setBuildInformation(0xc0003aa2c0, 0xe38620, 0xc000407c80, 0xc000281ee0, 0x19, 0xc00022c700, 0x45, 0x70, 0x5f5e101, 0x0, ...)
	  view.go:616  0x62
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc0003866e0, 0xe38620, 0xc000407c80, 0xc0004084b0, 0x4, 0xc000281ee0, 0x19, 0x4000000000000000, 0x10101, 0xc000408410, ...)
	  session.go:145  0x4fc
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc0003866e0, 0xe38620, 0xc000407c80, 0xc0004084b0, 0x4, 0xc000281ee0, 0x19, 0x4000000000000000, 0x10101, 0xc000408410, ...)
	  session.go:95  0x132
golang.org/x/tools/internal/lsp.(*Server).addView(0xc000218d00, 0xe38620, 0xc000407c80, 0xc0004084b0, 0x4, 0xc000281ee0, 0x19, 0x0, 0x0, 0x0, ...)
	  workspace.go:42  0x1eb
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc000218d00, 0xe38620, 0xc000407c80, 0xc00029ce80, 0x1, 0x4)
	  general.go:190  0x18b
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc000218d00, 0xe38620, 0xc000407c80, 0x1391e70, 0x0, 0x0)
	  general.go:178  0x3ab
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000218d00, 0xe38620, 0xc000407c80, 0x1391e70, 0x1391e70, 0x0)
	  server_gen.go:112  0x50
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xe38620, 0xc000407c80, 0xc000392f30, 0x28444510, 0xc000407c20, 0x0, 0x0)
	  tsserver.go:98  0x7bf
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xe38620, 0xc000407c80, 0xc000392f30, 0x28444510, 0xc000407c20, 0x0, 0x0)
	  lsprpc.go:531  0x558
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xe38620, 0xc000407c80, 0xc00040fdc0, 0x28444510, 0xc000407c20, 0x0, 0x0)
	  handler.go:35  0xda
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000215320, 0xc0004740c0, 0xc00027ada0, 0xe38620, 0xc000407c80, 0xc00040fdc0, 0x28444510, 0xc000407c20)
	  handler.go:103  0x8d
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x178
[Error - 上午1:53:51] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by i-curve** [comment]
After I do that, the error is report as this:
```
Error loading workspace folders (expected 1, got 0) failed to load view for file:///wsl$/Ubuntu/root/Temp: invalid workspace configuration: The system cannot find the path specified.
```
Note: I start the vscode in WSL2 by using "code .". Also, vscode always create a resources\app\out\cli.js file in VSCODE's installation directory. I don't know what the file is for

**Comment by stamblerre** [comment]
@hyangah: Any advice on what might be going on here? I don't know anything about WSL2.

**Comment by hyangah** [comment]
@i-curve Are you using [Remote WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)?

```
Why Remote – WSL in VS Code?
While you can edit files in Linux using Windows-based tools, you can’t easily run or debug on Windows: you'd have to install all the same tools on Windows as you did on Linux, defeating the purpose of having an isolated Linux environment. You could view files from your \\wsl$\ share, but you wouldn't have access to features such as autocomplete, debugging, or linting.
```

Leaving `cli.js` is really strange - do you mind sharing the cli.js file with us for inspection?

**Comment by i-curve** [comment]
In WSL2, 'code .' command will open vscode in WSL2's file system. cli.js is empty.

**Comment by hyangah** [comment]
For WSL, please use the Remote WSL extension. Just opening WSL2 file system directly isn't supported.
