### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by martinyonathann** [golang/vscode-go#807]
gopls version: v0.5.1
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xb5113f]

goroutine 3480 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize.func2()
	  view.go:756  0x2df
sync.(*Once).doSlow(0xc0004a80d0, 0xc0029c08d0)
	  once.go:66  0xf3
sync.(*Once).Do(...)
	  once.go:57
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize(0xc0002500c0, 0xee9620, 0xc00471a240, 0x0)
	  view.go:722  0x1c8
golang.org/x/tools/internal/lsp/cache.(*snapshot).AwaitInitialized(0xc0002500c0, 0xee9620, 0xc00471a240)
	  snapshot.go:794  0x109
golang.org/x/tools/internal/lsp/cache.(*View).invalidateContent(0xc0001063c0, 0xee9020, 0xc00736b350, 0xc0066dc990, 0xc00350e500, 0x0, 0x0, 0x0)
	  view.go:790  0xd7
golang.org/x/tools/internal/lsp/cache.(*Session).DidModifyFiles(0xc0000d0180, 0xee9020, 0xc00736b350, 0xc0091040a0, 0x1, 0x1, 0x0, 0x198, 0x1, 0xcb55e0, ...)
	  session.go:509  0x8b0
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles(0xc00008c320, 0xee9020, 0xc00736b350, 0xc0091040a0, 0x1, 0x1, 0x1, 0x0, 0x0)
	  text_synchronization.go:189  0x10c
golang.org/x/tools/internal/lsp.(*Server).didChange(0xc00008c320, 0xee9020, 0xc00736b350, 0xc0066dc6f0, 0x0, 0x0)
	  text_synchronization.go:117  0x21f
golang.org/x/tools/internal/lsp.(*Server).DidChange(0xc00008c320, 0xee9020, 0xc00736b350, 0xc0066dc6f0, 0xc0066dc6f0, 0x0)
	  server_gen.go:36  0x50
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xee9020, 0xc00736b350, 0xf013c0, 0xc00008c320, 0xc0066dc6c0, 0x28ab40e8, 0xc00736b2f0, 0x0, 0x0, 0x0)
	  tsserver.go:120  0x1a2c
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xee9020, 0xc00736b350, 0xc0066dc6c0, 0x28ab40e8, 0xc00736b2f0, 0x0, 0xbfdb76eb69bc83f0)
	  protocol.go:63  0xc7
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xee9020, 0xc00736b350, 0xc0066dc6c0, 0x28ab40e8, 0xc00736b2f0, 0x0, 0x0)
	  lsprpc.go:557  0x427
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xee9020, 0xc00736b350, 0xc007349220, 0x28ab40e8, 0xc00736b2f0, 0xee9020, 0xc001e7a030)
	  handler.go:35  0xda
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc005e12840, 0xc00736bd10, 0xc000362080, 0xee9020, 0xc00736b350, 0xc007349220, 0x28ab40e8, 0xc00736b2f0)
	  handler.go:103  0x8d
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x178
[Error - 17:02:21] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Fixed by https://golang.org/cl/263520, which will be released as part of gopls/v0.5.2.
