### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by isra270** [golang/vscode-go#808]
gopls version: v0.4.0 ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW. Describe what you observed. <ANSWER HERE> Please attach the stack trace from the crash. A window with the error message should have popped up in the lower half of your screen. Please copy the stack trace from that window and paste it in this issue. <PASTE STACK TRACE HERE> OPTIONAL: If you would like to share more information, you can attach your complete gopls logs. NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE. DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY. <OPTIONAL: ATTACH LOGS HERE>

Tools environment: GOPATH=C:\Users\egypt2\go
Installing 1 tool at C:\Users\egypt2\go\bin in module mode.
  gopls@0.4.1

Installing golang.org/x/tools/gopls@v0.4.1 FAILED

1 tools failed to install.

gopls: failed to install [object Object]: Error: Command failed: C:\Go\bin\go.exe get -v golang.org/x/tools/gopls@v0.4.1
golang.org/x/tools/internal/jsonrpc2
# golang.org/x/tools/internal/jsonrpc2
..\..\..\..\..\go\pkg\mod\golang.org\x\tools@v0.0.0-20200513154647-78b527d18275\internal\jsonrpc2\messages.go:168:5: undefined: errors.As
 undefined

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.1. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

**Comment by isra270** [comment]
> Can you please try updating your `gopls` version? The latest version is v0.5.1. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".

thanks A lot for your reply, It's working after updating it.
