### ISSUE TITLE
UI: Documentation tooltip keeps shrinking when close to the right side of the window

### ISSUE THREAD

**Issue by victorhurdugaci** [golang/vscode-go#81]
### What version of Go, VS Code & VS Code Go extension are you using?
- go: `go1.14.2 darwin/amd64`
- code `1.45.1 5763d909d5f12fe19f215cbfdd29a91c0fa9208a x64`
- Go extension: `0.14.2`

### Describe the bug

When you type code that's close to the right edge of the VS code window, the documentation tooltip keeps shrinking until its left margin reaches the position of the caret.

Here's how it looks like:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/5921642/82502651-766b0900-9aac-11ea-8337-3bb69d6dc60d.gif)

### Steps to reproduce the behavior:
1. Type code close to the right edge of the VS code window and observe the documentation tooltip

**Comment by stamblerre** [comment]
Thanks for the report, @victorhurdugaci! However, the Go extension does not control the size or UI of the window. This sounds like a VS Code bug to me - does this happen with other languages? I'd suggest filing it with the https://github.com/Microsoft/vscode repository.

**Comment by stamblerre** [comment]
Closing this issue, as it is a upstream VS Code bug.
