### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by js2854** [golang/vscode-go#812]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xb440cd]

goroutine 136 [running]:
golang.org/x/tools/internal/lsp/cache.tempModFile(0x0, 0x0, 0x0, 0x0, 0xc0008a9aa0, 0x1, 0x0, 0x0, 0x0)
	  view.go:224  0x7d
golang.org/x/tools/internal/lsp/cache.(*snapshot).load(0xc000444180, 0xef4a00, 0xc0008a9b00, 0xc0000fee00, 0x20, 0x20, 0x0, 0x0)
	  load.go:123  0x1bcb
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize.func2()
	  view.go:734  0x3d1
sync.(*Once).doSlow(0xc0006e1710, 0xc000295ef8)
	  once.go:66  0xec
sync.(*Once).Do(...)
	  once.go:57
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize(0xc000444180, 0xef4940, 0xc000117640, 0x1)
	  view.go:704  0x1c1
golang.org/x/tools/internal/lsp/cache.(*Session).createView.func3(0xc000444180, 0xef4940, 0xc000117640, 0xc000330870)
	  session.go:243  0x44
created by golang.org/x/tools/internal/lsp/cache.(*Session).createView
	  session.go:242  0x9fc
[Error - 9:04:40 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.1. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
