### ISSUE TITLE
is there any way to show network traffic in vscode when debug with vscode-go?

### ISSUE THREAD

**Issue by mnm1001** [golang/vscode-go#813]
i use vscode to debugging golang, but i can't see request detail in charles
is there any way to show network traffic in vscode when debug with vscode-go?
or is there some way to make the  network traffic showed  in charles?

**Comment by hyangah** [comment]
@mnm1001  If charles provides proxied traffic info, I guess one can write an extension to retrieve/visualize the info. But that's not in the scope of vscode-go. 

VS Code Go simply runs test/debug programs using `go`/`dlv` commands or using nodeJS fork/spawn/exec*. So I don't think we can offer general network monitoring feature (at least not yet).
