### ISSUE TITLE
Add -insecure to go get command when getting  additional tools

### ISSUE THREAD

**Issue by brownwk** [golang/vscode-go#814]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).

**Is your feature request related to a problem? Please describe.**
When the extension want to install things like gopls, it can't as some places use certifcate chains. This is solved by using -insecure in the go get command.
**Describe the solution you'd like**
I think the issue is in the goGetPackage.ts file. Line 35, I think you need to add '-insecure' after the '-v'. Although this would be better if it was configurable.  I don't think everyone would want the default being insecure
**Describe alternatives you've considered**
I typicall copy and paste the command it is trying to run in code's terminal and add the -insecure option.
**Additional context**

**Comment by hyangah** [comment]
@brownwk thanks for the feature request.

The flag `-insecure` is going to be deprecated (https://github.com/golang/go/issues/37519) and `GOINSECURE` environment variable is recommended instead. (See 
https://golang.org/cmd/go/#hdr-Environment_variables). 

You can set `GOINSECURE` in `"go.toolsEnvVar"`. You will need this anyway to make other tools such as `gopls` or `go` in modules mode to work smoothly.

I filed #825 to allow fine tune the tool installation process, but it's likely that you don't need that.

**Comment by hyangah** [comment]
Closing in favor of #825.
