### ISSUE TITLE
Creating file inside package should add package header

### ISSUE THREAD

**Issue by andig** [golang/vscode-go#821]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).

**Is your feature request related to a problem? Please describe.**
Often when refactoring I need to create new files and _always_ add the initial package xyz line.

**Describe the solution you'd like**
`package xyz` should automatically be added when creating go file in folder

**Comment by hyangah** [comment]
Isn't autocomplete feature better than the prefilled template? Especially when multiple values are possible (e.g. `pkg` vs `pkg_test` for test files). 
gopls's autocompletion handles `package xyz` completion pretty well.

**Comment by andig** [comment]
Autocompletion for packages does not work very well for me (now suggestion). Another use case outside of autocomplete would be moving files between packages which should ideally update the package name too and (for proper refactoring) rewrite imports.

**Comment by hyangah** [comment]
@andig are you using `gopls`? (`"go.useLanguageServer": true`)

**Comment by stamblerre** [comment]
Closing this issue as it has been in a WaitingForInfo state for many months.
