### ISSUE TITLE
vscode use gopls autoformat notwork

### ISSUE THREAD

**Issue by gameFu** [golang/vscode-go#823]
setting.json
![image](https://user-images.githubusercontent.com/11696134/96835787-a0b75d00-1476-11eb-903f-b44dab025ce7.png)
version
![image](https://user-images.githubusercontent.com/11696134/96825084-e833ee00-1462-11eb-9d70-3e76241b4504.png)
go env
![image](https://user-images.githubusercontent.com/11696134/96825125-f71aa080-1462-11eb-96d0-bfdb97645b35.png)

**Comment by hyangah** [comment]
@gameFu Thanks for the report. Do you have screenshot or gopls trace that shows gopls didn't format code on save?

**Comment by stamblerre** [comment]
Also, the `enhancedHover` setting is now deprecated and is not required.
