### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by soypat** [golang/vscode-go#834]
gopls version: v0.5.1
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: unsupported URI schemes: [{vsls:/ ieeextreme2020}] (gopls only supports file URIs)
  Code: 0 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@soypat thanks for reporting the issue. Gopls doesn't support Live Share yet. :-( 
https://github.com/golang/vscode-go/issues/605
