### ISSUE TITLE
formatting: option to wrap long lines

### ISSUE THREAD

**Issue by rendaw** [golang/vscode-go#847]
Recent changes removed the option to prevent gopls from formatting code in the context of VS Code: https://github.com/mvdan/gofumpt/issues/83

gofumpt is specially being integrated into gopls, but this leaves users of other tools like https://github.com/segmentio/golines out in the cold now having to choose between better in-editor diagnostics or code formatting.

I (at least) am not particular about how long lines are automatically wrapped, so if you aren't interested in adding an option to wrap lines perhaps bringing back options that would allow golines to coexist with gopls would be great.

**Comment by stamblerre** [comment]
Thanks for the report. `gopls` doesn't currently support any custom formatters apart from `gofumpt` yet, and it's not likely that we will add support for this in the near future. Transferring to the VS Code Go repo in case @hyangah has alternative ideas for supporting custom formatters in VS Code Go.

**Comment by hyangah** [comment]
@stamblerre Is there an option to disable gopls's formatting support?  As discussed in https://github.com/microsoft/vscode/issues/72315 and https://github.com/microsoft/vscode/issues/41882 at length, multiple formatters from the same extension is not recommended. 

I am not sure how many other formatters out there - is there any other formatter to consider?

Re: golines - as discussed in slack, most of formatting decisions `golines` makes do not follow Go best practice while a couple of them are still something to consider.  For example, wrapping [long case lists](https://github.com/segmentio/golines/blob/master/_fixtures/case_lists__exp.go), [long comments](https://github.com/segmentio/golines/blob/master/_fixtures/comments__exp.go) could be handy and not be too far off of Go best practice if offered as code action or commands.

**Comment by stamblerre** [comment]
> @stamblerre Is there an option to disable gopls's formatting support? As discussed in [microsoft/vscode#72315](https://github.com/microsoft/vscode/issues/72315) and [microsoft/vscode#41882](https://github.com/microsoft/vscode/issues/41882) at length, multiple formatters from the same extension is not recommended.

Would it be possible to apply additional formatting in the language client's middleware?

**Comment by hyangah** [comment]
@stamblerre We can intercept all the formatting requests and not forwarding the requests. Given that most of alternative formatters will run the default gofmt, I don't see a value of forwarding or post processing the requests. 

I fear we need to add an additional setting to override gopls's feature. Or is there any existing setting we can reference?

What other formatters do users want to use?

**Comment by stamblerre** [comment]
There is `formatTool`, but I'm not sure if it's the best option. I honestly wasn't aware of `golines` until this issue, so I'm not sure.

**Comment by StevenACoffman** [comment]
BTW, golines lets you use a base formatter (such as gofumports) (so I'm using run on save here):
```
"emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.go$",
                "cmd": "golines ${file} -w -m 120 --base-formatter=\"gofumports\""
            },
        ]
    },
```
Note: after 0.1.0 release, gofumpt will include gofumports by default so the above will need to change to `gofumpt`.

**Comment by stamblerre** [comment]
You can now setting "go.formatTool": "golines" and it will work together with `gopls`. Closing.
