### ISSUE TITLE
gopls: Invalid auto-completion result for pointer type fields

### ISSUE THREAD

**Issue by wtask** [golang/vscode-go#85]
Extension inserts source pointer type definition instead a valid pointer literal. For example if we have 2 types like:

```
type MyInt int

type MyStruct struct {
   Field *MyInt
}
```

Then If I start typing something like below, I get auto-completed list with *MyInt type for the Field:

```
ms := MyStruct{
   Field: *MyInt...
}
```

but expected and valid result is:
```
ms := MyStruct{
   Field: &MyInt...
}
```

So you should replace `*` with `&` before insertion.

**Comment by hyangah** [comment]
@wtask Thanks for the bug report. 
Can you please share the go extension related settings? 

From Command Palette -> `Preferences: Open Settings (JSON)`, and share any settings that start with `go`, `[go]`, `gopls` prefixes. (If you use workspace-setting, do the same for `Preferences: Open Workspace Settings (JSON)` too.)

**Comment by wtask** [comment]
@hyangah 
user settings
```
"go.autocompleteUnimportedPackages": true,
"go.buildOnSave": "off",
"go.vetOnSave": "off",
  "go.enableCodeLens": {
    "references": false,
    "runtest": true
  },
  "go.useCodeSnippetsOnFunctionSuggest": true,
  "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
  "go.alternateTools": {
    "go-langserver": "gopls"
  },
  "go.useLanguageServer": true,
  "[go]": {
    "editor.snippetSuggestions": "none",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true,
    },
    // "editor.codeActionsOnSaveTimeout": 1000,
  },
  "[go.mod]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll": true,
      "source.organizeImports": true
    }
  },
  "gopls": {
    // add parameter placeholders when completing a function
    "usePlaceholders": true,
    "staticcheck": false
    // Experimental settings
    // "completeUnimported": true, // autocomplete unimported packages
    // "deepCompletion": true, // enable deep completion
  },
  "go.languageServerFlags": [
    "-rpc.trace", // for more detailed debug logging
    "serve",
    "--debug=localhost:6060", // to investigate memory usage, see profiles
  ],
```

**Comment by hyangah** [comment]
Thanks for sharing the info, @wtask 
I filed https://github.com/golang/go/issues/39227. Let's see what others think about it.

**Comment by hyangah** [comment]
@wtask the other opinion is to get rid of the placeholder for struct fields. Instead, users can still depend on the manual triggering of autocompletion which should suggest syntactically correct candidates. I don't think that's too bad, but I want to hear other users' opinion as well.

**Comment by stamblerre** [comment]
Let's close this issue in favor of golang/go#39227. It will be easier to continue the discussion in one place since this is `gopls`-specific.
