### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ahad-Parmar** [golang/vscode-go#865]
- Issue Type: `Bug`
- Extension Name: `go`
- Extension Version: `0.18.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by stamblerre** [comment]
@Ahad-Parmar: Can you please provide additional information about the problem?
