### ISSUE TITLE
No log.Print() output in Output window.

### ISSUE THREAD

**Issue by GAZ082** [golang/vscode-go#869]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.3 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.18.0
- Run `go env` to get the go development environment details
	- GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gabriel/.cache/go-build"
GOENV="/home/gabriel/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/gabriel/go/pkg/mod"
GONOPROXY="github.com/GAZ082/*"
GONOSUMDB="github.com/GAZ082/*"
GOOS="linux"
GOPATH="/home/gabriel/go"
GOPRIVATE="github.com/GAZ082/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/gabriel/projects/imperialmight.com/backend/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build238708827=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
  "go.autocompleteUnimportedPackages": true,
  "go.formatTool": "goimports",
  "go.inferGopath": true,
  "go.lintTool":"golangci-lint",
  "go.testTimeout": "20s",
  "go.toolsEnvVars": {
    "GO111MODULE": "on"
  },
  "go.toolsGopath": "/opt/go",
  "go.useLanguageServer": true,
"go.lintOnSave": "file"

### Describe the bug
Run any function or tests and not log.Print (or similar) output is shown in the Ouptut window.
If run the program with go run main.go there is output in the terminal.

On the Debug window I get the output and more:
```
API server listening at: 127.0.0.1:12120
2020/10/31 14:46:44 Test. Hi!
PASS
Failed to get state - Process 163285 has exited with status 0
dumpStacktrace - Failed to get debugger state Process 163285 has exited with status 0
dumpStacktrace: Failed to produce stack traceProcess 163285 has exited with status 0

```

### Steps to reproduce the behavior:
Run a function. Output from log.Print should appear on the Output window.

### Screenshots or recordings

**Comment by hyangah** [comment]
@GAZ082 do you have an example for repro? If I guess it's from test, that's the behavior consistent with the go command printed in the Output window. 

The extension runs the test in the 'package list' mode for which the go command outputs only PASS for successful tests.  (I think the primary reason is the test result caching. See `go help test`) If you want the log, try `"go.testFlags": ["-v"]`, or try `go test` without the package name from the integrated terminal directly - that will run the test in the local directory mode, and prints the log output. 

When the test runs in `debug test`, the extension delegates the test to the delve that compiles the test binary, runs it directly (instead of invoking through the go command`), and attaches the debugger - so the log output is printed.

**Comment by GAZ082** [comment]
Thanks for the comprehensive reply @hyangah . I checked my settings and without knowing deleted the go.testFlags portion. Now I restored -v and as you said, outputs the logs.

Appreciated!

**Comment by hyangah** [comment]
BTW for the history - https://github.com/golang/vscode-go/issues/528 

I think for tests that triggered from 'run test' code lens, directory mode may make sense, but I am reluctant to change the behavior further without input from users.
