### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by pointer2null** [golang/vscode-go#870]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Just creating new project and main.go

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xafd0d8]

goroutine 155 [running]:
golang.org/x/tools/internal/lsp/mod.vendorLens(0xed9d60, 0xc000490e40, 0xeea620, 0xc0006bf810, 0xeda020, 0xc00028f800, 0xc000450f30, 0xc000454400, 0xb, 0x10, ...)
	  code_lens.go:129  0x158
golang.org/x/tools/internal/lsp.(*Server).codeLens(0xc00045e280, 0xed9d60, 0xc000490e40, 0xc0002c31a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	  code_lens.go:38  0x4b2
golang.org/x/tools/internal/lsp.(*Server).CodeLens(0xc00045e280, 0xed9d60, 0xc000490e40, 0xc0002c31a0, 0xc0002c31a0, 0x0, 0x0, 0xc000387e00, 0xc00034d860)
	  server_gen.go:16  0x4d
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc000490e40, 0xeed8e0, 0xc00045e280, 0xc0002c3170, 0xed9fa0, 0xc000490d40, 0x0, 0xec7680, 0xc00001fc30)
	  tsserver.go:325  0x26a5
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc000490e40, 0xc0002c3170, 0xed9fa0, 0xc000490d40, 0x15c5631d, 0x132dce0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc000490e40, 0xc0002c3170, 0xed9fa0, 0xc000490d40, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc000490e40, 0xc0002c59c0, 0xed9fa0, 0xc000490d40, 0x1, 0x718e37)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000292660, 0xc000387e90, 0xc00043f040, 0xed9d60, 0xc000490e40, 0xc0002c59c0, 0xed9fa0, 0xc000490d40)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 9:42:36 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.2. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
