### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by HuoDx** [golang/vscode-go#871]
gopls version: v0.5.1
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xba27d9]

goroutine 163 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize.func2()
	  view.go:756  0x2d9
sync.(*Once).doSlow(0xc00052def0, 0xc000663320)
	  once.go:66  0xec
sync.(*Once).Do(...)
	  once.go:57
golang.org/x/tools/internal/lsp/cache.(*snapshot).initialize(0xc00047c180, 0xeeb440, 0xc000652210, 0x0)
	  view.go:722  0x1d5
golang.org/x/tools/internal/lsp/cache.(*snapshot).AwaitInitialized(0xc00047c180, 0xeeb440, 0xc000652210)
	  snapshot.go:794  0x116
golang.org/x/tools/internal/lsp/cache.(*snapshot).awaitLoaded(0xc00047c180, 0xeeb440, 0xc000652210, 0x0, 0x0)
	  snapshot.go:767  0x58
golang.org/x/tools/internal/lsp/cache.(*snapshot).WorkspacePackages(0xc00047c180, 0xeeb440, 0xc000652210, 0x0, 0x0, 0x0, 0x0, 0x0)
	  snapshot.go:540  0x5a
golang.org/x/tools/internal/lsp/cache.(*snapshot).ModTidy(0xc00047c180, 0xeeb440, 0xc000652210, 0xeeb640, 0xc00060e900, 0xef3300, 0xc00060e900, 0x0)
	  mod_tidy.go:64  0xde
golang.org/x/tools/internal/lsp/mod.Diagnostics(0xeeb440, 0xc000652210, 0xefc320, 0xc00047c180, 0x0, 0x0, 0x0)
	  diagnostics.go:38  0x2fa
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000328140, 0xeeb380, 0xc0002a4b80, 0xefc320, 0xc00047c180, 0xc0005b0800, 0x0, 0x0)
	  diagnostics.go:84  0x2c8
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc000328140, 0xefc320, 0xc00047c180)
	  diagnostics.go:48  0x87
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles.func2(0xc00052dec0, 0xc000328140, 0xefc320, 0xc00047c180, 0xc0006b54a0, 0x1, 0x1)
	  text_synchronization.go:282  0x6b
created by golang.org/x/tools/internal/lsp.(*Server).didModifyFiles
	  text_synchronization.go:280  0x9f0
[Error - 6:19:43 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.2. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
