### ISSUE TITLE
debug: provide an option to configure 

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#874]
The extension currently registers two debug configurations and users have to choose one of them after F5 unless they have launch.json configured. Some users found the extra click is inconvenient and checking in `launch.json` is not ideal.  Give users an option to turn on only one.

![Screen Shot 2020-11-02 at 10 37 37 AM](https://user-images.githubusercontent.com/4999471/97887113-73c93c80-1cf7-11eb-9f08-0f57a7cc8e5a.png)

**Comment by hyangah** [comment]
We disabled Go Dlv DAP mode (in #960) from the stable version. 
Still I think this is an option to consider when we reenable Go Dlv DAP mode in the same way.

**Comment by suzmue** [comment]
We now have only a single debug configuration and configure which debug adapter to use in the launch configuration (defaults to legacy).
