### ISSUE TITLE
"could not import ...." any external package

### ISSUE THREAD

**Issue by alwayshungry0814** [golang/vscode-go#877]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.3 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.18.1
- Run `go env` to get the go development environment details
	- `set GO111MODULE=auto
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Name\AppData\Local\go-build
set GOENV=C:\Users\Name\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Name\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Name\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Name\Desktop\pp\server\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\Name\AppData\Local\Temp\go-build188919362=/tmp/go-build -gno-record-gcc-switches`

### Share the Go related settings you have added/edited
i've changed GO111MODULE to 'on' but when i do, i get another error as soon as i re-open vs code
`The code in the workspace failed to compile (see the error message below). If you believe this is a mistake, please file an issue: https://github.com/golang/go/issues/new. go [-e -json -compiled=true -test=true -export=false -deps=true -find=false -- ./]: exit status 1: go: cannot find main module, but found .git/config in C:\Users\Name\Desktop\ppto create a module there, run: go mod init : packages.Load error`

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "go.delveConfig": {
    
        "dlvLoadConfig": {
            "followPointers": true,
            "maxVariableRecurse": 1,
            "maxStringLen": 64,
            "maxArrayValues": 64,
            "maxStructFields": -1
        },
        "apiVersion": 2,
        "showGlobalVariables": false
    }
}

### Describe the bug
A clear and concise description of what the bug.
every external package i import is squiggled and throws an error "could not import <package>"

i expect to see no error or red squiggles 

### Steps to reproduce the behavior:
1. import an external package 
2. use external package 
3. notice the squiggles and error

### side note:
the code runs just fine and it works but the red squiggles and the statements shown in the "PROBLEMS" tab are wrong

**Comment by stamblerre** [comment]
Can you please share the output of `gopls -rpc.trace -v check path/to/file.go`?

**Comment by alwayshungry0814** [comment]
`2020/11/03 20:25:32 Info:2020/11/03 20:25:32 go env for C:\Users\Name\Desktop\pp\server
(root C:\Users\Name\Desktop\pp\server)
(go version go version go1.15.3 windows/amd64)
(valid build configuration = true)
(build flags: [])
GOPROXY=https://proxy.golang.org,direct
GOROOT=c:\go
GOCACHE=C:\Users\Name\AppData\Local\go-build
GOFLAGS=
GONOPROXY=
GOINSECURE=
GOMODCACHE=C:\Users\Name\go\pkg\mod
GOMOD=C:\Users\Name\Desktop\pp\server\go.mod
GONOSUMDB=
GOPATH=C:\Users\Name\go
GOPRIVATE=
GOSUMDB=sum.golang.org
GO111MODULE=auto

2020/11/03 20:25:33 Info:2020/11/03 20:25:33 go/packages.Load
        snapshot=0
        directory=C:\Users\Name\Desktop\pp\server
        query=[builtin github.com/alwayshungry0814/pp/...]
        packages=2
2020/11/03 20:25:33 Info:2020/11/03 20:25:33 go/packages.Load
        snapshot=0
        package_path="builtin"
        files=[c:\go\src\builtin\builtin.go]
2020/11/03 20:25:33 Info:2020/11/03 20:25:33 go/packages.Load
        snapshot=0
        package_path="github.com/alwayshungry0814/pp"
        files=[C:\Users\Name\Desktop\pp\server\main.go]`

**Comment by stamblerre** [comment]
@alwayshungry0814: It looks like your `go.mod` file is located in `C:\Users\Name\Desktop\pp\server`, so that is the directory that you need to open in VS Code. If you want to open a different top-level directory, you can also add the `server` directory by selecting File -> Add Folder to Workspace. The issue you encountered is being tracked by https://github.com/golang/go/issues/42108.

**Comment by alwayshungry0814** [comment]
thank you!
