### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by vuuihc** [golang/vscode-go#878]
gopls version: v0.5.1
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls crashed

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

[Info  - 8:01:09 PM] 2020/11/03 20:01:09 go/packages.Load
	snapshot=17
	directory=/home/myname/go/src/myproject
	query=[file=/data/mm64/myname/go/src/myproject/logic/resource/qqmusic.go]
	packages=2

2020/11/03 20:01:10 commonDir saw map[/data/mm64/myname/go/src/myproject/logic/process:true /home/myname/go/src/myproject/logic/process:true] for [/data/mm64/myname/go/src/myproject/logic/process/cmddevicerecall.go /home/myname/go/src/myproject/logic/process/recalldialog.go]
[Error - 8:01:10 PM] Connection to server got closed. Server will not be restarted.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Can you please try updating your `gopls` version? The latest version is v0.5.2. You can do so by opening the Command Palette (Ctrl+Shift+P) and selecting "Go: Install/Update Tools".
