### ISSUE TITLE
Golang extension fails to activate in previously activated projects.

### ISSUE THREAD

**Issue by kalexmills** [golang/vscode-go#880]
- Run `go version` to get version of Go
	- go version go1.15.2 windows/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.50.1
d2e414d9e4239a252d1ab117bd7067f125afd80a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.18.1
- Run `go env` to get the go development environment details
	- set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Alex\AppData\Local\go-build
set GOENV=C:\Users\Alex\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\Alex\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Alex\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\Alex\Sanity\workspace\voxel-heat\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Alex\AppData\Local\Temp\go-build884236838=/tmp/go-build -gno-record-gcc-switches

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    "go.formatTool": "goimports",
    "go.useLanguageServer": false,

### Describe the bug

When starting VSCode in a folder which previously had Golang support, the Golang extension fails to activate as expected. All `Go:` prefixed commands in VS Code are unavailable.
Checking the VS Code console shows the following relevant messages.
```
abstractExtensionService.ts:708 
Activating extension 'golang.go' failed: Invalid or unexpected token.
_logMessageInConsole @ abstractExtensionService.ts:707

(node:9996) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

notificationsAlerts.ts:40 Command 'Go: Install/Update Tools' resulted in an error (command 'go.tools.install' not found)
```

### Steps to reproduce the behavior:
1. Open a Golang project.
1. See error

**Comment by kalexmills** [comment]
This was fixed for me after manually deleting the extension from `~/.vscode/extensions`, re-installing, and restarting VS Code.

Uninstalling and reinstalling the extension from within VS Code had no effect.

**Comment by stamblerre** [comment]
I'm glad that you were able to resolve the issue--It sounds like you may have had a corrupted installation of the extension. 

OK to close this?
