### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by ignaciocarvajal** [golang/vscode-go#888]
gopls version: v0.5.2
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: unsupported URI schemes: [{vsls:/ api-credit-card-reissue-config}] (gopls only supports file URIs)
  Code: 0 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@ignaciocarvajal: The Go language server does not yet support VS Code Live Share. Can you try setting `go.useLanguageServer`: `false` when you're using VSLS?
