### ISSUE TITLE
Unrelated debug session triggering editing warning

### ISSUE THREAD

**Issue by ermik** [golang/vscode-go#892]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- `go version go1.13.4 darwin/amd64`
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- `1.50.1`
- Check your installed extensions to get the version of the VS Code Go extension 
	- `v0.18.1`
- Run `go env` to get the go development environment details

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ermik/Library/Caches/go-build"
GOENV="/Users/ermik/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ermik/Projects/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/bpblv6xj33n17_8pr7h8k1t40000gn/T/go-build620241596=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### Share the Go related settings you have added/edited
N/A

### Describe the bug
A warning:

> A debug session is currently active. Changes to your Go files may result in unexpected behavior.

appears in reference to a debug session which is inconsequential to the Go environment.

### Steps to reproduce the behavior:
1. Open workspace which combines a Go project (workspace has a folder which contains `go.mod`) and a Node.js project
1. Start debug session for the Node.js project
1. Edit Go source code
1. Trigger auto-save or save the changes to the Go file

**Comment by hyangah** [comment]
I also observed this issue while working on a go file in vscode-go project. 
The relevant code:  
https://github.com/golang/vscode-go/blob/855baebe4b62f7eff0662cd5e968a8381ba5576a/src/goMain.ts#L596 
We need to inspect the DebugSession and check the active debug session is relevant.
