### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by mirceadthelotter** [golang/vscode-go#893]
gopls version: v0.5.2
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: unsupported use of -modfile, expected 1 module, got 2

goroutine 5637 [running]:
golang.org/x/tools/internal/lsp/cache.(*snapshot).load(0xc0001663c0, 0xe894c0, 0xc00639cde0, 0xc003518000, 0x1a, 0x20, 0x0, 0x0)
	  load.go:118  0x29cb
golang.org/x/tools/internal/lsp/cache.(*snapshot).reloadWorkspace(0xc0001663c0, 0xe894c0, 0xc00639cde0, 0x3, 0x1)
	  snapshot.go:896  0x44a
golang.org/x/tools/internal/lsp/cache.(*snapshot).awaitLoaded(0xc0001663c0, 0xe894c0, 0xc00639cde0, 0x0, 0x0)
	  snapshot.go:839  0x85
golang.org/x/tools/internal/lsp/cache.(*snapshot).WorkspacePackages(0xc0001663c0, 0xe894c0, 0xc00639cde0, 0x0, 0x20, 0xe700000000000020, 0x8, 0x0)
	  snapshot.go:597  0x65
golang.org/x/tools/internal/lsp/cache.(*snapshot).ModTidy(0xc0001663c0, 0xe894c0, 0xc00639cde0, 0x1897eeb8d40, 0xc00069a120, 0x0, 0xc00069a120, 0x0)
	  mod_tidy.go:72  0x156
golang.org/x/tools/internal/lsp/mod.Diagnostics(0xe894c0, 0xc00639cde0, 0xe9b5c0, 0xc0001663c0, 0x0, 0x0, 0x0)
	  diagnostics.go:29  0x3d6
golang.org/x/tools/internal/lsp.(*Server).diagnose(0xc000166240, 0xe89400, 0xc005341200, 0xe9b5c0, 0xc0001663c0, 0xc004ed5e00, 0x0, 0x0)
	  diagnostics.go:163  0x26b
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot.func1()
	  diagnostics.go:104  0x77
golang.org/x/tools/internal/lsp.(*debouncer).debounce(0xc0008760d0, 0xc00028cd20, 0x6, 0x6, 0xbebc200, 0xc004087f10)
	  debounce.go:79  0x38a
golang.org/x/tools/internal/lsp.(*Server).diagnoseSnapshot(0xc000166240, 0xe9b5c0, 0xc0001663c0, 0xc005ebd1c0, 0x1, 0x1)
	  diagnostics.go:103  0x2b7
golang.org/x/tools/internal/lsp.(*Server).didModifyFiles.func2(0xc0051276d0, 0xc000166240, 0xe9b5c0, 0xc0001663c0, 0xc005ebd1c0, 0x1, 0x1)
	  text_synchronization.go:235  0x96
created by golang.org/x/tools/internal/lsp.(*Server).didModifyFiles
	  text_synchronization.go:233  0x5fe
[Error - 6:49:48 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@mirceadthelotter: Can you please share your VS Code settings? They can be found by opening the Command Palette (Ctrl+Shift+P) and then selecting Preferences: Open Settings (JSON).

Also, do you mind describing your workspace? Do you have multiple modules open at the top-level using workspace folders?

**Comment by stamblerre** [comment]
Also, can you please try reproducing with `gopls` at master? You can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.
