### ISSUE TITLE
no test files & cannot find debug.test

### ISSUE THREAD

**Issue by rantianhua** [golang/vscode-go#894]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.14.2 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.0
fcac248b077b55bae4ba5bab613fd6e9156c2f0c
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.18.1 - 30th Oct, 2020
- Run `go env` to get the go development environment details
	- GO111MODULE="on"
GOARCH="amd64"
GOBIN="/Users/rantianhua/go/bin"
GOCACHE="/Users/rantianhua/Library/Caches/go-build"
GOENV="/Users/rantianhua/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rantianhua/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/Cellar/go/1.14.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/rantianhua/mw/mr-weather-backend/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="/usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wn/y2vxh0wx36x0trv10dc0f0_h0000gn/T/go-build552681509=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

**settings.json**
```json
{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.semanticHighlighting.enabled": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "go.useLanguageServer": true,
    "window.zoomLevel": 0,
}
```
**launch.json**

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch test function",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${fileDirname}",
            "args": [
                "-test.run",
                "TestGenSKUSQL"
            ]
        },
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}
```

### Describe the bug

I have a main_test.go file with the package `main` in the sku_sql_generator folder.
Cannot debug and run test files with error:

1. [no test files]
2. debug.test: no such file or directory

### Steps to reproduce the behavior:
1. Go to `sku_sql_generator/main_test/go#TestGenSKUSQL` .
2. Click on 'run test' upon the function.
3. See error: `github.com/xxx/sku-sql-generator	[no test files]`

and 

1. Go to `sku_sql_generator/main_test/go#TestGenSKUSQL` .
2. Click on 'debug test' upon the function.
3. See error: `/Users/xxx/sku-sql-generator/debug.test: no such file or directory`

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

<img width="324" alt="Screen Shot 2020-11-07 at 1 37 50 PM" src="https://user-images.githubusercontent.com/7328707/98433011-803a0480-20fe-11eb-85e5-b4b33edfdb28.png">
<img width="499" alt="Screen Shot 2020-11-07 at 1 37 59 PM" src="https://user-images.githubusercontent.com/7328707/98433013-816b3180-20fe-11eb-87e2-051301ef8014.png">
<img width="491" alt="Screen Shot 2020-11-07 at 1 38 05 PM" src="https://user-images.githubusercontent.com/7328707/98433016-83cd8b80-20fe-11eb-885f-b8eb7f302104.png">

**Comment by hyangah** [comment]
@rantianhua The main_test.go has a build tag - `// +build unit` which prevents the go command from using the file only when `unit` build tag is enabled. Either remove the build tag line, or configure the build/test tag flags either using `"go.buildTags"` or `"go.testTags"` setting (https://github.com/golang/vscode-go/blob/master/docs/settings.md#gotesttags)

**Comment by rantianhua** [comment]
Use "go.buildTags" solved the problem.
