### ISSUE TITLE
Add Struct Tags: More transform variants

### ISSUE THREAD

**Issue by skaldesh** [golang/vscode-go#906]
**Is your feature request related to a problem? Please describe.**
I want to use "kebabcase" in my project for my `yaml:"my-property"` tags.

**Describe the solution you'd like**
Add kebabcase (and other transforms maybe?)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hyangah** [comment]
@skaldesh thanks for the report - we are using the `gomodifytags` tool for this feature, so we can support only the listed transformations here https://github.com/fatih/gomodifytags#transformations

Currently only snakecase/camelcase are settable through `settings.json` or settings UI. But you can still choose `lispcase`, `pascalcase`, or `keep` option by enabling `promptForTags` and supplying your choice for the transformation value.

```
"go.addTags": {
  "promptForTags": true
}
```

**Comment by skaldesh** [comment]
Understood, the `lispcase` transformation is the one that I am personally looking for.  
It should be an easy fix to simply allow all of these available transformations in the settings file/UI. I can try to do it, if you point me in the right direction (I have never contributed here before).

**Comment by hyangah** [comment]
@skaldesh https://github.com/golang/vscode-go/blob/master/package.json#L1691-L1692

Can you please add all the currently supported transform lists there? Thanks!
Our contribution guide is https://github.com/golang/vscode-go/blob/master/docs/contributing.md#setup but it's still sparse. Ping us in the gophers slack `#vscode-dev` channel if you have questions.
