### ISSUE TITLE
cwd configuration in Run: Start Without Debugging not respected

### ISSUE THREAD

**Issue by zpv** [golang/vscode-go#918]
### Describe the bug
https://github.com/zpv/cwd-test

With the following launch configuration:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/cmd/app/main.go",
            "env": {},
            "args": []
        }
    ]
}
```
the `cwd` property is respected in Debug mode, but is seemingly ignored when Start without Debugging is used.

Running [this project](https://github.com/zpv/cwd-test) will panic as it tries to read the file in cmd/app instead of the workspace root.

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.2 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- v0.18.1
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/steven/Library/Caches/go-build"
GOENV="/Users/steven/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/steven/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/steven/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1g/dlx_p3_j02gcs41jxpyy38s80000gn/T/go-build059177566=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by zpv** [comment]
Thank you @suzmue! 🙏

**Comment by mkilzer78** [comment]
Unfortunately this fix doesn't properly work on `GOOS=windows`, a file named `out` cannot be executed: [src/debugAdapter/goDebug.ts:486](https://github.com/golang/vscode-go/commit/3493cfee14f3b8b1250681c69a7faf7a32c72e5a#diff-42370209a717d9c657a14f0dcfc980d8321fff898c864c7be23b315deb977394R486). It would have to be named `out.exe` instead.

Trace output when hitting Ctrl+F5 (Run Without Debugging) on Win10 with golang.go v0.19.0:
```
[...]
Current working directory: c:\Users\Myself\go\src\hello_world
Building: C:\Program Files\go\bin\go.exe build -o=C:\Users\Myself\AppData\Local\Temp\out .
Build process exiting normally null
Current working directory: c:\Users\Myself\go\src\hello_world
Running: C:\Users\Myself\AppData\Local\Temp\out
Process exiting with code: -4058 signal: false
[...]
```

**Comment by suzmue** [comment]
Thanks for filing this issue @mkilzer78! Will get this fixed

I think this failure should be showing up in the long tests as well.
