### ISSUE TITLE
gorename: package xxx is not in GOROOT

### ISSUE THREAD

**Issue by taobaohi** [golang/vscode-go#92]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)
  - Set "trace": "log" and share the resulting logs in the debug console when logging an issue.

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- 1.14
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.45.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.14.3
- Run `go env` to get the go development environment details
<pre>
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\admin\AppData\Local\go-build
set GOENV=C:\Users\admin\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GONOPROXY=gitlab.c21sis.com
set GONOSUMDB=gitlab.c21sis.com
set GOOS=windows
set GOPATH=d:\go_workspace
set GOPRIVATE=gitlab.c21sis.com
set GOPROXY=https://goproxy.io/
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\go_workspace\src\pink-api\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\admin\AppData\Local\Temp\go-build671071106=/tmp/go-build -gno-record-gcc-switches
</pre>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.
<pre>
{
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.external.windowsExec": "C:\\Program Files\\Git\\bin\\bash.exe",
    "window.zoomLevel": 0,
    "go.formatTool": "goimports",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "editor.fontSize": 16,
    "files.autoSave": "afterDelay",
    "java.home": "C:\\Program Files\\RedHat\\java-11-openjdk-11.0.6-2\\",
    "java.help.firstView": "gettingStarted",
    "java.requirements.JDK11Warning": true,
    "maven.terminal.useJavaHome": true,
    "java.semanticHighlighting.enabled": true,
    "terminal.integrated.shell.linux": "",
    "terminal.integrated.automationShell.linux": "",
    "terminal.integrated.automationShell.osx": "",
    "terminal.integrated.automationShell.windows": "",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-11",
            "path": "C:\\Program Files\\RedHat\\java-11-openjdk-11.0.6-2\\",
        }
    ],
    "java.maven.updateSnapshots": true,
    "maven.executable.path": "C:\\java\\apache-maven-3.6.3\\bin\\mvn",
    "java.configuration.maven.userSettings": "C:\\java\\apache-maven-3.6.3\\conf\\settings.xml",
    "java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"c:\\Users\\admin\\.vscode\\extensions\\gabrielbb.vscode-lombok-1.0.1\\server\\lombok.jar\"",
    "remote.SSH.remotePlatform": {
        "105": "linux"
    },
    "git.ignoreLegacyWarning": true,
    "go.autocompleteUnimportedPackages": true,
    "go.addTags": {
    
    }
}
</pre>

### Describe the bug
A clear and concise description of what the bug.

### Steps to reproduce the behavior:
1. seelct type name 
2. press F2 rename
3. See error :Rename failed: gorename: package pink-api/service/sissvc is not in GOROOT (c:\go\src\pink-api\service\sissvc) 

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
You are using Go in modules mode (based on `set GOMOD=D:\go_workspace\src\pink-api\go.mod`). I don't think `gorename`, the underlying tool used in this case, supports module mode. https://github.com/golang/go/issues/24661

For modules mode, we recommend [`gopls` instead](https://github.com/golang/vscode-go/blob/master/docs/modules.md)

`"go.useLanguageServer": true`

**Comment by stamblerre** [comment]
As @hyangah says, this is working as intended for modules. We will only be supporting rename through `gopls` - please open a new issue if you have difficulties setting up `gopls`.

**Comment by taobaohi** [comment]
@hyangah  thanks!
setting-->search ''go.useLanguageServer"--->enable checkbox--->auto download gopls.
go rename bug fix!
