### ISSUE TITLE
Go Path of extension is always be defferent from go env gopath

### ISSUE THREAD

**Issue by roanhe-ts** [golang/vscode-go#922]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.12 linux/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	-  code -v 1.51.1
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.18.1
- Run `go env` to get the go development environment details
	- GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go:/root/go/src/ops/back_end"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build164673906=/tmp/go-build -gno-record-gcc-switches"

### Share the Go related settings you have added/edited
Modified go.gopath in the settings like this:

"go.gopath": "/root/go:/root/go/src/ops/back_end"

but it didn't work. Current Go Path of go extension always be /root/go

curren settings:
    "go.gopath": "/root/go:/root/go/src/ops/back_end",
    "go.installDependenciesWhenBuilding": true,
    "go.formatTool": "goimports",

### Describe the bug
Go Path of Go extension always be /root/go, which should be /root/go:/root/go/src/ops/back_end to be same with settings in go env gopath

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.
![image](https://user-images.githubusercontent.com/42906151/99144460-10e58700-26a1-11eb-9531-7544ea452c9a.png)

Actually I set Infer Gopath option to false.

**Comment by hyangah** [comment]
@roanhe-ts thanks for the report.

The message appears only if `go.inferGopath` is set ([code](https://github.com/golang/vscode-go/blob/master/src/goMain.ts#L726-L728)).
Can you please check the settings in all levels? (user level, workspace level, and folder level - if it applies). VSCode settings UI has a separate tabs for each level.

FYI - I personally recommend users stay away from depending on such GOPATH arrangement. The go project is currently moving towards deprecating `GOPATH`. For example, in Go1.16, it will turn on the module mode by default (https://github.com/golang/go/issues/41330 as the first step for the deprecation.

**Comment by roanhe-ts** [comment]
> @roanhe-ts thanks for the report.
> 
> The message appears only if `go.inferGopath` is set ([code](https://github.com/golang/vscode-go/blob/master/src/goMain.ts#L726-L728)).
> Can you please check the settings in all levels? (user level, workspace level, and folder level - if it applies). VSCode settings UI has a separate tabs for each level.
> 
> FYI - I personally recommend users stay away from depending on such GOPATH arrangement. The go project is currently moving towards deprecating `GOPATH`. For example, in Go1.16, it will turn on the module mode by default ([golang/go#41330](https://github.com/golang/go/issues/41330) as the first step for the deprecation.

@hyangah Thanks fou your replay.
My `go.inferGopath` is set true in user level setting, and false in SSH Remote and Workspace level.
In fact, the gopath got correct in the next day automatically ....

And I'll consider to use go module, thanks for your suggestion.

**Comment by hyangah** [comment]
@roanhe-ts Does the extension infer `GOPATH` even when the SSH Remote/Workspace level setting disables it? That's really strange - wonder if it's a vscode configuration bug. Let us know if it's reproducible and you have an example we can share with the upstream vscode team.
