### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zhiqiang-bianjie** [golang/vscode-go#931]
gopls version: v0.5.3
gopls flags: ${env:GOPATH} ${env:GOROOT}

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@zhiqiang-bianjie: Can you please share any of the Go related settings you have added/edited? It looks like there might be something wrong with your `go.languageServerFlags` configuration.

To do so, please run `Preferences: Open Settings (JSON)` command to open your settings.json file, and share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

**Comment by hyangah** [comment]
@zhiqiang-bianjie Please open a new issue if you still observe crash after fixing the `"go.languageServerFlags"` setting. Thanks for the report!
