### ISSUE TITLE
gopls: update to the latest version when we turn it on by default

### ISSUE THREAD

**Issue by stamblerre** [golang/vscode-go#938]
Users who have opted out of gopls may have outdated versions on their machines. We should not delay before prompting them to update--we should update right away, before we turn it on.

**Comment by hyangah** [comment]
This is critical for the first user experience.

**Comment by stamblerre** [comment]
Can we close this now that https://golang.org/cl/274250/ is merged, or is there other work to do here?

**Comment by hyangah** [comment]
Thanks @suzmue !
