### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by cfanbo** [golang/vscode-go#939]
gopls version: v0.5.3
gopls flags: *.wxs

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
@cfanbo: It looks like there might be an issue with your `go.languageServerFlags` configuration--can you clear that out?

**Comment by hyangah** [comment]
@cfanbo Please open a new issue if you still observe gopls crash even after clearing out and fixing `"go.languageServerFlags"`. Thanks for the report.
