### ISSUE TITLE
docs: improve documentation about the go tools installed by the extension

### ISSUE THREAD

**Issue by Kur-Ich** [golang/vscode-go#95]
I'm getting daily notifications that I'm missing some add-ons for Go. It would be nice if you could select in Settings which add-ons you want to use and which ones not, I really don't want to use formatting type add-ons for example which auto format the code in a certain way. Also an explanation would be nice of what the add-on exactly does so that it would be easy to select which ones you want. Currently a lot of Go extensions got automatically installed on my VSCode and it is not clear to me what they do.

**Comment by hyangah** [comment]
About what each tool is doing:
https://github.com/golang/vscode-go/blob/master/docs/tools.md

We need better documentation and improve the installation process.

About formatting: formatting can be disabled with "editors.formatOnSave", for example, 
```
"[go]": {
   "editors.formatOnSave": false
}
```

But, go has its own formatting rule from the very beginning of the language, and
the formatting tool is an essential part of the Go code writing that helps keeping the code style consistent among Go developers. Skipping formatting and applying different formatting rules is not recommended in general.

If you use `gopls`, many of them are unnecessary, and the extension shouldn't suggest installation of those tools - please update https://github.com/golang/vscode-go/issues/51 if you find any questionable tools that were recommended when using `gopls`.

**Comment by hyangah** [comment]
Recently we updated our [tools documentation](https://github.com/golang/vscode-go/blob/master/docs/tools.md) and also the minimal list of the required tools as we enabled gopls by default. Please file a new issue if the documentation is still ambiguous or if the extension requires you to install more tools than necessary.
