### ISSUE TITLE
autogenerate function under selected code segment

### ISSUE THREAD

**Issue by moneyease** [golang/vscode-go#950]
If you have a question, please ask it on the `#vscode` or `#vscode-go` channels in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode).

**Is your feature request related to a problem? Please describe.**
I always in a situation to modularize some part of code and It's be cool if we add an option to create a function with selected code 

```
func post() {
    url := "http://restapi3.apiary.io/notes"
    fmt.Println("URL:>", url)

    var jsonStr = []byte(`{"title":"Buy cheese and bread for breakfast."}`)
    req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonStr))
    req.Header.Set("X-Custom-Header", "myvalue")
    req.Header.Set("Content-Type", "application/json")
   
   // begin selected code
    client := &http.Client{}
    resp, err := client.Do(req)
    if err != nil {
        panic(err)
    }
    defer resp.Body.Close()

    fmt.Println("response Status:", resp.Status)
    fmt.Println("response Headers:", resp.Header)
    body, _ := ioutil.ReadAll(resp.Body)
    fmt.Println("response Body:", string(body))
   // end selected code
}
```

**Describe the solution you'd like**
It'll be good it we select common code and run a command to create a function with all required parameters. 
**Please note, the new autogenerated function needs to be called correctly by programmer and tool just creates a function.**

```
func this_is_auto_generated_code(req *http.Request) {
    client := &http.Client{}
    resp, err := client.Do(req)
    if err != nil {
        panic(err)
    }
    defer resp.Body.Close()

    fmt.Println("response Status:", resp.Status)
    fmt.Println("response Headers:", resp.Header)
    body, _ := ioutil.ReadAll(resp.Body)
    fmt.Println("response Body:", string(body))
}

func post() {
    url := "http://restapi3.apiary.io/notes"
    fmt.Println("URL:>", url)

    var jsonStr = []byte(`{"title":"Buy cheese and bread for breakfast."}`)
    req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonStr))
    req.Header.Set("X-Custom-Header", "myvalue")
    req.Header.Set("Content-Type", "application/json")
    // added by programmer
    this_is_auto_generated_code(req)
 
}

```

**Describe alternatives you've considered**
Manually do this

**Additional context**
* better modularization
* ease of use
* code reuse

**Comment by hyangah** [comment]
@moneyease Thanks for the feature request. Have you tried the language server and its refactoring feature?

https://twitter.com/belbaoverhill/status/1308851247831805952

In order to enable the language server, `"go.useLanguageServer": true` and make sure you are with the latest version of the go language server (`gopls version` --> v0.5.3).
