### ISSUE TITLE
debug: hide Go Dlv Dap (Experimental) configuration from the stable version.

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#960]
We enabled it in the stable version to allow more users to participate in the new feature testing 
https://github.com/golang/vscode-go/issues/23
But it requires the dev versions of Delve, and it is missing some important features.
I propose we hide it from the stable version for now and re-enable it as Delve is released for 1.16
or the extension has a solution to manage a separate version of delve for this feature.

cc/ @polinasok @suzmue

**Comment by hyangah** [comment]
Not sure why gopherbot doesn't close this. 
The change will be included in the next stable release 0.19.1

**Comment by niteeshhegde** [comment]
Good to see some progress after waiting so long
