### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by Philip-Nunoo** [golang/vscode-go#968]
gopls version: v0.5.3
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: unsupported URI schemes: [{vsls:/ my-app}] (gopls only supports file URIs)
  Code: 0 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
What version of the VS Code Go extension are you using? I believe this crash should be fixed with the latest release (v0.19.0).
