### ISSUE TITLE
Failed to find the "go" binary from PATH

### ISSUE THREAD

**Issue by up9cloud** [golang/vscode-go#971]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.2 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
- Check your installed extensions to get the version of the VS Code Go extension
	- v0.18.1
- Run `go env` to get the go development environment details
	- GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ss/Library/Caches/go-build"
GOENV="/Users/ss/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/ss/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ss/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
...

### Share the Go related settings you have added/edited

None.

### Describe the bug

Every time I restart vscode, it shows: `Failed to find the "go" binary in either。GOROOT() or PATH(/usr/bin:/bin:/usr/sbin:/sbin). Check PATH, or Install Go and reload the window.`

It seems the PATH(`/usr/bin:/bin:/usr/sbin:/sbin`) from the message is not my actual path:

```console
$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ which go
/usr/local/bin/go
```

And if I manually did `Developer: reload window` once after terminal started, it would work without errors.

### Steps to reproduce the behavior:

1. Clear all settings about go in vscode, make it all defaults
2. Make sure your executable go not in `/usr/bin:/bin:/usr/sbin:/sbin`
3. Add `sleep 15` to `~/.bash_profile` to make terminal very slow to up
3. Restart vocode

### Screenshots or recordings

<img width="458" alt="Screen Shot 2020-11-27 at 16 24 26" src="https://user-images.githubusercontent.com/8325632/100490079-56587a00-30cd-11eb-9403-153641041b01.png">

Refs may help:
- https://github.com/microsoft/vscode/issues/108804
- https://github.com/microsoft/vscode/issues/108003

**Comment by hyangah** [comment]
Thanks for finding the references to the latest vscode work towards this issue. Looks like the process environment population got unstable in the recent releases of vscode. :-( 

Until vscode team sorts out this and directs extension authors, let's make a link to the reference issue and recommend  the "Reload the window" command.

**Comment by kwsorensen** [comment]
I am running into this problem as well. 

Error on load: 
`Failed to find the "go" binary in either GOROOT() or PATH(/home/kyles/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/bin:/home/kyles/go/bin:/bin:/home/kyles/.nvm/versions/node/v10.24.1/bin:/usr/local/bin/pact/bin:/snap/bin:/home/kyles/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/kubebuilder/bin). Check PATH, or Install Go and reload the window. If PATH isn't what you expected, see https://github.com/golang/vscode-go/issues/971`

Commands on shell:
`go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/kyles/.cache/go-build"
GOENV="/home/kyles/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/kyles/.gvm/pkgsets/go1.15.6/global/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/kyles/.gvm/pkgsets/go1.15.6/global"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/kyles/.gvm/gos/go1.15.6"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/kyles/.gvm/gos/go1.15.6/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build617534469=/tmp/go-build -gno-record-gcc-switches"`

`go version
go version go1.15.6 linux/amd64`


`echo $GOPATH
/home/kyles/.gvm/pkgsets/go1.15.6/global`

`code -v
1.59.1
3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
x64`

**Comment by Tsubanee** [comment]
I also had the same problem.

Installing the go in the default directory suggested in go [docs](https://golang.org/doc/install) (/usr/local/go) solved the problem for me. Probably the extension uses some hard typed path resolution 😢 .

**Comment by kroksys** [comment]
I had this issue and resolved by overriding goroot variable in VSC.

1. Shift + Cmd + P
2. Search for: "open settings" and choose "Open Settings (JSON)"
<img width="608" alt="Screenshot 2021-09-27 at 11 41 15" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">

3. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").
4. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",
in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",

<img width="426" alt="Screenshot 2021-09-27 at 11 53 19" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">

Good luck!

**Comment by gcstang** [comment]
Why is this using a hardcoded path?

This is constantly erroring and the only current resolution was posted by @kroksys however this would need to be updated every time the version changes.

Please open this issue back up and fix it as the terminal works properly it's just this plugin that has an issue.
$ go version
go version go1.17.1 darwin/amd64

**Comment by stamblerre** [comment]
@gcstang: If you are encountering a problem, please open a new issue and fill out the issue template. Also, please see the [Troubleshooting guide](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md).

**Comment by armenic** [comment]
> 
> 
> I had this issue and resolved by overriding goroot variable in VSC.
> 
>     1. Shift + Cmd + P
> 
>     2. Search for: "open settings" and choose "Open Settings (JSON)"
> 
> 
> <img alt="Screenshot 2021-09-27 at 11 41 15" width="608" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">
> 
>     1. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").
> 
>     2. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",
>        in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",
> 
> 
> <img alt="Screenshot 2021-09-27 at 11 53 19" width="426" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">
> 
> Good luck!

Thanks so much @kroksys! I looked up the GOROOT variable with `go env` then copied the value in the settings as you specified.

**Comment by imageslr** [comment]
> Why is this using a hardcoded path?
> 
> This is constantly erroring and the only current resolution was posted by @kroksys however this would need to be updated every time the version changes.
> 
> Please open this issue back up and fix it as the terminal works properly it's just this plugin that has an issue. $ go version go version go1.17.1 darwin/amd64

I'm using gvm to manage go version. Everytime I switch the go version, I have to modify vscode setting to avoid this problem. That's inconvenient.

**Comment by gcstang** [comment]
> > Why is this using a hardcoded path?
> > This is constantly erroring and the only current resolution was posted by @kroksys however this would need to be updated every time the version changes.
> > Please open this issue back up and fix it as the terminal works properly it's just this plugin that has an issue. $ go version go version go1.17.1 darwin/amd64
> 
> I'm using gvm to manage go version. Everytime I switch the go version, I have to modify vscode setting to avoid this problem. That's inconvenient.

@imageslr See if this solution helps you
https://github.com/golang/vscode-go/issues/1823

**Comment by imageslr** [comment]
Thank you @gcstang

**Comment by bittopaz** [comment]
It works for me with the config as below:

```json
"go.alternateTools": {
    "go": "/opt/homebrew/bin/go"
}
```

**Comment by SebastianKristof** [comment]
> It works for me with the config as below, so I don't have to update the config after each `brew upgrade go`.
> 
> ```json
> "go.alternateTools": {
>     "go": "/opt/homebrew/bin/go"
> }
> ```

The above worked for me (thank you @bittopaz), while the previous solution with "go.goroot" gave the following error:
![image](https://user-images.githubusercontent.com/30603815/150917896-fe440cdf-143b-4724-9808-f76cb7053662.png)

**Comment by ikingye** [comment]
My VSCode was fine before, and today the problem just popped up.
I just restart my vscode, and problem is solved like magic.

**Comment by canispeakchinese** [comment]
> My VSCode was fine before, and today the problem just popped up. I just restart my vscode, and problem is solved like magic.

so am i

**Comment by uguryilmazunified** [comment]
Adding go.goroot to json file didn't work for me;

"go.alternateTools": {
    "go": "/opt/homebrew/bin/go"
} is working for me and if anyone is having trouble finding the variable for goroot value or if it doesn't come up in $go env, you can find it via `which go `, this should be the value of goroot

**Comment by tompave** [comment]
Another solution is to always start VS Code with the `code` command, i.e. `code .`. So that it will inherit the env from your shell.

**Comment by simonireilly** [comment]
> It works for me with the config as below, so I don't have to update the config after each `brew upgrade go`.
> 
> ```json
> "go.alternateTools": {
>     "go": "/opt/homebrew/bin/go"
> }
> ```

Yeah, this is the one that worked best for me, I am using .asdf and it works for changing go version aswell.

```
which go
/Users/simonreilly/.asdf/shims/go
```

**Comment by brunod3vs** [comment]
> Another solution is to always start VS Code with the `code` command, i.e. `code .`. So that it will inherit the env from your shell.

this worked for me! Thank you so much!

**Comment by isabellachen** [comment]
I'm on PopOS
Go installation (GOROOT) was installed on `/home/username/go/root/go`
GOPATH was set to `/home/username/go`
PATH variable in .bashrc was appended with `:$HOME/go/root/go/bin:$HOME/go/bin`
setting.json added:

```
 "go.goroot": "/home/username/go/root/go",
 "go.gopath": "/home/username/go"
```

Reason gopath and goroot was set differently was [because we don't want packages from the internet dumped into the official installation](https://groups.google.com/g/golang-nuts/c/U4Erx1_F-bo?pli=1).

**Comment by athenakia** [comment]
> I had this issue and resolved by overriding goroot variable in VSC.
> 
> 1. Shift + Cmd + P
> 2. Search for: "open settings" and choose "Open Settings (JSON)"
> 
> <img alt="Screenshot 2021-09-27 at 11 41 15" width="608" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">
> 
> 3. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").
> 4. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",
>    in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",
> 
> <img alt="Screenshot 2021-09-27 at 11 53 19" width="426" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">
> 
> Good luck!

Paste `/opt/homebrew/opt/go/libexec/` rather than `/opt/homebrew/Cellar/go/x.x.x/libexec` is better or more appropriate. `/opt/homebrew/opt/go/libexec/` is a soft link to go root of current version.

**Comment by source-transformer** [comment]
> My VSCode was fine before, and today the problem just popped up. I just restart my vscode, and problem is solved like magic.

Before you start mucking with your user or workspace settings in vs code - read this answer from @ikingye - i.e. restart vs code.  This worked for me without manually setting the path.

**Comment by liranelisha** [comment]
how come this is close if people still run into this?
i just hot it using `goenv` and tried several different combinations until i realized no matter what i do i'll lose the goenv capabilities, so i might as well remove it and use go without version management

**Comment by lwx599995** [comment]
reboot your machine may work

**Comment by bflad** [comment]
Just ran into this after my macOS workstation was restarted due to (an unrelated) kernel panic and VS Code automatically opened again on boot/login. I'm using Go installed via homebrew. Restarting VS Code resolved the issue.

**Comment by Systemhlp** [comment]
?

**Comment by Edenshaw** [comment]
If you installed Visual Studio Code using flatpak, it won´t load the env variables as you would expect (e.g. Pop OS), so go a head and install VSCode from the official web site instead.

**Comment by codex-corp** [comment]
I spent one hour and does not work on Ubuntu , why why it do not simple like this 

![image](https://user-images.githubusercontent.com/775654/219873976-688167ba-5f21-4eaa-bafc-2e25c5791e6e.png)

**Comment by peitili** [comment]
With Newest VS Code 1.76.0 the settings is split to default, user, and workspace settings, and you might want to change the user settings. Default settings is read-only.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/62725319/222303498-1477b5fc-a3a1-476b-89b8-7cf0519aefdf.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/62725319/222303560-b18a8bee-fc15-44a8-b14a-edcff6d93659.png">

**Comment by lapo-luchini** [comment]
On SteamDeck I used:

```sh
conda install go
```

and then in settings.json:

```json
    "go.alternateTools": {
        "go": "/home/deck/miniconda3/bin/go"
    }
```
… and it works even if flatpak avoid my PATH to be inherited.

**Comment by aesophor** [comment]
🤦🏻

**Comment by rikusen0335** [comment]
I've been using `rtx`, similar to `asdf`. 
I tried most workaround in this issue but they still doesn't fix the issue

I thought my env is right. This is my output from m2 mac:
```
> go env
...
GOPATH="/Users/user/.local/share/rtx/installs/golang/1.20/packages"
GOROOT="/Users/user/.local/share/rtx/installs/golang/1.20/go"
...

> echo $PATH
/Users/user/.local/share/rtx/installs/golang/1.20/go/bin:/Users/user/.local/share/rtx/installs/golang/1.20/packages/bin:...
```

Also set JSON config to:
```json
  "go.gopath": "/Users/user/.local/share/rtx/installs/golang/1.20/go/bin",
  "go.alternateTools": {
    "go": "/Users/user/.local/share/rtx/installs/golang/1.20/go/bin"
  }
```

Reloading code and Restarting pc doesn't fix this too.

**Comment by rikusen0335** [comment]
And though, finally, I installed go with brew (`brew install go`) code loads go fine. What a....

**Comment by BillZong** [comment]
> > It works for me with the config as below, so I don't have to update the config after each `brew upgrade go`.
> > ```json
> > "go.alternateTools": {
> >     "go": "/opt/homebrew/bin/go"
> > }
> > ```
> 
> The above worked for me (thank you @bittopaz), while the previous solution with "go.goroot" gave the following error:
> 
> ![image](https://user-images.githubusercontent.com/30603815/150917896-fe440cdf-143b-4724-9808-f76cb7053662.png)

This is a better idea since we don't need to hard code GOROOT path, which might be change when we upgrade go version.

**Comment by AbbyDeng** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/8296117/232574233-5fc51f8b-f4f8-4971-85a1-b4f54d0efd4b.png">

**Comment by ldemailly** [comment]
On a Mac:
```
sudo ln -s /opt/homebrew/bin/go /usr/bin/go
```
to not have to edit any settings etc

**Comment by JasonLou99** [comment]
Just like above, but you should open workspace settings, then there will be a `.vscode/settings.json` in your work directory.You can set go bin path in that settings.json:
```json
{
    "go.alternateTools": {
        "go": "/home/jason/go/bin/go",
    },
}
```

**Comment by zztaki** [comment]
> I had this issue and resolved by overriding goroot variable in VSC.我遇到了这个问题，并通过覆盖 VSC 中的 goroot 变量解决了这个问题。
> 
> 1. Shift + Cmd + P移位 + 厘米d + P
> 2. Search for: "open settings" and choose "Open Settings (JSON)"搜索：“打开设置”，然后选择“打开设置（JSON）”
> 
> <img alt="Screenshot 2021-09-27 at 11 41 15" width="608" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">
> 
> 3. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").$ go env 和 Copy GOROOT 值（在我的例子中是“/opt/homebrew/Cellar/go/1.17.1/libexec”）。
> 4. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",将新记录添加到 settings.json： “go.goroot”： “copyed/GOROOT/path”，
>    in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",在我的例子中，它是：“go.goroot”： “/opt/homebrew/Cellar/go/1.17.1/libexec”，
> 
> <img alt="Screenshot 2021-09-27 at 11 53 19" width="426" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">
> 
> Good luck! 祝你好运！

Thank you for your help!

**Comment by eitamal** [comment]
For me it failed when I installed go using [rtx](https://github.com/jdx/rtx). I saw antoher comment from someone who didn't manage to get it working with rtx, so just posting my solution (pretty much identical to asdf):
```json
{
    "go.alternateTools": {
        "go": "<home-path>/.local/share/rtx/shims/go",
     }
}
```

**Comment by Adesoji1** [comment]
![Screenshot from 2023-10-27 22-38-40](https://github.com/golang/vscode-go/assets/20457308/7c06fda1-6781-475c-aa1a-ff796ef8b629)
HELP ME

**Comment by mftcodes** [comment]
> I'm on PopOS Go installation (GOROOT) was installed on `/home/username/go/root/go` GOPATH was set to `/home/username/go` PATH variable in .bashrc was appended with `:$HOME/go/root/go/bin:$HOME/go/bin` setting.json added:
> 
> ```
>  "go.goroot": "/home/username/go/root/go",
>  "go.gopath": "/home/username/go"
> ```
> 
> Reason gopath and goroot was set differently was [because we don't want packages from the internet dumped into the official installation](https://groups.google.com/g/golang-nuts/c/U4Erx1_F-bo?pli=1).

I cannot get anything listed above to work for me. Still cannot find GOROOT.
The above seemed the most viable option given I'm on PopOS; however, when using the value from `which go` (`/usr/local/go/bin/`) I get a secondary error:
```
go.goroot setting is ignored. /usr/local/go is not a valid GOROOT directory.
```
I'm out of ideas here...

**Comment by Alan3344** [comment]
> > I had this issue and resolved by overriding goroot variable in VSC.
> > ```
> > 1. Shift + Cmd + P
> > 
> > 2. Search for: "open settings" and choose "Open Settings (JSON)"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screenshot 2021-09-27 at 11 41 15" width="608" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">
> > ```
> > 1. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").
> > 
> > 2. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",
> >    in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screenshot 2021-09-27 at 11 53 19" width="426" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">
> > Good luck!
> 
> Thanks so much @kroksys! I looked up the GOROOT variable with `go env` then copied the value in the settings as you specified.

I restarted my MAC and this error appears every time I open it.
Set these two lines of configuration and open it again to solve the problem successfully.
Thank you so much.

![image](https://github.com/golang/vscode-go/assets/60773912/dc53010f-24a2-40c5-bab0-2926c1aa2cea)

![image](https://github.com/golang/vscode-go/assets/60773912/5b366e5e-ed7f-451f-a245-83d55882c239)

**Comment by TheUncleRemus** [comment]
Hi, if you want I have published the correct guide useful to use `go` with visual-studio-code as IDE, installed by flatpak. You can found the repo at [https://github.com/TheUncleRemus/flapak-vscode-as-go-ide](https://github.com/TheUncleRemus/flapak-vscode-as-go-ide)

**Comment by danurahadi** [comment]
> Hi, if you want I have published the correct guide useful to use `go` with visual-studio-code as IDE, installed by flatpak. You can found the repo at https://github.com/TheUncleRemus/flapak-vscode-as-go-ide

Thanks @TheUncleRemus . This is the solution I'm searching for and also frustrating me. But, I've decided to use GoLand instead. hahhhaa

**Comment by gullitmiranda** [comment]
in my case the problem was the mise/asdf shims. To fix this I just run:
```
mise reshim go
```

The shim symlink before and after:

```shell
la /Users/user/.local/share/mise/shims/go

# before
/Users/user/.local/share/mise/shims/go -> /Users/user/.local/share/mise/shims/go
# after
/Users/user/.local/share/mise/shims/go -> /opt/homebrew/opt/mise/bin/mise
```

**Comment by buitcj** [comment]
manjaro users might attempt installing vscode and the go extension from AUR instead of via flatpak. This worked for me.

**Comment by StrayDragon** [comment]
After some testing, I found that if I configure the go path (GOROOT/PATH) in the .profile file and then log out of the computer or restart and reopen VSCode

The reason might be that VSCode or this plugin does not seem to read the .bash_profile when accessing environment variables. The test results show that it retrieves environment variables through .profile on the user's login side.

Config look like this:
```bash
# in .profile
# ...
export GOROOT=$HOME/go
export PATH=$PATH:$GOROOT/bin
```

**Comment by Adesoji1** [comment]
So what's the solution?

**Comment by bravepickle** [comment]
> For anyone for whom the above steps didn't work: check if you have the flatpak version of vs code/codium installed. It is a sandboxed environment, so it can't access your go tool suite.
> 
> That's what happened to me, so i uninstalled the flatpak and installed the standard version following the instructions [here](https://vscodium.com/), works like a charm :)

I found a solution for setup VSCode with Flatpak. It is quite simple. In my case I needed to change paths in the plugin settings `/usr/local/go` -> `/run/host/usr/local/go`:
```json
{
    "go.goroot": "/run/host/usr/local/go"
}
```
Thats it! The reason for it is rather simple - Flatpak is a sandboxed environment but some paths are shared (or can be shared by adding extra flags) with host environment. In my case GO was installed to its standard path -  `/usr/local/go`, but it it was mounted to `/run/host` folder. More information on permissions and how are they are shared can be read [here](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access). Also it might be helpful to try finding what files are shared and where they are on Flatpak sandbox environment by running command `flatpak run --command=sh com.visualstudio.code`. Alternative for it is to look at terminal in VS Code IDE directly. Good luck!

**Comment by BoscoDomingo** [comment]
For anyone using [mise (formerly rtx)](https://github.com/jdx/mise) the solution is to point to wherever `mise where go` or `which go` says (which should be the mise folder).

However, this will pin it to one specific version due to [what seems like a bug](https://github.com/jdx/mise/issues/2275) (in my case `mise install go@latest` installed 1.23.0 instead of 1.23.1 as of writing, and saved it to `~/.local/share/mise/installs/go/1.23.0`).

To fix this, use the [asdf-golang plugin](https://github.com/asdf-community/asdf-golang) (`mise p i https://github.com/asdf-community/asdf-golang`) which will install it correctly to `~/.local/share/mise/installs/go/latest/go/bin/go` which you can then add to your settings.json:
```json
"go.alternateTools": {
    "go": "~/.local/share/mise/installs/go/latest/go/bin/go"
},
```

**Comment by Md-Kasali** [comment]
> For anyone for whom the above steps didn't work: check if you have the flatpak version of vs code/codium installed. It is a sandboxed environment, so it can't access your go tool suite.
> 
> That's what happened to me, so i uninstalled the flatpak and installed the standard version following the instructions [here](https://vscodium.com/), works like a charm :)

I'm a Linux user. I followed your instructions and it works. This made my day. Thank you so much.

**Comment by DigiConvent** [comment]
So just to be sure, I enter "go env | grep GOROOT" in my terminal and copy that value into go.goroot into the vscode settings?

**Comment by starxchina** [comment]
remote link to ubuntu 22.04, and I finally got success through these steps:
install go in `/usr/lcoal`, like this:
~~~shell
/usr/local ❯ ls go                                                                                                                                                                          
api  bin  codereview.cfg  CONTRIBUTING.md  doc  go.env  lib  LICENSE  misc  PATENTS  pkg  README.md  SECURITY.md  src  test  VERSION

/usr/local ❯ echo "export PATH=\$PATH:/usr/local/go/bin" >> /etc/profile
/usr/local ❯ source /etc/profile
/usr/local ❯ go version
~~~

**Comment by pgollucci** [comment]
All of this is daft and still broken in 2024.

My PATH is correct. I used brew to install VS Code. I used code -n to start vscode.
I'm using goenv. The shim is in my path.

```bash
GOENV_ROOT=$HOME/.p6/syndbg/goenv
GOENV_SHELL=zsh
GOROOT=$HOME/.p6/syndbg/goenv/versions/1.23.2
GOPATH=$HOME/go/1.23.2

$ go version; which go
go version go1.23.2 darwin/arm64
$HOME/.p6/syndbg/goenv/shims/go
```

**Comment by dwrolvink** [comment]
Specifically for using vscode on Windows, using Remote-SSH to connect to a RHEL9 VM. The solution for me was this: https://stackoverflow.com/a/62391678

I.e.: Press F1 or ctrl+shift+p and choose: `Remote-SSH: Kill VS Code Server on Host`. Then F1 and choose: `Reload Window`. This gets the server to reload the PATH (assuming you have this configured in your ~/.bashrc or similar file).

**Comment by begin2023** [comment]
> I had this issue and resolved by overriding goroot variable in VSC.我遇到了这个问题，并通过覆盖 VSC 中的 goroot 变量来解决。
> 
> 1. Shift + Cmd + P
> 2. Search for: "open settings" and choose "Open Settings (JSON)"搜索：“open settings”并选择“Open Settings （JSON）”
> 
> <img alt="Screenshot 2021-09-27 at 11 41 15" width="608" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">
> 
> 3. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").$ **go env** 并复制 **GOROOT** 值（在我的例子中是 “/opt/homebrew/Cellar/go/1.17.1/libexec”）。
> 4. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",向settings.json添加新记录： “go.goroot”： “Copied/GOROOT/path”，
>    in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",在我的例子中是：“go.goroot”： “/opt/homebrew/Cellar/go/1.17.1/libexec”，
> 
> <img alt="Screenshot 2021-09-27 at 11 53 19" width="426" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">
> 
> Good luck!  祝你好运！

thanks

**Comment by volmedo** [comment]
I'm not sure what happens with the fix above when the Go installation is upgraded, as the `/opt/homebrew/Cellar/go/1.17.1/libexec` contains the version.

An alternative that worked for me was to close the VSCode window and launch it from a terminal (just `code <repo_dir>`) where the environment was correct. I guess VSCode inherits the env from the terminal and works. Not great, I know, but simple enough.

**Comment by unlimitedcodeG** [comment]
> I had this issue and resolved by overriding goroot variable in VSC.
> 
> 1. Shift + Cmd + P
> 2. Search for: "open settings" and choose "Open Settings (JSON)"
> 
> <img alt="Screenshot 2021-09-27 at 11 41 15" width="608" src="https://user-images.githubusercontent.com/15876796/134876316-1b4fa926-ae95-4b16-81b7-669650ce1e45.png">
> 
> 3. $ **go env** and  Copy **GOROOT** value (in my case its "/opt/homebrew/Cellar/go/1.17.1/libexec").
> 4. add new record to settings.json: "go.goroot": "Copied/GOROOT/path",
>    in my case its: "go.goroot": "/opt/homebrew/Cellar/go/1.17.1/libexec",
> 
> <img alt="Screenshot 2021-09-27 at 11 53 19" width="426" src="https://user-images.githubusercontent.com/15876796/134876673-c4c21405-02c3-40fd-a09a-b34365f1035a.png">
> 
> Good luck!

This is nice solution for my MacOs Thank You@！

**Comment by cyy-web** [comment]
in my case, I'm not able to find the 'open setting(JSON)', so I use UI to complete this part.

by click
file->preference->settings

expand extensions, find Go

and there is a GOROOT section

<img width="329" alt="Image" src="https://github.com/user-attachments/assets/f8f9981f-8fa3-47b0-a4b7-5d56502bcec1" />

then click edit, add `"go.goroot":"the path of GOROOT in 'go env' result"`

**Comment by parmcoder** [comment]
In my case, I fixed it by simply restarting VS Code (quit it or kill it).

If that does not help, then edit your `go.goroot` as suggested by earlier replies 😄 .

**Comment by magicdawn** [comment]
extension or vscode should integrate [fix-path](https://github.com/sindresorhus/fix-path?tab=readme-ov-file)

**Comment by k3mist** [comment]
im currently experiencing this issue trying to figure out a solution that does not involve manually maintaining the plugin go paths. crazy this is an issue at all. why is the plugin not using the environment to infer the paths?

**Comment by ugifractal** [comment]
I followed @unlimitedcodeG 
I created `.vscode/settings.json` under root of project.

And put this code

```json
{
  "go.goroot": "/opt/homebrew/Cellar/go/1.24.5/libexec"
}
```

**Comment by nickma82** [comment]
With vscode installed as Flatpak on Ubuntu I had to  ( thx @bravepickle and @kroksys )

Enable VSCode's access to the Host-Installation of Go
1. Get the GOROOT - `go env GOROOT`  (in my case `/usr/lib/go-1.22`)
1. Grant access to the Host-Installation of Go 
    `flatpak override --user --filesystem=/usr/bin --filesystem=$(go env GOROOT) com.visualstudio.code`
2. Verify the premission just given - 
     lookup `flatpak override --user --show com.visualstudio.code`

Tell VSCode where to find go (not in the flatpak installation but on the hostOS)
1.  Shift + Cmd + P
2. Search for: "Open User/Workspace Settings" and choose "Open Settings (JSON)"
3.  Make an entry in the settings.json providing your GOROOT path prefixed with `/run/host/`
(in my case it looks like this)
```
{
  "go.goroot": "/run/host/usr/lib/go-1.22",
}
```

**Comment by filip-dahlberg** [comment]
To solve it, I had to create a symlink .go-current which points to golang set by gvm. 

Entry added to user settings of vs code:
```json
"go.goroot": "<home>/.go-current",
```


I then dynamically set the symlink as on shell load:
```shell
#!/bin/bash

# Assumes gvm is already sourced in the shell
# Get current GVM Go version
GVM_CURRENT=$(gvm list | grep '=>' | awk '{print $2}')

if [[ -z "$GVM_CURRENT" ]]; then
  echo "No GVM Go version selected"
  exit 1
fi

# Make symlink point to the current GOROOT
GOROOT_PATH="$HOME/.gvm/gos/$GVM_CURRENT"
ln -sfn "$GOROOT_PATH" "$HOME/.go-current"

echo "GOROOT symlink set to $GOROOT_PATH"
```

**Comment by frankli0324** [comment]
for me somehow updating Apple Command line tools triggered the issue and running the included `clang` fixed it
I'm using homebrew installed go so it's located under `/opt/homebrew`

**Comment by oappi** [comment]
i got this error running vs code in fedora. Reason for it is that i was running it with flatpak. Removed flatpak vs code and installed it with instructions found in vs code homepage. Basically adding yum repository and installing it again with yum. After that go worked flawlessly.

I am sure I could get it working inside flatpak as well, but I rather run it natively, especially when i am using devcontainers. Having too many layers just makes my head hurt

**Comment by Danny5487401** [comment]
```shell
$ go env GOROOT
/Users/python/.g/go
$ cat /Users/python/Library/Application\ Support/Code/User/settings.json | grep go.goroot
  "go.goroot": "/Users/python/.g/go
```
would be ok

**Comment by luca147** [comment]
2026 and this issue persist :(

**Comment by frankli0324** [comment]
it might be worth to mention that if you start vscode from launchpad in macOS, it won't inherit your PATH variable defined in your rc file (.zshrc etc.). In that case it's actually not a bug.

**Comment by zeroflucs-adam-bishop** [comment]
I got this issue after a go upgrade and restarting mac with 'remember open windows'.  Quit and restart vscode resolved it

**Comment by yangjuncode** [comment]
so bad it can't find goroot,  when i install go with vfox

**Comment by herberthobregon** [comment]
Don't use `brew` or similar, use the official page installer https://go.dev/doc/install

**Comment by gjantsch** [comment]
I'm getting a 
```
go.goroot setting is ignored. /opt/homebrew/Cellar/go/1.26.1/libexec/bin/go is not a valid GOROOT directory.
```
after update the goroot on json settings.

**Comment by perkyquirky** [comment]
On Fedora Silverblue (Bazzite) I was able to get on VS Codium it working with:

"go.goroot": "/var/home/linuxbrew/.linuxbrew/Cellar/go/1.27.0/libexec",

<img width="835" height="296" alt="Image" src="https://github.com/user-attachments/assets/106ca711-e0b4-47fc-a085-17c104ec670b" />
