### ISSUE TITLE
golint: failed to install golint(golang.org/x/lint/golint): Error: spawn bin/go ENOENT undefined  

### ISSUE THREAD

**Issue by dragonDScript** [golang/vscode-go#972]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go1.15.5 linux/amd64
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).
	- zsh: command not found: gopls
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.51.1
e5a624b788d92b8d34d1392e4c4d9789406efe8f
x64
- Check your installed extensions to get the version of the VS Code Go extension
	- 19.0.0
- Run `go env` to get the go development environment details
	-GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dragon/.cache/go-build"
GOENV="/home/dragon/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/dragon/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/dragon/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/snap/go/6727"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/snap/go/6727/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build561784054=/tmp/go-build -gno-record-gcc-switches"

## Vscode configuration
```json
{
    "workbench.settings.editor": "json",
    "terminal.integrated.shell.windows": "C:\\windows\\System32\\cmd.exe",
    "discord.detailsIdle": "Ausente",
    "discord.detailsEditing": "Editando {filename}, con un total de lineas de {totallines}",
    "discord.detailsDebugging": "Depurando {filename}",
    "discord.largeImage": "Editando un archivo {LANG}",
    "discord.largeImageIdle": "Ausente",
    "discord.lowerDetailsDebugging": "Depurando {workspace}",
    "discord.lowerDetailsIdle": "Ausente",
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "[dart]": {
        "editor.formatOnSave": true,
        "editor.formatOnType": true,
        "editor.rulers": [
            80
        ],
        "editor.selectionHighlight": false,
        "editor.suggest.snippetsPreventQuickSuggestions": false,
        "editor.suggestSelection": "first",
        "editor.tabCompletion": "onlySnippets",
        "editor.wordBasedSuggestions": false
    },
    "dart.openDevTools": "always",
    "dart.flutterSdkPath": "C:\\src\\flutter",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "liveshare.increasedGuestLimit": false,
    "editor.fontLigatures": true,
    "workbench.editorAssociations": [
        {
            "viewType": "hexEditor.hexedit",
            "filenamePattern": "*.sqlite3"
        },
        {
            "viewType": "imagePreview.previewEditor",
            "filenamePattern": "*.png"
        }
    ],
    "breadcrumbs.enabled": true,
    "python.languageServer": "Pylance",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "scm.defaultViewMode": "tree",
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "[html]": {
    },
    "files.exclude": {
        "**/node_modules": true
    },
    "[javascript]": {
        "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "codestream.email": "agomila96@gmail.com",
    "extensions.ignoreRecommendations": false,
    "terminal.integrated.fontFamily": "Consolas, 'Courier New', monospace",
    "terminal.external.windowsExec": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "terminal.integrated.rendererType": "canvas",
    "cmake.configureOnOpen": true,
    "editor.suggestSelection": "first",
    "diffEditor.codeLens": true,
    "editor.renderControlCharacters": true,
    "editor.tabSize": 2,
    "eslint.alwaysShowStatus": true,
    "eslint.format.enable": true,
    "merge-conflict.autoNavigateNextConflict.enabled": true,
    "files.associations": {
        "Procfile": "yaml"
    },
    "window.zoomLevel": 0,
    "screencastMode.onlyKeyboardShortcuts": true,
    "zenMode.hideActivityBar": false,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "go.gopath": "/snap/bin/go",
    "go.enableCodeLens": {
        "references": true,
        "runtest": true
    },
    "go.useLanguageServer": true,
    "go.useGoProxyToCheckForToolUpdates": false,
    "editor.fontSize": 16,
    "workbench.colorTheme": "Darcula",
    "editor.fontFamily": "JetBrains Mono, Regular",
    "search.showLineNumbers": true,
    "editor.lineNumbers": "relative"
}
```

## Describe the bug
Go should have installed golint. Instead, it's outputting golint: failed to install golint(golang.org/x/lint/golint): Error: spawn bin/go ENOENT undefined

### Steps to reproduce the behavior:
1. Install the go extension without golint on a linux with zsh machine
2. Install golint
3. See error

**Comment by hyangah** [comment]
@dragonDScript Can you share your vscode settings? There is an outstanding issue related to snap (which unfortunately I couldn't reproduce in my latest snap installation) which causes failure of locating the go binary. Some snap users are working around the issue by configuring the go path from the setting like https://github.com/golang/vscode-go/issues/166#issuecomment-688000742.

**Comment by dragonDScript** [comment]
> @dragonDScript Can you share your vscode settings? There is an outstanding issue related to snap (which unfortunately I couldn't reproduce in my latest snap installation) which causes failure of locating the go binary. Some snap users are working around the issue by configuring the go path from the setting like [#166 (comment)](https://github.com/golang/vscode-go/issues/166#issuecomment-688000742).

Whey hyangah. I have edited the github issue and there it is. Thank you.

**Comment by hyangah** [comment]
Thanks. @dragonDScript Can you try to change the workaround setting (and reload the window)

```
"go.alternateTools": {
    "go": "/snap/go/current/bin/go"
}

```

And, please unset `"go.gopath"` from your current settings - that is to configure `GOPATH` environment variable and `/snap/bin/go` is not the right value.

**Comment by dragonDScript** [comment]
> Thanks. @dragonDScript Can you try to change the workaround setting (and reload the window)
> 
> ```
> "go.alternateTools": {
>     "go": "/snap/go/current/bin/go"
> }
> ```
> 
> And, please unset `"go.gopath"` from your current settings - that is to configure `GOPATH` environment variable and `/snap/bin/go` is not the right value.

I have a new error now:
Cannot install Go tools. Set either go.gopath or go.toolsGopath in settings.

And, yes, I have the go.alternateTools setting set already.

**Comment by hyangah** [comment]
@dragonDScript Before installing any tools, can you please run  "Go: Locate Configured Go Tools" command first to verify the extension detected the go and share the output?  I don't see `go.alternateTools` setting in your setting above.

The `"go.gopath"` or `"go.toolsGopath"` should be the directory path for which you should have write permission. If none of them are set, the go should default to `/home/dragon/go` but it sounds like the go command doesn't succeed at all.

**Comment by dragonDScript** [comment]
> @dragonDScript Before installing any tools, can you please run "Go: Locate Configured Go Tools" command first to verify the extension detected the go and share the output? I don't see `go.alternateTools` setting in your setting above.
> 
> The `"go.gopath"` or `"go.toolsGopath"` should be the directory path for which you should have write permission. If none of them are set, the go should default to `/home/dragon/go` but it sounds like the go command doesn't succeed at all.

This is my output:
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: undefined
GOROOT: 
PATH: bin:/home/dragon/.cargo/bin:/home/dragon/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dragon/nvim.appimage

cached Go version ({"binaryPath":"/snap/bin/go","version":""}) is invalid, recomputing
unable to determine version from the output of "/snap/bin/go version": "undefined"
   gocode: gocode not installed
   gopkgs: gopkgs not installed
   go-outline: go-outline not installed
   go-symbols: go-symbols not installed
   guru: guru not installed
   gorename: gorename not installed
   gotests: gotests not installed
   gomodifytags: gomodifytags not installed
   impl: impl not installed
   fillstruct: fillstruct not installed
   goplay: goplay not installed
   godoctor: godoctor not installed
   dlv: dlv not installed
   gocode-gomod: gocode-gomod not installed
   godef: godef not installed
   goreturns: goreturns not installed
   golint: golint not installed
   gopls: gopls not installed

go env
Workspace Folder (backend): /media/dragon/Archivos/Marcados/backend
	
(I have some of them installed manually)

Looks like a read/write permission or, as you say, a wrong setting.

What should gopath be? My project's directory?

**Comment by hyangah** [comment]
@dragonDScript It looks like your `go.alternateTools` setup configuration was properly done - it's still pointing to `/snap/bin/go`. Please verify your settings and check you have the `"go.alternateTools": { "go": "/snap/go/current/bin/go" }` section in your settings.json.

**Comment by dragonDScript** [comment]
> @dragonDScript It looks like your `go.alternateTools` setup configuration was properly done - it's still pointing to `/snap/bin/go`. Please verify your settings and check you have the `"go.alternateTools": { "go": "/snap/go/current/bin/go" }` section in your settings.json.

Updated, now it works, thanks!
