### ISSUE TITLE
debug: escape hatch for arbitrary dlv flags

### ISSUE THREAD

**Issue by polinasok** [golang/vscode-go#978]
Dlv has the following command-line arguments: https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv.md#options. For some we have `launch.json` equivalents that [are mapped by the debug adapter](https://github.com/golang/vscode-go/blob/3493cfee14f3b8b1250681c69a7faf7a32c72e5a/src/debugAdapter/goDebug.ts#L600).  In particular,
* `showLog` =>  `--log`
* `logOutput` => `--log-output`
* `init` => `--init`
* `backend` => `--backend`
* `output` => `--output`

For the rest, the only option the users have is to launch an instance of `--headless` delve from the terminal and then vscode and `launch.json` to connect to it. This is especially annoying for newly added flags based on popular demand (e.g. #810). We might or might not want to keep up with all the flags in our mapping, but in addition we should add an arbitrary string field to specify whatever flags users want to add to the dlv command as-is.

Related points that probably deserve their own issues:
- The above property-to-dlv-flag mapping should be made clear by the property comments in `package.json`, especially if we add an arbitrary option, so there are no surprises when users specify the same flag via both ways.
- With dlv-dap, we have an opportunity to revisit the names and conventions - should we follow the same pattern as we do for the existing adapter?

**Comment by hyangah** [comment]
I encountered this issue while testing go1.16 beta - we need to pass `--check-go-version=false` to test go1.16 beta now.

**Comment by hyangah** [comment]
v0.21.0 will have `dlvFlags` attributes.
