### ISSUE TITLE
debug: unhandled promise rejection error

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#982]
Reported by a user in the gopher slack

Extension version: v0.19.0

```
(node:77378) UnhandledPromiseRejectionWarning: TypeError: Cannot read property ~/be_game_platform' of undefined
    at Delve.<anonymous> (/Users/admin/.vim/plugged/vimspector/gadgets/macos/download/vscode-go/0.19.0/root/extension/dist/debugAdapter.js:24441:85)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/admin/.vim/plugged/vimspector/gadgets/macos/download/vscode-go/0.19.0/root/extension/dist/debugAdapter.js:24139:58)
(node:77378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:77378) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. (edited) 
```

The rejection was caused by the code https://github.com/golang/vscode-go/blob/e8d462e3ae4a7ad44ac70640b14118e30c0a1ef3/src/debugAdapter/goDebug.ts#L592

For some reason that I don't understand, we probably ended up with `undefined` `launchArgs.packagePathToGoModPAthMap`.  Check how this happened, and also make the code path more robust.

/cc @quoctruong @suzmue

**Comment by suzmue** [comment]
I was unable to reproduce this and unsure what could be causing packagePathToGoModMap to be undefined. We added a check so it will not crash if this happens. 

If you encounter this error again, please comment on this issue with information about your debugging setup!
