### ISSUE TITLE
settings: invalid link in the settings description

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#986]
Extension: Nightly 2020.11.3021
Links in the Settings (UI) for gopls settings are incorrect. For example,  the link associated with `here` in gopls.analyses is `/analyzers.md` which is invalid.
![Screen Shot 2020-12-01 at 3 30 22 PM](https://user-images.githubusercontent.com/4999471/100793472-23262b80-33ea-11eb-8f43-af6700bd015f.png)

**Comment by stamblerre** [comment]
Will be fixed in https://golang.org/cl/280355.
