### ISSUE TITLE
problem in Go: Alternate Tools , Edit in setting.json

### ISSUE THREAD

**Issue by Niru-godev** [golang/vscode-go#998]
Issue Type: <b>Bug</b>

I am not able to run my code as I have made some change in "Go: Alternate Tools , Edit in setting.json", which I am not able to reset to default. Need help in restting this.

Extension version: 0.19.0
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.84GB (1.00GB free)|
|Process Argv|--crash-reporter-id 823202f2-7f9d-4743-a3f6-03332333e83c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by stamblerre** [comment]
The default value of `go.alternateTools` is empty. You can access and clear your settings by opening the Command Palette (Ctrl+Shift+P) and selecting "Preferences: Open Settings (JSON)" or "Preferences: Open Settings (UI)".

**Comment by hyangah** [comment]
@Niru-godev Thanks for contacting us. If there are any more questions or issues, please use https://gophers.slack.com `#vscode` channel, or file a new issue.
